### ISSUE TITLE
feature request: RG entry for bam output

### ISSUE THREAD

**Issue by avilella** [FelixKrueger/Bismark#1]
Recent versions of samtools and other toolkits require the RG line in the header.

This is a feature request for bismark to have an option (or default) to include an RG line in the header, something like so:

```
-R "@RG\tPL:ILLUMINA\tID:ID\tSM:SAMPLE"
```

Thx

**Comment by FelixKrueger** [comment]
I have added an option --rg_tag to print an @RG header line as well as and RG:Z: tag to each read. The ID and SAMPLE fields default to 'SAMPLE', but can be specified manually with --rg_id or --rg_sample.

**Comment by avilella** [comment]
![borat-thumbs-up](https://cloud.githubusercontent.com/assets/158007/11398125/945c23fa-9376-11e5-8811-ee3d4110dd69.jpg)

**Comment by FelixKrueger** [comment]
resolved, seems to work.
