### ISSUE TITLE
Coverage result

### ISSUE THREAD

**Issue by ewels** [FelixKrueger/Bismark#10]
Does bismark already know the number of cytosines within the reference genome? It would be nice to print this, along with the average observation coverage within different contexts if so.

**Comment by FelixKrueger** [comment]
No it doesn't actually. The right place to look at this would be the `bismark2bedGraph` step I guess, maybe once the coverage files have been written out one could calculate a few stats on the coverage, is that what you had in mind?

**Comment by ewels** [comment]
Yeah I guess. It's just something I find myself doing frequently after processing. Especially with non-model organisms, where reference size can have a large effect on coverage. I was thinking it would be useful if bismark gave the read coverage and / or cytosine coverage in the log files to save me from having to figure it out :grin: 

Problem with adding it to `bismark2bedGraph` is that it involves an extra step with output files which would have to be deleted. I could also make myself a helper script I guess. Just calculated the number of cytosines in the reference using the following one-liner:
```
grep -v ">" | fgrep -o C genome.fa | wc -l
```
Wouldn't be _so_ hard to write a short script which calculates these stats I guess. I was just hoping you had the numbers in memory already.

**Comment by FelixKrueger** [comment]
No these numbers are not actually held in memory at anywhere, so someone would have to write something there...

**Comment by FelixKrueger** [comment]
Phil seems to be have found a solution, closing this for now.
