### ISSUE TITLE
question about mbias ?

### ISSUE THREAD

**Issue by hxlei** [FelixKrueger/Bismark#100]
For my special needs , I extract read pairs whose read1 has adapter from a bam file (directional) and generate a new sub_bam file. Then I draw a mbias plot using excel for sub-bam.  
But to my surprise, the average methylation level (CpG) of read2 is more than 70% while the average methylation level of read1 is only about 30% except bias part.  The mbias plot for original bam (and the bam which equals original bam - sub_bam ) looks good.  Methylation level is between 35% ~40% for read1 and read2. 
Then I use MethylDackel [https://github.com/dpryan79/MethylDackel](url) for sub_bam to plot mbias. The methylation level is between 35% ~40% for read1 and read2 except bias part (only OT and OB). I am confused totally.

Here is samtools flagstat for **original bam file**:
33116044 + 0 in total (QC-passed reads + QC-failed reads)
0 + 0 secondary
0 + 0 supplementary
0 + 0 duplicates
33116044 + 0 mapped (100.00% : N/A)
33116044 + 0 paired in sequencing
16558022 + 0 read1
16558022 + 0 read2
33116044 + 0 properly paired (100.00% : N/A)
33116044 + 0 with itself and mate mapped
0 + 0 singletons (0.00% : N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)

Here is flagstat for **sub_bam file**:
6684814 + 0 in total (QC-passed reads + QC-failed reads)
0 + 0 secondary
0 + 0 supplementary
0 + 0 duplicates
6684814 + 0 mapped (100.00% : N/A)
6684814 + 0 paired in sequencing
3342407 + 0 read1
3342407 + 0 read2
6684814 + 0 properly paired (100.00% : N/A)
6684814 + 0 with itself and mate mapped
0 + 0 singletons (0.00% : N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)

I notice that in M-bias.txt generated by bismark extractor,  the coverage (CpG) of R1 and R2  differs greatly.
Here is part of sub_bam M-bias.txt: 
CpG context (R1)
position        count methylated        count unmethylated      % methylation   coverage
1       11137   27815   28.59   38952
2       15764   27754   36.22   43518
3       18209   29884   37.86   48093
4       20658   35103   37.05   55761
5       16340   34528   32.12   50868
6       15304   30968   33.07   46272
7       13798   28317   32.76   42115
8       13544   28334   32.34   41878
9       19622   41264   32.23   60886
10      26533   64258   29.22   90791
11      14148   29361   32.52   43509
12      27912   59009   32.11   86921
13      19279   37846   33.75   57125
14      29211   62620   31.81   91831
15      20512   48203   29.85   68715
... ...
CpG context (R2)
position        count methylated        count unmethylated      % methylation   coverage
1       1230    3203    27.75   4433
2       311     1084    22.29   1395
3       556     1067    34.26   1623
4       530     1192    30.78   1722
5       631     1136    35.71   1767
6       573     1267    31.14   1840
7       495     1173    29.68   1668
8       534     906     37.08   1440
9       482     954     33.57   1436
10      1645    609     72.98   2254
11      2337    771     75.19   3108
12      1295    423     75.38   1718
13      2121    613     77.58   2734
14      1509    484     75.72   1993
15      2358    683     77.54   3041
16      1619    554     74.51   2173
17      1509    490     75.49   1999
18      1583    489     76.40   2072
19      1605    452     78.03   2057

The 9bp of read2 5' is expected because of repair.
Thank you very much for some advise.

**Comment by FelixKrueger** [comment]
I'm sorry I don't seem to completely understand what the issue is here. Are you saying that the M-bias profiles look very different for R1 and R2 between the original BAM file and the sub-bam files? Do the MethylDackel and Bismark M-bias plot look the same?

**Comment by realzhang** [comment]
> 

MethylDackel plots M-bias in a different way than Bismark, by discriminating OT and OB strand. Further more， MD uses a autoscale for the Y axis (mC%), while Bismark use full scale (0-100), which makes the bias not so obvious as MD does.

As to the bias levels of sub-bam between R1 and R2, I've no idea about it.

**Comment by FelixKrueger** [comment]
Thanks for the info. I would assume that OB and OT strands should pretty much always look the same. If I am not mistaken the y axis of the M-bias plots can be resized in interactive reports of the Bismark html report or the MultiQC report?
