### ISSUE TITLE
Bismark bam2nuc not reading samtools

### ISSUE THREAD

**Issue by BeeDoctor** [FelixKrueger/Bismark#101]
Hello, 

When I run bam2nuc, I get an error message stating "Can't exec "samtools": No such file or directory at /opt/bismark_v0.17.0/bam2nuc line 255.
No such file or directory at /opt/bismark_v0.17.0/bam2nuc line 255."
Samtools has worked up to this point with bismark and bismark_methylation_extractor. I'm using samtools 1.3.1. 

Thanks,
BeeDoctor

**Comment by FelixKrueger** [comment]
Do you have `samtools` in the PATH environment? When you type `samtools` on the command line, do you see the command options come up? 
One option could be to edit `bam2nuc` directly to replace 'samtools' with `/your/path/to/samtools`, or alternatively I could add an option where you can specifiy the path to Samtools yourself it is not in the PATH.

**Comment by BeeDoctor** [comment]
There was an issue with the path to Samtools in my directory, thank you for helping!

**Comment by FelixKrueger** [comment]
Excellent! All the best
