### ISSUE TITLE
Change FindBin to RealBin so that commands also work with symlinks

### ISSUE THREAD

**Issue by FelixKrueger** [FelixKrueger/Bismark#103]
The issue came up during the methylation course where bismark2report had been a symlink, but it should be changed for all modules of the Bismark suite.

**Comment by ewels** [comment]
Sounds like a great idea! 😉

**Comment by ewels** [comment]
Just a case of find+replace I think. See https://github.com/ewels/clusterflow/commit/cc4b8efb641886405debe2612542eb532d4d1592

**Comment by FelixKrueger** [comment]
Thought you might like it. In fact I was only waiting for it to come and bite me as well :P
