### ISSUE TITLE
Allow merging of mapped datasets for deduplication?

### ISSUE THREAD

**Issue by FelixKrueger** [FelixKrueger/Bismark#107]
Can we explore the possibility to supply several BAM files to `deduplicate_bismark` so that they are treated as one big file? This might be a useful feature when the same sample gets sequenced several times to increase read depth, and be an alternative to going back and merging at the FastQ stage.

**Comment by FelixKrueger** [comment]
I have now added an option `--multiple` to the deduplicator to treat several input SAM/BAM files as the same sample. 285f46ef5e6300f01f2e6e09221eddcb6f4c5557. 

It seems to work well for SAM/BAM files with BAM or SAM output. CRAM not tested yet.

**Comment by xiuru** [comment]
Hi Felix, 
Can you add a new flag like 'prefix' to deduplicate_bismark? When i treat multi bam files together, i prefer to use 'prefix' to name the output files.

**Comment by FelixKrueger** [comment]
Can't you just do something like:
`mv multiple.bam prefix` 
once the deduplication is complete?

**Comment by xiuru** [comment]
Yes, i did it in this way. Sorry for my stupid question :)
