### ISSUE TITLE
unknown error with newer versions of Bismark

### ISSUE THREAD

**Issue by shawpa** [FelixKrueger/Bismark#109]
I am having a strange issue that I cannot figure out how to resolve with the newer versions of Bismark. My system has 1 head compute node and 2 sub-nodes. I am able to run Bismark on the head node with no issues. However, when I try and run it on the sub-node I keep getting an error. 

Attempt to free unreferenced scalar: SV 0x57496f0, Perl interpreter: 0x557b010 at /usr/lib/perl5/5.8.8/FindBin.pm line 101.
Segmentation fault

I get this error even if I just try and get Bismark to output its version. I am trying to use the current version (18.1). I also still have a very old version of Bismark loaded (13). I am able to run this version on the sub-node. I don't think this is a brand new issue because I get the same error with v17 of Bismark too. 

Running an outdated version doesn't seem like a good option and I need to be able to access more computing cores for the amount of data that has been generated. I would really appreciate it if anyone could offer any type of suggestions on how to get this to work. 

Thanks, 

Annie Shaw

**Comment by s-andrews** [comment]
That looks like your copy of perl on your compute node is broken.  What happens if you try to run:

```
perl -MFindBin -e 'print $FindBin::RealBin'
```

..on the compute node.  Does that break too?

**Comment by ewels** [comment]
Version 5.8.8 of Perl is also really old - release date was June 2002. It's probably a good idea to update anyway..

**Comment by ewels** [comment]
There's a post on this error and how to fix it at PerlMonks here: http://www.perlmonks.org/?node_id=1089524

**Comment by shawpa** [comment]
Yes that command fails too on the compute node.

**Comment by s-andrews** [comment]
So from what Phil posted it looks like you might get away with just re-installing the FindBin package on the compute nodes.  It looks like you're referencing a binary component compiled against a different verison of perl.

By any chance are the versions of perl on your head and compute nodes different?  Might you also be sharing a module directory between them?  If so then this will break all modules with a binary component.

If not you could try to fix this with:

```
sudo perl -MCPAN -e 'install FindBin'
```

..on the compute node to see if that will update the FindBin package to one which matches your current version.

**Comment by shawpa** [comment]
Thank you so much for your prompt feedback. I am going to pass this information along to the person who maintains the system to see what might be doable. I was truly stumped.
