### ISSUE TITLE
Bismark multicore crashes

### ISSUE THREAD

**Issue by btc** [FelixKrueger/Bismark#111]
I'd like to speed up my bismark runs, but I need to run the methylation extractor on the output. I suppose this means I need to produce Sam from bismark. However, the multicore option requires bam formatting. Does the methylation extractor support bam?

Is there an elegant way to achieve my objective of speeding up bismark? I'm using 16.3

**Comment by FelixKrueger** [comment]
Yes, the methylation extractor is happy to accept BAM format, so you should be able to use a higher value of `--parallel` (the former option `--multicore`) as long as you have enough system resources (please read the `--help` text as a guideline). A value of 2 should cut the time in half, 4 to ~25% etc.

**Comment by btc** [comment]
Hi Felix. I tried the multicore option using version 16.3. However, the process crashes midway through without any error messages. Is there a known fault in this version? I am able to successfully run the program sequentially.

**Comment by FelixKrueger** [comment]
Hmm, when Bowtie2 crashes with signal PIPE it often means that you are running out of memory. How much memory have you got, and which value did you specify for `--multicore`? 
Keep in mind that each value increases the memory by ~12GB for a standard human genome alignment (or ~18GB for non-directional alignments, but I don't know which genome or alignment mode you went for). Could you elaborate on this?

**Comment by btc** [comment]
I allocated 255 GB (15 GB per processor) and 17 processors and ran bismark with `--multicore 16`. 

I have logs that tell me the max amount of memory utilized by the job. These logs show that the jobs are using between 60 GB and 120 GB. There's still quite a bit of headroom.

I updated to Bismark 18.1 and Bowtie2 2.3.2 and I still get the same crash. Now there's an error message though:

```
(ERR): bowtie2-align died with signal 13 (PIPE)
(ERR): bowtie2-align died with signal 13 (PIPE)
(ERR): bowtie2-align died with signal 13 (PIPE)
(ERR): bowtie2-align died with signal 13 (PIPE)
(ERR): bowtie2-align died with signal 13 (PIPE)
(ERR): bowtie2-align died with signal 13 (PIPE)
(ERR): bowtie2-align died with signal 13 (PIPE)
(ERR): bowtie2-align died with signal 13 (PIPE)
(ERR): bowtie2-align died with signal 13 (PIPE)
(ERR): bowtie2-align died with signal 13 (PIPE)
(ERR): bowtie2-align died with signal 13 (PIPE)
(ERR): bowtie2-align died with signal 13 (PIPE)
```

**Comment by FelixKrueger** [comment]
This is normally the out of memory warning. Which genome are you working with? and couldn't you start with something a bit more modest than `--multicore 16`, such as 2, or 4?

By the way, Bismark does itself use  one core for Bismark itself, and at least 2 more cores for the Bowties (4 more in non-directional mode), plus a few additional cores at a lower percent for gzip and samtools streams...). So as a ball park you would need at least 48 free cores and ~240GB or memory for this run (for a mouse genome), way more for a larger genome.

**Comment by btc** [comment]
hg19

> and couldn't you start with something a bit more modest than --multicore 16, such as 2, or 4?

Jobs that requires 6 hours or more are relegated to a low priority queue. I need each job to finish within 5 hours 59 minutes if I want them scheduled in a timely manner.

I will try running with a more modest value for multicore and report back.

**Comment by btc** [comment]
`--multicore 8` with 16 processors and 240 GB failed after about 2.5 hours. I'm convinced this is not OOM at this point. Not sure what to think.

```
Job 5816645 (bismark) Aborted
 Exit Status      = 141
 Signal           = PIPE
 Start Time       = 06/06/2017 14:55:40
 End Time         = 06/06/2017 17:38:10
 CPU              = 03:23:43
 Max vmem         = 65.927G
failed assumedly after job because:
job 5816645.1 died through signal PIPE (13)
```

**Comment by FelixKrueger** [comment]
Maybe it has to do with the fact that you are using specific temp, output and input folders with path information. What does the error log say? You can also email it to me so I can take a look if you prefer.

**Comment by btc** [comment]
multicore 8: https://gist.github.com/b06979b50b8873f6746d0c391e0b1c2d

multicore 16: https://gist.github.com/8fcf16fea880f4e49e7cd2a8df81baf2

**Comment by FelixKrueger** [comment]
All seems to work fine until the alignments kick off, and then Bowtie2's start dieing with `(ERR): bowtie2-align died with signal 13 (PIPE)` which typically is a memory issue. Can't you ask for more memory to see it that is the issue? Also, I would probably drop the `-N 1` parameter and use the default (which is `-N 0`).

**Comment by btc** [comment]
Thanks for the tip. Does `-N 0` produce different output? If so, I'll need to discuss the change with my PI (I am a lowly software engineer). Is there a reason you suggest `0` other than speed/performance?

Normally, my job scheduler notifies me if a job fails due to insufficient memory. I recognize it is possible that Bowtie2 is crashing during a call to `malloc` or `new` and exits before the scheduler/environment has an opportunity to detect the insufficient memory failure.

Is there (1) a value for `--multicore` and (2) a threshold of available memory above which you would rule out memory issues?

**Comment by FelixKrueger** [comment]
I haven't exhaustively tested the -N parameter but I remember there was once a issue report that suggested that `-N 1` created some different output (which was never followed up though). I would just imagine that allowing mismatches in the seed uses more memory, and normally it is not needed to allow extra mismatches because at least one of the multi-seeds should match without errors anyway.

I personally have never experienced the oom issues myself (we use a GridEngine Rocks6 cluster), and I tend to use -l h_vmem=15G for a human genome. I think a human genome takes ~4G of RAM (which Bismark holds in memory), and each of the 2 Bowtie2s will also need that. So assume it takes 12GB, but lets be on the safe side and give it 16G? So `--parallel 8` would need at least 24 cores and 128G of RAM.

Is there a change that your  `'mem' => "15G", # per core` isn't really per core but counts for the entire process?

**Comment by btc** [comment]
I'm on Grid Engine also. Rocks 6.2 (Sidewinder).

`mem` gets translated to `-l h_vmem=15G` (I implemented this DSL). I'm 100% sure it is per-core. For example, this job allocated over 60GB before dying. `mem` was under 20GB:

```
Job 5816645 (bismark) Aborted
 Exit Status      = 141
 Signal           = PIPE
 Start Time       = 06/06/2017 14:55:40
 End Time         = 06/06/2017 17:38:10
 CPU              = 03:23:43
 Max vmem         = 65.927G
failed assumedly after job because:
job 5816645.1 died through signal PIPE (13)
```

I will run a `--parallel 8` job with 30 cores and 200 GB RAM and report back.

``` ruby

  map_dir = File.join(OUT_DIR, sid, 'map')
  map_cores = 30
  map_job = {
    'name' => File.join(sid, 'map'),
    'inputs' => trim_job['outputs'],
    'outputs' => [File.join(map_dir, "#{base(trim_job['outputs'].first)}_bismark_bt2_pe.bam")],
    'command' => [
      BISMARK_PATH,
      '--parallel', 8,
      '--no_dovetail',
      '--temp_dir', File.join(OUT_DIR, 'tmp'),
      '--fastq',
      '--bowtie2',
      '--path_to_bowtie', BOWTIE_PATH,
      '--samtools_path', File.dirname(SAMTOOLS_PATH),
      BISMARK_GENOME_DIR,
      '-o', map_dir,
      -1, trim_job['outputs'][0],
      -2, trim_job['outputs'][1],
    ].join(' '),
    'resources' => {
      'procs' => map_cores,
      'mem' => "#{ 1 + 200 / map_cores }G", # per core
      'runtime' => {
        'hours' => 5,
        'minutes' => 59,
      },
      'tag' => sid,
    },
  }
```

**Comment by FelixKrueger** [comment]
Alright, good luck!

**Comment by btc** [comment]
It died. 😭 

```
Job 5848250 (bismark) Aborted
 Exit Status      = 141
 Signal           = PIPE
 User             = brianhc
 Queue            = extended@scg3-2-3.local
 Host             = scg3-2-3.local
 Start Time       = 06/07/2017 08:42:13
 End Time         = 06/07/2017 08:58:53
 CPU              = 00:56:47
 Max vmem         = 37.668G
failed assumedly after job because:
job 5848250.1 died through signal PIPE (13)
```

**Comment by FelixKrueger** [comment]
I'm pretty convinced it is the memory and something in your configuration that gets it wrong somehow. Can you try with `--parallel 2` and a ridiculous amount of mem to see if it works at all?

**Comment by FelixKrueger** [comment]
I just ran a test over here against the human genome with `--parallel 10`:

`qsub -o lots_of_RAM.log -l h_vmem=180G -pe orte 30 bismark --genome /bi/scratch/Genomes/Human/GRCh38/ --parallel 10 -1 file1 -2 file2`

```
Job 2366207 (bismark) Complete
User             = fkrueger
Queue            = all.q@compute-0-5.local
Host             = compute-0-5.local
Start Time       = 06/07/2017 22:04:56
End Time         = 06/07/2017 22:22:14
User Time        = 00:36:33
System Time      = 01:37:42
Wallclock Time   = 00:17:18
CPU              = 02:14:16
Max vmem         = 101.922G
Exit Status      = 0
```

So this took a bit more than 10G per instance of Bismark against the latest human genome build.

**Comment by btc** [comment]
`--parallel 2` with 30 cores and 210 GB RAM (`h_vmem=7G`). It died fairly quickly.

https://gist.github.com/anonymous/056a65ca2b5a7385798652b712263a47

```
Job 5873641 (bismark) Aborted
 Exit Status      = 141
 Signal           = PIPE
 User             = brianhc
 Queue            = extended@scg3-1-4.local
 Host             = scg3-1-4.local
 Start Time       = 06/07/2017 14:32:21
 End Time         = 06/07/2017 14:42:52
 CPU              = 00:22:36
 Max vmem         = 18.836G
failed assumedly after job because:
job 5873641.1 died through signal PIPE (13)
```

Aside: Why did you specify 180G? Is that to allocate 5,400GB total?

**Comment by btc** [comment]
As a comparison, this is how the output looks when a job is killed due to OOM:

```
Job 5789778 (foo) Aborted
 Exit Status      = 137
 Signal           = KILL
 User             = brianhc
 Queue            = extended@scg4-h17-37.local
 Host             = scg4-h17-37.local
 Start Time       = 06/04/2017 14:05:43
 End Time         = 06/04/2017 14:41:03
 CPU              = 00:15:28
 Max vmem         = 72.721G
failed qmaster enforced h_rt, h_cpu, or h_vmem limit because:
job 5789778.1 died through signal KILL (9)
```

**Comment by FelixKrueger** [comment]
Our cluster is configured so that what you ask for with `-l h_vmem` is the total memory and not the memory per core. So yea, I begin to think this is a more a question for a GE person because I don't quite know how to get this going... You said that you were able to run the jobs in single-core mode you said? 

I was just thinking: Do you think it is possible that the extra child-jobs get somehow run on a different node? or is there a possibility the node you are assigned to does not have enough RAM?

**Comment by btc** [comment]
I see.

Yes, single-core mode works just fine.

I am _fairly_ certain that jobs are running on one node. It would be incredibly strange for a job to 

I am certain that the node has enough RAM. All of the nodes have at least 400 GB physical RAM.

I notice there's a `--quiet` flag passed to bowtie2. Can I remove this to see if bowtie is trying to tell us something? Or does the correctness of bismark depend on the console output of bowtie?
https://github.com/FelixKrueger/Bismark/blob/master/bismark#L8458

**Comment by martinjvickers** [comment]
I used to look after a SGE cluster in my previous job. IIRC the `h_vmem` parameter is by default configured so that it's per job. 

http://gridscheduler.sourceforge.net/htmlman/htmlman5/queue_conf.html

```
The resource limit parameters s_vmem and h_vmem  are  implemented  by  Sun  Grid  Engine  as a job limit.
...
For parallel processes, the limit is applied per slot which means that the limit is multiplied by the number of slots being used by the job before being applied.
```

However, the configuration can be altered by the SysAdmin. So on the cluster I managed I set up `-pe multithread` which would only allocate slots on a single node and treat `h_vmem` as a whole, but equally there was `-pe openmpi` and `pe mpich` which would allocate slots on any available node and treat `h_vmem` per slot.

So depending on the cluster setup you could have the situation where when you request a single slot you're getting `h_vmem` for the whole job but for a different `-pe` the meaning of `h_vmem` is different. 

Do you have multiple parallel environments (`-pe`) to choose from?
