### ISSUE TITLE
Why the duplication is so high in a few of my WGBS data? 

### ISSUE THREAD

**Issue by wkl1990** [FelixKrueger/Bismark#112]
I use bismark bowtie2 to map and deduplicate to remove duplication. The duplication of some data is very high (nearly 60%). I want to know the reason. And how could I do?

**Comment by FelixKrueger** [comment]
The most likely explanation is that you didn't have a lot, or not very diverse, starting material so you ended up amplifying the same fragments but PCR at some point during the library preparation step. If you go back to the Bioanalyser profiles you might be able to confirm this.

**Comment by wkl1990** [comment]
@FelixKrueger Thank you for your help. Another question, how could I get duplicated information from Bioanalyser profiles? As I know, the Bioanalyser is usually performed to check the size distribution.

**Comment by FelixKrueger** [comment]
That is true, but I was probably more thinking of a quantification of the mRNA abundance (not sure on which machine this is measured these days, it's been a while that I have been working in the lab...). A very diverse library should probably look more of a smear across many fragment sizes. Sorry if that was misleading..

**Comment by wkl1990** [comment]
You are right. I should check the starting material, PCR cycles, and the fragment size.
