### ISSUE TITLE
global levels from bismark_methylation_extractor?

### ISSUE THREAD

**Issue by avilella** [FelixKrueger/Bismark#117]
What would be the best value to use as global levels of methylation from bismark_methylation_extractor? Or how should it be calculated from the output files?

**Comment by ewels** [comment]
Can you not just use the results from the summary file / bismark2report?

![image](https://user-images.githubusercontent.com/465550/27859644-b85839ba-6179-11e7-8700-89b36d704105.png)

**Comment by avilella** [comment]
Great, so it's simply a matter of using the value in `Percentage methylation (CpG context)`.

Thanks

**Comment by ewels** [comment]
Yeah, if that's the value that you're interested in :) Depends on experimental setup / species and everything else really.. But assuming that you're working with whole-genome BSseq in Human / Mouse, then yes CpG is probably what you're after.

**Comment by FelixKrueger** [comment]
Thanks Phil for your comments. I guess the options are are: 
a) to use the overall percentage methylation values from the methylation extractor or `bismark2report`, or
b) you calculate a histogram or beanplot of percentage methylation values of cytosines as reported in the coverage files.

a) has the advantage that it is already there and you just need to look at the value, but you need to keep in mind that, as this is really looking at every single methylation call in the entire file, this value might be biased if you have a lot of contaminating sequences in the sample (e.g. major satellites may make up 10% of all sequences in a library so they get a bigger say than most other genomic regions in an overall value. 
b) has the advantage that it not showing an overly simplistic average methylation but could show you the typical bimodal distribution of methylation data. The disadvantage is that this not calculated by the extractor by default and would require you to write a custom script.
