### ISSUE TITLE
mapping efficiency

### ISSUE THREAD

**Issue by yilunhuangyue** [FelixKrueger/Bismark#120]
Hi all, I met an problem when running bismark. I used a paired-end WGBS data from NCBI for a test, when I running the paired-end separately, the mapping  efficiency was 15% and 65% separately, but when I used the paired-end data together, the mapping efficiency was only 2%, the command I used were 
bismark --bowtie2 -N 1 -L 32 --parallel 10 -p 3 --score_min L,0,-0.6 /reference1   test1.fq;
bismark --bowtie2 -N 1 -L 32 --parallel 10 -p 3 --score_min L,0,-0.6 /reference1   test2.fq;
bismark --bowtie2 -N 1 -L 32 --parallel 10 -p 3 --score_min L,0,-0.6 /reference1   -1 test1.fq -2 test2.fq

One of the paired-end file was like this:
![j_ x3 d9 rq f5o55do na](https://user-images.githubusercontent.com/16872303/29674803-cef2be74-8925-11e7-9231-61573c577228.png)

It was the first time for me to used bismark and I was not sure where is the problem.  Thanks for any help~

**Comment by FelixKrueger** [comment]
From what you describe here the sample seems to have been constructed in PBAT mode (post bisulfites adapter tagging), which means that you need to specify the option `--pbat` for paired-end alignments. If you wanted to align the reads in single-end mode you would also need to use `--pbat` for Read 1, but use the default mode for Read 2. If you study the help for the `--pbat` mode or the Bismark User Guide you should get some more information on the PBAT alignment mode.

In addition to the `--pbat` option you also need to subject the data to adapter and poor quality trimming, and also PBAT also requires some additional 5' trimming. I am currently on holiday and can't research how many bases at the 5' end are affected, but running FastQC on the data will probably show you a dramatic sequence bias at the start of the read, my guess is that it will affect either the first 4 or 6bp. Here is a table giving you some guidance of which Trim Galore command would be ideal for your data: https://rawgit.com/FelixKrueger/Bismark/master/Docs/Bismark_User_Guide.html#viii-notes-about-different-library-types-and-commercial-kits. This is from the User Guide:

```
PBAT

The amount of bases that need to be trimmed from the 5' end depends on the length of the oligo used for random priming, which - as we know - isn't all that random, and in fact causes misalignments and methylation biases. While the original PBAT paper used 4N oligoes, these days 6N or 9N seem to be most common. Please also see the section 3' Trimming in general below.
```

Finally, just briefly regarding your mapping command:
I would simply start with something like:

`bismark /reference1 -1 test1_trimmed.fq -2 test2_trimmed.fq`

Which should just do the right thing. If you wanted to speed up the alignments somewhat (assuming you have enough system resources) you could start increasing `--parallel`, but the default mode should work just fine. I hope this helps a little, Best, Felix

**Comment by yilunhuangyue** [comment]
Hi @FelixKrueger,  The Mapping efficiency was 71% by adding --pbat.  I will study the help for the --pbat mode or the Bismark User Guide for more information and check the 5' trimming. Thanks again for your kind help, It is very useful.
