### ISSUE TITLE
Methylation call

### ISSUE THREAD

**Issue by bandapanda** [FelixKrueger/Bismark#121]
Hi,

I have a question about bismark_methylation_extractor. I have checked XM tag in bam file for methylation call, and from there I calculated a number of methylated and unmethylated C in CpG (Z and z) in some particular position. This number of total coverage of methylated and unmethylated cytosines in bam file is not the same as bismark_methylation_extractor gave in coverage file. Could you explain why is this difference present? Is bismark_methylation_extractor check map quality or base call quality, and because of that some methylated and unmethylated bases are excluded?

Thank you in advance

**Comment by FelixKrueger** [comment]
Hi bandapanda,

The most obvious difference might arise when you are looking at a paired-end BAM file, because the methylation extractor does by default stop extracting positions from read 2 when it starts overlapping with read 1. Would this explain what you are seeing?
What you could do next would be to look at the CpG-context files and grep for the position in question. Ideally, all the hits in there should match up with the coverage file, and whatever you have done.

**Comment by bandapanda** [comment]
Hi Felix, 

Thanks for the answer.

I have checked CpG context file, and in that file on position which I tested is same coverage as in bam file(output of Bismark), but different in coverage file. E.g. from bam file I have 22 coverage at some position, in CpG context file is same coverage (15unmeth + 7 meth), but in coverage file is 21 coverage (6 meth and 15 unmeth). Should the coverage in CpG-context file and coverage file (output of bismark_methylation_extractor) be the same, if I understood you well? So, I got that coverage file in bam file and cpg-context file at same position have same results. 

Thank you in advance.

**Comment by FelixKrueger** [comment]
Yes, in theory the coverage file should simply be an aggregated and sorted version of the CpG context file. Would you be able to isolate the reads in the BAM file, and from the CpG context files and send them to me via email (felix.krueger@babraham.ac.uk)? Also, please mention the exact command you used for the bismark2bedGraph? I'm still travelling for a couple of days but I will take a look soon. Cheers, Felix

**Comment by bandapanda** [comment]
Felix helped me with this problem. I will just explain what it is the solution. 
I checked again CpG context file and it gave the same value of coverage(methilated+unmethylated) as in coverage file. This difference in coverage of methylated and unmethylated C in bam file and coverage file was because of the option --no_overlap in bismark_methyalation_extractor exists by default, and that means, in term of paired_end reads, that if the mates are overlapped, methylation_extractor will call once methylated or unmethylated C, on the first read.

Thank you again, Felix, you helped me a lot.
