### ISSUE TITLE
Add a % methylation filtering option to the non-conversion filtering for NOMe-Seq data

### ISSUE THREAD

**Issue by FelixKrueger** [FelixKrueger/Bismark#122]
I had a request to check reads for bisulfite non-conversion for NOMe-Seq data, which makes it a bit more tricky because accessible cytosines in GpC context (which includes non-CG cytosines) are meant to be methylated by design.

Instead of using the rather crude measure of an total count cutoff per read, can we please add an option to filter out reads that have a methylation above a certain percentage? This should scale much better for reads with a different overall number of cytosines. Also, can we add a minimum cytosine count threshold so that the percentage is only calculated for reads for which there are enough cytosines to base the % calculation on?

**Comment by FelixKrueger** [comment]
I have now added the new options `--percentage_cutoff [int]` and  `--minimum_count [int]` to `filter_non_conversion` to allow just what we set out to do (addressed here: 698bfff75a6df36c981fed9e0e4c6296cbbceddf). Will wait to see if it is working as expected.

**Comment by FelixKrueger** [comment]
Seems to be working fine, haven't heard otherwise.

**Comment by vivekbhr** [comment]
Hi @FelixKrueger I am interested in the effect of `filter_non_conversion` on NoMe-seq data. What thresholds for `--percentage_cutoff [int]` and `--minimum_count [int]` you think are reasonable that doesn't over-filter the reads with GC-methylation ?
Best,
Vivek

**Comment by FelixKrueger** [comment]
I am afraid I don't have an answer to that, maybe you could try a few things out and then report your findings here?

**Comment by vivekbhr** [comment]
All right I can give it a shot. I was wondering if having an option like `--exclude_GC` could help safely process NoMe-Seq data with this filter
