### ISSUE TITLE
bismark_methylation_extractor sometimes fails for "broken pipe" error

### ISSUE THREAD

**Issue by taojinsheng** [FelixKrueger/Bismark#124]
Dear Dr Krueger,

Thank very much for sparing some time to read this letter.I am a research assistant in Wuhan University in China.My research interests is DNA methylation abberation in cancer biology.

As noted in the theme,I found sometimes bismark_methylation_extractor failed for "broken pipe" error. I grepped lines with "broken pipe" error in the log file:

gzip: stdout: Broken pipe
gzip: stdout: Broken pipe
gzip: stdout: Broken pipe
gzip: stdout: Broken pipe
gzip: stdout: Broken pipe
samtools view: writing to standard output failed: Broken pipe
gzip: stdout: Broken pipe

It seems that the error messages were related to bismark_methylation_extractor source code lines with gzip or samtools and pipe ("|").

It would be greatly appreciated if you could help with this problem.

Regards,

Jinsheng

**Comment by FelixKrueger** [comment]
Hi Jinsheng,

Broken pipe errors are generally not so straight forward to diagnose, they are some problems by your filesystem when a process attempts to a send output to pipe which has been terminated.

This may sometimes be interrupted network connections or processes that were killed by the operating system (possibly because resources exceeded a specified limit, mostly RAM issues). Could you link the command you were using? In case you specified a very high number of `--multicore`, maybe it would be worth taking this number down somewhat?

**Comment by taojinsheng** [comment]
Hi Felix,

Thank you very much for your reply.The command line I used was "/home/jinsheng_tao/software/bismark_v0.17.0/bismark_methylation_extractor -p --no_overlap --bedGraph --gzip --multicore 4 --buffer_size 10G DPM-LC002-367-PS1_IRM_S04_R1_001.clean_bismark_bt2_pe.sorted.deduplicated.bam.sortByName.bam".I submitted job to our PBS cluster,and the submit command is "for i in *bismark_methylation_extractor.sh;do qsub -d ./ -l mem=10gb -V -N $i -e $i.e -o $i.o $i;done".From your experience,it seems that both RAM issue and network interrupt are possible source for my broken pipe error.Am I right?Thanks a lot!

**Comment by FelixKrueger** [comment]
Yes, maybe you try again losing the `--multicore` altogether and see if that runs to completion? Also, upgrading to the latest version (0.18.2_dev) is always a good option so that we don't accidentally chase something that is no longer the case...

**Comment by taojinsheng** [comment]
Thank you,Felix.The --multicore option makes the program consume much more RAM,but if I lose the --multicore option,the program will consume much more time.So,I could try to allocate more RAM for the job and decrease the --multicore number.Anyway,thank you very much for your suggestions.
