### ISSUE TITLE
bismark_methylation_extractor hangs if samtools path is not specified.

### ISSUE THREAD

**Issue by nick863** [FelixKrueger/Bismark#133]
1. Run ./bismark_methylation_extractor without --samtools_path and --vanilla options on the machine which has no samtools path in the PATH variable.
2. The bismark_methylation_extractor will hang without error messages.
Here is a proposed fix.
```diff
diff --git a/bismark_methylation_extractor b/bismark_methylation_extractor
index 8cc48d2..05d4af2 100755
--- a/bismark_methylation_extractor
+++ b/bismark_methylation_extractor
@@ -1097,7 +1097,7 @@ VERSION
     }
     
     unless (defined $samtools_path){
-	$samtools_path = '';
+        die "No Samtools found. Please add samtools to the PATH or specify its location with --samtools_path [path]\n";
     }
 	
   }
```
Thank you!

**Comment by FelixKrueger** [comment]
Thanks, I have changed this now (d55eb662d480c193e80704cfb6010d61385446f2). By the way I think it is about time to completely retire the `--vanilla` option, haven't really used it since 2011...
