### ISSUE TITLE
--merge_CpG fails in the coverage2cytosine

### ISSUE THREAD

**Issue by svrever** [FelixKrueger/Bismark#136]
Script terminates after writing the .CpG_report.txt  file

command line:
$ coverage2cytosine --merge_CpG  --genome_folder /GENOMES/X.laevis_v9.1/  -o XL1-7S_mrg  XL1_chr7S.cov

output:
...................................
...................................
Writing cytosine report for not covered chromosome chr9_10L
Writing cytosine report for not covered chromosome chr9_10S
Finished writing out cytosine report (processed 402501 chromosomes/scaffolds in total). coverage2cytosine processing complete.

Now merging top and bottom strand CpGs into a single CG dinucleotide entity (writing to file >> XL1-7S_mrg <<)
Failed to open file XL1-7S_mrg: No such file or directory

Sergei

**Comment by FelixKrueger** [comment]
Thanks for spotting this. I have now tried to work on a better way of handling all output and input file paths in this commit: 5b56a5adeb0bd3be4dfdf637d04c7b05a89de8b0. Please clone the latest development version and let me know if something isn't working as expected.

**Comment by svrever** [comment]
Hi Felix,
thanks for the script update. It worked very well. 
One question I still have is about the message at the end of script execution:

The strand of line 1 and line 2 were not + and -:
line1:	Scaffold100809 	1	+	0	0	CG	CGG
line2:	Scaffold100809	        4	+	0	0	CG	CGT

Is this the FIRST of encountered errors or this is ALL of them?

Thanks again,
Sergei

**Comment by FelixKrueger** [comment]
Hi Sergei,

Hmm, this shouldn't really happen I guess. The problem is that the `CG` at position 1 is fine, but the `CG` at position 2 (in reverse orientation) cannot have a trinucleotide context extracted and is thus missing the cytosine report. This must have crept in again during the latest changes (I believe it was handled fine in the past), I will try to fix it again tomorrow. Felix

**Comment by FelixKrueger** [comment]
Hi Sergei,

I am currently trying to reproduce the error you are are describing, but I'm afraid I can't seem to reproduce it. I have made a test coverage file like so:

```
$ more test_coverage.cov
Scaffold100809  1       1       33.3333333333333        1       2
Scaffold100809  2       2       66.6666666666666        2       1
Scaffold100809  4       4       50      2       2
Scaffold100809  5       5       100     4       0
```
which should suffer from the same problem you are describing. This was an artificial chromsome I just made up:
`>Scaffold100809
CGGCGTTCTGAACTGGTTACCTGCCGTGAGTAAATTAAAATTTTATTGACTTAGGTCACTAAATACTTTA`

And indeed here is the CpG report file:

```
out.CpG_report.txt
Scaffold100809  1       +       1       2       CG      CGG
Scaffold100809  4       +       2       2       CG      CGT
Scaffold100809  5       -       4       0       CG      CGC
Scaffold100809  25      +       0       0       CG      CGT
Scaffold100809  26      -       0       0       CG      CGG
...
```
 where position 2 does not show up at all. If I run coverage2cytosine with `--merge_CpG` it finishes without errors, and produced this file:

```
more out.CpG_report.merged_CpG_evidence.cov
Scaffold100809  4       5       75.000000       6       2
```
Where positions 1 and 2 are simply not listed (as intended). I then had a look at the `coverage2cytosine`, and it contains this code:
```
	# If there is a CpG right at the start of the reference chromosome it will be present for the top strand,
	# but will be missing for the reverse strand because it is impossible to determine a trinucleotide context
...
	    if ($pos1 < 2){
		$line1 = $line2;
		$line2 = <IN>;
		chomp $line2;
		($chr1,$pos1,$strand1,$m1,$u1,$context1) = (split /\t/,$line1);
		($chr2,$pos2,$strand2,$m2,$u2,$context2) = (split /\t/,$line2);
	    }

```
which means that if there as a CG at position 1 it will simply discard the entry and read in a new line to make up the new pair. Are you using the very same version as I do (v0.19.1_dev)? If you are still seeing the same issue, could you please make available your genome file(s) and coverage file so I can try and track this down?

Thanks, Felix

**Comment by svrever** [comment]
Hi Felix,
thanks for looking into this. I am using your latest v0.19.1_dev version of the script, and so far I have seen this message in all (21) .cov files I had processed. Curiously enough, Scaffold100809 is not even present in any of my coverage files:

......................................................................................................................
Scaffold10080	480	480	100	6	0
Scaffold10080	481	481	87.5	7	1
Scaffold10080	487	487	100	6	0
Scaffold10080	488	488	87.5	7	1
Scaffold10080	505	505	100	6	0
Scaffold10080	506	506	100	8	0
Scaffold10080	512	512	100	6	0
Scaffold10080	513	513	100	8	0
Scaffold100805	24	24	100	6	0
Scaffold100805	29	29	100	6	0
Scaffold100805	134	134	100	6	0
Scaffold100805	135	135	100	2	0
Scaffold100805	148	148	100	3	0
Scaffold100805	149	149	100	1	0
Scaffold100805	151	151	100	3	0
Scaffold100805	152	152	100	1	0
Scaffold100805	157	157	100	3	0
Scaffold100805	158	158	100	1	0
Scaffold100805	166	166	100	3	0
Scaffold100805	167	167	100	1	0
Scaffold100805	176	176	100	3	0
Scaffold100805	183	183	66.6666666666667	2	1
Scaffold100805	202	202	50	1	1
Scaffold100806	21	21	66.6666666666667	2	1
Scaffold100807	7	7	80	4	1
Scaffold10081	25	25	100	1	0
Scaffold10081	51	51	0	0	1
Scaffold10081	52	52	100	1	0
Scaffold10081	88	88	0	0	1
Scaffold10081	89	89	33.3333333333333	1	2
Scaffold10081	153	153	100	2	0
Scaffold10081	154	154	75	3	1
Scaffold10081	186	186	100	2	0
Scaffold10081	187	187	100	2	0
Scaffold10081	210	210	100	3	0
Scaffold10081	211	211	100	2	0
Scaffold10081	342	342	100	6	0
Scaffold10081	343	343	100	4	0
..........................................................................................

I assume that must be in an issue with genome assembly, although frankly I do not see anything  unusual:
>Scaffold100805
TGATTTTTAACCCATATTTTTTCCGCAGCGTTCCAATGTAATAGTGAGCATCTGCAAAATCACACATGAGTTGGGGCAAA
TATTTGGGTATAATTGGGGTCAAttccagcttaggggtaaatttaataagtggcgaaaatttgccagcgacggctgcgcc
accatcgcaacacttcgccagacgaaaatttgctcagacaacgctaatttactaaaatgaaaagtt
>Scaffold100806
ccaagcaccaccctagttcccgccactccacaccagagttaaaagaccacacagacatcagtgctaaaaatggtaccccc
cacacacacaagttataaaaagctattgatggtgagggccccttataaattaaaaaaaactgtggcaccagggcccccca
taaaaaatttttttagaaaaattggtggtcagggcccccctacaagttaaaaaaaataattggtga
>Scaffold100807
TGCTGTCGGCAGACATTTTGAAATGAACCAGGTTTTGGCTTCAGAAATGGAAAGTGTGTGAGGAAAGAACATGGCAGAGT
AGAGCAAATAAAGGCAGAGGCTGAAGGATGTGCTAGACTGTACTTTTATAGATTGCAAGGGGCTGACAATAAAGACAGCA
GACCCTGTGACTCCTACTGAGTCCAGGAGAAGAGAGGCCCCATTGCTACCTGAGTCCAGGAGAAGA
>Scaffold100808
CGCTGGTTGTATAAAATCTGCAGAGACAGCATCAATCTTAATCAGGGCCTTTTTCAACATCAAACAGCATAGTTTGATCA
CCTCATGCTGTATGTCTAACCAACATACAGACACCTCTTATCTTGATAATTTTCAAAAGAGATGCATAACTATAAACTTG
ACACAAAGCAATAGGGGAAGATGGGGTCTGGCTCTGGGCATTTGTACTCTAAAGACATGACAATTA
>Scaffold100809
cggcgtttcaggagggggcctgatggagaacaaagtgaaggtaatttagtattttggctttccttctcCtttaaaagagt
atttaccaatgggtgaaagtgaaaattcatcctttgataaatacgcctttcaaaatacaatagagattaatgcagcttgg
ctgaatttcactctagggggcaaattcactaagccgctaagcgccgaacgctagcgttaattcgcT
>Scaffold10081
AGCCCTGCCAGTCCCGAGAACTCCGGGTTGCCCCACAGAggggtttggggcgctaatttattataactaaccaatctatg
ggctattcgtagaatggtgctctgcagccacactaatggcatttgcaatttctttggctgtttaaccagcagcgcccacc
agggggtggtggtgggatggtttgccgcaatggaccaaagctgtgacagcgggggggggggggacaaatcagcctgcacc
caaggtatgcaatgagtaagctgtgcagcaatatattacaagtagagatctggcagtgccaaccccccccctcttaccta
ggtctcattaaggtagtgaggcgcaggcgtggcctagaggacccccatataaatttgctgataaggctgtgtactcctgc
aaagaacttcttaggtataagaataggcgaatgccaaaggatgtacagccatttagggagaataaacattttaactagtt
gcaccctacctgcaggccccactggcaatgattcccaggtcttaaatttgtgctgggaccaatgaattaattggtccaga
ttcagttcctgaaacttgtcaatagggagcgctatttgcagtcccaagtatgtaaaagaatctactacttgcaaggggca
tgcattcaacgattcgccgggttgcttcgcatcaaccaaaaacaatacagatttgtgcgtattagtctgtagtccagaga
ctctgccaaagacttgcgtaagctcaaccagggcttgcaaagattgacccctatcaccgagatatactaatgtgtcgtct
gcatataattggatcttttcaacttggccctgtctttcaaaccctctgatttggggatgcaacctcacagcctgggcgaa
gggttcaatggccaatgcaaagagcaaaggggagagggggcacccctgtctcgttcccctggtaagtgaaaagctcggag
tgtggag

Here is X. laevis repeat masked genome link:
ftp://xenbaseturbofrog.org/sequence_information/JGI/xl9_1/Xla.v91.repeatMasked.fa

Sergei

**Comment by FelixKrueger** [comment]
Hmm, this doesn't become much clearer yet :) I'm not sure that the scaffolds are necessarily ordered in the same numerically in the coverage file, could you grep for it? And also, could you link the CpG report output plus minus a few lines around the start of Scaffold100809? Cheers, Felix

**Comment by svrever** [comment]
I pre-sorted coverage files with LC_COLLATE=C sort -k1,1 -k2,2n.  And grep did not find Scaffold100809 in the .cov files also (I used pg before).
However in  .CpG_report.txt file  Scaffold100809 was found, although not at the expected location and expected order:
. . . 
14277:Scaffold100807	7	+	4	1	CG	CGG
14278:Scaffold100807	8	-	0	0	CG	CGA
14279:Scaffold10081	15	+	0	0	CG	CGA
14280:Scaffold10081	16	-	0	0	CG	CGG
. . .
14350:Scaffold100815	105	-	3	0	CG	CGT
14351:Scaffold100815	178	+	4	0	CG	CGT
14352:Scaffold100815	179	-	2	1	CG	CGG
. . .
72134169:Scaffold100808	1	+	0	0	CG	CGC
72134170:Scaffold100809	1	+	0	0	CG	CGG
72134171:Scaffold100809	4	+	0	0	CG	CGT
72134172:Scaffold100809	5	-	0	0	CG	CGC
72134173:Scaffold100809	124	+	0	0	CG	CGC
72134174:Scaffold100809	125	-	0	0	CG	CGT
72134175:Scaffold100809	195	+	0	0	CG	CGC
72134176:Scaffold100809	196	-	0	0	CG	CGG
72134177:Scaffold100809	202	+	0	0	CG	CGC
72134178:Scaffold100809	203	-	0	0	CG	CGC
72134179:Scaffold100809	205	+	0	0	CG	CGA
72134180:Scaffold100809	206	-	0	0	CG	CGG
72134181:Scaffold100809	209	+	0	0	CG	CGC
72134182:Scaffold100809	210	-	0	0	CG	CGT
72134183:Scaffold100809	215	+	0	0	CG	CGT
72134184:Scaffold100809	216	-	0	0	CG	CGC
72134185:Scaffold100809	223	+	0	0	CG	CGC
72134186:Scaffold100809	224	-	0	0	CG	CGA
72134187:Scaffold100817	43	+	0	0	CG	CGG
72134188:Scaffold100817	44	-	0	0	CG	CGC
72134189:Scaffold100817	176	+	0	0	CG	CGT
72134190:Scaffold100817	177	-	0	0	CG	CGC
72134191:Scaffold100818	97	+	0	0	CG	CGG
72134192:Scaffold100818	98	-	0	0	CG	CGG
72134193:Scaffold100819	28	+	0	0	CG	CGT
72134194:Scaffold100819	29	-	0	0	CG	CGA
72134195:Scaffold100819	92	+	0	0	CG	CGC
72134196:Scaffold100819	93	-	0	0	CG	CGC

I guess so much for my sorting...

**Comment by FelixKrueger** [comment]
Ah right that's why, the culprit is the previous scaffold! Scaffold100808:

```
72134169:Scaffold100808 1 + 0 0 CG CGC
72134170:Scaffold100809 1 + 0 0 CG CGG
72134171:Scaffold100809 4 + 0 0 CG CGT
72134172:Scaffold100809 5 - 0 0 CG CGC
```

The reason is that Scaffold100808 only contains a single `CG`, and that at position 1 (how very likely is that...). Because of this it reads in a new line as read 1, which also happens to be a `CG` at position 1 on the next scaffold which doesn't have a - position as next entry. This means that I will need to add some more logic when it reads the next line. But at we found it! I am now going on holiday so I can't exactly promise when I will find to the to look at it again (but hopefully soon). Felix

**Comment by svrever** [comment]
Great! I am glad you figured that out. Probably  script should ensure that scaffold name is the same before merging...

Sergei

**Comment by svrever** [comment]
Two of my files generated yet another error message:

The strand of line 1 and line 2 were not + and -:
line1:	Scaffold234478	1	+	0	0	CG	CGG
line2:	Scaffold234478	20	+	0	0	CG	CGA

worse is that the output to the .CpG_report.merged_CpG_evidence.cov file aborted at that point (at ~2.5%). Here are the last lines of the output:

Scaffold234460	36	37	100.000000	5	0
Scaffold23447	119	120	100.000000	10	0
Scaffold23447	128	129	100.000000	9	0
Scaffold23447	230	231	88.888889	16	2
Scaffold23447	714	715	100.000000	4	0
Scaffold234472	23	24	100.000000	1	0
Scaffold234472	106	107	100.000000	1	0

corresponding lines from the .CpG_report.txt  file look like that:

1975782:Scaffold23447	119	+	6	0	CG	CGG
1975783:Scaffold23447	120	-	4	0	CG	CGA
. . . . .
1975788:Scaffold23447	714	+	1	0	CG	CGT
1975789:Scaffold23447	715	-	3	0	CG	CGG
1975790:Scaffold234472	23	+	1	0	CG	CGA
1975791:Scaffold234472	24	-	0	0	CG	CGA
1975792:Scaffold234472	106	+	1	0	CG	CGC
1975793:Scaffold234472	107	-	0	0	CG	CGT
1975794:Scaffold234477	1	+	1	0	CG	CGA
1975795:Scaffold234478	1	+	0	0	CG	CGG
1975796:Scaffold234478	20	+	0	0	CG	CGA
1975797:Scaffold234478	21	-	0	1	CG	CGA
1975798:Scaffold234478	67	+	0	0	CG	CGC
1975799:Scaffold234478	68	-	1	0	CG	CGG
1975800:Scaffold23448	46	+	0	0	CG	CGG
1975801:Scaffold23448	47	-	0	1	CG	CGG
1975802:Scaffold23448	524	+	0	8	CG	CGC
1975803:Scaffold23448	525	-	1	5	CG	CGG
1975804:Scaffold23448	555	+	0	8	CG	CGA
1975805:Scaffold23448	556	-	0	4	CG	CGA
. . . . .
72682683:Scaffold234470	2	+	0	0	CG	CGG
72682684:Scaffold234470	3	-	0	0	CG	CGT
. . . . .
72682697:Scaffold234470	114	+	0	0	CG	CGG
72682698:Scaffold234470	115	-	0	0	CG	CGT
72682699:Scaffold234473	30	+	0	0	CG	CGG
72682700:Scaffold234473	31	-	0	0	CG	CGC
. . . . .
72682709:Scaffold234473	126	+	0	0	CG	CGG
72682710:Scaffold234473	127	-	0	0	CG	CGC
72682711:Scaffold234475	6	+	0	0	CG	CGG
72682712:Scaffold234475	7	-	0	0	CG	CGC
. . . . .
72682727:Scaffold234475	126	+	0	0	CG	CGC
72682728:Scaffold234475	127	-	0	0	CG	CGG
72682729:Scaffold234476	25	+	0	0	CG	CGT
72682730:Scaffold234476	26	-	0	0	CG	CGA
. . . . .
72682741:Scaffold234476	102	+	0	0	CG	CGC
72682742:Scaffold234476	103	-	0	0	CG	CGT
72682743:Scaffold234479	16	+	0	0	CG	CGA
72682744:Scaffold234479	17	-	0	0	CG	CGC
72682745:Scaffold234481	86	+	0	0	CG	CGG
72682746:Scaffold234481	87	-	0	0	CG	CGC
72682747:Scaffold234481	121	+	0	0	CG	CGT
72682748:Scaffold234481	122	-	0	0	CG	CGA

Previously merging continued to the end of the last chromosome despite the error.

Sergei

**Comment by FelixKrueger** [comment]
I am pretty sure this the same issue:

```
1975794:Scaffold234477	1	+	1	0	CG	CGA
1975795:Scaffold234478	1	+	0	0	CG	CGG
1975796:Scaffold234478	20	+	0	0	CG	CGA
```

What's the bet that `Scaffold234477` starts with a CG, is very short and doesn't contain a second `CG`?

**Comment by FelixKrueger** [comment]
Hi Sergei,

I have tried to fix this issue now. Would you please clone the latest dev version and let me know how you get on?

Thanks, Felix

**Comment by svrever** [comment]
Hi Felix,

new version of the script worked without a glitch!
_CpG merging complete. Good luck finding DMRs with bsseq!_
Thanks for taking time ironing the bugs out!

Best,
Sergei

**Comment by FelixKrueger** [comment]
Excellent, thanks for letting me know!

**Comment by mtanic** [comment]
Hi Felix, 

I am using  Bismark Version: v0.19.0, and the coverage2cytosine module (Script last modified: 12 October 2017) with --mergeCpG option still gives the same error when running:

` coverage2cytosine --genome_folder ${BSGEN} --merge_CpG --gzip -o ${file%%.bismark.cov.gz}"bismark.CpG.cov.gz" $file
`

> Finished writing out cytosine report for covered chromosomes (processed 24 chromosomes/scaffolds in total)
> 
> Now processing chromosomes that were not covered by any methylation calls in the coverage file...
> All chromosomes in the genome were covered by at least some reads. coverage2cytosine processing complete.
> 
> Now merging top and bottom strand CpGs into a single CG dinucleotide entity (writing to file >> Agilent_ZYMO-UM_R1_val_1_bismark_bt2_pe.deduplicatedbismark.CpG.cov.gz <<)
> Failed to open file Agilent_ZYMO-UM_R1_val_1_bismark_bt2_pe.deduplicatedbismark.CpG.cov.gz: No such file or directory

Best wishes,
Miljana
