### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by ClaireXinSun** [FelixKrueger/Bismark#146]
Hi,

I am new in bisulfite sequencing analysis and is learning Bismark.But I got a problem in installing the software. 

I have Bowtie2 and samtools in my path, but after I un-tar the package by "tar xzf Bismark_v0.19.0" and "cd Bismark_v0.19.0", I can not install it by "make" or "sudo make". it said "No targets specified and no makefile found.  Stop."

I also tried to just execute bismark (thought it is running on top of bowtie), it also failed.
Do you have any idea about this?
Sorry about the stupid question. Thanks for any help.

Cheers
Claire

**Comment by FelixKrueger** [comment]
Hi Claire,

After un-taring Bismark you don't need to install it or run a make command, it should just work. If you run:
```
cd Bismark_v0.19.0
./bismark --help
```

It should just work. If not, please can you show what is happening?

**Comment by ClaireXinSun** [comment]
Hi Felix,

Thank you a lot for helping me out. It works now. 

Cheers
Claire
