### ISSUE TITLE
bismark2summary suggestion/help

### ISSUE THREAD

**Issue by jlsovaz** [FelixKrueger/Bismark#147]
Hello Felix,

I'm using the bismark2report and I was just wondering if it is possible to change the two graphics (alignment and Cytosine Methylation). I would want that in the X axis of the graphics could appear the name of each sample analyzed instead of numbers (I know that the name of the sample appears if you move the mouse around the graphic).

So my question is, could you help me with this modification? Otherwise, if I would want to make this modification, where is this part in the code? (I am a simple beginner in this world).

Thank you in advance,

Regards,

Jose Luis

**Comment by FelixKrueger** [comment]
Hi Jose,

You could go into the script `bismark2summary` itself and try to locate the plot X axis parameters and change those.

Alternatively, and almost certainly much less of a hassle, you can simply open the text file `bismark_summary_report.txt`, that is also produced by `bismark2summary`, in Excel where you can edit the plot to your heart's content.

**Comment by jlsovaz** [comment]
Perfect, thank you for your answer. Even if the second alternative seems to be easier, I'll try with the first solution as well.

Regards,

Jose
