### ISSUE TITLE
gzip: {sample}_pe.bismark.cov.gz: No such file or directory // Bismark_methylation_extraction, paired end reads

### ISSUE THREAD

**Issue by jlsovaz** [FelixKrueger/Bismark#148]
Hello Felix,

I have a little problem doing the methylation extraction in my paired end data.

When I do the bismark_methylation_extractor, all works fine except one thing. This is the output:

```
===============================================================================
Methylation information will now be written into a genome-wide cytosine report
===============================================================================

gzip: CRC3ND_CSX_pe.bismark.cov.gz: No such file or directory
No last chromosome was defined, something must have gone wrong while reading the data in (e.g. specified wrong file path for a gzipped coverage file?). Please check your command!
```

My question is: How can I obtain this .cov.gz? I have installed all the packages that I need (for example: GD::Graph) but finally I don't receive the .cov.gz. I tried to find this in the user guide and it seems it should be obtained from the M-bias section.

Thank you in advance.

Regards

Jose

**Comment by FelixKrueger** [comment]
Hi Jose,

when you run `bismark_methylation_extractor` with the option `--bedGraph` specified you should also get a coverage file (as `.cov` in default mode, or `.cov.gz` when run with `--gzip`). Which version of Bismark did you use, and can you specify the entire command?

**Comment by jlsovaz** [comment]
Hello Felix,

I am using the last version:

```
bismark --version


          Bismark - Bisulfite Mapper and Methylation Caller.

                       Bismark Version: v0.19.0
        Copyright 2010-17 Felix Krueger, Babraham Bioinformatics
              www.bioinformatics.babraham.ac.uk/projects/
                https://github.com/FelixKrueger/Bismark
```

Finally I fixed it, the problem was that bismark_methylation_extractor used the actual working folder to look for the .cov / .cov.gz file instead of using my output folder.

Sorry for any inconvenience. Regards,

Jose
