### ISSUE TITLE
FQ sequence format questions

### ISSUE THREAD

**Issue by hmyh1202** [FelixKrueger/Bismark#153]

**Comment by FelixKrueger** [comment]
What exactly happened to the FastQ file, would you be able to provide part of it that reproduces the error?
Thanks, Felix

**Comment by hmyh1202** [comment]
When I do gunzip *fq.gz, it was also reported that of "invalid compressed data--format violated".

**Comment by FelixKrueger** [comment]
Yea I guess we might be able to add something, but could you share the file, or part of the file that causes the error so I can work with it? Cheers
