### ISSUE TITLE
Couple of small errors in deduplicate_bismark?

### ISSUE THREAD

**Issue by insectopalo** [FelixKrueger/Bismark#159]
Hi,

It seems that there are a couple of errors in the lines 350 and 672 of deduplicate_bismark, where the **unless** test is testing for only one variable twice (`$read_conversion`) instead of testing for both `$read_conversion` and `$genome_conversion`:
https://github.com/FelixKrueger/Bismark/blob/fadb600a2b85032b3125d293da1957ae94a24e87/deduplicate_bismark#L350
https://github.com/FelixKrueger/Bismark/blob/fadb600a2b85032b3125d293da1957ae94a24e87/deduplicate_bismark#L672

Regards,

Gon

**Comment by FelixKrueger** [comment]
Good spot, thanks! I have just corrected that (e4ff9b0bdc0c77450ad6129fda8fc034160924cf). Cheers, Felix
