### ISSUE TITLE
Not all temporary files are removed - possible error?

### ISSUE THREAD

**Issue by varunorama** [FelixKrueger/Bismark#160]
Hello Felix,
Using the following command: 
bismark --bowtie2 -N 1 -L 20 --multicore 8 --nucleotide_coverage --temp_dir /output/to/separate/temp/folder/ --genome /path/to/genome/folder/ --single Day0_S85_L003_R1_001_trimmed.fq, Day0_S85_L004_R1_001_trimmed.fq. 

I was able to successfully run Bismark with what seems to be no errors (it was able to go to the final stage of bam2nuc calculations). However when I checked my temporary directory, I noticed not all of the temporary files were deleted (which I presume deleting the temporary files created is part of the bismark pipeline). Every other temporary file, except for one, was deleted. Is this an indication that bismark actually did not run properly and that there was an error somewhere in the middle of the analysis?  

Thanks,
Varun

**Comment by varunorama** [comment]
Upon further inquiry for errors (ERR), I noticed that there was a bowtie2-align died with signal 9 (KILL) and bowtie2-align died with signal 13 (PIPE) errors. This suggests that I ran out of memory when running bismark. 

Maybe this is the culprit but I still was able to get a bam file that is ~630 Mb in size. Any thoughts?

**Comment by FelixKrueger** [comment]
Hi @varunorama ,

I would agree that you probably ran out of memory, and therefore you can't trust the output results I am afraid. I am not sure which genome you are using for your alignments, but the option `--multicore 8` will require 8-times as many resources as a standard Bismark run. For the human genome this would roughly mean:
`default mode:` 3 cores at 100%, and ~ 13GB of RAM
`--multicore 8:` 24 cores at 100%, and ~104GB of RAM

If you don't have this much available you need to go down with the amount of parallel processes.

**Comment by varunorama** [comment]
Hey Felix,

Thank you very much for the quick response. I just checked the computing cluster we have and it says:

4 sockets/node x 8 cores/socket = 32 cores/node
512 GB/node of 1600 Mhz RAM.

The genome we are using is ~30 Gb in size. Based on our computer specifications, we should be able to run it at multicore of 8 yes? Or would you recommend bringing down the multicore to 4?

-Varun

**Comment by FelixKrueger** [comment]
Hi Varun,

If your genome is ~30Gb then you would probably have to increase the numbers in my calculations by 10-fold (the human genome is only 3.5Gb or so?)! So assuming that each level of `--multicore` uses ~90GB or RAM, you might indeed try `--multicore 4`, but as the upper limit. I would maybe prepare a small test file with say 100000 reads, and try to run that and see if it runs to completion (including the deletion of temp file).

Good luck!

**Comment by varunorama** [comment]
Hey Felix,

Thank you for the calculations! I will go back and rerun using less cores. Hopefully it works.

Appreciate your help and for Bismark!

-Varun

**Comment by varunorama** [comment]
Everything worked! Decreasing the multicore to 4 solved all issues, thank you!

**Comment by FelixKrueger** [comment]
Excellent!
