### ISSUE TITLE
Output of Bismark mapping is empty 

### ISSUE THREAD

**Issue by Holly0123** [FelixKrueger/Bismark#165]
I tried to run Bismark for Bisulfite sequencing data, the command was "bismark -p 4 --path_to_bowtie /bin/bowtie2-2.2.5 --bowtie2 /REFERENCES/human38/  -1 sample1_F.fq.gz -2 sample1_R.fq.gz, but after 4 days running, I did not got any output files... 

The log information was shown below:

Single-core mode: setting pid to 1
Paired-end alignments will be performed
=======================================
The provided filenames for paired-end alignments are B00832PL_S15_L002_R1_001_val_1.fq and B00832PL_S15_L002_R2_001_val_2.fq
Input files are in FastQ format
Writing a C -> T converted version of the input file B00832PL_S15_L002_R1_001_val_1.fq to B00832PL_S15_L002_R1_001_val_1.fq_C_to_T.fastq
Created C -> T converted version of the FastQ file B00832PL_S15_L002_R1_001_val_1.fq (19098045 sequences in total)
Writing a G -> A converted version of the input file B00832PL_S15_L002_R2_001_val_2.fq to B00832PL_S15_L002_R2_001_val_2.fq_G_to_A.fastq
Created G -> A converted version of the FastQ file B00832PL_S15_L002_R2_001_val_2.fq (19098045 sequences in total)
Input files are B00832PL_S15_L002_R1_001_val_1.fq_C_to_T.fastq and B00832PL_S15_L002_R2_001_val_2.fq_G_to_A.fastq (FastQ)
Now running 2 instances of Bowtie 2 against the bisulfite genome of /mnt/lustre/groups/groupso/REFERENCES/human38/ with the specified options: -q --score-min L,0,-0.2 -p 4 --reorder --ignore-quals --no-mixed --no-discordant --maxins 500
Now starting a Bowtie 2 paired-end alignment for CTread1GAread2CTgenome (reading in sequences from B00832PL_S15_L002_R1_001_val_1.fq_C_to_T.fastq and B00832PL_S15_L002_R2_001_val_2.fq_G_to_A.fastq, with the options: -q --score-min L,0,-0.2 -p 4 --reorder --ignore-quals --no-mixed --no-discordant --maxins 500 --norc))
Found first alignment:
D00505:255:H3HYJBCX2:2:1101:1249:2223_1:N:0:AGGCAGAA/1  77      *       0       0       *       *       0       0       GATATGTTGAAGTTTTAATTTTTAGTATGTGTGAATGTGATTTTGTTTGGAAATGGTTTTTGTAAGTATATTTATGTGAAGATGAGGTAGTATAGGGTAAG   GGGGGGGGIGIGGIIIIGIIIIIIIIIIIIIIIGGIIGGGIGIGGIIIIIIIIIIIIIIGIGIIIGGGIIIIIIIIIIIIIGGIIIIIIIIGGIIIGIIIG   YT:Z:UP
D00505:255:H3HYJBCX2:2:1101:1249:2223_2:N:0:AGGCAGAA/2  141     *       0       0       *       *       0       0       TCCTTCATATATATATATATACATATATATACATATATATATCTAAATCTTCACATAACATCCTTCTCTCTATATATCCATATCCATATTTATCCATATTT   AAGGGIIIIIIIIIIIIIIIIIIIIIIIGIIIIIIIGIIIGGIIGGGGIIIGIIIIGGGGIIIIIIIIGIIIIIIIGGIIIIIIIGIIIGIIIIGGIGIIG   YT:Z:UP
Now starting a Bowtie 2 paired-end alignment for CTread1GAread2GAgenome (reading in sequences from B00832PL_S15_L002_R1_001_val_1.fq_C_to_T.fastq and B00832PL_S15_L002_R2_001_val_2.fq_G_to_A.fastq, with the options: -q --score-min L,0,-0.2 -p 4 --reorder --ignore-quals --no-mixed --no-discordant --maxins 500 --nofw)) 

It seems like something wrong when running bowtie2. I searched solutions for this error, found out someone said to re-index the reference genome on "there's no output result #34" poster. I did it, but it's not work for me. Could you please give me some suggestions?  Thanks a lot!

**Comment by FelixKrueger** [comment]
Oh this is unfortunate. I would suggest you try to get the command running on a very small test file first before you try the entire files again.

Just to confirm at the start: when you enter `/bin/bowtie2-2.2.5` on your command line, do you see the bowtie2 help coming up? If Bowtie2 is not in your `PATH` I think you need to specify the executable, like so: 
`/bin/bowtie2-2.2.5/bowtie2`

there is a good chance that /bin/ is already in your PATH, so if you use 
`bowtie2`

and see the help coming up you don't have to specify the path especially at all. 

Also, I would suggest you upgrade to the latest Bowtie2 which is v2.3.4.1 (https://sourceforge.net/projects/bowtie-bio/files/bowtie2/2.3.4.1). Your version is more than 3 years out of date, there is a good chance that this is an issue that got fixed years ago.

Next, I would just try out using the first 10000 sequences, and leaving out the `-p` parameter until you see any output files.

```
bismark -u 10000 /REFERENCES/human38/ -1 sample1_F.fq.gz -2 sample1_R.fq.gz
```

This command should not take longer than a minute or so, and you will then know whether it worked or not. So:

1) Update Bowtie 2
2) ideally put Bowtie2 in your `PATH`
3) run test alingment with reduced number of sequence (`-u 10000`)

I hope this will work! Cheers, Felix

**Comment by Holly0123** [comment]
Hi Felix,

Yes, you are so smart! Everything you said about Bowtie2 was correct, Bowtie2 was in my path, I do not need the absolute path any more. I will update Bowtie2 and run Bismark with a small test file. Thank you so much! With a big smile. Haoli

**Comment by FelixKrueger** [comment]
Good luck! :)

**Comment by ywang285** [comment]
Hi @abearab, I got the same issue as you mentioned. Did you mange to solve the issue?

**Comment by FelixKrueger** [comment]
is the program still running? did it get killed?

**Comment by abearab** [comment]
> Hi @abearab, I got the same issue as you mentioned. Did you mange to solve the issue?

See this, maybe that helps https://github.com/FelixKrueger/Bismark/issues/475#issuecomment-1061100733

**Comment by ywang285** [comment]
> > Hi abearab, I got the same issue as you mentioned. Did you mange to solve the issue?
> 
> @ywang285 – see this, maybe that helps [#475 (comment)](https://github.com/FelixKrueger/Bismark/issues/475#issuecomment-1061100733)

Thanks for reply! I checked my samtools version is 
samtools 1.19
Using htslib 1.19

**Comment by ywang285** [comment]
@FelixKrueger our cluster admin says "I’ve checked the system logs but couldn’t find any indication that the job was terminated for external reasons. As far as we can tell, the application running in your job (bismark) exited on its own, and returned an error code value of 13." Do you have any idea what the error code value of 13 means?

**Comment by FelixKrueger** [comment]
Alright, so you've got a nanopore dataset, which you first attempt to trim for Illumina adapters, discarding reads shorter than 100bp.

Next you trim reads by 9 bp from either side, adding a filter for 500bp (which I think get's ignored by using the `-b`/`-e` options. 

Next you feed this into Bismark, using minimap2 and limiting the sequence length to 100,000bp (a warning about this, the CIGAR string must not contain more than 65K operations for BAM format). You specify non-directional libraries, and use the quality encoding `--phred64-quals`: why is that? To my knowledge these quality scores are not in use for over a decade any more?

I don't exactly know what error code 13 means, but my guess is that it somehow comes from minimap2. What I would do is dropping the length 100000 parameters and `--phred64-quals`, and try again. Maybe on a small subset to start with (e.g. `-u 1000`).

**Comment by ywang285** [comment]
@FelixKrueger Thank you so much for your reply! I managed to let it run after discarding information on the first line besides read name. It seems the read name line contains so many information (for nanopore, I think it will contains flowcelll name, basecalling model used, methylation type and likelihood on each base, etc), so that when it is feed into Bismark, all information get linked together (as a single string?), which somehow caused the problem.

**Comment by FelixKrueger** [comment]
Ah, that's interesting. Bismark does indeed convert all empty spaces to underscores. Is it now working if you remove the additional information?

**Comment by ywang285** [comment]
> Ah, that's interesting. Bismark does indeed convert all empty spaces to underscores. Is it now working if you remove the additional information?

Yes! I tested a small dataset and Bismark worked without any issues (and as you suggested, I dropped --phred64-quals). Do you have suggestions on how many --parallels I should run with 64 cores and 256GB ram for human genome (reads are 1-2kb)? Does RAM consumption increases with the size of input fastq file?

**Comment by FelixKrueger** [comment]
not with the size of the inout file, but as a function of the `--parallel`.  I haven't done too many tests regarding resources, but I suppose you could easily try a value of `8` to start with, while monitoring the resource consumption (e.g. via `top`)

**Comment by ywang285** [comment]
I will try. Thank you so much!
________________________________
