### ISSUE TITLE
Bismark alignment fails with "Exiting because chromosome name already exists"

### ISSUE THREAD

**Issue by kpadm** [FelixKrueger/Bismark#166]
Hello,

I am using Bismark v0.19.0 to align reads to a novel genome which is available only as multiple thousands of scaffolds. After preparing the genome using `bismark_genome_preparation`, whenever I try to align the reads to the genome, I get an error stating `Exiting because chromosome name already exists. Please make sure all chromosomes have a unique name!`. I have checked the genome multiple times for duplicates in scaffold names, but there are no duplicate names as far as I can tell. Can you please help me diagnose this issue? Thanks.

Karthik

**Comment by FelixKrueger** [comment]
That is interesting, because both the genome preparation as well as Bismark should tell you which chromosome name appeared duplicated. Would you be able to point me to the direction of where you downloaded the genome from? I could take a look at it later tonight. Cheers, Felix

**Comment by kpadm** [comment]
Hi Felix,

Thanks for the quick response. At first, `bismark_genome_preparation` did complain saying that there is a duplicate chromosome name, but I renamed the supposed duplicate scaffold name to something else (like scaffoldXXX to scaffoldXXX_zzz) and it stopped complaining, and completed the bisulfite conversion successfully. The weird issue is that, when the alignment is running, it fails at the scaffold name right after the one I renamed (so scaffoldYYY which is right after scaffoldXXX_zzz in the file). Unfortunately, I am not at the liberty of sharing the genome since it is not yet published.

**Comment by FelixKrueger** [comment]
That's weird indeed. But I'm afraid there is only so much I can do if you can't share the scaffold names... Obviously there is something strange going on with the names of the scaffolds, so you have an idea of what you need to look at. Just generally, what inadvertently causes problems quite frequently if the genome sequence was copied from one operating system to another, so using  `dos2unix` or `mac2unix` often fixes these issues. 

Good luck! 
Cheers, Felix

(I am still happy to help if you can e.g. exchange the sequence of all of your sequences to AAAAA or so, and provide the files as download in that format).

**Comment by kpadm** [comment]
Hi Felix,

I have uploaded a randomly generated genome with the same scaffold names in the same order here - https://filelocker.purdue.edu/public_download?shareId=2457069a9899abf7ccbb34d429171330 can you take a look at it when you can? Thanks for your helo.

**Comment by FelixKrueger** [comment]
Thanks for that. I'll be going skiing tomorrow so i am not quite sure when I can fit it in, but I will definitely take a look! Cheers, Felix

**Comment by kpadm** [comment]
Thanks Felix. Have a good skiing trip.

**Comment by kpadm** [comment]
Hi Felix,

Thanks for your response. I finally figured out what was going wrong, and managed to fix this error. Turns out there were two "*.fa" files in the genome directory, and both were getting roped in to create the bisulfite genome. Thanks for all your help!

Karthik

**Comment by FelixKrueger** [comment]
Ahh, I should have thought of that possibility as it happened before... I am still glad it worked eventually! Best, Felix
