### ISSUE TITLE
how to set a cuttoff tofilter low methylated count

### ISSUE THREAD

**Issue by Sisov** [FelixKrueger/Bismark#167]
Dear authors:
I have run the bismark software ,but there is an questions about it ,since I have obtained a genome-wide cytosine report output and want to using methylKit to annotate it. But it is too big and have many low methylated count, did have any criterion to filter it or any idea ?
![qq 20180415165025](https://user-images.githubusercontent.com/22792569/38776661-21530f84-40cd-11e8-84b4-a4c7518f6407.jpg)

**Comment by Sisov** [comment]
Hi FelixKrueger:
maybe you can see my commands like this :bismark_methylation_extractor -comprehensive --no_overlap --counts  -report --bedGraph --buffer_size 30G --CX -p --cytosine_report --genome_folder /public1/home/isoseq/DNA_methylome/Bisulfite/Bdstachyon clean_1_bismark_bt2_pe.bam

Did it correct or edit it ?

Alex

**Comment by FelixKrueger** [comment]
The command looks basically fine, if you wanted all cytosine contexts (CpG, CHG and CHH) you could shorten the command to:

`bismark_methylation_extractor -comprehensive --bedGraph --buffer_size 30G --CX --cytosine_report --genome_folder /public1/home/isoseq/DNA_methylome/Bisulfite/Bdstachyon clean_1_bismark_bt2_pe.bam`

or for CpG context only:

`bismark_methylation_extractor -comprehensive --bedGraph --buffer_size 30G --cytosine_report --genome_folder /public1/home/isoseq/DNA_methylome/Bisulfite/Bdstachyon clean_1_bismark_bt2_pe.bam`

**Comment by Sisov** [comment]
ok, thank you for your reply.

Alex
