### ISSUE TITLE
Should bam be sorted before deduplicate and methylation extracting ?

### ISSUE THREAD

**Issue by qindan2008** [FelixKrueger/Bismark#174]
Hello, I run bismark with the commands below:
##step1, Mapping
bismark --bowtie2 -N 1 -l 20 -p 2 -B  SampleName --nucleotide_coverage \
bismark_index_genome_dir \
-1 SampleName.r1.fq.gz \
-2 SampleName.r2.fq.gz
##step2, Deduplicate
deduplicate_bismark  -p  --bam  SampleName_pe.bam
##step3, Methylation_extracting 
bismark_methylation_extractor  \
--ignore 3 --ignore_r2 3 --ignore_3prime 3 --ignore_3prime_r2 3  \
--cytosine_report --CX_context --bedGraph   \
-p  --parallel 2  \
--genome_folder  bismark_index_genome_dir  \
SampleName_pe.deduplicated.bam

------------------------------------------------------
Is that ok ?  
Should "SampleName_pe.bam" be sorted before Deduplicate and Methylation_extracting ?
Thanks a lot !

**Comment by FelixKrueger** [comment]
Hi @qindan2008, 

Your commands look pretty fine to me. I have a few suggestions regarding the use of options (please see them below), but if you have a good reason to use them the way you have then feel free to ignore them. And you should explicitly **not sort** BAM files between the mapping, deduplication and methylation extractor steps as this breaks these steps.

If you haven't already done so I would definitely suggest to add an adapter and quality trimming step at the start, like this one:

#### Step 1
`trim_galore --paired SampleName.r1.fq.gz SampleName.r2.fq.gz`

#### Step 2, Mapping
`bismark -p 2 -B SampleName --nucleotide_coverage 
bismark_index_genome_dir 
-1 SampleName.r1.fq.gz 
-2 SampleName.r2.fq.gz`

#### Step 3, Deduplicate
`deduplicate_bismark --bam SampleName_pe.bam`

#### Step 4, Methylation_extracting (`--CX` is only useful if you are working with plants...)
`bismark_methylation_extractor 
--ignore_r2 3 --cytosine_report --bedGraph 
--parallel 2 
--genome_folder bismark_index_genome_dir 
SampleName_pe.deduplicated.bam`

All the best, Felix

**Comment by qindan2008** [comment]
OK. Thank you so much for giving me so many detailed guidance !
