### ISSUE TITLE
low mapping efficiency of DNA methylation data

### ISSUE THREAD

**Issue by xiuru** [FelixKrueger/Bismark#175]
Hi Felix,
I am trying to map paired-end reads from Bisulfite sequencing using Bismark. 
The genome i used is Zea_mays.AGPv4.dna_rm.fa download from Ensembl, i build index use the commond:
`bismark_genome_preparation --verbose /path_to_genome/` 

I trim data with trimmomatic,using the following command:
`trimmomatic PE in_f.fq.gz in_r.fq.gz out_paired_f out_unpaired_f out_paired_r out_unpaired_r ILLUMINACLIP:universal.fa:2:30:10 LEADING:15 TRAILING:15 SLIDINGWINDOW:4:20 MINLEN:36`

And the code for bismark alignment is: `bismark --sam genome -1 fastq_f -2 fastq_r` 
I got very low mapping efficiency, about 10%-20%. I tried to test --non_directional, set --score_min to L,0,-0.6,map read1 and read2 seperately,and trim data with trim_galore... But the mapping efficiency still under 20%
![image](https://user-images.githubusercontent.com/24283569/39730897-cf69a232-5229-11e8-87c9-8b18418ef0d3.png)

Could you please give me some advise?
Thanks in advance.

**Comment by FelixKrueger** [comment]
Hi Xiuru,

I just had a look at the test data you sent, and treated it with a standard pipeline:

1) Adapter trimming with Trim Galore, command is:
`trim_galore --paired test_R1.fastq test_R2.fastq`

2) Mapping (the data is directional): 
 `bismark --genome /bi/scratch/Genomes/Zea_mays/ -1 test_R1_val_1.fq -2 test_R2_val_2.fq`

The mapping efficiency in default mode is ~60%, and ~68% with `--score_min L,0,-0.4`. 
![test](https://user-images.githubusercontent.com/5870509/39750643-a6a27822-52ad-11e8-8613-8209908bd876.jpg)


So yea I suspect that something with your trimming step didn't work quite as expected, over here it seems just fine. Here is the MultiQC report of the run:
[multiqc_report.zip](https://github.com/FelixKrueger/Bismark/files/1983292/multiqc_report.zip)

**Comment by FelixKrueger** [comment]
Yes that will be the difference! If you can just get the dna.chromsome and not .rm. or .sm. files you should get the same results.

**Comment by xiuru** [comment]
So only chromosome 1 to 10， not include Pt、Mt and other scaffolds?

**Comment by FelixKrueger** [comment]
The one I used was chromosomes 1 to 10, Pt, Mt as well as nonchromosomal.

**Comment by xiuru** [comment]
![image](https://user-images.githubusercontent.com/24283569/39776043-48b89bde-52c5-11e8-8e3e-683a6eafe999.png)
Thanks for your patient and quick reply! 
Thank you very much, Felix!
I got the results like yours!
Felix is a good guy!

**Comment by xiuru** [comment]
Hi Felix,
I met with another problem,
![image](https://user-images.githubusercontent.com/24283569/39825370-426edc86-5377-11e8-8077-8dd39338e925.png)
Is this because the scaffold is too short? 
The job still running, can i ignore these warnings?

**Comment by xiuru** [comment]
Yes，i saw that closed issue. Thanks,Felix.
