### ISSUE TITLE
Samtools Multithreading for Parallel Runs

### ISSUE THREAD

**Issue by kkapuria3** [FelixKrueger/Bismark#176]
Merging BAM files on single thread takes very very long time for high coverage data. I am planning to test samtools `-@/--threads` flag, which is supported in samtools1.8 and above when running bismark on parallel using `-p` . This will imply that users will have to use the latest version of samtools.  Is there a newer version of bismark in development which is releasing soon ?

**Comment by FelixKrueger** [comment]
We have just released v0.19.1 some 10 days ago, so there are no current plans of releasing a new version. Let me know how you get on! Cheers, Felix
