### ISSUE TITLE
license of highcharts.js incompatible

### ISSUE THREAD

**Issue by rekado** [FelixKrueger/Bismark#177]
Hi,

Bismark comes with highcharts.js, which appears to be non-free software, which means that free software distributions packaging Bismark cannot legally distribute it.

Is there an alternative that can be used instead to ensure that all of Bismark remains software libre?

**Comment by FelixKrueger** [comment]
@ewels could you comment on this? Thanks, Felix

**Comment by FelixKrueger** [comment]
I have now replaced highcharts.js in both `bismark2report` and `bismark2summary`, so Bismark should now be completely free to use again. The changes are already available in the current development version, there will also be a new release in due course. Thanks again for pointing this out! Best, Felix

**Comment by rekado** [comment]
Thanks a lot, Felix!  That's great news.
