### ISSUE TITLE
adding a build system?

### ISSUE THREAD

**Issue by rekado** [FelixKrueger/Bismark#178]
Currently, installing Bismark requires some amount of work for packagers because it does not come with a build system and makes assumptions about the runtime environment.

The use of `$RealBin` to find other files relative to the executables makes it difficult to conform to packaging conventions.  For example, I'm installing `bismark_siterep` to `$prefix/share/bismark/` and not to `$prefix/bin/`, which is what bismark2report expects when it is installed to `$prefix/bin`.

A similar problem is the use of `gzip` and `gunzip` in the code, which assumes that they are available on the user's PATH. 

Would you be willing to accept patches that add a traditional build system that supports a configuration step?  I'm familiar with autotools, which do not impose any extra burden on users as they don't need to have any build system installed.  They can install Bismark the usual way with

    ./configure
    make install

Providing a configuration step ensures that the software can be installed into a separate prefix and keep working even when the assumption of relative paths is invalid at runtime.  It also allows packagers to capture the location of gzip and gunzip at build time instead of assuming their presence at runtime.  This would be achieved by refering to these tools through a placeholder variable that is substituted during the configuration step.

This change would make packaging Bismark more robust and less error-prone.

(I'm maintaining the "bismark" package for GNU Guix, a reproducible package manager.)

**Comment by FelixKrueger** [comment]
Hi @rekado,

Thanks for your suggestions; we can see that the changes you suggest to the build system would make your life easier for maintaining packages. Apart from the fact that I don't actually know anything about packagers such as autotools or how to maintain such a system, we are not convinced that we want to change the way Bismark is "installed", which is in fact simply typing `tar xvf bismark_vX.Y.tar`. 

For clusters like ours where we need to have many different versions of Bismark installed and users load different modules like e.g.: `module load bismark/v0.18.1` I am not sure an installer would actually work at all? 

In the light of this it might probably a better solution if you kept a script that changes the standard Bismark installation folder to the way that works best for the Guix system, wouldn't you agree?

**Comment by rekado** [comment]
Just noticed that I never answered your question:

> For clusters like ours where we need to have many different versions of Bismark installed and users load different modules like e.g.: module load bismark/v0.18.1 I am not sure an installer would actually work at all?

Conventional build systems address this with a configure step.  Traditionally that's done with the `--prefix` argument.  On our cluster we use Guix, which install every package into its own prefix directory, so not only is installation of different versions possible but also of different variants (no matter if the version of the target package differs or not).
