### ISSUE TITLE
Ultra Slow Bowtie2 | No Bam File 

### ISSUE THREAD

**Issue by kkapuria3** [FelixKrueger/Bismark#179]
I am running bismark with `--parallel 3` for *hg19* reference on human files. Everything runs fine.
I now created a mouse reference [mm10](http://hgdownload.soe.ucsc.edu/goldenPath/mm10/bigZips/), and use the exact same pipeline on different sample with this *mm10* reference, but this time, when I run `--parallel 3`, it only runs 3 threads exactly which is usually ~(3 x 5) threads for human runs. I take a subset `head -n 400000` of samples and test it. Its been running since 20 minutes (again 3 threads on `--parallel 3`) which should have been ~40 seconds and ~15 threads running.  I just downloaded the *ensemble* top level reference for *mm10* and preparing it for testing tomorrow. Have you ever got this issue before ?

**Comment by FelixKrueger** [comment]
I don't think I have head about this before. Which mm10 sequence file from the UCSC page was it exactly that you used for the genome preparation?

**Comment by kkapuria3** [comment]
I rebuild the mm10 genome and this time, surprisingly it works. 

The problem was, 

![image](https://user-images.githubusercontent.com/25559534/39867734-5756d4fc-5424-11e8-92fe-6ff56295548f.png) 

which now looks like, 

![image](https://user-images.githubusercontent.com/25559534/39867763-7dcabc8e-5424-11e8-8459-a70039bf5a59.png)

Thanks a lot for your help !

**Comment by FelixKrueger** [comment]
Ah that's interesting, maybe the previous build process was either not finished yet or got interrupted? In any case I am glad it is now working!
