### ISSUE TITLE
no bedGraph output

### ISSUE THREAD

**Issue by baylie1990** [FelixKrueger/Bismark#180]
Hiya,
I have been using the methylation extractor - but don't seem to get a bedGraph output file?
This is how it is running below, no error message:

 *** Bismark methylation extractor version v0.19.0 ***

Setting core usage to single-threaded (default). Consider using --multicore <int> to speed up the extraction process.

Summarising Bismark methylation extractor parameters:
===============================================================
Bismark single-end SAM format specified (default)
Number of cores to be used: 1
Strand-specific outputs will be skipped. Separate output files for cytosines in CpG, CHG and CHH context will be generated
Output will be written to the current directory ('/scratch/rebekah.weatherhead/Bismark-0.19.0')

Summarising bedGraph parameters:
===============================================================
Generating additional output in bedGraph and coverage format
bedGraph format:        <Chromosome> <Start Position> <End Position> <Methylation Percentage>
coverage format:        <Chromosome> <Start Position> <End Position> <Methylation Percentage> <count methylated> <count non-methylated>

Using a cutoff of 1 read(s) to report cytosine positions
Reporting and sorting cytosine methylation information in CpG context only (default)
The bedGraph UNIX sort command will use the following memory setting:   '2G'. Temporary directory used for sorting is the output directory

Checking file >>/scratch/rebekah.weatherhead/Bismark-0.19.0/70_merged_bismark_bt2.bam<< for signs of file truncation...

Writing result file containing methylation information for C in CpG context to CpG_context_70_merged_bismark_bt2.txt.gz
Writing result file containing methylation information for C in CHG context to CHG_context_70_merged_bismark_bt2.txt.gz
Writing result file containing methylation information for C in CHH context to CHH_context_70_merged_bismark_bt2.txt.gz
Now reading in Bismark result file /scratch/rebekah.weatherhead/Bismark-0.19.0/70_merged_bismark_bt2.bam
skipping SAM header line:       @HD     VN:1.0  SO:unsorted
skipping SAM header line:       @SQ     SN:NC_022199.1  LN:31194787
.....

**Comment by FelixKrueger** [comment]
Your genome of interest seems to contain tens of thousands of scaffolds which makes it difficult to write to temporary files as we can do for chromosome based genomes. I recommend you use the option `--scaffolds` to fix this. This is taken from the `bismark2bedGraph` help file:

```
--scaffolds/--gazillion    Users working with unfinished genomes sporting tens or even hundreds of thousands of
                           scaffolds/contigs/chromosomes frequently encountered errors with pre-sorting reads to 
                           individual chromosome files. These errors were caused by the operating system's limit
                           of the number of filehandle that can be written to at any one time (typically 1024; to
                           find out this limit on Linux, type: ulimit -a).
                           To bypass the limitation of open filehandles, the option --scaffolds does not pre-sort
                           methylation calls into individual chromosome files. Instead, all input files are
                           temporarily merged into a single file (unless there is only a single file), and this
                           file will then be sorted by both chromosome AND position using the Unix sort command.
                           Please be aware that this option might take a looooong time to complete, depending on 
                           the size of the input files, and the memory you allocate to this process (see --buffer_size).
                           Nevertheless, it seems to be working.
```

**Comment by baylie1990** [comment]
cheers! that makes sense


Rebekah Weatherhead

PhD Student
Aberystwyth University
IBERS
NRN-LCEE AquaWales Research Cluster
http://aquawales.wix.com/aquawalescluster

________________________________
