### ISSUE TITLE
Strand Information (--NOME-Seq)

### ISSUE THREAD

**Issue by chadi-elfarran** [FelixKrueger/Bismark#182]
Dear Admin,

Greetings. Thank you for creating this wonderful tool. 

I am currently analyzing NOME-Seq libraries. I have a question regarding the strand information in the output of coverage2cytosine. The third column is supposed to be the strand information according to the user guide. However, in the output which I get, the third column is a replica of the second column (third column is position as well! ). Is there something wrong with the way I am processing the libraries? I am processing the NOME-Seq libraries as follows:

$ trim_galore --fastqc input_sample1_R1.fastq.gz

$ bismark --non_directional --genome /path/to/genome/ input_sample1_R1.fastq.gz   (I am mapping the paired end libraries separately as recommended for the NOME-Seq)

$ deduplicate_bismark --bam input_sample1_R1.bismark_bt2.bam

$ bismark_methylation_extractor --CX --gzip --bedGraph input_sample1_R1.bismark_bt2.deduplicated.bam

$ coverage2cytosine --nome-seq --genome_folder /Path/to/gene -o Sample1 Sample1_trimmed_bismark_bt2.deduplicated.bismark.cov.gz

Thank you for your help.

Best Regards,

Chadi

**Comment by FelixKrueger** [comment]
Hi Chadi,

I suspect you are looking at a coverage file and not at the CpG report file. For NOMe-Seq processing you should see the following 4 output files:

```
NOMe.CpG.cov.gz
NOMe.CpG_report.txt.gz
NOMe.GpC.cov.gz
NOMe.GpC_report.txt.gz
```

This will require you to use the latest version of Bismark though. The coverage files will look like this:

```
11	3127598	3127598	100.000000	5	0
11	3127605	3127605	60.000000	3	2
```

And the CpG report files like this:

```
11	3127598	-	5	0	CG	CGG
11	3127605	+	3	2	CG	CGG
```

I hope this helps. Cheers, Felix

**Comment by chadi-elfarran** [comment]
Hi Felix,

This was really informative and helpful.

Thanks a lot.

Best Wishes,

Chadi

**Comment by FelixKrueger** [comment]
Excellent, glad it helped.
