### ISSUE TITLE
bismark_methylation_extractor --comprehensive produces cytosine data, not CpG context data?

### ISSUE THREAD

**Issue by slockton** [FelixKrueger/Bismark#183]
Hi,

I am running bismark_methylation_extractor using --comprehensive --bedGraph on paired-end WGBS data. Studying the *.bismark.cov.gz files, it seems like this is still cytosine data, rather than merged CpG-context data. I was expecting for these pairs of reads to be each collapsed into a single percentage and read count data per CpG.

### Command used:
`bismark_methylation_extractor --comprehensive --merge_non_CpG --bedGraph --parallel 20 --no_overlap --ignore_r2 2 --genome_folder References/hg38-no_alt chr11_deduped_sortedn.bam -o testrun
`

Edit: I'm using bismark v0.19.0

### Output snippet:
chr11   197036  197036  71.4285714285714        5       2
chr11   197037  197037  75      3       1
chr11   197187  197187  87.5    7       1
chr11   197188  197188  100     2       0
chr11   197224  197224  100     11      0
chr11   197225  197225  100     4       0
chr11   197240  197240  91.6666666666667        11      1
chr11   197241  197241  100     5       0
chr11   197256  197256  100     9       0
chr11   197257  197257  100     6       0
chr11   197290  197290  100     4       0
chr11   197291  197291  100     7       0
chr11   197309  197309  100     6       0
chr11   197310  197310  100     7       0
chr11   197344  197344  100     7       0
chr11   197345  197345  100     9       0
chr11   197350  197350  100     7       0
chr11   197351  197351  100     9       0
chr11   197455  197455  100     8       0
chr11   197456  197456  100     10      0
chr11   197472  197472  100     6       0
chr11   197473  197473  88.8888888888889        8       1
chr11   197507  197507  100     10      0
chr11   197508  197508  100     10      0
chr11   197531  197531  100     9       0
chr11   197532  197532  90.9090909090909        10      1
chr11   197552  197552  100     8       0
chr11   197553  197553  100     13      0
chr11   197576  197576  100     4       0
chr11   197577  197577  72.7272727272727        8       3
chr11   197590  197590  100     4       0
chr11   197591  197591  90.9090909090909        10      1

Is this expected behavior? From what I can tell, this is the methylation read count of the C in the CpG on one strand and also the corresponding C in the CpG on the opposite strand. I was hoping these would be merged (as CpG methylation is symmetrical) to sum the read counts for each symmetrical CpG.

Am I doing something wrong, or making some incorrect assumptions about how the program works?

Thanks,
Steve

**Comment by FelixKrueger** [comment]
Hi Steve,

This behaviour is indeed expected. The methylation extraction will generate a coverage file which is at single cytosine resolution. If you wanted to merge the CpGs from both strands you could in addition run `coverage2cytosine` on the data, which does the following:

```
--merge_CpG              Using this option will post-process the genome-wide report to write out an additional coverage
                         file (see above for the coverage file format) which has the top and bottom strand methylation
                         evidence pooled into a single CpG dinucleotide entity. This may be the desirable input format
                         for some downstream processing tools such as the R-package bsseq (by K.D. Hansen). An example would be:

			   genome-wide CpG report (old)
			   gi|9626372|ref|NC_001422.1|     157     +       313     156     CG
			   gi|9626372|ref|NC_001422.1|     158     -       335     156     CG
			   merged CpG evidence coverage file (new)
			   gi|9626372|ref|NC_001422.1|     157     158     67.500000       648     312

			 This option is currently experimental, and only works if CpG context only and a single genome-wide report
                         were specified (i.e. it doesn't work with the options --CX or --split_by_chromosome).
                         If --zero_based was specified as well the output coverage file is in zero-based half-open format like
                         bedGraph files.
```

This kind of report is then strictly based on the reference sequence, and is probably the functionality you were looking for? Just run `coverage2cytosine --help` to get more information about how to invoke it.

Let me know if you have any questions. Felix

**Comment by FelixKrueger** [comment]
Incidentally, `coverage2cytosine --merge` produces a coverage file as well, so that should be all you need as input for BiSeq. All the best! Felix

**Comment by slockton** [comment]
Excellent! Thanks for your help.

S
