### ISSUE TITLE
Enable --no-discordant flag

### ISSUE THREAD

**Issue by caalo** [FelixKrueger/Bismark#185]
Hi Bismark team,

I'd like to invoke the --no-discordant flag in my alignment, and I'm not sure how to switch the flag. I am getting an error of: 
`Unknown option: no-discordant
Please respecify command line options`

from my command (the brackets are from a Snakemake script):
`Bismark_v0.19.0/bismark --bowtie2 Bismark_v0.19.0/genome_preparation/ -1 {input.fastq1} -2 {input.fastq2} --basename {params.sample_id} -o {params.folder} --no-discordant`

Do I have to go into Bowtie2 to enable this option?

Thanks,
Chris

**Comment by FelixKrueger** [comment]
Hi Chris,

Even though it seems quite straight forward to enable `--no-discordant`, I'm afraid it doesn't work like this in the current implementation as it would completely break all sorts of downstream processing within Bismark.

May I ask what is it exactly that you would like to achieve with this option? Would you like to be able to simply align more reads when only one of the partner reads doesn't align well for whatever reason, or would you like to detect reads that align to different parts of the genome? 

In these cases we have in the past used the option `--unmapped` for the paired-end mapping step, and then run single-end alignments for the unmapped R1 (default mode, directional) and R2 (`--pbat` mode) reads separately. You could then pair up R1 and R2 to create virtual Hi-C files to see where partner reads end up if both of them align single-end mode but not in a concordant fashion. I hope this helps. Felix

**Comment by caalo** [comment]
Hi Felix,

I'm interested in using `--no-discordant` as I am finding a substantial fraction of our reads being mapped as "tandem" when using bsmap. Tandem aligned read pairs face the same direction, and overlap each other almost completely, giving small to no insert size.
<img width="190" alt="screen shot 2018-06-21 at 8 38 04 am" src="https://user-images.githubusercontent.com/17771008/41729596-789f0e42-752e-11e8-93a9-3237f80400e4.png">

Bsmap keeps these tandem aligned reads, whereas these reads (searching by read ID) are not found in Bismark, which I presume to be tossed out. I was wondering if  `--no-discordant` could align these reads so that I can use Bismark and also quantify the fraction of tandem aligned reads in our samples.

**Comment by FelixKrueger** [comment]
This looks a bit weird, why would you ever have read pairs like this in your library? 

As long as the reads are not so repetitive that they are getting tossed out entirely you should be able to align them in single-end mode and then pair them up by read ID. This is the nearest you can get in Bismark to a discordant read. If you generate these Hi-C like files you should see very quickly (e.g. in SeqMonk) where the odd pairs come from and how they behave. If you have further questions about getting this going I could also send you a script to pair-up the SE reads from BAM files. Alternatively you could also send me a fraction of your reads and I give it a go over here and send you an update. Cheers, Felix

**Comment by caalo** [comment]
Hi Felix,

It's pretty weird for us too -- it seems to be happening at high rates with our cell-free DNA samples for some reason (relative to gDNA samples).

Our guess is that bisulfite treatment is creating breaks in our libraries such that some of the broken fragments are ligating back to each other to create molecules with functional p5, p7 ends that can be PE sequenced. In the case when the ligation process is two unrelated molecules, that would create chimeric reads. In the case when the ligation process is the OT and OB strands of the same molecule, a tandem phenotype is possible.

I'd be interested to try your way to pull out these reads. Either options works: getting a script from you or sending over R1, R2 SE mapped bams to you. What's easier for you?

How does Bismark deal with chimeric reads? Would Picard's InsertSizeMetrics be able to quantify them?

**Comment by FelixKrueger** [comment]
Frankly, Bismark is not exactly made for really weird situations, so chimaeric reads are indeed a problem as they are not reported at all in paired-end mode (see also this [article](https://sequencing.qcfail.com/articles/pbat-libraries-may-generate-chimaeric-read-pairs/) where I describe how we dealt with chimaeric reads in PBAT data).

How about you send me an [email](felix.krueger@babraham.ac.uk) and I set up and FTP site for your where you can upload your reads. Once I have got the pairing-up script working with your data I can then share it with you for potential future use.

**Comment by caalo** [comment]
Thanks for letting me know -- I'll look into your article. I'll send over the data in about a week as I'm a bit swamped on my side for now.

**Comment by caalo** [comment]
Hi Felix,

It's a little bit tricky to send you the data right now, as we're working with patient data -- I'm trying to get approval to send you part of the single-end realigned data. Meanwhile, if you have an existing script that can help pair up these single-end realigned data, would you be willing to share with me?

Thanks again,
Chris

**Comment by FelixKrueger** [comment]
Hi Chris,
Don't worry if it too tricky to share the data. Here is a script which I use every so often, you might need to adapt the regex for the read ID a little to work for your specific files. In case you are having trouble getting it to work it would be sufficient to provide 2 or so reads from a BAM file where you can edit the Sequence to NNNNNNN or whatever, I just need to see the read IDs.

Cheers, Felix
[repair_SE_BAM.zip](https://github.com/FelixKrueger/Bismark/files/2248503/repair_SE_BAM.zip)

**Comment by caalo** [comment]
Hi Felix,

The script worked nicely and I was able to get the needed analysis done. Thanks for all the help and quick responses!

**Comment by FelixKrueger** [comment]
Perfect, thanks for the feedback.
