### ISSUE TITLE
--cytosine_report option in methylation extractor doesn't find coverage file

### ISSUE THREAD

**Issue by QGouil** [FelixKrueger/Bismark#188]
Hi Felix,
in v0.19.1 (and previous versions), when running 
`bismark_methylation_extractor -p -o "$LIBNAME"_extraction --no_overlap --ignore_r2 2 --comprehensive --cytosine_report --CX --bedGraph --buffer_size 10G --genome_folder $GENOME_FOLDER --gzip --multicore 2 "$LIBNAME"_1_val_1_bismark_bt2_pe.deduplicated.bam`
the outputs are correctly written in "$LIBNAME"_extraction, but the cytosine report stage fails 

> gzip: LIB_1_val_1_bismark_bt2_pe.deduplicated.bismark.cov.gz: No such file or directory

I think because it's looking for the coverage infile in the current directory rather than in "$LIBNAME"_extraction.

**Comment by FelixKrueger** [comment]
I believe the problem is that the methylation extractor does not create the folder for you in case it doesn't exist. If you select a previously existing output directory it all seems to work fine. I'll add the directory creating when I find time. Thanks, Felix

**Comment by santhilalsubhash** [comment]
Hi,

**### Issue:**

Your fix from "**02 July 2018**" did not resolve this issue. Still the 'bismark_methylation_extractor' could not find the coverage file and **'.CX_report.txt**' file is empty.

**### Command line:**

`bismark_methylation_extractor --comprehensive --output $outdir --paired-end --parallel 10 --bedGraph --CX_context --buffer_size 85% --cytosine_report --genome_folder $index_dir $inpath/${outname}_p1_val_1_bismark_bt2_pe.deduplicated.bam
`

**### Logs from the run:** 

> Summarising Bismark methylation extractor parameters:
> ===============================================================
> Bismark paired-end SAM format specified (default)
> Number of cores to be used: 10
> Strand-specific outputs will be skipped. Separate output files for cytosines in CpG, CHG and CHH context will be generated
> Output path specified as: /proj/myserver/myname/myproject/reanalysis/Methyl-seq/Stage1/WGBS/methcall/sample1/
> 
> 
> Summarising bedGraph parameters:
> ===============================================================
> Generating additional output in bedGraph and coverage format
> bedGraph format:	<Chromosome> <Start Position> <End Position> <Methylation Percentage>
> coverage format:	<Chromosome> <Start Position> <End Position> <Methylation Percentage> <count methylated> <count non-methylated>
> 
> Using a cutoff of 1 read(s) to report cytosine positions
> Reporting and sorting methylation information for all cytosine context (sorting may take a long time, you have been warned ...)
> The bedGraph UNIX sort command will use the following memory setting:	'85%'. Temporary directory used for sorting is the output directory
> 
> 
> Summarising genome-wide cytosine methylation report parameters:
> ===============================================================
> Generating comprehensive genome-wide cytosine report
> (output format: <Chromosome> <Position> <Strand> <count methylated> <count non-methylated>  <C-context>  <trinucleotide context> )
> Reporting methylation for all cytosine contexts. Be aware that this will generate enormous files
> Using 1-based genomic coordinates (default)
> Genome folder was specified as /proj/myserver/myname/dbs/hg38/hESC_project/ensembl_genome/bismark_index/
> 
> Checking file >>/proj/myserver/myname/myproject/reanalysis/Methyl-seq/Stage1/WGBS/aligned/sample1/sample1_p1_val_1_bismark_bt2_pe.deduplicated.bam<< for signs of file truncation...
> 
> 
> Now testing Bismark result file /proj/myserver/myname/myproject/reanalysis/Methyl-seq/Stage1/WGBS/aligned/sample1/sample1_p1_val_1_bismark_bt2_pe.deduplicated.bam for positional sorting (which would be bad...)	...passed!
> Writing result file containing methylation information for C in CpG context to /proj/myserver/myname/myproject/reanalysis/Methyl-seq/Stage1/WGBS/methcall/sample1/CpG_context_sample1_p1_val_1_bismark_bt2_pe.deduplicated.txt
> Writing result file containing methylation information for C in CHG context to /proj/myserver/myname/myproject/reanalysis/Methyl-seq/Stage1/WGBS/methcall/sample1/CHG_context_sample1_p1_val_1_bismark_bt2_pe.deduplicated.txt
> Writing result file containing methylation information for C in CHH context to /proj/myserver/myname/myproject/reanalysis/Methyl-seq/Stage1/WGBS/methcall/sample1/CHH_context_sample1_p1_val_1_bismark_bt2_pe.deduplicated.txt
> 
> ...
> ...
> .....[SHORTENED]
> 
> 
> 
> Finished BedGraph conversion ...
> 
> Output will be written into the directory: /disk/proj/myserver/myname/myproject/reanalysis/Methyl-seq/Stage1/WGBS/methcall/sample1/
> Summary of parameters for genome-wide cytosine report:
> ==============================================================================
> Coverage infile:				sample1_p1_val_1_bismark_bt2_pe.deduplicated.bismark.cov.gz
> Output directory:				>/disk/proj/myserver/myname/myproject/reanalysis/Methyl-seq/Stage1/WGBS/methcall/sample1/<
> Parent directory:				>/disk/proj/myserver/myname/myproject/reanalysis/Methyl-seq/Stage1/WGBS/scripts/bscripts/<
> Genome directory:				>/proj/myserver/myname/dbs/hg38/hESC_project/ensembl_genome/bismark_index/<
> CX context:					yes
> Genome coordinates used:			1-based (default)
> GZIP compression:				no
> Split by chromosome:				no
> 
> 
> Now reading in and storing sequence information of the genome specified in: /proj/myserver/myname/dbs/hg38/hESC_project/ensembl_genome/bismark_index/
> 
> chr 1 (248956422 bp)
> chr 10 (133797422 bp)
> chr 11 (135086622 bp)
> chr 12 (133275309 bp)
> chr 13 (114364328 bp)
> chr 14 (107043718 bp)
> chr 15 (101991189 bp)
> chr 16 (90338345 bp)
> ...
> ....
> .....[SHORTENED]
> 
> 
> Stored sequence information of 194 chromosomes/scaffolds in total
> 
> ==============================================================================
> Methylation information will now be written into a genome-wide cytosine report
> ==============================================================================
> 
> >>> Writing genome-wide cytosine report to: sample1_p1_val_1_bismark_bt2_pe.deduplicated.CX_report.txt.CX_report.txt <<<
> 
> **gzip: sample1_p1_val_1_bismark_bt2_pe.deduplicated.bismark.cov.gz: No such file or directory**
> **No last chromosome was defined, something must have gone wrong while reading the data in (e.g. specified wrong file path for a gzipped coverage file?). Please check your command!**
> 
> 
> 
> Finished generating genome-wide cytosine report


Please let me know if I am doing anything wrong.

**Comment by FelixKrueger** [comment]
This was an issue with the parent directory that is passed on to `coverage2cytosine` (it was the parent directory where you started off with the methylation extraction, but for the cytosine report generation this is not actually relevant, so I changed it to what you specified as `--output $outdir`). Can you please clone the latest development version and see if the very same command you mentioned above is now working? Thanks for reporting this. Best, Felix

Fixed in 7db05a615306a29dbeac888979b8189604788421.

**Comment by santhilalsubhash** [comment]
Hello Felix,

Thanks a lot for your quick fix. It was so helpful. With your current fix [7db05a6](https://github.com/FelixKrueger/Bismark/commit/7db05a615306a29dbeac888979b8189604788421), it woks fine now.

**Comment by FelixKrueger** [comment]
Excellent, thanks for the feedback.
