### ISSUE TITLE
Test  data- not in fastq format

### ISSUE THREAD

**Issue by chrisb56** [FelixKrueger/Bismark#189]
Hello, I am trying to run Bismark on the test data set to get the hang of things. After preparing the reference genome and running bismark I keep getting the following error:

Single-end alignments will be performed
=======================================

Input file is in FastQ format
Writing a C -> T converted version of the input file testdata.fasta to testdata.fasta_C_to_T.fastq
Input file doesn't seem to be in FastQ format at sequence 1: Inappropriate ioctl for device

I tried two different reference genomes but got the same results. I feel like this is a simple fix but I can't figure out what the problem is. Any help would be greatly appreciated.

**Comment by FelixKrueger** [comment]
I can't be exactly sure but the filename seem to be giving it away:

... input file `testdata.fasta` ... not in FastQ format...

Any chance that the test data in in `FastA` format instead? I don't know where you got the test data from, but there are now 2 options:

1. Either you specify the option `-f` to work with FastA formatted data, or
2. You get some FastQ formatted test data, e.g. the one that comes with Bismark: https://github.com/FelixKrueger/Bismark/blob/master/test_data.fastq

And try again. Hope this helps, Cheers, Felix

**Comment by chrisb56** [comment]
Hey, the test data is the one that comes with Bismark. I just changed the file name to see if that would fix the problem but got the same error.

**Comment by FelixKrueger** [comment]
Hmm, I guess you may have pulled down the data in a weird form then. I just clicked the link above, then clicked `View Raw` which opens the FastQ reads in a website. I then did select all, pasted it in a text file on our cluster and Bismark or FastQC produce fine runs within 2 mins. You don't necessarily need exactly this file, just and few lines of FastQ data should work all the same for testing purposes...

**Comment by FelixKrueger** [comment]
How did you get on?
