### ISSUE TITLE
--non_directional and --pbat  ?

### ISSUE THREAD

**Issue by hmyh1202** [FelixKrueger/Bismark#190]
Hi, Felix：

what is the different between --non_directional and  --pbat ?

I had test the  parameter， and the mapping ratio is similar, when using 20000 reads as input.

My single cell  methylation library is also Post-Bisulfite Adapter Tagging method, so what should I select that parameters? Besides, what should I do when do mapping using single end reads, such as read1 and read2 data.
 
Thank U！

**Comment by FelixKrueger** [comment]
The option `--pbat` will only align reads to two strands, namely the CTOT and CTOB strands. In contrast, the option `--non_directional` will align the reads to all four possible strands: OT (original top), CTOT (complementary to OT), OB (original bottom), and CTOB (complementary to OB). 

For library constructions following the protocol for scBS-Seq then we often saw mapping ratios of roughly `1:2:2:1` (`OT:CTOT:CTOB:OB`), which protocol did you use? 

We often proceeded aligning the data in single-end mode (after trimming), and then merged the methylation calls from both R1 and R2 for the bedGraph and coverage file generation, e.g. like so:

`bismark2bedGraph -o merged_R1_R2 CpG*`

**Comment by hmyh1202** [comment]
OK， thank you!
In many related scBS-seq paper, thy also used the unmapped single reads for mapping.

In my study, I had used the --non_directional for both PE mapping and unmapped single reads mapping, and BAM files was merged by using samtools merge, and followed by duplication by samtools in SE mode( -s and -S， for both PE and SE in the merged SAM file ). And bismark_methylation_extractor was used for mC calling.

So, was that rigth ? My quenstion is that FuChouTang alway use that umapped single end reads for alignement, however if the PE and SE alignment results could result ambiguous mC.

Thank you!

**Comment by hmyh1202** [comment]
And are there some reference paper for your align  style ?

**Comment by FelixKrueger** [comment]
Not sure how many single-cell methods are currently out there, but I thought there were mainly the scRRBS methods by Fuchou Tangs's group (which require default, directional alignments), and the scBS-seq method and its parallel expression and accessibility derivates:

scBS-seq: https://www.ncbi.nlm.nih.gov/pubmed/25042786
scBS-seq (protocol): https://www.ncbi.nlm.nih.gov/pubmed/28182018
scM&T-seq: https://www.ncbi.nlm.nih.gov/pubmed/26752769
scNMT-seq: https://www.nature.com/articles/s41467-018-03149-4

In all those studies we didn't even start with paired-end alignments but treated Read 1 and Read 2 independently of each other, and merged the data after mapping (this should all be mentioned in the methods of the mentioned papers). So the order of tools for both R1 and R2 would be:
1) Trim with Trim Galore (SE mode)
2) Align with Bismark (`--non_directional`, SE mode)
3) deduplicate_bismark (SE mode)
4) methylation extraction
5) merge all CpG calls from R1 and R2, and run `bismark2bedGaph`
6) use the coverage file for data analysis

I hope this helps.

**Comment by hmyh1202** [comment]
Thanks a lot
