### ISSUE TITLE
DIfference in numbers of Final Cytosine Methylation Report

### ISSUE THREAD

**Issue by luisafb** [FelixKrueger/Bismark#194]
Hi, 
I'm finding differences between the "Total number of C's  analysed" and the total sum of "Total methylated/unmethylated C's in each context". I supossed the number should be equal, for example:

Total number of C's   analysed | 1,495,716,701

Total methylated C's in CpG context | 108,808,074
Total methylated C's in CHG context | 76,164,926
Total methylated C's in CHH context | 145,558,968
Total methylated C's in Unknown context | 2,229
  |  
Total unmethylated C's in CpG context | 36,442,993
Total unmethylated C's in CHG context | 64,350,348
Total unmethylated C's in CHH context | 1,064,391,392
Total unmethylated C's in Unknown context | 6,776
  |  
Sum meth/unmeth in each context | 1,495,725,706
Difference | 9,005

Do you know what does it mean these 9,005 ??

Thanks in advance!

Luisa

--

**Comment by FelixKrueger** [comment]
Hi Luisa,

Don't the numbers of Cs found methylated (2229) and unmethylated (6776) add up to exactly those missing 9005 calls that are missing? 

The cytosine context is called unknown whenever there was either an `N` immediately nearby in the genome, i.e. `CN` or `CHN` context, or - and this is by far the more likely scenario - when there was in insertion right downstream of the C in question (insertions get treated as `Ns` in the reference).

I hope this clears things up?

**Comment by luisafb** [comment]
Hi Felix,
Thanks for your answer!
You are right, I though the Unknown context was included in the Total number of C's analysed. Now is clear!
Thank you,
Luisa
