### ISSUE TITLE
error in plotly newPlot call

### ISSUE THREAD

**Issue by scholtalbers** [FelixKrueger/Bismark#196]
There is a small error on the `newPlot()` call which causes the buttons to not be removed (in case you really want them removed :) ):
https://github.com/FelixKrueger/Bismark/blob/cf9f74bf2f4dae9ef926fce9dae4e7b2bbaea4e6/plotly/plotly_template.tpl#L968 

Should be:
```
Plotly.newPlot('mbias1_plot', data, layout, {displaylogo: false, modeBarButtonsToRemove: ['toImage',
```

**Comment by FelixKrueger** [comment]
Thanks for that, I realised recently that newPlot() only accepts 4 arguments, I will amend it once I am back from holiday.
