### ISSUE TITLE
Do I have to use --score-min L,0,-0.6 for newer version of Bismark?

### ISSUE THREAD

**Issue by bishwaG** [FelixKrueger/Bismark#197]
Hi,
In some of the older versions of Bismark I have used Bowtie parameter `--score-min L,0,-0.6` as suggested by the manual. It is not mentioned in the manual of newer version of Bismark. WHen I tried running bismark without `--score-min` I got really low mapping rate. Is it recommended to use it anyways?

**Comment by FelixKrueger** [comment]
By default, Bismark is run with `--score_min L,0,-0.2`. This is quite a stringent setting, and may be relaxed of you have a good reason for it, e.g. a low quality reference genome or of you know that your reads are likely to suffer from sequencing errors. In any case, you should make sure the reads are properly trimmed to start with. Sorry for the late reply, but I am currently on holiday...

**Comment by bishwaG** [comment]
Hi @FelixKrueger,
I have used `Bismark v0.15.0 `with parameters `--score-min L,0,-0.2 --ignore-quals`. I used the same data using `Bismark v0.19.1` without any parameters. Version `0.19.1` produced almost half the number of uniquely mapped reads compared to `0.15.0`. Should such big different in alignment be expected?

**Comment by FelixKrueger** [comment]
No I don't think you would expect such a big difference. I would expect some differences with regards to ambiguous alignments, but that should only affect a small number of reads.

A few things that spring to my mind:
- is there a chance your libraries are non directional and you used `--non_directional` previously? (This would nicely explain half of the mapping rate)
- is there a chance that the reads were not trimmed appropriately before aligning this time round? If not just run them through Trim Galore once more.
- is there a chance you ran out of memory this time and one of the assignment threads got killed? You should be able to check this in the error log or by looking at the number of alignments for the different stands.

Sorry for my slow replies at the moment but I am traveling. Best, Felix
