### ISSUE TITLE
Documentation missing for deduplicate_bismark

### ISSUE THREAD

**Issue by ewels** [FelixKrueger/Bismark#199]
Perhaps I'm going blind in my old age, but I can't find any documentation about the `deduplicate_bismark` command...

**Comment by FelixKrueger** [comment]
Don't worry Old Friend, it's not you, it's me...! Will add some documentation soon.

**Comment by FelixKrueger** [comment]
I have now added the deduplication step to the [README](https://github.com/FelixKrueger/Bismark/blob/master/Docs/README.md#iii-bismark-deduplication-step) file and the [Bismark User Guide](https://rawgit.com/FelixKrueger/Bismark/master/Docs/Bismark_User_Guide.html#iii-bismark-deduplication-step). Cheers, Felix

**Comment by ewels** [comment]
![yay](https://media.giphy.com/media/wZaoi0FCUFD6U/giphy.gif)
