### ISSUE TITLE
Interesting M-bias pattern

### ISSUE THREAD

**Issue by caalo** [FelixKrueger/Bismark#200]
Hi Felix,

Another question for you -- I'm looking at M-bias for my samples (8-10x WGBS) and I'm noticing that there is definitely a dropoff of methylation at the start of the read, but it goes back up continuously rather than a sharp increase, over 20-25bp. This looks somewhat different than your [post illustrating M-bias](https://sequencing.qcfail.com/articles/library-end-repair-reaction-introduces-methylation-biases-in-paired-end-pe-bisulfite-seq-applications/). Have you seen anything like this before and do you have any recommendation on read clipping? I'm looking at read 2 here, but also included the read 1 plot. 

![fc19311298-01feb17sr_hsbs-wgbs_high markduplicates sorted m-bias_r2](https://user-images.githubusercontent.com/17771008/45268278-9e851680-b447-11e8-87c3-c8238a14c247.png)
![fc19311298-01feb17sr_hsbs-wgbs_high markduplicates sorted m-bias_r1](https://user-images.githubusercontent.com/17771008/45268279-9e851680-b447-11e8-9a01-3567d65f6204.png)

Thanks,
Chris

**Comment by FelixKrueger** [comment]
Wow this looks really weird, and more worryingly: it looks quite different from what R1 is doing. It is almost  certain that combing Read 1 and Read in this case will introduce a LOT of variability almost independently of which kind of threshold you are setting. Which kind of kit was that? Maybe it would be worth getting back to the manufacturer and ask them what they think might be going on?

**Comment by caalo** [comment]
Hi Felix,

Upon a bit more digging, this phenomena is only specific to cell-free DNA (cfDNA): our gDNA samples do not exhibit this pattern.  All of our cfDNA and gDNA samples were treated with [Zymo EZ Methylation lightning kit](https://www.zymoresearch.com/ez-dna-methylation-lightning-kit). I also have been looking at cfDNA WGBS samples from other publications who used a [Qiagen Epitect](https://www.qiagen.com/us/shop/epigenetics/epitect-bisulfite-kits/#orderinginformation), and they exhibit the same phenomena. Ours is labeled "in-house", whereas the other publication is labeled as "external":

![screen shot 2018-09-10 at 1 45 56 pm](https://user-images.githubusercontent.com/17771008/45314498-e798a180-b4ff-11e8-9851-79e21f8b31ab.png)

And here is our gDNA:

![fc19269698-09jan2017sr_wgbs-wgbs_high markduplicates sorted m-bias_r2](https://user-images.githubusercontent.com/17771008/45314635-452cee00-b500-11e8-8cd0-b73d50541723.png)
![fc19269698-09jan2017sr_wgbs-wgbs_high markduplicates sorted m-bias_r1](https://user-images.githubusercontent.com/17771008/45314636-452cee00-b500-11e8-8e42-e8f359d2ce2c.png)


This observation seems to be specific to cfDNA regardless of kit used. However, I don't see any reason why R1 and R2 should have noticeably different methylation patterns, especially if there is 50/50 strand balance.
