### ISSUE TITLE
bin folder in the releases

### ISSUE THREAD

**Issue by IsmailM** [FelixKrueger/Bismark#204]
Hey, 

For future releases, it would be easier if you place all the binaries in a `bin` folder - this would make it easier for people to add the folder to their $PATH variable...

**Comment by FelixKrueger** [comment]
Hi Ismail,

All the executables are already in a single folder, e.g. `bismark_v0.20.0`, so adding a new folder `bin` to that would really only add some (admittedly only five) extra characters to the command that adds the folder to the $PATH, or am I missing something? Cheers, Felix

**Comment by IsmailM** [comment]
Hey Felix, 

The issue with this is that there are many non-executable files that would be added to the $PATH this way - i.e., the following:

```
Bismark_alignment_modes.pdf  CHANGELOG.md  _config.yml  Docs  license.txt  README.md  test_data.fastq
```

The $PATH is not supposed to contain non-executable files and as such, by definition, it would be more "correct" to create a bin folder and add that to the $PATH.

Nonetheless, this isn't too important - users for whom this an issue, should be able to create a bin folder and move all executables into it. Personally, I simply created a bin folder and created symlinks to the original binaries...

Many Thanks,
Ismail

**Comment by FelixKrueger** [comment]
Oh I see, that makes indeed sense. You seem to already have a solution in place, but I'll keep it in mind (and maybe move non-executable files to folders such as Docs). Thanks for the tip!
