### ISSUE TITLE
Release 0.20.0 reports version as 0.19.1

### ISSUE THREAD

**Issue by jjv5** [FelixKrueger/Bismark#206]
` curl -kLO https://github.com/FelixKrueger/Bismark/archive/0.20.0.tar.gz
 tar zxf 0.20.0.tar.gz
 cd Bismark-0.20.0/
 $ ./bismark --version

          Bismark - Bisulfite Mapper and Methylation Caller.

                       Bismark Version: v0.19.1
        Copyright 2010-18 Felix Krueger, Babraham Bioinformatics
              www.bioinformatics.babraham.ac.uk/projects/
                https://github.com/FelixKrueger/Bismark`

**Comment by FelixKrueger** [comment]
Thanks for that, this has already been updated for the development version in August (46119cc01641c56ca58a52d28edb92083a32d97d) and will make it's way into the next release.
