### ISSUE TITLE
Subsampling bam files

### ISSUE THREAD

**Issue by mtanic** [FelixKrueger/Bismark#207]
Hi Felix,

I have a few questions regarding subsampling bam files and I was hoping you have some experience or ideas how to go about it. 

I am comparing a bunch of different targeted BS-sequencing platforms and want to normalize my 100bp PE samples to cap at 60M raw reads (some samples have less reads).  I have already aligned all of the samples (n=80) and deduplicated them.

I was wondering if it makes sence to downsample unsorted bam files or if that would introduce bias in  downstream duplication rates and methylation stats?
In other words, would I end up having the same duplication rates and methylation percentages if I were to subsample bam files versus subsampling FASTQ files and mapping again?

Example:  
Bismark report -Agilent_253J 
Total Reads	Aligned Reads	Mapping efficiency: 	Unaligned Reads	Ambiguously Aligned Reads	No Genomic Sequence
55,179,593	42,202,482	76.5%	11,815,567	1,161,544	0
 
But from flagstat it seems that bam containes only uniquely aligned read pairs:
samtools flagstat Agilent_253J_R1_val_1_bismark_bt2_pe.bam
84404964 + 0 in total (QC-passed reads + QC-failed reads)
0 + 0 secondary
0 + 0 supplementary
0 + 0 duplicates
84404964 + 0 mapped (100.00%:-nan%)
84404964 + 0 paired in sequencing
42202482 + 0 read1
42202482 + 0 read2
84404964 + 0 properly paired (100.00%:-nan%)
84404964 + 0 with itself and mate mapped
0 + 0 singletons (0.00%:-nan%)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)

Sorry for the long email and thanks in advance!

Miljana

**Comment by FelixKrueger** [comment]
Hi Miljana,

If you really have to down-sample the reads I think you should be able to do it various stages during the processing. The FastQ files are not sorted in a specific way (apart from the fact that at the very start you will probably get reads from the edge tiles of the flowcell which might have somewhat lower quality scores), so the order of the resulting BAM files should also have no influence of the results in any way. 

Therefore I would suggest that you sub-sample at the stage of deduplicated alignments (as long as your data type allows de-duplication (amplicon, RRBS or target captured data should probably not be deduplicated...), and then re-run the methylation extraction and coverage conversion thereafter. Does this help at all?

**Comment by mtanic** [comment]
Thank you Felix, that resolved some doubts I had. I will subsample from deduplicated bams then.

I am not deduplicating RRBS files (except Nugen’s using UMIs), but manufacturers of other platforms recommend deduplication. The captured regions size (80 - 130 Mb) should be large enough to support this, wouldn’t you agree?

 

Cheers,

Miljana

**Comment by FelixKrueger** [comment]
Hi Miljana,

I’m glad this helped. And yes, I would agree that the size of the captured regions sounds like it is plenty big enough to justify deduplication.

All the best, Felix
