### ISSUE TITLE
Bismark PE/SE directional and non-directional alignments

### ISSUE THREAD

**Issue by digrigor** [FelixKrueger/Bismark#208]
Hi Felix,

I am trying to analyse RRBS data which were produced using the Diagenode Premium RRBS Sequencing Kit. The produced RRBS paired-end libraries were run in an Illumina Next-Seq 500 sequencer and the produced reads are of 76bp length.

QC of the reads:
-Great sequencing quality
-Almost all Reads pair 1 (R1) start with TGG or CGG (because they were derived from OT or OB)
-Almost all Reads pair 2 (R2) start with CAA (because they were derived from CTOT or CTOB)

Trimming with Trim Galore!:
--non_directional --rrbs --paired -phred33 -q 30 --retain_unpaired -o
The adaptors were removed correctly - The artificial bases were removed correctly - The quality was increased

Alignment using Bismark:
When running the alignments I get:

- PE non-directional: 53.2% mapping efficiency (ME):
                                CT/GA/CT:	839578	((converted) top strand)
                                GA/CT/CT:	481	(complementary to (converted) top strand)
                                GA/CT/GA:	812	(complementary to (converted) bottom strand)
                                CT/GA/GA:	842955	((converted) bottom strand)
- PE directional: 53.2% ME:
                      similar stats as above (0s in the CTOT/CTOB)
- R1 SE directional: 69.7% ME
- R2 SE non-directional: 67.7% ME
                     they only align to CTOT/CTOB
- R2 SE directional: 1.6% ME

My question is:
How is it possible for my R2 reads to align in the OT/OB strands when running PE directional alignment (ME: 53.2%)  and not to align in the OT/OB strands when running SE directional alignment? Please also take into consideration that R2 reads clearly align to the CTOT/CTOB strands when running SE non-directional alignment (ME: 67.7% and the report clearly indicates that they only align to CTOT/CTOB).

Thank you very much,

All the best,
Dio

**Comment by FelixKrueger** [comment]
Hi Dionysios,

Thanks for the comprehensive questions. I think you are making your life a little unnecessarily complicated here, I'll try to make it a bit clearer.

    - Almost all Reads pair 1 (R1) start with TGG or CGG (because they were derived from OT or OB)
    - Almost all Reads pair 2 (R2) start with CAA (because they were derived from CTOT or CTOB)

This is a clear indication that your libraries are **directional**. The only thing I would add to this is, is that `R2.... were derived from CTOT or CTOB` is a bit misleading in the context of paired-end sequencing:
While it is true that the reads look like CTOT or CTOB, they are merely the reverse complement of R1, and it is R1 which determines the type of library (and thus the processing you need to carry out). So all you need to get out of the initial QC is is that the libary is directional, Trim Galore and Bismark will take care of everything else.

That means that the trimming you need to carry out will be (ideally with TrimGalore v0.5.0+):
`trim_galore --rrbs --paired file_R1.fastq.gz file_R2.fastq.gz`

The alignment will then be:
`bismark --genome /your/genome/ -1 file_R1_val_1.fq.gz -2 file_R2_val_2.fq.gz`


I think the main confusion comes from the fact that single-end alignments of R2 taken on its align to the CTOT and CTOB strands, isn't that right? I think the answer to this is mystery is simply that Bismark figures R2 in as the other end of a pair, and as I mentioned above, R1 determines which strand aligns to. In other words: don't worry, it's all being taken care of!


There is a discrepancy in mapping efficiency between PE and SE alignments of almost ~15%. This is something that I cannot easily explain, there seems to be something in the data that prevents reads from mapping concordantly as a pair, but reads do align in single-end mode. I think the options here are 
- see if the different trimming mode has an influence on the stats
- relax the `--score_min` function somewhat for the paired-end alignments, e.g. to `--score_min L,0,-0.4`
- you could also think of specifying `--unmapped` during the PE alignment steps, and then use the unmapped reads in single-end mode to get the most out of your data. The commands for the SE data would then be:

**R1**:
`bismark --genome /your/genome/ R1_unmapped.fq.gz`

**R2**:
`bismark --genome /your/genome/ --pbat R2_unmapped.fq.gz`

This might yield some more data in the end, but you would have to treat the unmapped reads differently for the alignment and extraction steps. Once the methylation calls have been extracted from both the PE and SE files separately you could feed them both to the coverage file generation like so:

`bismark2bedGraph -o PE_and_SE_merged.coverage CpG*`

I hope this answers your initial question? Feel free to ask further questions, either here or via email. 
All the best, Felix

**Comment by digrigor** [comment]
Hi Felix, 

This answers my questions. Thank you very much for your prompt and helpful response.

Have a nice weekend,
Dionysios

**Comment by FelixKrueger** [comment]
Excellent, you too!

**Comment by FelixKrueger** [comment]
Hi Dio,

From what people report it doesn't seem to be all that uncommon that something happens during the library preparation or the sequencing process that prevents reads from getting aligned as properly oriented, concordant reads (mind you people do not report when things work as expected, so it is difficult to gauge how often this really is a problem...). Reasons for this could be (in no particular order): 
- quality issues in one or the other read, which causes the entire read pair to fail
- too many N calls in one read
- orientation of one read got messed up
- the library contained chimaeric reads (e.g. here: https://sequencing.qcfail.com/articles/pbat-libraries-may-generate-chimaeric-read-pairs/)

As mentioned above, and also  in the QC Fail article, we then follow a combination of PE and SE alignments in this case:

"...
To rescue as much data from a paired-end PBAT library with low mapping efficiency as possible we sometimes perform the following method (affectionately termed “Dirty Harry” because it is not the most straight forward or cleanest approach):

Paired-end alignments to start while writing out the unmapped R1 and R2 reads using the option `--unmapped`. Properly aligned PE reads should be methylation extracted while counting overlapping reads only once (which is the default).
 1. unmapped R1 is then mapped in single-end mode (in default = directional mode)
2. unmapped R2 is then mapped in single-end mode (in `--pbat` mode)
3. Single-end aligned R1 and R2 can then be methylation extracted normally as they should in theory map to different places in the genome anyway so don’t require attention to overlapping reads. Finally, the methylation calls from the PE and SE alignments can merged together before proceeding to the `bismark2bedGraph` or further downstream steps. The command for this is this one:

`bismark2bedGraph -o PE_and_SE_merged.cov CpG*single-end* CpG*paired-end*`

**Comment by digrigor** [comment]
Hi Felix,
Thanks again, your help is invaluable.

I will probably follow the Dirty Harry method since no matter what I try the PE mapping efficiency does not seem to increase.

Another think that confuses me is the alignment of the R2 reads. More specifically when run SE in --pbat or --non_directional mode for the PE-unmapped ones I observe a conversion of those reads to their reverse complement which is not the case for the R1 reads.

For example:
R2 sequence after trimming ->   5'-AATCTTCCTTTCTTAACTACCCTCAATACCAAAACTACCTATAATACCG-3'

R2 sequence in the 
BAM/SAM file after SE 
alignment in --pbat or          ->5'-CGGTATTATAGGTAGTTTTGGTATTGAGGGTAGTTAAGAAAGGAAGATT-3'
--non_directional mode:                                

The R2 sequence after trimming is ready for CTOT or CTOB alignment? Am I wrong?

Sorry for the huge amount of questions.

Thanks,
Dio

**Comment by FelixKrueger** [comment]
Hi Dio,

Strand conversions are very quickly getting very confusing... Apart from the 4-strand business you also get the additional complication that the SAM format dictates that sequences are displayed relative to the forward strand with the leftmost position as the starting position... 

But yes generally R2 of read pairs aligns to either the CTOT or CTOB strands when aligned in SE mode. This is normally factored in for PE alignments, but you don't need to worry, it will still r esult in correct methylation calls.

**Comment by digrigor** [comment]
Hi Felix,

Ok, now things seem more clear. Thanks for your time, I really appreciate it.

One more question:
When I run bowtie2 using my PE data I noticed that the option --dovetail is automatically set for the bowtie2 alignment although I am not running in --pbat mode. Given that I notice an almost ~20% difference between mapping efficiencies from bowtie1 and bowtie2 (has the highest ME) I am trying to figure out why this is happening. 

Thanks again Felix.

All the best,
Dio

**Comment by FelixKrueger** [comment]
The main difference between Bowtie 1 and Bowtie 2 is that Bowtie 2 allows reads with small insertions or deletions to map (which Bowtie doesn't do at all). Bowtie2 also scales with the read length, and it performs multi-seeding of longer reads. In other words: for longer reads, with potential InDels, gapped mapping with Bowtie2 is the preferred option. The `--dovetail` has a big impact if you perform 5' end trimming prior to mapping, bu it doesn't really hurt to have it active all the time.

**Comment by digrigor** [comment]
Hi again Felix,

Thanks to your useful suggestions I managed to get up to 70-80% Mapping efficiency for the PE data using bowtie2. I have now proceeded to the **Methylation extraction step**.

I **ignored 2-bp from the 5'-end of both read pair 1 and read pair 2** since I was observing a huge bias there (almost like you did [here](https://sequencing.qcfail.com/articles/library-end-repair-reaction-introduces-methylation-biases-in-paired-end-pe-bisulfite-seq-applications/). This certainly **improved** the M-bias plot.

![s18_pe_merged_sorted m-bias_r1](https://user-images.githubusercontent.com/33452269/46866091-df41c800-ce17-11e8-8fcf-345eb5f54cb6.png)
![s18_pe_merged_sorted m-bias_r2](https://user-images.githubusercontent.com/33452269/46866090-df41c800-ce17-11e8-8160-50ab8cf4270b.png)


However, there is a **broad-ranged fluctuation in both read pairs** (similar in both pairs), as you can see in the attached images. It is really hard for me to understand **why certain read positions have this bias**. I was thinking that maybe duplicate reads or over-represented sequences could cause this issue but still I did not have indications for none of the above (based on the FastQC).

Do you have any ideas or have you faced the similar problem? 

Thanks again for your time and for being keen to help, I really appreciate it.

Best,
Dio

**Comment by FelixKrueger** [comment]
Hi again Dio,  

Great to hear that the mapping efficiency is looking quite good now! I assume you did not deduplicate the data before continuing to the methylation extraction? (RRBS data should not be deduplicated except you used UMIs for each fragment...).

Just as a general tip, I would recommend you use `bismark2report` to convert all Bismark reports into an HTML report, this way the M-bias plots should look much nicer and are also a little interactive.

Next, I **don't think** you want to be using `--ignore` for your data, because the start of the reads will always cover CpG sites (this is how RRBS is designed). The methylation state of these residues might look weird, but they should carry the genomic methylation state. So I think you should re-do the extraction but leaving everything in (you got rid of artificial methylation states already during the trimming step).

Lastly, regarding the spikyness in the M-bias plots: When you do RRBS, there are only so many reads you can possibly sequence, something in the range of ~800,000 different fragments. Depending on your sequencing depth, these fragments will be covered by a lot of reads. Amongst those reads, there are some fragments which will receive an extraordinary amount of reads, and I suspect that it is those reads that will have an influence on the M-bias profile as a whole. I bet if you would import all reads into e.g. SeqMonk, and quantify the number of reads in the genome you would find that there will be a very small number of places with a huge numbers of reads. You could then look at their sequence to see if they match the M-bias profile... Such reads could potentially come from repetitive regions where only a single sequence is present in the genome, so all reads end up in a very small number of spaces.

If you then continue to quantify percentage methylation over features in the genome, these regions which a very large number of reads will get reduced down to a single % methylation value. So in other words, they are unlikely to disturb your overall analysis very much. I personally would probably not really try to interpret the M-bias plot for RRBS data at all, and just go ahead analysing promoters, CGIs, etc.

**Comment by digrigor** [comment]
Hi Felix,

Once again thanks for your helpful response and sorry for being so long to get back to you but we were facing some server issues and I could not reach my data.

So I ignored the m-bias plots and proceeded to create the cov files using:
bismark2bedGraph -o PE_and_SE_merged.cov CpG*single-end* CpG*paired-end*

Now I am inspecting the resulted bedgraph files and comparing them to their corresponding files from previous pipeline steps for QC and I noticed something which I cannot explain/understand. Let me give you an example:

Bedgraph cov file for a specific genomic position looks like that:
chr8    156100  156100  77.7777777777778        7       2

Searching this genomic location in the cpg files that methylation extractor returned I indeed found 7 reads with (+)  and 2 reads with (-) in this particular position as expected.

Going even further back to the initial bam files I used 2 ways to find this genomic location and get the base calls:
a) picard positional sorting of bam file -> samtools mpileup (for this location) -> it gave me 22 Gs and 2 As (it's in the OB strand) (24 total) for the same position:
gagagggggggggggggggggggg /EEE///E/EEEAEEE<EEEAEEE

b) samtools view bam -L (for this location) -> it also gave me that this location is covered by 24 reads.

Why is this happening?

I suspect that something weird is going when samtools is involved (positional sorting or something else) and therefore the "manual" methylation calling is different.

I would appreciate your opinion on the above observation!

Best regards,
Dio

**Comment by FelixKrueger** [comment]
Hi Dio,

The difference between the coverage files and the read counts with Picard or Samtools arises from the fact that bisulfites data, and thus methylation calls, are strand specific, but the overall number of reads that is seen by mpileup etc is not.  So a bisulfites read is either informative for the top strand *or* the bottom strand, and it seems that you got 9 (7+2) reads for one strand, and 15 reads for the other strand at this position.

I hope this makes sense. Best, Felix

**Comment by digrigor** [comment]
This makes 100% sense! Once again your help is invaluable!

This cpg position is on the bottom strand. I checked again the bam file and there are only 9 reads with a flag of 83 (OB, CTOB)!! So you are absolutely right. 

Thanks for helping!

Best,
Dio

**Comment by digrigor** [comment]
Hi again Felix,

One quick question:

Is there any possibility that I can get a cov file containing information about the strand of the reported CpG site or I should manually get a cov file from OT, CTOT and OB, CTOB and then merge them? 

I checked the documentation of bismark2bedGraph -o PE_and_SE_merged.cov CpGsingle-end CpGpaired-end but I couldn't find this option.

Thanks for your time and help.

Best,
Dio

**Comment by digrigor** [comment]
Hi Felix,

That was a silly question and I am really sorry that I wasted your time. I had completely forgotten about coverage2cytosine. That’s exactly what I need. That’s why I deleted the question at the first place.

Thanks,
Dio

**Comment by FelixKrueger** [comment]
fine :P glad it got solved!

**Comment by digrigor** [comment]
Hi Felix,

I hope you are well.
I have used the coverage2cytosine function as you have suggested to create a genome-wide cytosine report using the command: 

`coverage2cytosine --genome_folder /Reference -o out -dir /out --gzip input.bismark.cov.gz `

I did a QC on the output files and I noticed that the input.bismark.cov.gz contains some sites (out of the total 1562359) which are not present at all in the genome-wide o.CpG_report.txt.gz

for example the coverage file contains an entry:
chr21   9826398 9826398 26.6666666666667        20      55

which is not found in the CpG_report file.

Do you have any idea on why is this happening? Could that possibly be a bug?

Thanks for your help Felix.

Best,
Dio

**Comment by FelixKrueger** [comment]
Hi Dio,

This question has come up before, please allow me to copy-paste some of the text from issue#149:

```
It is potentially possible that there is a discrepancy in sequence context between the Bismark output (also the coverage file) and the genome-wide cytosine report. The reason for that is that when Bismark performs its methylation call (the one you see in the XM tag), it extracts a genomic sequence that aims to be a genomic equivalent to the read sequence. For reads that contain deletions, this may result in a context change. If you assume a genomic sequence `CTTG` that has the `TT` deleted in the read, the resulting context is a `CG` methylation call, even though the genomic sequence would have classified this cytosine as a CHH call.

The methylation extractor itself will simply extract the base-resolution calls from the BAM files and write them out to C* context files.

The following `bismark2bedGraph` step uses the C* context files to construct a coverage file. Until this point, all files (BAM,C* and .cov.gz) use the methylation call produced by Bismark, so as close to the probable context as possible.

Now the final step, `coverage2cytosine` is purely based on the reference genome sequence and does NOT care about what actually happened within the reads. This is primarily done to have a common set of reference positions, even if it means that for some select reads it might get the context wrong (else you might end up with multiple contexts for the same position and then everything would get more tricky...).

So the coverage files are probably the more 'truthful' files to work with if you wanted to call them that. Under default circumstances (CpG context only), a context change from CpG to some other context would simply not appear in the (CpG context only) coverage file, and the position would simply be missing from the genome-wide CpG-report. If you run everything in `--CX` mode the whole situation is a little more complicated...

I hope this answers your questions?

**Comment by digrigor** [comment]
Hi again Felix,

Thanks for your prompt response. Based on what you stated here I believe that the CpG reports are more trustworthy, since they are purely based on reference. However, given the fact that I am working with cancer samples (and not general population) I am worried that I might miss useful information about potential changes in the cancer genome (some sites became CpGs???). Do you think that if I run the function with --CX option, using the same CpG coverage input, I will probably get all the missing sites back in the CpG_report??

Thanks again Felix. I appreciate your help!

Best,
Dio

**Comment by FelixKrueger** [comment]
Hi Dio,

The reference you should use for this is the same genome you specified for the Bismark alignments, i.e. the folder containing the both the unconverted `.fa` sequences, as well as the folder `Bisulfite_Genome`.

By the way, did you know that Bismark can produce CRAM output directly? This is from the help text:

```
--cram                   Writes the output to a CRAM file instead of BAM. This requires the use of Samtools 1.2 or higher.

--cram_ref <ref_file>    CRAM output requires you to specify a reference genome as a single FastA file. If this single-FastA
                         reference file is not supplied explicitly it will be regenerated from the genome .fa sequence(s)
                         used for the Bismark run and written to a file called 'Bismark_genome_CRAM_reference.mfa' into the
                         oputput directory.
```

Does this help?

**Comment by digrigor** [comment]
Hi Felix, thanks for the prompt response. 
I am aware of the --cram option but at the moment I already have used Bismark for a large amount of input data and I would like to compress the archive storage. Therefore, I have to manually convert them using samtools(??) but I struggle with the conversion, since samtools only accept a single fasta file for reference. The workaround I found so far was to enable the --output-fmt-option no_ref in samtools view command but the compression is not that efficient.

Thanks for your help,
All the best,
Dio

**Comment by FelixKrueger** [comment]
You should be able to make a single genome file very simply: move to the genome folder you used for the Bismark alignments, and type `ls *fa`.
This should something like this:
```
Mus_musculus.GRCm38.68.dna.chromosome.10.fa  Mus_musculus.GRCm38.68.dna.chromosome.15.fa  Mus_musculus.GRCm38.68.dna.chromosome.1.fa  Mus_musculus.GRCm38.68.dna.chromosome.6.fa   Mus_musculus.GRCm38.68.dna.chromosome.X.fa
Mus_musculus.GRCm38.68.dna.chromosome.11.fa  Mus_musculus.GRCm38.68.dna.chromosome.16.fa  Mus_musculus.GRCm38.68.dna.chromosome.2.fa  Mus_musculus.GRCm38.68.dna.chromosome.7.fa   Mus_musculus.GRCm38.68.dna.chromosome.Y.fa
Mus_musculus.GRCm38.68.dna.chromosome.12.fa  Mus_musculus.GRCm38.68.dna.chromosome.17.fa  Mus_musculus.GRCm38.68.dna.chromosome.3.fa  Mus_musculus.GRCm38.68.dna.chromosome.8.fa
Mus_musculus.GRCm38.68.dna.chromosome.13.fa  Mus_musculus.GRCm38.68.dna.chromosome.18.fa  Mus_musculus.GRCm38.68.dna.chromosome.4.fa  Mus_musculus.GRCm38.68.dna.chromosome.9.fa
Mus_musculus.GRCm38.68.dna.chromosome.14.fa  Mus_musculus.GRCm38.68.dna.chromosome.19.fa  Mus_musculus.GRCm38.68.dna.chromosome.5.fa  Mus_musculus.GRCm38.68.dna.chromosome.MT.fa
```

Then do 
```
cat Mus_musculus.GRCm38.68.dna.chromosome.10.fa  Mus_musculus.GRCm38.68.dna.chromosome.15.fa  Mus_musculus.GRCm38.68.dna.chromosome.1.fa  Mus_musculus.GRCm38.68.dna.chromosome.6.fa   Mus_musculus.GRCm38.68.dna.chromosome.X.fa
Mus_musculus.GRCm38.68.dna.chromosome.11.fa  Mus_musculus.GRCm38.68.dna.chromosome.16.fa  Mus_musculus.GRCm38.68.dna.chromosome.2.fa  Mus_musculus.GRCm38.68.dna.chromosome.7.fa   Mus_musculus.GRCm38.68.dna.chromosome.Y.fa
Mus_musculus.GRCm38.68.dna.chromosome.12.fa  Mus_musculus.GRCm38.68.dna.chromosome.17.fa  Mus_musculus.GRCm38.68.dna.chromosome.3.fa  Mus_musculus.GRCm38.68.dna.chromosome.8.fa
Mus_musculus.GRCm38.68.dna.chromosome.13.fa  Mus_musculus.GRCm38.68.dna.chromosome.18.fa  Mus_musculus.GRCm38.68.dna.chromosome.4.fa  Mus_musculus.GRCm38.68.dna.chromosome.9.fa
Mus_musculus.GRCm38.68.dna.chromosome.14.fa  Mus_musculus.GRCm38.68.dna.chromosome.19.fa  Mus_musculus.GRCm38.68.dna.chromosome.5.fa  Mus_musculus.GRCm38.68.dna.chromosome.MT.fa
> Mus_musculus.GRCm38.combined.mfa
```

And voila, now you can use `Mus_musculus.GRCm38.combined.mfa` as the reference file for CRAM conversion. The command for he BAM > CRAM conversion of all files should be something like this:
```
for i in *bam; do samtools view -C -T Mus_musculus.GRCm38.combined.mfa $i > $i.cram; done
```

**Comment by digrigor** [comment]
Oh, that's so helpful! Thanks Felix.

**Comment by digrigor** [comment]
Hi Felix,
I hope you are well.
Have you ever heard of/used any particular way to combine cpg coverage files of (for example) different runs of the same sample (sum the coverage of shared files and list not_shared cpgs from both files into a new one)? 

Thanks,
Dio

**Comment by FelixKrueger** [comment]
Hi Dio,

I could send you a script that we routinely use to use combine the coverage files from eg. R1 and R2 of single-cell experiments into a single shared file? I'll attach it here tomorrow when I am back at work.

**Comment by FelixKrueger** [comment]
And here you go! The way it currently works is that it finds all .cov.gz files in a folder, and will try to merge the ones that have a similar description together.

[merge_coverage_files.zip]

(https://github.com/FelixKrueger/Bismark/files/2685381/merge_coverage_files.zip)
There are two regular expressions that might need adapting to suit your purposes, shout if you need help with that.

**Comment by digrigor** [comment]
Thanks Felix! It works perfectly! You just saved me many hours!

**Comment by FelixKrueger** [comment]
Perfect, thanks for the feedback

**Comment by digrigor** [comment]
Hi again Felix,
This is a slightly modified version of your code to merge cytosine-wide reports as well. I am attaching it here as it might be useful to other people too.

[merge_cytosinewide_coverage_files.zip](https://github.com/FelixKrueger/Bismark/files/2686262/merge_cytosinewide_coverage_files.zip)

All the best,
Dio

**Comment by digrigor** [comment]
> Hi Felix,
> 
> I am trying to analyse RRBS data which were produced using the Diagenode Premium RRBS Sequencing Kit. The produced RRBS paired-end libraries were run in an Illumina Next-Seq 500 sequencer and the produced reads are of 76bp length.
> 
> QC of the reads:
> -Great sequencing quality
> -Almost all Reads pair 1 (R1) start with TGG or CGG (because they were derived from OT or OB)
> -Almost all Reads pair 2 (R2) start with CAA (because they were derived from CTOT or CTOB)
> 
> Trimming with Trim Galore!:
> --non_directional --rrbs --paired -phred33 -q 30 --retain_unpaired -o
> The adaptors were removed correctly - The artificial bases were removed correctly - The quality was increased
> 
> Alignment using Bismark:
> When running the alignments I get:
> 
> * PE non-directional: 53.2% mapping efficiency (ME):
>   CT/GA/CT:	839578	((converted) top strand)
>   GA/CT/CT:	481	(complementary to (converted) top strand)
>   GA/CT/GA:	812	(complementary to (converted) bottom strand)
>   CT/GA/GA:	842955	((converted) bottom strand)
> * PE directional: 53.2% ME:
>   similar stats as above (0s in the CTOT/CTOB)
> * R1 SE directional: 69.7% ME
> * R2 SE non-directional: 67.7% ME
>   they only align to CTOT/CTOB
> * R2 SE directional: 1.6% ME
> 
> My question is:
> How is it possible for my R2 reads to align in the OT/OB strands when running PE directional alignment (ME: 53.2%) and not to align in the OT/OB strands when running SE directional alignment? Please also take into consideration that R2 reads clearly align to the CTOT/CTOB strands when running SE non-directional alignment (ME: 67.7% and the report clearly indicates that they only align to CTOT/CTOB).
> 
> Thank you very much,
> 
> All the best,
> Dio

Hi Felix,

I was looking at this very insteresing conversation we had back then about this project (when you saved my life :P) and just wondered... why R2 reads I was getting were only starting with CAA? Don't we expect R2 starting with CAG as well?

Many thanks for everything,

Dionysios

**Comment by FelixKrueger** [comment]
Hi Dionysios,

directional RRBS reads, so the 3' ends of OT and OB sequences, will end in `CCGG`. After MspI cutting, the fragment will end in `CCG`. Now the first `C` is in non-CG context and as such is almost universally unmethylated. The middle`C` is the one that gets filled in during the end-repair procedure, and it get's filled in with unmethylated cytosines. This, after the end repair, fill-in reaction and bisulfite treatment, the fragment will always end in `TTG`. Thus, R2 will always start with `CAA`. Makes sense?

**Comment by dktanwar** [comment]
Hi @FelixKrueger 

Can `--pbat` be used for WGBS, or is it specific to RRBS/ PBAT?

https://github.com/FelixKrueger/Bismark/issues/208#issuecomment-427380012

**Comment by FelixKrueger** [comment]
Typically, `--pbat` is the exact opposite to conventional WGBS. To be sure I would study the kit description, look at the base composition plot, or as last resort - get in touch...
