### ISSUE TITLE
Remove .fastq.gz or .fq.gz from Bismark output filenames

### ISSUE THREAD

**Issue by FelixKrueger** [FelixKrueger/Bismark#21]
Because file names are getting silly long anyway.

**Comment by FelixKrueger** [comment]
File endings `.fastq | .fq | .fastq.gz | .fq.gz` are now removed from the output file (unless they were specified with `--basename`. This addresses f88d770cbcd0417d0dec5402b371098a4aaac49b. Happy, Simon?

**Comment by s-andrews** [comment]
Always happy :-)

From:  FelixKrueger <notifications@github.com>
Reply-To:  FelixKrueger/Bismark
<reply+007c7ae37d34188ab877781ab0b2eb2649f1173dd804c38892cf0000000112cc375f9
2a169ce07d3c764@reply.github.com>
Date:  Friday, 5 February 2016 at 10:11
To:  FelixKrueger/Bismark <Bismark@noreply.github.com>
Subject:  Re: [Bismark] Remove .fastq.gz or .fq.gz from Bismark output
filenames (#21)


File endings .fastq | .fq | .fastq.gz | .fq.gz are now removed from the
output file (unless they were specified with --basename. This addresses
f88d770 
<https://github.com/FelixKrueger/Bismark/commit/f88d770cbcd0417d0dec5402b371
098a4aaac49b> . Happy, Simon?


Reply to this email directly or view it on GitHub
<https://github.com/FelixKrueger/Bismark/issues/21#issuecomment-180283211> .
