### ISSUE TITLE
methylation_extractor: --CX required for GpC?

### ISSUE THREAD

**Issue by Jkay7** [FelixKrueger/Bismark#212]
Hi Felix,

I am currently reproducing a publication interested in both CpG and GpC contexts. Following bismark alignment and deduplication I am now extracting the methylation sites.

For this reason, I currently use the following call:
`bismark_methylation_extractor  --cytosine_report --CX --gzip --bedGraph --o $outdir --remove_spaces --buffer_size 10G --genome_folder $gendir $infile`
_(Note that due to the absence of --nome-seq I am currently using --CX.)_

I noticed that, when using a pretty small .bam file as input (~24 mb), the output is still quite large (> 4 GB). I understand that this is mainly due to the CX_report.txt.gz.

**1**. As my focus will be on the analysis of the .cov file for CpG and GpC, is there a possibility to obtain only .cov files for these two contexts (rather than using the resource-hungry CX)? 
**1.1** I understand that, using coverage2cytosine with --cg and --gc one can obtain these individual contexts from the coverage file. I was wondering if it is only the coverage file that was needed, why we bother dump the whole CX_report taking up plenty of storage (which, of course, can be deleted after processing, but might occupy the hard disks quite heavily when processing many samples in parallel)?

**2.** On a perhaps related note, I noticed that this call uses 'only' 3 GB of memory, is this because the CX report is dumped onto storage?

**3.** Would it be better to drop the arguments `--cytosine_report` and `--bedGraph` in favor of processing these individually with `coverage2cyotsine --nome-seq` and either `--gc` or `--cg` ?

Thanks in advance!

**Comment by Jkay7** [comment]
Hi Felix,

Thanks for your swift and elaborate answer!

1) That makes sense, thanks for the explanation!
2) Since I am working with single-cell data I presume due to the lower coverage I can also assume a lower memory usage (good to know for adjusting of buffer size & allocating resources on the cluster!)
3) You're right, there is no --cg, my bad. 

You helped a lot, thanks!

**Comment by FelixKrueger** [comment]
Excellent, glad it helped! Felix
