### ISSUE TITLE
Methylation extraction split into chunks

### ISSUE THREAD

**Issue by bryan201** [FelixKrueger/Bismark#216]
Hello,
I am running Bismark on a research cluster with max walltime of 4 hours. I was able to split the alignment into chunks using --skip to run them under 4 hours, so I have each sample aligned in about 9 separate files. Is it possible to run the methylation extraction on the parts and then merge the .cov files afterwards for further analysis (such as identifying DMR)? Or will I have to merge the aligned .bam files and run methylation extraction on the entire sample? Apologies for the dumb questions as I am new to bioinformatics.

All the best.
-Chris

**Comment by FelixKrueger** [comment]
Hi Chris,

you should be able to run all the extractions separately, using e.g. this command: 
`bismark_methylation_extractor --gzip chunk1.bam` 
`bismark_methylation_extractor --gzip chunk2.bam` 
...
Alternatively, you could also merge all BAM files, e.g using `samtools cat`, and then run the methylation on the merged BAM files. The option `--parallel` will greatly speed up up the extraction process, e.g. `--parallel 4` will reduce the time needed for the extraction to ~30%.

Assuming you are going ahead with the extraction on the chunk-data:
Once this is all done, you can run `bismark2bedGraph on the combined files from all your chunks. Assuming the files are all in the same folder, you can simply do:

`bismark2bedGraph -o all_chunks_merged.cov --buffer 10G CpG*`

This command will take all CpG files in the current working directory and make a single coverage file from it. Is this what you were after?

**Comment by bryan201** [comment]
Hey Felix, 

Many thanks, this is very helpful.

**Comment by FelixKrueger** [comment]
Merry Christmas!
