### ISSUE TITLE
how to get bowtie2 parameters used in bismark

### ISSUE THREAD

**Issue by Honchkrow** [FelixKrueger/Bismark#217]
Hi,
  I'm running WGBS data and want to establish an pipeline.  I have tried bsseeker2 and Bismark, but get different mapping efficiency (Bismark: 75.9%, BSseeker2:86.0524%). I want using FASTQC and Bismark in my pipeline, but this mapping efficiency puzzled me. 
  Can I get bowtie2 parameters used in Bismark and compare these parameters with BSseeker2 (I already get parameters used inBSseeker2 )? 
  Thank you very much!

Honchkrow

**Comment by Honchkrow** [comment]
I found the following command in my log file, Is there a way for me to try other bowtie2 parameters like --local in Bismark? I get "Unknown option: local" message just add the parameter in command line.

Now running 2 instances of Bowtie 2 against the bisulfite genome of /home/wzhang/genome/hg19_bismark/ with the specified options: -q -N 1 --score-min L,0,-0.2 --ignore-quals

Now starting the Bowtie 2 aligner for CTreadCTgenome (reading in sequences from HOT164.fq.gz.temp.9_C_to_T.fastq with options -q -N 1 --score-min L,0,-0.2 --ignore-quals --norc)
Using Bowtie 2 index: /home/wzhang/genome/hg19_bismark/Bisulfite_Genome/CT_conversion/BS_CT

**Comment by FelixKrueger** [comment]
Hi Honchkrow,

I assume the main difference comes from the fact that Bismark is using a very stringent set of parameters as default (`--score_min L,0,-0.2`). If you were to relax this value to 0.4 or even 0.6 you would probably also see a slight increase in mapping efficiency.
I am afraid Bismark does not support local alignments (see [here](https://sequencing.qcfail.com/articles/soft-clipping-of-reads-may-add-potentially-unwanted-alignments-to-repetitive-regions/)). Instead we are advocates of stringently removing all known contaminations, and then aligning the data in a fairly strict fashion.

Just generally I would suggest:
- rigorous trimming of the data (e.g. with [Trim Galore](https://github.com/FelixKrueger/TrimGalore))
- you may relax the alignment parameters somewhat (mainly using `--score_min`), but be aware that the more you relax the mapping parameters you will also increase the incidence of mis-alignments
- for the trimming I tend to not change `-N` to 1 as it tends to increase the time needed considerably.


Hope this helps.

**Comment by Honchkrow** [comment]
Thanks for your rapid reply. I will try to relax the score_min.
