### ISSUE TITLE
how to calculate conversion rate?

### ISSUE THREAD

**Issue by DiegoZvallo** [FelixKrueger/Bismark#225]
Hi Felix.
I have an RRBS experiment done with Premium RRBS kit from Diagenode (protocol attached). In order to make a full NextSeq 500 single-end 75nt run, we first try a small run with a MIseq paired-end 2x150 to see if the library and specially the bisulfite conversion are good enough to keep going.

The kit provides sequences spikes to address this  issue. In the table 18 are shown the sequences, both fully unmethylated and methylated ones.

First I `trim_galore` the reads, and then I make a `bismark_genome_preparation` on those sequences and run `bismark` on them, however no a a single read mapped on them. Is this the correct way of doing that? 
Here are the code:
`trim_galore -q 25 --phred33 --fastqc --illumina --rrbs --non_directional --paired --length 30 sar073-2019_S7_L001_R1_001_10A_R1_Fw.fastq sar073-2019_S7_L001_R2_001_10A_R1_Rev.fastq`

`bismark_genome_preparation --bowtie2 --genomic_composition /home/dzavallo/RRBS/Vid/spike/`

`bismark -q --non_directional --nucleotide_coverage -p 4 --genome_folder /home/dzavallo/RRBS/Vid/spike/ -1 sar073-2019_S7_L001_R1_001_10A_R1_Fw_val_1.fq -2 sar073-2019_S7_L001_R2_001_10A_R1_Rev_val_2.fq -o /./spike/Bismark`

Here is the report:

Bismark

 report for: sar073-2019_S7_L001_R1_001_10A_R1_Fw_val_1.fq and sar073-2019_S7_L001_R2_001_10A_R1_Rev_val_2.fq (version: v0.20.0)
Bismark was run with Bowtie 2 against the bisulfite genome of /home/dzavallo/RRBS/Vid/spike/ with the specified options: -q --score-min L,0,-0.2 -p 4 --reorder --ignore-quals --no-mixed --no-discordant --dovetail --maxins 500
Option '--non_directional' specified: alignments to all strands were being performed (OT, OB, CTOT, CTOB)

Final Alignment report
======================
Sequence pairs analysed in total:	16474
Number of paired-end alignments with a unique best hit:	0
Mapping efficiency:	0.0% 
Sequence pairs with no alignments under any condition:	16474
Sequence pairs did not map uniquely:	0
Sequence pairs which were discarded because genomic sequence could not be extracted:	0

Number of sequence pairs with unique best (first) alignment came from the bowtie output:
CT/GA/CT:	0	((converted) top strand)
GA/CT/CT:	0	(complementary to (converted) top strand)
GA/CT/GA:	0	(complementary to (converted) bottom strand)
CT/GA/GA:	0	((converted) bottom strand)

Final Cytosine Methylation Report
=================================
Total number of C's analysed:	0

Total methylated C's in CpG context:	0
Total methylated C's in CHG context:	0
Total methylated C's in CHH context:	0
Total methylated C's in Unknown context:	0

Total unmethylated C's in CpG context:	0
Total unmethylated C's in CHG context:	0
Total unmethylated C's in CHH context:	0
Total unmethylated C's in Unknown context:	0

Can't determine percentage of methylated Cs in CpG context if value was 0
Can't determine percentage of methylated Cs in CHG context if value was 0
Can't determine percentage of methylated Cs in CHH context if value was 0
Can't determine percentage of methylated Cs in unknown context (CN or CHN) if value was 0

Bismark completed in 0d 0h 0m 10s 10s

I also read in your RRBS_Guide that there is a way to use paired end data to calculate the conversion rate based on the experimental adding of Cs in the library construction, by not removing the 3' nucleotide after adapter removal. Could you guide me a bit more step_by_step bases) on how to do this? The M-plot could gave me a hint on that?

Once I determine the convertion rate I would like to ask you some results from the actual mapping rates, but I think that the single-end experiment would have better results.

Thanks a lot
Cheers

Diego
[Premium_RRBS_kit_manual_24rxns.pdf](https://github.com/FelixKrueger/Bismark/files/2814007/Premium_RRBS_kit_manual_24rxns.pdf)

**Comment by FelixKrueger** [comment]
Hi Diego,

assuming that you have used the sequences in Table 18 correctly, the conclusion would indeed be that your 16474 sequences did not contain any spike-in reads that can be mapped as paired-end fragments.

Before giving up on this entirely I would try to find reads in single-end mode though.

First, take your sequences, strip out the 'm's, and use it for genome_preparation.

``` 
>unForward
TCGAACGCCCGGTCGCGCGTGTGGAGGATGTCGGTGCTGCAGGGGGCGTTGGAGCCGAAGTAGACCGCGCCGAACGTACGAACGGTCGTTCATATTAGTTATACTGGTTGTCTTGATGTTGCTTCTCCTAATTT
>unReverse
AAATTAGGAGAAGCAACATCAAGACAACCAGTATAACTAATATGAACGACCGTTCGTACGTTCGGCGCGGTCTACTTCGGCTCCAACGCCCCCTGCAGCACCGACATCCTCCACACGCGCGACCGGGCGTTCGA
>methForward
TCGAGAGGCAGTGGGTGCTGTCGGCGAAGTAGGGGTTGACGATGCCGGACCGTTCGTACGTACGCGCGACCGCTACTAATTTTAGTTGTGTTTCTGGTCCTATTGATCATTATCTTGC
>methReverse
GCAAGATAATGATCAATAGGACCAGAAACACAACTAAAATTAGTAGCGGTCGCGCGTACGTACGAACGGTCCGGCATCGTCAACCCCTACTTCGCCGACAGCACCCACTGCCTCTCGA
```

I would then take your data and run:
```
trim_galore --gzip --rrbs --paired sar073-2019_S7_L001_R1_001_10A_R1_Fw.fastq sar073-2019_S7_L001_R2_001_10A_R1_Rev.fastq
```

and lastly:

```
bismark --genome_folder /home/dzavallo/RRBS/Vid/spike/ sar073-2019_S7_L001_R1_001_10A_R1_Fw_val_1.fq.gz -o ./spike/Bismark/
```

This might be more informative than the paired-end test. By the way, I am not sure whether the Diagenode kit produces any non-directional reads at all. If yes, then you might have to include `--non_directional` in your commands. Otherwise, you should not use them.

Regarding your last question, there was a time when we indeed looked at the conversion state of the filled in position. This sometimes worked, but sometimes didn't look so great, so we stopped pursuing it. 

If I wanted to judge the conversion efficiency I would simply look at the lowest methylation you see anywhere. Often it is enough to just look at the methylation levels in non-CG context (in mammalian systems), else some people look at reads from the MT, or withing CpG islands. If you see a general methylation of 0.3% in  non-CG context, then your conversion efficiency must have been at least 99.7% efficient. Does that make sense?

**Comment by FelixKrueger** [comment]
Hi Diego,

I just saw from your report the line `Sequences did not map uniquely: 2`. Prompted by this I checked the sequences again which you were mentioned as reference in the Diagenode manual, and it turns out that >unForward and >unReverse are exactly the same sequence, only as the reverse complement (same for the meth-ones). That means that you should only be using one OR the other for the genome indexing process, because if Bismark finds equally good matches to different "genomes" it will boot the sequence. That way you should get at least 2 sequence alignments, and should get methylation values for this. But I would agree that 16000 sequences is not exactly sequenced very deeply...

**Regarding library directionality:**
Whether or not a library is directional is indeed determined by the library construction protocol.
```
In my Fw reads (R1) I do have almost all TGG first 3 bases
```

This means that the library is directional. R2 is merely the reverse complement of Read 1, so if you about how the end of each fragments looks:
```
C|CGG 3'
GGC|C 5'
```
then the start of each R2 would be CGA or CAA, depending on the C methylation state of the top strand.
For both SE and PE sequencing, only the orientation of the R1 alignment is the one that determines directionality (and R2 by definition has to face the other way). So bottom line, you should just run Trim Galore as well as Bismark in default, i.e. directional mode.

The chloroplast is indeed a good solution to check for the conversion rates in plant systems. 

Best, Felix

**Comment by DiegoZvallo** [comment]
Hi Felix, thanks for the explanation, the libraries are indeed directional
I did you what you told me, ran all on directional mode and with the meth and unmeth control only using the Foward strand and separately. I also used another data set from the same sequencing run but from human samples that have a bit more reads (40K average)
Oddly I always found more reads mapping with the metylated control rather than de unmethylated one.
Let me show you one example (the sample with the highest mapped reads):
This is the mapping report from this sample on the **meth_control** after  ` bismark` (on the unmeth_control only 4 reads mapped and all Cs were unmethylated) 

 
Final Alignment report
======================
Sequence pairs analysed in total:	148373
Number of paired-end alignments with a unique best hit:	241
Mapping efficiency:	0.2%

Sequence pairs with no alignments under any condition:	148132
Sequence pairs did not map uniquely:	0
Sequence pairs which were discarded because genomic sequence could not be extracted:	90

Number of sequence pairs with unique best (first) alignment came from the bowtie output:
CT/GA/CT:	143	((converted) top strand)
GA/CT/CT:	0	(complementary to (converted) top strand)
GA/CT/GA:	0	(complementary to (converted) bottom strand)
CT/GA/GA:	8	((converted) bottom strand)

Number of alignments to (merely theoretical) complementary strands being rejected in total:	0

Final Cytosine Methylation Report
=================================
Total number of C's analysed:	6779

Total methylated C's in CpG context:	3145
Total methylated C's in CHG context:	1503
Total methylated C's in CHH context:	1886
Total methylated C's in Unknown context:	2

Total unmethylated C's in CpG context:	49
Total unmethylated C's in CHG context:	54
Total unmethylated C's in CHH context:	142
Total unmethylated C's in Unknown context:	0

C methylated in CpG context:	98.5%
C methylated in CHG context:	96.5%
C methylated in CHH context:	93.0%
C methylated in unknown context (CN or CHN):	100.0%


Bismark completed in 0d 0h 0m 44s

====================
Bismark run complete
====================

I would expect a 100% methylated Cs in all context since this was a totally methylated spike right?

Then I saw that the Diagenode protocol, also came with data processing analysis for the convertion rate (attached) and the recommend some steps to extract the finale convertion rates. Of course is almost the same as I did, and I realize that the give you one extra file in .bed format for the **unmethylated Cs on the methylated spike!!!**  that they used to filter out the converted Cs.
I ran the exact command and the output was a number: **16.5!!!**
These are de command that I ran: 

`bismark_methylation_extractor --comprehensive --merge_non_CpG --bedGraph --CX --cytosine_report --CX --genome_folder /home/dzavallo/RRBS/Cancer/spike_meth/ sar071-2019_S5_L001_R1_001_Der_R3_Fw_val_1_bismark_bt2_pe.bam`

`intersectBed -v -a sar071-2019_S5_L001_R1_001_Der_R3_Fw_val_1_bismark_bt2_pe.bedGraph.gz -b RRBS_control_unmC.bed | awk '{methperc+=$4; allC++} END {print 100-methperc/allC}' `
16.5

Could you help me to undestand what's going on here?
I also attach the files if you want to try it yourself.

You can't imagine the invaluable help you offer, when no one in your work environment can

Best

Diego

[RRBS.tar.gz](https://github.com/FelixKrueger/Bismark/files/2823069/RRBS.tar.gz)

**Comment by FelixKrueger** [comment]
Hi Diego, 

Sorry for taking some time but the weekends are really quite busy these days...

I took your file, made a genome from it, and aligned R1 to it (in single-end mode). This resulted in the following stats:

```
CT/CT:	18	((converted) top strand)
CT/GA:	2	((converted) bottom strand)
GA/CT:	0	(complementary to (converted) top strand)
GA/GA:	0	(complementary to (converted) bottom strand)

Number of alignments to (merely theoretical) complementary strands being rejected in total:	0

Final Cytosine Methylation Report
=================================
Total number of C's analysed:	609

Total methylated C's in CpG context:	2
Total methylated C's in CHG context:	2
Total methylated C's in CHH context:	0
Total methylated C's in Unknown context:	0

Total unmethylated C's in CpG context:	310
Total unmethylated C's in CHG context:	132
Total unmethylated C's in CHH context:	163
Total unmethylated C's in Unknown context:	0

C methylated in CpG context:	0.6%
C methylated in CHG context:	1.5%
C methylated in CHH context:	0.0%
```

The important parts in this report are:
- most alignments (18/20) came from the top strand
- all contexts merged together, you saw 4 cytosines methylated and 605 cytosines unmethylated. This translates to an overall mean 'methylation' of 0.66%. Normally this value is a mix between real, i.e. genuine, methylation, and the so-called bisulfite conversion error. Since these are spike-in controls that should not carry methylation, we could therefore assume that this is the only the bisulfite conversion error. Or in other words: the bisulfite conversion must have been at least (100-0.66) = **99.34%** efficient. 

A screenshot of SeqMonk shows that there is indeed only a single-position that produces this effect (this is CpG context only; read means methylated call, blue means unmethylated call):
![unmeth](https://user-images.githubusercontent.com/5870509/52212409-521df580-2884-11e9-80e4-5d63cd3be827.png)

For the methylated control you do get more reads, and there are some unmethylated calls at most positions (again, only CpG context here). So the average methylation per position is between ~95-98% across the control. This could stem from over-conversion of methylated positions, or potentially un-methylated positions in the oligoes? In any case, I never really understood the concept methylated control samples anyway.

![meth](https://user-images.githubusercontent.com/5870509/52212384-44687000-2884-11e9-9380-768b52efbde1.png)

As bottom line, judging by the numbers of the unmethylated control you seem to have a conversion rate > 99%, and I think there is no need for panic (just yet ^^).

**Comment by DiegoZvallo** [comment]
Felix! Thanks for your reply!
I also didn't understand the methylated_control. I rest easy (for now) with the conversion rate. I soon as I  get my fully sequencing data I will definitely contact you for more question (specially for the analysis part, how to get good DMRs etc.) I remember that once you told me that I'll could do the subsequent analysis with SeqMonk, but at the moment I had some problems dealing with the biological replicates. Do you have some sort of tutorial for RRBS analysis with SeqMonk? Do you recommend others programs such as Methylkit or DMRCaller?

Thanks again for you amazing predisposition to answer all my question

Best

Diego

**Comment by FelixKrueger** [comment]
Hi Diego,

I can recommend you try to follow the training material we provide here: https://www.bioinformatics.babraham.ac.uk/training.html#bsseq

Both the Exploring methylation data and differential methylation part come with a detailed practical that should be easy to follow. While the course is not specifically tailored to RRBS data, mostly the same rules apply for that type of data as well. MethylKit is certainly one of the more widely used downstream tools, but you will find that SeqMonk itself comes with a good set of tools for this as well.

**Comment by digrigor** [comment]
Dear both,

I just read your conversation and given the fact I have analysed data derived from this specific kit I thought that I could give some useful input.

Diego it would be really easy for you to follow the manual diagenode has made available here (with ready spike-in references):  https://www.diagenode.com/en/documents/premium-RRBS-spike-controls
I have done it and got my conversion rates.

For analysing data from this kit, maybe it would be useful to have a look at my discussion with Felix, who helped me throughout all parts of my analysis here:  https://github.com/FelixKrueger/Bismark/issues/208

**Comment by DiegoZvallo** [comment]
Hi Dio, 
Thanks for your insights.
Actually I read your conversation with Felix before, It was very helpful for all the bismark steps, although I still having issues with the DMR calling and statistics with SeqMonk. Maybe when I have my full sequencing data I will bother you (both) again.

I did follow the diagenode manual for the convertion rates. I don't know if you saw it above, but I can only done it for the methylated-spike since I only had 2 reads for the unmethylated one (did you also encountered that bias?). Let me remind you that this data is just a test to see the if the library, as well as the bisulfite kit were ok. So I only have a few reads in total (~40.000).

This is what I wrote to Felix regarding the Diagenode protocol, and the retrieved number was **16.5**
Is that the conversion rate? 
What numbers did you get?


> Then I saw that the Diagenode protocol, also came with data processing analysis for the convertion rate (attached) and the recommend some steps to extract the finale convertion rates. Not surprising, is almost the same as I did, and I realize that they gave you one extra file in .bed format for the **unmethylated Cs on the methylated spike!!!** that they used to filter out the converted Cs.
> I ran the exact command and the output was a number: **16.5!!!**
> These are the commands that I ran:
> 
> `bismark_methylation_extractor --comprehensive --merge_non_CpG --bedGraph --CX --cytosine_report --CX --genome_folder /home/dzavallo/RRBS/Cancer/spike_meth/ sar071-2019_S5_L001_R1_001_Der_R3_Fw_val_1_bismark_bt2_pe.bam`
> 
> `intersectBed -v -a sar071-2019_S5_L001_R1_001_Der_R3_Fw_val_1_bismark_bt2_pe.bedGraph.gz -b RRBS_control_unmC.bed | awk '{methperc+=$4; allC++} END {print 100-methperc/allC}' `
> 16.5
> Is that the conversion rate???

This number and the fact that in my data I'm having only a ~15% of CpG methylation rates makes me wonder... if the bisulfite treatment worked at all?

Look at one mapping report example:

```
Bismark report for: sar067-2019_S1_L001_R1_001_Der_R1_Fw_val_1.fq and sar067-2019_S1_L001_R2_001_Der_R1_Rev_val_2.fq (version: v0.20.0)
Bismark was run with Bowtie 2 against the bisulfite genome of /home/dzavallo/RRBS/Cancer/Human_genome/ with the specified options: -q --score-min L,0,-0.2 -p 4 --reorder --ignore-quals --no-mixed --no-discordant --dovetail --maxins 500
Option '--directional' specified (default mode): alignments to complementary strands (CTOT, CTOB) were ignored (i.e. not performed)

Final Alignment report
======================
Sequence pairs analysed in total:	77561
Number of paired-end alignments with a unique best hit:	27124
Mapping efficiency:	35.0% 
Sequence pairs with no alignments under any condition:	47206
Sequence pairs did not map uniquely:	3231
Sequence pairs which were discarded because genomic sequence could not be extracted:	0

Number of sequence pairs with unique best (first) alignment came from the bowtie output:
CT/GA/CT:	13518	((converted) top strand)
GA/CT/CT:	0	(complementary to (converted) top strand)
GA/CT/GA:	0	(complementary to (converted) bottom strand)
CT/GA/GA:	13606	((converted) bottom strand)

Number of alignments to (merely theoretical) complementary strands being rejected in total:	0

Final Cytosine Methylation Report
=================================
Total number of C's analysed:	1606707

Total methylated C's in CpG context:	39163
Total methylated C's in CHG context:	2009
Total methylated C's in CHH context:	3880
Total methylated C's in Unknown context:	6


Total unmethylated C's in CpG context:	225104
Total unmethylated C's in CHG context:	410095
Total unmethylated C's in CHH context:	926456
Total unmethylated C's in Unknown context:	500


C methylated in CpG context:	14.8%
C methylated in CHG context:	0.5%
C methylated in CHH context:	0.4%
C methylated in unknown context (CN or CHN):	1.2%


Bismark completed in 0d 0h 2m 21s
```
Isn't that a very low CpG methylated percentage? (and for my other plant data set the CpG methylated percentage are even lower (~5%).

How can I be sure that the bisulfite treatment works just fine? And if it did, why I'm having so low CpG methylated percentage?

Could any of you give me a hint? 

All the best

Diego

**Comment by digrigor** [comment]
Hi Zwallo,
In my case, I had runs with millions of input reads and therefore I got some reads aligning to both meth and unmeth references. The limited amount of reads may be the reason of not having good mapping efficiencies to the unmeth reference.

- What you expect/want is your **unmethylated** control having 0-2% (let's say 1%) average methylation percentage in all the Cs you detected. In that case the algorithm output will be 
**100%-1% = 99% -> 99% conversion efficiency.**
- What you also expect/want is your **methylated** control having 98-100% (let's say 99%) average methylation percentage in all the Cs you detected. In that case the algorithm output will be 
**100%-99% = 1% -> 99% conversion efficiency.** As you said, **your output is 15%** meaning that you have around 85% conversion efficiency. 

Make sure that you don't copy/paste the code from the protocol for the conversion efficiency as I remember there were some spelling problems with '," and ` symbols. 

You can also suspect your bedgraph files. For the methylated control analysis these should be something like: 
RRBS_methylated_control 1       2       100
RRBS_methylated_control 2       3       100
RRBS_methylated_control 4       5       100
RRBS_methylated_control 6       7       100
RRBS_methylated_control 7       8       100
RRBS_methylated_control 8       9       93.8461538461538
RRBS_methylated_control 10      11      100

Best,
Dio

**Comment by FelixKrueger** [comment]
Regarding the output against the human sample above

```
C methylated in CpG context:	14.8%
C methylated in CHG context:	0.5%
C methylated in CHH context:	0.4%
```

I would probably state that:

a) the bisulfite conversion must have been at least 100 - 0.4 = 99.6% efficient. This is generally regarded an excellent value.
b) the methylation in CpG context is 15%, which is indeed quite low. This could have several causes:

- the sample is RRBS, so you interrogate mainly CG rich sequences. CG-rich sequences are highly enriched in CpG islands, and those are known to often be universally unmethylated. So while the value is overall fairly low, this might just be what you are after.
- The biological/clinical stage of the samples could mean that there was a wave of demethylation?
- over-conversion with bisulfite. Maybe you got the concentration wrong, and/or incubated the DNA with too much bisulfite for too long?

The latter case is probably unlikely, so I would tend to speculate that the conversion seems to be very good, and what you are looking at is real biology....

**Comment by josesovaz** [comment]
Hello Felix, 

Regarding this last answer about the over-conversion with bisulfite, I would want to ask you if this over conversion really exists or is a very unlikely proccess. With filter_non_conversion we can filter for "false negatives" (non methylated Cs that haven't been converted to Ts), but I was wondering if it is possible to identify "false positives" (methylated Cs that have been converted to Ts). Is it chemically possible to convert methylated Cs to Ts when you use a high concentration / incubation time with bisulfite? 

Kind regards,

Jose

**Comment by FelixKrueger** [comment]
Hi Jose,

To my understanding, bisulfite conversion is essentially a chemical reaction which also acts on methylated cytosines, however the kinetics are so slow that it doesn't really play much of a role in real life.

We only once had the case (some ~8 years ago), where someone accidentally had a factor of 10 too much bisulfite, and this caused some very weird patterns of methylation. It also was so harsh to the DNA that there was hardly anything left to look at :) So bottom line, I think it is safe to ignore this scenario....

**Comment by josesovaz** [comment]
Ok! Thank you for your clarification.

Regards,

Jose

**Comment by DiegoZvallo** [comment]
Hi all, thanks for the responses.

Felix, on what are you basing to say that the conversion rate must be 99.6%? On this: C methylated in CHH context:	0.4%?

Dio, I inspected the bedGraph files as well as the cov file.
The bed files, have some 0% methylated positions, but when I looked that positions in the cov files they are always very low read coverage.

bedGraph:

```
methForward	1	2	98.0392156862745
methForward	4	5	50
methForward	6	7	50
methForward	7	8	100
methForward	8	9	100
methForward	10	11	100
methForward	12	13	100
methForward	13	14	100
methForward	14	15	100
methForward	16	17	100
methForward	17	18	100
methForward	19	20	0
methForward	21	22	100
methForward	22	23	100
methForward	23	24	0
methForward	24	25	93.4426229508197
methForward	25	26	100
methForward	28	29	100
methForward	31	32	0
methForward	32	33	0
methForward	33	34	0
methForward	34	35	100
methForward	37	38	0
methForward	39	40	98.5074626865672
...
..
.
```
cov file

```
methForward	2	2	98.0392156862745	50	1
methForward	5	5	50	1	1
methForward	7	7	50	1	1
methForward	8	8	100	2	0
methForward	9	9	100	58	0
methForward	11	11	100	2	0
methForward	13	13	100	2	0
methForward	14	14	100	2	0
methForward	15	15	100	2	0
methForward	17	17	100	2	0
methForward	18	18	100	57	0
methForward	20	20	0	0	2
methForward	22	22	100	60	0
methForward	23	23	100	2	0
methForward	24	24	0	0	2
methForward	25	25	93.4426229508197	57	4
methForward	26	26	100	2	0
methForward	29	29	100	2	0
methForward	32	32	0	0	2
methForward	33	33	0	0	2
methForward	34	34	0	0	2
methForward	35	35	100	2	0
methForward	38	38	0	0	2
methForward	40	40	98.5074626865672	66	1
...
..
.
```

As you can see, the 0% methylated positions are due to low coverage reads. But I assume that the conversion rate calculations take in account the coverage right?

I simply sum all the methylated *Cs against all the unmethylated Cs and I had this:


Methylated: 1721 
Unmethylated: 49

Methylated conversion rate: (1721/1770)*100= 97.23%

Is this assumption correct?

Could it be that this low read coverage are some how biassing my results?


Felix, you stated that:

>   
CG-rich sequences are highly enriched in CpG islands, and those are known to often be universally unmethylated.

I didn't know that, in plants is quite the opposite. In fact, look at this paragrah from Cokus et al 2008 (Nature)

> Finally, we found that regions with higher concentrations of CG dinucleotides were more heavily methylated at CG sites (Supplementary Fig. 10). Interestingly, this is different from mammalian genomes that show the opposite trend: CGs are depleted in methylated regions and at a higher density in unmethylated CpG islands.

Maybe I've to be worry about me plant data set (vid) since the CpG percentage was ~5%!! Or perhaps its just the low sequencing deepness. 

My boss is pressing me to give him an answer about whether the bisulfite treatment works at all.

Best

Diego

**Comment by FelixKrueger** [comment]
Hi Diego,

My comment about the conversion efficiency was indeed based on the lowest value of non-CG methylation. If you only see 0.4% methylation, then you can't possibly have a conversion failure rate of higher than 0.4%. Or in other words: the conversion efficiency must at least have been 99.6%.

My comment about the low methyation of CGIs was based on the fact that you seemed to have aligned (at least the last sample) to the human genome: `/home/dzavallo/RRBS/Cancer/Human_genome/`. It might well be possible that it is very different in plants.

**Comment by FelixKrueger** [comment]
Closing this for the time being.
