### ISSUE TITLE
methylation extraction: bedGraph and coverage

### ISSUE THREAD

**Issue by mtanic** [FelixKrueger/Bismark#227]
Hi Felix,

Just wanted to double check if there is any difference in the bismark bedGraph and coverage reports generated using strand specific vs. --comprehensive methylation extraction?

Thanks in advance,
Miljana

**Comment by FelixKrueger** [comment]
There coverage report should indeed be exactly the same for either the strand-specific or comprehensive option.

**Comment by mtanic** [comment]
Thanks Felix!
