### ISSUE TITLE
--merge_CpG still fails in coverage2cytosine bismark v0.19.0

### ISSUE THREAD

**Issue by mtanic** [FelixKrueger/Bismark#229]
Hi Felix, 

I am using  Bismark Version: v0.19.0, and the coverage2cytosine module (Script last modified: 12 October 2017) with --mergeCpG option still gives the same error when running:

` coverage2cytosine --genome_folder ${BSGEN} --merge_CpG --gzip -o ${file%%.bismark.cov.gz}"bismark.CpG.cov.gz" $file
`

> Finished writing out cytosine report for covered chromosomes (processed 24 chromosomes/scaffolds in total)
> 
> Now processing chromosomes that were not covered by any methylation calls in the coverage file...
> All chromosomes in the genome were covered by at least some reads. coverage2cytosine processing complete.
> 
> Now merging top and bottom strand CpGs into a single CG dinucleotide entity (writing to file >> Agilent_ZYMO-UM_R1_val_1_bismark_bt2_pe.deduplicatedbismark.CpG.cov.gz <<)
> Failed to open file Agilent_ZYMO-UM_R1_val_1_bismark_bt2_pe.deduplicatedbismark.CpG.cov.gz: No such file or directory

Best wishes,
Miljana

**Comment by FelixKrueger** [comment]
Hi Miljana,

I have just tried to run your command over here, and it runs just fine. Could you please update to the latest version of Bismark (v0.21.0), and see if the problem still exists? Cheers, Felix

**Comment by FelixKrueger** [comment]
I assume this is now working...
