### ISSUE TITLE
bismark alignment basename and multicore exclusive

### ISSUE THREAD

**Issue by davidries84** [FelixKrueger/Bismark#230]
Hi,
when I run bismark with -B and -multicore, it complains that this doesn't work together.
Is this behaviour intended top be fixed in the near future?
Or is it possible to use -prefix instead?
Best,

David

**Comment by FelixKrueger** [comment]
Hi David,

There are no immediate plans to add the `-B` and `--muticore` functionality, as I am currently working tirelessly to retire Bowtie 1 from Bismar, add HISAT2 support instead, and there is also a bank holiday looming... :) .`--prefix` should work fine together with `--multicore` though.

**Comment by davidries84** [comment]
Thanks,
I probably can manage without for now ;-).
