### ISSUE TITLE
Update table with Bismark alignment modes for Bowtie1/HISAT2/SLAM-seq

### ISSUE THREAD

**Issue by FelixKrueger** [FelixKrueger/Bismark#232]
It is truly a little out of date....

**Comment by groverj3** [comment]
I had no idea HISAT2 alignment was coming. That's exciting. If it's already working then I'll give this a try!

**Comment by FelixKrueger** [comment]
Hi Jeffrey,

I think it is all working in the current development version. I am currently on holiday, so there won't be much support I am afraid. Feedback welcome, but you have been warned...

**Comment by groverj3** [comment]
If I get some spare time, I'll test this out. I'm already comparing our standard bismark pipeline to bwa-meth + methyldackel. This is likely to reduce alignment time dramatically vs bowtie2 mode. Mapping rate is probably more important, but it's difficult to compare "mapping rate" between the aligners in meaningful ways.

**Comment by groverj3** [comment]
So, I ran a test last night. I got a slightly lower alignment rate than with bowtie2 mode, but it was faster by about 10%. Not a huge speed-up. I've usually run Bismark in bowtie2 mode with the -N 1 option though, and it was about 30% faster than that.

Nice to see Bismark is still in active development!

**Comment by FelixKrueger** [comment]
Thanks for the update. I still need to add a few options, e.g. to allow splice junction file etc. The option `-N 1` is indeed much slower than running it with the default of 0. Cheers, Felix

**Comment by FelixKrueger** [comment]
The table is now up-to-date! https://github.com/FelixKrueger/Bismark/blob/master/Bismark_alignment_modes.pdf
