### ISSUE TITLE
Advice for methylation extraction from paired-end data?

### ISSUE THREAD

**Issue by jrknoedler** [FelixKrueger/Bismark#233]
I'm crunching through an enormous MethylC-data set and I have a question regarding methylation extraction - specifically how to handle paired-end reads. We had a grant specifically for sequencing so we went for broke and sequenced 150 bp paired-end. The median insert size for the library is about 200 bp, so  in practice most of the reads do overlap. However, a sizeable portion don't, or might only overlap slightly, so there's a ton of extra coverage data there. I notice that for the bismark methylation extractor tool there's an option to ignore overlap (obviously bad in this case since it would double count a lot of C's) and an option to only take the methylation calls from R1, but nothing in between. Would I have to just use another tool to count all singly-sequenced bases?

**Comment by FelixKrueger** [comment]
Hi @jrknoedler,

The way the methylation extraction works for paired-end data is that:
- *all* methylation calls from Read 1 are extracted 
- all methylation calls from Read 2 are extracted, until R2 starts to overlap with R1 (which has already bee exctracted)

In other words, in its default mode all positions from both R1 and R2 will be present once in the extracted data, and coverage file, and overlapping portions are not double counted. Does this help?

**Comment by jrknoedler** [comment]
Yes it does, perfect! Sorry, the --help documentation on Bismark (a least on the version I have downloaded) made it sound like only Read 1 was counted with --no-overlap on. Thanks for the quick response!
