### ISSUE TITLE
Bismark Deduplication Step

### ISSUE THREAD

**Issue by sunshine-lp0** [FelixKrueger/Bismark#234]
Hi,

Why deduplication is not recommended for RRBS, amplicon or other
target enrichment-type libraries ?
Thank you.

Sincerely,
Anita

**Comment by FelixKrueger** [comment]
The reason for this is rather pragmatic: whenever you expect a very high coverage of a region, and you do not include unique molecular identifiers (UMIs) in your reads, you cannot tell whether a read was a genuine read from a different cell, or if it was a PCR duplicate.

De-duplication which is based on mapping position (and orientation) alone will only allow 1 alignment to a given position. In cases where you can only ever sequence a small number of different fragments (for RRBS this is ~600,000), you would start discarding reads as soon as each fragment was covered once. In other words: the deeper you sequence, the more data would get discarded.

The following schematic tries to illustrate this:

![donotdeduplicate](https://user-images.githubusercontent.com/5870509/53801739-df15a680-3f37-11e9-815d-6ef2241acd11.jpg)

**Comment by sunshine-lp0** [comment]
Thank you very much!

**Comment by Hendricks27** [comment]
Hi,

Thank you for asking the question, and very nice illustration. 
Here is probably a dumb question.
What if we have 2 fragments (read-pairs) with different methylation patterns, but they align to the exact same position, in this diagram, they are considered duplicates. But should they?
Thanks!

**Comment by Hendricks27** [comment]
Yes, yes. It makes perfect sense to me.
I just want to make sure I understand the problem.
Thank you so much for your explanation!
