### ISSUE TITLE
Question about paired-end mapping

### ISSUE THREAD

**Issue by sunshine-lp0** [FelixKrueger/Bismark#235]
Hi Felix,
    According to my methylation method, Read 2 are OT and OB, Read 1 are CTOT and CTOB. I used "--pbat --single_end ...R1.fastq.gz" or "--single_end ...R2.fastq.gz", the mapping efficiency both can reach 50%. But when i used "-1 ...R1.fastq.gz -2 ...R2.fastq.gz", the mapping efficiency is only 0.4%. Maybe my sequencing reads are too short after triming useless sequences (mainly concentrated in the length of 50bp)?
    Thank you very much!

- "--single_end ...R2.fastq.gz"

![image](https://user-images.githubusercontent.com/33354198/53806689-989c6800-3f88-11e9-9df4-7f1bd628fa2f.png)

- "--pbat --single_end ...R1.fastq.gz"
![image](https://user-images.githubusercontent.com/33354198/53806787-e74a0200-3f88-11e9-9f26-7b714bd0aa2a.png)

- -1 ...R1.fastq.gz -2 ...R2.fastq.gz
![image](https://user-images.githubusercontent.com/33354198/53809654-24fe5900-3f90-11e9-97ca-bcd9bd242ea7.png)

**Comment by FelixKrueger** [comment]
The mapping orientation of R1 is the one that governs the orientation of the entire alignment, both for single-end and paired-end mapping. So if you have a Read 1 that needs to be aligned in `--pbat` mode, then you also need to use that for paired-end mapping. 

The command 
`bismark --genome GRCh38.95 --pbat -1 ...R1.fastq.gz -2 ...R2.fastq.gz`

should do the trick. If you have not already done so, I would certainly recommend you trim the sequences with Trim Galore. If the mapping efficiency stays at only ~50%, you could also try and relax the mapping criteria somewhat (to say `--score_min L,0,-0.4`) to see if this has an appreciable positive impact on the mapping rate.

**Comment by sunshine-lp0** [comment]
Thank you! I'll try this.
What range do you think the mapping efficiency is normal? I would have thought that 50% is already high enough. If I relax the mapping criteria, how do I assess authenticity of reads?

**Comment by FelixKrueger** [comment]
For PBAT data, we typically see anything between ~40 and 65%, depending on the experimentalist and protocol used. Sometime we also do a paired-end alignments first, followed by single-end alignments. Please check out this as well: https://sequencing.qcfail.com/?s=pbat

**Comment by sunshine-lp0** [comment]
Thank you!

**Comment by sunshine-lp0** [comment]
But you told me before "paired-end data is paired-end data...". I would have thought that you wouldn't do a paired-end alignments first, followed by single-end alignments.
![image](https://user-images.githubusercontent.com/33354198/53879087-8d107600-4048-11e9-982b-0744f4a8a93b.png)

**Comment by FelixKrueger** [comment]
And I stand by it, I personally try to keep it PE only, and not bother with single-end. But technically, it can be done...

**Comment by sunshine-lp0** [comment]
ok. Thank you very much!
