### ISSUE TITLE
Concatenating optional read ID descriptions to read ID's in outputted BAM

### ISSUE THREAD

**Issue by benjamincarlin** [FelixKrueger/Bismark#236]
In order "to avoid problems with truncated read ID when they contain white spaces", whitespace in the the read ID line (Line 1's of the FASTQ format) if currently being replaced underscores.

https://github.com/FelixKrueger/Bismark/blob/782b3e543842a9c40e435a19fbe4660f22020aa8/bismark#L5885

However, read ID's can be followed by an optional description that is currently being concatenated to the read ID in the outputted BAM/SAM. This can cause the output data from Bismarck to be altered/differ from the input FASTQ's and the output of other tools, such as picard tools or gatk tools, which ignore the read ID optional description.

[FASTQ Format:](https://en.wikipedia.org/wiki/FASTQ_format)
A FASTQ file normally uses four lines per sequence.

**Line 1 begins with a '@' character and is followed by a sequence identifier and an optional description (like a FASTA title line).**
Line 2 is the raw sequence letters.
Line 3 begins with a '+' character and is optionally followed by the same sequence identifier (and any description) again.
Line 4 encodes the quality values for the sequence in Line 2, and must contain the same number of symbols as letters in the sequence.

**Comment by FelixKrueger** [comment]
Hi Benjamin,

It is true that Bismark replaces white spaces with underscores, but this is done deliberately to preserve the information contained within the header line. For many applications, barcodes, UMI etc are written as comments into the header line, e.g. like here:

```
@HWI-D00436:407:CCAETANXX:1:1101:4088:1857 3:N:0: CGATGTTT:R1:NAAGTTCG:R2:GATTTTGA:F1:CAGT:F2:CAGT
CAAATTAATTATACACTACGCCTCATTTACATATTCCTCATCTAATTAACTACTCTCTCTCTC
+
GGGGGGGGFEGGGGGGEGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
```

where a standard (= truncate at first whitespace) approach would simply delete the UMI information `R1:NAAGTTCG:R2:GATTTTGA`. 

 I suppose if you really wanted to get rid of that information, one could write a quick post-processing script that would do the truncation based on a regular expression for first element you don't like: `s/_\d:N:\d+//`. Does that make sense?

**Comment by benjamincarlin** [comment]
Thank you for the quick response! 

There has been a fairly new updated the [SAM spec](https://samtools.github.io/hts-specs/SAMv1.pdf). Concatenating the UMI to the read ID goes against the GA4GH standard, making the outputted BAM/SAM invalid. UMI’s are now standardized to be stored as tags within the BAM. In addition, in the case that the fastq comments/read ID descriptions are different in read 1 compared to read 2, the outputted BAM/SAM will have invalid GA4GH mate information. The output will result in different query names for read 1 versus read 2, even though they are supposed to have the same mate information/read ID.

**Comment by FelixKrueger** [comment]
Hi Benjamin,

I just had a look at the updated SAM format specification you linked. It's probably me but I could not find anything about the fact that concatenating UMIs to the read ID goes against the GA4GH standard, would you mind pointing me to the specific passage about that? 

All I found is the specification of `QNAME`:

```
1. QNAME: Query template NAME. Reads/segments having identical QNAME are regarded to come from
the same template. A QNAME ‘*’ indicates the information is unavailable. In a SAM file, a read may
occupy multiple alignment lines, when its alignment is chimeric or when multiple mappings are given.
```

In my mind that doesn't make any statements about what exactly would be invalidating the SAM spec. For paired-end reads, Bismark uses the very same read ID for both R1 and R2, so the query name should therefore be consistent, and more importantly, valid. Or am I missing something here?

Don't get me wrong, I would have no problem handling UMIs differently, e.g. writing them into a special tag in the BAM file, and then adjusting `deduplicate_bismark` or `UmiBam` so that they utilise this new format instead. But at the moment I don't think there are any tools apart from the Bismark internal scripts  that make active use of the tags, e.g. as we do for mouse epigenetic clock processing (https://github.com/FelixKrueger/TrimGalore/blob/master/Docs/Trim_Galore_User_Guide.md#mouse-epigenetic-clock-trimming).

**Comment by benjamincarlin** [comment]
Hi Felix,

Thanks for the quick response again, I appreciate you taking the time to help!

I first wanted to apologize for my mistake and share with you the SAM spec for sam tags [here](https://samtools.github.io/hts-specs/SAMtags.pdf) where section 1.3 discusses tags for barcodes

Also, in my use case of Bismark, my aligned data is producing different read ID’s in the aligned bams. My data is paired end but being mapped as single end in certain situations. The read id descriptions of differ from read 1 vs. read 2 in my fastq's:

Read 1 ID Ex: A00280:14:H32NJDSXX:1:1101:27742:2033 1:N:0:TGGAGTTG+CGATCGAT 
Read 2 ID Ex: A00280:14:H32NJDSXX:1:1101:27742:2033 2:N:0:TGGAGTTG+CGATCGAT

And as a result, my aligned Bam read 1 and read 2 have different ID’s:

Read 1 ID Ex: A00280:14:H32NJDSXX:1:1101:27742:2033_**1**:N:0:TGGAGTTG+CGATCGAT 
Read 2 ID Ex: A00280:14:H32NJDSXX:1:1101:27742:2033_**2**:N:0:TGGAGTTG+CGATCGAT

**Comment by FelixKrueger** [comment]
Hi Benjamin,

Many thanks for the new link about guidelines for optional fields. I think it would make a lot of sense to move away from storing lots of useful information in the readID, and instead use optional fields to store this - sometimes critical - data. One could e.g. envisage storing the barcode sequence, as well asl R1  and R2 UMIs in special tags, and potentially put other data into a free-text field such as `CO:Z:text`. For this to work properly however, I would think that all mapping tools would have to 'do the right thing' and extract the right information from the FastQ files, and put it into the right kinds of optional field - a task that is probably easier said than done... I will certainly keep it in mind, and try to add it to my list of things that need doing.

Regarding your specific use case of Bismark, I can see that in a case where you align R1 and R2 independently the read IDs would indeed be different. 

We are trying to make sure that paired-end reads carry exactly the same read ID for both reads when they are processed with Bismark; we would probably argue that the burden of making sure that the read IDs don't go against the format specifications passes on to you if you choose to stitch together two single-end files. (just out of interest, what are doing with `FLAG` values for such files?)

I suppose until all comments and barcodes are handled using appropriate optional tags (see above), your best option for the time being is to perform post-processing of your files while taking the same approach that most tools are taking already, namely truncate the IDs after the initial read-coordinate part (i.e. when at the first `_`) which is in common between both reads in the FastQ files and the BAM files:

```
FastQ Read 1 ID Ex: A00280:14:H32NJDSXX:1:1101:27742:2033 1:N:0:TGGAGTTG+CGATCGAT
FastQ Read 2 ID Ex: A00280:14:H32NJDSXX:1:1101:27742:2033 2:N:0:TGGAGTTG+CGATCGAT
truncated read ID:  A00280:14:H32NJDSXX:1:1101:27742:2033
```

Does that make sense? Again, just out of interest, do you have an idea whether all other tools and/or aligners are making an active push to carry over useful information from the FastQ read ID + comments into optional fields? Cheers, Felix

**Comment by benjamincarlin** [comment]
Hi Felix,

Thank your response!

For the flag values in my use case, the solution is a tool that adjust samflag values based off of information from both the BAM's and user input.

In addition, would you possibly be willing to accept a patch into Bismark that allows for a flag/optional parameter that when used ignores the read ID description?

**Comment by FelixKrueger** [comment]
Hi Benjamin,

Such a patch would certainly be acceptable. I suppose it would have to be added to all the biTransform... sections, and then to the single-end FastA/FastQ processing steps. This is potentially something I should be able to knock up fairly quickly, unless you would like to have a go yourself?

**Comment by benjamincarlin** [comment]
Hi Felix!

I think I can give it a go, unless, you have the time to work on it now? Also, I am not as familiar with the code base but why not just modify the fix id method itself?

**Comment by FelixKrueger** [comment]
I'll see if I can do something about it tomorrow. Cheers, Felix

**Comment by FelixKrueger** [comment]
Hi Benjamin,

I just added a new option to truncate read IDs at the first space (or tab) it encounters in the (FastQ) read ID, which are sometimes used to add comments to a FastQ entry (instead of replacing them with underscores (_) as is the default behaviour).

For lack of a better name the option is currently called `--icpc` ("I couldn't possibly comment"), and kept a bit cryptic as it only becomes relevant when R1 and R2 of a read pair are mapped separately in single-end mode, and then re-paired afterwards. Paired-end mapping already creates BAM files with identical read IDs.

Can you clone the latest development version and let me know if it works in your hands?

**Comment by benjamincarlin** [comment]
Thanks!

I created a PR with a possible suggestion, please treat this as just a suggestions if it helps!

**Comment by benjamincarlin** [comment]
Do you have an idea when the next release will be?

**Comment by FelixKrueger** [comment]
Very soon indeed, I am hoping within the next two days actually.

**Comment by FelixKrueger** [comment]
New release is out now, go try it out! Feedback welcomed. Cheers, Felix

**Comment by benjamincarlin** [comment]
Yay! and will do!
