### ISSUE TITLE
identify forward strand and reverse strand in single-end alignment

### ISSUE THREAD

**Issue by sunshine-lp0** [FelixKrueger/Bismark#239]
Hi Felix,

I used Read2 (OT and OB) to do single-end alignment. OT reads received a FLAG of 0 while OB received a FLAG of 16. But how can I know if they are from forward strand or reverse strand？

Best,
Anita

**Comment by FelixKrueger** [comment]
Well, the OT (= original top) strand is the forward strand, and the OB (= original bottom) strand is the reverse strand. The FLAGs are assigned accordingly.

**Comment by sunshine-lp0** [comment]
So in bam file, reads were all corrected to the forward strand which is the reference itself?

Here are my data:
BAM file:
TTCC_GTAC_CACTA_ST-E00243:606:HY32VCCXY:3:1119:16843:27398_2:N:0:AGTCAAAT       16      chr1    10447   255   4
6M      *       0       0       **CCCTAACCCTAACCCTAACCCTCGCGATACCCTCAACCGACCCGCG**  JJJFJJJJJJJJJJJJJJJJJJJJJJJFJJJJFJJJJJJJJJJJJJ NM:i:4  MD:Z:26G8G3G5C0 XM:Z:.......................Z.Zx........x..Zx...Z..     XR:Z:CT XG:Z:GA

Read2:
@TTCC_GTAC_CACTA ST-E00243:606:HY32VCCXY:3:1119:16843:27398 2:N:0:AGTCAAAT
**CGCGGGTCGGTTGAGGGTATCGCGAGGGTTAGGGTTAGGGTTAGGG**
+
JJJJJJJJJJJJJFJJJJFJJJJJJJJJJJJJJJJJJJJJJJFJJJ

**Comment by sunshine-lp0** [comment]
Dear Felix,
I'm solved the problem. Thanks for your patience!
