### ISSUE TITLE
methylation calling in watson and crick helix chain separately

### ISSUE THREAD

**Issue by Shicheng-Guo** [FelixKrueger/Bismark#24]
I think there must some way to calling the methylation frequency in watson and crick helix chain separately. Am I right? Where I can find this information before the methylation frequency calling?

**Comment by FelixKrueger** [comment]
Bismark performs all read alignments and methylation calls in one combined process. If you are then only interested in one particular strand you can proceed using the output files of the methylation extractor which have OT (original top, or Watson) or OB (original bottom, or Crick) in their filename.

**Comment by Shicheng-Guo** [comment]
Hi Felix,

I cannot find the setting for this situation. I do not to separate the methylation frequency/read counts for different strain (Watson and Crick). 

Any practicable command could do this? I know bismark_methylation_extractor can provide some strand specific result. However, in these output file, there is no reads counts for methylation and non-methylation.

For example:

`bismark_methylation_extractor --multicore 6 ENCFF000LVF_trimmed.fq.gz_bismark_bt2.bam`

6 output were created by bismark_methylation_extractor：

 CpG_OT_ENCFF000LVF_trimmed.fq.gz_bismark_bt2.txt
CpG_OB_ENCFF000LVF_trimmed.fq.gz_bismark_bt2.txt
CHH_OT_ENCFF000LVF_trimmed.fq.gz_bismark_bt2.txt
CHH_OB_ENCFF000LVF_trimmed.fq.gz_bismark_bt2.txt
CHG_OT_ENCFF000LVF_trimmed.fq.gz_bismark_bt2.txt
CHG_OB_ENCFF000LVF_trimmed.fq.gz_bismark_bt2.txt

However, the content for these files are as the following:

Bismark methylation extractor version v0.14.4
ILLUMINA-EAS295_30:3:1:3768:1281:0:1:1  -       chr7    103969875       z
ILLUMINA-EAS295_30:3:1:3768:1281:0:1:1  -       chr7    103969884       z
ILLUMINA-EAS295_30:3:1:3768:1281:0:1:1  -       chr7    103969908       z
ILLUMINA-EAS295_30:3:1:10751:1280:0:1:1 +       chr16   904870  Z
ILLUMINA-EAS295_30:3:1:10751:1280:0:1:1 -       chr16   904892  z


no reads counts for methylation and non-methylation were coming out. 


Any suggestion?


Many Thanks 

Shicheng

**Comment by FelixKrueger** [comment]
Hi Shicheng,

`ILLUMINA-EAS295_30:3:1:3768:1281:0:1:1 - chr7 103969908 z`
`ILLUMINA-EAS295_30:3:1:10751:1280:0:1:1 + chr16 904870 Z`

do contain the chromosome (col 3), the position (col 4) and the methylation state (col 2), where `+` means methylated and `-` means non-methylated. You could process this data further to a coverage file (option `--bedGraph` in the methylation extractor) to get all cytosines sorted with all methylated and non-methylated calls per positions. Just take a look at the manual or type `--help` for more information on all the options. Cheers, Felix
