### ISSUE TITLE
Use of uninitialized value $path_to_bowtie in concatenation (.) or string at /hpc/home/minardsmitha/tools/bismark_v0.21.0/bismark line 6893.

### ISSUE THREAD

**Issue by aminards** [FelixKrueger/Bismark#242]
I am scratching my head as to why I am getting this error.  I have copied the path to bowtie2 directly from my system so as to be sure there are no typos.  Is there something else I need to be doing?  Here is my command:  

/hpc/home/smith/tools/bismark_v0.21.0/bismark \
--path_to_bowtie2 /hpc/home/smith/tools/bowtie2-2.3.5 \
--parallel 8 -o /hpc/home/smith/Bismark_results \
--non_directional --samtools_path /hpc/home/smith/tools/samtools/samtools-0.1.19 \
/hpc/home/smith/Indexed_genomes/Rattus_norvegicus \
-1 /hpc/home/smith/Bismark_analysis/89_R1_val_1.fq,/hpc/home/smith/Bismark_analysis/91_R1_val_1.fq \
-2 /hpc/home/smith/Bismark_analysis/89_R2_val_2.fq,/hpc/home/smith/Bismark_analysis/91_R2_val_2.fq

Here is the full error message I get when I try to run this:

Use of uninitialized value $path_to_bowtie in concatenation (.) or string at /hpc/home/smith/tools/bismark_v0.21.0/bismark line 6893.
Failed to execute Bowtie 2 porperly (return code of 'bowtie2 --version' was 32512). Please install Bowtie 2 or HISAT2 first and make sure it is in the PATH, or specify the path to the Bowtie 2 with --path_to_bowtie2 /path/to/bowtie2, or --path_to_hisat2 /path/to/hisat2

Is there something else I need to be doing to get this to run correctly?
Thank you.

**Comment by FelixKrueger** [comment]
Couldn't it simply need adding `bowtie2` to the end, like so:

```
--path_to_bowtie2 /hpc/home/smith/tools/bowtie2-2.3.5/bowtie2
```

If you are able to run `/hpc/home/smith/tools/bowtie2-2.3.5/bowtie2 --version` successfully in a shell, it should also work within Bismark.

**Comment by aminards** [comment]
I tried adding bowtie2 to the end of the path and got this error:

The path to Bowtie 2 provided (/hpc/home/smith/tools/bowtie2-2.3.5/bowtie2/) is invalid (not a directory)!

I was able to run /hpc/home/smith/tools/bowtie2-2.3.5/bowtie2 --version successfully .  

I may need to contact our HPC admin I guess.

**Comment by FelixKrueger** [comment]
I just look at the code, and I'm sorry, you should indeed only supply the path, but not the executable itself...

so `--path_to_bowtie2 /hpc/home/smith/tools/bowtie2-2.3.5` should work just fine. 

I am wondering if it could be the `-` in the name? Could you try putting the path into inverted commas, like so:

`--path_to_bowtie2 "/hpc/home/smith/tools/bowtie2-2.3.5"`

**Comment by aminards** [comment]
I tried your suggestion by surrounding the bowtie2 path in the quotes and get the same error "Use of uninitialized value....".

I did add a line in the job script to add Bowtie2 to my PATH and omitted the  --path_to_bowtie2 parameter and Bismark is running now.  So I have a working solution.  I just wonder why I can't seem to use the --path_to_bowtie2.

**Comment by FelixKrueger** [comment]
Right, I found the culprit. There was simply a single character (`2`) missing while processing the path information. Sorry for that. If you get the latest dev version, it should now work. Fixed in https://github.com/FelixKrueger/Bismark/commit/ee5d5e912a0e1a9da9ac6df45c5ba6040541955f.
