### ISSUE TITLE
How to set the sample distance of SA?

### ISSUE THREAD

**Issue by chhylp123** [FelixKrueger/Bismark#243]
Hi Felix,

May I ask if it is possible for users to set the sample distance of SA of FM-index? I mean how to change the following option of bowtie2 when indexing:

-o/--offrate <int> SA is sampled every 2^<int> BWT chars (default: 5)

Thank you in advance!

**Comment by FelixKrueger** [comment]
This is currently not possible, but I supposed it could be added fairly easily if this is really something that people would like to change often (I have so far not really come across it to be honest). If it is just a one-off thing it would probably be easiest if you just locate the lines in the indexer that calls `bowtie2-build` and add the offrate manually.

**Comment by chhylp123** [comment]
> This is currently not possible, but I supposed it could be added fairly easily if this is really something that people would like to change often (I have so far not really come across it to be honest). If it is just a one-off thing it would probably be easiest if you just locate the lines in the indexer that calls `bowtie2-build` and add the offrate manually.

Thank you. I will modify `bowtie2-build` as you said.

**Comment by FelixKrueger** [comment]
Great. Let me know if you require any action on my part. Best, Felix
