### ISSUE TITLE
Bismark with Hisat2 --no-spliced-alignment

### ISSUE THREAD

**Issue by jsemple19** [FelixKrueger/Bismark#247]
Hi Felix,

I am trying to analyse whole genome bisulfite sequencing with Bismark+HiSat2.
This is the command i use:

`${BISMARKDIR}/bismark --hisat2 --no-spliced-alignment --genome ${genomeDir} -X 600 -o aln/ -B ${bname}_${seqDate} --nucleotide_coverage -1 trim/${bname}_${seqDate}_1P.fq.gz -2 trim/${bname}_${seqDate}_2P.fq.gz`

And i keep on getting the following error message:
`Now starting a HISAT2 paired-end alignment for CTread1GAread2CTgenome (reading in sequences from dS16N2gw_20190206_1P.fq.gz_C_to_T.fastq and dS16N2gw_20190206_2P.fq.gz_G_to_A.fastq, with the options: -q --score-min L,0,-0.2 --ignore-quals --no-mixed --no-discordant --maxins 600 --no-spliced-alignments --no-softclip --omit-sec-seq --norc))
/software/UHTS/Aligner/hisat/2.1.0/bin/hisat2-align-s: unrecognized option '--no-spliced-alignments'
HISAT2 version 2.1.0 by Daehwan Kim (infphilo@gmail.com, www.ccb.jhu.edu/people/infphilo)`

For some reason, my command with "--no-spliced-alignment" is translated to "--no-spliced-alignments" (with an s at the end which is then not a valid parameter of hisat2).

If it is just a typo in the wrapper for hisat it should be easy to fix... i hope :-)

**Comment by FelixKrueger** [comment]
Hi Jennifer,

Thanks for noticing this, it is in fact already fixed in the development version. Could you clone that and let me know if it works as expected in your hands?

Cheers, Felix

**Comment by jsemple19** [comment]
Yes! the dev version is working fine. Thanks!

**Comment by FelixKrueger** [comment]
Great, thanks for the feedback.
