### ISSUE TITLE
subprocess.CalledProcessError <Signals.SIGPIPE: 13>

### ISSUE THREAD

**Issue by s18692001** [FelixKrueger/Bismark#248]
Hi there,

When I try to use bismark with python subprocess, I get the following error message:

`subprocess.CalledProcessError: Command '['bismark', '/fasta', '--bowtie2', 'R1.trimed.fq.gz', '--pbat', '-o', '/M1-1-2-B1', '--temp_dir', '/M1-1-2-B1']' died with <Signals.SIGPIPE: 13>.`

Any suggestion?

**Comment by FelixKrueger** [comment]
I'm sorry but I have no experience with Python subprocess whatsoever...

**Comment by qoldt** [comment]
@shengyongniu did you ever find a solution to this? I'm getting a similar error when running bismark with Snakemake.
