### ISSUE TITLE
Bam file suitable for bismark_methylation_extractor

### ISSUE THREAD

**Issue by Shicheng-Guo** [FelixKrueger/Bismark#25]
Do you think bismark_methylation_extractor will be working for all kind of bam files not only created by bismaker? Do you think the bam files created by BWA can also be used for methylation calling by bismark_methylation_extractor?

**Comment by FelixKrueger** [comment]
Bismark works exclusively with Bismark BAM files I am afraid since e.g. BWA doesn't do any of the steps for methylation analysis (which was the reason why we wrote Bismark in the first place...).
