### ISSUE TITLE
separating bedGraph file into three context-dependent file

### ISSUE THREAD

**Issue by AudryZhao** [FelixKrueger/Bismark#259]
hi Felix,
Bismark is amazing and it works well for me.
BUT I am wondering whether there is any option to separate bedGraph file into three context-dependent file, so that visualization also can be context-dependent. 
Please give me a hand.
Thanks.

**Comment by FelixKrueger** [comment]
Hi Audry,

The easiest way to go on about this is probably to pick and choose the context you want to be using. So you might want to run three independent bedGraph conversions using the C* context files that the methylation extractor produces, e.g. like so:

```
bismark2bedGraph --gzip --buffer 10G -o CpG_context CpG*
bismark2bedGraph --gzip --buffer 10G -o CHG_context CHG*
bismark2bedGraph --gzip --buffer 10G -o CHH_context CHH*
```

Another option might be to continue with the `coverage2cytosine` step, and then use a post-filtering command or script to filter out just the context you are interested in. Does that make sense?

**Comment by AudryZhao** [comment]
Hi Felix,
I tried the first way you suggested and all I want to say  is
"EVVIVA FELIX".
Thank you so much.

**Comment by FelixKrueger** [comment]
Glad it worked!
