### ISSUE TITLE
GpC methylation calls for each alignment

### ISSUE THREAD

**Issue by genomics-kl** [FelixKrueger/Bismark#268]
Hi @FelixKrueger,

I know that `coverage2cytosine` has functionality for outputting per-position methylation counts/percentages in `.cov` format for GpC/NOME-seq methylation. However, I am working on a NOME-seq project that requires filtering the BAM file for alignments containing at least one methylated CpG or GpC site before doing the total counts. CpG only methylation is easy since I can simply filter BAM alignments by requiring that the XM tag contain at least one 'Z'. However, GpC methylation is much trickier since it is not represented in the XM tag.

I was wondering if you have any ideas or suggestions for achieving this. I can do basic scripting and manipulation of BAM files in Perl and R.

Thanks in advance for your help.

**Comment by FelixKrueger** [comment]
Hi @genomics-kl ,

I am almost glad you are asking, because I might incidentally have something you might want to use.... (I spent quite some time on this in 2017, and no one has since really needed it).

 If you call the `bismark_methylation_extractor` with the option `--yacht`, it will write out the context files some additional information about the read.

```
--yacht                  This option (Yet Another Context Hunting Tool) writes out additional information about the read a methylation
                         call belongs to, and its output is meant to be fed into the NOMe_filtering script. This option writes out
                         a single 'any_C_context' file that contains all methylation calls for a read consecutively. Its intended use
                         is single-cell NOMe-Seq data, and thus this option works only in single-end mode (paired-end reads often suffer
                         from chimaera problems...)

                         --yacht will add three additional columns to the standard methylation call files:
                                    <read start>  <read end>  <read orientation>
                         For forward reads (+ orientation) the start position is the left-most position wheras for reverse reads
                         (- orientation) it is the rightmost position.

```

You can then feed the resulting `any_C_context...` file into `NOMe_filtering`. The output of this procedure is then a file with `manOwar` in its name (please don't ask), which should look like this:


```
OUTPUT FORMAT:

The NOMe-Seq filtering output reports cytosines in CpG context only if they are in A-CG or T-CG context,
and cytosines in GC context only when the C is not in CpG context. The output file is tab-delimited and in
the following format (1-based coords):
===========================================================================================================

<readID>  <chromosome>  <read start>  <read end>  <count methylated CpG>  <count non-methylated CpG>  <count methylated GC>  <count non-methylated GC>
HWI-D00436:298:C9KY4ANXX:1:1101:2035:2000_1:N:0:_ACAGTGGT 10 8517979 8518098 0 1 0 1 
HWI-D00436:298:C9KY4ANXX:1:1101:5072:1993_1:N:0:_ACAGTGGT 8 9476630 9476748 0 0 0 2 
```

Now finally, I think you should be able to make use of this file by:

- reading in the `manOwar` file, filtering on GC methylation, and store the read ID (or at least the first part of the file, `HWI-D00436:298:C9KY4ANXX:1:1101:2035:2000` in the example above)
- read in again the Bismark BAM file, and write out only reads that contain the (previously filtered) read IDs

I don't think this adaptation will take much more than a few minutes (if your samples are paired-end it might be a little more complicated). I'd be happy to help out if you are struggling.

Let me know how you get on.
Cheers, Felix

**Comment by genomics-kl** [comment]
Hi @FelixKrueger,

Thanks so much for the prompt response. It looks like your suggestions should work perfectly for me and I have just tried running `--yacht`. I have two follow-up questions about your proposed approach:

1. Actually, I am indeed working with paired data. I found out that the script will not run in paired-end mode when `--yacht` is set. I was able to run to completion using `--single-end` to 'trick' it into thinking it is SE data. Is there anything to beware of when doing this?

2. In`NOMe_filtering`, the default is to retain only the CpG and GpC contexts that can be unequivocally identified as either CG or GC. In my case, I just want to identify the sites that are CpG OR GpC. It seems like there is a `nome-seq` flag in `NOMe_filtering`, but it seems to be hard-coded as 1. Are there any work-arounds for this? Can I change $nome to 0 within the `NOMe_filtering` script?

Thanks again for all your help!

PS: Sorry you're going to have to give me a hint about the `manOwar` name.

**Comment by FelixKrueger** [comment]
- To 1:  I don't think that this should be an issue. If I understand it correctly, you would like to generate a whitelist of reads that you would like to filter out from the BAM files, and characterise further. Isn't that right? Paired end files tend to have different read IDs in the FastQ files (e.g.: `1:N:0` or `2:N:0`), but in the BAM file they both have:
```
HWI-D00436:298:C9KY4ANXX:1:1101:2035:2000_1:N:0:_ACAGTGGT
HWI-D00436:298:C9KY4ANXX:1:1101:2035:2000_1:N:0:_ACAGTGGT
```

Thus, you should be able to use the entire read ID for your whitelist, and simply mark the entire read pair as `pass` if one or the other, or both of the reads, fulfill your filtering criteria.

2. If you want to to merge CpG and GpC contexts you would have to do manually edit the context conditions somewhere within the script, it is definitely not made to work like that. If you need help with that I could take a look.

**Comment by genomics-kl** [comment]
Yes, your response to 1. is exactly what I am trying to do.

To 2., I think a possible work-around would be to make the 'white-list' by finding the union of 1) Parsing for 'Z' in the BAM file for CG methylation and 2) the approach you suggested here for GC methylation.

Thanks again for all your help and ideas.

**Comment by FelixKrueger** [comment]
OK, all the best. Shout out if you need anything.
