### ISSUE TITLE
Add option to coverage2cytosine to only output covered positions

### ISSUE THREAD

**Issue by FelixKrueger** [FelixKrueger/Bismark#269]
As referenced here: https://github.com/FelixKrueger/Bismark/issues/143#issuecomment-506509161

**Comment by FelixKrueger** [comment]
I have now added a new option `--coverage_threshold INT`. Positions have to be covered by at least `INT` calls (irrespective of their methylation state) before they get reported. 

- For NOMe-seq, the minimum threshold is automatically set to 1 unless specified explicitly.
- Setting a coverage threshold does not work in conjunction with `--merge_CpGs` (as all genomix CpGs are required for this). 
- Default: 0 (i.e. all genomic positions get reported)

**Comment by FelixKrueger** [comment]
Addressed here: 2123b3afa8f89f29e44083210cb86944fe4d17ea.

**Comment by yongchao** [comment]
I did the test and confirmed that It is working as expected. Thanks for adding this option.

**Comment by FelixKrueger** [comment]
Thanks for the feedback

**Comment by NomiCentarix** [comment]
> I have now added a new option `--coverage_threshold INT`. Positions have to be covered by at least `INT` calls (irrespective of their methylation state) before they get reported.
> 
> * For NOMe-seq, the minimum threshold is automatically set to 1 unless specified explicitly.
> * Setting a coverage threshold does not work in conjunction with `--merge_CpGs` (as all genomix CpGs are required for this).
> * Default: 0 (i.e. all genomic positions get reported)

Hello
Does this option (which is helpful) exist? Because I don't see it in the docs.

**Comment by FelixKrueger** [comment]
Yes it does, if you type `--coverage2cytosine --help` you can see, and then use it!

**Comment by NomiCentarix** [comment]
thanks for the quick answer! 
So I see there are more options which are not documented yet?

**Comment by FelixKrueger** [comment]
I am not sure if all options of downstream modules will actually go into the main documentation - but yea, they probably should. `--help` should always be the most up-to-date version!

**Comment by NomiCentarix** [comment]
ok, thank you!
