### ISSUE TITLE
deduplicate_bismark to keep the first paired-end

### ISSUE THREAD

**Issue by yongchao** [FelixKrueger/Bismark#271]
Hi,

In the code below when removing the duplicated reads

https://github.com/FelixKrueger/Bismark/blob/2123b3afa8f89f29e44083210cb86944fe4d17ea/deduplicate_bismark#L838

It keeps only the the first paired-end line for SAM output. I'm wondering if the code can be revised to take all reads that are mapped to the same positions and shared with the same barcode, but we keep the one with the best alignment (the fifth column of bam file).

Of course, one can work around this by ordering the sam files according to the alignment score first and then by read name before calling the command deduplicate_bismark.
`samtools view -H $bam >$sam`
 `samtools view $bam |sort -k5,5n -k1,1 -s >>$sam`
`samtoos view  -b $sam -o $bam_sorted`

I haven't worked in perl for many years and I don't know how much is it going to be involved to revise the perl code to take the best alignment ( I guess you have to save all reads that are mapped in the same positions, so the variable unique_seqs{$composite} is not a simple count, but a vector to store all of the reads and then post processing the reads after the whole bam file is finished). If it's not much work, it will be nice to have the code revised with this new feature. 

This also applies to simple deduplicate command that doesn't use the barcode for RRBS data, such as  below https://github.com/FelixKrueger/Bismark/blob/2123b3afa8f89f29e44083210cb86944fe4d17ea/deduplicate_bismark#L482

**Comment by FelixKrueger** [comment]
Hi @yongchao,

Thanks for your suggestion. Such a change wouldn't be very hard to implement, and in fact we even used to have something similar in the deduplicator years and years ago, but this was dropped eventually (at that time it printed out the highest represented methylation call and not the highest MAPQ score, but the idea is the same). 

The reason why I don't really want to add this as a standard option is rather simple - it doesn't scale very well...: It might work well if you only have a limited number of alignments to work with, but then comes the next person with 800 million, or 1.2 billion alignments which we need to keep all in memory (if we don't want to use `sort` internally), so we would most likely be talking about memory usage of up to a few hundreds of GB..

At the same time I am wondering whether this would make a huge difference, or any difference at all? If you could convince me that there is a big benefit to be had, I might look into this further. The `samtools view` workflow you posted above is probably not super-fast, but if it works and you don't have too many samples it might be a valid option for the time being.

**Comment by yongchao** [comment]
Thanks Felix for the clarification about the memory consumption.  I guess the unix sort is the way to go.

The improvement is probably not much.  For us here, the other concern is when we use different parameters of the --multicore (say once with 2 and another times with 4). The different splitting and joining gives different order of the reads and selects different reads after the de-duplication, which causes different outputs in terms of the bam files and bed coverage file.

I think for the time being, I will go with the samtools view flow. It's not going to be as fast as what would be done in the perl program. The computation time is not too much a worry as nowadays for many samples, it's a given that we have to submit the job for each sample to a different node in a cluster computer anyway to save the time.

by the way, the samtools flow I posted before had a small bug, I should sort the the fifth column in reverse order, so the revised code as below.  

`samtools view -H $bam >$sam`
`samtools view $bam |sort -k5,5nr -k1,1 -s >>$sam`
`samtoos view -b $sam -o $bam_sorted`

**Comment by FelixKrueger** [comment]
Thanks for the comments and the updated code. It'll be a good reference in the future if anyone else wanted to follow a similar path. If you don't object I'll close this issue for the moment. All the best, Felix
