### ISSUE TITLE
Bismark errors 

### ISSUE THREAD

**Issue by RubioB** [FelixKrueger/Bismark#272]
Hi, I'm very new in using bismark. Before to realize bismark alignement, I have prepared my reference genome using bismark_genome_preparation. Then I tried to realized the alignement but whatever I have tried to modify i have this king of output : 

Path to Bowtie 2 specified as: bowtie2
Bowtie seems to be working fine (tested command 'bowtie2 --version' [2.3.3])
Output format is BAM (default)
Alignments will be written out in BAM format. Samtools found here: '/usr/local/bioinfo/src/samtools/samtools-1.4/samtools'
Reference genome folder provided is /work/project/vvegfv/BR_WGBS/RefGenome/Genome_LargeIndex/   (absolute path is '/work/project/vvegfv/BR_WGBS/RefGenome/Genome_LargeIndex/)'
FastQ format assumed (by default)
Each Bowtie 2 instance is going to be run with 3 threads. Please monitor performance closely and tune down if needed!

Input files to be analysed (in current folder '/work/project/vvegfv/BR_WGBS'):
WTC_R1_val_1_part.fq.gz
WTC_R2_val_2_part.fq.gz
Library is assumed to be strand-specific (directional), alignments to strands complementary to the original top or bottom strands will be ignored (i.e. not performed!)
Running Bismark Parallel version. Number of parallel instances to be spawned: 2

Current working directory is: /work/project/vvegfv/BR_WGBS

Now reading in and storing sequence information of the genome specified in: /work/project/vvegfv/BR_WGBS/RefGenome/Genome_LargeIndex/

chr SL2.50ch00 (21805821 bp)
chr SL2.50ch01 (98543444 bp)
chr SL2.50ch02 (55340444 bp)
chr SL2.50ch03 (70787664 bp)
chr SL2.50ch04 (66470942 bp)
chr SL2.50ch05 (65875088 bp)
chr SL2.50ch06 (49751636 bp)
chr SL2.50ch07 (68045021 bp)
chr SL2.50ch08 (65866657 bp)
chr SL2.50ch09 (72482091 bp)
chr SL2.50ch10 (65527505 bp)
chr SL2.50ch11 (56302525 bp)
chr SL2.50ch12 (67145203 bp)

Paired-end alignments will be performed
=======================================

The provided filenames for paired-end alignments are WTC_R1_val_1_part.fq.gz and WTC_R2_val_2_part.fq.gz

Paired-end alignments will be performed
=======================================

The provided filenames for paired-end alignments are WTC_R1_val_1_part.fq.gz and WTC_R2_val_2_part.fq.gz
Finished subdividing WTC_R1_val_1_part.fq.gz for PID: 113296 and offset 2

Using the subset file >WTC_R1_val_1_part.fq.gz.temp.2< as new in-file 1 (instead of >WTC_R1_val_1_part.fq.gz<)
Finished subdividing WTC_R1_val_1_part.fq.gz for PID: 0 and offset 1

Using the subset file >WTC_R1_val_1_part.fq.gz.temp.1< as new in-file 1 (instead of >WTC_R1_val_1_part.fq.gz<)
Finished subdividing WTC_R2_val_2_part.fq.gz for PID: 113296 and offset 2

Using the subset file >WTC_R2_val_2_part.fq.gz.temp.2< as new in-file 2 (instead of >WTC_R2_val_2_part.fq.gz<)
Input files are in FastQ format
Writing a C -> T converted version of the input file WTC_R1_val_1_part.fq.gz.temp.2 to WTC_R1_val_1_part.fq.gz.temp.2_C_to_T.fastq
Finished subdividing WTC_R2_val_2_part.fq.gz for PID: 0 and offset 1

Using the subset file >WTC_R2_val_2_part.fq.gz.temp.1< as new in-file 2 (instead of >WTC_R2_val_2_part.fq.gz<)
Input files are in FastQ format
Writing a C -> T converted version of the input file WTC_R1_val_1_part.fq.gz.temp.1 to WTC_R1_val_1_part.fq.gz.temp.1_C_to_T.fastq

Created C -> T converted version of the FastQ file WTC_R1_val_1_part.fq.gz.temp.1 (2500000 sequences in total)

Writing a G -> A converted version of the input file WTC_R2_val_2_part.fq.gz.temp.1 to WTC_R2_val_2_part.fq.gz.temp.1_G_to_A.fastq

Created C -> T converted version of the FastQ file WTC_R1_val_1_part.fq.gz.temp.2 (2500000 sequences in total)

Writing a G -> A converted version of the input file WTC_R2_val_2_part.fq.gz.temp.2 to WTC_R2_val_2_part.fq.gz.temp.2_G_to_A.fastq

Created G -> A converted version of the FastQ file WTC_R2_val_2_part.fq.gz.temp.2 (2500000 sequences in total)

Input files are WTC_R1_val_1_part.fq.gz.temp.2_C_to_T.fastq and WTC_R2_val_2_part.fq.gz.temp.2_G_to_A.fastq (FastQ)
Now running 2 instances of Bowtie 2 against the bisulfite genome of /work/project/vvegfv/BR_WGBS/RefGenome/Genome_LargeIndex/ with the specified options: -q --score-min L,0,-0.2 -p 3 --reorder --ignore-quals --no-mixed --no-discordant --
dovetail --maxins 500

Now starting a Bowtie 2 paired-end alignment for CTread1GAread2CTgenome (reading in sequences from WTC_R1_val_1_part.fq.gz.temp.2_C_to_T.fastq and WTC_R2_val_2_part.fq.gz.temp.2_G_to_A.fastq, with the options: -q --score-min L,0,-0.2 -p
3 --reorder --ignore-quals --no-mixed --no-discordant --dovetail --maxins 500 --norc))

Created G -> A converted version of the FastQ file WTC_R2_val_2_part.fq.gz.temp.1 (2500000 sequences in total)

Input files are WTC_R1_val_1_part.fq.gz.temp.1_C_to_T.fastq and WTC_R2_val_2_part.fq.gz.temp.1_G_to_A.fastq (FastQ)
Now running 2 instances of Bowtie 2 against the bisulfite genome of /work/project/vvegfv/BR_WGBS/RefGenome/Genome_LargeIndex/ with the specified options: -q --score-min L,0,-0.2 -p 3 --reorder --ignore-quals --no-mixed --no-discordant --
dovetail --maxins 500

Now starting a Bowtie 2 paired-end alignment for CTread1GAread2CTgenome (reading in sequences from WTC_R1_val_1_part.fq.gz.temp.1_C_to_T.fastq and WTC_R2_val_2_part.fq.gz.temp.1_G_to_A.fastq, with the options: -q --score-min L,0,-0.2 -p
3 --reorder --ignore-quals --no-mixed --no-discordant --dovetail --maxins 500 --norc))
Error reading block of _offs[] array: 262140, 184409088Error Reading File!
Error reading block of _offs[] array: 262140, 184409088Error Reading File!
Error: Encountered internal Bowtie 2 exception (#1)
Command: /usr/local/bioinfo/src/bowtie/bowtie2-2.3.3.1/bowtie2-align-s --wrapper basic-0 -q --score-min L,0,-0.2 -p 3 --reorder --ignore-quals --no-mixed --no-discordant --dovetail --maxins 500 --norc -x /work/project/vvegfv/BR_WGBS/RefG
enome/Genome_LargeIndex/Bisulfite_Genome/CT_conversion/BS_CT -1 WTC_R1_val_1_part.fq.gz.temp.2_C_to_T.fastq -2 WTC_R2_val_2_part.fq.gz.temp.2_G_to_A.fastq
Error: Encountered internal Bowtie 2 exception (#1)
Command: /usr/local/bioinfo/src/bowtie/bowtie2-2.3.3.1/bowtie2-align-s --wrapper basic-0 -q --score-min L,0,-0.2 -p 3 --reorder --ignore-quals --no-mixed --no-discordant --dovetail --maxins 500 --norc -x /work/project/vvegfv/BR_WGBS/RefG
enome/Genome_LargeIndex/Bisulfite_Genome/CT_conversion/BS_CT -1 WTC_R1_val_1_part.fq.gz.temp.1_C_to_T.fastq -2 WTC_R2_val_2_part.fq.gz.temp.1_G_to_A.fastq
/var/spool/slurm/d/job6709449/slurm_script: line 17: 90164 Killed                  bismark --genome /work/project/vvegfv/BR_WGBS/RefGenome/Genome_LargeIndex --parallel 2 -p 3 -1 WTC_R1_val_1_part.fq.gz -2 WTC_R2_val_2_part.fq.gz
(ERR): bowtie2-align exited with value 1
slurmstepd: error: Detected 3 oom-kill event(s) in step 6709449.batch cgroup

I dont' understand what is the problem. First I thought that it was a problem with the genome preparation step so I re-run the script, I have tried to use different versions of bowtie and bismark, also different genome versions but nothing works...

My command lines are as follows 
 - for genome preparation : bismark_genome_preparation --verbose --bowtie2 /work/project/vvegfv/BR_WGBS/RefGenome/Genome

 - for alignement : bismark --genome /work/project/vvegfv/BR_WGBS/RefGenome/Genome --parallel 2 -p 3 --non_directionnal -1 WTC_R1_val_1_part.fq.gz -2 WTC_R2_val_2_part.fq.gz

Thank you in advance for your help !

**Comment by FelixKrueger** [comment]
Hi @RubioB ,

You seem to be running into several problems, and if I had to guess then I would assume that you either don't have enough system resources available, or didn't ask for enough memory when submitting your job:

```
Error reading block of _offs[] array: 262140, 184409088Error Reading File!
Error reading block of _offs[] array: 262140, 184409088Error Reading File!
Error: Encountered internal Bowtie 2 exception (#182 
```
This
```
slurmstepd: error: Detected 3 oom-kill event(s) in step 6709449.batch cgroup
```

In your command:
- you are using 4 threads of the `--non_directional` alignments, which is normally not required (are you sure you have non-directional data? I'd be happy to look at a FastQC html report for you and advise based on that)
- you are also asking for 3 cores for each Bowtie2 thread (`-p 3`)
- and you are asking to split the run into 2 parallel sessions.

Assuming that the tomato genome is ~1/3 the size of the human genome, I would guess that your command will use ~30 cores, and ~15GB of RAM. Did you ask Slurm for that much?

I would probably try with a single instance first, and see if that succeeds:

`bismark --genome Genome -1 WTC_R1_val_1_part.fq.gz -2 WTC_R2_val_2_part.fq.gz`

**Comment by RubioB** [comment]
Hi,

Thank you very much for your answer. I did undertstand that there might be a memory problem...

I started a new job following your advices : bismark --genome Genome -1 WTC_R1_val_1_part.fq.gz -2 WTC_R2_val_2_part.fq.gz (I have asked 96G0) I obtained this kind of report where 1/I always have an error related to bowtie (Error reading _ebwt[] array: 200620, 245878784Error Reading File! Error: Encountered internal Bowtie 2 exception (#1)) 2/ at the end I always have an oom-kill event...
However, I have the impression that the analysis was done in full...I'm wrong ? I have obtained one bam file and one report file. Should no I have two bam files because I'm in paired end ?


Thanks a lot for your help,


Bernadette


Path to Bowtie 2 specified as: bowtie2
Bowtie seems to be working fine (tested command 'bowtie2 --version' [2.3.3])
Output format is BAM (default)
Alignments will be written out in BAM format. Samtools found here: '/usr/local/bioinfo/src/samtools/samtools-1.4/samtools'
Reference genome folder provided is GenomeWithoutSinglefasta/   (absolute path is '/work/project/vvegfv/BR_WGBS/GenomeWithoutSinglefasta/)'
FastQ format assumed (by default)

Input files to be analysed (in current folder '/work/project/vvegfv/BR_WGBS'):
WTC_R1_val_1_part.fq.gz
WTC_R2_val_2_part.fq.gz
Library is assumed to be strand-specific (directional), alignments to strands complementary to the original top or bottom strands will be ignored (i.e. not performed!)
Setting parallelization to single-threaded (default)

Current working directory is: /work/project/vvegfv/BR_WGBS

Now reading in and storing sequence information of the genome specified in: /work/project/vvegfv/BR_WGBS/GenomeWithoutSinglefasta/

chr SL2.50ch00 (21805821 bp)
chr SL2.50ch01 (98543444 bp)
chr SL2.50ch02 (55340444 bp)
chr SL2.50ch03 (70787664 bp)
chr SL2.50ch04 (66470942 bp)
chr SL2.50ch05 (65875088 bp)
chr SL2.50ch06 (49751636 bp)
chr SL2.50ch07 (68045021 bp)
chr SL2.50ch08 (65866657 bp)
chr SL2.50ch09 (72482091 bp)
chr SL2.50ch10 (65527505 bp)
chr SL2.50ch11 (56302525 bp)
chr SL2.50ch12 (67145203 bp)

Single-core mode: setting pid to 1

Paired-end alignments will be performed
=======================================

The provided filenames for paired-end alignments are WTC_R1_val_1_part.fq.gz and WTC_R2_val_2_part.fq.gz
Input files are in FastQ format
Writing a C -> T converted version of the input file WTC_R1_val_1_part.fq.gz to WTC_R1_val_1_part.fq.gz_C_to_T.fastq

Created C -> T converted version of the FastQ file WTC_R1_val_1_part.fq.gz (5000000 sequences in total)

Writing a G -> A converted version of the input file WTC_R2_val_2_part.fq.gz to WTC_R2_val_2_part.fq.gz_G_to_A.fastq

Created G -> A converted version of the FastQ file WTC_R2_val_2_part.fq.gz (5000000 sequences in total)

Input files are WTC_R1_val_1_part.fq.gz_C_to_T.fastq and WTC_R2_val_2_part.fq.gz_G_to_A.fastq (FastQ)
Now running 2 instances of Bowtie 2 against the bisulfite genome of /work/project/vvegfv/BR_WGBS/GenomeWithoutSinglefasta/ with the specified options: -q --score-min L,0,-0.2 --ignore-quals --no-mixed --no-discordant --dovetail --maxins
500

Now starting a Bowtie 2 paired-end alignment for CTread1GAread2CTgenome (reading in sequences from WTC_R1_val_1_part.fq.gz_C_to_T.fastq and WTC_R2_val_2_part.fq.gz_G_to_A.fastq, with the options: -q --score-min L,0,-0.2 --ignore-quals --
no-mixed --no-discordant --dovetail --maxins 500 --norc))
Found first alignment:
E00602:218:HVMKHCCXY:6:1101:6695:1450_1:N:0/1   77      *       0       0       *       *       0       0       NTGGATTATGGATATTTATATAGGATTGTATGATGTTGAGTATGGAATTTTATTATTTTTATTGGTAGTATAAGTAGTTAAATGATGTTGGATGTGATATATTATATTTGATTTTGGAGAAAATA
TATGATGGTTTGGAAAGTATGT  #AAAFJJJJJJJFJFAJJJJJJJJJJ<AJJJJJJJFJJAF<FJAJFJFJJFJJJJJJJJJJJJJJJJJJJJJJJJJJFJFJJFFFJFJ-A<-AFJJJFJJJJJJJJFFAJ-F-FFJJ7FJJJJ-F-A7<-77-777AFJ<FFFJJFF     YT:Z:UP
E00602:218:HVMKHCCXY:6:1101:6695:1450_2:N:0/2   141     *       0       0       *       *       0       0       AAAATTAAAATAACATACCACACCCAACATTATCTAACCATATATACTACACAAAAACCATAATACATACCACACCTAATATATTCAAATCATACATATTATCCAAAAACAATAATAACATACCA
AACTCAACTTTATTCAACCATACAT       AAFFFJJJJJJJJJJJJJJJJFFFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFJJJJJJFFAAFJJFJ77AAJAAFJFFAJJJJJAFJ7JJFJJJA7-<FFFJA<FJJJJAFAJAFFA<-F7--AF<<7<<AJ--F--<-<AJJ  YT:Z:UP
Now starting a Bowtie 2 paired-end alignment for CTread1GAread2GAgenome (reading in sequences from WTC_R1_val_1_part.fq.gz_C_to_T.fastq and WTC_R2_val_2_part.fq.gz_G_to_A.fastq, with the options: -q --score-min L,0,-0.2 --ignore-quals --
no-mixed --no-discordant --dovetail --maxins 500 --nofw))
Error reading _ebwt[] array: 200620, 245878784Error Reading File!
Error: Encountered internal Bowtie 2 exception (#1)
Command: /usr/local/bioinfo/src/bowtie/bowtie2-2.3.3.1/bowtie2-align-s --wrapper basic-0 -q --score-min L,0,-0.2 --ignore-quals --no-mixed --no-discordant --dovetail --maxins 500 --nofw -x /work/project/vvegfv/BR_WGBS/GenomeWithoutSingle
fasta/Bisulfite_Genome/GA_conversion/BS_GA -1 WTC_R1_val_1_part.fq.gz_C_to_T.fastq -2 WTC_R2_val_2_part.fq.gz_G_to_A.fastq
(ERR): bowtie2-align exited with value 1
Found no alignment, assigning undef to last_seq_id and last_lines

>>> Writing bisulfite mapping results to WTC_R1_val_1_part_bismark_bt2_pe.bam <<<


Reading in the sequence files WTC_R1_val_1_part.fq.gz and WTC_R2_val_2_part.fq.gz
Processed 1000000 sequence pairs so far
Processed 2000000 sequence pairs so far
Processed 3000000 sequence pairs so far
Processed 4000000 sequence pairs so far
5000000 reads; of these:
  5000000 (100.00%) were paired; of these:
    2896047 (57.92%) aligned concordantly 0 times
    1565896 (31.32%) aligned concordantly exactly 1 time
    538057 (10.76%) aligned concordantly >1 times
42.08% overall alignment rate
Processed 5000000 sequence pairs so far
Processed 5000000 sequences in total


Successfully deleted the temporary files WTC_R1_val_1_part.fq.gz_C_to_T.fastq and WTC_R2_val_2_part.fq.gz_G_to_A.fastq

Final Alignment report
======================
Sequence pairs analysed in total:       5000000
Number of paired-end alignments with a unique best hit: 1970510
Mapping efficiency:     39.4%

Sequence pairs with no alignments under any condition:  2896047
Sequence pairs did not map uniquely:    133443
Sequence pairs which were discarded because genomic sequence could not be extracted:    0

Number of sequence pairs with unique best (first) alignment came from the bowtie output:
CT/GA/CT:       1970510 ((converted) top strand)
GA/CT/CT:       0       (complementary to (converted) top strand)
GA/CT/GA:       0       (complementary to (converted) bottom strand)
CT/GA/GA:       0       ((converted) bottom strand)

Number of alignments to (merely theoretical) complementary strands being rejected in total:     0

Final Cytosine Methylation Report
=================================
Total number of C's analysed:   101015999

Total methylated C's in CpG context:    10012445
Total methylated C's in CHG context:    7760805
Total methylated C's in CHH context:    7827196
Total methylated C's in Unknown context:        3517

Total unmethylated C's in CpG context:  3744805
Total unmethylated C's in CHG context:  6234387
Total unmethylated C's in CHH context:  65436361
Total unmethylated C's in Unknown context:      15689

C methylated in CpG context:    72.8%
C methylated in CHG context:    55.5%
C methylated in CHH context:    10.7%
C methylated in unknown context (CN or CHN):    18.3%


Bismark completed in 0d 1h 33m 47s

====================
Bismark run complete
====================

slurmstepd: error: Detected 1 oom-kill event(s) in step 6830035.batch cgroup.
________________________________
De : FelixKrueger <notifications@github.com>
Envoyé : mardi 23 juillet 2019 14:53
À : FelixKrueger/Bismark <Bismark@noreply.github.com>
Cc : RubioB <bernadetterubio@hotmail.com>; Mention <mention@noreply.github.com>
Objet : Re: [FelixKrueger/Bismark] Bismark errors (#272)


Hi @RubioB<https://github.com/RubioB> ,

You seem to be running into several problems, and if I had to guess then I would assume that you either don't have enough system resources available, or didn't ask for enough memory when submitting your job:

Error reading block of _offs[] array: 262140, 184409088Error Reading File!
Error reading block of _offs[] array: 262140, 184409088Error Reading File!
Error: Encountered internal Bowtie 2 exception (#182


This

slurmstepd: error: Detected 3 oom-kill event(s) in step 6709449.batch cgroup


In your command:

  *   you are using 4 threads of the --non_directional alignments, which is normally not required (are you sure you have non-directional data? I'd be happy to look at a FastQC html report for you and advise based on that)
  *   you are also asking for 3 cores for each Bowtie2 thread (-p 3)
  *   and you are asking to split the run into 2 parallel sessions.

Assuming that the tomato genome is ~1/3 the size of the human genome, I would guess that your command will use ~30 cores, and ~15GB of RAM. Did you ask Slurm for that much?

I would probably try with a single instance first, and see if that succeeds:

bismark --genome Genome -1 WTC_R1_val_1_part.fq.gz -2 WTC_R2_val_2_part.fq.gz

**Comment by FelixKrueger** [comment]
It looks like at least one alignment thread completed this time, to the OT (original top strand). 

Bowtie 2 encountered another exception for the OB strand though:
```
Error reading _ebwt[] array: 200620, 245878784Error Reading File!
Error: Encountered internal Bowtie 2 exception (#1)
...
(ERR): bowtie2-align exited with value 1
```

So my guess is that you probably already ran out of memory during the indexing process and that the index for the C>T converted bottom strand is faulty/corrupt. Is that a possibility? I would probably repeat the indexing process (with more resources), and then try again. This should then also bring up your mapping efficiency to ~80% overall. 

Cheers, Felix

**Comment by FelixKrueger** [comment]
I assume you got this to work in the end?
