### ISSUE TITLE
Running with --sam option

### ISSUE THREAD

**Issue by DolapoA** [FelixKrueger/Bismark#273]
Hi there,

If you run bismark with the `--sam` option **and** the `--parallel` option it simply does not run and there is no info given to remove the one or the other in order to get it to work. However, having looked through the bismark script and saw:
`die "The multicore function currently requires the output to be in BAM format, so please lose either option --sam or --multi\n";` - **line 8614**

...I took it to mean that I've got to remove the --parallel option from bismark in order to get it running. This got it to work. Just thought you might want to mention that in the --help info under --sam. 

Thanks.

**Comment by FelixKrueger** [comment]
Thanks for the comment. I have now added a statement to the help text.

By the way, the much preferred option would be to install Samtools, as writing out BAM files only takes a fraction of the disk-space required.
