### ISSUE TITLE
bismark-methylation-extractor problem

### ISSUE THREAD

**Issue by Wentting** [FelixKrueger/Bismark#276]
Hi Felix,
Thanks for the excellent work on Bismark,it is so friendly
to use!
I've been using Bismark to process some scBS-seq data, there are some problems confused me a lot about the bismark-methylation-extractor function. I've used it on my data and produced some files successfully. But I noticed that the .cov.gz and bedGraph files have not the strand message which is important in the annotation step. So I wondered that if there are some parameters to add the stand message in this two files. 
At first I want to use .CX.reprot.txt file to do anntotaion step which is genome-wide cytosine report and has stand message. I know it is a report of every cytosine on both the top and bottom strands taking no accounct of whether they were actually covered by any reads in the experiment or not. But my output file is like this:

```
J02459.1        3       -       0       0       CHH     CCC
J02459.1        4       +       2       26      CG      CGG
J02459.1        5       -       0       0       CG      CGC
J02459.1        6       -       0       0       CHG     CCG
J02459.1        7       +       2       35      CG      CGA
J02459.1        8       -       0       0       CG      CGC
J02459.1        10      +       1       38      CHH     CCT
J02459.1        11      +       0       43      CHH     CTC
J02459.1        13      +       3       72      CG      CGC
J02459.1        14      -       0       1       CG      CGA
J02459.1        15      +       1       77      CG      CGG
J02459.1        16      -       0       1       CG      CGC
J02459.1        17      -       0       1       CHG     CCG
J02459.1        18      -       0       1       CHH     CCC
J02459.1        23      +       0       100     CG      CGC
J02459.1        24      -       0       1       CG      CGA
J02459.1        25      +       1       99      CHH     CTA
```
It is clearly not every  cytosine ,like 3,4,5,6,7,8,10 .So do you know the working mechanism of this command to pick up the cytosine sites? And also , in this file I notice that the base on every single position has not only one possibility. for example, the14th cytosine context show that 16th position is A, while in the report the 16th base is considered as C.
 My problems have confused my for some days,so if you have any suggestions on how to resolve my issue would be much appreciated. Thanks !

**Comment by FelixKrueger** [comment]
Hi Wentting,

I am currently travelling in Canada so I will keep it short. If you use `--CX` in your commands then you will get all cytosine contexts, not just CpG context (which would be the default). So all positions mentioned *are* in fact cytosines, somme of which will be CpGs. Not that some positions may have a somewhat different context (but there definitely are Cs in the genome). This context change may occur whenever the a deletion is positioned exactly downstream of the C. There should have been numerous issues on this topic, so feel free to browse some of the closed issues.

I think if you would just process the data with default parameters, including the `--cytosine` option. you would end up with the genome wide CpG report, which is exactly what you are looking for.

If there are still any problems feel free to ask, but I might only reply early in September as we have a very patchy data connection.
All the best, Felix

**Comment by Wentting** [comment]
Hi Felix, hope you have a beautiful trip first ! 

Thank you so much for you apply, I think you have solve my problem on the context problem, but I still have one question : Can I recognize .cov format file,bedGraph file and the whole genome cytosine report .CX_report.txt record the same cytosine message, Or in other words, the C sites in whole genome cytosine report are combined with all cytosines in bedGraph file and these are not covered in experiment. Am I right?

Recently I’ve searched a lot about the low mapping effiency for scBS-seq, and I believe “Dirty Harry”method in the Bismark user menuscript is useful. 

One thing is the example given on Bismark page is :Paired-end reads and unmapped R1 are mapped use –pbat mode, while unmapped R2 is mapped in default mode(directional). But scBS-seq data is recommended to map in –non-directional mode. According to my understandin, reads under this mode will be aligned 4times, while –pbat and –dirctional mode do only twice. So my stupid question is if your example is just suitable for PBAT data not for scBS-seq data ? And I really want to know you suggestion about the “dirty harry ” methods applied on scBS-seq data.

Thanks a ton !

**Comment by FelixKrueger** [comment]
The coverage (and bedGraph) files contain only the reads that were covered in your experiment, and if a cytosine had a deletion right downstream the same cytosine position may occur in more than one context. The genome-wide reports are purely reference genome based, so a given position will always have only a single context. 

Regarding the Dirty Harry method for single-cell BS-Seq: this would still apply, but you would have to perform all alignments in `--non_directional` mode. There was even a recent publication on this issue, which is referenced in our article over at QC Fail: https://sequencing.qcfail.com/articles/pbat-libraries-may-generate-chimaeric-read-pairs/.

Hope this helps, Best, Felix
