### ISSUE TITLE
Problems with some positions between coverage file and cytosine report

### ISSUE THREAD

**Issue by RubioB** [FelixKrueger/Bismark#277]
Hi Felix,

There is something I don't unsderstand well between the coverage file and the cytosine report obtained after methyl extraction step. I have realized the methylation extraction step and I have obtained three .txt document, one for each context with specific codage (xX, zZ,hH) according to the CG context. Then I used the bismark2bedGraph function only on the .txt file of the CHG context positions and I have obtained the bedGraph file and the coverage file. Finally I used the coverage2cytosine and I have obtained the cytosine report file. I understand that in the cytosine report all the C positions are listed. As I only want to work on the CHG context, I created a new file from the cytosine report including only the positions noted in CHG context and I also removed the positions 0 methylated/0 unmethylated. 

However, when I compare this new cytosine report file to my coverage file, I notice that some positions are missing in the new cytosine report file (so, there are more positions in the coverage file). Having compared the files, I noticed that the missing positions in my new cytosine report file were removed when I apllied the filter to select in the cytosine report file only postions in the CHG context. Indeed, the missing positions are noted as belonging to the CHH context. 
I was looked to the .txt file of the CHG context that I have used and the missing positions are well found with the correct context coding (in fact x for unmethylated C in CHG contex)...

So, I do not understand how it is possible that there was for some positions a change in the C context (form CHG to CHH) ? Have you ever seen this kind of results ?

Thank for your help, 

Bernadette

**Comment by FelixKrueger** [comment]
Dear Bernadette,

As this question keeps coming up I have decided to start a new [FAQ document](https://github.com/FelixKrueger/Bismark/blob/master/Docs/FAQ.md) which willl get populated over time with issues that appear to come up repeatedly. Can you please take a look and see if what I wrote there makes sense and if it answers your question?

All the best, Felix

**Comment by RubioB** [comment]
Hi Felix,

Thank you for taking the time to write this article on this question !
Yes that make sense for me ! And indeed I have deletions near the positions for which I had a change of CH context. Taking the example of a position, I find it in both the .txt file corresponding to the CHG context file and the CHH context file produced by bismark_methylation_extraction. Then, if I understood correctly, in the cytosine report it will postpone the CG context that it finds respect to the reference genome (in the example of my position it will note it in the context CHH).

The question now is how to take this observation into account ? Is it a good strategy to first compare the coverage files between the CHH and CHG context (and potentially the CG context ?) in order to get out the positions found in these different contexts and then do the cytosine report ?

Would it be possible to integrate in the script a function which would make it possible to put in the unknown context the positions near a deletion ?

Thanks,

Bernadette

________________________________
De : Felix Krueger <notifications@github.com>
Envoyé : mardi 3 septembre 2019 15:14
À : FelixKrueger/Bismark <Bismark@noreply.github.com>
Cc : RubioB <bernadetterubio@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [FelixKrueger/Bismark] Problems with some positions between coverage file and cytosine report (#277)


Dear Bernadette,

As this question keeps coming up I have decided to start a new FAQ document<https://github.com/FelixKrueger/Bismark/blob/master/Docs/FAQ.md> which willl get populated over time with issues that appear to come up repeatedly. Can you please take a look and see if what I wrote there makes sense and if it answers your question?

All the best, Felix

**Comment by RubioB** [comment]
Hi again,

I come back to you beacause looking at other positions concerned by the question, I realized that I also had the situation in which the position is found only, for example, in the CHG context .txt file (obtained after bismark_methylation_extractor) and in only the coverage file of the CHG context, however, in the cytosine report there is a change for the CHH context.
By having these two situations, I can not see how can I manage its positions ...

Thanks again,

Bernadette

________________________________
De : Felix Krueger <notifications@github.com>
Envoyé : mardi 3 septembre 2019 15:14
À : FelixKrueger/Bismark <Bismark@noreply.github.com>
Cc : RubioB <bernadetterubio@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [FelixKrueger/Bismark] Problems with some positions between coverage file and cytosine report (#277)


Dear Bernadette,

As this question keeps coming up I have decided to start a new FAQ document<https://github.com/FelixKrueger/Bismark/blob/master/Docs/FAQ.md> which willl get populated over time with issues that appear to come up repeatedly. Can you please take a look and see if what I wrote there makes sense and if it answers your question?

All the best, Felix

**Comment by FelixKrueger** [comment]
If you want to go down the route of dissecting all these positions manually, you could choose to generate 3 different coverage files for the different contexts, as they were found in the data. This can be accomplished by running 3 separate `bismark2bedGraph` commands, like so:

```
bismark2bedGraph --gzip -o CpG_context.cov.gz CpG*
bismark2bedGraph --gzip -o CHG_context.cov.gz CHG*
bismark2bedGraph --gzip -o CHH_context.cov.gz CHH*
```

You could then run coverage2cytosine on these files separately:

```
coverage2cytosine --gzip --CX -o genome-wide_report_CpG CpG_context.cov.gz
coverage2cytosine --gzip --CX -o genome-wide_report_CHG CHG_context.cov.gz
coverage2cytosine --gzip --CX -o genome-wide_report_CHH CHH_context.cov.gz
```

Finally, you could filter your coverage and genome-wide reports to your heart's content. Does that make sense?

We personally run Bismark almost exclusively in CpG-only mode, and we tend to stop at the coverage file step. Like this we gain a few, and we lose a few positions due to context shifting, but we can be reasonably sure that the calls in the coverage files are accurate.

As soon as you want to go back to rely on the genome reference sequence instead of what you really see in the data, you may see discrepancies between the real situation (coverage files) and the ideal situation (reference sequence) again. I don't think there is a single right decision to make here, which is probably also why there is not a single (and "correct") filtering option there already.

**Comment by FelixKrueger** [comment]
I am assuming this gave some inspiration on possible next steps. I will close this issue now (pre-Christmas issue closure...)
