### ISSUE TITLE
bismark2bedGraph  Error: Use of uninitialized value $pos in string ne at.. 

### ISSUE THREAD

**Issue by iromeo** [FelixKrueger/Bismark#279]
I'm using  bismark2bedGraph v0.22.1 and cannot convert CpG*.txt.gz to *.bismark.cov.gz file due to some errors from bismark2bedGraph.

```
bismark2bedGraph --buffer_size 20G --dir meth_CpG/D16 --output D16_hs37d5.bedGraph.gz meth/D16/CpG_context_D16_hs37d5.txt.gz
```

Fails with

```
Created output directory meth_CpG/D16/
Using these input files: meth/D16/CpG_context_D16_hs37d5.txt.gz

Summary of parameters for bismark2bedGraph conversion:
======================================================
bedGraph output:                D16_hs37d5.bedGraph.gz
output directory:               >/meth_CpG/D16/<
remove whitespaces:             no
CX context:                     no (CpG context only, default)
No-header selected:             no
Sorting method:                 Unix sort-based (smaller memory footprint, but slower)
Sort buffer size:               20G
Coverage threshold:             1
=============================================================================
Methylation information will now be written into a bedGraph and coverage file
=============================================================================

Using the following files as Input:
/meth/D16/CpG_context_D16_hs37d5.txt.gz

Writing bedGraph to file: D16_hs37d5.bedGraph.gz
Also writing out a coverage file including counts methylated and unmethylated residues to file: D16_hs37d5.bismark.cov.gz

Changed directory to /meth_CpG/D16/
Now writing methylation information for file >>CpG_context_D16_hs37d5.txt.gz<< to individual files for each chromosome
qFinished writing out individual chromosome files for CpG_context_D16_hs37d5.txt.gz

Collecting temporary chromosome file information... Processing the following input file(s):
CpG_context_D16_hs37d5.txt.gz.chr11.methXtractor.temp
CpG_context_D16_hs37d5.txt.gz.chr17.methXtractor.temp
CpG_context_D16_hs37d5.txt.gz.chr6.methXtractor.temp

...

CpG_context_D16_hs37d5.txt.gz.chrGL000197.1.methXtractor.temp
CpG_context_D16_hs37d5.txt.gz.chrGL000201.1.methXtractor.temp
CpG_context_D16_hs37d5.txt.gz.chrGL000236.1.methXtractor.temp
CpG_context_D16_hs37d5.txt.gz.chrGL000200.1.methXtractor.temp

Sorting input file CpG_context_D16_hs37d5.txt.gz.chr11.methXtractor.temp by positions (using -S of 20G)
Use of uninitialized value $pos in string ne at /wd/.snakemake/conda/7c7ea30e/bin/bismark2bedGraph line 460, <$ifh> line 14413435.
Missing (+/-) methylation call at /wd/.snakemake/conda/7c7ea30e/bin/bismark2bedGraph line 519, <$ifh> line 14413435.
        main::validate_methylation_call(undef, undef) called at /wd/.snakemake/conda/7c7ea30e/bin/bismark2bedGraph line 465
```

```
bismark2bedGraph --version


                      Bismark Methylation Extractor Module -
                                bismark2bedGraph

                      Bismark Extractor Version: v0.22.1
              Copyright 2010-19 Felix Krueger, Babraham Bioinformatics
                www.bioinformatics.babraham.ac.uk/projects/bismark/
                     https://github.com/FelixKrueger/Bismark
```
P.S: --ample_memory option just leads to 'bus error' for first chromosome

**Comment by FelixKrueger** [comment]
Hi Roman,

The error description itself seems to indicate that the file `CpG_context_D16_hs37d5.txt.gz.chr11.methXtractor.temp` is truncated in some. Since the process died, could you try and locate this file, and run `tail CpG_context_D16_hs37d5.txt.gz.chr11.methXtractor.temp` on it to see if it really is truncated? If it is, the question is why this is so. Is the original input file `meth/D16/CpG_context_D16_hs37d5.txt.gz` truncated as well? In that case you could run the methylation extractor once more.

Also, I would probably also suggest to change the command line a little to see if that helps. Something I find odd that `--dir meth_CpG/D16` works at all, because if this command tries to create a folder within another non-existing folder, the whole process should fail straight away.

I have just tried to execute a command that looks very close to what you had:
`../bismark2bedGraph --buffer 20G --dir meth_CpG/D16 --output D16_hs37d5.bedGraph.gz meth/D16/CpG_*`

where I created the folders `meth_CpG` and `meth_CpG/D16` before, and put the input files into this folder `meth/D16/`.

This process completed just fine:

```
ll meth_CpG/D16/
-rw-rw-r-- 1 fkrueger bioinf 2395211 Oct  3 15:33 D16_hs37d5.bedGraph.gz
-rw-rw-r-- 1 fkrueger bioinf 2060577 Oct  3 15:33 D16_hs37d5.bismark.cov.gz
```

Your on-screen text also said:
`Using these input files: meth/D16/CpG_context_D16_hs37d5.txt.gz`
and later, once it made the input file path absolute, it says:
`Using the following files as Input:
/meth/D16/CpG_context_D16_hs37d5.txt.gz`

Are you really running this in the `/` root folder? Or is this a consequence of your conda environment somehow?

In case you couldn't get it to work up to this point, I would suggest you move to the directory containing the input file, and try again without all of the path information, e.g.:

```
bismark2bedGraph --buffer 20G --o D16_hs37d5.bedGraph.gz CpG_context_D16_hs37d5.txt.gz
```

Let me know how you get on.

**Comment by iromeo** [comment]
> and locate this file, and run tail 
```
$ tail meth_CpG/D16/CpG_context_D16_hs37d5.txt.gz.chr11.methXtractor.temp
V300019122L1C006R0010168323/1   +       11      130590658       Z
V300019122L1C006R0010160367/1   +       11      84468887        Z
V300019122L1C006R0010168323/1   +       11      130590517       Z
V300019122L1C006R0010161736/1   +       11      105523615       Z
V300019122L1C006R0010170056/1   +       11      30655064        Z
V300019122L1C006R0010170056/1   +       11      30655113        Z
V300019122L1C006R0010171845/1   +       11      16733025        Z
V300019122L1C006R0010171845/1   +       11      16733049        Z
V300019122L1C006R0010173245/1   -       11      123872696       z
V300019122L1C006R0010170485/1   +       11      12628525        Z
```
The file seems to be OK, `zcat meth/D16/CpG_context_D16_hs37d5.txt.gz | awk '$3 == 11' | tail` returns the same result

> Are you really running this in the / root folder? Or is this a consequence of your conda environment somehow?

Please ignore this root folder, I've just removed long path prefix before "meth", ".snakemake" and other folders. Paths are ok.

> I find odd that --dir meth_CpG/D16 works at all, because if this command tries to create a folder within another non-existing folder

it shouldn't be an issue because snakemake creates intermediate folders and at the moment all folders exists while I'm investigating the issue

> Is the original input file meth/D16/CpG_context_D16_hs37d5.txt.gz truncated as well?
Also looks ok

```
$ zcat meth/D16/CpG_context_D16_hs37d5.txt.gz | tail
V300019122L1C006R0010172849/1   +       19      45672711        Z
V300019122L1C006R0010172849/1   +       19      45672811        Z
V300019122L1C006R0010173149/1   +       1       215003710       Z
V300019122L1C006R0010173196/1   -       20      57436949        z
V300019122L1C006R0010173196/1   +       20      57436973        Z
V300019122L1C006R0010173196/1   +       20      57436980        Z
V300019122L1C006R0010173196/1   +       20      57437007        Z
V300019122L1C006R0010173354/1   -       4       39250331        z
V300019122L1C006R0010173429/1   +       4       36161249        Z
V300019122L1C006R0010173639/1   +       17      57956364        Z
```

**Comment by iromeo** [comment]
Failed with the same error
```
CpG_context_D16_hs37d5.txt.gz.chrGL000197.1.methXtractor.temp
CpG_context_D16_hs37d5.txt.gz.chrGL000201.1.methXtractor.temp
CpG_context_D16_hs37d5.txt.gz.chrGL000236.1.methXtractor.temp
CpG_context_D16_hs37d5.txt.gz.chrGL000200.1.methXtractor.temp

Sorting input file CpG_context_D16_hs37d5.txt.gz.chr11.methXtractor.temp by positions (using -S of 20G)
Use of uninitialized value $pos in string ne at /wd/.snakemake/conda/7c7ea30e/bin/bismark2bedGraph line 460, <$ifh> line 12347181.
Missing (+/-) methylation call at /wd/.snakemake/conda/7c7ea30e/bin/bismark2bedGraph line 519, <$ifh> line 12347181.
        main::validate_methylation_call(undef, undef) called at /wd/.snakemake/conda/7c7ea30e/bin/bismark2bedGraph line 465
```

Tail for `CpG_context_D16_hs37d5.txt.gz.chr11.methXtractor.temp` shows same result. All rows have 5 columns:
```
$ cat CpG_context_D16_hs37d5.txt.gz.chr11.methXtractor.temp |  awk '{ print NF }' | uniq
5
```

**Comment by iromeo** [comment]
Initially, I've noticed that `*.bismark.cov` files generated by `bismark_methylation_extractor` are truncated by the first chromosome for samples with larger library size (samples with lower library size were ok). The "D16" sample was processed correctly and I have `*.bismark.cov.gz` file for it generated with `bismark_methylation_extractor` I've got issues with some other samples.

For the consistency and in order not to re-run  `bismark_methylation_extractor` I decided to recalc all `*.bismark.cov.gz` files using `bismark2bedGraph` script.

So it isn't clear why I cannot recalculate `D16` again just using `bismark2bedGraph` script instead of  `bismark_methylation_extractor --bedGraph`

**Comment by iromeo** [comment]
I've enabled current `$line` logging and re-launched `bismark2bedGraph --buffer 10G --o D16_hs37d5.bedGraph.gz CpG_context_D16_hs37d5.txt.gz` several times:

1st attempt:
```
full line:
V300022389L3C006R0061263152/1   +       11      83701517        Z
Bus error (core dumped)
```

2nd attempt:
```
full line:
V300019122L1C005R0610939343/1   +       11      75615493        Z
Bus error (core dumped)
```

3rd attempt: (a bit modified logging):
```
V300019122L1C004R0711015275/1   +       11      75837983        Z at /wd/.snakemake/conda/7c7ea30e/bin/bismark2bedGraph line 455, <$ifh> line 15233702.
V300019122L1C005R0311094836/1   +       11      7 at /wd/.snakemake/conda/7c7ea30e/bin/bismark2bedGraph line 455, <$ifh> line 15233703.
Missing alphabetical methylation call at /wd/.snakemake/conda/7c7ea30e/bin/bismark2bedGraph line 521, <$ifh> line 15233703.
        main::validate_methylation_call("+", undef) called at /wd/.snakemake/conda/7c7ea30e/bin/bismark2bedGraph line 465
```

**Comment by iromeo** [comment]
'CpG_context_D16_hs37d5.txt.gz' file contains 607.819.414 lines

**Comment by FelixKrueger** [comment]
I have to admit that I don't think I have ever seen these errors before ('missing alphabetical methylation call' is certainly not something anywhere in the bismark code...). Somehow it looks like the temp files are getting truncated somehow, is there a chance your process is running out of temporary disk space? I could offer to set up an FTP site for you to upload your `CpG_context_D16_hs37d5.txt.gz` file, so I could test if it runs through alright over here... If you are interested, please send me and [email](mailto:felix.krueger@babraham.ac.uk).

**Comment by iromeo** [comment]
I agree that it looks like sorted stream is getting truncated due to some quota limitations. Thank you for your advice, i’ll check quotas again and try to launch it in some other environment.

**Comment by iromeo** [comment]
@FelixKrueger I've managed to launch it without errors. The issue is related to RAM or virtual memory quotas on our computational cluster. I've tried to run `gunzip .. | sort ..` manually and it was killed by OS task manager at some moment likely due to large memory footprint. It seems the same issue occurs when running with `--ample_memory` the script fails to allocate memory array for some chromosomes and fails with 'bus error' error. I've increased RAM limits from 20gb to 40gb and now it works ok.

Thank you for your help with debugging this issue. Please close this issue.

**Comment by FelixKrueger** [comment]
Excellent, I'm glad it is now all running smoothly!
