### ISSUE TITLE
--cutoff usage

### ISSUE THREAD

**Issue by Shicheng-Guo** [FelixKrueger/Bismark#28]
Hi Felix,

Can you make it more explicit:

--cutoff [threshold]  The minimum number of times a methylation state has to be seen for that nucleotide before its methylation percentage is reported. Default: 1.

It means the methylation read counts should be >=1 or total reads at the base should be >=1? 

Thanks. 

I think it should be 

--cutoff [threshold]  The minimum number of times a methylation state (M or U) has to be seen for that nucleotide before its methylation percentage is reported. Default: 1.

Isn't it?

Thanks.

**Comment by FelixKrueger** [comment]
For piece of mind I have altered the description slightly to: 

`--cutoff [threshold]     The minimum number of times any methylation state (methylated or unmethylated) has to be seen
                         for a nucleotide before its methylation percentage is reported. Default: 1.`
