### ISSUE TITLE
bismark2summary cannot find splitting_report

### ISSUE THREAD

**Issue by bounlu** [FelixKrueger/Bismark#280]
Splitting report is generated by `bismark_methylation_extractor` in the format (for PE):

> $base."_splitting_report.txt"

But `bismark2summary` function looks for the file:

> $base."_pe.deduplicated_splitting_report.txt"

Hence it can't find and it gives the error:

> No methylation extractor report present, skipping...

When I manually change the filename as expected, it works fine.

**Comment by FelixKrueger** [comment]
Hi @bounlu 

I think I have found (and fixed) this issue a few months ago (see https://github.com/FelixKrueger/Bismark/blob/master/CHANGELOG.md and https://github.com/FelixKrueger/Bismark/commit/aa6d43862e425cbb01786c0e85143c59481f9632). Could you try to clone the latest dev version and see if that works?

Cheers, Felix

**Comment by bounlu** [comment]
Thanks for the update. I'm using bismark from conda installation, where the latest version does not have this fix.

**Comment by FelixKrueger** [comment]
Ah right, I see. In that case I need to do a new Bismark release so that the changes get pushed to Conda. Will try and do it this afternoon. 

Cheers, Felix

**Comment by FelixKrueger** [comment]
I have just pushed release `v0.22.2`, I hope it'll find its way to Conda soon.

**Comment by bounlu** [comment]
I installed the `v0.22.2` from the conda, but the error is still there. `bismark_methylation_extractor` still generates the file with this naming:

> $base."_splitting_report.txt"

**Comment by FelixKrueger** [comment]
Would you be able to zip up all the reports of one sample to this thread so I can try to reproduce this myself? Thanks

**Comment by bounlu** [comment]
attached, thanks!

[bismark_reports.zip](https://github.com/FelixKrueger/Bismark/files/3766775/bismark_reports.zip)

**Comment by FelixKrueger** [comment]
Thanks. It looks like the original file generated by Bismark should have been called:

```
CD34_008_bisulfite_1_bismark_bt2_pe.bam
```
Thus bismark2summary will look for the reports:

```
CD34_008_bisulfite_1_bismark_bt2_PE_report.txt
CD34_008_bisulfite_1_bismark_bt2_pe.deduplication_report.txt
CD34_008_bisulfite_1_bismark_bt2_pe.deduplicated_splitting_report.txt
```

You seem to have renamed the de-duplicated BAM file to `CD34_008_bisulfite.bam` however, which explains why it is no longer being picked up by the default recognition. 

`bismark2summary` is designed to pick up the names following strict rules as it is typically run as the final step of a pipeline where no one interfered with the expected naming convention. You can certainly appreciate that if you run `bismark2summary` on 8 lanes with 384 samples, you do want it to second-guess which report file _might_ belong to which starting sample amongst thousands of files...

So as a solution to this, couldn't you run the entire pipeline from start to finish, and rename the files afterwards, with e.g. `rename replace_what_you_find_too_long shorter *`

**Comment by bounlu** [comment]
I see, now it's clear. Yes I do process the bam files and change the naming from the default one before calling the `bismark2summary`.

That said, to make everyone happy, may I suggest to implement a parameter to choose a specific file for the reports, just like available in `bismark2report` function?

available:
`bismark2report --splitting_report whatever_splitting_report.txt`

suggestion:
`bismark2summary --splitting_report whatever_splitting_report.txt`

**Comment by FelixKrueger** [comment]
Specifying a single file, or set of files, does indeed work for `bismark2report`, as long as you limit the report generation to a single sample. 

Allowing the same for a summary plot kind of defies its principle of summarising many (up to hundreds or even thousands) samples though. In fact, the summary plot for a single file really only is a set of dots in the middle of the page, which doesn't look very pretty to me. For I single sample I would suggest you simply look at the report generated by `bismark2report`. Does that make sense?

**Comment by FelixKrueger** [comment]
I have added some statements on the Docs page to try and make this a little clearer. Cheers, Felix
