### ISSUE TITLE
score_min not correctly computed in calc_map, leading to wrong MAPQ output

### ISSUE THREAD

**Issue by stephenkraemer** [FelixKrueger/Bismark#281]
Hi Felix,
thanks a lot for all your work and for sharing so much of your experience through qcfail.com etc.

I noticed that the recomputed mapping qualities don't seem to be correct when using local alignments. I saw #260 and also that you included the updated code for computing the MAPQ in the latest release from today.

However, I think that the calculation of scMin also needs to be updated to account for the logarithmic formula (min_score=G,...,...)

This is at the start of sub calc_mapq, in line 3797:

```perl
	my $scMin = $score_min_intercept + $score_min_slope * $read1Len;
	### read2Len is only defined for paired-end reads, so for single-end mode we can just a score min value for read 1
	if (defined $read2Len){
		$scMin   += $score_min_intercept + $score_min_slope * $read2Len;
	}
```
I tested your new mapq calculation code, and while it doesn't produce 0 and 2 as before, it mainly produces MAPQ 22 for valid alignments, which is in line with a wrong scMin calculation.

Does that make sense? Should I submit a pull request with my fix?

Thank you,
Stephen

**Comment by FelixKrueger** [comment]
Hi Stephen,

Thanks for your comments. If you are already working on this and know how to fix the scMin calculation, I would indeed very much welcome a PR with the fix.

Best, Felix

**Comment by stephenkraemer** [comment]
Great! I'll run a test alignment to be sure and will get back to you later today!

**Comment by stephenkraemer** [comment]
After fixing scMin calculation with #282, I get realistic MAPQ values in end-to-end and local mode with default parameters. So far only tested on a small 75bp scNMT dataset. I'll run it over longer reads and larger datasets tomorrow and will report back again.

**Comment by FelixKrueger** [comment]
Many thanks already. I'll wait for your assessment tomorrow, and then merge the changes if it looks alright.

**Comment by stephenkraemer** [comment]
Sorry for the delay, I didn't get to it on friday, but now I followed up on this: Independent of the read length, the results look fine. I am relatively confident that this is a reliable improvement. For 125 bp reads, many reads reach high qualities. For small reads (75 bp), one may have to i) allow lower mapping qualities into the methylation calls ii) adjust the penalty scores to get better differentiation within low-ish mapping qualities (say MAPQ between 15 and 30). I think for my use case, higher gap opening penalties make sense, for example, so that soft clipping is less penalized relative to indels (we expect chimeric reads from a single cell protocol, but align standard mouse cells which shouldn't have too many mutations). But you already indicate in the manual that the user is responsible for adjusting the defaults, especially in local mode, so that's fine as it is in my opinion.

Follow up question from my side: in the past, we ran alignments with bismark and then used methyldackel downstream. Now that we have scNMT data, we are looking into the methylation extraction functionality of bismark. Can I specify mapping quality, phred score and SAM flag filters when using bismark_methylation_extractor? I didn't find options for that yet and it seems to me that I also cannot pipe a BAM file via stdin and filter it with samtools. Sorry for my potential tunnel vision!

**Comment by FelixKrueger** [comment]
Hi Stephen,

Many thanks for the feedback, I'll try to merge your changes later tonight. 

Regarding your follow up, don't worry about tunnel vision, there really isn't any functionality to stream or filter BAM files for the extractor. You could of course take the Bismark BAM file, run it through the de-duplicator, filter away using Samtools, and finally use that filtered file to feed into the methylation extractor (you only need to ensure that paired-end files are name sorted). We personally tend not to filter for base call scores for methylation calls as we run all reads through fairly stringent quality trimming already, which should make this step unnecessary. Let me know if there are any further issues you need answers to. Best, Felix

**Comment by stephenkraemer** [comment]
Hi Felix,
I wanted to collect some (few, I promise) follow up questions on filtering strategies, but I haven't yet found the time to have a closer look at my data and derive my questions from that. So before this becomes even more belated: thanks for your help and apologies for being so late to reply! Perhaps I'll have one or two more usage questions, in that case I'll get back to you later once I have learned more about that :)

**Comment by FelixKrueger** [comment]
Sounds good, looking forward to further contributions!  :)
