### ISSUE TITLE
Bismark installation 

### ISSUE THREAD

**Issue by janeen-b** [FelixKrueger/Bismark#283]
Recently I installed Bismark on my PC by downloading the file and extracting in a folder which I named Bismark. Upon runing the test the results could not executed bismark_genome_preparation: command not found or bismark: command not found

Codes run: 
bismark_genome_preparation --/usr/bin/bowtie2/ --verbose /data/genomes/homo_sapiens/GRCh37/

 bismark --help

**Comment by FelixKrueger** [comment]
I assume you want to run Bismark on a Linux PC or Mac? Running Bismark follows the general *nix rules that you can use programs simply by their name if they are in your `PATH` environment (check e.g. here https://unix.stackexchange.com/questions/26047/how-to-correctly-add-a-path-to-path).

Alternatively, you can specify the entire path to run it. If you are in the folder containing the Bismark package, you can use `./bismark` (where `.` means 'this folder'). Or you use an absolute path like `/complete/path/to/Bismark/bismark`.

**Comment by janeen-b** [comment]
I did the file GRch37.fa its within this path

**Comment by janeen-b** [comment]
Thank you so much by using this code command is runing: 
./bismark_genome_preparation ./data/genomes/homo_sapiens/GRCh37/

**Comment by FelixKrueger** [comment]
Hmm, it seems that the program thinks otherwise :)

```
Could't move to directory /data/genomes/homo_sapiens/GRCh37/. Make sure the directory exists!
```

Can you try to run
`ls -l /data/genomes/homo_sapiens/GRCh37/`

and link the command.

**Comment by FelixKrueger** [comment]
Ah, it seems you placed the folder `/data/genomes/homo_sapiens/GRCh37/` inside your working directory. That would explain it. Good luck!

**Comment by janeen-b** [comment]
Yes, is there an easy way to go this because this will be troublesome everytimes. Also I am soooooo thankful for your assistances.

**Comment by FelixKrueger** [comment]
You might want to google a little to find a tutorial for 'command line unix' or the like. If you are planning to stay in this line of work it will certainly be a good skill to have!
