### ISSUE TITLE
book-ended sites in methylation extraction

### ISSUE THREAD

**Issue by xiaoyunguo** [FelixKrueger/Bismark#288]
Dear Felix,
First, thank you for your time and effort. I have read a lot of your articles about methylation calling and they are very helpful.
I have been using Bismark for RRBS data analysis. I noticed that in the default mode, the methylation extractor output a lot of book-ended sites. For example (from the .cov file):

chr1	3015767	3015767	100	1	0
chr1	3020815	3020815	66.6666666666667	2	1
**chr1	3020842	3020842	100	1	0
chr1	3020843	3020843	66.6666666666667	2	1**
chr1	3020877	3020877	94.1176470588235	48	3
...

I use bedtools merge to merge these book-ended sites and counted the number of sites left, the difference was quite large:

bulk/rrbs2/genome_wide$ wc -l test.merged.cov
**1714691** test.merged.cov

bulk/rrbs2/genome_wide$ wc -l test.sorted.cov
**2622676** test.sorted.cov

The bam file was generated using:
 bismark_v0.22.1/bismark --multicore $thread -un --genome $genome $fastq_file

The extraction was done using: 
bismark_v0.22.1/bismark_methylation_extractor --bedGraph -multicore $thread --genome $genome $bam_file

I thought the default output of the extractor is CpG context only (according to the documentation). For CpG context, there shouldn't be continuous sites being reported, right? Is there something I did wrong? I don't mind getting non CpG context sites, but I want to make sure that I have the correct assumption and do it the right way. And I am concerned about my interpretation of the methylation extraction result. 

Thank you very much. 

Xiaoyun

**Comment by FelixKrueger** [comment]
Hi Xiaoyun,

It is correct that the default mode is CpG context only, but the default output is single base pair resolution. In other words, consecutive top and bottom strand CpGs that form a CpG di-nucleotide like this:
```
CG
GC
```

are reported individually in coverage files (is this what you mean with book-ended sites? Sorry, but I haven't come across this term before). 

If you wanted to merge top and bottom strand CpG information you could choose to run `coverage2cytosine` with the option `--merge_CpG` specified. This is from the help text:

```
--merge_CpG              Using this option will post-process the genome-wide report to write out an additional coverage
                         file (see above for the coverage file format) which has the top and bottom strand methylation
                         evidence pooled into a single CpG dinucleotide entity. This may be the desirable input format
                         for some downstream processing tools such as the R-package bsseq (by K.D. Hansen). An example would be:

                           genome-wide CpG report (old)
                           gi|9626372|ref|NC_001422.1|     157     +       313     156     CG
                           gi|9626372|ref|NC_001422.1|     158     -       335     156     CG
                           merged CpG evidence coverage file (new)
                           gi|9626372|ref|NC_001422.1|     157     158     67.500000       648     312
```

You could even apply filtering using the option `--discorcance`. Just as a word of warning: while the coverage files are data-based, the genome-wide methylation reports are reference genome sequence based. I have tried to write up details about this important distinction here: https://github.com/FelixKrueger/Bismark/blob/master/Docs/FAQ.md#issue-3-context-changediscrepancy-between-bismark-coverage-and-genome-wide-cytosine-reports

Does this answer the questions you were having?

**Comment by xiaoyunguo** [comment]
Dear Felix,

Thank you so much for your prompt reply. Your explanation totally makes
sense to me! By book-ended sites, I mean two adjacent sites. Just to
clarify.

Best,

Xiaoyun
