### ISSUE TITLE
M-bias Figure's line could be change

### ISSUE THREAD

**Issue by Shicheng-Guo** [FelixKrueger/Bismark#29]
Hi Felix,

In the current M-bias Figure, the color and the width of the line were applied to label different categories. It is really hard to recognize. Do you think we can change it a little bit better? 

Thanks.

**Comment by FelixKrueger** [comment]
Are you referring to the M-bias.png figures generated automatically by the methylation extractor? These are really just meant to allow you a quick glance at the results. Running `bismark2report` produces a much nicer and interactive M-bias plot. If you also don't like that you are welcome to use the M-bias.txt file to generate your favourite plot in an application of your choice.
