### ISSUE TITLE
AS:i field

### ISSUE THREAD

**Issue by BenAuxier** [FelixKrueger/Bismark#290]
Hi Felix,

Is it possible to access the alignment score field (AS:i) that is used from the BowTie2 output? I took a look at the code, but I wasn't clear on how/if AS was tracked together with the reads through the program.

I have BS-Seq data from a hybrid with high sequence divergence (10%), and I want to compare how reads map to the two component genomes. I could map to the CT/GA converted genomes, but I figured since bismark is already doing the counting maybe that is easiest?

Thanks

**Comment by FelixKrueger** [comment]
Hi Ben,

Yes I believe that should be a fairly easy fix. If you look for subroutines `sub paired_end_SAM_output`, you should find the AS scores in the parameter
 `$methylation_call_params{$id}->{alignment_score_1}` and 
`$methylation_call_params{$id}->{alignment_score_2}`.

If you just go down in thet subroutine to the last print OUT statement, just added the AS: score at the very end, e.g.: "AS:i:$methylation_call_params{$id}->{alignment_score_1}", and the same for R2. 

For single-end data the names might be slightly different, but the idea is the same. Let me know if I can help at all.

**Comment by BenAuxier** [comment]
Ah, this is amazing. 

Thanks so much!
