### ISSUE TITLE
bismark_methylation_extractor report unmethylated reads

### ISSUE THREAD

**Issue by Czh3** [FelixKrueger/Bismark#293]
Hi,
I used bismark_methylation_extractor to get methylated/unmethlated reads at all C sites. bismark_methylation_extractor reports <chromosome> <position> <strand> <count methylated> <count unmethylated> <C-context> <trinucleotide context>. 
I wonder whether the <count unmethylated> reads only contain the C->T reads or contain other conversions (for example: C to A) .

Thanks for developing the tools.
Chao

**Comment by FelixKrueger** [comment]
Hi Chao,

The primary output of the methylation extractor (`CpG_*`, `CHH_*` and `CHG_*` files) do indeed only consider positions where there was a Cytosine in the genome, and the base found in the reads are either `C` or `T`. C positions other than `C` or `T` will receive a `.` in the methylation call string, and are hence ignored.

Bismark doesn't generally deal with any other SNV calls, but you could potentially run other programs on its BAM files.

**Comment by Czh3** [comment]
Thank you for the quick response.  Unmethylated reads counts only include C>T(G>A) conversions, that's what I want.
Thanks!
