### ISSUE TITLE
bismark_methylation_extractor dies

### ISSUE THREAD

**Issue by StefanoLonardi** [FelixKrueger/Bismark#294]
I am encountering a problem with bismark_methylation_extractor, which dies during the
conversion to bed (bismark2bedGraph). See log below. Maybe bismark2bedGraph does not like the fact that our contig names have a "(" in it?

This is the command I executed
bismark_methylation_extractor --gzip --bedGraph --parallel 20 FCH2LLYCCX2_L1_COWtzgMAAABAAA-40_1_bismark_bt2_pe.bam

FYI.. I checked bismark2bedGraph version it is $bismark2bedGraph_version = 'v0.22.2'

Please advise - I could change the contig names and re-run Bismark again, but it takes almost a week on the samples we have.

```
...
CpG_OB_FCH2LLYCCX2_L1_COWtzgMAAABAAA-40_1_bismark_bt2_pe.txt.gz.chrcontig_356.methXtractor.temp
CpG_OB_FCH2LLYCCX2_L1_COWtzgMAAABAAA-40_1_bismark_bt2_pe.txt.gz.chrcontig_308.methXtractor.temp
CpG_OB_FCH2LLYCCX2_L1_COWtzgMAAABAAA-40_1_bismark_bt2_pe.txt.gz.chrcontig_230.methXtractor.temp
CpG_OB_FCH2LLYCCX2_L1_COWtzgMAAABAAA-40_1_bismark_bt2_pe.txt.gz.chrcontig_410.methXtractor.temp
CpG_OB_FCH2LLYCCX2_L1_COWtzgMAAABAAA-40_1_bismark_bt2_pe.txt.gz.chrcontig_408.methXtractor.temp
CpG_OB_FCH2LLYCCX2_L1_COWtzgMAAABAAA-40_1_bismark_bt2_pe.txt.gz.chrcontig_419.methXtractor.temp

Sorting input file CpG_OT_FCH2LLYCCX2_L1_COWtzgMAAABAAA-40_1_bismark_bt2_pe.txt.gz.chrcontig_325.methXtractor.temp by positions (using -S of 2G)
Successfully deleted the temporary input file CpG_OT_FCH2LLYCCX2_L1_COWtzgMAAABAAA-40_1_bismark_bt2_pe.txt.gz.chrcontig_325.methXtractor.temp

Sorting input file CpG_OT_FCH2LLYCCX2_L1_COWtzgMAAABAAA-40_1_bismark_bt2_pe.txt.gz.chrVu06(old6).methXtractor.temp by positions (using -S of 2G)
sh: 1: Syntax error: "(" unexpected
Died at /24-2/home/ssere004/anaconda2/bin/bismark2bedGraph line 486.
Finished BedGraph conversion ...

```

**Comment by StefanoLonardi** [comment]
I just noticed that the temp files that contain "(" have a different filenames (they have a quote before and after). See below.

```
-rw-rw-r--  1 stelo closelonardilab     14726 Dec 18 10:47  CpG_OT_FCH2LLYCCX2_L1_COWtzgMAAABAAA-40_1_bismark_bt2_pe.txt.gz.chrcontig_95.methXtractor.temp
-rw-rw-r--  1 stelo closelonardilab     25295 Dec 18 10:47  CpG_OT_FCH2LLYCCX2_L1_COWtzgMAAABAAA-40_1_bismark_bt2_pe.txt.gz.chrcontig_96.methXtractor.temp
-rw-rw-r--  1 stelo closelonardilab     19001 Dec 18 10:47  CpG_OT_FCH2LLYCCX2_L1_COWtzgMAAABAAA-40_1_bismark_bt2_pe.txt.gz.chrcontig_97.methXtractor.temp
-rw-rw-r--  1 stelo closelonardilab      2700 Dec 18 10:47  CpG_OT_FCH2LLYCCX2_L1_COWtzgMAAABAAA-40_1_bismark_bt2_pe.txt.gz.chrcontig_98.methXtractor.temp
-rw-rw-r--  1 stelo closelonardilab    114183 Dec 18 10:47  CpG_OT_FCH2LLYCCX2_L1_COWtzgMAAABAAA-40_1_bismark_bt2_pe.txt.gz.chrcontig_99.methXtractor.temp
-rw-rw-r--  1 stelo closelonardilab 201123564 Dec 18 10:47 'CpG_OT_FCH2LLYCCX2_L1_COWtzgMAAABAAA-40_1_bismark_bt2_pe.txt.gz.chrVu01(old4).methXtractor.temp'
-rw-rw-r--  1 stelo closelonardilab 172374522 Dec 18 10:47 'CpG_OT_FCH2LLYCCX2_L1_COWtzgMAAABAAA-40_1_bismark_bt2_pe.txt.gz.chrVu02(old7).methXtractor.temp'
-rw-rw-r--  1 stelo closelonardilab 320964619 Dec 18 10:47 'CpG_OT_FCH2LLYCCX2_L1_COWtzgMAAABAAA-40_1_bismark_bt2_pe.txt.gz.chrVu03(old3).methXtractor.temp'
-rw-rw-r--  1 stelo closelonardilab 169789854 Dec 18 10:47 'CpG_OT_FCH2LLYCCX2_L1_COWtzgMAAABAAA-40_1_bismark_bt2_pe.txt.gz.chrVu04(old11).methXtractor.temp'
-rw-rw-r--  1 stelo closelonardilab 244170969 Dec 18 10:47 'CpG_OT_FCH2LLYCCX2_L1_COWtzgMAAABAAA-40_1_bismark_bt2_pe.txt.gz.chrVu05(old1).methXtractor.temp'
-rw-rw-r--  1 stelo closelonardilab 168350809 Dec 18 10:47 'CpG_OT_FCH2LLYCCX2_L1_COWtzgMAAABAAA-40_1_bismark_bt2_pe.txt.gz.chrVu06(old6).methXtractor.temp'
-rw-rw-r--  1 stelo closelonardilab 207767258 Dec 18 10:47 'CpG_OT_FCH2LLYCCX2_L1_COWtzgMAAABAAA-40_1_bismark_bt2_pe.txt.gz.chrVu07(old2).methXtractor.temp'
-rw-rw-r--  1 stelo closelonardilab 185232216 Dec 18 10:47 'CpG_OT_FCH2LLYCCX2_L1_COWtzgMAAABAAA-40_1_bismark_bt2_pe.txt.gz.chrVu08(old5).methXtractor.temp'
-rw-rw-r--  1 stelo closelonardilab 217947008 Dec 18 10:47 'CpG_OT_FCH2LLYCCX2_L1_COWtzgMAAABAAA-40_1_bismark_bt2_pe.txt.gz.chrVu09(old8).methXtractor.temp'
-rw-rw-r--  1 stelo closelonardilab 136392776 Dec 18 10:47 'CpG_OT_FCH2LLYCCX2_L1_COWtzgMAAABAAA-40_1_bismark_bt2_pe.txt.gz.chrVu10(old10).methXtractor.temp'
-rw-rw-r--  1 stelo closelonardilab 182221444 Dec 18 10:47 'CpG_OT_FCH2LLYCCX2_L1_COWtzgMAAABAAA-40_1_bismark_bt2_pe.txt.gz.chrVu11(old9).methXtractor.temp'
```

**Comment by StefanoLonardi** [comment]
Here is the content of the file in which the script dies

```
(base) stelo@H4:~/methylation$ more 'CpG_OT_FCH2LLYCCX2_L1_COWtzgMAAABAAA-40_1_bismark_bt2_pe.txt.gz.chrVu06(old6).methXtractor.temp'
E00454:562:H2LLYCCX2:1:1102:30076:31441_1:N:0   -       Vu06(old6)      29187009        z
E00454:562:H2LLYCCX2:1:1102:16904:31441_1:N:0   +       Vu06(old6)      6683711 Z
E00454:562:H2LLYCCX2:1:1101:19613:2030_1:N:0    -       Vu06(old6)      21844160        z
E00454:562:H2LLYCCX2:1:1101:19613:2030_1:N:0    -       Vu06(old6)      21844197        z
E00454:562:H2LLYCCX2:1:1101:19613:2030_1:N:0    -       Vu06(old6)      21844230        z
E00454:562:H2LLYCCX2:1:1101:19613:2030_1:N:0    -       Vu06(old6)      21844251        z
E00454:562:H2LLYCCX2:1:1101:9394:1977_1:N:0     +       Vu06(old6)      921945  Z
E00454:562:H2LLYCCX2:1:1101:9394:1977_1:N:0     +       Vu06(old6)      921971  Z
E00454:562:H2LLYCCX2:1:1101:9394:1977_1:N:0     +       Vu06(old6)      921982  Z
E00454:562:H2LLYCCX2:1:1101:9394:1977_1:N:0     +       Vu06(old6)      921990  Z
...
```

**Comment by FelixKrueger** [comment]
Hi Stefano,

I am not sure I ever ran into this problem, but I can immediately see that brackets create a problem with both file names creation and potentially also the sorting afterwards. It might be possible to change the behaviour within `bismark2bedGraph`, but I would probably indeed recommend you simply change the chromosome/contig names within your results. This should not require re-mapping at all, a simply find and replace should be enough. I have just written a little script for you that should take care of this step, just unzip the attached script, and then run:

```
./rename_braces.pl C*
```
This should generate a copy of each file ending in `replaced.txt.gz`, where all `(` opening braces are replaced by `_` underscores, and closing braces `)` are removed. In your case it should become:
```
Old:
E00454:562:H2LLYCCX2:1:1102:30076:31441_1:N:0   -       Vu06(old6)      29187009
New:
E00454:562:H2LLYCCX2:1:1102:30076:31441_1:N:0   -       Vu06_old6      29187009
```

The resulting files should then in theory work well with the coverage file conversion:
```
bismark2bedGraph -o working.bedGraph --gzip CpG*replaced.txt.gz
```

**Important:**
- You should also apply the same change of name for your genome FastA file(s), and potentially run `bimark_genome_preparation` again on the new FastA files (for future alignments). Technically, you won't need to change the name of the FastA file(s) for the coverage file generation, but if you were to proceed with `coverage2cytosine` etc. then this would be required

- If you want to additional things with your BAM file, you would have to apply a similar procedure to the BAM file.

I realise that this is a bit of a faff, but it should only take a few minutes as opposed to renaming and then re-launching the entire pipeline. Let me know if you have any questions.

[rename_braces.zip](https://github.com/FelixKrueger/Bismark/files/3983125/rename_braces.zip)

**Comment by StefanoLonardi** [comment]
Felix, thank you so much for providing the script. I was hoping you could fix bismark2bedGraph to handle the "(". I tried your script but it did not work all the files. We will be changing the contig names and re-run the entire pipeline again. Thanks again.

**Comment by FelixKrueger** [comment]
Oh, I'm sorry it didn't work with all your files, it seemed to do the job alright on the test files I used. I suppose working on bismark2bedGraph might be an option, but given that I am on holiday already and it often isn't a great idea to use special characters that need to be escaped when typing it on a *nix platform, it might be best to rename and start again (consider speeding up the process using `--parallel N`?)

Merry Christmas!

**Comment by StefanoLonardi** [comment]
Felix, that's ok. Thanks again for providing the script. Happy holidays, Stefano
