### ISSUE TITLE
Unable to build the index files for Chicken genome

### ISSUE THREAD

**Issue by nashchem** [FelixKrueger/Bismark#296]
Hi Felix,

I am trying to run the bismark pipeline.

I am working with Chicken genome fasta file (ftp://ftp.ensembl.org/pub/release-98/fasta/gallus_gallus/dna_index/) and having issues with bismark genome preparation. 

The command I used
`bismark_genome_preparation --parallel 2 --genomic_composition --verbose ${genome_dir} `

bismark version: 0.19.0
bowtie2 version: 2.3.5.1

It's been running for 20 hours and completed steps I and II and step III is still running. It generated only 4 bt2 index files (*.4.bt2, *.3.bt2, *.1.bt2, *.2.bt2) for both GA and CT converted genomes.

The error log file shows this output (last 10 lines):

_Step II - Genome bisulfite conversions - completed
Bismark Genome Preparation - Step III: Launching the Bowtie 2 indexer
Preparing indexing of CT converted genome in ${genome_dir}/Bisulfite_Genome/CT_conversion/
Building a SMALL index
Preparing indexing of GA converted genome in ${genome_dir}/Bisulfite_Genome/GA_conversion/
Building a SMALL index_

The output log file shows (last 10 lines):

_bmax according to bmaxDivN setting: 131947619
Using parameters --bmax 98960715 --dcv 1024
  Doing ahead-of-time memory usage test
  Passed!  Constructing with these parameters: --bmax 98960715 --dcv 1024
Constructing suffix-array element generator
Building DifferenceCoverSample
  Building sPrime
  Building sPrimeOrder
  V-Sorting samples_

Can someone help me whats going wrong? 
Thank you,
Best,
Naresh  D J

**Comment by nashchem** [comment]
> Hi Felix,
> 
> I am trying to run the bismark pipeline.
> 
> I am working with Chicken genome fasta file (ftp://ftp.ensembl.org/pub/release-98/fasta/gallus_gallus/dna_index/) and having issues with bismark genome preparation.
> 
> The command I used
> `bismark_genome_preparation --parallel 2 --genomic_composition --verbose ${genome_dir} `
> 
> bismark version: 0.19.0
> bowtie2 version: 2.3.5.1
> 
> It's been running for 20 hours and completed steps I and II and step III is still running. It generated only 4 bt2 index files (*.4.bt2, *.3.bt2, *.1.bt2, *.2.bt2) for both GA and CT converted genomes.
> 
> The error log file shows this output (last 10 lines):
> 
> _Step II - Genome bisulfite conversions - completed Bismark Genome Preparation - Step III: Launching the Bowtie 2 indexer Preparing indexing of CT converted genome in ${genome_dir}/Bisulfite_Genome/CT_conversion/ Building a SMALL index Preparing indexing of GA converted genome in ${genome_dir}/Bisulfite_Genome/GA_conversion/ Building a SMALL index_
> 
> The output log file shows (last 10 lines):
> 
> _bmax according to bmaxDivN setting: 131947619 Using parameters --bmax 98960715 --dcv 1024 Doing ahead-of-time memory usage test Passed! Constructing with these parameters: --bmax 98960715 --dcv 1024 Constructing suffix-array element generator Building DifferenceCoverSample Building sPrime Building sPrimeOrder V-Sorting samples_
> 
> Can someone help me whats going wrong?
> Thank you,
> Best,
> Naresh D J

Hi Felix,
Can you help me?

**Comment by FelixKrueger** [comment]
Hi Naresh,

Sorry for the late reply, I am now back from the holidays. With a genome size of ~1.1 Gbp and `--parallel 2` it shouldn't take very long at all. In fact I just downloaded the genome file you linked and ran the same command over here:

```
time bismark_genome_preparation --parallel 2 --genomic_composition --verbose .
```

Which completed in just under half an hour:

```
Total time for backward call to driver() for mirror index: 00:10:23

real    29m51.368s
user    89m43.670s
sys     2m33.924s
```

To be honest I am not exactly sure why the Bowtie 2 indexing process doesn't seem to continue on your end, but I would consider the following:

- Upgrade Bismark to v0.22.3. Not sure much has changed, but your version is Bismark is > 2 years outdated
- Do you have enough memory on your machine? It shouldn't take all that much, but will probably require some 6-8Gb of RAM for `--parallel 2`
- Apart from the two points above, you could try to run the indexing manually. The command (which Bismark also uses), is: 

`bowtie2-build  -f genome_mfa.CT_conversion.fa BS_CT --threads 2`

I hope this helps, Cheers, Felix

**Comment by nashchem** [comment]
@FelixKrueger , No problems, Thank you for the response. Finally I made it to work by increasing the memory to 20GB for each core and --parallel 4.
One more quick question, does large memory needed for alignment as well.
Best, Naresh

**Comment by FelixKrueger** [comment]
Given that the genome is around 40% of the size of the human or mouse genomes I would expect a memory usage of ~6-7GB per instance of Bismark, so if you are planning to use `--parallel` you would need to multiply this number.
