### ISSUE TITLE
--dovetail not available while using --old flagg 

### ISSUE THREAD

**Issue by AlejandroXriv** [FelixKrueger/Bismark#297]
Dear Felix,

My name is Alejandro and Im new at using Bismark using v 22.1. Recently I have tried to start an alignment using the following command line:

./bismark /mnt/e/Bismark/bismark_genome/bismark_genome/hg19_indexed -1 /mnt/e/NGS_data/sae_meth_fastq/first_run/R1_FINAL_CONCATENATED.fastq.gz -2 /mnt/e/NGS_data/sae_meth_fastq/first_run/R2_FINAL_CONCATENATED.fastq.gz --score_min L,-0.6,-0.6 --old_flag --dovetail

However the output of the terminal is as follows

                                                                                                                                                        Bowtie 2 seems to be working fine (tested command 'bowtie2 --version' [2.3.4])                                                                                Output format is BAM (default)                                                                                                                                Alignments will be written out in BAM format. Samtools found here: '/usr/bin/samtools'                                                                        Reference genome folder provided is /mnt/e/Bismark/bismark_genome/bismark_genome/hg19_indexed/  (absolute path is '/mnt/e/Bismark/bismark_genome/bismark_genome/hg19_indexed/)'                                                                                                                                             FastQ format assumed (by default)                                                                                                                             **The option '--dovetail' may only be specified with the current SAM FLAG values. Please respecify...**

Does this mean that --dovetail option is not compatible with the --old flag options? it seems so as I tried the same command line removing the --old flag and the  alignment run as normal. 

Thanks in advance for your time

Best,

Alejandro

**Comment by FelixKrueger** [comment]
Hi Alejandro,

It sounds quite possible that this is not possible, since we have stopped supporting the old FLAG values for nearly 7 years now. Do you really require different FLAG values to the ones used right now?

Happy New Year,
Felix

**Comment by AlejandroXriv** [comment]
Dear Felix

Thanks for your quick answer, ideally we would like to continue using the old FLAG values as we use a software that requires the old FLAG.

Thanks again for your help

Best,

Alejandro

**Comment by FelixKrueger** [comment]
In that case I think it would you would either have the option of trying to use `--no_dovetail` (I think this is an option), or run Bismark in its normal mode, and then go do one round of post-processing where you change the FLAG values.

**Comment by AlejandroXriv** [comment]
Indeed, I think we will use the –no_dovetail option.

Thanks a lot for your answers.

Best,


Alejandro X. Rivera. Ph.D.
[http://www.agilent.com/cs/promotions/images/Agilent_Logo_Tag_v_RGB_1.33w.png]
Field Application Scientist
Diagnostics and Genomics Group
Agilent Technologies Mexico, S. de R. de C. V.
M: +52  5518504639    |     www.agilent.com<http://www.agilent.com/>
xchel.rivera@agilent.com






Follow Agilent on:

[http://www.agilent.com/cs/promotions/images/20170518-social-media-facebook-sml.png] [http://www.agilent.com/cs/promotions/images/20170518-social-media-twitter-sml.png]  [http://www.agilent.com/cs/promotions/images/20170518-social-media-linkedin-sml.png]   [http://www.agilent.com/cs/promotions/images/20170518-social-media-instagram-sml.png]
