### ISSUE TITLE
size of result bam files, multicore 

### ISSUE THREAD

**Issue by robinycfang** [FelixKrueger/Bismark#298]
Hi,

I have some Illumina paired-end WGBS data. I ran Bismark as followings:

`bismark --genome /path/to/fasta/and/bisulfite_index -1 reads_1.fq.gz -2 reads_2.fq.gz -o output_dir --temp_dir tempdir -p 4 --multicore 4 `

I got these results:

30G reads_1_bismark_bt2_pe.bam
20G reads_1.fq.gz.temp.\*_bismark_bt2_pe.bam
2k    reads_1.fq.gz.temp.\*_bismark_bt2_pe.bam_report.txt
*: 1 to 4

The naming is confusing, but I understand that if we don't set basename, bismark will automatically use the name of the first fastq file. In my case, I have 4 separate bam files generated, and I believe that bismark merge them all into reads_1_bismark_bt2_pe.bam, but it seems like 4 bam files doesn't add up (20*4=80G vs. 30G). Just want to quickly confirm that the output is correct. Perhaps summing up bam files doesn't work this way? Also, it looks like the temp bam files don't get deleted automatically in the end on the multicore mode.

Thanks for any clarifying!

YC

**Comment by FelixKrueger** [comment]
Hi @robinycfang,

You are right that the output should only be a single BAM file, ending in `reads_1_bismark_bt2_pe.bam` which should be pretty much of the same size all temp files added together. Further, all temporary BAM files as well as report files should have been deleted at the very end.

If they do not get deleted properly then I would assume that
- either the merging process was still ongoing, and you just need to wait a little longer
- or that something bad happened to the run which caused the merging process to stop, e.g. maybe you ran out of disk space?

You should be able see in the on-screen text (or the log file if you redirected the on-screen output) what is going on. Feel free to send it to me, either post it here or via email, so I can look through the log and try to spot the problem.

Cheers, Felix

**Comment by robinycfang** [comment]
Hey Felix,

I realized the process was still running right after I posed the issue, so I immediately closed this pose. Still, thanks for the speedy reply!

YC

**Comment by FelixKrueger** [comment]
Ah excellent. So I assume all is fine by now?

**Comment by robinycfang** [comment]
Yes, all is working well now. Thanks for making Bismark, that's very useful!

YC
