### ISSUE TITLE
feature request: --cram output option

### ISSUE THREAD

**Issue by avilella** [FelixKrueger/Bismark#3]
Feature request to have a .cram/.crai compatibility in bismark, using samtools 1.2 or later versions, so that .cram files are produces if the `--cram` flag is present, and the files are consumed by bismark methylation report downstream of the alignment step.

**Comment by FelixKrueger** [comment]
I have added the new options `--cram` and `--cram_ref` to Bismark for both paired-end and single-end mode and it seems to work fine for me. This option requires Samtools version 1.2 or higher, and you need to supply the genome FastA sequences as a single file with the option `--cram_ref`. In the future I am considering to derive the reference file from multiple .fa files that were specified for the Bismark run anyway.

Can you please have a go and see if this is what you were after? Addressed in 0726a7fd360067af8bb3fda4cb71ab68e9d20369.

**Comment by avilella** [comment]
I am on it!

**Comment by FelixKrueger** [comment]
Updated the `CRAM` functionality to now also work in `--multicore` mode, and to derive the single-file FastA reference required for `--cram_ref` from the genome FastA sequences if not specified explicitly. Addressed in 047609416ff2cd1377b11b1c2a0ee1115a982fd8.
