### ISSUE TITLE
deduplication by umi

### ISSUE THREAD

**Issue by HyunjunNam** [FelixKrueger/Bismark#300]
Hi,

I am trying to use './deduplicate_bismark' for the deduplication.
But problem is that format of bam file that I have is little bit different with bam file in deduplicate_bismark --help.

here is the header line of the bam file that I have below,

```
@NB501200:95:HKCJNAFXY:1:11101:7368:1091:CAGT_NNNT_1:N:0:ACAACG
TATTAAGTAGTAGTTATAGTTTAAGTGGGAGAGGAGGTGAAGGTTTTAAAGATAAGTTATAGGAGTTTTGGTAAGGGAAGGAGTTTGTTATTTTAATATATTATTTAAATTAGTATTGAATGGGAAGATTTAGGTAGGGGACATAN
+
E/EEAAEEEEEEAEEAEEEEEEAEEEEEEEEEEEEEEEEEEE<EEEE/EEEEEEEEEEEEEEEAEEEEEAEEEEEEEEEEEAEEEEEEE/EEEEAEEAAAEA/EEA/A<AEAEE/AAEE<AAAAA<EEEEEE6<AE<AAAA<AEE#


CAGT_NNNT: umi sequence of paired-reads
ACAACG: index sequence
```

I've extracted umi sequence by using fastp, and it generated this fastq file (umi-trimmed).
Then, I've ran the bismark on those fastq files and, bismark generated bam file as output file. Then I was trying to run deduplicate_bismark on the bam file.

As I know, 'deduplicate_bismark' recognizes last element of read ID (e,g, ACAACG here) as barcode for deduplication, not 'CAGT_NNNT'.

In this case, should I modify my fastq files for the deduplication?

**Comment by FelixKrueger** [comment]
Hi @HyunjunNam 
In its current form, `deduplicate_bismark` extracts word characters from the last `:` in the read ID to the end of the string:
 https://github.com/FelixKrueger/Bismark/blob/5720acbcf9c54738a2285670cd68da10c9bfa913/deduplicate_bismark#L583

If you want to use the `--barcode` option I suppose you've got the choice of either modifying the FastQ files to end in the UMI-sequence, or modifying the regex in line 583 to suit your needs. Does that make sense?

**Comment by HyunjunNam** [comment]
Thanks Felix.
Your suggestion makes sense to me. 

This is the first time to analyze methylation calling, so some steps are still unclear to me.
First of all, how does deduplication step affect to methylation calling? If I don't do deduplication step,  the result of methylation calling will be changed?

Second, my input files is fastq files. So to do the deduplication step, I need following steps.
1. run bismark on fastq files-> generate bam file
2. run deduplication_bismakr on the bam files -> generate deduplicated bam file.
3. run bismark_methylation_extractor on duplicated bam file. -> get the result of methylation calling.
Is this correct?

When I followed above steps, the only difference between including/excluding deduplication steps is that the chart for duplication was inserted into bismakr report html or not. Except that, all of the results are same with no-deduplication step. 
So to my understanding, deduplication step does not affect to define methylated sites. 
Am I correct?

Hyunjun

**Comment by FelixKrueger** [comment]
The deduplication step really only intends to find reads that come from PCR (over-)amplification, and remove those so that some regions to not gain an unfair coverage advantage over less amplified regions (as more highly covered regions will have a higher chance to result in statistically significant changes).

If your samples are not very duplicated, then this step will indeed not change your results very much.

The workflow you are describing looks perfectly fine to me.

**Comment by HyunjunNam** [comment]
Thank you for quick response.

If I  modify the the regex in line 583 for my data which have dual UMI sequence for paired-reads, it the only thing that I should do is modifying regex of code to just recognize the dual UMI sequences (such as 'CAGT_NNNT')? Are there anything to change additionally?

Hyunjun

**Comment by FelixKrueger** [comment]
I believe all you would need to be doing is to remove the `_` in the dual UMIs, and put it to the end, like so:

```
@NB501200:95:HKCJNAFXY:1:11101:7368:1091:1:N:0:ACAACG:CAGTNNNT
TATTAAGTAGTAGTTATAGTTTAAGTGGGAGAGGAGGTGAAGGTTTTAAAGATAAGTTATAGGAGTTTTGGTAAGGGAAGGAGTTTGTTATTTTAATATATTATTTAAATTAGTATTGAATGGGAAGATTTAGGTAGGGGACATAN
+
E/EEAAEEEEEEAEEAEEEEEEAEEEEEEEEEEEEEEEEEEE<EEEE/EEEEEEEEEEEEEEEAEEEEEAEEEEEEEEEEEAEEEEEEE/EEEEAEEAAAEA/EEA/A<AEAEE/AAEE<AAAAA<EEEEEE6<AE<AAAA<AEE#
```

This would then simply use both UMIs of R1 and R2 combined for deduplication. There is also another tool available that deals with dual UMIs in this way (https://github.com/FelixKrueger/Umi-Grinder, option `--dual_umi`), but that expects the 2 UMIs at the end, separated by colons. One of these should work for you.

**Comment by HyunjunNam** [comment]
Thank you so much Felix.
Let me try what you suggested first!

Hyunjun

**Comment by HyunjunNam** [comment]
Hi Felix again,

I tired what you mentioned (modified header by putting the UMI sequence to the end without '_'). 
deduplicate_bismark ran with out any error, but I am not sure about deduplication result.

```
[sequencer@meth1]$ ./deduplicate_bismark --barcode -p TM01-Meth1_S11_                                                                                                                                                                       L001_R1_001_umi_modified_bismark_bt2_pe.bam
Processing paired-end Bismark output file(s) (SAM format):
TM01-Meth1_S11_L001_R1_001_umi_modified_bismark_bt2_pe.bam


If the input is a multiplexed sample with several alignments to a sin                                                                                                                                                                        gle position in the genome, only alignments with a unique barcode wil                                                                                                                                                                        l be chosen)

Checking file >>TM01-Meth1_S11_L001_R1_001_umi_modified_bismark_bt2_p                                                                                                                                                                        e.bam<< for signs of file truncation...



Now testing Bismark result file TM01-Meth1_S11_L001_R1_001_umi_modifi                                                                                                                                                                        ed_bismark_bt2_pe.bam for positional sorting (which would be bad...).                                                                                                                                                                        ..passed!
skipping SAM header line:       @HD     VN:1.0  SO:unsorted
skipping SAM header line:       @SQ     SN:10   LN:135534747
skipping SAM header line:       @SQ     SN:11   LN:135006516
skipping SAM header line:       @SQ     SN:12   LN:133851895
skipping SAM header line:       @SQ     SN:13   LN:115169878
skipping SAM header line:       @SQ     SN:14   LN:107349540
skipping SAM header line:       @SQ     SN:15   LN:102531392
skipping SAM header line:       @SQ     SN:16   LN:90354753
skipping SAM header line:       @SQ     SN:17   LN:81195210
skipping SAM header line:       @SQ     SN:18   LN:78077248
skipping SAM header line:       @SQ     SN:19   LN:59128983
skipping SAM header line:       @SQ     SN:1    LN:249250621
skipping SAM header line:       @SQ     SN:20   LN:63025520
skipping SAM header line:       @SQ     SN:21   LN:48129895
skipping SAM header line:       @SQ     SN:22   LN:51304566
skipping SAM header line:       @SQ     SN:2    LN:243199373
skipping SAM header line:       @SQ     SN:3    LN:198022430
skipping SAM header line:       @SQ     SN:4    LN:191154276
skipping SAM header line:       @SQ     SN:5    LN:180915260
skipping SAM header line:       @SQ     SN:6    LN:171115067
skipping SAM header line:       @SQ     SN:7    LN:159138663
skipping SAM header line:       @SQ     SN:8    LN:146364022
skipping SAM header line:       @SQ     SN:9    LN:141213431
skipping SAM header line:       @SQ     SN:X    LN:155270560
skipping SAM header line:       @SQ     SN:Y    LN:59373566
skipping SAM header line:       @PG     ID:Bismark      VN:v0.22.3  C                                                                                                                                                                        L:"bismark --genome /isilon/R_and_D/user_folders/hjnam/Data/genomes -                                                                                                                                                                        1 /isilon/R_and_D/user_folders/hjnam/Projects/Methylation/data/Sample                                                                                                                                                                        _Meth1/TM01-Meth1_S11_L001_R1_001_umi.fastq/TM01-Meth1_S11_L001_R1_00                                                                                                                                                                        1_umi_modified.fastq -2 /isilon/R_and_D/user_folders/hjnam/Projects/M                                                                                                                                                                        ethylation/data/Sample_Meth1/TM01-Meth1_S11_L001_R2_001_umi.fastq/TM0                                                                                                                                                                        1-Meth1_S11_L001_R2_001_umi_modified.fastq"

Total number of alignments analysed in TM01-Meth1_S11_L001_R1_001_umi                                                                                                                                                                        _modified_bismark_bt2_pe.bam (UMI-mode):        2506534
Total number duplicated alignments removed:     2243684 (89.51%)
Duplicated alignments were found at:    114763 different position(s)

Total count of deduplicated leftover sequences: 262850 (10.49% of tot                                                                                                                                                                        al)
```

As you can see here, the fraction of deduplicated leftover sequences is only 10.49% (89.51% reads were duplicated). 

The duplicated rate is so higher than I expected. When I used fastp (https://github.com/OpenGene/fastp) to trim out UMI sequences and put them into header of fastq file, it provided the summary report in which the duplication rate was around 24%. I know that each tools have own algorithms to check the duplication rate, but the difference is bigger than I expected. 
Is there anything that I missed here?

Hyunjun

**Comment by HyunjunNam** [comment]
Hi Felix, 
I'm adding another question..

Should I run the 'bismark_methylation_extractor' on deduplicated bam file or original bam file(before deduplication)?

I've generated bismark2report html on both results, then I realized that summary reports are different between them...

Hyunjun

**Comment by FelixKrueger** [comment]
Hi Hyunjun,

I suppose the test to see if the UMI deduplication has worked you could run the file not in UMI mode, like so:

```
./deduplicate_bismark TM01-Meth1_S11_L001_R1_001_umi_modified_bismark_bt2_pe.bam
```

You here you would expect that number of duplicated sequences to be even higher (I realise that this can only be a small increase as you are already removing ~90% of reads as duplicates). What the UMI deduplication in `deduplicate_bismark` is doing is taking the chromosome, mapping orientation, start, end as well as the UMI sequence and check whether this exact combination was present already (in which case no further duplicates are written out).

https://github.com/FelixKrueger/Bismark/blob/5720acbcf9c54738a2285670cd68da10c9bfa913/deduplicate_bismark#L790

Regarding your second question: for RRBS files we typically recommend not to de-duplicate as you cannot tell the difference between genuine MspI fragments and PCR duplicates. In your case where you have UMI sequence to discriminate between PCR products and different fragments I would say you should de-duplicate (after all this is the whole idea behind using UMIs...). If you remove 90% of the results, albeit PCR artefacts, in this step I wouldn't be surprised if this changes the overall stats somewhat (some types of fragment might just get preferentially amplified for example).

If you are suspecting that something is not working as expected I'd be happy to take a look at one of your files over here (just drop me a quick email and I can set up an FTP server for you).

**Comment by HyunjunNam** [comment]
Hi Felix,

I've tried what you suggested to see whether UMI deduplication is working or not on my data.
I could see the obvious difference between two commands below,

```
command 1. 
./deduplicate_bismark TM01-Meth1_S11_L001_R1_001_umi_modified_bismark_bt2_pe.bam

command 2.
./deduplicate_bismark --barcode -p TM01-Meth1_S11_L001_R1_001_umi_modified_bismark_bt2_pe.bam
```

Second command could capture more unique reads than first one, which means duplication rate was higher in command 1 than command 2. Based on this test, I think UMI deduplication is properly working on my data.

Thanks!
Hyunjun

**Comment by FelixKrueger** [comment]
Excellent. Now the next step would be to improve somewhat the wet-lab side of the experiment to reduce the the duplication rate... :)
