### ISSUE TITLE
M-bias plot have fluctuation a lot.

### ISSUE THREAD

**Issue by HyunjunNam** [FelixKrueger/Bismark#301]
Hi,

I got M-bias plot for my data after umi trimming. But they are not flat at all, and have a lot of fluctuation like below,
![Bismark M-bias Read 1](https://user-images.githubusercontent.com/56126961/72287326-afc1d280-35fb-11ea-8a42-4ebfdf661e9a.png)
![Bismark M-bias Read 2](https://user-images.githubusercontent.com/56126961/72287334-b2242c80-35fb-11ea-9665-5e967a674ebe.png)

Is this normal? (I am using targeted library now for the analysis)

Thanks!

**Comment by FelixKrueger** [comment]
It is difficult to say what exactly is 'normal', but one can certainly say that it doesn't look as flat as one would hope to see for an unbiased shotgun sequencing library. 

Peakyness in the signal often arises when certain sequences show up at an elevated rate in a library, e.g. certain PCR products tend to show a very similar profile at certain positions. Is your libary the combination of a number of different PCR products, or does it use something like the SureSelect kit? Certain aspects of these M-bias plots might require some additional thoughts and/or processing, e.g. why are there certain residues at the start of read 2 with non-CG methylation of 100%?

Can't you just go ahead and look at the amplified/enriched regions to see if the results appear to make any sense?
