### ISSUE TITLE
html bismark report

### ISSUE THREAD

**Issue by demis001** [FelixKrueger/Bismark#304]
@FelixKrueger 
I am trying to create html report and missing nucleotide report file, would you please suggest what went wrong?
I assume these files were created during this step.

`bismark2bedGraph --buffer 20G -o CpG_context_${SAMPLE}.gz CpG_context_${SAMPLE}*.gz`

```
# html report

 for SAMPLE in `cat ./task_samples.txt`
 do
     bismark2report  -o ${SAMPLE}_summary.html  --dir alignment_report --alignment_report ${SAMPLE}_L001_R1_val_1_bismark_bt2_PE_report.txt --splitting_report ${SAMPLE}_L001_R1_val_1_bismark_bt2_pe_splitting_report.txt --     mbias_report ${SAMPLE}_L001_R1_val_1_bismark_bt2_pe.M-bias.txt
 done
```

Would you also guide me how to use  bismark2summary script? I  have seen the parameters and it isn't clear to me how to use it.

Everything looks good, the alignment efficiency is great!

@demis001

**Comment by FelixKrueger** [comment]
Hi @demis001 

you should simply be able to go to folder containing **ALL** your files, and then type:

`bismark2report`

of

`bismark2summary`

Both scripts should identify all relevant files and generate the reports automatically.

**Comment by demis001** [comment]
Thanks!

How to merge the CpG report files and generate methylation ratio? I have different treatment groups?

`coverage2cytosine --genome_folder $GENODIR --output CG_${SAMPLE} CpG_context_${SAMPLE}.gz.bismark.cov.gz`

```
CG_ADAA1381.CpG_report.txt
CG_ADAA760.CpG_report.txt
CG_ADCA1594.CpG_report.txt
```
I want to merge the above three files, I assume these give, methylated C count and unmethylated count. How do you generate methylation ratio from this? 

I want to generate methylation ratio from the same treatment group for DMR analysis in methylKit? Any software recommendation for DMR call?

Thank you for your help!!!!

@demis001

**Comment by FelixKrueger** [comment]
I am afraid this is where the Bismark package ends. If you wanted to generate a unified report you could feed all files (e.g. `CpG_*CG_AD*`) to `bismark2bedGraph` to generate a single coverage file, and then generate a single CpG report.

But I am sure methylKit has functionality to group samples from the same group?

**Comment by demis001** [comment]
I am not looking for a unified report because I have different treatment groups, I am interested with CpG context not others. I did, methylation extraction using this line:

`bismark_methylation_extractor --single-end --gzip --comprehensive --merge_non_CpG --bedGraph --multicore 6 --buffer_size 34G ${SAMPLE}_L001_merged_unpaired_sorted_dedup.deduplicated.bam`

And then, did:

bismark2bedGraph --buffer 20G -o CpG_context_${SAMPLE}.gz CpG_context_${SAMPLE}*.gz

This gave me sample level CpG files: 

```
CpG_context_ADAA1381.gz 
CpG_context_ADAA1381.gz.bismark.cov.gz
CpG_context_ADAA1381_L001_merged_unpaired_sorted_dedup.deduplicated.txt.gz
CpG_context_ADAA1381_L001_R1_val_1_bismark_bt2_pe.txt.gz
```

Then, for each sample, I did coverage2cytosine:

`coverage2cytosine --genome_folder $GENODIR --output CG_${SAMPLE} CpG_context_${SAMPLE}.gz.bismark.cov.gz`

To get: 

`CG_ADAA1381.CpG_report.txt`

Are you saying this isn't a normal practice?

I have "disease vs control" for many groups to call DMR. After this step, I want to merge coverage2cytosine output for the same treatment group.

@demis001

**Comment by FelixKrueger** [comment]
That looks fine to be honest, now you just need to take the files forward for analysis in e.g. methylKit.

You could also arrive at the CpG report directly by using a command like this:

`bismark_methylation_extractor --gzip --bedGraph --multicore 6 --buffer_size 34G --cytosine_report --genome_folder $GENODIR *.deduplicated.bam` 

But you seem to have gotten there manually already, so you should be fine. By the way, I think the coverage files are probably already good enough for your DMR analysis, and since they only contain positions that were covered in the data, they should also be noticably smaller and easier to work with.

**Comment by demis001** [comment]
Thanks!

Oh! I see thank you for let me know. I have executed separate line in for loop. I should have run in single steps. Good to know for the future. 

Thank you for help! I really appreciate. It is my first time to use your tools.

@demis001

**Comment by demis001** [comment]
I don't think this will work in my case because. The CpG report file should combine PE and SE. This should  work if the option works "--cytosine_report" option works with this step. 

`bismark2bedGraph --buffer 20G -o CpG_context_${SAMPLE}.gz CpG_context_${SAMPLE}*.gz`

**Comment by FelixKrueger** [comment]
Ah right if you have this special case then you need to run the steps sequentially, e.g. in `for` loops, as you have done. Good luck!

**Comment by demis001** [comment]
Reply, that is what I did.

Thanks!
