### ISSUE TITLE
BAM sorting query

### ISSUE THREAD

**Issue by prasundutta87** [FelixKrueger/Bismark#305]
Hi,

Once I got a BAM file after I have aligned paired-end reads using 'bismark', is it absolutely necessary to sort the BAM file by queryname using samtools sort -n before supplying the file to 'deduplicate_bismark' program? Or 'bismark' or 'deduplicate_bismark'  sort the BAM file inside their scripts already? I did not find the code for sorting in either of the programs (correct me if I am wrong). 'SO' in the header does show unsorted in the BAM files. Just to add, I am using Bismark v0.16.3

Regards,
Prasun

**Comment by FelixKrueger** [comment]
Hi Prasun,

Bismark outputs the files in a format that already resembles name sorting, i.e. Read 1 and Read 2 of a pair follow each other. As a result of this you can straight away use `deduplicate_bismark` on the BAM file produced by Bismark.

I would highly recommend you upgrade to the latest version, it seems that your version of Bismark is already some >3 years out of date.

**Comment by prasundutta87** [comment]
Thanks a lot for the confirmation, Felix. I will use the latest version as suggested.
