### ISSUE TITLE
nucleotide coverage interpretation

### ISSUE THREAD

**Issue by prasundutta87** [FelixKrueger/Bismark#306]
Hi,

Is there any document I can refer to where it is explained how to interpret nucleotide coverage statistics? Or, what is it I should infer or look for in the coverage report?

Regards,
Prasun

**Comment by FelixKrueger** [comment]
The nucleotide coverage statistics was really just something we once needed for a paper submission (where we looked at difference sequence bias of different kits). I don't think there is any further information anywhere. If something looks very off or biased compared to the standard genomic composition it might give you a pointer where to start looking.

**Comment by prasundutta87** [comment]
Thanks, Felix. I believe even the FastQC report is sufficient if I am concerned about single nucleotide composition statistics or GC content as well.

**Comment by FelixKrueger** [comment]
Quite possibly. I don't think we have ever used it ourselves really since that publication. The genome frequency table does come in handy though, if you want to know the sequence composition of a genome for example, or the number of CpGs....

**Comment by prasundutta87** [comment]
Thanks for the explanation, Felix!
