### ISSUE TITLE
Calculate coverage

### ISSUE THREAD

**Issue by demis001** [FelixKrueger/Bismark#308]
@FelixKrueger 

Do you know how to calculate a combined coverage for multiple samples from `*bismark.cov` files?

I decided to use DMRfinder for DMR call due to command line usage. What I am looking is to estimate global genome wide coverage for each treatment group. For example, I have 6 samples in Control group and want to know the global coverage for all samples without merging to a single bam file.

**Comment by FelixKrueger** [comment]
Hi @demis001 

I am not sure about such tools to be honest, especially not command line ones, as we tend to use SeqMonk for most our workflows (where you could simply import all BAM files, put them into a Data Group, and then run Data Store summary on that).

I am also not sure if you could use the coverage files for that, as they output single bp calls only, and it is kind of tricky getting that related back to the fold genome coverage (unless you use the total number of CpG positions as the 'genome length' , which should then work again).
