### ISSUE TITLE
Generating PE_report.txt from a Bam file

### ISSUE THREAD

**Issue by npatel22526** [FelixKrueger/Bismark#310]
Hello, 

We have mapped bam files from a cloud based platform but they can not provide us the *PE_report.txt file.  As per my understanding *PE_report.txt is generated during mapping step, I was curious if it is possible to generate the same report given a bam file mapped with bismark ?

Best, 
Nick

**Comment by FelixKrueger** [comment]
Hi Nick,

Unfortunately it is not possible to recover the mapping statistics just from a BAM file, as all of the information about unmappable and ambiguous alignments are no longer present at this point. 

You can however get the overall methylation statistics by running `bismark_methylation_extractor`, just look out for the `..._splitting_report.txt`.

**Comment by npatel22526** [comment]
Thank you for quick response.
