### ISSUE TITLE
Failed to open filehandle: too many files

### ISSUE THREAD

**Issue by hanahm1** [FelixKrueger/Bismark#311]
Hi Felix,

Two of my seven experimental samples (.bam files) are not running through the bismark_methylation_extractor command. I run the following:

`bismark_methylation_extractor -s -o $outputfolder --bedgraph --CX --multicore 8 $inputBamFile
`

It goes through 45000000 lines and starts throwing these:

`Processed lines: 48000000
Processed lines: 48000000
Finished processing child process. Exiting..
Processed lines: 47000000
Finished processing child process. Exiting..
Processed lines: 43000000
Processed lines: 47000000
`
It writes to the methylation.txt files then throws this error:

`Now writing methylation information for file >>CpG_OB_zr2831_2.sort.txt<< to individual files for each chromosome
Failed to open filehandle: Too many open files at /home/hanahm1/miniconda3/envs/ViewBS/bin/bismark2bedGraph line 278, <IN> line 249872686.
Finished BedGraph conversion ...`

When the code finishes, it leaves a bunch of methXtractor.temp files in the output folder and an empty .cov report.

All of the output files (with the exception of the .bismark.cov file) has data. I'm not sure why this is only throwing this error for two of my seven .bam files. Any tips?

Thank you!

-Hanah

**Comment by FelixKrueger** [comment]
Hi Hanah,

Are you using a genome that consists of a limited number of chromosomes, such as the human or mouse genome, or are you using a less polished genome that is made up of contigs and/or scaffolds? In the latter case you can re-run the coverage file creation using `bismark2bedGraph` with the option `--scaffolds` enabled. This should allow you to circumvent your operating systems limitation of how many files you are allowed to hold open at the same time.

For more information just run `bismark2bedGraph --help`

Cheers, Felix

**Comment by hanahm1** [comment]
Hi Felix, 

Thank you for the quick answer. After running the following: 

`bismark2bedGraph -o F268.C --dir $outputDir --CX --scaffolds $inputBamFile
`
I am now receiving this error

`The genome of interest was specified to contain gazillions of chromosomes or scaffolds. Sorting everything in memory instead of writing out individual chromosome files ...
Sorting input file zr2831_2.sort.bam by positions (using -S of 2G)
Use of uninitialized value $pos in string ne at /home/hanahm1/miniconda3/envs/ViewBS/bin/bismark2bedGraph line 460, <$ifh> line 1.
Missing (+/-) methylation call at /home/hanahm1/miniconda3/envs/ViewBS/bin/bismark2bedGraph line 519, <$ifh> line 1.
	main::validate_methylation_call(undef, undef) called at /home/hanahm1/miniconda3/envs/ViewBS/bin/bismark2bedGraph line 465`

I am using the bosTau9 genome.

Thanks again!

**Comment by FelixKrueger** [comment]
The input for bismark2bedGraph are the C* context files produced by the methylation extractor, and not a BAM file. 

I would suggest you start with the CpG* files, as the non-CG context will be absolutely huuuge, and be almost universally unmethylated... Else just use C* as the input files.

**Comment by hanahm1** [comment]
Hi Felix,

That worked perfectly! Thank you so much for your help.

Best,

Hanah
