### ISSUE TITLE
Generate CHG coverage file using bismark2bedGraph 

### ISSUE THREAD

**Issue by GatorShan** [FelixKrueger/Bismark#312]
Hi Felix,

I am trying to generate CHG coverage file using the following command:
```
bismark2bedGraph \
	--output S2_CHG \
	--dir ${IN} \
	--CX_context \
	--buffer_size 4G \
	${IN}/CHG_OB_S2_cat_R1_val_1_bismark_bt2_pe_nameSorted.deduplicated.txt.gz \
	${IN}/CHG_OT_S2_cat_R1_val_1_bismark_bt2_pe_nameSorted.deduplicated.txt.gz
```

As you might have seen, the input files are **strand-specific methylation output files** from `bismark_methylation_extractor`.

Does the script look okay? If so, I guess a similar script could be used to generate the CHH coverage file.

Thanks!

Shan

**Comment by FelixKrueger** [comment]
Hi Shan,

Sorry for the late reply, but yea, that command looks spot-on!

**Comment by GatorShan** [comment]
Hi Felix,

Thanks for your quick reply! This is very helpful!

Shan
