### ISSUE TITLE
Duplication rate from bismark is higher than duplication rate from fastp

### ISSUE THREAD

**Issue by HyunjunNam** [FelixKrueger/Bismark#316]
Hi Feilix,

I extracted the UMI sequences and trimmed that out by using Fastp. Then aligned and de-duplicated them by using Bimark.

Fastp calculated duplication rate after UMI trimming. So, I compared its duplication rate with ones from Bismark. However the duplication rate from bismark is higher than duplication rate from fastp.
I know that the algorithm to calculate duplication rate in Fastp and Bismark is totally different, but I expected that duplication rate of bismark should be lower thant Fastp, because bismark used more info from the alignment such as strand, sequence and etc to check the duplication. Like FASTQC, the Fastp also use only few bp from read1 and read2 to calculate the duplication. For example, I got the duplication rate 21% from Fastp and 53% from bismark.
I'm not sure that my understanding is correct..
FYI, we are using dual-UMI for each reads...

Thank you
Hyunjun

**Comment by FelixKrueger** [comment]
Hi Hyunjun,

The UMI mode in `deduplicate_bismark` requires the following two things:
- the read ID of the FastQ entry (and thus also the BAM file) needs to end in a colon, followed by the UMI sequence, e.g.: 
`@NB501547:379:HHTVTBGXC:1:11101:20206:1060 1:N:0:0 TTGGTATG:CAGGACTA`
- the UMI mode is activated using the option `--barcode`:

`deduplicate_bismark --barcode mapped_bismark_file.bam`

This command would extract the _last_ `:sequence` from the readID, which here is `CAGGACTA`, and then use the following for deduplication: `chromosome:start:strand:UMI`. For paired-end files it would also use `chromosome:start:end:strand:UMI`, but note that only the very last `:CAGGACTA` would be used as UMI.

If your files haves dual UMIs then I am afraid deduplicate_bismark doesn't do the right thing out of the box. You could use the tool `UmiBam` from over here: https://github.com/FelixKrueger/Umi-Grinder. It should work pretty much in the same way, but it does have dual UMI support (type `UmiBam --help` for more options. This is from the help:

```
--umi			In addition to chromosome, start position and orientation this will also take a potential UMI into
                        consideration while deduplicating. The barcode needs to be the last element of the read ID and separated
                        by a ':', e.g.: MISEQ:14:000000000-A55D0:1:1101:18024:2858_1:N:0:CTCCT

--double_umi		If the file was double-barcoded this mode extracts both Read 1 and Read 2 barcodes for the UMI
			deduplication. In its current implementation the two UMIs are expected to the in a format like this:
			HWI-D00436:267:C71A4ANXX:5:1102:1531:82511_1:N:0:_TCTCACGG:R1:CCAACCTA:R2:TATGGGGT:F1:CAGT:F2:CAGT.
			The barcodes following R1: and R2: are being used, here CCAACCTA and TATGGGGT.
```

So in dual UMI mode you need to ensure that the reads contain `R1:` and `R2:` followed by their respective barcodes. If this pattern does not occur in the reads, the deduplication will simply nor extract any UMI, and therefore proceed as if you were not using UMIs at all.

You should easily be able to see if the procedure works by running deduplicate Bismark with and without `--barcode`: the difference should be very noticable!

**Comment by HyunjunNam** [comment]
Hi Felix,

The double UMI which you mentioned seems like their UMI sequence are different in R1 and R2 respectively. My understanding is correct?

The UMIs that I am using currently is dual-UMIs that are encompassing the insert sequence. 
For example,

R1:   Index 1 --- UMI(4pb) --- Insert sequence --- UMI(4pb) --- index2

R2 also have same structure. Is it okay that the double-umi option of UniBam could be used for my case?

Thanks!
Hyunjun

Thanks

**Comment by FelixKrueger** [comment]
I suppose if you would edit the sequences so that the FastQ file (and thus also the BAM file) contains:

`R1:FIRST_UMI(4pb):R2:SECOND_UMI(4pb)`

in the readID, it should be fine. I believe that the readID of Read 1 is used to form the entry in the BAM file, so in this scenario you could only accommodate the 2 UMIs from Read 1. If you wanted to also retain the UMIs of Read 2, then I would suggest you pre-process the FastQ files, extract the first and second 4bp UMIs of Read 1 and simply concatenate to form an 8bp `:R1:UMI1UMI2` and do the same for `R2:UMI1UMI2`.

Does that make sense?

**Comment by FelixKrueger** [comment]
I assume this has worked, will tidy a few issues now.
