### ISSUE TITLE
Methylation_consistency program

### ISSUE THREAD

**Issue by Drummerz** [FelixKrueger/Bismark#318]
Not exactly an issue but a question. Can the methylation_consistency program be easily altered to look at CHH context instead of CpG? I ask because in my system I believe CHH is altered in some samples and there are not programs available that look in this context for concordance or heterogeneity within reads.

**Comment by FelixKrueger** [comment]
Hi @Drummerz 

I think that should be relatively easy to do. I am currently attending the nf-core hackathon in London, so it would have to wait until next week if that is OK.

**Comment by FelixKrueger** [comment]
Hi @Drummerz 

Are you still interested in this or have you found a solution in the meantime?

**Comment by Drummerz** [comment]
Hello, I am still very much interested in this capability. I have been trying to edit the code for [BSPAT](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-015-0649-2#CR10) so that it can look for patterns in CHH methylation within reads but have had no success. CHH methylation has been shown to be the most responsive in the system I am working in and the increased abundance should make differences in patterns between samples more convincing.

**Comment by FelixKrueger** [comment]
OK, so changing the context simply from `CpG` to `CHH` would already work for you? You should still be able to set lowe and upper thresholds using the respective options

**Comment by Drummerz** [comment]
Yes, simply having the option to look at CHH would be very useful. I could tinker with the thresholds to observe any differences in patterns between samples. [BSPAT](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-015-0649-2#CR10) is great for getting a more complete view on what patterns are present and visualization of that data, but it only looks for CpG

**Comment by FelixKrueger** [comment]
Could you have a go at using the attached script and let me know if it is working in your hands?
[methylation_consistency_CHH.zip](https://github.com/FelixKrueger/Bismark/files/4307835/methylation_consistency_CHH.zip)

**Comment by Drummerz** [comment]
The scripts seems to be working great at detected CHHs! It is autodetecting that my bam file is single-end though I am fairly sure it is PE. Also, this is likely more involved but I am interested in looking at specific regions within my bam file (promoters etc.). Would it possible to have window/range option for this script?

**Comment by FelixKrueger** [comment]
It tries to find `-1 file... -2 file` in the `@PG` header line of your BAM file. You can override this with `-s/--single_end` if you prefer.

For specific regions I would suggest you simply use `samtools view` afterwards, you can feed it a bedfile witth regions of interest. Does that make sense?

**Comment by FelixKrueger** [comment]
I assume this has worked alright, I'm currently tidying up a few issues. Stay safe!
