### ISSUE TITLE
Guide doesn't mention TrimGalore --non_directional option

### ISSUE THREAD

**Issue by kubu4** [FelixKrueger/Bismark#319]
The section of the Bismark User Guide, "(IX) Notes about different library types and commercial kits" is very useful.

However, we just noticed in the TrimGalore documentation:

(https://github.com/FelixKrueger/TrimGalore/blob/master/Docs/Trim_Galore_User_Guide.md#non-directional-mode)

>Non-directional mode
>Trim Galore! also has a --non_directional option, which will screen adapter-trimmed sequences for the presence of either CAA or CGA at the start of sequences and clip off the first 2 bases if found. If CAA or CGA are found at the start, no bases will be trimmed off from the 3’ end even if the sequence had some contaminating adapter sequence removed (in this case the sequence read likely originated from either the CTOT or CTOB strand).

This usage isn't mentioned in the Bismark User Guide.

If you have a sec, could you please clarify what the implications are for using this setting vs. not using this setting when running TrimGalore?

edited: fix markdown formatting

**Comment by FelixKrueger** [comment]
Hi @kubu4 ,

The `--non_directional` setting which is only meant to be used for non-directional **RRBS** sequencing only. Non-directional RRBS libraries are indeed very rare, we had to deal with them in 2010/11, but I think someone else dug up a protocol a bit more recently. If your application is RRBS and you would like to know more about this you could probably read the RRBS Guide on the Trim Galore page, and direct further questions to me.

For anything else, including non-directional standard BS-seq libraries, e.g. scBS-seq or scNMT-seq, it is **not required** to use this options. I hope this helps. Cheers, Felix

**Comment by kubu4** [comment]
Thanks so much for the info and the very fast response! We encountered this situation (non-directional RRBS sequencing) when analyzing some data recently and started to dive into things when we noticed the TrimGalore `--non_directional` option and our curiosity was piqued...
