### ISSUE TITLE
bismark_genome_preparation to accept hg38.fa.gz

### ISSUE THREAD

**Issue by Shicheng-Guo** [FelixKrueger/Bismark#320]
Dear Felix, 

I think `bismark_genome_preparation `accept gzip compressed hg38.fa (hg38.fa.gz), correct? 

Thanks. 

Shicheng

**Comment by FelixKrueger** [comment]
Yes, in think it should. And so should Bismark itself

**Comment by FelixKrueger** [comment]
Closing this before it gets stale.
