### ISSUE TITLE
Context specific methylation totals in bismark reports

### ISSUE THREAD

**Issue by stephenjclark** [FelixKrueger/Bismark#321]
Hey Felix,

Would it be possible to get methylation counts in additional contexts within the report/summary_report files as is currently done for CpG, CHG, and CHH? Perhaps functionality to specify whichever contexts you want but specifically I would like HCCC (first C methylated/unmethyalted) to use as an upper bound for non-conversion in NOMe-seq data. And it would also be useful to have WCG and GCH when processing NOMe-seq.

Cheers,

Stephen

**Comment by FelixKrueger** [comment]
I got `coverage2cytosine` to a state where it records the counts for each context, and prints it to a special file called `*.cytosine_context_summary.txt` for each input coverage file. This will happen automatically whenever you specify `--nome`. The output file should enable pretty much any calculation you want to be doing downstream, e.g. in R.

At this stage I am not sure whether this should also be included into the `bismark2summary`, but if you think this is vital we could look into this further. Can you let me know your thoughts about it? 

Here is an example of the context summary report:

```
upstream	C-context	full context	count methylated	count unmethylated	percent methylation
A	CAA	ACAA	308398	93360	23.24
C	CAA	CCAA	329555	75518	18.64
G	CAA	GCAA	242262	118175	32.79
T	CAA	TCAA	302209	86219	22.20
A	CAC	ACAC	266786	91121	25.46
C	CAC	CCAC	409749	89154	17.87
G	CAC	GCAC	201057	138262	40.75
T	CAC	TCAC	332051	79557	19.33
A	CAG	ACAG	494448	90581	15.48
C	CAG	CCAG	637910	90746	12.45
G	CAG	GCAG	401128	249747	38.37
T	CAG	TCAG	487162	83964	14.70
A	CAT	ACAT	300967	96135	24.21
C	CAT	CCAT	346032	97047	21.90
G	CAT	GCAT	217814	133704	38.04
T	CAT	TCAT	321150	100241	23.79
A	CCA	ACCA	348770	85087	19.61
C	CCA	CCCA	539509	88565	14.10
G	CCA	GCCA	330171	183081	35.67
T	CCA	TCCA	399069	96139	19.41
A	CCC	ACCC	285724	53082	15.67
C	CCC	CCCC	355899	54261	13.23
G	CCC	GCCC	268064	162717	37.77
T	CCC	TCCC	422265	74286	14.96
A	CCG	ACCG	70023	7948	10.19
C	CCG	CCCG	165938	13788	7.67
G	CCG	GCCG	90554	52284	36.60
T	CCG	TCCG	85005	9313	9.87
A	CCT	ACCT	342091	65569	16.08
C	CCT	CCCT	380808	77914	16.99
G	CCT	GCCT	332897	245663	42.46
T	CCT	TCCT	457659	102572	18.31
A	CGA	ACGA	45916	20830	31.21
C	CGA	CCGA	62004	29813	32.47
G	CGA	GCGA	40118	42410	51.39
T	CGA	TCGA	43154	22971	34.74
A	CGC	ACGC	59804	24853	29.36
C	CGC	CCGC	100821	42292	29.55
G	CGC	GCGC	56360	64338	53.30
T	CGC	TCGC	50600	20063	28.39
A	CGG	ACGG	71208	30531	30.01
C	CGG	CCGG	114162	47425	29.35
G	CGG	GCGG	80053	77343	49.14
T	CGG	TCGG	69697	31756	31.30
A	CGT	ACGT	62275	25181	28.79
C	CGT	CCGT	65966	31621	32.40
G	CGT	GCGT	44159	54706	55.33
T	CGT	TCGT	48585	21673	30.85
A	CTA	ACTA	187018	55544	22.90
C	CTA	CCTA	200592	55320	21.62
G	CTA	GCTA	149676	112225	42.85
T	CTA	TCTA	240983	74952	23.72
A	CTC	ACTC	270297	58705	17.84
C	CTC	CCTC	461271	99396	17.73
G	CTC	GCTC	212611	174857	45.13
T	CTC	TCTC	424822	118010	21.74
A	CTG	ACTG	398802	69253	14.80
C	CTG	CCTG	657806	93150	12.40
G	CTG	GCTG	419404	277214	39.79
T	CTG	TCTG	532562	107885	16.85
A	CTT	ACTT	311887	81886	20.80
C	CTT	CCTT	339950	96574	22.12
G	CTT	GCTT	213138	174408	45.00
T	CTT	TCTT	404201	136833	25.29
```

Added here: 2e7e763b2591e8c2b0fff99b256e724651368e59

**Comment by stephenjclark** [comment]
Hi Felix,

This looks perfect. And I'm quite happy with it being a separate file, no need to clutter the summary report.

Stephen

**Comment by FelixKrueger** [comment]
Excellent. This will be in the next release then.
