### ISSUE TITLE
Order of chromosomes in bedGraph/coverage files

### ISSUE THREAD

**Issue by jnthnhss** [FelixKrueger/Bismark#324]
I have a question regarding bismark_methylation_extractor. I observed that in the final bedGraph/coverage files CpG sites are sorted by their position within each chromosome, but the order of chromosomes can differ, i.e., sometimes chromosome 14 might be reported first and sometimes chromosome 20. Is there a parameter to force a fixed order of chromosomes? (I couldn't find one.)

**Comment by FelixKrueger** [comment]
Hi Jonathan,
I don't think the order is currently enforced (I think it is in the genome wide CpG files produced by `coverage2cytosine`). Do you think this is essential, and i should be looking into this?

**Comment by jnthnhss** [comment]
Hi Felix,

Not essential, only convenient. It would allow one to take a quick look to compare a bunch of bedGraphs for simple sanity checks without parsing entire files. More important, however, might be that the documentation speaks of a sorted bedGraph, which I would have assumed implies a defined order for the chromosomes, so maybe it's enough to add a sentence to the documentation to clarify this point.

**Comment by FelixKrueger** [comment]
Hi Jonathan,

Apologies for the slow response, I am struggling a little to keep on top of things these days... I just had a quick look at `bismark2bedGraph` and added a `sort` function to the list of temp files being processed. I hope this might be sufficient to achieve a similar order for each sample. Would you like to test this by cloning the latest dev version and trying it out? Many thanks for your patience. Cheers, Felix

**Comment by jnthnhss** [comment]
Hi Felix,

Works as intended. I tested `bismark_methylation_extractor` from the latest version with .bam files from two samples and looked at three different output files (coverage file, 0-based coverage file, 0-based bedGraph) for both and they were all sorted, including chromosomes. Thank you so much for your efforts.

**Comment by FelixKrueger** [comment]
Great, thanks for the feedback! Stay safe!
