### ISSUE TITLE
Can't execute

### ISSUE THREAD

**Issue by asumann** [FelixKrueger/Bismark#326]
Can you help me figure out this error?

"Child process: Starting to index G->A converted genome with the following command:

/cta/apps/share/spack/modules/linux-ubuntu16.04-x86_64/bowtie2-build  -f genome_mfa.GA_conversion.fa BS_GA

Can't exec "/cta/apps/share/spack/modules/linux-ubuntu16.04-x86_64/bowtie2-build": No such file or directory at /cta/capps/bismark/0.22.1/bin/bismark_genome_preparation line 217, <IN> line 5359443."

Many thanks

**Comment by FelixKrueger** [comment]
Hi @asumann,

the error message is fairly clear:

"/cta/apps/share/spack/modules/linux-ubuntu16.04-x86_64/bowtie2-build": `No such file or directory`

You need to make sure that Bowtie2 is installed at exactly that location. In fact you need to be able to run that command on the command line, and see the Bowtie2-build help:

`/cta/apps/share/spack/modules/linux-ubuntu16.04-x86_64/bowtie2-build`

If that doesn't work, you either need to install Bowtie2 first, or provide the correct path Bowtie2.

**Comment by FelixKrueger** [comment]
And while you are at it, I would recommend you get the latest version, instead of 0.22.1.

**Comment by asumann** [comment]
Thanks a lot, I finally run it!

However, I got somehow low alignment(39%-50%) in my samples(MethylC-Seq, single end) in default mode. I checked previous entry, where the error was from sequencing quality. Then, I checked my fastqc after trimming, I have very low C content and around 15% of G content.  Is there a way to target higher mapping efficiency? Probably, some options help me in that, but I am not sure how. I appreciate if you can offer your suggestions.

**Comment by FelixKrueger** [comment]
Mapping efficiency is a function of several things:
- read length
- sequencing quality
- adapter/quality trimming
- genome quality
- contamination
 
The following link describes some steps you can take to ensure you've got good quality sequence. Even though it is written for paired-end libraries, most aspect also apply for SE samples. If you are struggling with the contaminants screed I welcome you to send some 100-200,000 sequences (gzip compressed), and I can take a quick look over here.
https://github.com/FelixKrueger/Bismark/blob/master/Docs/FAQ.md#issue-2-low-mapping-effiency-of-paired-end-bisulfite-seq-sample

**Comment by asumann** [comment]
Many thanks @FelixKrueger for your detailed explanations and amazing promptness.
