### ISSUE TITLE
 Failed to run Bismark tool on fasta file

### ISSUE THREAD

**Issue by mayurdoke6** [FelixKrueger/Bismark#327]
Hello,

I am trying to map bisulfite sequencing data files with the help of Bismark. I am getting an error while running this tool on command line. could you help with this issue? Thanks in advance.

 $ bismark --bowtie2 -n 1 -l 50  /scratch/user/mayurdoke/Genome2/control1.fasta
Bowtie 2 seems to be working fine (tested command bowtie2 --version [2.3.5])

Output format is BAM (default)

Alignments will be written out in BAM format. Samtools found here: /sw/eb/software/SAMtools/1.9-intel-2018b/bin/samtools

Failed to move to /scratch/user/mayurdoke/Genome2/control1.fasta/: No such file or directory

**Comment by FelixKrueger** [comment]
You need to specify a genome to align to, and then a file you want aligned. This can be accomplished with `--genome /path/to/genome`, else Bismark will use the first argument on the command line which in your case is `/scratch/user/mayurdoke/Genome2/control1.fasta`. 

If you want to align a FastA file, you also need to use the `-f` Flag. 

Alternatively, if you wanted to use the FastA file as a custom genome sequence, you need to use `bismark_genome_preparation` first.

**Comment by mayurdoke6** [comment]
Thank you very much !!!!
