### ISSUE TITLE
allc file in Bismark

### ISSUE THREAD

**Issue by asumann** [FelixKrueger/Bismark#328]
Hi Felix,

I wonder if there is 'allc file' output availability in bismark? In an analysis, it will be easier for me to start from allc. I hope somehow it can be extracted from bismark outputs.

Stay healthy!
Asuman

**Comment by FelixKrueger** [comment]
There are 3 main types of files as the output to Bismark:
1. The mapping BAM file. This file contains all alignments, and thus also all information.
2. the coverage file. This is produced by `bismark2bedGraph` and can also be gotten by `bismark_methylation_extractor`. The default is CpG context only, but using the option `--CX` you can get all contexts
3. The genome wide cytosine report generated by `coverage2cytosine`. The default is CpG mode only, but the option `--CX` will enable all contexts

All this is described in a lot of detail in the Bismark documentation (https://github.com/FelixKrueger/Bismark/tree/master/Docs), or if you type `--help` on the command line for each of the steps involved.
