### ISSUE TITLE
feature request: bismark_methylation_extractor --exclude_bed / --include_bed options

### ISSUE THREAD

**Issue by avilella** [FelixKrueger/Bismark#33]
This is a feature request against the head master version of bme.

Would it be possible to add a feature where the CpGs counts are done either excluding or including the regions given in a bed file? E.g.

```
bme $input.bam --genome_folder /my/genome.fa --exclude_bed /my/excluded.regions.from.genome.bed

or

bme $input.bam --genome_folder /my/genome.fa --includee_bed /my/included.regions.from.genome.bed
```

I guess one option is not to do this, and do a filtering step posterior to running bme, but then none of the useful metrics would in turn be reported.

Apologies if this is already an option, I couldn't see it in the code myself.

**Comment by FelixKrueger** [comment]
This option does not exist at the moment, but I am also not particularly keen to implement this right now to be honest because we can easily do the filtering in SeqMonk already. So I might keep it in mind but this won't happen anytime soon I am afraid.
