### ISSUE TITLE
Bowtie2 version dependency

### ISSUE THREAD

**Issue by elfwoz** [FelixKrueger/Bismark#330]
Hi Felix, 
I'm working in a research environment and we have various modules installed on our HPC which are under strict control. 
I'm using Bismark, but notice that it won't run with our current Bowtie2 installment (v2.4.1) as Bismark 0.22.1 has a dependency on bowtie2/2.3.4.

Are there any plans to update this so that we can run with a newer bowtie2 module without having to roll back?

Many thanks
Eva

**Comment by FelixKrueger** [comment]
Hi Eva,

I am not aware of any dependencies that are enforced by Bismark. We are currently running v2.3.5.1 ourselves, I might to go and check out the latest version....

**Comment by elfwoz** [comment]
Hi Felix,

Thanks for your quick reply.
I see the following error when I try to run Bismark with these commands:
module load bowtie2
Loading bowtie2/2.4.1
  Loading requirement: tbb/2018_U2 gcc/7.1.0 python/3.6.3
Loading samtools/1.6
  Loading requirement: htslib/1.6
module load bismark
Loading bismark/0.22.1
  ERROR: Load of requirement 'bowtie2/2.3.4' failed

I had assumed that as it mentions v2.3.4 as a requirement, that this is something bismark was driving.
Could you advise?

Many thanks,
Eva

**Comment by FelixKrueger** [comment]
I just installed Bowtie2 v2.4.1 on our cluster, and can confirm that it runs just fine with Bismark:

```
bismark --genome /bi/scratch/Genomes/Human/GRCh38 test_data.fastq 
Bowtie 2 seems to be working fine (tested command 'bowtie2 --version' [2.4.1])
Output format is BAM (default)
Alignments will be written out in BAM format. Samtools found here: '/bi/apps/samtools/1.9/bin/samtools'
...
```

At no point does Bismark enforce the version of Bowtie2, so the error message:

```
ERROR: Load of requirement 'bowtie2/2.3.4' failed
```

Seems to be something that is specific to your HPC environment, and has nothing to do with me (phew). Can you just ask your admin team to remove this restriction?

Cheers, Felix

**Comment by elfwoz** [comment]
Hi Felix,

Thanks so much for looking in to this, and sorry to have troubled you. I’ve contacted our HPC admin team to see what they’ve done here. Hopefully something silly that they can undo!

Thanks,
Eva

**Comment by FelixKrueger** [comment]
While they are at it, maybe they want to update Bismark as well... :)
