### ISSUE TITLE
genome with lots of scaffolds

### ISSUE THREAD

**Issue by asumann** [FelixKrueger/Bismark#331]
Hi Felix!

I have run a similar issue as mentioned here previously. Methylation extractor gives lots of .temp files. You suggest running bismark2bedGraph on .temp files after methyl_extractor. My confusion is I have got .temp files only for CpG_OT, but neither for other strand nor other contexts.

Also I am confused with output file name. This is a unix newbie question, but if you can offer an example command that will be very much helpful.

PS: Previously, I tried to solve the problem by excluding scaffolds(and keeping all chr only) from the .bam files prior to methyl_extractor. It works, and I got .cov files. I want to learn if that is sensible to you. What do you also think about it? Do I lots of information that way?

Thanks,

Asuman

**Comment by FelixKrueger** [comment]
This is all normal, and luckily there should be an easy fix: just specify the option `--scaffolds` and it should all run smoothly (pleas e manually delete the *temp files first). For more information on that just run bismark2bedGraph with `--help`.]

Cheers, Felix

**Comment by asumann** [comment]
Many thanks again!
