### ISSUE TITLE
coverage2cytosine

### ISSUE THREAD

**Issue by shruti3009** [FelixKrueger/Bismark#332]
Hi Felix, 
I am running bismark on my sample for a methylation study, I am having difficulty in generating CX-report using coverage2cytosine module. The trouble is that it is taking a long time, I ran the command: 
$ coverage2cytosine --CX --genome_folder /Raw_data/shruti/methylation/reference_genome/ -o ALS3_ref ALS3_deduplicated.bam
It is running since April 22 and there is zero increment happened to the file size that is generated in the output directory so far. I have killed the process twice before as it got stuck on different lines numbers earlier.

The last ten-line from the now-running screen says:
```
Use of uninitialized value within %chromosomes in pattern match (m//) at /home/ssrivastava/anaconda3/bin/coverage2cytosine line 195, <IN> line 43961119.
Writing cytosine report for chromosome �3�����k�4���
                                                     $]�K�����r�z��rsgr��X�ѕ;��a��/~�S���!����� (stored 1 different covered positions)
Use of uninitialized value within %chromosomes in pattern match (m//) at /home/ssrivastava/anaconda3/bin/coverage2cytosine line 195, <IN> line 43961120.
Use of uninitialized value $start in hash element at /home/ssrivastava/anaconda3/bin/coverage2cytosine line 383, <IN> line 43961120.
Use of uninitialized value $start in hash element at /home/ssrivastava/anaconda3/bin/coverage2cytosine line 384, <IN> line 43961120.
Writing cytosine report for chromosome e��k�{}Jf��������䡘���i
                                                                  ���e�m�JS�᣶��10u�)�hJ̪р��&�T��m��nd��^��ظ%�_QߑV�������ɇ\J��D2�I�H��X�g�lE���:��'
                                                                                                                                                          �R�%uZ���ō�Wޗ�ԫF,��L (stored 1 different covered positions)
Use of uninitialized value within %chromosomes in pattern match (m//) at /home/ssrivastava/anaconda3/bin/coverage2cytosine line 195, <IN> line 43961121.
Use of unini


```
I have run a similar command to generate CX-report for my spike-in alignment file and it happened quickly, I do understand the size of the genome was small for those runs but does coverage2cytosine should take this long for the human genome (hg19)? 

Please correct me if I am doing something wrong.

**Comment by FelixKrueger** [comment]
Hi @shruti3009,

`coverage2cytosine` requires as input file a coverage file (`.cov.gz`), and not a BAM file. Just run it through `bismark_methylation_extractor --bedGraph` first, and use the resulting coverage file as input.

Cheers, Felix

**Comment by shruti3009** [comment]
Thank you for the prompt response, Felix, I successfully ran the covergae2cytosine module.
