### ISSUE TITLE
Methylation significance

### ISSUE THREAD

**Issue by asumann** [FelixKrueger/Bismark#334]
Hi Felix,

Is there a significance test available in Bismark for methylation percentage? Or, what would you suggest to catch true methylation for each site? Cutoff option would work, I assume. But I am not sure how to set a non-arbitrary cutoff. 

Thanks,
Asuman

**Comment by FelixKrueger** [comment]
This really falls into the downstream data analysis of your data, and is beyond the scope of Bismark itself. There are many options for how to proceed from here, you can probably get an idea by looking at the material for our methylation analysis course (https://www.bioinformatics.babraham.ac.uk/training.html#bsseq), and read up on some tools like Methylkit (https://www.bioconductor.org/packages/release/bioc/html/methylKit.html).
