### ISSUE TITLE
Cytosine report file

### ISSUE THREAD

**Issue by RubioB** [FelixKrueger/Bismark#335]
Hi Felix, 

I certainly have two naive questions regarding the cytosine report obtained with the function coverage2cytosine :
- first, I do not understand why in the cytosine report we only find the identifier of a single chromosome while looking in the slurm I think that the analysis has been performed on all the chromosmes of the genome ? 
- second, does the number of Cs of the cytosine report allow us to know the number of Cs that we have in the genome ? knowing that normally it takes into account all of the Cs in the genome without taking into account the fact whether or not it is covered by reads. Is what I say right ? 

Thanks in advanced for your answer !

Bernadette

**Comment by FelixKrueger** [comment]
Regarding your first question: The analysis is performed chromosome by chromosome (as the coverage files are also sorted by chromosome), but all chromosomes are analysed.

Re 2: Yes, it processes all Cs in the reference sequence, whether or not they were covered.

Cheers, Felix

**Comment by RubioB** [comment]
Thank you for your answer !

I had badly sought my chromosome identifiers so I bothered you for nothing...sorry... So everything is very clear !

Thanks again

Bernadette
________________________________
De : Felix Krueger <notifications@github.com>
Envoyé : mercredi 29 avril 2020 07:38
À : FelixKrueger/Bismark <Bismark@noreply.github.com>
Cc : RubioB <bernadetterubio@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [FelixKrueger/Bismark] Cytosine report file (#335)


Regarding your first question: The analysis is performed chromosome by chromosome (as the coverage files are also sorted by chromosome), but all chromosomes are analysed.

Re 2: Yes, it processes all Cs in the reference sequence, whether or not they were covered.

Cheers, Felix

**Comment by FelixKrueger** [comment]
That's absolutely fine, don't worry! :P
