### ISSUE TITLE
Subsetting resulting .bam files while retaining methylation tags?

### ISSUE THREAD

**Issue by miyakokodama** [FelixKrueger/Bismark#340]
Hi,

I am new to Bismark, and I am trying to create small chromosome-specific bam files (using bam files originating from alignment with Bismark), however using `samtools view -b SAMPLE.bam NC_027300.1 chr1 > SAMPLE_Chr1.bam` seems to remove methylation tags. Do you happen to know of any tools that would allow me to subset .bam files while retaining Bismark methylation tags? 

Apologize for a newbie question, and please do not hesitate to let me know if you don't think this is a relevant question for Bismark.

Many thanks in advance!

Miyako

**Comment by FelixKrueger** [comment]
Hi Miyako,

Not exactly sure why Samtools doesn't want to do this, but I without writing a script I think your could probably use the following process:

**1. Save the SAM header only:**
```
samtools view -H SAMPLE.bam > sam_header.txt
```

**2. filter out reads that contain `chr1`** 

```
samtools view SAMPLE.bam | grep chr1 > chr1.sam
```

**3. Re-generate a BAM file** 

```
cat sam_header.txt chr1.sam | samtools view -b - > SAMPLE_chr1.bam
```

I hope this will work! For paired-end Bismark files, please make sure that you do not use samtools sort first, as this may also interfere with the order of reads...

**Comment by miyakokodama** [comment]
Hi Felix,

Thanks for the quick response and the solution - I will try that! It was also good that you pointed out not to use samtools sort because I actually did use sorted bam files to subset it to chromosomes :) Thanks again for your help!

Miyako

**Comment by FelixKrueger** [comment]
Alright, good luck! I e.g. had a report of `samtools sort` affecting non-directional reads: #295

**Comment by miyakokodama** [comment]
Thanks for the heads up, that's actually very good to know. Out of curiosity do you also happen to know if `samtools sort` may affect directional reads too? I am asking this as I am having issues with downstream analyses with sorted bam files (based on bams coming from Bismark, sorted with `samtools`) and am currently trying to troubleshoot.

**Comment by FelixKrueger** [comment]
I don't think it does to be honest, but we have noticed only last week that when you re-sort position sorted BAM files by name, it will sort them with FLAG values from low to high - which in the case of complimentary reads (CTOT and CTOB) changes their read-order in the resulting file (bad bad Samtools! :)).

But couldn't you quickly do the following:
take two read pair alignments, one with an OT and one with and OB alignment, then sort by position, and then re-sort by name (`samtools sort -n`). Ideally the pos->name sorted file should be identical to the initial file. Does that make sense?

**Comment by miyakokodama** [comment]
Yes it does make sense - I will definitely give it a try and check, it would be good to know if samtools sort is the one messing with the downstream analyses. Thanks again for your quick response - it is really helpful! :)
