### ISSUE TITLE
How to convert the methyl-extract output to gff3?

### ISSUE THREAD

**Issue by ofirgriess** [FelixKrueger/Bismark#341]
Hey!
I'm a beginner bioinformatician. How do I convert the output of the methyl-extractor to a gff format?
What really is the output of the methyl-extractor?

**Comment by FelixKrueger** [comment]
The initial output of the mehylation extractor is described here: https://github.com/FelixKrueger/Bismark/tree/master/Docs#iv-bismark-methylation-extractor

You can then also proceed to processing this further to a coverage file (https://github.com/FelixKrueger/Bismark/tree/master/Docs#optional-bedgraph-output) or the genome-wide cytosine report (https://github.com/FelixKrueger/Bismark/tree/master/Docs#optional-genome-wide-cytosine-report-output). I am not sure what you want to do with a gff file, but here is a link to our methylation analysis course material: https://www.bioinformatics.babraham.ac.uk/training.html#bsseq

**Comment by ofirgriess** [comment]
Thank you!
