### ISSUE TITLE
Online documentation --local

### ISSUE THREAD

**Issue by StevenWingett** [FelixKrueger/Bismark#342]
It would be nice to mention the Bismark --local option in the online documentation at: 
https://rawgit.com/FelixKrueger/Bismark/master/Docs/Bismark_User_Guide.html

Thanks.

**Comment by FelixKrueger** [comment]
Fair enough, apparently `--local` mode is currently only mentioned in the Release Notes and Changelog files, e.g. here: https://github.com/FelixKrueger/Bismark/tree/0.22.0

**Comment by FelixKrueger** [comment]
The online [documentation](https://github.com/FelixKrueger/Bismark/blob/master/Docs/README.md) does now feature a description of `--local` mode. I will try to also update the html User Guide for the next release.
