### ISSUE TITLE
coverage2cytosine

### ISSUE THREAD

**Issue by rafaelsb-1** [FelixKrueger/Bismark#343]
Hello, I'm trying to run or coverage2cytosine module, however I have the following error "Use of uninitialized value within% chromosomes in pattern match (m //) at ./coverage2cytosine line 195, <IN> line 209955" and it persists in the others lines. In the end my file has values of 0 where it was supposed to have values of cap. My input file is cov.gz

**Comment by FelixKrueger** [comment]
This type of error usually occurs when the coverage file is either corrupted, or completely empty. Is that a possibility? You could test this with a command like:

```
gzip *cov.gz | tail
``` 

In case the coverage file is empty, are you using a genome that is mainly made up of contigs or scaffolds? In this case, you might have to use `--scaffold` when running the methylation extractor or `bismark2bedGraph`. I am obviously just guessing here... Let me know how you get on.

**Comment by rafaelsb-1** [comment]
Ola, obrigado pela resposta rapida. Eu digitei o camando em minha linha de comando e a saida é esta:
-bash-4.2$ gunzip -c *cov.gz | tail
chrY     90826248        90826248       100     3       0
chrY     90826210        90826210       100     3       0
chrY     90828181        90828181       0       0       1
chrY     90828198        90828198       100     1       0
chrY     90828226        90828226       100     1       0
chrY     90828859        90828859       0       0       8
chrY     90828848        90828848       100     8       0
chrY     90828872        90828872       100     8       0
chrY     90828846        90828846       0       0       8
chrY     90828880        90828880       100     8       0

I think the file is correct, could it be some incompatibility with the genome I'm using for reference?

**Comment by FelixKrueger** [comment]
Hi @rafaelsb-1 

The file looks fine indeed. You definitely need to use the same genome for this step. E.g. the Ensembl genomes do not use the `chr` notation at the start of each chromosome, and use `MT` instead of `chrM`. So you might want to get the hold of the same genome you used for the alignment step.

Was your initial reply in Portuguese? I think I would just about have gotten the message anyway!

**Comment by rafaelsb-1** [comment]
Thank you! I think this may be the problem, yes it was in Portuguese, my fault. The chromosome annotations are the same however there may be incompatibility in the genome size within other possibilities. Thanks again for the help!

**Comment by FelixKrueger** [comment]
Alright, best of luck!

**Comment by rafaelsb-1** [comment]
The error problem was solved with the correct genome, but I still get zero values where it was to have the non-methylated and methylated ones.
chr1    3000827 +       0       0       CG      CGT
chr1    3000828 -       0       0       CG      CGG
chr1    3001007 +       0       0       CG      CGG
chr1    3001008 -       0       0       CG      CGA
chr1    3001018 +       0       0       CG      CGT
chr1    3001019 -       0       0       CG      CGG
chr1    3001277 +       0       0       CG      CGA
chr1    3001278 -       0       0       CG      CGA
chr1    3001629 +       0       0       CG      CGT
chr1    3001630 -       0       0       CG      CGG
chr1    3003226 +       0       0       CG      CGG
chr1    3003227 -       0       0       CG      CGC
chr1    3003339 +       0       0       CG      CGC
chr1    3003340 -       0       0       CG      CGG
chr1    3003379 +       0       0       CG      CGT
chr1    3003380 -       0       0       CG      CGA

I'm running the following command: ./coverage2cytosine --gzip --genome_folder ./ Sample_1364.cov.gz -o the test

**Comment by FelixKrueger** [comment]
The output of coverage2cytosine writes out one line for every position in the genome, regardless of whether it is covered by a call in your coverage file. As a test you could grep for a position in the coverage file, e.g.:

```
gunzip -c *cov.gz | grep 90826248
```
Should give you this output file:
```
chrY 90826248 90826248 100 3 0
```

If you don't want to include uncovered positions, you could use the following coverage2cytosine option (latest version required I think):
```
--coverage_threshold INT   Positions have to be covered by at least INT calls (irrespective of their methylation state) before
						 they get reported. For NOMe-seq, the minimum threshold is automatically set to 1 unless specified explicitly.
						 Setting a coverage threshold does not work in conjunction with --merge_CpGs. Default: 0 (i.e. all genomic positions get reported).
```

**Comment by rafaelsb-1** [comment]
I typed the command line and got the following result:
-bash-4.2 $ gunzip -c * cov.gz | grep 90826248
chrY 90826248 90826248 100 3 0

Quando eu uso essa opção =1 eu tenho valores em meu arquivo só que não batem com a posiçao do arquivo de cobertura por exempo:
chr1    100000477       +       2       3       CG      CGG
chr1    100006217       -       0       7       CG      CGT
chr1    100037673       +       2       0       CG      CGT
chr1    100052846       -       4       4       CG      CGC
chr1    100052893       -       8       0       CG      CGG
chr1    100054668       +       3       0       CG      CGC
chr1    100054883       -       9       0       CG      CGG
chr1    100055026       -       129     53      CG      CGG
chr1    100055043       -       19      0       CG      CGG
chr1    100135395       -       10      0       CG      CGC
chr1    100135407       -       10      0       CG      CGG
chr1    100138692       -       27      7       CG      CGC
Porém isso nã se parece com meu arquivo de entrada nas posições:

chr1      3003721         3003721       100     10      0
chr1      3007581         3007581       100     20      0
chr1      3007430         3007430       5.556   1       17
chr1      3014974         3014974       100     1       0
chr1      3020972         3020972       49.468  93      95
chr1      3021025         3021025       100     2       0
chr1      3021012         3021012       100     2       0
chr1      3027514         3027514       0       0       2
chr1      3037279         3037279       100     8       0
chr1      3054744         3054744       100     2       0
chr1      3058614         3058614       0       0       1
chr1      3061686         3061686       100     1       0
chr1      3062687         3062687       27.273  3       8
When I do this with the pattern the positions are ok but everything with zero instead of having something

**Comment by FelixKrueger** [comment]
Something is odd... So are you saying that you see positions in the cytosine report that have 0 / 0 calls, and you feed it a coverage file where that very position had several calls? Are you using something like `--zero` or something? If you keep seeing this, could you send me the coverage file (or e.g. only one chromosome of the coverage file), and the genome you are using for a test?

**Comment by rafaelsb-1** [comment]
Hello, yes, I see several calls in my cov file and those calls are not in my cytosine report. I was trying with the --zero option and a few others, but everything remains the same. I will send my files to you. Thanks again for all the attention!
