### ISSUE TITLE
Randomly assigning multiply mappable reads to one of mappable sites. And subsequent quantification

### ISSUE THREAD

**Issue by phytomind** [FelixKrueger/Bismark#344]
Dear Felix,

I recently began analyzing bisulfite sequencing data without much background of experience.
I'm focusing on analyzing DNA methylation of repetitive elements in human genome like transposable elements and tandem satellite repeats.
And my question is...
Is there a way that I can assign multiply mappable BS-seq reads to one of their mappable sites in a random manner, followed by quantitative analysis for repetitive sequence?
In RNA-seq analysis, it was easy to do it using Homer software resulting in a reasonable quantification of repetitive sequence transcripts.
But bismark seems to exclude such multiple-mapped reads or I don't find how to analyze them.
Also it will be greatly appreciated if you can give me any advice about downstream quantitative analysis for those repetitive sequence-matched reads.
Currently I'm using MethylKit.

Thank you so much!

Jinkil

**Comment by FelixKrueger** [comment]
Hi Jinkil,

You are correct in assuming that multi-mapping reads are removed during standard Bismark runs, and there currently is no capacity to allow it map reads to a position at random. 

What we have done in the past to get round this issue with repetitive elements is to make special  short repeat-genomes by using just a consensus sequence for a certain repeat class or family, such as ERV, L1, SINE, Satellites, LTR etc. The consensus sequences were often downloaded from Repase. From a technical point of view you would just take the `.fa` sequences of these repeat consensus (just make sure they are not self-repetitive), run `bismark_genome_preparation` on them, and then use this new genome for the alignments.

We personally use SeqMonk for the downstream analysis, you can simply use the same .fa sequences to make custom chromosomes (corresponding to one repeat consensus each), and then use the usual arsenal of SeqMonk to do the analysis (see [here](http://www.bioinformatics.babraham.ac.uk/training.html#bsseq) for more).

**Comment by phytomind** [comment]
Thank you so much for great answers, Felix!
I wonder how you dealt with sequence deviation of repetitive elements if you were careful about it.

**Comment by phytomind** [comment]
Thanks a lot for your comments! :)
