### ISSUE TITLE
can ambiguous bam file show XR or XG?

### ISSUE THREAD

**Issue by jeongmeani** [FelixKrueger/Bismark#346]
Hi, 
these days, i analysis ampliseq data and count a number of bases of target region.
but many of the reads to be considered as target are mapped to ambiguous bam file.

and i want to divide watson and crick strand using XG information. but ambiguous bam file does not provide it.
so how can i check this?

Best Regards
Jeongmin

**Comment by FelixKrueger** [comment]
Hi Jeongmin,

I think reads that are reported to the ambiguous BAM files have their mapping information directly relayed from the Bowtie2 or HISAT2 alignment, and as such they are the missing the XR or XG tags. I suppose it could potentially be added, but I think in the short term it might be easier if you would try to align the sequences to a reference that is not self-similar (just for these counting purposes). So if you have an amplicon, just use that sequence for the alignments for the classification, does that make sense?
