### ISSUE TITLE
methylation extractor output with fragment insert size

### ISSUE THREAD

**Issue by lemon027** [FelixKrueger/Bismark#348]
1. seq-ID
2. methylation state
3. chromosome
4. start position (= end position)
5. methylation call

may I have the insert size column?

**Comment by FelixKrueger** [comment]
The insert size of a single base of cytosine is: 1

That's why the start and end position are the same.

**Comment by lemon027** [comment]
I mean the pair end fragment size

**Comment by FelixKrueger** [comment]
Apologies for closing the issue so quickly, I din't mean to be rude... :) I am afraid the insert size of a paired end fragment is beyond the scope of the methylation extractor out out. If you wanted to add that you would have to write a script that processes the BAM file and methylation call files at the same time, and add this as a new column. Does that make sense?

**Comment by lemon027** [comment]
Thanks for your suggestion!  I might not describe the issue clearly~
I just want to integrate bismark to my own pipeline without reading BAM  multiple times. 

Thanks again for your prompt reply

**Comment by FelixKrueger** [comment]
I am afraid there is no current solution for this (and I wonder why would you need to know the insert size length at this stage?). Therefore, your only options would be to modify the code for the methylation extractor directly to output this information, or write a quick script that would post-process the CpG* and BAM files (which is probably much easier if you have enough RAM available).

**Comment by lemon027** [comment]
I will try to modify the code for the methylation extractor first. I will also explain why I need this feature after I cite your paper(maybe later this year)

**Comment by FelixKrueger** [comment]
Excellent, looking forward to learning more about it! Good luck!
