### ISSUE TITLE
annotation of C in CTOT and CTOB query

### ISSUE THREAD

**Issue by prasundutta87** [FelixKrueger/Bismark#350]
Hi Felix,

Hope you are doing well in the new normal. Just wanted to confirm if the positions of methylated C’s are annotated in the same way for CTOT and CTOB strands as they are done for OT and OB strands respectively? I am asking this because I am aiming to only use reads aligned to only CTOT and CTOB strands and will process it in the same way as I would have processed reads aligned to OT and OB strands. At one glance, it does, but just wanted to be sure if there should be any change on the downstream processing-

OT
track type=bedGraph
chr17	2796309	2796310	100

CTOT
track type=bedGraph
chr7	2614638	2614639	0

Regards,
Prasun

**Comment by FelixKrueger** [comment]
Hi Prasun

The positions for OT and CTOT, as well as for OB and CTOB, should be exactly the same. You should be able to find cytosines at those positions for the top strand or bottom strand, respectively, if you were looking on a genome browser such as Ensembl or UCSC.

**Comment by prasundutta87** [comment]
Thanks a lot, Felix!
