### ISSUE TITLE
Inputting genome-aligned bam file that lacks methylation call?

### ISSUE THREAD

**Issue by phytomind** [FelixKrueger/Bismark#351]
Hi Felix,

I was trying to analyze RRBS data from CCLE project.
(https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6697103)
Broad institute has uploaded its analyzed data focusing on gene promoters.
But I wanted to analyze its genome-wide methylation pattern.
So I needed to begin from more raw data and I found they deposited BAM data in SRA format in NCBI SRA (I thought this bam data is a typical bismark output because they said they mapped using bismark 0.7.12 according to Methods section of the above linked paper).
An example of U2OS cell line is linked here.
https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR8633329
However, after I converted the downloaded SRA file to BAM by using sam-dump and samtools,
I realized this BAM file is aligned to hg19/GRCh37 but missing methylation call information (like below).
```
[jjeong@igc4 Sarcoma]$ samtools view U2OS.bam | head -10
1       0       1       10497   0       29M     *       0       0       TGGGTTTGATTTGAGGAGAATTGTGTTTT   @@@ADDDD<DBFFAFG3?<CFBHHGFHCE   RG:Z:C25NT.2    NH:i:1  NM:i:8
2       0       1       10497   0       29M     *       0       0       TGGGTTTGATTTGAGGAGAATTGTGTTTT   BBCFDDFFHHHHHIIIDHEHIJJHIGHIJ   RG:Z:C25NT.2    NH:i:1  NM:i:8
3       0       1       10497   0       29M     *       0       0       TGGGTTTGATTTGAGGAGAATTGTGTTTT   @@@DDDDD<FHHH4EHAFBGHIIHHIIII   RG:Z:C25NT.2    NH:i:1  NM:i:8
4       0       1       10497   0       29M     *       0       0       TGGGTTTGATTTGAGGAGAATTGTGTTTT   BBBFDDFFHHHHGIGIDGGHIJJFHHHIJ   RG:Z:C25NT.2    NH:i:1  NM:i:8
5       0       1       10497   0       29M     *       0       0       TGGGTTTGATTTGAGGAGAATTGTGTTTT   BBBFDDFFFHHHHHIJHG@FHIJHHHIJJ   RG:Z:C25NT.2    NH:i:1  NM:i:8
6       0       1       10497   0       29M     *       0       0       TGGGTTTGATTTGAGGAGAATTGTGTTTT   @@CFBDDFDHHHHBGHEHACFHIFHFHIJ   RG:Z:C25NT.2    NH:i:1  NM:i:8
7       0       1       10497   0       29M     *       0       0       TGGGTTTGATTTGAGGAGAATTGTGCTTT   @@CFDDDDDHHHHGIGBGA?FHHFBGIJJ   RG:Z:C25NT.2    NH:i:1  NM:i:7
8       0       1       10497   0       29M     *       0       0       TGGGTTTGATTTGAGGAGAATTGTGTTTT   ?@@FABDFBFHHHFHE@FA?CHGCEHIJJ   RG:Z:C25NT.2    NH:i:1  NM:i:8
9       512     1       10497   0       29M     *       0       0       TGGGTTTGATTTGAGGAGAAGTGGGTTTT   5<<@@@@9.><98)=4>((..@?)@(=5@   RG:Z:C25NT.2    NH:i:1  NM:i:9
10      0       1       10497   0       29M     *       0       0       TGGGTTTGATTTGAGGAGAATTGTGTTTT   @BCFDDFFHHHHHHIJFHFGHIJHHHIJJ   RG:Z:C25NT.2    NH:i:1  NM:i:8
[jjeong@igc4 Sarcoma]$ samtools view -H U2OS.bam | head -10
@HD     VN:1.4  GO:none SO:coordinate
@SQ     SN:1    LN:249250621    UR:http://www.broadinstitute.org/ftp/pub/seq/references/Homo_sapiens_assembly19.fasta   AS:GRCh37       M5:1b22b98cdeb4a9304cb5d48026a85128     SP:Homo Sapiens
@SQ     SN:2    LN:243199373    UR:http://www.broadinstitute.org/ftp/pub/seq/references/Homo_sapiens_assembly19.fasta   AS:GRCh37       M5:a0d9851da00400dec1098a9255ac712e     SP:Homo Sapiens
@SQ     SN:3    LN:198022430    UR:http://www.broadinstitute.org/ftp/pub/seq/references/Homo_sapiens_assembly19.fasta   AS:GRCh37       M5:fdfd811849cc2fadebc929bb925902e5     SP:Homo Sapiens
@SQ     SN:4    LN:191154276    UR:http://www.broadinstitute.org/ftp/pub/seq/references/Homo_sapiens_assembly19.fasta   AS:GRCh37       M5:23dccd106897542ad87d2765d28a19a1     SP:Homo Sapiens
@SQ     SN:5    LN:180915260    UR:http://www.broadinstitute.org/ftp/pub/seq/references/Homo_sapiens_assembly19.fasta   AS:GRCh37       M5:0740173db9ffd264d728f32784845cd7     SP:Homo Sapiens
@SQ     SN:6    LN:171115067    UR:http://www.broadinstitute.org/ftp/pub/seq/references/Homo_sapiens_assembly19.fasta   AS:GRCh37       M5:1d3a93a248d92a729ee764823acbbc6b     SP:Homo Sapiens
@SQ     SN:7    LN:159138663    UR:http://www.broadinstitute.org/ftp/pub/seq/references/Homo_sapiens_assembly19.fasta   AS:GRCh37       M5:618366e953d6aaad97dbe4777c29375e     SP:Homo Sapiens
@SQ     SN:8    LN:146364022    UR:http://www.broadinstitute.org/ftp/pub/seq/references/Homo_sapiens_assembly19.fasta   AS:GRCh37       M5:96f514a9929e410c6651697bded59aec     SP:Homo Sapiens
@SQ     SN:9    LN:141213431    UR:http://www.broadinstitute.org/ftp/pub/seq/references/Homo_sapiens_assembly19.fasta   AS:GRCh37       M5:3e273117f15e0a400f01055d9f393768     SP:Homo Sapiens
[jjeong@igc4 Sarcoma]$
```
So I'm pretty confused what to do with this BAM.
I gave bismark_methylation_extractor a shot but doesn't work with it.
Is there a way I may possibly "reconstruct" the methylation call part of this BAM file?

What I just tried separately, I converted the same SRA to fastq by using fastq-dump instead of sam-dump.
Then went through Trim_Galore! trimming with RRBS parameter followed by bismark alignment to GRCh37 reference which ends up ~50% mapping efficiency.
And downstream results look reasonable when compared to my own bisulfite-seq for the same cell line.
But it feels like I'm wasting the other half of the data by doing this.
So just wondered if you have any idea what to do with this BAM file.

Thank you!

**Comment by FelixKrueger** [comment]
Hi @phytomind 

If I were you I would definitely not use any submitted BAM files, especially not if they were aligned with a Bismark version that is probably 8 years old...

So extracting the FastQ files via `fastq-dump` is the way to go. Is it really true that the reads are only 29bp long? If that is really the case then a mapping efficiency of 50% is a very good result in my opinion. With modern say 100bp reads you might get up to 70-80% against he human (GRCh38) genome, but with reads that short I wouldn't be surprised. 

Something else you might want to consider is that for RRBS libaries sequencing facilities frequently spiked in an increased amount of PhiX sequences to counteract the biased sequence composition of RRBS data. You might want to align this data to the PhiX genome (just say 1 million reads using -u 1000000), which would tell you if another 10-20% are actually spiked-in PhiX reads.

If you keep having issues I can also take a quick look myself (if I can get hold of FastQ files somehow).

**Comment by phytomind** [comment]
Thank you for super quick answers!

Surprisingly, the read length was only 29 bp. And the high mapping efficiency despite the short length is probably because this data is something that was already somehow mapped to hg19 once before probably by bowtie. And it seems like they didn't have phiX reference when they did mapping, according to the full header list of the bam.
But I'm so glad to hear that you think positively about converting it to fastq and doing all again. It helps me have confidence at what I'm doing.

Thanks!
