### ISSUE TITLE
Output name from Read 1 file name ? 

### ISSUE THREAD

**Issue by jeongmeani** [FelixKrueger/Bismark#355]
Hi, Felix

i get a trivial question.

when bismark run with pair, the output name is determined from R1 data?

i run pair read like -1 test.R1.trimmed.fastq.gz test.R2.trimmed.fastq.gz, 
and output is 'test.R1.trimmed_bismark_hisat2_pe.bam'

Best Regards.

Jeongmin

**Comment by FelixKrueger** [comment]
The answer is: yes.

Mapping of single-end or paired-end results in a single BAM file, so we took the decision to derive the name from the Read 1 file (you could also use `--basename` to change this name).
