### ISSUE TITLE
deduplicate_bismark removing over 50% of the reads from bam

### ISSUE THREAD

**Issue by npatel22526** [FelixKrueger/Bismark#356]
Hello, 

I am trying to analyze some samples sequenced using "TruSeq Methyl Capture Epic" library.  However, after running the  deduplicate_bismark step I am loosing over 50% the reads. In some samples, as many as 70% of the reads were removed. I later learned from the manual that for target enrichment analysis, the duplication step should be avoided, but I am still little concerned if such as high duplication levels indicate any issue with the data? or this is expected behavior. 

Best, 
Nick

**Comment by FelixKrueger** [comment]
Hi Nick,

Generally, duplication is generally a function of
- how diverse your library is
- how deep you are sequencing (i.e. number of reads), and
- whether your reads are single-end or paired-end (single-end alignments are only deduplicated on the start positions, whereas PE alignments are deduplicated on both start and end position)

The diversity of the library, i.e. the number of different unique fragments in a library, can be substantially lower if the library is degraded (e.g. harsh bisulfite treatment), or, and this might apply to your sample, if you used a capture system that only pulls down a reduced representation of the genome. If you only look at say 1% of the genome, but still sequence very deeply you are bound to start sequencing the same fragments again. If this is the case, you can't tell the difference between PCR duplicates of the same fragments, or genuine fragments that just happen to come from the same region (albeit from a different cell or allele in the pool of DNA). Unless you are using UMIs there is no way for you to discriminate these two cases.

So yea, depending on the size of the pulled down regions, and your sequencing depth, I wouldn't be surprised to get duplication rates in the region of 50-70%. As a comparison, RRBS libraries are typically 90-95% duplicated... If you wanted to you could analyse the data deduplicated and not deduplicated, and then compare if this has any effect on the results downstream....

**Comment by npatel22526** [comment]
This is really helpful. Thank you for the quick response.
