### ISSUE TITLE
Does the mbias plot include pair overlaps

### ISSUE THREAD

**Issue by KerstenBreuer** [FelixKrueger/Bismark#359]
Hi @FelixKrueger,

I have quick question:

Do the statistics presented in the mbias plots (and the counts in the corresponding txt) include calls on read 2 that are overlapping with read1 or are they excluded (as they are for the final bedgraph output)?

I hope my question is clear, if not please let me know.

Thanks a lot and best wishes,
Kersten

**Comment by FelixKrueger** [comment]
Hi Kersten,

If you `--no_overlap` is specified (which is the default), then the M-bias does not reflect calls from overlapping regions. I believe there is an option `--include_overlap`, in which case it should reflect all calls.

I think there is also an option `--mbias_only` in case you wanted to test out whether there is a difference.

**Comment by KerstenBreuer** [comment]
Wow that was fast. Thanks a lot that's the behavior I was expecting. I just wanted to double check.

Thanks and best wishes, 
Kersten
