### ISSUE TITLE
Error with methylation_extractor when plot M-bias plot

### ISSUE THREAD

**Issue by gsmzxc** [FelixKrueger/Bismark#36]
Hi,

I am working on bisulfite data, and meet some error when I run Bismark_methylation_extractor from Bismark 0.15.0.

I am wondering whether you could give me some advice about it.

Everything was fine and I got gzip output about methylation location and number or methylated reads.  Then when it was going to plot M-bias plot, it just stopped. I paste the error message here.

Determining maximum read lengths for M-Bias plots
Maximum read length of Read 1: 100
Maximum read length of Read 2: 100

/usr/bin/perl: symbol lookup error: /home/groups/apps/perllib/perl-5.16.1/lib/perl5/x86_64-linux-thread-multi/auto/GD/GD.so: undefined symbol: Perl_xs_apiversion_bootcheck
samtools: writing to standard output failed: Broken pipe
samtools: error closing standard output: -1

At first, I think it is some problem with the newest samtools (1.3), since they changed the way we use samtools sort command.  But I also tried samtools 1.2 and still got the same error. Is it caused by perl? Do I need to try older version of samtools and check?

The command I used (I didn't sort the bam file form bismark_align, just change the file name):

bismark_methylation_extractor -p --bedGraph --counts --cytosine_report --comprehensive --gzip  --genome_folder ../bismark_genome_index/ -o ../bismark_methylation_extract/ C12.bam

bismark --bowtie2 ../bismark_genome_index -1 ../trimmed_fastq/C12.R1.paired.fastq.gz -2 ../trimmed_fastq/C12.R2.paired.fastq.gz -o ./

Thanks,
Guang

**Comment by s-andrews** [comment]
That's a problem with your perl GD module.  Given that the error is for an internal perl symbol my guess would be that you built GD under a different version of perl than you're trying to use to run it.
I guess the fix would be to either switch back to the original version of perl used to build GD, or reinstall the GD module using your current perl version.
