### ISSUE TITLE
Best practices for processing Lamda Phage unmethylated control data with Bismark?

### ISSUE THREAD

**Issue by naumenko-sa** [FelixKrueger/Bismark#361]
Hi Felix!

Not an issue, but I (and I hope many other users) would highly appreciate your recommendations on how to process L phage genome control WGBS data with Bismark.

One of the solutions would be to generate a combined human + phage reference genome. But in that case, % methylated for a human sample would be altered with totally unmethylated L phage reads.

Running all the reads in a sample vs L phage genome sounds more reasonable, but it also will take time (or is it very fast?).

To reduce running time, I'd think to align reads first to the human genome only, filter unaligned reads, and align them to the L phage genome.

Could you please share your best practices on how did you processed L phage control data?

Thanks!

Sergey

**Comment by FelixKrueger** [comment]
Hi Sergey,

As you pointed out already, you do indeed have several options here. 

- You could add the Lambda phage DNA sequence as an additional chromosome for the mapping, but this would require and additional indexing step, and would indeed also influence the overall averages that are reported in the mapping report. You could afterwards separate out the Lambda reads (e.g. using `grep`), to get around this 'issue'
- alternatively, you could do the human mapping first, and then take the trimmed file (probably R1 is fine if the data is paired-end), and align it to a separate Lambda genome. These alignments are super fast, in the regions of several hundred million alignments/h. I don't think that you really need to filter for unmapped reads first as it is so quick anyway.

Lastly, I thought I would mention that some people described issues with efficient bisulfite conversion of Lambda DNA, similar to what has been described for the chr MT: https://www.frontiersin.org/articles/10.3389/fgene.2017.00166/full. This might be useful for the downstream interpretation fo your data.

Hope this helps!

**Comment by naumenko-sa** [comment]
Thanks, Felix!

We created a Lamda genome and ran Bismark pipeline in bcbio starting after trimming step
with 4/2/30G. It finished in 3h-19h for different samples (different nodes on a cluster have different performance).
None failed.

Sergey

**Comment by hchetia** [comment]
Hi @FelixKrueger 
I am also going to follow the separate genome alignment procedure for assessing my spike in lambda genome's conversion.
How can I assess the conversion rate of the control and compare to that of my actual sample?

regards,
hasna

**Comment by FelixKrueger** [comment]
Hi @hchetia, 

Yes, that't the idea behind it. As has been pointed out above and elsewhere, the spike-in control doesn't necessarily behave as a perfect control, but it is certainly worth checking!
