### ISSUE TITLE
bismark2report empty files error

### ISSUE THREAD

**Issue by grexor** [FelixKrueger/Bismark#362]
Hello Bismark developers, great work!

I am running bismark2report and get this error on some of the files:

`Can't use an undefined value as an ARRAY reference at bismark2report line 925, <MBIAS> line 5604.`

I see this happening with empty PE_report.txt, pe_splitting_report.txt, pe.M-bias.txt files (some or all?).

Would it be possible for bismark2report to detect this and not crash and stop reporting (I have several files in the same folder).

Thanks,
Gregor

**Comment by FelixKrueger** [comment]
Hi Gregor,

This does indeed sound like something that shouldn't be happening, these days you often have so many samples that something is bound to wrong at some point, I have already started an issue for bismark2summary for empty reads [here](https://github.com/FelixKrueger/Bismark/issues/315) for a similar issue... Would you mind bundling up one example of failing reports and send it to me via email? I am currently on annual leave, but I could look at it once I am back.

So I am afraid for the moment you would have to move empty files (e.g. based on very small size of BAM files) to an 'exclude' folder...

**Comment by grexor** [comment]
Thank you Felix, yes moving the empty files works ok, I think it's an OK fix for now, wish you a nice vacation, Gregor
