### ISSUE TITLE
M-bias plot of WGBS data

### ISSUE THREAD

**Issue by frylhc** [FelixKrueger/Bismark#363]
Hi Dr Frueger, I am analyzing WGBS data recently. After aligning, deduplicating and extracting DNA methylation infromation, I got a   M-bias plot using bismark2report. What confuses me is that while M-bias plot of read1 looks less fluctuating and normal, that of read 2 differs greatly, and the line of CHH methylation ratio in read 2 dropped steeply from over 60% to less than 20 percent. I wondered the reason why the M-bias plot in read 2 differs greatly with that of read 1? I have already trimmed raw data using trimmomatic, and the fastqc results of trimmed files looks fine. Besides, for all the raw data I got, fastqc results of read 2 is worse than read 1, this has pullzed me for several weeks，I wondered if you know the answer. Many thanks to you.
![M-bias plot of read 1](https://user-images.githubusercontent.com/68120639/89158551-e3b51300-d5a0-11ea-81ef-629c7880298b.png)
![M-bias plot of read 2](https://user-images.githubusercontent.com/68120639/89158562-e7489a00-d5a0-11ea-98e4-201e57d8e962.png)
![raw data fastqc read 1](https://user-images.githubusercontent.com/68120639/89158564-e7e13080-d5a0-11ea-8ef7-556216d0b656.png)
![raw data fastqc read 2](https://user-images.githubusercontent.com/68120639/89158568-e9125d80-d5a0-11ea-99fd-5a732884f504.png)

**Comment by FelixKrueger** [comment]
Hi @frylhc 

Luckily I think the answer to this one should be fairly easy: The M-bias plots have a dual axis, where the bold lines are the methylation percentages (which in CHH context are pretty much 0% throughout both R1 and R2). The light lines are the number of calls in each context. So what the graph means is that the number of calls at each position in R2 stat at around 0.6M. and tail off to around 0.2M, mainly as a consequence of overlapping reads (the overlapping parts of R2 get ignored).

It is true though that the qualities of R2 are poorer, but this is a rather common feature of Illumina sequencing. What is a little bit more worrying is that the CpG methylation of R2 starts at a little under 20%, and then 'creep up' to the level you see in R1. This is also quite typical for R2s, and also depends on the type of library preparation you performed.

Overall I would say: don't worry, it looks all fine! :)

**Comment by frylhc** [comment]
Thank you for your explanation, Dr. This has solved my puzzle. Best wishes.

**Comment by FelixKrueger** [comment]
Sorry I seem to have missed your latest comment, but yes, you are right in that overlapping calls will not be included in the M-bias plots.
