### ISSUE TITLE
bismark files for deconvseq blood composition analysis

### ISSUE THREAD

**Issue by lc716** [FelixKrueger/Bismark#365]
Dear Felix,

Thanks for your great work with bismark. I got some data on blood samples using RRBS and performed the trimming with Trimgalore, alignment/methylation extraction with bismark, did DMR analysis with methylkit and all worked well. 
I now want to check if i can get any info on the blood cell type composition  using a package called deconvseq. 
https://github.com/rosedu1/deconvSeq
The developer says in their description that their package can read bismark coverage files with the following headings:

chrBase, chr, base, strand, coverage, freqC, freqT.

However none of the files i get from bismark (cov, coverage2cytosine report and all other methylation extraction) have the following info in one file. Is there an option to get all these headings in one file? I also raised this with the deconvseq developers.

Thanks so much for all your work, Leo

**Comment by FelixKrueger** [comment]
Hi Leo,

I am afraid there is no specific file to convert the Bismark formats to all sorts of arbitrary formats right now, even though pretty much all of the required information seems to be contained within the genome-wide CpG-report (the output of `coverage2cytosine`). So you could either write a very small script, or possibly even a sed/awk one-liner, or indeed see if there is some kind of conversion script that comes with deconvSeq.
