### ISSUE TITLE
Indexing and alignments - Variants Called

### ISSUE THREAD

**Issue by MMG9** [FelixKrueger/Bismark#366]
We have are performing amplicon Next Gen sequencing of Bisulfite converted DNA. We are interested in the methylation status at the CpG sites in our region of interest. For our analysis, we first perform QC, then align the sequences in Bismark with HISAT2. We then use Samtools/BCFtools to perform mpileup and generate a VCF file. I'm curious about the resulting data in the columns RefF, RefR, AltF, AltR.  My initial understanding of these was the following: 

Starting sequence - wild type not converted
Strand A
Strand B (reverse complement to strand A)

Bisulfite convert DNA
- Converted Strand A
 -Converted Strand B

RefF = bisulfite converted strand A  with full methylation of CpGs. 
RefR= Bisulfite converted strand A with no methylation at CpG sites, or alternate allele
AltF = bisulfite converted strand B  with full methylation of CpGs. 
AltR= Bisulfite converted strand B with no methylation at CpG sites, or alternate allele

However, I just had a set of data where part way through the region of interested, the variants switches columns. Here it seems as though the variants are being read from the forward strand (or read 1) and then halfway through switches to call variants from the reverse strand (or read 2).  I understand why this would happen, but the columns the data are reported in do not align with what I was originally thinking the columns meant. Could you provide some further clarification?  I've attached an example of what I'm referring to. 

![Capture (2)](https://user-images.githubusercontent.com/69982751/90806786-1ff7ab80-e2e3-11ea-8539-d5c7b5ee9a5f.PNG)

Thank you in advance for any clarification you can provide.

**Comment by FelixKrueger** [comment]
Closing this as there was no further interaction.
