### ISSUE TITLE
Error in bismark_genome_preparation of Human Genome 

### ISSUE THREAD

**Issue by OrangeLuis97** [FelixKrueger/Bismark#369]
Hi everyone, 

I'm working on a project which the aim is to create a pipeline for the differential methylation analisys and I'm using bismark for several steps of this analisys. 

In genome preparation step I'm trying to use different genome downloaded from iGenomes site
-GRCh38 from NCBI
-GRCh37 from Ensembl

but in both cases i figured out the same problem. 
I use the command ./bismark_genome_preparation followed by the path of the folder containing the fastA file of the whole genome: 
-genome.dict
-genome.dict.old
-genome.fa
-genome.fa.fai
-GenomeSixe.xml
-GenomeSize.xml.old

**but the output is always the same**

Writing bisulfite genomes out into a single MFA (multi FastA) file

Bisulfite Genome Indexer version v0.22.3 (last modified: 14 April 2019)

A directory called /home/dhuser/PROGETTO7/Files/ReferenceGenome/Homo_sapiens_NCBI_GRCh38/Homo_sapiens/NCBI/GRCh38/Sequence/WholeGenomeFasta/Bisulfite_Genome/ already exists. Already existing converted sequences and/or already existing Bowtie 2 or HISAT2) indices will be overwritten!

Step I - Prepare genome folders - completed

Total number of conversions performed:
C->T:	598683433
G->A:	600854940

Step II - Genome bisulfite conversions - completed

Bismark Genome Preparation - Step III: Launching the Bowtie 2 indexer
Please be aware that this process can - depending on genome size - take several hours!
Settings:
  Output files: "BS_CT.*.bt2"
  Line rate: 6 (line is 64 bytes)
  Lines per side: 1 (side is 64 bytes)
  Offset rate: 4 (one in 16)
  FTable chars: 10
  Strings: unpacked
  Max bucket size: default
  Max bucket size, sqrt multiplier: default
  Max bucket size, len divisor: 4
  Difference-cover sample period: 1024
  Endianness: little
  Actual local endianness: little
  Sanity checking: disabled
  Assertions: disabled
  Random seed: 0
  Sizeofs: void*:8, int:4, long:8, size_t:8
Input files DNA, FASTA:
  genome_mfa.CT_conversion.fa
Building a SMALL index
Reading reference sizes
Settings:
  Output files: "BS_GA.*.bt2"
  Line rate: 6 (line is 64 bytes)
  Lines per side: 1 (side is 64 bytes)
  Offset rate: 4 (one in 16)
  FTable chars: 10
  Strings: unpacked
  Max bucket size: default
  Max bucket size, sqrt multiplier: default
  Max bucket size, len divisor: 4
  Difference-cover sample period: 1024
  Endianness: little
  Actual local endianness: little
  Sanity checking: disabled
  Assertions: disabled
  Random seed: 0
  Sizeofs: void*:8, int:4, long:8, size_t:8
Input files DNA, FASTA:
  genome_mfa.GA_conversion.fa
Building a SMALL index
Reading reference sizes
  Time reading reference sizes: 00:00:46
Calculating joined length
Writing header
Reserving space for joined string
Joining reference sequences
  Time reading reference sizes: 00:00:47
Calculating joined length
Writing header
Reserving space for joined string
Joining reference sequences
  Time to join reference sequences: 00:00:36
bmax according to bmaxDivN setting: 733719112
Using parameters --bmax 550289334 --dcv 1024
  Doing ahead-of-time memory usage test
  Time to join reference sequences: 00:00:36
bmax according to bmaxDivN setting: 733719112
Using parameters --bmax 550289334 --dcv 1024
  Doing ahead-of-time memory usage test
  Passed!  Constructing with these parameters: --bmax 550289334 --dcv 1024
Constructing suffix-array element generator
Building DifferenceCoverSample
  Building sPrime
  Building sPrimeOrder
  V-Sorting samples
  Passed!  Constructing with these parameters: --bmax 550289334 --dcv 1024
Constructing suffix-array element generator
Building DifferenceCoverSample
  Building sPrime
  Building sPrimeOrder
  V-Sorting samples
^CTraceback (most recent call last):
Traceback (most recent call last):
  File "/usr/bin/bowtie2-build", line 90, in <module>
  File "/usr/bin/bowtie2-build", line 90, in <module>
        main()
  File "/usr/bin/bowtie2-build", line 87, in main
    main()
  File "/usr/bin/bowtie2-build", line 87, in main
sys.exit(subprocess.call(argv))
  File "/usr/lib/python2.7/subprocess.py", line 172, in call
    sys.exit(subprocess.call(argv))
  File "/usr/lib/python2.7/subprocess.py", line 172, in call
        return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 1099, in wait
return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 1099, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/usr/lib/python2.7/subprocess.py", line 125, in _eintr_retry_call
    return func(*args)
    KeyboardInterrupt
pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/usr/lib/python2.7/subprocess.py", line 125, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt
Parent process: Failed to build index

I'm trying to understand why I'm having this problem and how I can manage it, can you help me? 

Best Regards, Luigi

**Comment by FelixKrueger** [comment]
Hi Luigi,

It seems that the Bismark part of the indexing is working, but there is either a problem with your installation of Bowtie2 or Python, or how they work together.

I would probably recommend you install the latest version of Bowtie 2, and then move one of the folders

```
cd /home/dhuser/PROGETTO7/Files/ReferenceGenome/Homo_sapiens_NCBI_GRCh38/Homo_sapiens/NCBI/GRCh38/Sequence/WholeGenomeFasta/Bisulfite_Genome/
cd CT_conversion/
```

Once in there, you can try to manually launch the Bowtie 2 indexer, like so:

```
bowtie2-build genome_mfa.CT_conversion.fa BS_CT
```

If you can get this to work, you should have no issues with the Bismark indexer either.

**Comment by FelixKrueger** [comment]
Of course, in this example:

```
^C
KeyboardInterrupt
```
 looks like you the process was terminated? You need to let it run to completion in this case (`--threads INT` helps with speed).

**Comment by OrangeLuis97** [comment]
Hi Felix, thanks for replying. 

For the KeyboardInterrupt, probably I wrongly copied the shell output for this post, so my mistake. 

About the real problem, I updated Bowtie2 and runned a genome_preparation only on a chromosome, so to test it faster and to see if it works and actually it does. Now i started another genome_preparation on the whole genome, I will let you know in the next hours. 

Regards, 
Luigi

**Comment by OrangeLuis97** [comment]
Hi Felix, that's my update after running the whole enome preparation. 

It gives me "failed to build index" error, probably because the ram that I assigned to my virtual machine isn't enough (only 12gb). 

Thank you for your time.

Best Regards, Luigi

**Comment by FelixKrueger** [comment]
That's probably right, give it enough RAM and all will be fine! Cheers, Felix

**Comment by FelixKrueger** [comment]
I assume this has now worked.
