### ISSUE TITLE
Poor mapping effeciency

### ISSUE THREAD

**Issue by Jkakob** [FelixKrueger/Bismark#370]
Hello!

I am trying to align my raw 150bp paired end sequencing files to the mitochondrial genome. My mapping efficiency is <3%. I have used a methylation kit that requires PCR amplification of the library at the very end stage before sequencing of libraries. 

I have used the following parameters to try to improve the mapping:
--pbat (separately align paired reads)
--non_directional
--score_min L,0,-0.4 (relaxed scoring)

But nothing has worked. The following messages keep repeating:

1) "Chromosomal sequence could not be extracted for ....[reference genome]...."
2) "Use of uninitialized value in concatenation..."

Am I missing any important parameters that are required for aligning to smaller genomes specifically? Previously where a pcr amplification of the library was NOT performed before sequencing, I did not have this issue.

Any suggestions will be greatly appreciated. Thankyou.

**Comment by FelixKrueger** [comment]
Hi @Jkakob 

It would probably be easiest if you could send me a subsample of the data (e.g. 200K reads typically fit into an email attachment, and I have a go myself.

For some amplicon data it might help to add 2 additional basepairs to the reference sequence (e.g. NNSEQUENCENN, and then run the indexing again) so that Bismark can extract 2bp up or downstream to determine the cytosine context. Cheers, Felix

**Comment by Jkakob** [comment]
Hello!

Thanks so much for your suggestions, if it is ok with you, I would like to
send you an entire file of one sample so that you may be able to
thoroughly gauge what might be going on. Please let me know if the file
transfer has worked. I truly appreciate your help and support in this
issue.  Many thanks again!
 D12_1_sequence.txt.gz
<https://drive.google.com/file/d/1gf4-6uvCWASBhZxVHNl6Wt6eemt5J9kT/view?usp=drive_web>
 D12_2_sequence.txt.gz
<https://drive.google.com/file/d/1a17yO3eSsb5Nj12ZKEKi5IouWf4DMd2V/view?usp=drive_web>

**Comment by Jkakob** [comment]
Hello!

Thanks so much for your suggestion, if it is ok with you, I would like to
send you an entire file of one sample so that you may be able to
thoroughly gauge what might be going on. Is there a way I can send the
files to you directly? Please let me know what is the easiest option.
Otherwise, as you have suggested, since I am not a bioinformatician,
I would require some assistance in knowing how to subset 200K reads from a
file. Many thanks again!

**Comment by FelixKrueger** [comment]
Thanks for that, I'm on it.

**Comment by FelixKrueger** [comment]
Right, here is a quick assessment

- The quality of your sample looks great overall
- the Sample is almost exclusively mouse sequence, with some 3% PhiX
- The bisulfite conversion is excellent (>99.6%)
- The sample looks like genome-wide sequencing (WGBS), the parameters required for mapping are thus the *default* mode (no `--pbat` or `--non_directional` needed)
- The fragment length is unusually long, so for future alignments I would increase the maximum mapping parameter `-X 1000` (up from the default of 500). See the attachment for an illustration
- I have generated a SeqMonk vistory report (just unpack the zip file attached) to show you that the reads are 
    - uniformly distributed across the genome
    - ~2-3% of reads align to the MT, and uniformly so
    - the unusually long fragment length in your sample is shown as a histogram
- I haven't looked at the methylation itself but I am sure you will.

In essence, your Sample looks great. For best performance I would:

 - Trim with Trim Galore (`trim_galore --paired R1.fastq.gz R2.fastq.gz`)
- Align to the GRCm38 genome using a longer length cutfoff, e.g.:
`bismark -X 1000 --genome GRCm38 -1 D12_R1_val_1.fq.gz -2 D12_R12_val_2.fq.gz`

[Jkakob.zip](https://github.com/FelixKrueger/Bismark/files/5238876/Jkakob.zip)

I am afraid I don't exactly know where your errors came from exactly, but can you ensure that you are using the latest version of Bismark, align to the mouse genome (which reference have you been using?) and all should be fine. 

Happy to answer any questions you may have. Cheers, Felix

**Comment by Jkakob** [comment]
Oh wow, thank you so much for being so thorough. I really appreciate it! I
was under the impression I was working with mtDNA enriched samples and so
was confused at why only 2% was aligning to my reference genome. I was
using NC_005089 which is the mouse mitochondrial genome only.

Thanks very much again for your help.

**Comment by FelixKrueger** [comment]
You are very welcome. All the best, Felix
