### ISSUE TITLE
bedgraph to bigwig

### ISSUE THREAD

**Issue by sanchari24** [FelixKrueger/Bismark#371]
Hello, I have a small question. I want to convert the bismark coverage files to bigWig format.
I have the sample_CHG.gz.bismark.cov files. Other than the first 3 columns which refer to the chromosome and coordinates, which of the last 3 columns I should keep as the score for the bedgraph ?
Thanks.

    SL4.0ch07       136     136     50      1       1
    SL4.0ch07       153     153     100     2       0
    SL4.0ch07       378     378     50      1       1
    SL4.0ch07       380     380     100     2       0

**Comment by FelixKrueger** [comment]
I'm not all that familiar with bigWig format, but you should be able to simply use Bismark's `.bedGraph` file, and then run it through the `bedGraphToBigWig` utility. More information about this is available over at UCSC: https://genome.ucsc.edu/goldenPath/help/bigWig.html#Ex3

Good luck!

**Comment by s-andrews** [comment]
To do the bigWig conversion from the bismark bedGraph file you'll also need to generate a file of chromosome sizes.  It might not be a bad idea to have bismark generate this if it's making bedGraph files since this information will be available when that processing is happening.

**Comment by FelixKrueger** [comment]
Alright, I can look into that.

**Comment by s-andrews** [comment]
One other little glitch with this (not sure if you do this already).  If people want to use the bedGraph / bigWig with UCSC then chromosome names need to be prefixed with chr. It might be worth having an option to add this if it's not there already (maybe on by default?), otherwise people might get bigWig/bedGraph files which don't actually work when they try them.

**Comment by sanchari24** [comment]
> One other little glitch with this (not sure if you do this already). If people want to use the bedGraph / bigWig with UCSC then chromosome names need to be prefixed with chr. It might be worth having an option to add this if it's not there already (maybe on by default?), otherwise people might get bigWig/bedGraph files which don't actually work when they try them.

Correct, right now I am handling this with an awk script.

**Comment by FelixKrueger** [comment]
I have now added a new option `--ucsc` to `bismark2bedGraph` that will produce a UCSC-ready bedGraph file if the genome version used came from Ensembl.

This option:

- prefixes chromosome names with 'chr'
- changes the mitochondrial chromosome from 'MT' to 'chrM' (see here: http://www.ensembl.org/Homo_sapiens/Location/Chromosome?chr=MT;r=MT:1-16569)
 

So:

```
9	135760747	135760748	100
9	136608920	136608921	0
9	136895832	136895833	100
9	137919834	137919835	100
9	137919846	137919847	100
MT	5820	5821	0
MT	6656	6657	0
MT	9911	9912	0
MT	9917	9918	0
MT	9920	9921	0
MT	11125	11126	0
MT	15147	15148	0
MT	15199	15200	0
X	1759095	1759096	100
X	3710382	3710383	100
X	5167140	5167141	100
X	7054828	7054829	100
X	10131568	10131569	0
```

would become:

```
chr9	135760747	135760748	100
chr9	136608920	136608921	0
chr9	136895832	136895833	100
chr9	137919834	137919835	100
chr9	137919846	137919847	100
chrM	5820	5821	0
chrM	6656	6657	0
chrM	9911	9912	0
chrM	9917	9918	0
chrM	9920	9921	0
chrM	11125	11126	0
chrM	15147	15148	0
chrM	15199	15200	0
chrX	1759095	1759096	100
chrX	3710382	3710383	100
chrX	5167140	5167141	100
chrX	7054828	7054829	100
chrX	10131568	10131569	0
```

**Comment by FelixKrueger** [comment]
I now need to add the same option to the `bismark_methylation_extractor` so that it can be passed on to the bedGraph process.

Regarding the file for with chromosome sizes: I think this might be best extracted from the SAM header during the methylation extraction step, maybe only when the option `--ucsc` is specified.

**Comment by FelixKrueger** [comment]
I have now added the option `--ucsc` also to `bismark_methylation_extractor` which can be passed on to `bismark2bedGraph` (f91d85dfc2c04b474663e9b1e9f421143548de11). In addition, it will now write out a new file ending in `.chromosome_sizes.txt`. This file is a tab-delimited text file, that equally:

- prefixes chromosome names with 'chr'
- changes the mitochondrial chromosome from 'MT' to 'chrM'

A chromosome sizes file for the human genome would currently look like this:  

```
chr1	248956422
chr10	133797422
chr11	135086622
chr12	133275309
chr13	114364328
chr14	107043718
chr15	101991189
chr16	90338345
chr17	83257441
chr18	80373285
chr19	58617616
chr2	242193529
chr20	64444167
chr21	46709983
chr22	50818468
chr3	198295559
chr4	190214555
chr5	181538259
chr6	170805979
chr7	159345973
chr8	145138636
chr9	138394717
chrM	16569
chrX	156040895
chrY	57227415
```

Are these changes the ones you had in mind? If so, could you please clone the current dev (from the master branch) and let me know if it works in your hands?

**Comment by sanchari24** [comment]
I will try this option and let you know

**Comment by FelixKrueger** [comment]
Hi @sanchari24 

Did it work?

**Comment by sanchari24** [comment]
Hello, this works perfectly for me!

**Comment by FelixKrueger** [comment]
thanks for the feedback!

**Comment by moqri** [comment]
It seems the chromsize posted here will result in this error using updated bed graph files:
`"chrUn_KI270548v1 is not found in chromosome sizes file"`

**Comment by FelixKrueger** [comment]
The chromosome sizes should get created from the header in BAM file you are using (extracted here: `/SN:(.*)\s+LN:(\d+)/`. Can you check to see if it is part of the BAM file?

**Comment by moqri** [comment]
Thank you! I resolved it by removing unwanted chromosomes as we are only interested in somatic Chrs:
`grep -v '_' <BedGraph> | grep 'chr[1-9][0-9]\?' > <bed> # only somatic Chrs`
