### ISSUE TITLE
limit time with bismark2bedGraph command

### ISSUE THREAD

**Issue by RubioB** [FelixKrueger/Bismark#372]
Hi Felix, 
I having a problem with th bismark2bedGraph command for my data in the CHH context. Indeed, from the start, I had a job that was stopped because of a time overrun. So I used the --buffer_size (60G and even 90G) argument associated with the --scaffolds argument while increasing the time limit that is allowed on my working cluster (5 days of compute time used instead of 3) but I still have the same problem. 

Am I using the arguments correctly? Do I still have to increase the maximum computing time on my cluster?

thank you for your help

Bernadette

**Comment by FelixKrueger** [comment]
Hi Bernadette, 

The answer to this is: I don't really know... I don't think I ever had any issues with this, neither with time nor memory usage. What does the test you see on screen indicate, is it still running or were there any issues?

**Comment by RubioB** [comment]
Thanks to your answer !

The test is still stopped with always the same error which is as follows :

"The genome of interest was specified to contain gazillions of chromosomes or scaffolds. Sorting everything in memory instead of writing out individual chromosome files ...
Sorting input file CHH_context_D35_R1_val_1_bismark_bt2_pe.deduplicated.txt by positions (using -S of 90G)
slurmstepd: error: *** JOB 19534275 ON node136 CANCELLED AT 2020-09-18T15:11:20 DUE TO TIME LIMIT ***"

Do I have to allow an even greater time limit than the 5 days I have already tested ?
________________________________
De : Felix Krueger <notifications@github.com>
Envoyé : lundi 21 septembre 2020 13:04
À : FelixKrueger/Bismark <Bismark@noreply.github.com>
Cc : RubioB <bernadetterubio@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [FelixKrueger/Bismark] limit time with bismark2bedGraph command (#372)


Hi Bernadette,

The answer to this is: I don't really know... I don't think I ever had any issues with this, neither with time nor memory usage. What does the test you see on screen indicate, is it still running or were there any issues?

**Comment by FelixKrueger** [comment]
I am not en expert with Slurm, but:

```
*** JOB ... CANCELLED ... DUE TO TIME LIMIT ***
```

Sounds an awful lot like it needs more time :)

We really have not used this much since we are mostly working with human and mouse genomes, but it seemed clear from the start that sort on a huge file will be very computationally intense.

```
                           ...and this
                           file will then be sorted by both chromosome AND position using the Unix sort command.
                           Please be aware that this option might take a looooong time to complete, depending on 
                           the size of the input files, and the memory you allocate to this process (see --buffer_size).
                           Nevertheless, it seems to be working.
```

Maybe you could look into options for the Linx sort command to make it faster, and modify that step in `bismark2bedGraph`?

**Comment by RubioB** [comment]
Ok thanks !
I will try to increase the time limit even more !

________________________________
De : Felix Krueger <notifications@github.com>
Envoyé : lundi 21 septembre 2020 13:24
À : FelixKrueger/Bismark <Bismark@noreply.github.com>
Cc : RubioB <bernadetterubio@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [FelixKrueger/Bismark] limit time with bismark2bedGraph command (#372)


I am not en expert with Slurm, but:

*** JOB ... CANCELLED ... DUE TO TIME LIMIT ***


Sounds an awful lot like it needs more time :)

We really have not used this much since we are mostly working with human and mouse genomes, but it seemed clear from the start that sort on a huge file will be very computationally intense.

                           ...and this
                           file will then be sorted by both chromosome AND position using the Unix sort command.
                           Please be aware that this option might take a looooong time to complete, depending on
                           the size of the input files, and the memory you allocate to this process (see --buffer_size).
                           Nevertheless, it seems to be working.


Maybe you could look into options for the Linx sort command to make it faster, and modify that step in bismark2bedGraph?
