### ISSUE TITLE
some questions about identifing the methylation of cytosine

### ISSUE THREAD

**Issue by Grace-0114** [FelixKrueger/Bismark#373]
1. mC and C . Question 1: how to identify mC?
2. bismark 0.20.0 : bismark_methylation_extractor 
 -option
--split_by_chromosome 
output files: XX.clean_val_1_bismark_bt2_pe.deduplicated.CX_report.txt.chr{1..22,X,Y}.CX_report.txt
Question 2: all cytosines in output files are cytosines. What are the judgment standards of mCpG, mCHH and mCHG ?
I want to draw the methylation situation of all cytosine and the methylation situations of mCpG, mCHH and mCHG with XX.clean_val_1_bismark_bt2_pe.deduplicated.CX_report.txt.chr{1..22,X,Y}.CX_report.txt.

**Comment by FelixKrueger** [comment]
Hi @Grace-0114 

I am not sure if I understand your questions correctly. Generally, the Bismark alignment step will map reads to the genome and determine the methylation state of all cytosines for each read. So within a read, a cytosine (in any context) can either be found methylated or unmethylated. If you then take the entirety of all reads in your sequencing library that were informative for a certain position in the genome, you can determine the average methylation state of a cytosine either as percentage methylation, or a ratio between 0 and 1.

We personally perform methylation analysis like mentioned in this methylation course:  
https://www.bioinformatics.babraham.ac.uk/training.html#bsseq. If you need a pointer how to get started with SeqMonk, please refer to e.g. this introductory video https://www.youtube.com/watch?v=pi8o2_Q_Dy0

Not sure what you mean with judgement standards, but e.g. in mammalian systems CpG residues tend to be methylated, while non-CG residues are generally unmethylated. I hope this help?

**Comment by Grace-0114** [comment]
I'm really sorry.  I didn't make my question clear.

Bismark Software (V0.20.0) Alignment program with Bowtie2 v2.3.4.1：
Q1. **Total methylated C's analysed**plus**Total unmethylated C's analysed**is not**the total number of C's analysed**  ？ : 
Sample：YA09
Final Cytosine Methylation Report
=================================
Total number of C's analysed:	14457991729
Total methylated C's analysed：471294909
Total unmethylated C's analysed：13993370558

![5D3})TC4$B2S4$RP1DF{VIW](https://user-images.githubusercontent.com/53073190/94360787-a2de0400-00e2-11eb-8365-ee5f6d39ca67.png)

 Bismark_methylation_extractor program with --split_by_chromosome. 
Output files：YA09.clean_val_1_bismark_bt2_pe.deduplicated.CX_report.txt.chr{1..22,X,Y}.CX_report.txt
Q2：The number of all cytosines in all output files above is 1131822093. What do you mean these cytosines in all output files above？ They make up about 7% of all C's analysed.

**Comment by Grace-0114** [comment]
I'm really sorry. I didn't make my question clear.
Bismark Software (V0.20.0) Alignment program with Bowtie2 v2.3.4.1：
Q1: Total methylated C's analysedplusTotal unmethylated C's analysedis notthe total number of C's analysed？ 
         Sample：YA09
         Final Cytosine Methylation Report
         Total number of C's analysed: 14457991729
         Total methylated C's analysed：471294909
         Total unmethylated C's analysed：13993370558
Q2: The number of all cytosines in all output files above is 1131822093. What do you mean these cytosines in all output files above？ They make up about 7% of all C's analysed.
         Bismark_methylation_extractor program with --split_by_chromosome.
         Output files：YA09.clean_val_1_bismark_bt2_pe.deduplicated.CX_report.txt.chr{1..22,X,Y}.CX_report.txt

**Comment by FelixKrueger** [comment]
To Q1:

Upon completion Bismark prints an overall summary of all of the methylation that were found during the entire run. This is merely there to give you an idea of the overall averages that were seen, but it doesn't say anything about the genomic location or whether there are any trends around certain features.

So in your sample, around 14.4 billion cytosines were analysed overall, and ~3.2% of those calls were found to be methylated.

To Q2:

I am not sure there the number 1131822093 comes from here, but as pointed out for Q1, the number is simply a summed up tally of all cytosines found in ALL reads in the entire samples. So as an example if you have a read or read-pair with 5 CpGs, and 10 cytosines in each CHG and CHH context, the entire read would add 5 + 10 +10 = 25 calls to the overall tally.

At this point, this does NOT say anything about how many different cytosines in the genome were covered, or where they were. You could either have relatively shallow coverage of most cytosines in the genome, or only a few cytosine but at a huge sequencing depth, or most likely: a mix of the two. This is however something that needs to be answered in your downstream analysis. Makes sense?
