### ISSUE TITLE
Migrate Continuous Integration from Travis to Github actions

### ISSUE THREAD

**Issue by FelixKrueger** [FelixKrueger/Bismark#374]
Some tests in Travis CI are failing, this might be a good time to migrate to GA. https://github.com/FelixKrueger/Bismark/blob/master/.travis.yml

**Comment by FelixKrueger** [comment]
This is now complete. Thanks for your help setting up Conda & more @ewels ! https://github.com/FelixKrueger/Bismark/pull/379

**Comment by ewels** [comment]
Nice!
