### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Carly-31** [FelixKrueger/Bismark#375]
Hello I am new to Bismark, I am encountering a problem. please see below:

The IDs of Read 1 (#!/usr/bin/env perl
) and Read 2 (use warnings;
) are not the same. This might be the result of sorting the paired-end SAM/BAM files by chromosomal position which is not compatible with correct methylation extraction. Please use an unsorted file instead or sort the file using 'samtools sort -n' (by read name). This may also occur using samtools merge as it does not guarantee the read order. To properly merge files please use 'samtools merge -n' or 'samtools cat'.

Code I run: ./bismark_methylation_extractor --gzip --bedGraph --counts --buffer_size 10G --p coverage2cytosine --CX  --genome_folder /Users/Desktop/bismark/data/genomes/Brassica/1.5 M1F_clean_1_bismark_bt2_pe.bam --o 1F .

**Comment by FelixKrueger** [comment]
Hi @Carly-31 

It seems that you are running the script on the script `coverage2cytosine`, instead of the BAM file. Let's look at the command again:

`./bismark_methylation_extractor` fine
`--gzip --bedGraph` fine
`--counts` not necessary, as is default
`--buffer_size 10G` fine
 `--p` not needed, as auto-detected
`coverage2cytosine`: **THIS IS THE PROBLEM.** The option is called `--cytosine_report`
` --CX --genome_folder /Users/Desktop/bismark/data/genomes/Brassica/1.5` fine
`M1F_clean_1_bismark_bt2_pe.bam` fine. THIS IS THE FILE TO BE PROCESSED
`--o 1F` fine
`.` why is there a `.` dot? This is interpreted as the current directory by you shell. Please lose it.

So the correct command should be:
```
./bismark_methylation_extractor --gzip --bedGraph --buffer_size 10G --cytosine_report --CX --genome_folder /Users/Desktop/bismark/data/genomes/Brassica/1.5 M1F_clean_1_bismark_bt2_pe.bam --o 1F
```

Let me know how you get on. Cheers, Felix

**Comment by Carly-31** [comment]
Thank you so much for the help. 

Question 1:
But when running the code I get this error.

Using a cutoff of 1 read(s) to report cytosine positions
Reporting and sorting methylation information for all cytosine context (sorting may take a long time, you have been warned ...)
The bedGraph UNIX sort command will use the following memory setting:	'10G'. Temporary directory used for sorting is the output directory


Summarising genome-wide cytosine methylation report parameters:
===============================================================
Generating comprehensive genome-wide cytosine report
(output format: <Chromosome> <Position> <Strand> <count methylated> <count non-methylated>  <C-context>  <trinucleotide context> )
Reporting methylation for all cytosine contexts. Be aware that this will generate enormous files
Using 1-based genomic coordinates (default)
The specified genome folder does not appear to be a directory. Please respecify and try again!

I clearly but the genome_folder /Users/Desktop/bismark/data/genomes/Brassica/1.5 but still this error. Does this usually happen.'

Question 2
I want to determine TE( Transposable elements) using the software ViewBS but when I am trying to run the software they want an input file for the run which is cov.gz and also a tab.gz but for the output files for Bismark extractor its only a cov.gz  represented. How do I get a tab.gz file.

**Comment by FelixKrueger** [comment]
Hmm, I am not exactly sure what the error is here: 

"I clearly but the genome_folder /Users/Desktop/bismark/data/genomes/Brassica/1.5 but still this error. Does this usually happen.'
"

If you type 
```
ls -l /Users/Desktop/bismark/data/genomes/Brassica/1.5
```

Do you then see the folder containing your genome `.fa` files as well as the folder `Bisulfite_Genome`?

For 2): I have not come across the software ViewBS so far, so I am also not sure which input files it requires. Could you try and look this up in the ViewBS documentation?

**Comment by FelixKrueger** [comment]
Just saw this on their Githib site: 

```
bgzip test.bis_rep.cov            ## test.bis_rep.cov.gz will be generated. Note: test.bis_rep.cov shoud be sorted based on chromosome coordinates. 
tabix -C -p vcf test.bis_rep.cov.gz  ## test.bis_rep.cov.gz.csi will be generated. Now test.bis_rep.cov.gz can be used as input for ViewBS. 
```

**Comment by Carly-31** [comment]
Hello thank you so much 
I run this code ls -l /Users/Desktop/bismark/data/genomes/Brassica/1.5 and 
got this error:

I bismark % ls -l /Users/Desktop/bismark/data/genomes/Brassica/1.5
ls: /Users/Desktop/bismark/data/genomes/Brassica/1.5: No such file or directory
 
But when I physically go to the folder and ls I got this:
1.5 % ls -l
total 569584
29081951 Oct 26  2019 A01.fa
28310497 Oct 26  2019 A02.fa
32244345 Oct 26  2019 A03.fa
19281495 Oct 26  2019 A04.fa
24338894 Oct 26  2019 A05.fa
26709667 Oct 26  2019 A06.fa
22963232 Oct 26  2019 A07.fa
21954623 Oct 26  2019 A08.fa
37739218 Oct 26  2019 A09.fa
 17887840 Oct 26  2019 A10.fa
 128 Sep 26 00:45 Bisulfite_Genome
31087698 Nov 13  2019 nonchromosomal.fa
 
All my files and also Bisulfite_Genome folder

**Comment by FelixKrueger** [comment]
This just sounds like you got the folder name wrong. When you move to that folder physically, and type `pwd` (path to working directory), what do you see?

**Comment by Carly-31** [comment]
Gee, your right. Thank you so much and sorry for this silly mistake.
