### ISSUE TITLE
How to determine possible bacterial/viral contaminants on BS-Seq data?

### ISSUE THREAD

**Issue by StefanoLonardi** [FelixKrueger/Bismark#376]
Hi Felix,
thanks for your great tool.

We have some BS-Seq data sets that show very low mapping efficiency with Bismark (<2%), and we are worried about bacterial/viral contaminants in the samples. The problem is what we do not know what bacteria could be present. We could use Bismark against *all* the bacterial genomes, but that could be very time consuming. Do you have any suggestion?

Cheers,
Stefano

**Comment by FelixKrueger** [comment]
Hi Stefano,

Before aligning the data to every single known organism, I could offer that you send me subset of your one of samples and I take a look over here (e.g. 200,000 reads as .gz file fit into an email attachment, but I could also share an FTP site for you if that helps). We have a fairly broad range of typical contaminants already set up, so if you could also let me know which type of library and organism you were trying to look at, I might be able to give some advice?

**Comment by StefanoLonardi** [comment]
Hi Felix, thanks for offering to take a look at our reads. I will email you the reads by email. Cheers, Stefano

**Comment by FelixKrueger** [comment]
Found the culprit, results sent. Best, Felix
