### ISSUE TITLE
bismark shared memory loading of reference 

### ISSUE THREAD

**Issue by avilella** [FelixKrueger/Bismark#38]
This is a feature request against the master branch of bismark:

Bismark loads the reference genome in memory, then calls bowtie2 to align reads.

The loading of the reference can take between 30 seconds and 5 minutes, depending on the size of the reference and the type of read access. 

If the use of bismark is sporadic, e.g. a blast-like service of a few reads against a running bismark server, it takes a long time to load the reference and then only a few seconds to align the reads and produce the output.

Feature request: `bismark -shm`

Similar to `bwa shm`, an option to create an index in shared memory, so that bismark can run in "server mode":

```
bwa shm

Usage: bwa shm [-d|-l] [-f tmpFile] [idxbase]

Options: -d       destroy all indices in shared memory
         -l       list names of indices in shared memory
         -f FILE  temporary file to reduce peak memory

Example use:

index=/opt/Homo_sapiens/UCSC/hg19/Sequence/BWAIndex/genome.fa
bwa shm $index # load the index into shared memory
bwa mem ref.fa reads.fq > results.sam
bwa shm -l # list indices in shared memory
bwa shm -d # unload all indices 

```

**Comment by FelixKrueger** [comment]
Talked about it over coffee and decided that we are not going to look into this further.

**Comment by jonathanronen** [comment]
Adding one vote to the usefulness of this feature, in case you ever decide to reconsider

**Comment by yo54233154** [comment]
Both bowtie and bowtie2 have an --mm  option to use memory-mapped I/O for index. bowtie(but not bowtie2) has an additional --shmem option which I think should be similar to that of bwa. 
I have tested --mm for standard bowtie2 alignment runs and can confirm that bowtie2 instances against the same index do share memory. This could potentially lower ram requirements for parallel-bismark.
