### ISSUE TITLE
Methylation Extractor Output

### ISSUE THREAD

**Issue by salehsereshki** [FelixKrueger/Bismark#383]
Dear Felix,

I want to use the methylation-extractor genome-wide cytosine report in my downstream analysis. I ran the bismark_methylation_extractor command with --CX option. I expected to get the bedgraph file containing the methylation report for every single Cytosine. The Bedgraph file(pe.CX_report.txt) contains 10,230,027 rows. But the mapping report(at the step of generating .bam file PE_report.txt) shows I have 21,672,090 Cytosines in total('Total number of C's analysed:	22667786'). Why these two numbers are different? I supposed to get the same number in both reports. Because they are the number of cytosines in the genome.

**Comment by FelixKrueger** [comment]
The total number of cytosines analysed is simply the total tally of methyltation calls that were performed anywhere, in any read. This number increases with increased sequencing depth, and does not necessarily say anything about the number of different position covered in the genome.

So if there are 10.2 million positions covered, each with 2-3 reads, you should end up at the total number of cytosines reported in the Overall Bismark report. Does that make sense?
