### ISSUE TITLE
Unknown option: parallel

### ISSUE THREAD

**Issue by lauzikaite** [FelixKrueger/Bismark#386]
Hi,

I'm trying to run bismark_genome_preparation as follows:

`
bismark_genome_preparation --parallel 8 path_to_dir
`

but it fails with an error 

> Unknown option: parallel

When I run the command without this option, genome preparation works, it's just incredibly slow.

Bismark Version: v0.22.3 running on a Debian GNU/Linux 10 server.

**Comment by FelixKrueger** [comment]
Hu @lauzikaite 

When I copy-paste your command, I get the following:

```
bismark_genome_preparation --parallel 8 .
Using 8 threads for the top and bottom strand indexing processes each, so using 16 cores in total
Writing bisulfite genomes out into a single MFA (multi FastA) file
...
```

So it seems to be just fine.

So my guess is that you might think that you've got v0.22.3 installed, but maybe the genome preparation is still in older version? Could you run `bismark_genome_preparation --version`?

**Comment by lauzikaite** [comment]
Thanks for your reply, it was indeed a silently linked older version of bismark_genome_preparation,  once I updated the symlink, the command works fine. Thanks again!
