### ISSUE TITLE
Understanding common positions in different contexts 

### ISSUE THREAD

**Issue by NomiCentarix** [FelixKrueger/Bismark#387]
Hello Felix,
I have another question on the same data I used in [this](https://github.com/FelixKrueger/Bismark/issues/385) issue.

Please look at the following figure. 
![image](https://user-images.githubusercontent.com/70898836/96569525-edadfe80-12d1-11eb-9f66-692bff3f003b.png)

In the standard outputs we can see that position 136 is covered by **4** reads: 3 in CpG context, 1 in non-CpG context.
The _coverage2cytosine_ report says we have 4 reads as well, where all are in CpG context.

My questions are:
1. Can you explain me how the same position can appear in different contexts? (or link me if it was already asked).
2. How do the _coverage2cytosine_ report decides what is the context? Does it do it by the majority (i.e., 3 in CpG, 1 in non-CpG, thus context is CpG)? 

Thank you for your patient,
Nomi

**Comment by FelixKrueger** [comment]
Hi Nomi,

the short answer is: the methylation call in Bismark may report a different context if the read has a deletion directly downstream of the cytosine in question. This call and its context is carried through to the methylation extractor and coverage file stage.

The output of the `coverage2cytosine` however is strictly based on the reference genome and does therefore not take the context of the calls as such into account (you just need to make that you only feed the correct contexts into the process to start with).

This issue has indeed been discussed many times, here is a link to the [FAQ section](https://github.com/FelixKrueger/Bismark/blob/master/Docs/FAQ.md#issue-3-context-changediscrepancy-between-bismark-coverage-and-genome-wide-cytosine-reports).

**Comment by NomiCentarix** [comment]
Oh I missed this FAQ, sorry.
"feed the correct contexts" - meaning, the a correct reference genome, yes?
Thank you!

**Comment by FelixKrueger** [comment]
What I meant was: if the position is in `CpG`context, and the methylation calls show 3 calls in `CpG` context, and 1 in `CHH` context, then just feeding the CpG context to `bismark2bedGraph` (the step that generates the coverage file) will essentially drop the one `CHH` call with the deletion immediately downstream. 

The result should be that you get only 3 calls, all of which had been called as `CpG` context. Makes sense?

**Comment by NomiCentarix** [comment]
ahhhh.
now I get it, and this little comment was important to me. thanks!!
