### ISSUE TITLE
error when combining the --local and --non_bs_mm options

### ISSUE THREAD

**Issue by retrogenomics** [FelixKrueger/Bismark#388]
Combining the `--local` and `--non_bs_mm` options leads to the following type of errors:

> The CIGAR string contained illegal CIGAR operations in addition to 'M', 'I', 'D' or 'N': 2S70M6D31M1D6M1I22M3D2M1D7M9D59M

It is likely due to the presence of the soft-clipping operation 'S' in the CIGAR string that only occurs in the local mode, but not in the end-to-end mode.

**Comment by retrogenomics** [comment]
Sorry, this issue has been addressed in a more recent release than the version I used (0.22.2 vs 0.22.1). This combination of options is now forbidden.

**Comment by FelixKrueger** [comment]
Hehe OK. I hope this is something you can live with?

**Comment by retrogenomics** [comment]
I guess so, thanks !
