### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by bri2020** [FelixKrueger/Bismark#393]
Hi Felix, 
I am searching this document but I get out in the nirvana... ;D
http://www.epigenesys.eu/en/protocols/bio-informatics/483-quality-control-trimming-and-alignment-of-bisulfite-seq-data-prot-57 
Thanks a lot!
Britta

**Comment by FelixKrueger** [comment]
Hi Britta,

This is really hosted by Epigenesys and not ourselves, but given that this document is probably around 8 years old by now I am not sure how up to date it really is... Anything specific you are interested in?

**Comment by bri2020** [comment]
Hi, 
not really I am just checking Mbias, adaptors and 3'prime and 5'prime problems (again) and try to what happened in my new experiment. Just thought that I could find some nice picture there... ;D

**Comment by FelixKrueger** [comment]
OK fine. If there are any specific don't hesitate to drop me an email. In the meantime, there might be some nice pictures over at https://sequencing.qcfail.com/? 👍
