### ISSUE TITLE
Low mapping rate using the NOMe-seq option

### ISSUE THREAD

**Issue by docmainz** [FelixKrueger/Bismark#394]
Hi Felix, 

first thanks for bismark, i especially love the NOMe-seq option to analyse some new data i have.

So I am trying to align a sample test NOMe-seq data (number of reads is extremely low) using bismark with the NOMe-seq option. My issue is that in the output i see mapping around 13-23%, and i ask you is it normal to get this sort of low mapping? 

The procedure i used is as follows.

    - data recieved are paired-end, fastq files trimmed.
    - loading bismark 0.22.3 and bowtie 2.1.0 (im computing from a remote server)
    - preparing a regular conversion of the mm10 genome using bismark_genome_preparation. As far as i understood, i need to prepare the genome the same way as for fishing CpG, except that in the end i will look for GpC. Correct me if im wrong.
    **bismark --bowtie2 --non_directional --multicore 4 -I 0 -X 1000 --score_min L,0,-0.6 -L 5 -N 1 --genome_folder $genome -1 $fastq_R1 -2 $fastq_R2 -o bismark_out/** (to note: i tried to modify the 0.6 value to 10 or more to increase number of reads aligned, but the quality of aln dropped with cigar patterns that include inserts and deletions. There i can reach 80% and probably more.
    in the end, i get the report below. As you can see number of paired reads (21344) is low, but this is expected in our experiment.

========================================================================================== 

sample_R1_001.final.fastq.gz and sample_R2_001.final.fastq.gz (version: v0.22.3) Bismark was run with Bowtie 2 against the bisulfite genome of genomes/mm10/current/bowtie/2.1.0/ with the specified options: -q -N 1 -L 5 --score-min L,0,-0.6 --ig\ nore-quals --no-mixed --no-discordant --dovetail --minins 0 --maxins 1000 Option '--non_directional' specified: alignments to all strands were being performed (OT, OB, CTOT, CTOB)

Final Alignment report

Sequence pairs analysed in total: 21344 
Number of paired-end alignments with a unique best hit: 3778 
Mapping efficiency: 17.7% 
Sequence pairs with no alignments under any condition: 16504 
Sequence pairs did not map uniquely: 1062 
Sequence pairs which were discarded because genomic sequence could not be extracted: 0

Number of sequence pairs with unique best (first) alignment came from the bowtie output: 
CT/GA/CT: 1947 ((converted) top strand) 
GA/CT/CT: 13 (complementary to (converted) top strand) 
GA/CT/GA: 12 (complementary to (converted) bottom strand) 
CT/GA/GA: 1806 ((converted) bottom strand)

Final Cytosine Methylation Report

Total number of C's analysed: 131387

Total methylated C's in CpG context: 3086 
Total methylated C's in CHG context: 3630 
Total methylated C's in CHH context: 10640 
Total methylated C's in Unknown context: 43

Total unmethylated C's in CpG context: 6499 
Total unmethylated C's in CHG context: 25829 
Total unmethylated C's in CHH context: 81703 
Total unmethylated C's in Unknown context: 611

C methylated in CpG context: 32.2% 
C methylated in CHG context: 12.3% 
C methylated in CHH context: 11.5% 
C methylated in unknown context (CN or CHN): 6.6%

Bismark completed in 0d 0h 8m 43s

=================================================================================

David

**Comment by FelixKrueger** [comment]
Hi David,

There are few things to unpick here. If I understand it correctly then you have used a methylase to methylated cytosines in GpC context, presumably in a bid to determine accessible regions? If so, then you, you should be able to align the data as per usual, and add a NOMe-seq filtering step at the very last step, namely `coverage2cytosine`. The steps until that point should be pretty much normal, except that you will need to use the option `--CX` for the `bismark2bedGraph` (or the the `bismark_methylation_extractor --CX --bed`, as you would other wise lose all GpC calls in the default mode which is CpG only.

I can't really comment very much on which mapping mode you will have to use, as this really depends very much on the library preparation you used. I think it might help if you could send me say 200K reads of your raw, untrimmed reads, so I can take a look? I could then assess whether the data looks like it needs specific clipping before alignments, if the data looks like there are contaminants etc that might explain the rather poor mapping efficiencies etc.

In the meantime, here are a few comments in no particular order:
- you data looks directional, as almost all reads align to the OT and OB strands (so just drop `--non_directional`)
- what did you use for trimming, we would recommend Trim Galore in `--paired` mode
- Bowtie2 v2.1.0 is nearly 7 years out of date, I would recommend getting that upgraded to 2.4.2
- `--multicore 4` for 20K sequences, you really don't need parallel processing. Remember that it will still take some 50GB of RAM or so to even start the alignments in this mode
- `-X 1000` this is normally not needed as bisulfite fragments are quite short. You could of course assess the fragment length later and increase it from the default of 500 if needed.
- `--score_min L,0,-0.6` I would not change this in the first instance for the mouse genome, as you will only see incorrect alignments. Maybe to -0.4 if you have a reason for it. If your mapping rate is that low, i would expect something else
- I can't remember having changed the parameters for `-L` `-N` ever. Why do you think the value you used are superior to the defaults?

So yea, I think it could help if you could send me a few reads of R1 and R2 to take a look myself?

Let me know if there are any other questions.

**Comment by FelixKrueger** [comment]
Haven't heeard back in a long while, assuming all is well.

**Comment by docmainz** [comment]
Hi Felix,
I forgot to reply at the time of the post, but your suggestion worked.
Thanks for your help and care. All the best for you. David


Le mar. 20 juil. 2021 à 17:00, Felix Krueger ***@***.***> a
écrit :
