### ISSUE TITLE
multiple input/output with shared reference

### ISSUE THREAD

**Issue by jksr** [FelixKrueger/Bismark#396]
Hi Felix,

We work on a lot of single cell mapping with bismark. We call one bismark run for each cell. The problem with this is each bismark run will have its own reference loaded into memory, which limits the mapping throughput. And since it's single cell data, merging fastq files and then splitting after mapping is not practical. 
I wonder if there is some way to have bismark support multiple fastq inputs (thus multiple corresponding bam output) with a shared reference?

Thanks,

**Comment by FelixKrueger** [comment]
That should be absolutely possible by simply specifying multiple samples.

```
<singles>                A comma- or space-separated list of files containing the reads to be aligned (e.g.
                         lane1.fq,lane2.fq lane3.fq). Reads may be a mix of different lengths. Bismark will
                         produce one mapping result and one report file per input file.
```

In the extreme, `bismark --genome /your/genome/ *fastq.gz` should do the trick. A similar provision is available for paired-end files (not sure you want to use that for single cells though (?)), just do `bismark --help` for more details. Is that what you are looking for?

**Comment by FelixKrueger** [comment]
I hope this what you needed.
