### ISSUE TITLE
CX report has chrY for females?

### ISSUE THREAD

**Issue by shruti3009** [FelixKrueger/Bismark#397]
Hi Felix,

I have a question regarding the CX report that I am using as an input in MethylKit. Please note that I have used Bismark aligner embedded in Illumina Dragen Methylation pipeline.

I used hg38 assembly with the "ALT-aware no HLA" mapping argument while mapping the fastq files from different samples. I was aware of the gender of these samples except the one. So, I thought of looking into the CX report that I got as a methylation pipeline result for that unknown gender sample. I simply grep "chrY"; if present-male, otherwise female.

It came to me surprisingly, that all of my CX reports from all the samples have "chrY", perhaps, there should be some females among these samples (which I already know), for which it should not mention "chrY".  

Do you think- is this related to any mismapping due to the hg38 Alt-aware No HLA argument while aligning the fastqs? Or does CX-report contain all autosomes' + both sex chromosomes' C/T counts, irrespective of female/male sample?

Will appreciate if you could clarify,

Thanks in advance,
Shruti

**Comment by FelixKrueger** [comment]
Hi Shruti,

I don't exactly know how exactly Bismark is implemented in the Dragen pipeline, but just generally, the CX report is entirely based on the reference genome sequence, and will have the same number of position in any sample - whether it is deeply lowly or deeply sequenced, male of female. The only difference would be that male samples probably have 0 counts methylated and 0 counts unmethylated throughout, in other words: they were not covered in the sample.

You should be able to filter out positions that were not covered at all, and then you would see the difference between the gendered samples that you are looking for. Alternatively, you could re-run the `coverage2cytosine` step starting from the coverage file yourself, and select a coverage threshold of 1. Or even better, you could grep fro chrY in the coverage file (`.cov.gz`), as this file should only contain covered positions.

Does this clear things up?

**Comment by shruti3009** [comment]
Hi Felix,

Thanks for the instant response.  I checked whether there is any count for
chrY rows in methylated (C) or unmethylated (T) columns of the CX report
for a female sample and found there are. I used the following command on
the CX report as I don't get the cov.gz file through dragen pipeline.
*cat ACRI-247.CX_report.txt | awk '{if ($1 == "chrY" && $4+$5 != 0) print
$0}'*

*Output snippet:*

chrY 59028974 + 0 13 CHG CTG
chrY 59028976 - 0 28 CHG CAG
chrY 59028977 + 0 13 CHH CAC
chrY 59028979 + 0 13 CHH CCC
chrY 59028980 + 0 13 CHH CCA
chrY 59028981 + 0 14 CHH CAT
chrY 59028987 + 0 14 CHH CTC
chrY 59028989 + 3 10 CG CGT
chrY 59028990 - 9 19 CG CGA

Should I consider it as a male sample or there has been some misalignment
that might be causing such confusion? Please advise.

Thank you,
Shruti

*Shruti Srivastava, B.Tech., MSc*
Bioinformatician
Atlantic Cancer Research Institute
Moncton, Canada
Contact no. +1 (778)-710-7937

**Comment by FelixKrueger** [comment]
Hmm, no coverage file? I am not sure this is that clever an idea, after all it is the most useful file of all of them... 

I think what you would want to be doing next is count the number of lines with non-0 counts - and then compare that number to samples you know are male. In my experience, an even better way than doing this is to import the BAM files into a genome browser (we use SeqMonk for that), and then you can just look at chrY and chrX - and it will become very clear in under a minute.  I think the Y chromosome shares some sequence portion with the X, and you would always expect a few reads going to the Y, but compared to true male samples it should really look like night and day.

**Comment by shruti3009** [comment]
Thank you for your response, Felix. I checked the read counts for chrY on female and male patients and that confirmed the starking difference. The homology between the Y sequence portion with X has definitely caused such confusion. Thanks once again for resolving this.
