### ISSUE TITLE
feature request: explicit --reference/--genome_folder option 

### ISSUE THREAD

**Issue by avilella** [FelixKrueger/Bismark#4]
This is a feature request for bismark. Currently, the genome_folder is parsed from the command line as an unnamed option:

```
  ### GENOME FOLDER
  my $genome_folder = shift @ARGV; # mandatory
  unless ($genome_folder){
    warn "Genome folder was not specified!\n";
    print_helpfile();
    exit;
  }
```

It would be easier to parse the genome folder from the bam header there was an explicit option for it. E.g.:

```
# Current mode kept for compatibility
bismark --bam --maxins 500 /path/to/fasta/homo_sapiens/dna/GRCh38 -1 SAMPLE_R1.cut.fq.gz -2 SAMPLE_R2.cut.fq.gz

# New explicit mode
bismark --bam --maxins 500 --genome_folder /path/to/fasta/homo_sapiens/dna/GRCh38 -1 SAMPLE_R1.cut.fq.gz -2 SAMPLE_R2.cut.fq.gz
```

There are programs downstream that rely on a consistent way of parsing the bam header, and it's easier to parse if all the parameters are named.

For your consideration :-)

**Comment by FelixKrueger** [comment]
I have now added this option, please let me know if it doesn't work as expected.
