### ISSUE TITLE
Bismark in WGBS extremely slow (~1M reads per hour)

### ISSUE THREAD

**Issue by LedaKatopodi** [FelixKrueger/Bismark#401]
Hello,

I am using Bismark on WGBS libraries with ~400M reads (post-trimming), PE150bp. My command is:

`bismark -n 1 --bowtie2 --genome ${wkDir}/genomes/hg38/ --multicore 6 -1 ${trim1} -2 ${trim2}`

with `{trim1}`and `{trim2}` being the absolute paths to the trimmed fastq files. 

I have requested 18 cores total [after your suggestions here: https://github.com/FelixKrueger/Bismark/issues/96], and 120G of RAM. 

The alignment step has been running for about 36 hours now, and my stderr log file writes "Processed 40,000,000 sequence pairs so far", resulting in ~1M reads processed per hour.

Do you know what might be the issue and the alignment step has been taking so much time? Do you have any suggestions on how to speed the process? 

Thank you very much,
Leda

**Comment by FelixKrueger** [comment]
Hi Leda,

you do have fairly long reads (150bp), paired-end libraries, and selected `-N 1` (which is probably quite a lot slower than the default of `-N 0`). But overall I would agree that 1M/hour seems quite slow.

If you are at 40M sequences now, and have split the data into 6 threads you should now be close to 300M sequences in total, so it will probably finish over night. Not sure if you wanted to test a second version, dropping the `-N 0` though...

**Comment by LedaKatopodi** [comment]
Thank you very much for your reply!

I will get a second version running, dropping the `-n` option. 

Best,
Leda
