### ISSUE TITLE
less lines in cytosine report than .cov

### ISSUE THREAD

**Issue by oxygen26** [FelixKrueger/Bismark#402]
Hi Felix:
Noticed there are about 5% less lines in cov2cytosine report than .cov in my data.
Checked the missing positions and they are not CG context on the chrom.
-X option is not applied, only focused on CG context.
Is there a possible mistake in my extraction process or mapping?
Here is several position, I'm not sure if the pics can be seen.
Basically they seem to be CC in most cases.
Thanks!
![image](https://user-images.githubusercontent.com/45955330/103840844-50db5000-50cd-11eb-9f05-b9f303712cbb.png)
![image](https://user-images.githubusercontent.com/45955330/103840862-5df83f00-50cd-11eb-92e0-74cee258653d.png)
![image](https://user-images.githubusercontent.com/45955330/103840880-651f4d00-50cd-11eb-92e5-b870952f7e24.png)
![image](https://user-images.githubusercontent.com/45955330/103840897-6ea8b500-50cd-11eb-8e20-c6fbd676f4d5.png)
![image](https://user-images.githubusercontent.com/45955330/103840908-7405ff80-50cd-11eb-82c4-e085eeb710ea.png)

**Comment by FelixKrueger** [comment]
Hi @oxygen26 

This has almost certainly to do with the fact that the coverage files call the cytosine context differently when a deletion is affecting the downstream bases adjacent to called cytosines. The genome-wide cytosine reports are however strictly reference sequence based. I have tried to describe this in more detail in the FAQ section: https://github.com/FelixKrueger/Bismark/blob/master/Docs/FAQ.md#issue-3

Would that explain whay you are seeing?

**Comment by oxygen26** [comment]
By all means, I should have read more carefully, thanks a lot : )

**Comment by FelixKrueger** [comment]
Not to worry, wishing a happy and healthy New Year!
