### ISSUE TITLE
speeding up bismark2bedgraph processing

### ISSUE THREAD

**Issue by shawpa** [FelixKrueger/Bismark#404]
I am trying to better understand the memory usage of the bismark2bedgraph script. I have always used a sort buffer size of 10G. I know from reading the userguide that I can change that but I am not really sure what I should try. I have access up to 28 cores where each core is 4.5GB/core. I currently use 3 cores and sort buffer size of 10G. If I wanted to double that would you suggest 6 cores with a sort buffer size of 20GB? Have you tested to see what the limit is or is that something I need to try on my own. I also have access to higher memory cores so I really don't have a memory limit. I once tried increasing the cores allocated but it didn't seem to change the processing time. However, I kept the --10G sort buffer setting so maybe that limited it.

I am processing very large WGBS files and I would like to shorten the process as much as possible. 

Thanks, 
Annie

**Comment by FelixKrueger** [comment]
Hi Annie,

the sorting process within `bismark2bedGraph` only uses a single core (using the linux `sort` function). Specifying more memory will allow `sort` to do more in memory (which is generally the fastest possible option), but if you exceed the buffer size `sort` will have to write out temporary sorting related files to disk. This process generally takes more time, relative to in-memory sorting, but I have never really done any benchmarking in this regard.

**Comment by shawpa** [comment]
Do you think I would get a speed increase if I used a core that was 37.5G and upped the buffer sort size?

Annie

**Comment by FelixKrueger** [comment]
possibly a little bit faster. If you just run the commands with `time` before, you could test it :)
