### ISSUE TITLE
bismark2report with multiple alignment_report

### ISSUE THREAD

**Issue by imerelli** [FelixKrueger/Bismark#405]
Hi Felix,
since using --multicore creates different output bam files and different alignment reports for each pairs of R1 and R2 fastq files passed to bismark (since --basename is not supported in combination with --multicore and I had to merge the resulting bam files using samtools afterwards), is there a way to use bismark2report for producing a single report for all the pairs of fastq files that correspond to a single sample? It seems that bismark2report can't take in input multiple alignment_reports.

**Comment by FelixKrueger** [comment]
If you end up with several files for a run due to `--parallel` then something must have gone wrong, or you haven't removed intermediate files from a previous run. The output of `--parallel` should be exactly the same as it were run in single-core mode, and especially for paired-end files there is a fair chance that merging the files afterwards went wrong. I would seriously suggest you get rid of manually merged files and intermediate files, and try once more....

**Comment by imerelli** [comment]
Sorry, maybe I wasn't clear. This is my command line:

bismark -o test --parallel 12 -1 MC1_1_S1_001_R1_val_1.fq.gz,MC1_1_S1_002_R1_val_1.fq.gz -2 MC1_1_S1_001_R2_val_2.fq.gz,MC1_1_S1_002_R2_val_2.fq.gz 

I cannot specify --basename (and I think --parallel is exatacly the same of --multicore). Then I get these results:

MC1_1_S1_001_R1_val_1_bismark_bt2_pe.bam
MC1_1_S1_001_R1_val_1_bismark_bt2_PE_report.txt
MC1_1_S1_002_R1_val_1_bismark_bt2_pe.bam
MC1_1_S1_002_R1_val_1_bismark_bt2_PE_report.txt

I don't see how the software could  produce something different without specifying the --basename. 

Please correct me if I'm wrong. Then I merged the two bam files using samtools. I don't think this can cause problems.

My questione is how to use bismark2report to create a single report about this analysis.

**Comment by FelixKrueger** [comment]
Ah OK. `bismark2report` would treat these files as separate runs, and there is currently no stand-alone facility to merge Bismark reports (even though similar code is used internally to merge multiple parallel runs when using the option `--parallel`).

If I were you I would probably merge the initial FastQ files before even running Trim Galore. That way you would then start with one set of merged FastQ files, and only generate a single set of result files.

```
gunzip -c MC1_1_S1_001_R1.fastq.gz MC1_1_S1_002_R1.fastq.gz | gzip -c - > MC1_1_S1_merged_R1.fastq.gz
gunzip -c MC1_1_S1_001_R2.fastq.gz MC1_1_S1_002_R2.fastq.gz | gzip -c - > MC1_1_S1_merged_R2.fastq.gz
```

Does that make sense?

**Comment by FelixKrueger** [comment]
Haven't heard back in a while, so I assume all is well.
