### ISSUE TITLE
Is there a way to resume a bismark run?

### ISSUE THREAD

**Issue by efratushava** [FelixKrueger/Bismark#407]
My run was going for 8 hours, and than stopped (due to resources allocation), and it wasn't enough time 0 the alignment was not completed.

Is there a way to resume the alignment from this point or I need to start everything from the beginning?

**Comment by FelixKrueger** [comment]
I'm sorry but there is no facilty to resume the run... Just make sure you use enough time, or consider specifying `--parallel` to decrease the run time (at the expense of increased resource consumption).

**Comment by efratushava** [comment]
Thank you for the very fast reply!

Shame...
I used `--multicore`

**Comment by FelixKrueger** [comment]
`--multicore` and `--parallel` are the same option. So then it really seems to be a time issue...

**Comment by efratushava** [comment]
Yes, probably.
Thank you!
