### ISSUE TITLE
bismark_methylation_extractor output ERROR

### ISSUE THREAD

**Issue by mmyoung** [FelixKrueger/Bismark#408]
I used the bismark_methylation_extractor function with parameters:` --no_overlap --paired-end --bedGraph --comprehensive --gzip --counts --remove_spaces  --buffer_size 10G  -o ${out_dir} $file_dir/AA.deduplicated.bam`
And get the output files: 
 CHG_context_AA.deduplicated.txt.gz
 CHG_context_AA.deduplicated.txt.gz
 CHG_context_AA.deduplicated.txt.gz
 **CpG_context_AA.deduplicated.txt.gz.spaces_removed.txt**
 AA.deduplicated.bedGraph.gz
 AA.deduplicated.bismark.cov.gz
 AA.deduplicated.M-bias.txt
 AA.deduplicated_splitting_report.txt

So I was wondering if the file `CpG_context_AA.deduplicated.txt.gz.spaces_removed.txt` was reasonable. Thanks a lot!!

**Comment by FelixKrueger** [comment]
Hi @mmyoung 

I am not exactly sure you think is the ERROR here as the issue title suggests? I suppose the files you find in the folder are:

```
CHG_context_AA.deduplicated.txt.gz
CHH_context_AA.deduplicated.txt.gz
CpG_context_AA.deduplicated.txt.gz
CpG_context_AA.deduplicated.txt.gz.spaces_removed.txt
```

(instead of three times CHG context files), and you are wondering why there is now the additional file called `spaced_removed.txt`? I suppose if you don't need that file you can just delete it. Just generally, if your BAM file doesn't have spaces (and I think files from Bismark don't have spaces), then you don't need to specify `--remove_spaces` as that file is a 100% identical copy of the original file `CpG_context_AA.deduplicated.txt.gz`.

I think you could simplify your command to:

```
bismark_methylation_extractor --bedGraph --comprehensive --gzip --buffer_size 10G -o ${out_dir} $file_dir/AA.deduplicated.bam
```

And it should do the the same thing. I hope this helps?

**Comment by mmyoung** [comment]
Thanks for your timely reply. I now understand the role of parameter `--remove_spaces`. But I noticed that the files `CpG_context_AA.deduplicated.txt.gz.spaces_removed.txt` and `CpG_context_AA.deduplicated.txt.gz`  don't have the same number of rows. Can you help me with this doubt?

**Comment by FelixKrueger** [comment]
Hmm, they should have the same number of lines... How did you determine the number of lines?

```
wc -l CpG_context_AA.deduplicated.txt.gz.spaces_removed.txt 
zcat CpG_context_AA.deduplicated.txt.gz | wc -l
```

This is how I would do it, and with a test case here it works just fine:

```
zcat CpG_context_test.txt.gz | wc -l
1045659
wc -l CpG_context_test.txt.gz.spaces_removed.txt
1045659 CpG_context_test.txt.gz.spaces_removed.txt
```

**Comment by mmyoung** [comment]
Yes, I did it in a similar way with you:
```
zcat CpG_context_B5T_BS_merge_sorted.deduplicated.txt.gz|wc -l
366217659
```

```
less -S CpG_context_B5T_BS_merge_sorted.deduplicated.txt.gz.spaces_removed.txt|wc -l
172594764
```

**Comment by FelixKrueger** [comment]
Hmm, not sure where the difference is coming from to be honest. what does `less -S` do? what happens if you run `wc -l CpG_context_B5T_BS_merge_sorted.deduplicated.txt.gz.spaces_removed.txt`? This is of course all a theoretical exercise, as you shouldn't use  `--remove_spaces` in the first place :)

**Comment by mmyoung** [comment]
OK, I will simply delete the `spaces_removed.txt` files then. Thanks again for your help.

But I get another question that bothers me a lot. Here is it:  As I can see, there aren't strand information for methylation sites in all output files with my command.  But I think the strand information is essential for downstream annotation. Should I turn to other tools for this information or there are any solutions with bismark? Do you have any recommendations?

**Comment by FelixKrueger** [comment]
Up to, and including, the coverage file (`.co.gz`), the methylation calls are simply based on position. You could relate back the coverage files to the reference genome using the tool `coverage2cytosine`. This script used the coverage files as input, and does just that. Here is more documentation about it: https://github.com/FelixKrueger/Bismark/tree/master/Docs#optional-genome-wide-cytosine-report-output

**Comment by mmyoung** [comment]
Got it. Thanks a lot for your time.
