### ISSUE TITLE
bam file empty

### ISSUE THREAD

**Issue by traceyjooste** [FelixKrueger/Bismark#410]
Dear Felix, 

After running bismark on paired-end (100bp) WGBS data using default parameters with the inclusion of the --non_directional option, the resulting "bismark_bt2.bam" file is empty upon successful completion. I've repeated the analysis on multiple input datasets and yet no change. 

Please find attached the report file. I'm running bismark/0.22.3 on a high performance cluster and have access to 12 cores and 128 GB memory. 
[M2_bismark_bt2_PE_report.txt](https://github.com/FelixKrueger/Bismark/files/5838733/M2_bismark_bt2_PE_report.txt)

**Comment by FelixKrueger** [comment]
This is the oddest thing! Judging by the report you attached, Bismark itself runs to completion (the time statement is literally the last thing it prints). Also, all 4 alignments run well and to completion - which is an indication that Bowtie 2 is also working well on your system.

It furthermore shows that specifying `--non_directional` is not warranted, your libraries seem to be directional. So just lose that option.

Now the operation that writes out a BAM file is a print stream to `samtools`, so my guess would be that something is wrong with the samtools installation on your system. Could you maybe also link the exact command you were using when invoking Bismark, and which version of Samtools are you using?

I'm sure we will get to the bottom of this somehow, your alignments definitely seem to have worked well.

**Comment by traceyjooste** [comment]
Thank you very much for the prompt response. The modules installed on the system are bowtie2/2.3.4 and samtools/1.9. 

Bismark usage: _bismark --bowtie2 --non_directional -o 03_Bismark_alignment/ --genome_folder Test_reference/ -1 02_PreProc/M2_R1.fq.gz -2 02_PreProc/M2_R2.fq.gz_

My plan is to batch it for all my samples once I'm familiar with the entire pipeline.

**Comment by FelixKrueger** [comment]
You command looks fine (just as a side, I hope the files were preprocessed with Trim Galore or an equivalent step?). I have just tried this out with a local sample here, and the following command:

```
bismark -o 03_Bismark_alignment/ --genome_folder /bi/scratch/Genomes/Yeast/Saccharomyces_cerevisiae/R64-1-1/ -1 02_PreProc/ZZZ_R1.fastq.gz -2 02_PreProc/ZZZ_R2.fastq.gz
```

This processed absolutely fine, and the results are, as expected, found in the folder `03_Bismark_alignment`:
```
ls 0* | cat
02_PreProc:
ZZZ_R1.fastq.gz
ZZZ_R2.fastq.gz

03_Bismark_alignment:
ZZZ_R1_bismark_bt2_pe.bam
ZZZ_R1_bismark_bt2_PE_report.txt
```

We are currently using samtools v1.11. If it wouldn't be rude I would ask if you could take another look in your 03_output directory again... (I am sure you have done that already). Could you maybe try making the command simpler (and only with a subset of sequences, e.g. 100 sequences so the alignments complete instantaneously) by e.g. losing the `-o` output command, or the relative path of the input files? maybe also saving the on-screen text of Bismark would help, in the beginning it should state most information about which files and paths are being used, to see if there are any error messages? Other than that I am a little lost for what else it could be, for me it is working just fine...

**Comment by traceyjooste** [comment]
Hey Felix, 

I've asked the cluster administrator to load a newer version of samtools and repeated the analysis as you recommended with a subset of 100 reads using samtools/1.10. It worked perfectly and the bam output generated is 31 kb. So your guess regarding the samtools was correct.

The simplified command I ran is:
`bismark --bowtie2 --genome_folder ../Test_reference/ -1 M3_R1_subset.fq.gz -2 M3_R2_subset.fq.gz`

I'm attaching on-screen output and log file just in case and have initialised a re-run of the alignment using my full dataset. 
[Screen_output.txt](https://github.com/FelixKrueger/Bismark/files/5842417/Screen_output.txt)
[M3_R1_subset_bismark_bt2_PE_report.txt](https://github.com/FelixKrueger/Bismark/files/5842418/M3_R1_subset_bismark_bt2_PE_report.txt)

Thank you very much for your time and assistance in this regard.

**Comment by FelixKrueger** [comment]
Perfect, I am glad this is now working well! All the best with the analysis!
