### ISSUE TITLE
Overlapping paired-end reads

### ISSUE THREAD

**Issue by aayushraman** [FelixKrueger/Bismark#411]
Hi,

I would like to know if there is a way to extract paired-end reads (and the genomic region) from the aligned bam file (after running the Bismark alignment step), where a certain part of R1 and R2 read overlaps the genomic location. For example, if R1 and R2 are the paired-end read then, I am interested in extracting this paired-end read from the bam file and extract the region that is between **.

    R1 ---**----------**>
            <**----------**---- R2 

Thanks,
-Ar

**Comment by FelixKrueger** [comment]
Bismark doesn't have any functionality to look at overlapping parts especially, for this kind of stuff would have to write your own solution I am afraid. I remember that in the early days some people were interested in looking at the consistency of overlapping methylation calls (if ithat is what you are after), so it is possible. I remember that the calls were ridiculously consistent (the discrepancy being much lower than 0.01% I think), but this was probably in 2011 or so, so my memory might fail me a little there....
