### ISSUE TITLE
bismark_genome_preparation fasta.gz

### ISSUE THREAD

**Issue by joncahn** [FelixKrueger/Bismark#412]
Hi,
It seems that fasta.gz files are not actaully considered and I think it comes from missing ".gz" in this part of the code:
### if there aren't any genomic files with the extension .fa, .fa.gz or .fasta we will look for files with the extension .fasta.gz
	unless (@filenames){
		@filenames =  <*.fasta>; ### should be @filenames =  <*.fasta.gz>;
	}
Sorry if the issue comes from me and not the code.
Keep up the good work!

**Comment by FelixKrueger** [comment]
This was indeed a bug, but luckily it took only 3 characters to have it fixed :) Thanks for bringing this to my attention, it is now part of the latest dev version (9faff88bd9b00d2ae2c156dc3d6892614f40dcf9).
