### ISSUE TITLE
Problems with CHH context extract

### ISSUE THREAD

**Issue by RubioB** [FelixKrueger/Bismark#414]
Hi Felix, 

I analyze methylation data with bismark and I have a problem with the command lines 'bismark2bedGrafph' and 'coverage2cytosine' in the CHH context. I get the following error message : "No last chromosome was defined, something must have gone wrong while reading the data in (e.g. specified wrong file path for a gzipped coverage file?). Please check your command!
slurmstepd: error: Detected 1 oom-kill event(s) in step 22544580.batch cgroup."

I have already tested several things after reading the answers to similar questions that you have already been asked. So, the last command line I tested is as follows : bismark2bedGraph -CX --scaffolds --buffer_size 300G -o out_CHH_T6_CTRL2 CHH_context_Merged_T6_CTRL2_R1_bismark_bt2_pe.deduplicated.txt
coverage2cytosine --genome_folder genome_folder -CX -o CHH_bismark_T6_CTRL2_CytoReport.txt out_CHH_T6_CTRL2.gz.bismark.cov.gz. 

I don't understand what is wrong and how can I fix the problem ? Is the file too large ? Is a memory or time problem ?

Thank you in advance for your help !

Bernadette

**Comment by FelixKrueger** [comment]
I am not exactly sure where the problem lies, but the main issue seems to be:

```
slurmstepd: error: Detected 1 oom-kill event(s) 
```

So the job ran out of memory, and got killed by the Slurm job scheduler. You might need to ask for more resources in your `sbatch` queing command.

**Comment by RubioB** [comment]
Ok thanks ! I understand that indeed it could be a memory problem. In my script I has requested --mem=300G. Would the solution be to increase --mem more (if yes, how much ?) ? Or, do I also have to request more cpu ? nodes ?

Thanks again !

________________________________
De : Felix Krueger <notifications@github.com>
Envoyé : lundi 8 février 2021 09:51
À : FelixKrueger/Bismark <Bismark@noreply.github.com>
Cc : RubioB <bernadetterubio@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [FelixKrueger/Bismark] Problems with CHH context extract (#414)


I am not exactly sure where the problem lies, but the main issue seems to be:

slurmstepd: error: Detected 1 oom-kill event(s)


So the job ran out of memory, and got killed by the Slurm job scheduler. You might need to ask for more resources in your sbatch queing command.

**Comment by FelixKrueger** [comment]
If you request 300G for SLURM, and 300GB within `bismark2bedGraph` you might end up with just a little bit more than that (even though this seems like an incredibly high amount already. I am afraid you will need to experiment with that a bit yourself.
