### ISSUE TITLE
Reads not aligning to the genome

### ISSUE THREAD

**Issue by ajwije** [FelixKrueger/Bismark#415]
I have 6 samples from Whole-genome bisulfite Illumina PE sequencing. Each file has 60-80 million reads. Two samples aligned well (70% and 72%). The other four samples had very few alignments (less than 1000 alignments). I checked both reads and both had more than 30 Phred quality across the reads and all insert lengths are less than 500bp based on Bioanalyzer traces from libraries. I also performed a BLAST analysis using a few reads and most of them aligned to the desired genome as expected. Here the code chunk I used:
`bismark --non_directional $Genome_path -1 $FIRST_SAMPLE_LOC \
  -2 $SECCOND_SAMPLE_LOC -o $ALIGN`
I can try to align two reads separately but wanted to see if you had any other suggestions.

**Comment by FelixKrueger** [comment]
Hi Asela,

Would you be able to send me a few samples reads, e.g. 100-200,000 reads completely raw and untrimmed (that should fit into an email). I could then run a few tests and get back to you?

**Comment by ajwije** [comment]
Thanks Felix!
I have sent it to your email address listed on Github. Hope it is fine.
Asela

**Comment by FelixKrueger** [comment]
I guess I should have remembered to ask which genome your samples are supposed to align against? It seems pretty clear that is it not a mammalian genome (possibly some plant?).

Otherwise the qualities look fine, so I am not sure if I will be able to point you to something more specific, but I’m happy to take another look if you can let me know the intended species..

Cheers, Felix

**Comment by ajwije** [comment]
I will send you the genome I used.
Asela

**Comment by FelixKrueger** [comment]
I have tried to align the reads to the genome you sent, or the soy bean genome I downloaded from Ensembl - the reads seem to align perfectly well in both single-end (~67%) and paired-end conditions (72%). Please see attached the MultiQC reports.

[SE PE reports.zip](https://github.com/FelixKrueger/Bismark/files/6015798/SE.PE.reports.zip)

Not sure why there are problems in your side? And by the way, the reads are directional and do NOT require the option `--non_directional`. Cheers, Felix

**Comment by FelixKrueger** [comment]
Haven't heard back for a while, I assume all is well.

**Comment by ajwije** [comment]
Sorry Felix - I realized that I haven’t replied. Yes, it worked.
Thanks for your help.
Asela

On Jul 20, 2021, at 9:44 AM, Felix Krueger ***@***.******@***.***>> wrote:

This Message Is From an External Sender
This message came from outside your organization.


Haven't heard back for a while, I assume all is well.

**Comment by FelixKrueger** [comment]
excellent, had a bit of a spring clean today. Glad it worked in the end!
