### ISSUE TITLE
Read level methylation rate

### ISSUE THREAD

**Issue by weishwu** [FelixKrueger/Bismark#417]
Hi,

I wonder if there is a simple way to get methylation rate (ratio of methylated C out of total C) for each read/alignment, and report the distribution of methylation rate across all reads.

**Comment by FelixKrueger** [comment]
I guess the tool that comes closest could be `methylation_constistency`, which does the following:

```
Bismark Methylation Consistency Module
======================================

SYNOPSIS

This program takes in a BAM file generated by Bismark and splits it into three smaller BAM files
based on the consistency of the methylation calls within the file. The reads are split into those
which show consistent methylation, consistent unmethylation and mixed methylation. Only methylation
in CpG context is considered. In its default condition, reads are considered as:

unmethylated  0 -  10% methylated (inclusive)
mixed:       10 -  90% methylated
methylated:  90 - 100% methylated (inclusive)
```

It should be fairly easy to not only get it to sort reads by its overall methylation, but maybe also add an additional tag?

**Comment by weishwu** [comment]
Thanks! This is very close to what I need.
It would be ideal if the relative information is stored in some tags of each alignment in the SAM file so that I can get an accurate value for each read.

**Comment by FelixKrueger** [comment]
In that script, you could just add a new tag to the BAM, e.g. `XO:Z:86.4` to show a read level methylation percentage. Should be not much more than a two line edit...

**Comment by weishwu** [comment]
I see what you mean. Thanks!
