### ISSUE TITLE
SAM flag explanation

### ISSUE THREAD

**Issue by weishwu** [FelixKrueger/Bismark#418]
Where can I find the explanation of each flag in the SAM output of Bismark, such as ZC, ZR, XL, XA, XB and YD?

**Comment by FelixKrueger** [comment]
I'm not sure whether Bismark reports all of the optional flags you mentioned above...

`XA` and `XB` can be optionally the number of non-bisulfite mismatches, but the others are not output by Bismark to my knowledge.
