### ISSUE TITLE
different results in fastq screen and bismark

### ISSUE THREAD

**Issue by prasundutta87** [FelixKrueger/Bismark#419]
Hi Felix,

I am not sure if you remember me, but just to give a small background on my project, I am working with a UMI based target enrichment methylation protocol. I am using the --barcode parameter of bismark in the deduplication stage. The barcode is the last element of the read ID and is separated by a ':' as instructed in the manual. 

Basically, methylation was done using an EMseq protocol (similar to bisulphite). But, in our case, all four strands were targetted by the target enrichment probes and hence, I believe running bismark in non-directional mode will be the best option. But, before running bismark, I did a fastq screen on raw fastq reads (without attached UMIs) and this is the plot I got:

![image](https://user-images.githubusercontent.com/25484608/110176739-b876f880-7dfb-11eb-858a-de0688bfd4a2.png)

Samples with R1 are read1 of the paired end set and samples with R3 are read 2 of the paired end set. R2 were the sequenced UMI, which was used downstream to attach them at the end of the read IDs. From the plot, we can clearly see that the read1s have aligned to the CTOT and CTOB strand whereas read 2s have aligned to OT and OB strand. 

However, when I ran bismark in paired-end non-directional mode (after attaching read IDs with UMI and trimming), extremely few reads aligned to the OT and OB strand and most of the reads aligned to only CTOT and CTOB strand. Please see the image below for reference:

![image](https://user-images.githubusercontent.com/25484608/110176868-e52b1000-7dfb-11eb-821d-d669297b7e72.png)

Of course, when I ran in directional mode, I got extremely small unique alignment. I am doing some more experiments and try running fastq screen on the unmapped reads, but would like to get your view on this issue. I am using bismark v0.22.3.

Regards,
Prasun

**Comment by FelixKrueger** [comment]
Hi Prasun,

you wrote: 
> But, in our case, all four strands were targetted by the target enrichment probes and hence, I believe running bismark in non-directional mode will be the best option. 
I would dispute that. Both the FastQ screen and the later Bismark results show that your Read 1 aligns to the `CTOT` and `CTOB` strands, which means that the data looks like a PBAT library and is not non-directional. Read 2, as the reverse complement of Read1, will align to the `OT` and `OB` strands, by definition. The overall orientation of the library is given by Read 1 only though. 

FastQ Screen runs Bismark in non-directional mode, but still you don't get alignments to all four strands. Trimming issues might have a role to play here, too (see below), but at first glance I woudl think that your samples require just the `--pbat` parameter.

You should be able to see this very easily when you run the data against your genome of interest in `--non_directional` mode (either Read1 on its own, or in paired-end mode): If almost all of your reads align to the `CTOT` and `CTOB` strands, the library is **not** non-directional.

As a word of caution, I believe both PBAT and also the EM-seq prototcol have biases on their 5' ends, especially for Read 2, which might require extensive trimming (e.g. using `trim_galore --paired --clip_r1 10 --clip_r2 20 R1.fastq.gz R2.fastq.gz`. Ideally, this trimming should also bring the mapping efficiency of R1 and R2 to the same level. If you need any help with this I'd be happy to take a look at some FastQC html profiles, or even take a look at a small subset of your data over here.

**Comment by prasundutta87** [comment]
Hi Felix,

Thanks for the reply. I have actually performed trimming using these parameters: -q 0 --clip_R1 10 --clip_R2 10 --three_prime_clip_R1 1 --three_prime_clip_R2 1

I am attaching fastqc reports of one of the samples (pre and post trimming) of one of the samples for which we saw very bad mapping efficiency. Post trimming ends with val1/val2
[pre-post-trimming_fastqc.zip](https://github.com/FelixKrueger/Bismark/files/6095665/pre-post-trimming_fastqc.zip)

I would also like to mention about the per base sequence content plots where read 1 shows G>A conversion and read 2 shows C>T. It should be vice versa, probably something is happenning in the library prep stage, or we are probably capturing and enriching only the complementary strands.

**Comment by FelixKrueger** [comment]
Thanks for the plots. I agree that in your case R1 is low in G, and R2 is low in C (as discussed above). From some EM-seq data I have been provided with before, it should indeed be the other way round, no idea what could be the cause for this in your case.

Regarding the trimming:

`--clip_R1 10 --clip_R2 10`

I can't exactly remember the details, but I think EM-seq might even need longer trimming than this (due to the EM-seq adaptor). This might be different in your case as something else might have gone (wr)on(g) see above)

`-q 0`

I don't think this is a good idea. While, yes, overall the qualities appear very good, there may still be some residues that have poorer qualities - and these may introdude spurious methylation calls. Also, your R2 has substantially poorer read qualities than R1, and there is a noticable fraction of reads that have an overal read quality of Phred10-20. I would just drop this.

`--three_prime_clip_R1 1 --three_prime_clip_R2 1`

This is not needed. The last base appears to be low in `A`, or `AG` or `AGA` at the end, but this is a consequence of adapter trimming. Just ignore it.

I hope you'll get to the bottom of it somehow. Don't hesitate to contact me again if you wanted me to take a look at something specific.

**Comment by prasundutta87** [comment]
Hi Felix,

Thanks a lot! I will follow the suggestions. Just a few more queries. From the first plot I shared, I could observe that more reads of read2 set map to OT/OB strand as compared to reads of read1 set to CTOT/CTOB. Just wondering if this can be explained. As in, why is it the case. 

My other question is that I took the unmapped reads I got after paired end alignment (--pbat mode), and run fastq screen on each of the fastq files (single-end-non-directional). I got the following results:

![image](https://user-images.githubusercontent.com/25484608/110224213-8b951500-7ed1-11eb-9c86-bde9000dcba4.png)

![image](https://user-images.githubusercontent.com/25484608/110224225-a36c9900-7ed1-11eb-8a6d-eef57f070087.png)

We see that a lot of reads got aligned in single ended mode. So, probably the paired end parameters are too strict in the bismark for my particular case and many paired end reads are not fulfilling the defaults (probably insert size). I will of course re-trim and do the paired end alignment and see if alignment improves or not. Can anything be checked in the sequencing end for this?

**Comment by FelixKrueger** [comment]
Hmm, this looks like a lot of reads align to the MT, or has light blue been used twice? This would then potentially be an issue for your library preparation...

You could relax the paired-end parameters a bit to see if this help, by e.g. using `--score_min L,0,-0.4` (the default os -0.2). You can also monitor if the number of reads rejected as multiple mapping increases in this case. If the EM conversion hasn't worked on some reads, you would probably expect some reads to be close to 100% methylated, others more unmethylated. You could check this with the script `methylation_consistency`.


I am not sure why R1 and R2 align at different rates, maybe it would help to work out whether there is still EM-seq adaptor in your reads? If you could get hold of that sequence, you could maybe add it as contaminant (adapter to the FastQC adapter list, and then you would see an additional line in the adapter contamination plot  (I would be quite interested in that sequence, if you have it).

**Comment by prasundutta87** [comment]
Hi Felix,

Actually the colour has been used twice by MultiQC. Human and MT have the same colour. But, the reads belong to human (just hovered my mouse over the bars). But, there are still no hits for a large number of reads (don't know where the reads have come from). Will plots in Counts (rather than Percentage) help. I can update the plots.

Thanks for the suggestion. I can try relaxing the paired-end parameter (will have a quick look into the scoring system used).

According to NEB website (https://international.neb.com/faqs/2021/01/15/what-sequences-need-to-be-trimmed-for-nebnext-libraries-that-are-sequenced-on-an-illumina-instrument), they seem to the same as Illumina adapters, so trim_galore in its default settings should work fine.

**Comment by FelixKrueger** [comment]
Yes the 3' read through are fine, TrimG alroe will find them, but I think EM-seq also adds specific EM-seq adaptors to the 5' end which can mess thing up. Why don't you send me one of your files so I can take a quick look over here and get back to you? a subset of both R1 and R2, untrimmed, would be fine.

**Comment by prasundutta87** [comment]
Hi Felix,

Thanks a lot! I have attached a subset of reads for your reference.
[test_sequences.zip](https://github.com/FelixKrueger/Bismark/files/6097728/test_sequences.zip)

**Comment by FelixKrueger** [comment]
Hi Prasun,

I have run few tests right now, but I a can't say I am any the wiser :) 

- I tried to align the data in PE mode, with increasing trimming from the 5' end (`--clip_r1 and --clip_r2` as 0, 10 and 20), and the mapping efficiencies were 17.5, 19 and 21. There is some effect, but it doesn't look very strong
- Trimming from the 3' end didn't increase mapping very much
- I did not find any contaminants, and we've got quite a selection of ususal suspects....
- relaxing the `--score_min` to `L,0,-0.4` or `L,0,-0.6` increased the mapping efficiency much more, up to ~35% I think. So there somehow seem to be errors in the data that prevent mapping.
- in PE mode, increasing `-X to 1000`, did not increase the mapping efficiency noticably 
- single end mapping started much higher than PE alignments. Allowing more mismatches brought up the mapping rates to 60%
- finally, I tried the big club and used `--local`. This increased the mapping efficiency in PE mode (`--pbat`) to >85%! it also changed the methylation levels somewhat. This is probably not exactly unexpected, as you will add quite a few 'dodgy' alignments.

I think this is probably where I would like to stop now. There is a chance that your data is indeed almost exclusively human material, but something is preventing proper paired-end alignments. I guess the next step would be to compare the alignemnts you get in `--local` mode with default end-to-end alignments, and then try to make sense of it all.... I hope this helps.

**Comment by prasundutta87** [comment]
Dear Felix,

Thanks you so so much for this. Based on my previous experiments with different samples with questionable mapping efficiency, I remember that --local mode in single-ended mode gave the highest mapping efficiency. It seems it is the same case with the sets of samples I am analysing now. Thanks again for this.

As suggested by you, I ran the methylation consistency script on three paired-end BAM files (not deduplicated)- one sample with questionable mapping efficiency, one methylated control sample and one unmethylated control sample. The results are as follows:

**One of the samples with low mapping efficiency**
Total single-end records     -  180604
-------------------------------------------------
All methylated    [ >= 90% ] -  58078 (32.16%)
All unmethylated  [ <= 10% ] -  35122 (19.45%)
Mixed methylation [ 10-90% ] -  21471 (11.89%)
Too few CpGs   [min-count 5] -  65933 (36.51%)

**Methylated control**
Total single-end records     -  1688020
-------------------------------------------------
All methylated    [ >= 90% ] -  217997 (12.91%)
All unmethylated  [ <= 10% ] -  1632 (0.10%)
Mixed methylation [ 10-90% ] -  19606 (1.16%)
Too few CpGs   [min-count 5] -  1448785 (85.83%)

**Unmethylated control**
Total single-end records     -  2015596
-------------------------------------------------
All methylated    [ >= 90% ] -  121 (0.01%)
All unmethylated  [ <= 10% ] -  231604 (11.49%)
Mixed methylation [ 10-90% ] -  854 (0.04%)
Too few CpGs   [min-count 5] -  1783017 (88.46%)

I am not sure, but methylation_consistency recognised the paired-end BAM file as single-end (**Single-end (SE) mode selected (auto-detected)**). The BAM files are paired-end only (I ran bisamark command using -1 and -2 and also bam file name ends with "_pe.bam".

I can understand the last tow tables where methylated control have higher 'All methylated' and unmethylated control have higher 'All unmethylated'. The first table seems likes a mixed result which should be expected. Is it okay to see a result like this?

**Comment by FelixKrueger** [comment]
The auto-detection has now been adressed, could you clone the current development version and see if it works for PE files? Thanks

**Comment by prasundutta87** [comment]
Thanks, Felix. Let me try downloading it, may have permission issues as I am working on a cluster..

**Comment by prasundutta87** [comment]
HI Felix,

These are the updated results for your reference (--pbat mode, 5' trimming as suggested and adapter removed, q --score-min L,0,-0.2 --ignore-quals --no-mixed --no-discordant --dovetail --maxins 500):

**One of the samples with low mapping efficiency**
Total paired-end records     -  90302
-------------------------------------------------
All methylated    [ >= 90% ] -  35853 (39.70%)
All unmethylated  [ <= 10% ] -  19153 (21.21%)
Mixed methylation [ 10-90% ] -  14090 (15.60%)
Too few CpGs   [min-count 5] -  21206 (23.48%)


**Methylated control**
Total paired-end records     -  844010
-------------------------------------------------
All methylated    [ >= 90% ] -  208577 (24.71%)
All unmethylated  [ <= 10% ] -  1397 (0.17%)
Mixed methylation [ 10-90% ] -  20092 (2.38%)
Too few CpGs   [min-count 5] -  613944 (72.74%)


**Unmethylated control**
Total paired-end records     -  1007798
-------------------------------------------------
All methylated    [ >= 90% ] -  196 (0.02%)
All unmethylated  [ <= 10% ] -  232609 (23.08%)
Mixed methylation [ 10-90% ] -  723 (0.07%)
Too few CpGs   [min-count 5] -  774270 (76.83%)
