### ISSUE TITLE
bismark2summary: No deduplication report present

### ISSUE THREAD

**Issue by igordot** [FelixKrueger/Bismark#42]
When I run `bismark2report`, it runs as expected:
```
Found 1 alignment reports in current directory. Now trying to figure out whether there are corresponding optional reports

Writing Bismark HTML report to >> AAA_bismark_bt2_PE_report.html <<

==============================================================================================================
Using the following alignment report:		> AAA_bismark_bt2_PE_report.txt <
Using the following deduplication report:	> AAA_bismark_bt2_PE_report.deduplication_report.txt <
No splitting report file specified, skipping this step
No M-bias report file specified, skipping this step
No nucleotide coverage report file specified, skipping this step
==============================================================================================================


Processing alignment report AAA_bismark_bt2_PE_report.txt ...
Complete

Processing deduplication report AAA_bismark_bt2_PE_report.deduplication_report.txt ...
Complete
```
But then I run `bismark2summary` and it can't find the deduplication report:
```
No Bismark/Bowtie2 single-end BAM files detected
Found Bismark/Bowtie2 paired-end files
No Bismark/Bowtie single-end BAM files detected
No Bismark/Bowtie paired-end BAM files detected

Generating Bismark summary report from 1 Bismark BAM file(s)...
>> Reading from Bismark report: AAA_bismark_bt2_PE_report.txt
No deduplication report present, skipping...
No methylation extractor report present, skipping...

Wrote bismark project summary to bismark_summary_report.html
```
How can that be?

**Comment by FelixKrueger** [comment]
Hi igor,

`bismark2summary` assumes the current naming convention that Bismark produces by default, so in your case it would require a .bam file, and derive the other report names from the base name that bam file. It expects:

- AAA_bismark_bt2_pe.bam
- AAA_bismark_bt2_PE_report.txt
- AAA_bismark_bt2_pe.deduplication_report.txt

your deduplication report however is:
- AAA_bismark_bt2_PE_report.deduplication_report.txt

`bismark2report` is a little more lenient there as it only requires that the report starts with the file base name and ends in 'deduplication_report.txt', effectively ignoring the part in your file name that shouldn't be there. Were you using an older version of Bismark to generate these reports, or did you rename them yourself?

**Comment by igordot** [comment]
I was renaming them myself (sorry, I don't like the default names). I didn't realize I made a mistake since `bismark2report` was recognizing it.

I also noticed that `bismark2report` can process a coverage file now. In `bismark`, the flag is `--nucleotide_coverage`, but in the `bismark2report` help, it says it should be `--nucleocov`.

**Comment by FelixKrueger** [comment]
The "methylation extractor report" ends in 'splitting_report.txt', and this is generated by the Bismark methylation extractor (`bismark_methylation_extractor`).

Thanks for spotting the discrepancy in the help text, I have changed that now here  1b316fa559eca59fec2bb953ba849981ed83cec4.

**Comment by igordot** [comment]
I have a splitting report. According the `bismark2report`:
```
==============================================================================================================
Using the following alignment report:		> AAA_bismark_bt2_PE_report.txt <
Using the following deduplication report:	> AAA_bismark_bt2_pe.deduplication_report.txt <
Using the following splitting report:		> AAA_bismark_bt2_splitting_report.txt <
Using the following M-bias report:		> AAA_bismark_bt2.M-bias.txt <
No nucleotide coverage report file specified, skipping this step
==============================================================================================================
```
And then `bismark2summary`:
```
>> Reading from Bismark report: AAA_bismark_bt2_PE_report.txt
No methylation extractor report present, skipping...
```

**Comment by FelixKrueger** [comment]
Similar to the post above `bismark2summary` expects the splitting to be "{base name}_pe.deduplicated_splitting_report.txt" like so:

- AAA_bismark_bt2_pe.bam
- AAA_bismark_bt2_PE_report.txt
- AAA_bismark_bt2_pe.deduplicated_splitting_report.txt

**Comment by igordot** [comment]
That fixed it! I forgot about ".deduplicated" part. Thank you so much for all the help.

**Comment by FelixKrueger** [comment]
Excellent!
