### ISSUE TITLE
How to interpret CHG_context and CHH_context files

### ISSUE THREAD

**Issue by mapostolides** [FelixKrueger/Bismark#421]
Hi Felix,

I'm wondering how I might interpret the contents of these files. Is there some documentation explaining their contents? I see the following but without a header it is difficult to make sense of it:

CHG_context
```
HWI-C00124:125:C6VJYANXX:2:1101:10003:20498_1:N:0:CGATGT        -       chr13   73408483        x
HWI-C00124:125:C6VJYANXX:2:1101:10002:99497_1:N:0:CGATGT        -       chr4    6187091 x
HWI-C00124:125:C6VJYANXX:2:1101:10003:20498_1:N:0:CGATGT        -       chr13   73408490        x
```

CHH_context
```
HWI-C00124:125:C6VJYANXX:2:1101:10003:20498_1:N:0:CGATGT        -       chr13   73408465        h
HWI-C00124:125:C6VJYANXX:2:1101:10002:99497_1:N:0:CGATGT        -       chr4    6187094 h
HWI-C00124:125:C6VJYANXX:2:1101:10003:20498_1:N:0:CGATGT        -       chr13   73408469        h
```

Thanks,
Michael

**Comment by mapostolides** [comment]
Thanks Felix! I'm wondering, is it possible to produce a ".cov" file which contains the coverage for non-CpG loci? I notice that the 3 files produced from the `--comprehensive` file use a binary representation of methylated/unmethylated

**Comment by FelixKrueger** [comment]
yes, that's certainly possible. Either you run `bismark_methylation_extractor --CX --bedGraph`, or, if you already have the non-CG context files, you can also run `bismark2bedGraph -o nonCG_output.bedGraph CH*` straight away.
