### ISSUE TITLE
Deduplicate_bismark error

### ISSUE THREAD

**Issue by RubioB** [FelixKrueger/Bismark#423]
Hi Felix, 

I encounter a problem during the deduplication step. Here is the error that is displayed : 

If there are several alignments to a single position in the genome the first alignment will be chosen. Since the input files are not in any way sorted this is a near-enough random selection of reads.

Checking file >>merge_R1_3FC7A2P0_1_1_DNA_bismark_bt2_pe.bam<< for signs of file truncation...

Now testing Bismark result file merge_R1_3FC7A2P0_1_1_DNA_bismark_bt2_pe.bam for positional sorting (which would be bad...)	...passed!
Output file is: merge_R1_3FC7A2P0_1_1_DNA_bismark_bt2_pe.deduplicated.bam

Use of uninitialized value $line1 in concatenation (.) or string at /usr/local/bioinfo/src/Bismark/Bismark_v0.20.0/deduplicate_bismark line 296, <IN> line 29638597.
Failed to determine read and genome conversion from line: 

slurmstepd: error: Job 23598381 exceeded memory limit (2104216 > 2097152), being killed
slurmstepd: error: Exceeded job memory limit
slurmstepd: error: *** JOB 23598381 ON node125 CANCELLED AT 2021-03-12T10:35:10 ***
slurmstepd: error: Detected 1 oom-kill event(s) in step 23598381.batch cgroup.

I saw that it could be due to a corrupted bam file. So I went back to the alignement results but I have no errors anywhere.
I also resquested more memory for my job (up to 300G) but that doesnt change anything. Besides, my other samples whose bam files are sometimes larger did not have any problems related to the memory requested. 

I'm not sure what to test anymore, do you have any suggestions ? 

Thanks in advance !

Bernadette

**Comment by FelixKrueger** [comment]
This does indeed look like the job is getting killed as it exceeds 2GB of memory (maybe that is your default setting?). Do you, and how do you request enough memory? How was the file merged (I assume it was as it is in the name)? Can you run something like
`samtools view merge_R1_3FC7A2P0_1_1_DNA_bismark_bt2_pe.bam | tail`: does this produce proper output? How big is the BAM file, maybe you can simply run it on your head-node, or in an interactive session to avoid submitting the job to the queue to see if that works?

**Comment by RubioB** [comment]
Thank you for your answer ! I launched the job in an interactive session as you suggested and it works !
I think the problem was related to the fact that I already have other jobs on the way that used a lot of memory and so I exceeded the limit with this job !
Anyway, thank you very much !

Bernadette


________________________________
De : Felix Krueger ***@***.***>
Envoyé : vendredi 12 mars 2021 13:08
À : FelixKrueger/Bismark ***@***.***>
Cc : RubioB ***@***.***>; Author ***@***.***>
Objet : Re: [FelixKrueger/Bismark] Deduplicate_bismark error (#423)


This does indeed look like the job is getting killed as it exceeds 2GB of memory (maybe that is your default setting?). Do you, and how do you request enough memory? How was the file merged (I assume it was as it is in the name)? Can you run something like
samtools view merge_R1_3FC7A2P0_1_1_DNA_bismark_bt2_pe.bam | tail: does this produce proper output? How big is the BAM file, maybe you can simply run it on your head-node, or in an interactive session to avoid submitting the job to the queue to see if that works?
