### ISSUE TITLE
soft-clipped primer bases in the .cov.gz files 

### ISSUE THREAD

**Issue by smzuniga** [FelixKrueger/Bismark#424]
Hi,
I have two different amplicon-based designs, one with no overlapping amplicons, so here primer trimming is not an issue, but I have a different design in which amplicons overlap. To check the behavior of the different bismark tools, I'm working on the first dataset (no overlaping amplicons) and a control sample that should not provide any methylated signal at all. In the .cov.gz files provided by the bismark_methylation_extractor script, the primer bases show methylation signals in the negative control so for the second design, where amplicons overlap, I'd need to find a way to remove the primers. The first thing I've done is to apply bamclipper, a tool that soft-clips primers bases from bam files. Providing this bam as input to the bismark_methylation_extractor script still shows methylation in primer bases. Is there any way to not count the methylated soft-masked bases that belong to the primer in bismark? Is there any alternative you could recommend to avoid results in primer regions in amplicon-based data?

Thanks very much in advance.

Best regards.

Sheila

**Comment by FelixKrueger** [comment]
Hi Sheila,

I think it might help if you could maybe email me a slide or two explaining how the experiment is designed exactly. Options could be to remove the primer sequence from the start (e.g. as a 5' trimming with Trim Galore), or use the `--ignore` functionality of the the methylation extractor.

**Comment by smzuniga** [comment]
Hi Felix,
Thanks very much for your quick reply.
When analyzing target-Seq data I usually soft-clip primer bases and I was hoping to apply the same strategy to methylation data. 
The way you recommend would imply that trimming is performed at both 5' and 3' ends of all reads from any amplicon since most read pairs overlap completely and the reverse complement primer from the other end might also be at the end of reads. This way the number of removed bases at both 5' and 3' ends in all reads should be equal to the maximum primer length. If applying this strategy, some uncovered regions show up. 
I think we need to design primers again to allow a 50-60bp trimming (depending on the maximum primer length).

Thanks very much again for your advice.

Best regards,

Sheila
