### ISSUE TITLE
CpG_report.txt contains repeated chromosomes

### ISSUE THREAD

**Issue by julienrichardalbert** [FelixKrueger/Bismark#426]
Hi Felix & co,

For an unknown reason, the output of bismark_methylation_extractor is extremely large (>300Gb, zipped). Checking column 1, I get:

`zcat rat_MII_oocyte_PBAT_BrindAmour2018_DRR126422_PE_raw_rmDup.CpG_report.txt.gz | cut -f1 | uniq -c | grep -v "random" | grep -v "KL" | grep -v "Un"`

3427866 chr3
3276106 chr4
    606 chrM
2664340 chr10
1986619 chrX
1718382 chr16
1422134 chr19
1676668 chr18
2142088 chr14
2018593 chr15
5380374 chr1
4426096 chr2
2889890 chr7
2889890 chr7
2889890 chr7
2889890 chr7
2889890 chr7
2889890 chr7
2889890 chr7
2889890 chr7
2889890 chr7
2889890 chr7
3318682 chr5
3318682 chr5
3318682 chr5

`bismark_methylation_extractor -p --multicore 4 --buffer_size 80% --comprehensive --merge_non_CpG --bedGraph --counts --cytosine_report --gzip --genome_folder $PATH_TO_GENOME "$FILE"_deduplicated.bam `

Any ideas would be greatly appreciated!
Julien

**Comment by FelixKrueger** [comment]
Hi Julien,

This is really odd. Do you also see several times the same chromosome name when your last pipe is just `| uniq`?

You stated:
 > the output of bismark_methylation_extractor is extremely large (>300Gb, zipped)

Which output did you mean with this, is it the `CpG*` files? So I assume the coverage files were created fine and without errors? What happens when you run the above command on the coverage file?

```
zcat coverage_file.cov.gz | cut -f1 | uniq -c 
``` 

can you show the first 10 lines of the `CpG*`, coverage and CpG report files?

Your input file is called:
`rat_MII_oocyte_PBAT_BrindAmour2018_DRR126422_PE_raw_rmDup.CpG_report.txt.gz`. As the filename contains `raw_rmDup` I am wondering whether you used any third part tools on the BAM file to start with?

I can't really think of a reason why this might have happened, could there maybe be non-printable characters after the chromosome names that prevent it from running properly? Maybe you could upload a small section of the your BAM file to an FTP server (which I can provide), and I take a look here?

**Comment by julienrichardalbert** [comment]
Hi Felix,

Apologies for not being explicit with the extractor output file. I meant this optional one (called CpG report I believe):

> (Optional): genome-wide cytosine report output
> Starting from the coverage output, the Bismark methylation extractor can optionally also output a genome-wide cytosine methylation report. The module coverage2cytosine (part of the Bismark package) may also be run individually. It is also sorted by chromosomal coordinates but also contains the sequence context and is in the following format:
> <chromosome> <position> <strand> <count methylated> <count unmethylated> <C-context> <trinucleotide context>

Now that I've just re-read the doc quote above, maybe I should be running coverage2cytosine separately? As the first chromosome of my output file is chr3, which is not sorted. 

> I am wondering whether you used any third part tools on the BAM file to start with?

Yes the BAM file name is being handled by a Bash script I've rigged together, though the "rmDup" simply refers to a bismark_deduplicate-d BAM. I just changed the name to be consistent across HTS data types. Otherwise, the BAM file itself was generated by default PE alignment using bismark. 

> I can't really think of a reason why this might have happened, could there maybe be non-printable characters after the chromosome names that prevent it from running properly?
That rat rn6 genome has many unplaced contigs with strange names. In fact, you reminded me of an error I got when running ChromHMM on rat ChIP-seq data. Removing all unplaced contigs using grep -v worked... maybe I'll try this for bismark, too! Thank you!

I will have to get back to you regarding your other troubleshooting recommendations next week, I'm off 'till then. I didn't expect such a quick response, thank you!

**Comment by FelixKrueger** [comment]
Next week is perfectly fine. 

And yes, all steps can also be carried out separately, so you could use the `CpG*` files as input for `bismark2bedGraph`. If you say that the rat genome has a ton of unplaced contigs, you might want to make sure that it's not too many for the operating system to handle. If there are error messages, usually the option `--scaffold/gazillion` works like a treat.

Once this has worked, you can also re-run `coverage2cytosine` on the coverage files. I don't there is a need to explude any contigs here, at least not for the processing itself. 

Good luck, and I am happy to assist at any stage. 
Have a good weekend, Felix

**Comment by julienrichardalbert** [comment]
Hi again,

Apologies for the delay, we had a COVID scare at the institute and I couldn't access the lab computer!
Anyway, I have good news to report.

During my quarantine it dawned on me that bismark_methylation_extractor has a sort step, and that running >1 instances of bismark_methylation_extractor is probably generating some kind of Frankenstein temporary file. I tested this by running only 1 instance of my script (without any edits to it) and it completed just fine. 

Normally, I run bismark and associated scripts on an HPC. Here, I think I was getting errors because I've been working on a local machine. Your software runs perfectly fine and I was just misusing it! 
Thank you again for your help,
Julien

**Comment by FelixKrueger** [comment]
Hi Julien,

That's good news (even though the Frankenstein scenario is somewhat mysterious still...)! I hope the Covid-19 situation is back under control as well.

If you don't object I'll just close this issue for now then, do let me know if there are anty further issues.
