### ISSUE TITLE
Exit code non-zero when genome_preparation finishes?

### ISSUE THREAD

**Issue by hans-vg** [FelixKrueger/Bismark#427]
I am trying to create a snakemake pipeline using bismark. I had to update the wrapper environment.yaml for both bismark and bowtie2 to get it to build most of the database: https://github.com/hans-vg/snakemake-wrappers/tree/master/bio/bismark/bismark_genome_preparation

Now it looks like it should be completing the genome preparation step, but snakemake is detecting an error, deleting the output folder, so I can't make sure if the data was actually written. 

Any suggestions on how to debug this error would be greatly appreciated. What would be useful is knowing what the end of the log looks like when it successfully builds an index. Does it look similar to my log output?

End of log below
```
Total time for backward call to driver() for mirror index: 00:16:49
Exited Ebwt loop
fchr[A]: 0
fchr[C]: 380384135
fchr[G]: 380384135
fchr[T]: 694080965
fchr[$]: 1388472180
Exiting Ebwt::buildToDisk()
Returning from initFromVector
Wrote 483472949 bytes to primary EBWT file: BS_CT.rev.1.bt2
Wrote 347118052 bytes to secondary EBWT file: BS_CT.rev.2.bt2
Re-opening _in1 and _in2 as input streams
Returning from Ebwt constructor
Headers:
    len: 1388472180
    bwtLen: 1388472181
    sz: 347118045
    bwtSz: 347118046
    lineRate: 6
    offRate: 4
    offMask: 0xfffffff0
    ftabChars: 10
    eftabLen: 20
    eftabSz: 80
    ftabLen: 1048577
    ftabSz: 4194308
    offsLen: 86779512
    offsSz: 347118048
    lineSz: 64
    sideSz: 64
    sideBwtSz: 48
    sideBwtLen: 192
    numSides: 7231626
    numLines: 7231626
    ebwtTotLen: 462824064
    ebwtTotSz: 462824064
    color: 0
    reverse: 1
Total time for backward call to driver() for mirror index: 00:16:51
```

**Comment by hans-vg** [comment]
Snakemake rule needed to be updated for the output folder. I am doing my first mapping now, but will see if it finishes successfully.

**Comment by FelixKrueger** [comment]
Excellent, let me know if you require anything!
