### ISSUE TITLE
In the CpG_report.txt, first CpG is skipped

### ISSUE THREAD

**Issue by kojimak324** [FelixKrueger/Bismark#428]
Thank you for your work, Felix.

In the CpG_repot.txt file, there is an example like below.

NTIC01031111.1  329751  -       0       0       CG      CGG
NTIC01031111.1  329753  +       0       0       CG      CGG
NTIC01031111.1  329754  -       0       0       CG      CGG
NTIC01032222.1  1       +       0       0       CG      CGC
NTIC01032222.1  29      +       0       0       CG      CGC
NTIC01032222.1  30      -       0       0       CG      CGA

In NTIC01032222.1, + is followed by +.
I think the reason is there is no third nucleotide (right column) in - (position 2).
If I hope to get the coverage in position2 CpG, what I should do?

Thank you.

**Comment by FelixKrueger** [comment]
Hi @kojimak324 

I think you are right about why position 2 is getting skipped here. 

I can currently picture three possible scenarios as potential solutions to this:
- you you could try to identify the position in `coverage2cytosine` that skips the position in the the trinucleotide context cannot be extracted fully, and somehow comment it out
- you could add that position manually, by simply extracting the information for that position from the coverage file. Something like this should work:
```
gunzip -c coverage_file.cov.gz | grep -P 'NTIC01032222.1\t2\t'
```
This would get you the position 2 and its methylation counts, and you could then make up a line in the format of the CpG report:

```
NTIC01032222.1  2      -       0       0       CG      CGN
```
-  The probably easiest solution would be to add an additional nucleotide to the start of that transcript, I would suggest adding an 'N'. This way, it should all work out of the box, but I'm afraid it would require re-mapping as the positions will get shifted by 1.

I hope one of these solutions will help?

**Comment by kojimak324** [comment]
Hi Felix,

Thank you for your quick and appropriate response.
I think your solutions will help me!

Best regards.
