### ISSUE TITLE
bismark 0.23.0 run end prematurely with generation of empty files 

### ISSUE THREAD

**Issue by missuse** [FelixKrueger/Bismark#429]
Hi,

I am a first time user of bismark, and I just wanted to say the documentation you prepared is very clear and helped me immensely. Thank you.

The problem I am encountering might be due to my machine, but since I am unable to verify this atm, I decided to post here just in case this is a global problem.

I am running bismark via wsl2 (Ubuntu 20.04) on windows 10 (19041.928), I installed bismark 0.23.0 via conda in a new environment.

per my config wsl2 can utilize 10 threads and 24 GB of RAM (system available is 12 threads and 32 GB)

When I try to run bismark, after the initial printout the run ends immediately and the generated bismark_bt2_pe.bam and bismark_bt2_PE_report are empty.

The last few lines of the printout:

```
Found first alignment:
ST-E00181:933:HFWKTCCX2:8:2116:17837:7884_1:N:0:GAACCAAG+CATGAGCA/1     77      *       0       0       *       *       0       0       TGTATGGGAATTTAGTGTATGGGATGATTTAAGGTTTTGTTTTTATGATGTTAATAATGGAAGTAGAATTATTTTAATAATGTGGAATTTTGAAGTTGTTAATTGTGTTATATTTATTAGTTTATTTTTG       JJJJJJJJJJJJJJJJFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFJJJJJJJJJJJJJJJJJJJFFJJJJJJJJJFJJJJJJJJJJJJJJJJJJJJJJJJJJJFJJJJJ       YT:Z:UP
ST-E00181:933:HFWKTCCX2:8:2116:17837:7884_2:N:0:GAACCAAG+CATGAGCA/2     141     *       0       0       *       *       0       0       TTAATACATATAAAATATCCATCCACATTAAACTTCAAATCTCAAACTCAATTAAAAAATCAAATACAAAAAACTAACCTCTACTTATAACCTTAAATAATTCTTCTACATTTTCCAAAACAAA     JFFJJFJJJFJJFJFAFJJJFAJJFJFJFFJJJJAA-7JFFJJ<FFFFFJJJJAJJJJJJJJJJJJFJJJJJFJJFJFJJJJFJJJJJJJJJJ7AFJFFJJJJJFJJJJFFJFJFJJ7--AJA<     YT:Z:UP
Now starting a Bowtie 2 paired-end alignment for CTread1GAread2GAgenome (reading in sequences from ctrl1_val_1.fq.gz_C_to_T.fastq and ctrl2_val_2.fq.gz_G_to_A.fastq, with the options: -q --score-min L,0,-0.2 --ignore-quals --no-mixed --no-discordant --dovetail --maxins 500 --nofw))
Found first alignment:
ST-E00181:933:HFWKTCCX2:8:2116:17837:7884_1:N:0:GAACCAAG+CATGAGCA/1     77      *       0       0       *       *       0       0       TGTATGGGAATTTAGTGTATGGGATGATTTAAGGTTTTGTTTTTATGATGTTAATAATGGAAGTAGAATTATTTTAATAATGTGGAATTTTGAAGTTGTTAATTGTGTTATATTTATTAGTTTATTTTTG       JJJJJJJJJJJJJJJJFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFJJJJJJJJJJJJJJJJJJJFFJJJJJJJJJFJJJJJJJJJJJJJJJJJJJJJJJJJJJFJJJJJ       YT:Z:UP
ST-E00181:933:HFWKTCCX2:8:2116:17837:7884_2:N:0:GAACCAAG+CATGAGCA/2     141     *       0       0       *       *       0       0       TTAATACATATAAAATATCCATCCACATTAAACTTCAAATCTCAAACTCAATTAAAAAATCAAATACAAAAAACTAACCTCTACTTATAACCTTAAATAATTCTTCTACATTTTCCAAAACAAA     JFFJJFJJJFJJFJFAFJJJFAJJFJFJFFJJJJAA-7JFFJJ<FFFFFJJJJAJJJJJJJJJJJJFJJJJJFJJFJFJJJJFJJJJJJJJJJ7AFJFFJJJJJFJJJJFFJFJFJJ7--AJA<     YT:Z:UP

>>> Writing bisulfite mapping results to ctrl1_val_1_bismark_bt2_pe.bam <<<
```

I should note that `bismark_genome_preparation` appears to run and finish normally.

At first I was certain this was due to my inexperience, however after some fiddling with this problem
I installed bismark 0.22.3 via conda in a new environment and everything runs smoothly and as expected based on the documentation.

This could be a problem with wsl2 in which case I know and completely understand you should not spend your time on fixing it since the use case is very specific, however if this is reproducible when running on linux then it might be worth looking into.

Thank you and all the best,

Milan

**Comment by FelixKrueger** [comment]
Hi Milan,

To be perfectly honest this is the first time I hear about someone using Bismark on a Windows machine, but I suppose if the Linux subsystem works well then there isn't a reason why it wouldn't work.

The 'first alignment' looks somewhat weird as well, because it is not actually an alignment at all but merely a SAM representation of a sequence (no chromosome, both reads unmapped). So I would need to look into this further, but if you say you found a solution then I'd also be OK if you could use that :)

**Comment by missuse** [comment]
Hi Felix,

thanks for the fast reply.

It seems installing the older bismark version (0.22.3) solved the problem for me.

I am attaching the report from a dummy run where a sample of 1 million PE reads was used. 

[sub1_bismark_bt2_PE_report.txt](https://github.com/FelixKrueger/Bismark/files/6331768/sub1_bismark_bt2_PE_report.txt)

Please let me know if this seems ok?

The genome used is potato v6.1 - http://solanaceae.plantbiology.msu.edu/dm_v6_1_download.shtml

the reads are from a different tetraploid line of potato.

If this report seems good then there is no need to look further for fixes to my problem.

I posted the issue because I believe there is a problem with the conda installation of the latest bismark (0.23). Perhaps some incompatibility  between the bowtie2 version installed by default and bismark could cause a problem, if that is at all possible?

I mentioned I was running via wsl2 because this could be the culprit, and as you say not many people use it. It didn't seem correct to omit this detail. However I do not think the problem is due to wsl because 1. this would be the first time I experience a problem of this sort 2. because the older version of the same software works.

**Comment by FelixKrueger** [comment]
Hi Milan,

thanks for the additional details. The alignment report you attached looks pretty good to me, so as long as there wasn't anything in the 0.23.0 release that you need you should be good to proceed with that version. 

It is still odd that the latest version doesn't seem to work in your hands, but for the moment I would probably just acknowledge it and only take action if this happens for other people as well (I wouldn't exactly know what to do though, maybe contact the guys at Bioconda?)

All the best! Felix

**Comment by FelixKrueger** [comment]
PS: I love your avatar, Walt!

**Comment by missuse** [comment]
Thanks Felix and all the best!

Milan

**Comment by coffeeCowLu** [comment]
> Hi Milan,
> 
> To be perfectly honest this is the first time I hear about someone using Bismark on a Windows machine, but I suppose if the Linux subsystem works well then there isn't a reason why it wouldn't work.
> 
> The 'first alignment' looks somewhat weird as well, because it is not actually an alignment at all but merely a SAM representation of a sequence (no chromosome, both reads unmapped). So I would need to look into this further, but if you say you found a solution then I'd also be OK if you could use that :)

##############
When installing Bismark through Conda and using multithreaded analysis, the main reason for this phenomenon is that "samtools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory" .
Just create soft link for libcrypto.so.1.0.0 in /yourenvs/lib by "ln  -s  libcrypto.so.3   libcrypto.so.1.0.0".
