### ISSUE TITLE
error: No last chromosome was defined

### ISSUE THREAD

**Issue by avilella** [FelixKrueger/Bismark#43]
Hi,

I am running bismark methylation extractor (head master branch) and it looks like it's unable to produce the `CpG_report.txt` files:

```
cd /bi/group/cegx/CEGX_Run196/CEGX_Run196-12345678/CEG40_90_9-36442469/ && /bi/home/rocks-av/avilella/Bismark/bismark_methylation_extractor --samtools_path=/bi/apps/samtools/0.1.18/samtools --ignore 6 --genome_folder /bi/group/cegx/Genomes/Human/hs38DH_orig --multicore 8 --buffer_size 20G --cytosine_report  --bedGraph --gzip --single-end /bi/group/cegx/CEGX_Run196/CEGX_Run196-12345678/CEG40_90_9-36442469/CEG40-90-9_S1_L001_R1_001.cutB.sorted.mrgd.barcoded.bam
```

The counting txt files look correct:

```
-rw-r--r-- 1 rocks-av cegx 1091252162 Jun  3 10:04 CHG_CTOT_CEG40-90-9_S1_L001_R1_001.cutB.sorted.mrgd.barcoded.txt.gz
-rw-r--r-- 1 rocks-av cegx 2328942363 Jun  3 10:04 CHH_CTOT_CEG40-90-9_S1_L001_R1_001.cutB.sorted.mrgd.barcoded.txt.gz
-rw-r--r-- 1 rocks-av cegx  462080614 Jun  3 10:04 CpG_CTOT_CEG40-90-9_S1_L001_R1_001.cutB.sorted.mrgd.barcoded.txt.gz
-rw-r--r-- 1 rocks-av cegx  957859394 Jun  3 10:04 CHG_CTOB_CEG40-90-9_S1_L001_R1_001.cutB.sorted.mrgd.barcoded.txt.gz
-rw-r--r-- 1 rocks-av cegx 2067793732 Jun  3 10:04 CHH_CTOB_CEG40-90-9_S1_L001_R1_001.cutB.sorted.mrgd.barcoded.txt.gz
-rw-r--r-- 1 rocks-av cegx  406603928 Jun  3 10:04 CpG_CTOB_CEG40-90-9_S1_L001_R1_001.cutB.sorted.mrgd.barcoded.txt.gz
-rw-r--r-- 1 rocks-av cegx        856 Jun  3 10:04 CEG40-90-9_S1_L001_R1_001.cutB.sorted.mrgd.barcoded_splitting_report.txt
-rw-r--r-- 1 rocks-av cegx      12492 Jun  3 10:04 CEG40-90-9_S1_L001_R1_001.cutB.sorted.mrgd.barcoded.M-bias.txt
-rw-r--r-- 1 rocks-av cegx       7399 Jun  3 10:04 CEG40-90-9_S1_L001_R1_001.cutB.sorted.mrgd.barcoded.M-bias_R1.png
```

But when it tries to produce the cytosine report part, it fails. The `.temp` files also look correct. See below. Any ideas?

```
Stored sequence information of 3366 chromosomes/scaffolds in total

==============================================================================
Methylation information will now be written into a genome-wide cytosine report
==============================================================================

>>> Writing genome-wide cytosine report to: CEG40-90-9_S1_L001_R1_001.cutB.sorted.mrgd.barcoded.CpG_report.txt.gz <<<

No last chromosome was defined, something must have gone wrong while reading the data in (e.g. specified wrong file path for a gzipped coverage file?). Please check your command!



Finished generating genome-wide cytosine report
```

**Comment by FelixKrueger** [comment]
It appears that it didn't read any data from the coverage file, which is most likely a file path issue. Are you running version 0.16.1 or something older (there were a few issues with paths that have been fixed recently). If yes could you try to specify the input file without path information?
If it still fails I can take a look next week when I am back. Best, Felix

**Comment by avilella** [comment]
I will check that. Thanks.

Is it possible that if the bam file comes from bismark 0.14.4 then a more
recent bismark methylation extractor would fail?

**Comment by FelixKrueger** [comment]
No the BAM files should be fine, the error came with older versions of `bismark2bedGraph` or `coverage2cytosine`, e.g. explained here #31 or #18.

**Comment by avilella** [comment]
I updated the code and it still crashes with the same error. I am pinning
it down to some of the short decoy/HLA sequence ids messing with the counts.

Is it possible to align with bismark against a reference with decoys and
then run bismark methylation extractor with the same reference but without
decoys? Or would that confuse the extractor script?

Thx in advance,

A.

**Comment by FelixKrueger** [comment]
The methylation extractor shouldn't mind. The step that reads the genomic reference again is `coverage2cytosine`, but if you point it to a reference without decoys and it *should* just read those. If possible I would however be interested to learn what is going worn exactly so that we can fix it properly. Could you put a small test sample on scratch maybe?

**Comment by FelixKrueger** [comment]
any news regardin this?

**Comment by bwang2014** [comment]
When I use bismark_v0.16.3, I met the same question. The strange thing is that only a small part of samples can be run normally, but the others issued the same error above with the same options.

**Comment by FelixKrueger** [comment]
I am now back from holidays, may I ask which errors you saw exactly and is there a chance that your coverage files were empty? Could you supply a sample file so I could reproduce the errors?

**Comment by justinjohns** [comment]
Presumably this has been resolved by now, but for anyone else - try modifying your -o output if you run into this usse, as even in the current release this caused some issues for me. The following worked:

#! /bin/bash
for i in {1..187}
do
echo "Generating Global Report for: "$i 
perl coverage2cytosine  -o "$i" --dir ./global_reports/ --split_by_chromosome --genome_folder /shafer3/lynx_meth/genome/cat9/  /shafer3/lynx_meth/data/cat9/Bismark/"$i"_R1_bismark_bt2_pe.nonCG_filtered.bismark.cov.gz
done

**Comment by dazed1** [comment]
it's been a few years, I'm running into this exact issue myself.  Ran particular steps against one reference genome, ran exact same steps against another and got this error.  I'm using the full path, and am also in the output directory, and I can see the cov.gz file is right there with all the other files (having just been created by previous deduplicate_bismark command).

```
/usr/local/src/Bismark/bismark --parallel 8 -p 8 --temp_dir /projects/scratch/ /projects/cp1kb/ --output_dir /projects/cp1kb/ -1 /projects/90X_1_val_1.fq -2 /projects/90X_2_val_2.fq
/usr/local/src/Bismark/deduplicate_bismark --bam -o /projects/cp1kb/SRR129390X_1_val_1_bismark_bt2_pe -p /projects/cp1kb/90X_1_val_1_bismark_bt2_pe.bam
```

at this point the bam file can be opened by ugene with no complaints...

`/usr/local/src/Bismark/bismark_methylation_extractor --bedGraph -p --genome_folder /projects/cp1kb/ --comprehensive -o /projects/cp1kb --cytosine_report /projects/cp1kb/90X_1_val_1_bismark_bt2_pe.deduplicated.bam`

Now I get that same error:

`==============================================================================
Methylation information will now be written into a genome-wide cytosine report
==============================================================================

Adding context-specific methylation summaries

>>> Writing genome-wide cytosine report to: SRR129390X_1_val_1_bismark_bt2_pe.deduplicated.CpG_report.txt <<<

>>> Writing all cytosine context summary file to: SRR129390X_1_val_1_bismark_bt2_pe.deduplicated.cytosine_context_summary.txt <<<

No last chromosome was defined, something must have gone wrong while reading the data in (e.g. specified wrong file path for a gzipped coverage file?). Please check your command!



Finished generating genome-wide cytosine report
`

What's likely the cause, can be seen in the temp files created:

```
[brian@ominous bis_cp1kb]$ ls
 CHG_context_90X_1_val_1_bismark_bt2_pe.deduplicated.txt
 CHH_context_90X_1_val_1_bismark_bt2_pe.deduplicated.txt
 CpG_context_90X_1_val_1_bismark_bt2_pe.deduplicated.txt
 CpG_context_90X_1_val_1_bismark_bt2_pe.deduplicated.txt.chrENSFCAG00000001192_ENSFCAG00000001192.5_ENSFCAT00000001191_ENSFCAT00000001191.5.methXtractor.temp
 CpG_context_90X_1_val_1_bismark_bt2_pe.deduplicated.txt.chrENSFCAG00000001684_ENSFCAG00000001684.6_ENSFCAT00000001684_ENSFCAT00000001684.6.methXtractor.temp
 CpG_context_90X_1_val_1_bismark_bt2_pe.deduplicated.txt.chrENSFCAG00000009053_ENSFCAG00000009053.6_ENSFCAT00000009056_ENSFCAT00000009056.6.methXtractor.temp
 CpG_context_90X_1_val_1_bismark_bt2_pe.deduplicated.txt.chrENSFCAG00000023773_ENSFCAG00000023773.3_ENSFCAT00000023271_ENSFCAT00000023271.3.methXtractor.temp
 CpG_context_90X_1_val_1_bismark_bt2_pe.deduplicated.txt.chrENSFCAG00000026447_ENSFCAG00000026447.4_ENSFCAT00000024248_ENSFCAT00000024248.4.methXtractor.temp
 CpG_context_90X_1_val_1_bismark_bt2_pe.deduplicated.txt.chrENSFCAG00000034095_ENSFCAG00000034095.3_ENSFCAT00000044316_ENSFCAT00000044316.3.methXtractor.temp
 CpG_context_90X_1_val_1_bismark_bt2_pe.deduplicated.txt.chrENSFCAG00000034685_ENSFCAG00000034685.3_ENSFCAT00000037880_ENSFCAT00000037880.3.methXtractor.temp
 CpG_context_90X_1_val_1_bismark_bt2_pe.deduplicated.txt.chrENSFCAG00000035684_ENSFCAG00000035684.2_ENSFCAT00000040056_ENSFCAT00000040056.2.methXtractor.temp
'CpG_context_90X_1_val_1_bismark_bt2_pe.deduplicated.txt.chrENSFCAG00000037070_ENSFCAG00000037070.3_ENSFCAT00000053332;ENSFCAT00000064250;ENSFCAT00000049184_ENSFCAT00000053332.2;ENSFCAT00000064250.2;ENSFCAT00000049184.3.methXtractor.temp'
 CpG_context_90X_1_val_1_bismark_bt2_pe.deduplicated.txt.chrENSFCAG00000040462_ENSFCAG00000040462.2_ENSFCAT00000050793_ENSFCAT00000050793.2.methXtractor.temp
 CpG_context_90X_1_val_1_bismark_bt2_pe.deduplicated.txt.chrENSFCAG00000041269_ENSFCAG00000041269.2_ENSFCAT00000063393_ENSFCAT00000063393.2.methXtractor.temp
 CpG_context_90X_1_val_1_bismark_bt2_pe.deduplicated.txt.chrENSFCAG00000041836_ENSFCAG00000041836.2_ENSFCAT00000061065_ENSFCAT00000061065.2.methXtractor.temp
 CpG_context_90X_1_val_1_bismark_bt2_pe.deduplicated.txt.chrENSFCAG00000043336_ENSFCAG00000043336.2_ENSFCAT00000057284_ENSFCAT00000057284.2.methXtractor.temp
 CpG_context_90X_1_val_1_bismark_bt2_pe.deduplicated.txt.chrENSFCAG00000044968_ENSFCAG00000044968.2_ENSFCAT00000028051_ENSFCAT00000028051.4.methXtractor.temp
 CpG_context_90X_1_val_1_bismark_bt2_pe.deduplicated.txt.chrENSFCAG00000045642_ENSFCAG00000045642.2_ENSFCAT00000064261_ENSFCAT00000064261.2.methXtractor.temp
 CpG_context_90X_1_val_1_bismark_bt2_pe.deduplicated.txt.chrENSFCAG00000049143_ENSFCAG00000049143.1_ENSFCAT00000084406_ENSFCAT00000084406.1.methXtractor.temp
```

**Comment by dazed1** [comment]
Note that while running, the output doesn't actually pause/hiccup when it gets to parsing that part:

```
skipping SAM header line:       @SQ     SN:ENSFCAG00000033261|ENSFCAG00000033261.2|ENSFCAT00000041659;ENSFCAT00000056082|ENSFCAT00000041659.2;ENSFCAT00000056082.1      LN:1000
skipping SAM header line:       @SQ     SN:ENSFCAG00000035925|ENSFCAG00000035925.3|ENSFCAT00000047013|ENSFCAT00000047013.3      LN:1000
skipping SAM header line:       @SQ     SN:ENSFCAG00000037070|ENSFCAG00000037070.3|ENSFCAT00000053332;ENSFCAT00000064250;ENSFCAT00000049184|ENSFCAT00000053332.2;ENSFCAT00000064250.2;ENSF
CAT00000049184.3        LN:1000
skipping SAM header line:       @SQ     SN:ENSFCAG00000034227|ENSFCAG00000034227.3|ENSFCAT00000032690|ENSFCAT00000032690.3      LN:1000
skipping SAM header line:       @SQ     SN:ENSFCAG00000032959|ENSFCAG00000032959.2|ENSFCAT00000045633|ENSFCAT00000045633.2      LN:1000
```
