### ISSUE TITLE
Deduplication error

### ISSUE THREAD

**Issue by sunabcun** [FelixKrueger/Bismark#431]
Hi,
I have tried to run a deduplication step with this command:
deduplicate_bismark --bam --paired HDF1-1.HDF1-1_R1_bismark_bt2_pe.bam

And, I got this error message but I assume that it does not recognize my input file. Is there any way I can do for this issue? Many thanks!!!

Processing paired-end Bismark output file(s) (SAM format):
HDF1-1.HDF1-1_R1_bismark_bt2_pe.bam

If there are several alignments to a single position in the genome the first alignment will be chosen. Since the input files are not in any way sorted this is a near-enough random selection of reads.

Checking file >>HDF1-1.HDF1-1_R1_bismark_bt2_pe.bam<< for signs of file truncation...

Now testing Bismark result file HDF1-1.HDF1-1_R1_bismark_bt2_pe.bam for positional sorting (which would be bad...)	...passed!
Output file is: HDF1-1.HDF1-1_R1_bismark_bt2_pe.deduplicated.bam

view: invalid option -- '-'
[main_samview] fail to open "1" for reading.

Total number of alignments analysed in HDF1-1.HDF1-1_R1_bismark_bt2_pe.bam:     0
Total number duplicated alignments removed:     0 (N/A%)
Duplicated alignments were found at:    0 different position(s)

Total count of deduplicated leftover sequences: 0 (N/A% of total)

view: invalid option -- '-'
[main_samview] fail to open "1" for reading.
Failed to close output filehandle:

**Comment by FelixKrueger** [comment]
Hi @sunabcun 

I am not exactly sure what is the issue here, but my guess would be that it has to do with the version of Samtools you are using, or maybe the input file is truncated? Which versions of Samtools and Bismark are you running?

Can you run:

```
samtools view -H HDF1-1.HDF1-1_R1_bismark_bt2_pe.bam | tail
```

Does this run without errors and display the last lines OK? If you are not running the latest versions of Bismark and Samtools, can you please update and try again?

**Comment by sunabcun** [comment]
Hi @FelixKrueger,

You're right! Our HPC has old Samtools and it causes this weird problem. I downloaded new samtools and put the path location to Bismark. And, it works fine! Thank you so much. I will close the issue!

**Comment by FelixKrueger** [comment]
Excellent, glad this could be fixed so easily!
