### ISSUE TITLE
Are read sequences in bismark output bam files converted or not?

### ISSUE THREAD

**Issue by frylhc** [FelixKrueger/Bismark#435]
Dear Felix, hi, I have already used bismark to process my WGBS data. Now I look back and found myself not completely understand whether the read sequences in bismark output bam files are C>T(or G>A) converted or not? I presume that they are, but i'm not 100% sure about that. Besides, after alignment and deduplication using bismark, I converted bismark bam files to bigwig files using deeptools bamCoverage, and subsequently plotted DNA methylation profile using deeptools plotProfile, and I got the following profiles. I am not sure I completely understand the y-axis of the profile. Does it stand for the methylation level (percentage) of each site? Thanks a lot for your time and attention.
![image](https://user-images.githubusercontent.com/68120639/118648228-c80bb800-b814-11eb-8051-048ce19b7a74.png)

**Comment by FelixKrueger** [comment]
Hi @frylhc 

The wording is a little unconventional, but yes, the BAM files output by Bismark contain alignments of the C>T or G>A converted FastQ files. Unless you are interested in general coverage statistics, the BAM files are however not really interesting. What you are interested in are the methylation calls, more specifically the coverage files which you obtain by running `bismark_methylation_extractor --bedGraph --gzip your_file.bam`. The details for this can be found here: 
https://www.bioinformatics.babraham.ac.uk/training/Methylation_Course/BS-Seq%20theory%20and%20QC%20lecture.pdf or here: https://github.com/FelixKrueger/Bismark/tree/master/Docs#iv-bismark-methylation-extractor

I am not sure that you should convert the BAM files to bigWig, or use Deeptools for this either...
