### ISSUE TITLE
bismark align R1 --pbat R2 normal

### ISSUE THREAD

**Issue by emarti88** [FelixKrueger/Bismark#436]
Hello,

I was curious if there was a method to align paired end sequencing from Illumina with R1 using the --pbat parameter and the R2 aligning to the conventional strands in the reference genome. Please advise. 

Thanks,
Eduardo

**Comment by FelixKrueger** [comment]
Not quite sure if I understand the question right, but if you have a paired-end PBAT sample (where R1 would align to either the CTOT or CTOB strand, and R2 would align to the OT or OB strands if aligned separately as single-end files), then then the option `--pbat` would do just the right thing for your paired-end sample. Or am I missing something?

**Comment by emarti88** [comment]
I am following the methods section for a single cell methylation experiment (published here: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5570439/#SD1) The alignment they do is separate single-end alignments for their paired-end reads: 

"R1 and R2 reads were mapped separately as single-end reads using Bismark v0.15.0 with parameter --bowtie2. --pbat option was activated for mapping R1 reads." 

This seemed strange to me and I wanted to know if I could align them as paired-end reads while activating the --pbat option for only R1. But from what you mentioned earlier it seems a paired end PBAT alignment should do the same thing and forego any complications of doing the R1 and R2 alignment separately. Correct?

**Comment by FelixKrueger** [comment]
I can't really give you a final recommendation on the exact mapping parameters without looking at the data, or at least the QC and mapping reports myself. For the single-cell data we generate in house (scBS-seq, scM&T-seq or scNMT-seq) we tend to treat the samples as single-end, even though some libraries were paired end. I have written up some information about that here: https://github.com/FelixKrueger/Bismark/blob/master/Docs/FAQ.md#issue-1.

If you could send me either the FastQC reports of the raw files, and the mapping results of both R1 and R2 aligned in `--non_directional` mode, I could probably say a bit more. Alternatively,if you could let me know the SRR number of one of the samples you interested in, I could take a quick look myself?

**Comment by FelixKrueger** [comment]
not heard back for a few months, closing for now,.
