### ISSUE TITLE
Methylation Per Read

### ISSUE THREAD

**Issue by aayushraman** [FelixKrueger/Bismark#437]
Hi @FelixKrueger 

I hope you are doing well. Do you have a script or function to calculate the methylation per read or paired-end read? 

Thanks,
-Ar

**Comment by FelixKrueger** [comment]
You try out the `methylation_consistency` script. This will assess the methylation percentage of reads, or read pairs, and sort them into low, intermediate high methylation BAM files. If you wanted, it should be trivial to output the methylation percentage as an additional optional field for the BAM files.

**Comment by FelixKrueger** [comment]
not heard back in a long while, I assume you have found a way?

**Comment by aayushraman** [comment]
Apologies for the late reply. I found the `MethylDackerl perRead` command to be more helpful as I was looking for the methylation levels per read. Thanks again for the help and for maintaining such awesome software.
