### ISSUE TITLE
Why the bismark_methylation_extractor cytosine_report and bedGraph output have fewer columns?

### ISSUE THREAD

**Issue by HYan-lei** [FelixKrueger/Bismark#438]
Hi, 
I used the following script, bismark_methylation_extractor -p --no_overlap --counts --merge_non_CpG --gzip --bedGraph  --cytosine_report --genome_folder $dir/hg19_bowtie2 ${sampleName}.dd.bam

Here is the output, bedGraph just has 4 columns:
track type=bedGraph
chr1    11479   11480   0
chr1    12265   12266   0
chr1    12271   12272   0
chr1    12278   12279   100
chr1    12305   12306   100

head 3_MDB1447.dd.bismark.cov
chr1    11480   11480   0       0       1
chr1    12266   12266   0       0       1
chr1    12272   12272   0       0       1
chr1    12279   12279   100     1       0
chr1    12306   12306   100     1       0
chr1    12319   12319   100     1       0

Can you please give me some suggestions? Thanks.

HY

**Comment by FelixKrueger** [comment]
Here is the explanation of the bedGraph and coverage output: https://github.com/FelixKrueger/Bismark/tree/master/Docs#optional-bedgraph-output. Generally, the coverage file is the more helpful one...

Hope this helps.

**Comment by HYan-lei** [comment]
Hi, Thanks very much for the quick reply. So I should add --CX if I want to add additional column? Sorry another question, the cystine-report should be
<chromosome> <position> <strand> <count methylated> <count unmethylated> <C-context> <trinucleotide context>,
but in my output,
head 3_MDB1447.dd.bismark.cov
chr1 11480 11480 0 0 1
chr1 12266 12266 0 0 1

The third column is still the position, not strand; And I think the number is not quite right, you can see in bedGraph file, 12279 position, methylation percentage is 1; and in cov file, 12279 position, methylated count is 110, unmethylated count is 1,  do you think it right? Thanks very much.

best

HY

**Comment by HYan-lei** [comment]
cystine-report should be
<chromosome> <position> <strand> <count methylated> <count unmethylated> <C-context> <trinucleotide context>

**Comment by FelixKrueger** [comment]
The output files in Bismark follow a certain convention, which are explained in the link above. Bismark coverage files always look like this:

```
<chromosome> <start position> <end position> <methylation percentage> <count methylated> <count unmethylated>
```

and I am afraid you can't add any column unless you perform some custom post-processing. If you use `--CX` you would not only look in CpG context, but also add CHH and CHG context to the file. While the file format would stay the same, you would probably increase the number of lines in the file from 10-40M to over one billion (as there are a lot of (mostly unmethylated) cytosines in non-CG context in the genome).

`The third column is still the position, not strand;` that's indeed right, the coverage file does not carry information about the strand (see above). If you wanted to relate the calls back to the genome reference and get the strand information your would need to specify `--cytosine_report` in the methylation extractor, or run `coverage2cytosine` as a stand-alone process with the coverage file as the input.


Regarding the final question: 

This is the relevant position in the **bedGraph**:
```
chr1 12278 12279 100
```
this is the equivalent position in the **coverage** file:
```
chr1 12279 12279 100 1 0
```

As you can see both files show a methylation of 100%, but the coverage file details the counts as 1 count methylated, and 0 unmethylated. Did I miss anything?

**Comment by HYan-lei** [comment]
Thanks. So in the bedGraph and Coverage file, the fourth column both are mehtylation percentage? This is consistent with my result. Just in the tutorial, the coverage report shows the fourth column should be the count methylated and not the methylation percentage. 

(Optional): genome-wide cytosine report output
Starting from the coverage output, the Bismark methylation extractor can optionally also output a genome-wide cytosine methylation report. The module coverage2cytosine (part of the Bismark package) may also be run individually. It is also sorted by chromosomal coordinates but also contains the sequence context and is in the following format:

<chromosome> <position> <strand> <count methylated> <count unmethylated> <C-context> <trinucleotide context>

**Comment by HYan-lei** [comment]
Thanks. So in the bedGraph and Coverage file, the fourth column both are mehtylation percentage? This is consistent with my result. Just in the tutorial, the coverage report shows the fourth column should be the count methylated and not the methylation percentage.

(Optional): genome-wide cytosine report output
Starting from the coverage output, the Bismark methylation extractor can optionally also output a genome-wide cytosine methylation report. The module coverage2cytosine (part of the Bismark package) may also be run individually. It is also sorted by chromosomal coordinates but also contains the sequence context and is in the following format:

chromosome position strand count methylated count unmethylated C-context trinucleotide context

**Comment by FelixKrueger** [comment]
Yes that's right. May I ask which tutorial are you referring to that has the coverage file format wrong, allegedly?

And yes, the cytosine report has a different format, most notably it contains the position a single time, and has the genomic strand information instead. Good luck

**Comment by HYan-lei** [comment]
I follow this tutorial, in the page 15, https://www.bioinformatics.babraham.ac.uk/projects/bismark/Bismark_User_Guide.pdf

**Comment by FelixKrueger** [comment]
Hmm, even though this version of the User Guide is more than 5 years old, it seems to say exactly the same as the current version (https://github.com/FelixKrueger/Bismark/tree/master/Docs) and what I have pointed out in above? In any case, I'm glad that everything seems to be clear now?

**Comment by HYan-lei** [comment]
It is very clear. Thanks very much for your explaination.
