### ISSUE TITLE
bam2nuc option to generate genomic_nucleotide_frequencies.txt only

### ISSUE THREAD

**Issue by ewels** [FelixKrueger/Bismark#44]
We have our Bismark reference genomes in a central location without write privileges for non-admins (_eg._ me). It would be nice to have the `bam2nuc` `genomic_nucleotide_frequencies.txt` written there, but I need to ask someone to generate it for me. Currently, it seems that the only way to get this to happen is to actually analyse some real data.

Please could a command line option be added to `bam2nuc` to generate just the `genomic_nucleotide_frequencies.txt` file without processing any data? 

Additionally / alternatively, the generation of this file could be added to the `bismark_genome_preparation` script.

**Comment by FelixKrueger** [comment]
Added a new option `--genomic_composition_only` to `bam2nuc` to just process the genomic sequence without requiring any data files. In addition, this step will now attempt to write the file `genomic_nucleotide_frequencies.txt` to the genome folder, and if this fails will write it to the output folder instead. This should be good for people without admin rights...

I have also added the step to the genome preparation step (as option `--genomic_composition`) so this can now be handled right when preparing the genome. Added in 1ab04570e1e9c1aab007b6599790d65443b26f23. Can you let me know if something is not working as expected?

**Comment by ewels** [comment]
Just tried the `bam2nuc` `--genomic_composition_only` option and it worked perfectly 👍 

I'll tell the sysadmins about the new option in the genome preparation step once this is released - I doubt they'll want to change anything until it's available in a core release.

Thanks!

**Comment by FelixKrueger** [comment]
Excellent, thanks for testing. There shall be a new release once I finished the current batch of feature requests...
