### ISSUE TITLE
No CpG_report.txt.gz

### ISSUE THREAD

**Issue by EmanuelDiak** [FelixKrueger/Bismark#440]
Hi, 

I am having an issue using Bismark methylation extractor working with 'pe.bam' files, although i am using the command --cytosine_report i do not get the necessary "CpG_report.txt.gz? file. The extractor runs, i get all the other output files but not the one mentioned. 
I am quite new to the field, so it might be a simple solution, however I would appreciate any feedback. 

Thanks a lot

Emanuel

**Comment by FelixKrueger** [comment]
Hi Emanuel,

This doesn't sound quite right. Could you link the exact command you are using, mentioning also the Bismark version, and then link the relevant text you see on-screen (or send me the log file as an email)? 

Best wishes, Felix
