### ISSUE TITLE
extract mapped and unmapped reads from bismark bam  

### ISSUE THREAD

**Issue by shruti3009** [FelixKrueger/Bismark#441]
Hi Felix,

I am interested in extracting mapped reads and unmapped reads in two separate files to re-align them with a new genome to check the contamination level in sample library preparation. I have output bam files generated from the dragen methylation pipeline in Illumina basespace. I have tried doing:

```
samtools view --threads $PROCESSORS -b -F 4 in.bam > mapped.bam
samtools view --threads $PROCESSORS -b -f 4 in.bam > unmapped.bam

```
and then tried 

`bedtools bamtofastsq -i mapped.bam -fq R1.fastq -fq2 R2.fastq
`

I am noticing nothing is being extracted in unmapped.bam and everything in original output goes to mapped.bam. Can you suggest a way- how can I get mapped/unmapped reads from bismark output?

Thanks in advance,
Shruti

**Comment by FelixKrueger** [comment]
Hi Shruti,

Sorry for the late reply, but I was off on vacations. 

I believe the Dragen pipeline uses Bismark for its alignments, and the Bismark only ever outputs mapped reads, or properly paired read pairs for paired-end input files; so the result you described above is to be expected. The solution to this is fairly simple, you can simply re-run Bismark and specify `--unmapped` (see `--help` for more details): this option will output the same mapped BAM file, and also write unmapped files to separate unmapped FastQ files. Not sure if Dragen has the option to use this parameter, but if not, then the process is fairly straight forward:
**1) Trimming**
```
trim_galore --paired file_R1.fastq.gz file_R2.fastq.gz
```

**2) Mapping including unmapped reads**
```
bismark --genome /path/to/genome/ --unmapped -1 trimmed_R1.fq.gz -2 trimmed_R2.fq.gz
```

If you want to discriminate between reads that did not map (unmapped), and reads that aligned ambiguously and were hence not included in the BAM file, you might want to look at the option `--ambiguous` as well. Let me know if you have any questions.

**Comment by FelixKrueger** [comment]
Not heard back in a while, I assume this got sorted somehow.
