### ISSUE TITLE
Coordinates in cov and bedgraph files

### ISSUE THREAD

**Issue by smzt** [FelixKrueger/Bismark#442]
Dear Felix,
I'm analyzing this CpG cg16201038 with an amplicon-based panel. Coordinates in hg38 locate this CpG at position chr13:27970623.
When I look at the .cov file it reports the position chr13:27970624-27970624 instead of reporting chr13:27970623-27970623 (1-based position).  
![imagen](https://user-images.githubusercontent.com/32428329/120893500-f4e10d00-c613-11eb-92ee-721fe5569ce7.png)

When looking at the bedGraph it reports the position of the CpG as the start and the position of CpG + 1 as the final coordinate. I was expecting to find chr13:27970622-27970623 (if do not misunderstand 1-base schemas) instead of chr13:27970623-27970624 in the bedGraph.
![imagen](https://user-images.githubusercontent.com/32428329/120896380-8a36ce00-c621-11eb-9b69-d80276ee94f7.png)

Sorry to bother you with such a naive question but I just want to make sure everything is working fine.

Thanks very much in advance.

Sheila

**Comment by FelixKrueger** [comment]
Hi Sheila,

I just checked the actual sequence of the region in your sample, and it appears that there are CpGs on the bottom (reverse) strand at positions (ending in) 17, 24, and 27. So I would hope that you targeted the Cox2 gene via amplicons of the reverse strand.

The coverage files show the position exactly as you would see them on Ensembl (or USCS), the bedGraph files are zero-based and half-open, so the starting coord will be one less than the actual position in question. Does this answer your question?

**Comment by smzt** [comment]
Hi Felix,
Thanks very much for your quick reply.
Yes, this fully answers my question. The targeted gene is CDX2 and it is in the reverse strand. People in the lab constructed primers just to amplify the reverse strand. I hadn't realized that the position in the files was for the reverse strand, which is the strand of interest. Here is one of the alignment reports.

Final Alignment report
======================
Sequence pairs analysed in total:       4309
Number of paired-end alignments with a unique best hit: 3558
Mapping efficiency:     82.6%

Sequence pairs with no alignments under any condition:  716
Sequence pairs did not map uniquely:    35
Sequence pairs which were discarded because genomic sequence could not be extracted:    0

Number of sequence pairs with unique best (first) alignment came from the bowtie output:
CT/GA/CT:       2       ((converted) top strand)
GA/CT/CT:       74      (complementary to (converted) top strand)
GA/CT/GA:       112     (complementary to (converted) bottom strand)
CT/GA/GA:       3370    ((converted) bottom strand)

Thanks very much again for your help.

Best regards,

Sheila

**Comment by FelixKrueger** [comment]
Excellent, I'm glad is could be sorted so easily. And yes, I should probably not reply to Github issues after eight hours of driving back down from Scotland, today the gene reads CDX2 for me as well (I even worked on this gene in a previous life some 15 years ago...). All the best!
