### ISSUE TITLE
How to speed up bismarkk

### ISSUE THREAD

**Issue by hmyh1202** [FelixKrueger/Bismark#443]
Dear sir:
  I have huge bases sequenced samples, and the default prameter is so.. slow. How to speed up the align spee and how to set the -p and --multicore ? thank U.

**Comment by FelixKrueger** [comment]
Well, if you have plenty of system resources available you should be able to `--parallel` more or less in a linear fashion. `--parallel 2` should cut the time in half, and need twice as many resources, `--parallel 4` would reduce the time to ~25% but cost 4-times the resources etc.

**Comment by hmyh1202** [comment]
Yes, I have set the -p to 30, it is runnig. And how to set the parameter of --multicore, if I don`t use the -p.  
Thanks.

**Comment by FelixKrueger** [comment]
`-p 30` is most likely completely useless, there have been reports that it will actually slow down alignments if you set it any higher than `-p 4`, and there should be an on-screen warning to inform you about it.

Just specify `--parallel 4` when running, or read its documentation with `--help` for further information.

**Comment by hmyh1202** [comment]
I got it. But my friend told me, they use 64 core and finish a big data alignment in one day. So I just try it today.  Usually, I use --multicore 1 and finish in 2-3 days (90Gb WGBS data).

I will set -p to 4 and more core for --parallel ( 8 or  more).

**Comment by FelixKrueger** [comment]
Good luck!

**Comment by FelixKrueger** [comment]
Things helping with speed are using properly trimmed data, strict mapping parameters, and using more system resources. If you have the means, `--parallel 2` should bring that down by half once more...
