### ISSUE TITLE
failed to create index file

### ISSUE THREAD

**Issue by sharma775** [FelixKrueger/Bismark#445]
Hi,

I am trying to analyze BS sequenced files using Bismark on Galaxy. It shows the following error.  

Create a temporary index with the offered files from the user. Utilizing the script: bismark_genome_preparation
Generating index with: 'bismark_genome_preparation --bowtie2 /tmp/tmpnwcj1y_m'

Is it required to supply converted file to make index for maping in Bismark please

**Comment by FelixKrueger** [comment]
Hi @sharma775 

I am afraid this doesn't look like code from Bismark at all, but it might be something Galaxy specific. Bismark doesn't use a temporary index.... So you might have to get help from the Galaxy people instead, or run Bismark on another Linux machine, where I'd be happy to help.

Cheers, Felix

**Comment by sharma775** [comment]
Hi @FelixKrueger 

Thank you so much. Yes, it is on Galaxy. I will seek help from the galaxy peoples before i will switch to linux.

Cheers,

Uma

**Comment by FelixKrueger** [comment]
Good luck!
