### ISSUE TITLE
deduplicate_bismark bam currupted

### ISSUE THREAD

**Issue by StefanoBertoUTSW** [FelixKrueger/Bismark#447]
Hello, 

I am currently working on WGBS and I have an issue using bismark (v0.23.1). 

the resultant bam file after deduplicate_bismark is truncated and cannot be used for the bismark_methylation_extractor. The original bam file after alignment works perfectly. 

This is the error when I used samtools view: 
[E::bgzf_uncompress] Inflate operation failed: invalid distance too far back
[E::bgzf_read] Read block operation failed with error -1 after 0 of 4 bytes
[E::bam_hdr_read] Invalid BAM binary header

The code I used for the alignment:
for file in $(ls Trimmed/*.fastq.gz | rev | cut -c 26- | rev | uniq)
do
bismark --bowtie2 \
--genome /endosome/work/Neuroinformatics_Core/s157784/GENOMES/mm10_bismark \
--non_directional \
--multicore 20 \
-output_dir Bismark_Output/ \
--temp_dir Bismark_Output/ \
-1 ${file}_R1.NoAdapt.Trim.fastq.gz -2 ${file}_R2.NoAdapt.Trim.fastq.gz
echo $file
done

The code I used for the dedups using bismark:
ls *_pe.bam | parallel --progress --eta -j 12 'deduplicate_bismark --paired --bam {} > {.}.deduplicated.bam'

The code I used for the methyl extraction:
ls *_pe.deduplicated.bam | parallel -j 2 'bismark_methylation_extractor --paired-end --include_overlap --multicore 10 --bedGraph --zero_based --merge_non_CpG --comprehensive --gzip {} > {.}.txt.gz'

Not sure what's going on.

**Comment by FelixKrueger** [comment]
Hi Stefano,

I am not very familiar with the command you used to invoke the deduplication, but to me it looks like you are redirecting the output to a file that ends in `_pe.bam.deduplicated.bam`, or possibly `_pe.deduplicated.bam` in case `{.}` truncates the name at the file ending. `deduplicate_bismark` generates its own output filenames, pretty much according to the same rules, so I could imagine that these two operations get each other in the way.

Couldn't you try the following command on one file and see if it works (`--bam` should be default, and PE should be auto-detected)?

```
deduplicate_bismark file1_pe.bam
```

If this is the case, then something similar might be happening with the methylation extraction command (`> {.}.txt.gz`).

Let me know how you get on.

**Comment by StefanoBertoUTSW** [comment]
Thank you so much Felix. It solved the problem. It was the "> {.}.deduplicated.bam". 
My mistake.

**Comment by FelixKrueger** [comment]
Excellent, glad it helped!
