### ISSUE TITLE
bedgraph and cov files empty 

### ISSUE THREAD

**Issue by mmageroy** [FelixKrueger/Bismark#448]
Hi,

I am using Bismark to perform WGBS analysis on Norway spruce. The spruce genome is still a draft genome and is about 20Gb. I ran the libraries separately for the alignment, combined them in the deduplication step, and this ran methylation extractor using: 

bismark_methylation_extractor --gzip --bedGraph /55MJ100_pe.multiple.deduplicated.bam

The bedgraph and cov files were empty. From what I can tell, methylated Cs were called (see slurm report below).

Perhaps the genome is too fragmented and larger to produce the files. Is there another way to determine the position of the methylated Cs?

Thanks,
Melissa

Final Cytosine Methylation Report
=================================
Total number of C's analysed:	16619168225

Total methylated C's in CpG context:	1022855861
Total methylated C's in CHG context:	1525530480
Total methylated C's in CHH context:	365539166

Total C to T conversions in CpG context:	509141574
Total C to T conversions in CHG context:	816868068
Total C to T conversions in CHH context:	12379233076

C methylated in CpG context:	66.8%
C methylated in CHG context:	65.1%
C methylated in CHH context:	2.9%

Determining maximum read lengths for M-Bias plots
Maximum read length of Read 1: 100
Maximum read length of Read 2: 100

Perl module GD::Graph::lines is not installed, skipping drawing M-bias plots (only writing out M-bias plot table)
Determining maximum read lengths for M-Bias plots
Maximum read length of Read 1: 100
Maximum read length of Read 2: 100

Perl module GD::Graph::lines is not installed, skipping drawing M-bias plots (only writing out M-bias plot table)
Deleting unused files ...

CpG_OT_55MJ100_pe.multiple.deduplicated.txt.gz contains data ->	kept
CpG_CTOT_55MJ100_pe.multiple.deduplicated.txt.gz was empty ->	deleted
CpG_CTOB_55MJ100_pe.multiple.deduplicated.txt.gz was empty ->	deleted
CpG_OB_55MJ100_pe.multiple.deduplicated.txt.gz contains data ->	kept
CHG_OT_55MJ100_pe.multiple.deduplicated.txt.gz contains data ->	kept
CHG_CTOT_55MJ100_pe.multiple.deduplicated.txt.gz was empty ->	deleted
CHG_CTOB_55MJ100_pe.multiple.deduplicated.txt.gz was empty ->	deleted
CHG_OB_55MJ100_pe.multiple.deduplicated.txt.gz contains data ->	kept
CHH_OT_55MJ100_pe.multiple.deduplicated.txt.gz contains data ->	kept
CHH_CTOT_55MJ100_pe.multiple.deduplicated.txt.gz was empty ->	deleted
CHH_CTOB_55MJ100_pe.multiple.deduplicated.txt.gz was empty ->	deleted
CHH_OB_55MJ100_pe.multiple.deduplicated.txt.gz contains data ->	kept

Using these input files: CpG_OT_55MJ100_pe.multiple.deduplicated.txt.gz CpG_OB_55MJ100_pe.multiple.deduplicated.txt.gz CHG_OT_55MJ100_pe.multiple.deduplicated.txt.gz CHG_OB_55MJ100_pe.multiple.deduplicated.txt.gz CHH_OT_55MJ100_pe.multiple.deduplicated.txt.gz CHH_OB_55MJ100_pe.multiple.deduplicated.txt.gz

Summary of parameters for bismark2bedGraph conversion:
======================================================
bedGraph output:		55MJ100_pe.multiple.deduplicated.bedGraph.gz
output directory:		><
remove whitespaces:		no
CX context:			no (CpG context only, default)
No-header selected:		no
Sorting method:			Unix sort-based (smaller memory footprint, but slower)
Sort buffer size:		2G
Coverage threshold:		1
=============================================================================
Methylation information will now be written into a bedGraph and coverage file
=============================================================================

Using the following files as Input:
/cluster/work/users/mmageroy/Bismark/Alignments/CpG_OT_55MJ100_pe.multiple.deduplicated.txt.gz	/cluster/work/users/mmageroy/Bismark/Alignments/CpG_OB_55MJ100_pe.multiple.deduplicated.txt.gz

Writing bedGraph to file: 55MJ100_pe.multiple.deduplicated.bedGraph.gz
Also writing out a coverage file including counts methylated and unmethylated residues to file: 55MJ100_pe.multiple.deduplicated.bismark.cov.gz

Now writing methylation information for file >>CpG_OT_55MJ100_pe.multiple.deduplicated.txt.gz<< to individual files for each chromosome
Failed to open filehandle: Too many open files at /cluster/home/mmageroy/.local/easybuild/software/Bismark/0.20.1-intel-2018b/bismark2bedGraph line 278, <IN> line 2442744.
Finished BedGraph conversion ...

**Comment by FelixKrueger** [comment]
I think this can be resolved by specifying the option `--scaffolds`, either for the methylation extractor itself, or for `bismark2bedGraph` if you want to start from the CpG... context files straight away. The command for this should be something like:

```
bismark2bedGraph -o 55MJ100_output.cov.gz --scaffolds --gzip CpG*
```

If you type the program `--help` you can see why the process fails for unfinished genomes.

Good luck!

**Comment by FelixKrueger** [comment]
I think this can be resolved by specifying the option `--scaffolds`, either for the methylation extractor itself, or for `bismark2bedGraph` if you want to start from the CpG... context files straight away. The command for this should be something like:

```
bismark2bedGraph -o 55MJ100_output.cov.gz --scaffolds --gzip CpG*
```

If you type the program `--help` you can see why the process fails for unfinished genomes.

Good luck!
