### ISSUE TITLE
Bismark Genome Preparation - "Parent process: Failed to build index"

### ISSUE THREAD

**Issue by VitaminBrad** [FelixKrueger/Bismark#449]
Hello,

Running 
`Bismark-0.22.3/bismark_genome_preparation` on the mouse reference genome `GCF/000/001/635/GCF_000001635.26_GRCm38.p6/`

with the following, under the hood:
`
bowtie2-2.3.5.1            |   py37he513fc3_0        12.0 MB  bioconda
    perl-5.26.2                |    h36c2ea0_1008        15.4 MB  conda-forge
`

I receive the error message "Parent process: Failed to build index" after the following output:
`
Writing bisulfite genomes out into a single MFA (multi FastA) file

Bisulfite Genome Indexer version v0.22.3 (last modified: 14 April 2019)

A directory called /root/GCF/000/001/635/GCF_000001635.26_GRCm38.p6/Bisulfite_Genome/ already exists. Already existing converted sequences and/or already existing Bowtie 2 or HISAT2) indices will be overwritten!

Step I - Prepare genome folders - completed

Total number of conversions performed:
C->T:	571537930
G->A:	571665869

Step II - Genome bisulfite conversions - completed

Bismark Genome Preparation - Step III: Launching the Bowtie 2 indexer
Please be aware that this process can - depending on genome size - take several hours!
Settings:
  Output files: "BS_CT.*.bt2"
  Line rate: 6 (line is 64 bytes)
  Lines per side: 1 (side is 64 bytes)
  Offset rate: 4 (one in 16)
  FTable chars: 10
  Strings: unpacked
  Max bucket size: default
  Max bucket size, sqrt multiplier: default
  Max bucket size, len divisor: 4
  Difference-cover sample period: 1024
  Endianness: little
  Actual local endianness: little
  Sanity checking: disabled
  Assertions: disabled
  Random seed: 0
  Sizeofs: void*:8, int:4, long:8, size_t:8
Input files DNA, FASTA:
  genome_mfa.CT_conversion.fa
Building a SMALL index
Reading reference sizes
Settings:
  Output files: "BS_GA.*.bt2"
  Line rate: 6 (line is 64 bytes)
  Lines per side: 1 (side is 64 bytes)
  Offset rate: 4 (one in 16)
  FTable chars: 10
  Strings: unpacked
  Max bucket size: default
  Max bucket size, sqrt multiplier: default
  Max bucket size, len divisor: 4
  Difference-cover sample period: 1024
  Endianness: little
  Actual local endianness: little
  Sanity checking: disabled
  Assertions: disabled
  Random seed: 0
  Sizeofs: void*:8, int:4, long:8, size_t:8
Input files DNA, FASTA:
  genome_mfa.GA_conversion.fa
Building a SMALL index
Reading reference sizes
  Time reading reference sizes: 00:00:47
Calculating joined length
Writing header
Reserving space for joined string
Joining reference sequences
  Time reading reference sizes: 00:00:51
Calculating joined length
Writing header
Reserving space for joined string
Joining reference sequences
  Time to join reference sequences: 00:00:13
bmax according to bmaxDivN setting: 684884673
Using parameters --bmax 513663505 --dcv 1024
  Doing ahead-of-time memory usage test
Parent process: Failed to build index
`

Any idea why this might be happening?

Thanks so much!

Best,
Brad

**Comment by FelixKrueger** [comment]
Hmm, how much memory do you have available on your system?  I am guessing that the mouse genome prep will take around8-10GB of RAM

**Comment by VitaminBrad** [comment]
Thanks **so** much, Felix! That seemed to do it! (increased memory)

**Comment by iranianuser** [comment]
Hello
I have recieved same error code (parent process: failed to build index)
My system RAM is 8
and I have about 2T hard space
Does anyone know the reason please????

**Comment by FelixKrueger** [comment]
8GB of RAM is insufficient,  I would recommend at least 16GB upwards
