### ISSUE TITLE
Documenation and --help / --version for bismark2summary

### ISSUE THREAD

**Issue by ewels** [FelixKrueger/Bismark#45]
It's kind of tricky to figure out how to use bismark2summary currently - some documentation would be awesome! (I've heard that Markdown is a great way to write docs 😉 )

When I struggled to find documentation, I tried using the standard command line flags `--help`/`-h`/`--version`/`-v` but none of them did anything, instead it just tried to run with those filenames. It would be nice if these could be added in to be consistent with the other bismark tools.

**Comment by s-andrews** [comment]
There's a really nice [blog post](http://proteo.me.uk/2016/05/defensive-strategies-to-get-through-software-paper-reviews/) saying how to structure programs so that they do what people expect.

**Comment by FelixKrueger** [comment]
I didn't start it!

**Comment by FelixKrueger** [comment]
But point taken, I'll look into this. :)

**Comment by FelixKrueger** [comment]
Added command line options `--help`, `--version` as well as options `-o/--basename` and `--title` to allow some more customisation. Also added some help text to guide users. Addressed here: 7a323ba0b3917b3b2f1fe9f64ded933bda91c8c0.

**Comment by ewels** [comment]
Added Cluster Flow support in ewels/clusterflow@edf658b0561836684e2558ee0ff1b5329b8b9e16
