### ISSUE TITLE
sam output

### ISSUE THREAD

**Issue by suke18** [FelixKrueger/Bismark#452]
Hello, 

I am using bismark/0.22.3 and bowtie2/2.2.6 for the mapping. I am getting sam files instead of bam files. Any ideas of how to convert to bam files?

Best,
KS

**Comment by mmageroy** [comment]
You can use samtools.
samtools view -S -b sample.sam > sample.bam

**Comment by FelixKrueger** [comment]
Either that, or make sure you have samtools installed when you run Bismark. Ideally palce samtools in the `PATH` (just google how to do this), or specify the path with `--samtools_path /path_to/your/samtools`.

**Comment by suke18** [comment]
Thanks, I figured it out. I need to specify the samtools `module load samtools` as well when submitting jobs. Then the output file will be `.bam` files.
