### ISSUE TITLE
Use of uninitialized value $samtools_path in concatenation (.) or tsring at bismark line 1369. <IN2> line 6202448

### ISSUE THREAD

**Issue by VitaminBrad** [FelixKrueger/Bismark#453]
Hi Felix,

I'm getting the following message:

```
Now merging BAM files SRR5195621_1_val_1.fq.temp.1_bismark_bt2_pe.bam SRR5195621_1_val_1.fq.temp.2_bismark_bt2_pe.bam SRR5195621_1_val_1.fq.temp.3_bismark_bt2_pe.bam SRR5195621_1_val_1.fq.temp.4_bismark_bt2_pe.bam SRR5195621_1_val_1.fq.temp.5_bismark_bt2_pe.bam SRR5195621_1_val_1.fq.temp.6_bismark_bt2_pe.bam SRR5195621_1_val_1.fq.temp.7_bismark_bt2_pe.bam SRR5195621_1_val_1.fq.temp.8_bismark_bt2_pe.bam SRR5195621_1_val_1.fq.temp.9_bismark_bt2_pe.bam SRR5195621_1_val_1.fq.temp.10_bismark_bt2_pe.bam SRR5195621_1_val_1.fq.temp.11_bismark_bt2_pe.bam SRR5195621_1_val_1.fq.temp.12_bismark_bt2_pe.bam SRR5195621_1_val_1.fq.temp.13_bismark_bt2_pe.bam SRR5195621_1_val_1.fq.temp.14_bismark_bt2_pe.bam SRR5195621_1_val_1.fq.temp.15_bismark_bt2_pe.bam SRR5195621_1_val_1.fq.temp.16_bismark_bt2_pe.bam into >>> SRR5195621_1_val_1_bismark_bt2_pe.bam <<<
Use of uninitialized value $samtools_path in concatenation (.) or string at Bismark-0.22.3/bismark line 1369, <IN2> line 6202448.
Merging from file >> SRR5195621_1_val_1.fq.temp.1_bismark_bt2_pe.bam <<
Use of uninitialized value $samtools_path in concatenation (.) or string at Bismark-0.22.3/bismark line 1383, <IN2> line 6202448.
Can't exec "view": No such file or directory at Bismark-0.22.3/bismark line 1383, <IN2> line 6202448.
Failed to read from BAM file /root/Bismark_output/SRP097629/SRR5195621_1_val_1.fq.temp.1_bismark_bt2_pe.bam`
```

when running 
```
Bismark-0.22.3/bismark \
            --multicore 16 \
            --path_to_bowtie2 ~/bowtie2-2.4.2-sra-linux-x86_64 \
            --output_dir $output_dir --temp_dir tmpdir \
            --genome GCF/000/001/635/GCF_000001635.26_GRCm38.p6/ \
            -1 fastq_trimmed/sratofastq/SRP097629/SRR5195621_1_val_1.fq \
            -2 fastq_trimmed/sratofastq/SRP097629/SRR5195621_2_val_2.fq \
            
```
On [this dataset](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE93957)

After being trimmed by this command 
`/TrimGalore-0.6.6/trim_galore --rrbs -o fastq_trimmed/sratofastq/SRP097629 --path_to_cutadapt ~/.local/bin/cutadapt --paired sratofastq/SRP097629/SRR5195624_1.fastq sratofastq/SRP097629/SRR5195624_2.fastq`

Any idea why it isn't successfully merging?
Thanks!

**Comment by VitaminBrad** [comment]
Update: apparently only happens when I have `--multicore` on

**Comment by FelixKrueger** [comment]
Hi @VitaminBrad ,

Is there a chance that samtools is not in your `PATH`? If not, you could specify the path with `--path_to_samtools`

**Comment by VitaminBrad** [comment]
Hi @FelixKrueger,

thanks!

[Did that](https://i.imgur.com/LOXKi9l.png) and [got this](https://i.imgur.com/TzgLvVs.png).

Is it necessary to point to a specific file in samtools?

I'll try adding it to `PATH` now.

**Comment by FelixKrueger** [comment]
Hi Brad,

shouldn't it be `--samtools_path samtools/samtools` (seeing that samtools seems to be a folder in your screenshot)?

Just as comment, you seem to be using `--parallel 32`: this is quite something!

A single thread of Bismark tends to use 3 cores (and a few more for in-/out streams but they don't take much CPU), and around 12GB of RAM for the mouse genome. That times 32 would mean close to 100 cores, and >350GB of RAM! I am not sure whether this really results in any noticeable speed increase, or you passed the threshold for diminishing returns by quite a bit? (if you did a benchmark up to that amount I'd be interested to hear about it!).

Until you've got this sorted I would recommend to take a small subset of reads, e.g. 10000, and then try with and without `--parallel 2` as start. Let me know how you get on.

**Comment by VitaminBrad** [comment]
> shouldn't it be --samtools_path samtools/samtools (seeing that samtools seems to be a folder in your screenshot)?

My err: simply pointing to a samtools folder, produced via `git clone` 
One should follow the [INSTALL](https://github.com/samtools/samtools/blob/develop/INSTALL) instructions very closely when installing samtools. I have found success following [this page](http://www.htslib.org/download/). 

Sorry to use your time so @FelixKrueger (I've been having to teach myself a lot of this due to current lab issues), so thank you once again greatly for your assistance!

> [...] parallel [...]

Ah, I had 32 cores to used to I thought it was 1:1 on cores.... Wow, ok. 

`--parallel 2` seems to be working fine with 32 vCPU + 256 GiB on AWS.

Nochmals vielen Dank! : )
Brad

**Comment by FelixKrueger** [comment]
Excellent! Glad it's all sorted!
