### ISSUE TITLE
wrong plot label CHH CHG final-report.html

### ISSUE THREAD

**Issue by crisalves80** [FelixKrueger/Bismark#457]
Hi,

The 'Cytosine Methylation after Extraction'  plot label is switching the CHG and CHH labels.  Is there a way to fix it?

Thanks,

Cris

<img width="1106" alt="Screen Shot 2021-09-10 at 11 45 48 AM" src="https://user-images.githubusercontent.com/39201388/132881035-fa82cc03-6fac-47c8-a21d-14fb6f120eea.png">

**Comment by FelixKrueger** [comment]
Wow, an excellent spot! I suppose I didn't notice since we mainly work with mammalian systems, where CHH and CHG context are typically equally low (or non-existent. I will try to change that out of the HTML template at the earliest opportunity.

**Comment by FelixKrueger** [comment]
This should now work as expected, just clone the current dev version. Thanks for spotting this!
