### ISSUE TITLE
Error 141 in bowtie2 using Bismark

### ISSUE THREAD

**Issue by vgaout** [FelixKrueger/Bismark#458]
Hi to all,

I am using Bismark (version 2.3.4.1) to analyze Bisulfite sequencing in paired-end unstranded samples. When I run Bismark using the following code:

`bismark --genome_folder  [...] -1 [samples_1] -2 [samples_2] --path_to_hisat2 /home/vera/Desktop/Software/hisat2-2.2.1 -o bismark_output -p 20 `

(I have tried several bowtie2 versions: 2.3.4.1, 2.2.9, 2.2.5... and Hisat2 version 2.1.0-1 and samtools 1.13 version)

Bowtie 2 gave me the following error:

`(ERR): bowtie2-align exited with value 141 `

I hope that somebody has solved the same problem... I tried several versions of the programs ans I do not know which can be the problem...

**Comment by FelixKrueger** [comment]
Hmm, if you run Bismark in default mode, the aligner will be Bowtie2. If you want to use HISAT2, you need to add the flag `--hisat2`. Mixing and matching programs won't work.

I have just tried the command:

```
./bismark --genome [...] test_file.fastq --path_to_hisat2 /bi/apps/hisat2/2.1.0/ --hisat2 -o bismark_output -p 20
```

which works just  fine. Please note that you really shouldn't be using `-p 20`, as it will probably use a more resources and not really help. You should also see the following warning:

> Attention: using more than 4 cores per alignment thread has been reported to have diminishing returns. If possible try to limit -p to a value of 4
Each HISAT2 instance is going to be run with 20 threads. Please monitor performance closely and tune down if necessary!

**Comment by vgaout** [comment]
Thank you so much! I thought that Bismark was using Bowtie2 and after that applying also Hisat2 to unmapped reads, and now that I haved removed hisat2 options it seems to work.

**Comment by FelixKrueger** [comment]
Excellent! Good luck!
