### ISSUE TITLE
Create combined CpG and non-CpG bedgraphs

### ISSUE THREAD

**Issue by sanchari24** [FelixKrueger/Bismark#459]
Hello, previously, I was using Bismark  with the  '--comprehensive' option to generate the individual bedgraph files from which we made the bigWigs. For one particular figure, my boss wants me to generate merged bdg files so that we have one bigWig file at the end. Does this mean that I can add the score column of the individual bdgs ? Or do I use some option in the bismark_methylation_extractor ? Thanks

**Comment by FelixKrueger** [comment]
If you want to merge several datasets together, you can either use the CpG* context files of several samples that are generated by the methylation extractor, and  run `bismark2bedGraph` again, e.g. like so:

```
bismark2bedGraph -o all_merged.cov.gz --gzip CpG*
```

Alternatively, you could merge the data from Bismark coverage files (the bedGraph files do not contain methylated/unmethylated count data, and can therefore not be merged easily/at all). This would require either a script or the like. Let me know if you require any help with this.

**Comment by sanchari24** [comment]
Hello, sorry I wasn't clear with my question. I have only one sample and I have generated CpG, CHG and CHH bedgraph files. I just want to merge all together. I saw an option to generate CpG and non-CpG files. Is it possible to merge all of them together so that I can have a single bigWig file?

Sorry and Thanks again!

**Comment by FelixKrueger** [comment]
I suppose you could in theory just concatenate all files, but with this approach I can see the issue that a) simply concatenating would mean that the coordinates are no longer sorted (which might be an issue for the bigWig conversion), and b) some positions might have been called in more than one context (see [more here](https://github.com/FelixKrueger/Bismark/blob/master/Docs/FAQ.md#context-changediscrepancy-between-bismark-coverage-and-genome-wide-cytosine-reports)).

In that case I would probably suggest to use all methylation call files, and run another bismark2bedGraph conversion:

```
bismark2bedGraph --CX -o all_contexts_merged.cov.gz --gzip C*
```

This would take CpG, CHG and CHH context calls, and convert all of them into a single bedGraph and coverage file.

**Comment by sanchari24** [comment]
That will be perfect! Thanks
