### ISSUE TITLE
Specify output filename for bismark2summary

### ISSUE THREAD

**Issue by ewels** [FelixKrueger/Bismark#46]
It would be really nice if the filename could be specified for `bismark2summary` instead of having to always have `bismark_summary.html`. It looks like the original author actually [wrote the code](https://github.com/FelixKrueger/Bismark/blob/master/bismark2summary#L79) with this in mind 😉 

Should be fairly easy to customise with a command line flag I think..?

**Comment by FelixKrueger** [comment]
I have now added this. Thanks to the original author for being so visionary (shortly before abandoning the project of course) :wink: Addressed here: 7dfc618c8291cf781a0945e945c05a1c8975e8b8

**Comment by ewels** [comment]
Yay, awesome 👏  Thank you!

**Comment by ewels** [comment]
Added Cluster Flow support in ewels/clusterflow@edf658b0561836684e2558ee0ff1b5329b8b9e16
