### ISSUE TITLE
Bedgraph files for BS and OXBS gives similar peaks?

### ISSUE THREAD

**Issue by hchatts** [FelixKrueger/Bismark#462]
Hi @FelixKrueger ,
I have a pair of BS and OXBS seq samples for which methylation calls were generated using the foll command-  
"bismark_methylation_extractor -p --comprehensive --gzip --bedGraph --remove_spaces --buffer_size 20G --cytosine_report --genome_folder "$HG38_BISMARK" --report "$OXBS_OUTDIR/$BISMARK_DEDUPED_BAM".
This was followed by bedgraph generation and conversion to tdf for IGV.
OXBS should have much fewer peaks than BS. So, I was wondering if I am missing a step where I subtract one from the other?

**Comment by FelixKrueger** [comment]
haven't heard back for a while, closing.
