### ISSUE TITLE
error closing converted fastq's

### ISSUE THREAD

**Issue by ArnoudBoot86** [FelixKrueger/Bismark#464]
Hi Felix,

I'm analyzing WGBS data, but am getting an error when running in normal (directional mode) with my PE data.

at the step where it converts the input fastq's, it writes them, but I get an error that it fails to close the first file (the C>T converted R1). this error doesn't show up when i add the 'non-directional' flag, and also no problems when analyzing SE data (R1 in normal mode, R2 with PBAT)

Do you know what's going wrong? this is the command I'm running, and below is the error message. The C>T converted fastq is generated and looks fine (and exactly the same as when running 'non-directional')
.../bin/Bismark-0.23.0/bismark --parallel 1 -p 32 --path_to_bowtie .../bin/bowtie2-2.1.0 --samtools_path .../bin/samtools-1.3 -o .../BismarkAlignment/ --temp_dir tempDir_Bismark --ambiguous --un --score_min L,0,-0.6 --genome_folder /mnt/shared/genomes/GRCh38 -1 fastptrim/..._R1.fastq.gz -2 fastptrim/..._R2.fastq.gz 2> logs/....BismarkAlignment_PE.log

Paired-end alignments will be performed
=======================================

The provided filenames for paired-end alignments are fastptrim/..._R1.fastq.gz and fastptrim/..._R2.fastq.gz
Input files are in FastQ format
Writing a C -> T converted version of the input file ..._R1.fastq.gz to ..._R1.fastq.gz_C_to_T.fastq

Created C -> T converted version of the FastQ file ..._R1.fastq.gz (6905948 sequences in total)

Failed to close filehandle Bad file descriptor

**Comment by FelixKrueger** [comment]
You really seem to want to specify every single option possible :)

I don't exactly know off hand what might be wrong, but I would try eliminating options, especially the ones with file paths, to see if that fixes it. E.g. lose ` --temp_dir tempDir_Bismark` (the temp dir will be the output directory, which should be large enough to hold temp files). Or move to the folder fastptrim and then use `-1 .._R1.fastq.gz -2 .._R2.fastq.gz`.
 
A few other things I noticed: Your Bowtie2, Samtools and Bismark are somewhat out of date, updating might not hurt (but this shouldn't affect the current problem).
 `-p 32` is a very bad idea, this will allocate 64 cores for Bowtie2 alignments, but from `-p 4` onwards you will see diminishing returns. If it was me I would simply lose this option entirely.

Let me know how you get on.

**Comment by ArnoudBoot86** [comment]
Hi Felix,

thanks for the quick response. point taken on the need to update my tools, did so this morning ^_^
I just tried to rerun, taking out all options except for the minimum; same error

I did in the meantime also found this old thread you were involved in, where a similar error apparently occurred; seems like you fixed it in version 14 of bismark already, and i couldn't find the same bug when looking at the code, but perhaps it might help you pinpoint the problem
[http://seqanswers.com/forums/printthread.php?t=5502&pp=20&page=27]

` .../bin/Bismark-0.23.1/bismark -p 4 --path_to_bowtie .../bin/bowtie2-2.4.4 --samtools_path .../bin/samtools-1.14 --genome_folder /mnt/shared/genomes/GRCh38 -1 fastptrim/..._R1.fastq.gz -2 fastptrim/..._R2.fastq.gz 2> logs/....BismarkAlignment_PE.log`

**Comment by FelixKrueger** [comment]
Hmm, I just tried to prepare test structure with folders `fastptrim` and `logs`, specified exactly the same command as you did and it works just fine. So I am now suspecting that is could have to do with either your system's gzip (or Perl)? versions, or the FastQ files. Can you run them through FastQC to see if they look alright? Could you try do the trimming with Trim Galore to see if that works? Or as a test just use the original FastQ files (untrimmed).

**Comment by ArnoudBoot86** [comment]
Thanks for the tip

i tried running the untrimmed files; again same error. 

I just tried running the non-directional again, and now it bugged out as well, so I'm thinking this is likely an IO issue. We've been having some IO issues recently, and this might be another one.
apologies for wasting your time

**Comment by FelixKrueger** [comment]
That's quite alright, but I don't think this is really anything within Bismark I could help you with, but rather seems to be specific to your environment. Would you have the option to use a different machine? In any case, good luck! :)
