### ISSUE TITLE
bam2nuc / bismark2summary to calculate nucleotide fold coverage

### ISSUE THREAD

**Issue by ewels** [FelixKrueger/Bismark#47]
The excellent new `bam2nuc` module apparently adds a very fetching new table to the bismark summary reports:
![bam2nuc](https://raw.githubusercontent.com/FelixKrueger/Bismark/fef3c7239d111eaed11bbb5e649c4e791be34905/Docs/Images/nucleocoverage.png)

It looks like we have sample counts and genome counts for each (di)nucleotide - would it be possible to additionally calculate and print the fold coverage for these? Should be minimal work but a useful metric.

**Comment by FelixKrueger** [comment]
I have now added a coverage calculation in this commit: 9ee5a04ea51e5279ca6595027703c689da48d2c7. Adds an extra column to the nucleotide_stats text file and to the table generated by `bismark2report`.

![newcov](https://cloud.githubusercontent.com/assets/5870509/16620938/4c5e3770-438c-11e6-93bd-52860edeb144.png)

Does that work for you?

**Comment by ewels** [comment]
Looks good! Personally I'd put it as the first column instead of the last, but that's just me ;) Awesome stuff though. Thanks!
