### ISSUE TITLE
Bismark mapper subdividing results in empty file

### ISSUE THREAD

**Issue by zmz1988** [FelixKrueger/Bismark#471]
Dear developers,

Thank you so much for providing this nice tool! I currently start to run bisulphite mapping with Bismark, and encounter a problem while subdividing my fastq file. After subdividing the fastq file, the new tmp file are all empty... I'm not sure where is the problem, as I didn't get an error at all. I paste my log file below. Could you kindly help me to sort this problem out? Thanks in advance!

`Bowtie 2 seems to be working fine (tested command '/miniconda3/envs/MethylStar/bin/bowtie2 --versio
n' [2.3.5])
Output format is BAM (default)
Alignments will be written out in BAM format. Samtools path provided as: '/miniconda3/envs/MethylSt
ar/bin/samtools'
Reference genome folder provided is /reference/Can/  (absolute path is '/reference/Can/)'
FastQ format assumed (by default)
Each Bowtie 2 instance is going to be run with 3 threads. Please monitor performance closely and tune down if necessar
y!

Input files to be analysed (in current folder '/analysis/bisulphite_
analysis/Can_1/bismark-mappers'):
/analysis/bisulphite_analysis/Can_1/trimmomatic-files/Can_1_EKDL2100
06447-1a_HK5WMDSX2_L1_paired_1.fq.gz
/analysis/bisulphite_analysis/Can_1/trimmomatic-files/Can_1_EKDL2100
06447-1a_HK5WMDSX2_L1_paired_2.fq.gz
Library is assumed to be strand-specific (directional), alignments to strands complementary to the original top or bot
tom strands will be ignored (i.e. not performed!)
Output will be written into the directory: /analysis/bisulphite_anal
ysis/Can_1/bismark-mappers/
Summary of all aligner options: -q -N 0 -L 20 --score-min L,0,-0.2 -p 3 --reorder --ignore-quals --no-mixed --no-disco
rdant --dovetail --maxins 500
Running Bismark Parallel version. Number of parallel instances to be spawned: 6

Current working directory is: /analysis/bisulphite_analysis/Can_1/bi
smark-mappers

Now reading in and storing sequence information of the genome specified in: /reference/Can/

chr Chr1_RagTag (34797893 bp)
chr Chr2_RagTag (23392616 bp)
chr Chr3_RagTag (24961777 bp)
chr Chr4_RagTag (19453660 bp)
chr Chr5_RagTag (30004249 bp)
chr ChrC_RagTag (66321 bp)
chr ChrM_RagTag (299991 bp)
chr Chr0_RagTag (8612120 bp)

Paired-end alignments will be performed
=======================================

The provided filenames for paired-end alignments are /analysis/bisul
phite_analysis/Can_1/trimmomatic-files/Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_1.fq.gz and /analysis/bisulphite_analysis/Can_1/trimmomatic-files/Can_1_EKDL210006447-1a_HK5WMDSX2_L1_pa
ired_2.fq.gz

Paired-end alignments will be performed
=======================================

The provided filenames for paired-end alignments are /analysis/bisulphite_analysis/Can_1/trimmomatic-files/Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_1.fq.gz and /analysis/bisulphite_analysis/Can_1/trimmomatic-files/Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_2.fq.gz

Paired-end alignments will be performed
=======================================

The provided filenames for paired-end alignments are /analysis/bisulphite_analysis/Can_1/trimmomatic-files/Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_1.fq.gz and /analysis/bisulphite_analysis/Can_1/trimmomatic-files/Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_2.fq.gz

Paired-end alignments will be performed
=======================================

The provided filenames for paired-end alignments are /analysis/bisulphite_analysis/Can_1/trimmomatic-files/Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_1.fq.gz and /analysis/bisulphite_analysis/Can_1/trimmomatic-files/Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_2.fq.gz

Paired-end alignments will be performed
=======================================

The provided filenames for paired-end alignments are /analysis/bisulphite_analysis/Can_1/trimmomatic-files/Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_1.fq.gz and /analysis/bisulphite_analysis/Can_1/trimmomatic-files/Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_2.fq.gz

Paired-end alignments will be performed
=======================================

The provided filenames for paired-end alignments are /analysis/bisulphite_analysis/Can_1/trimmomatic-files/Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_1.fq.gz and /analysis/bisulphite_analysis/Can_1/trimmomatic-files/Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_2.fq.gz
Finished subdividing /analysis/bisulphite_analysis/Can_1/trimmomatic-files/Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_1.fq.gz for PID: 0 and offset 1 (sequences written out: 0)
Using the subset file >Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_1.fq.gz.temp.1< as new in-file 1 (instead of >/analysis/bisulphite_analysis/Can_1/trimmomatic-files/Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_1.fq.gz<)
Finished subdividing /analysis/bisulphite_analysis/Can_1/trimmomatic-files/Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_1.fq.gz for PID: 0 and offset 2 (sequences written out: 0)

Using the subset file >Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_1.fq.gz.temp.2< as new in-file 1 (instead of >/analysis/bisulphite_analysis/Can_1/trimmomatic-files/Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_1.fq.gz<)
Finished subdividing /analysis/bisulphite_analysis/Can_1/trimmomatic-files/Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_1.fq.gz for PID: 0 and offset 3 (sequences written out: 0)

Using the subset file >Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_1.fq.gz.temp.3< as new in-file 1 (instead of >/analysis/bisulphite_analysis/Can_1/trimmomatic-files/Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_1.fq.gz<)
Finished subdividing /analysis/bisulphite_analysis/Can_1/trimmomatic-files/Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_1.fq.gz for PID: 0 and offset 4 (sequences written out: 0)

Using the subset file >Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_1.fq.gz.temp.4< as new in-file 1 (instead of >/analysis/bisulphite_analysis/Can_1/trimmomatic-files/Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_1.fq.gz<)
Finished subdividing /analysis/bisulphite_analysis/Can_1/trimmomatic-files/Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_1.fq.gz for PID: 167613 and offset 6 (sequences written out: 0)

Using the subset file >Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_1.fq.gz.temp.6< as new in-file 1 (instead of >/analysis/bisulphite_analysis/Can_1/trimmomatic-files/Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_1.fq.gz<)
Finished subdividing /analysis/bisulphite_analysis/Can_1/trimmomatic-files/Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_1.fq.gz for PID: 0 and offset 5 (sequences written out: 0)

Using the subset file >Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_1.fq.gz.temp.5< as new in-file 1 (instead of >/analysis/bisulphite_analysis/Can_1/trimmomatic-files/Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_1.fq.gz<)
Finished subdividing /analysis/bisulphite_analysis/Can_1/trimmomatic-files/Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_2.fq.gz for PID: 0 and offset 2 (sequences written out: 0)

Using the subset file >Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_2.fq.gz.temp.2< as new in-file 2 (instead of >/analysis/bisulphite_analysis/Can_1/trimmomatic-files/Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_2.fq.gz<)
Input files are in FastQ format
Writing a C -> T converted version of the input file Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_1.fq.gz.temp.2 to Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_1.fq.gz.temp.2_C_to_T.fastq
Finished subdividing /analysis/bisulphite_analysis/Can_1/trimmomatic-files/Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_2.fq.gz for PID: 0 and offset 1 (sequences written out: 0)
Using the subset file >Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_2.fq.gz.temp.1< as new in-file 2 (instead of >/analysis/bisulphite_analysis/Can_1/trimmomatic-files/Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_2.fq.gz<)
Input files are in FastQ format

Created C -> T converted version of the FastQ file Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_1.fq.gz.temp.2 (0 sequences in total)

Writing a C -> T converted version of the input file Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_1.fq.gz.temp.1 to Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_1.fq.gz.temp.1_C_to_T.fastq
Writing a G -> A converted version of the input file Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_2.fq.gz.temp.2 to Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_2.fq.gz.temp.2_G_to_A.fastq

Created C -> T converted version of the FastQ file Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_1.fq.gz.temp.1 (0 sequences in total)

Writing a G -> A converted version of the input file Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_2.fq.gz.temp.1 to Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_2.fq.gz.temp.1_G_to_A.fastq
Finished subdividing /analysis/bisulphite_analysis/Can_1/trimmomatic-files/Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_2.fq.gz for PID: 0 and offset 3 (sequences written out: 0)

Using the subset file >Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_2.fq.gz.temp.3< as new in-file 2 (instead of >/analysis/bisulphite_analysis/Can_1/trimmomatic-files/Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_2.fq.gz<)
Input files are in FastQ format
Writing a C -> T converted version of the input file Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_1.fq.gz.temp.3 to Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_1.fq.gz.temp.3_C_to_T.fastq
Finished subdividing /analysis/bisulphite_analysis/Can_1/trimmomatic-files/Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_2.fq.gz for PID: 167613 and offset 6 (sequences written out: 0)

Using the subset file >Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_2.fq.gz.temp.6< as new in-file 2 (instead of >/analysis/bisulphite_analysis/Can_1/trimmomatic-files/Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_2.fq.gz<)
Input files are in FastQ format
Writing a C -> T converted version of the input file Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_1.fq.gz.temp.6 to Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_1.fq.gz.temp.6_C_to_T.fastq

Created G -> A converted version of the FastQ file Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_2.fq.gz.temp.2 (0 sequences in total)

... (omit the rest log file)`

**Comment by FelixKrueger** [comment]
Hi @zmz1988 

thanks for the report. Something does indeed seem to go wrong (sequences written out: 0), but I am not quite sure what the problem is. The first things I would test would be:

- instead of specifying each FastQ file as with a full (or relative) path, can you move to the folder containing the file and try threre? 
- can you try to lose `--parallel 6` to see if the issue also exists in single-thread mode?
- if everything is done correctly, Trimmomatic processed files should work fine, but you can always try to use Trim Galore (`trim_galore --paired file_R1.fastq.gz file_R2.fastq.gz`) as we know it just works
- if none of these options work, please send me an email with a small subset of both reads (e.g. up to 100K reads should fit as an email attachment). I'm sure we can solve this fairly quickly.

Best, Felix

**Comment by zmz1988** [comment]
Hi @FelixKrueger 

Thank you so much for replying me so fast! was you suggested, I moved to the folder containing the file and reduce --parallel to single-thread mode. Somehow things works a bit, as I got the _C_to_T.fastq and _G_to_A.fastq files. But the final bam file and the report are still empty. Still, no error was given in the log file, which I paste below. If you think there is no hope to solve the problem without trying Trim Galore, I will try it then. 

`Bowtie 2 seems to be working fine (tested command 'bowtie2 --version' [2.3.5])
Output format is BAM (default)
Alignments will be written out in BAM format. Samtools found here: '/share/apps/mottlab/miniconda3/envs/MethylStar/bin/samtools'
Reference genome folder provided is /SAN/mottlab/ArabidopsisAssembly/Zhelyazkov/reference/Can/  (absolute path is '/SAN/mottlab/ArabidopsisAssembly/Zhelyazkov/reference/Can/)'
FastQ format assumed (by default)

Input files to be analysed (in current folder '/SAN/mottlab/ArabidopsisAssembly/Zhelyazkov/Ziming_analysis/bisulphite_analysis/Can_1/trimmomatic-files'):
Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_1.fq.gz
Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_2.fq.gz
Library is assumed to be strand-specific (directional), alignments to strands complementary to the original top or bottom strands will be ignored (i.e. not performed!)
Output will be written into the directory: /SAN/mottlab/ArabidopsisAssembly/Zhelyazkov/Ziming_analysis/bisulphite_analysis/Can_1/bismark-mappers/
Summary of all aligner options: -q -N 0 -L 20 --score-min L,0,-0.2 --ignore-quals --no-mixed --no-discordant --dovetail --maxins 500
Current working directory is: /SAN/mottlab/ArabidopsisAssembly/Zhelyazkov/Ziming_analysis/bisulphite_analysis/Can_1/trimmomatic-files

Now reading in and storing sequence information of the genome specified in: /SAN/mottlab/ArabidopsisAssembly/Zhelyazkov/reference/Can/

chr Chr1_RagTag (34797893 bp)
chr Chr2_RagTag (23392616 bp)
chr Chr3_RagTag (24961777 bp)
chr Chr4_RagTag (19453660 bp)
chr Chr5_RagTag (30004249 bp)
chr ChrC_RagTag (66321 bp)
chr ChrM_RagTag (299991 bp)
chr Chr0_RagTag (8612120 bp)

Single-core mode: setting pid to 1

Paired-end alignments will be performed
=======================================

The provided filenames for paired-end alignments are Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_1.fq.gz and Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_2.fq.gz
Input files are in FastQ format
Writing a C -> T converted version of the input file Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_1.fq.gz to Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_1.fq.gz_C_to_T.fastq

Created C -> T converted version of the FastQ file Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_1.fq.gz (3446555 sequences in total)

Writing a G -> A converted version of the input file Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_2.fq.gz to Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_2.fq.gz_G_to_A.fastq

Created G -> A converted version of the FastQ file Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_2.fq.gz (3446555 sequences in total)

Input files are Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_1.fq.gz_C_to_T.fastq and Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_2.fq.gz_G_to_A.fastq (FastQ)
Now running 2 instances of Bowtie 2 against the bisulfite genome of /SAN/mottlab/ArabidopsisAssembly/Zhelyazkov/reference/Can/ with the specified options: -q -N 0 -L 20 --score-min L,0,-0.2 --ignore-quals --no-mixed --no-discordant --dovetail --maxins 500

Now starting a Bowtie 2 paired-end alignment for CTread1GAread2CTgenome (reading in sequences from Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_1.fq.gz_C_to_T.fastq and Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_2.fq.gz_G_to_A.fastq, with the options: -q -N 0 -L 20 --score-min L,0,-0.2 --ignore-quals --no-mixed --no-discordant --dovetail --maxins 500 --norc))
Found first alignment:
A00627:221:HK5WMDSX2:1:1101:1949:1016_1:N:0:ACAGTGAT/1  77      *       0       0       *       *       0
       0       TTANAAAATAATTTAAATAAAATATAAAAATAATTAAATTTTTTATAGTATAATTATTTTTTGTTTTTATATATTATAGATATTTTTTGAATATGAAAATTTAGTTTTAAATGAAGTAGAGTATG   FFF#FFFFFFFFFFFFFFFFFFFFFFF:F:FFFFFF::FFFFFFF:FFF:::FFF:FFFF,FFF,FFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFF::FFF:FFFFFFF,,F   YT:Z:UP
A00627:221:HK5WMDSX2:1:1101:1949:1016_2:N:0:ACAGTGAT/2  141     *       0       0       *       *       0
       0       TCCTTTTAATAAAAAAAAAATAATAAAAAAAAAAATTTATTACTAAAAATTATAAAATTAATTAAAAAAAAATCTCCAAACACATA  FFFFFFFF:,FFFFFFFFFF:FFFFFFF,F:FFFFFFFF:,F::FFFFFF:F:FFFFFFF::FFFF:FFFFFF,FFFFFF:FFFFF  YT:Z:UP
Now starting a Bowtie 2 paired-end alignment for CTread1GAread2GAgenome (reading in sequences from Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_1.fq.gz_C_to_T.fastq and Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_2.fq.gz_G_to_A.fastq, with the options: -q -N 0 -L 20 --score-min L,0,-0.2 --ignore-quals --no-mixed --no-discordant --dovetail --maxins 500 --nofw))
Found first alignment:
A00627:221:HK5WMDSX2:1:1101:1949:1016_1:N:0:ACAGTGAT/1  77      *       0       0       *       *       0
       0       TTANAAAATAATTTAAATAAAATATAAAAATAATTAAATTTTTTATAGTATAATTATTTTTTGTTTTTATATATTATAGATATTTTTTGAATATGAAAATTTAGTTTTAAATGAAGTAGAGTATG   FFF#FFFFFFFFFFFFFFFFFFFFFFF:F:FFFFFF::FFFFFFF:FFF:::FFF:FFFF,FFF,FFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFF::FFF:FFFFFFF,,F   YT:Z:UP
A00627:221:HK5WMDSX2:1:1101:1949:1016_2:N:0:ACAGTGAT/2  141     *       0       0       *       *       0
       0       TCCTTTTAATAAAAAAAAAATAATAAAAAAAAAAATTTATTACTAAAAATTATAAAATTAATTAAAAAAAAATCTCCAAACACATA  FFFFFFFF:,FFFFFFFFFF:FFFFFFF,F:FFFFFFFF:,F::FFFFFF:F:FFFFFFF::FFFF:FFFFFF,FFFFFF:FFFFF  YT:Z:UP

>>> Writing bisulfite mapping results to Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_1_bismark_bt2_pe.bam <<<

`

**Comment by FelixKrueger** [comment]
I somehow can't see your reply here, but from what I saw in your reply everything seemed to look fine: 3446555 reads were in-silico converted, so is there a chance that the process was still running?

**Comment by zmz1988** [comment]
Sorry, I deleted my second reply, because I realised that the adapters in my sequence are not clean. So I thought probably the adapters caused the problem. Now I re-did the Trimmomatic trimming and the adapters are mostly gone, but still the final bam files are empty while the converted fastq files are fine. No any error. Do you think there is something to do with my bowtie2? I paste the log file (which is the same as last time) below.

`Bowtie 2 seems to be working fine (tested command 'bowtie2 --version' [2.3.5])
Output format is BAM (default)
Alignments will be written out in BAM format. Samtools found here: '/miniconda3/envs/MethylStar/bin/samtools'
Reference genome folder provided is /reference/Can/  (absolute path is '/reference/Can/)'
FastQ format assumed (by default)

Input files to be analysed (in current folder '/analysis/bisulphite_analysis/Can_1/trimmomatic-files'):
Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_1.fq.gz
Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_2.fq.gz
Library is assumed to be strand-specific (directional), alignments to strands complementary to the original top or bottom strands will be ignored (i.e. not performed!)
Output will be written into the directory: /analysis/bisulphite_analysis/Can_1/bismark-mappers/
Summary of all aligner options: -q -N 0 -L 20 --score-min L,0,-0.2 --ignore-quals --no-mixed --no-discordant --dovetail --maxins 500
Current working directory is: /analysis/bisulphite_analysis/Can_1/trimmomatic-files

Now reading in and storing sequence information of the genome specified in: /reference/Can/

Single-core mode: setting pid to 1

Paired-end alignments will be performed
=======================================
The provided filenames for paired-end alignments are Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_1.fq.gz and Can
_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_2.fq.gz
Input files are in FastQ format
Writing a C -> T converted version of the input file Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_1.fq.gz to Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_1.fq.gz_C_to_T.fastq

Created C -> T converted version of the FastQ file Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_1.fq.gz (3382041 sequences in total)

Writing a G -> A converted version of the input file Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_2.fq.gz to Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_2.fq.gz_G_to_A.fastq

Created G -> A converted version of the FastQ file Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_2.fq.gz (3382041 sequences in total)

Input files are Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_1.fq.gz_C_to_T.fastq and Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_2.fq.gz_G_to_A.fastq (FastQ)
Now running 2 instances of Bowtie 2 against the bisulfite genome of /reference/Can/ with the specified options: -q -N 0 -L 20 --score-min L,0,-0.2 --ignore-quals --no-mixed --no-discordant --dovetail --maxins 500

Now starting a Bowtie 2 paired-end alignment for CTread1GAread2CTgenome (reading in sequences from Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_1.fq.gz_C_to_T.fastq and Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_2.fq.gz_G_to_A.fastq, with the options: -q -N 0 -L 20 --score-min L,0,-0.2 --ignore-quals --no-mixed --no-discordant --dovetail --maxins 500 --norc))
Found first alignment:
A00627:221:HK5WMDSX2:1:1101:1949:1016_1:N:0:ACAGTGAT/1  77      *       0       0       *       *       0
       0       TTANAAAATAATTTAAATAAAATATAAAAATAATTAAATTTTTTATAGTATAATTATTTTTTGTTTTTATATATTATAGATATTTTTTGAATATGAAAATTTAGTTTTAAATGAAGTAGAGTATG   FFF#FFFFFFFFFFFFFFFFFFFFFFF:F:FFFFFF::FFFFFFF:FFF:::FFF:FFFF,FFF,FFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFF::FFF:FFFFFFF,,F   YT:Z:UP
A00627:221:HK5WMDSX2:1:1101:1949:1016_2:N:0:ACAGTGAT/2  141     *       0       0       *       *       0
       0       TCCTTTTAATAAAAAAAAAATAATAAAAAAAAAAATTTATTACTAAAAATTATAAAATTAATTAAAAAAAAATCTCCAAACACATA  FFFFFFFF:,FFFFFFFFFF:FFFFFFF,F:FFFFFFFF:,F::FFFFFF:F:FFFFFFF::FFFF:FFFFFF,FFFFFF:FFFFF  YT:Z:UP
Now starting a Bowtie 2 paired-end alignment for CTread1GAread2GAgenome (reading in sequences from Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_1.fq.gz_C_to_T.fastq and Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_2.fq.gz_G_to_A.fastq, with the options: -q -N 0 -L 20 --score-min L,0,-0.2 --ignore-quals --no-mixed --no-discordant --dovetail --maxins 500 --nofw))
Found first alignment:
A00627:221:HK5WMDSX2:1:1101:1949:1016_1:N:0:ACAGTGAT/1  77      *       0       0       *       *       0
       0       TTANAAAATAATTTAAATAAAATATAAAAATAATTAAATTTTTTATAGTATAATTATTTTTTGTTTTTATATATTATAGATATTTTTTGAATATGAAAATTTAGTTTTAAATGAAGTAGAGTATG   FFF#FFFFFFFFFFFFFFFFFFFFFFF:F:FFFFFF::FFFFFFF:FFF:::FFF:FFFF,FFF,FFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFF::FFF:FFFFFFF,,F   YT:Z:UP
A00627:221:HK5WMDSX2:1:1101:1949:1016_2:N:0:ACAGTGAT/2  141     *       0       0       *       *       0
       0       TCCTTTTAATAAAAAAAAAATAATAAAAAAAAAAATTTATTACTAAAAATTATAAAATTAATTAAAAAAAAATCTCCAAACACATA  FFFFFFFF:,FFFFFFFFFF:FFFFFFF,F:FFFFFFFF:,F::FFFFFF:F:FFFFFFF::FFFF:FFFFFF,FFFFFF:FFFFF  YT:Z:UP

>>> Writing bisulfite mapping results to Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_1_bismark_bt2_pe.bam <<<

`

**Comment by FelixKrueger** [comment]
Hmm, this looks perfectly normal so far to be honest. Bismark, the FastQ conversion and the first Bowtie2 alignments seem to be working, the next step would usually be just to wait until the run has finished... Would you be able to send me some of the files you are using? 

This command should reduce the file to 50,000 reads, which you can then send to felix.krueger@babraham.ac.uk:

```
gunzip -c Can_1_EKDL210006447-1a_HK5WMDSX2_L1_paired_1.fq.gz | head -200000 | gzip -c - > test_R1.fq.gz
```

Another thought, which kind of machine are you running this on? The Arabidopsis genome shouldn't be particularly challenging, but still...

**Comment by zmz1988** [comment]
Just send you the test data. Thanks a lot in advance!

I'm using our computer server to run the code. The node I used has 40 cores and 50 G (something like this) memory. So I guess it's not the memory issue?

**Comment by FelixKrueger** [comment]
Thanks for that. It doesn't sound like a memory issue, I will take a look and get back to you.

**Comment by FelixKrueger** [comment]
Just had a quick look at your data. 
- it is not adapter trimmed (if you used Trimmomatic you might have done something wrong)
- it looks like single-cell data, or at least non-directional data with a strong sequence bias in the fist 6+ bp
- trimming those bases off I achieved >45% mapping for both the TAIR10 and the genome you provided (plus some extra 15% or so of ambiguously mapping data which is getting discarded.

So yea, for me is seems to work just fine. The commands I used were (roughly):

```
trim_galore --paired --clip_r1 6 --clip_r2 6 test_R1.fastq.gz test_R2.fastq.gz
bismark --genome genome/ -1 test_R1_val_1.fq.gz -2 test_R2_val_2.fq.gz --non_dir --score_min L,0,-0.4
```

**Comment by zmz1988** [comment]
Thanks a lot, Felix! That's very helpful! Especially thanks to the multiqc report! 

It's my first time analysing bisulfites data, and I read from forums that nearly all WGBS nowadays are directional. I didn't expect that our library is non-directional... Also I saw a huge decrease of adapters in percentage reads after Trimmomatic run with TrueSeq3 adapter in fastqc reports, though the percentage didn't decrease to Zero. With this result of adapter trimming, so I assumed that our library is directional... With your experience, do you think WGBS data can be non-directional? I tried to find the answer online, but so far no luck yet.

About the primer, I saw a huge decrease of adapters in percentage reads after Trimmomatic run with TrueSeq3 adapter in fastqc reports, though the percentage didn't decrease to Zero. With this result of adapter trimming, so I assumed that our library is directional... I'm really not familiar with Trimmomatic, as I usually use BBduk to trim Illumina reads. Do you think BBduk could also work for bisulfites sequence?

**Comment by zmz1988** [comment]
I think I find the answer in a recent question on Seqanswers.com that WGBS library can be non-directional. :) Sorry for the stupid question!

**Comment by zmz1988** [comment]
Sorry Felix, I also have a question about the over presented sequence (GGGGGGG) in the reverse reads (_2.fq.gz). Shall I trim this GGGGG sequence off? I'm not so sure why we get this GGGGG sequence, but I thought overpresented sequence should be trimmed off, because they could be the adapters. In this case, this GGGG sequence are not adapters (I think), and so we could keep it in the reverse reads?

**Comment by FelixKrueger** [comment]
> I didn't expect that our library is non-directional

For bisulfite data, it is very important that you know what you are doing, as the type of library preparation and the type of kit dictates which treatment and processing will be required. Here is a link listing a few commercial kits that we put together: https://github.com/FelixKrueger/Bismark/tree/master/Docs#ix-notes-about-different-library-types-and-commercial-kits
If I had to guess I would think you used the Zymo Picomethyl kit for your library prep, which warrants 10bp trimming from all ends, but please try to find this out as it will affect your downstream results.

We have written Trim Galore back in 2010 to consistently do the right thing for Bisulfite-seq data, so I am afraid I am not the best person to ask about Trimmomatic or bbduk (even though I am sure if you give them the right parameters they would equally do the same job).

Poly-G sequences result from a lack of fluorescent signal on NextSeq or NovaSeq machine (or any other platform using the same technology), see e.g. here: https://sequencing.qcfail.com/articles/illumina-2-colour-chemistry-can-overcall-high-confidence-g-bases/. These sequences are technical artefacts, and you have the following options:

- You could run a (second) round of adapter trimming with e.g. `-a G{10}` (which is then expanded to `-a GGGGGGGGGG`), which should remove those sequences
- Alternatively, you might as well not bother about them as they will most likely not produce a unique alignment in the genome, and thus will be effectively removed by the mapping process anyway (this would be what I would be doing)

I hope this helps?

**Comment by zmz1988** [comment]
Yes, great help! Thanks a lot!!
