### ISSUE TITLE
How to merge multiple CpG_report.txt files

### ISSUE THREAD

**Issue by mibsmibs** [FelixKrueger/Bismark#479]
I have multiple sequencing runs 1, 2, 3 for a sample "A". Is there a way to merge the reports into one file in order to analyze in BESSEQ? 
bismark_methylation_extractor --merge A1.CpC_report.txt,A2.CpC_report.txt,A3.CpC_report.txt -o A_total.CpC_report.txt

**Comment by FelixKrueger** [comment]
I am afraid there isn't a merging capability as such, but what you probably could to is keeping all the reports in the same folder (including the Bismark alignment reports), and then run `bismark2summary`. This will produce a `bismark_summary_report.txt` (as well as an HTML report) which you can then use to easily sum up the numbers. I hope this will work for you?

**Comment by mibsmibs** [comment]
Thank you for your response. I tried the summary feature but I am getting an error. Does it only work on the BAM file?
[/test]$ head Sample.CpG_report.txt
8       10407   +       0       0       CG      CGG
8       10408   -       0       0       CG      CGT
8       10422   +       0       0       CG      CGA
8       10423   -       0       0       CG      CGT
8       10498   +       0       0       CG      CGA
8       10499   -       1       0       CG      CGC
8       10553   +       0       1       CG      CGG
8       10554   -       0       0       CG      CGT
8       10781   +       0       0       CG      CGA
8       10782   -       1       0       CG      CGT
[/test]$ ./bismark2summary Sample.CpG_report.txt
Generating Bismark summary report from 1 Bismark BAM file(s)...
Could not find Bismark report (Sample.CpG_report_SE_report.txt) to open
[/test]$

**Comment by FelixKrueger** [comment]
Oh I am so sorry, it seems that I didn't read the original post well enough.

I am afraid there is also no facility to merge CpG reports as such, you would have to write a little script to do that job. I think I could provide you with a script that merges an arbitrary number of coverage file (`*.cov.gz`) into a single merged coverage file, and you could then use this merged coverage file as input for another round of `coverage2cytosine`, would that work?

I personally would always merge right from the start at the level of the input FastQ files, so from there on you only ever get one set of output files...
