### ISSUE TITLE
Bismark alignment step: bail if filenames entered do no exist

### ISSUE THREAD

**Issue by FelixKrueger** [FelixKrueger/Bismark#48]
This came up during our methylation course.

**Comment by ewels** [comment]
Also, bail if `bowtie` commands aren't available early on? I've had environment module problems recently and it goes through the trouble of creating the converted files and loads of other stuff before falling over because it can't run any alignment..

**Comment by FelixKrueger** [comment]
Just added checks for supplied filenames (in e70bed1493346d56134d06f629db62c161c8f249).

**Comment by ewels** [comment]
![hooray](https://media.giphy.com/media/11sBLVxNs7v6WA/giphy.gif)
