### ISSUE TITLE
Issue with Final Alignment Report

### ISSUE THREAD

**Issue by rbpisupati** [FelixKrueger/Bismark#480]
Hi Felix !

I think, we identified one of the bugs in the alignment report. I am mapping bisulfite reads to Arabidopsis thaliana (TAIR10) genome  and this is the alignment report

```
Bismark report for: H7MWJDSX3_1#188467_AATCCAATTGCATGTAGAGG_1_val_1.fq.gz and H7MWJDSX3_1#188467_AATCCAATTGCATGTAGAGG_2_val_2.fq.gz (version: v0.23.0)
Bismark was run with Bowtie 2 against the bisulfite genome of TAIR10_wholeGenome/ with the specified options: -q --score-min L,0,0.5 --ignore-quals --no-mixed --no-discordant --dovetail --maxins 500
Option '--non_directional' specified: alignments to all strands were being performed (OT, OB, CTOT, CTOB)

Final Alignment report
======================
Sequence pairs analysed in total:	7658821
Number of paired-end alignments with a unique best hit:	2518193
Mapping efficiency:	32.9% 
Sequence pairs with no alignments under any condition:	4350420
Sequence pairs did not map uniquely:	790208
Sequence pairs which were discarded because genomic sequence could not be extracted:	0

Number of sequence pairs with unique best (first) alignment came from the bowtie output:
CT/GA/CT:	651956	((converted) top strand)
GA/CT/CT:	584233	(complementary to (converted) top strand)
GA/CT/GA:	603959	(complementary to (converted) bottom strand)
CT/GA/GA:	678045	((converted) bottom strand)

Final Cytosine Methylation Report
=================================
Total number of C's analysed:	93145547

Total methylated C's in CpG context:	2561668
Total methylated C's in CHG context:	1274057
Total methylated C's in CHH context:	5095582
Total methylated C's in Unknown context:	2

Total unmethylated C's in CpG context:	10967697
Total unmethylated C's in CHG context:	12153405
Total unmethylated C's in CHH context:	61093138
Total unmethylated C's in Unknown context:	0

C methylated in CpG context:	18.9%
C methylated in CHG context:	9.5%
C methylated in CHH context:	7.7%
C methylated in unknown context (CN or CHN):	100.0%


Bismark completed in 0d 0h 15m 18s

```

As you can see the total number of C's analysed is showing to be 90M. A. thaliana genome size is approximately 120M, it isnt possible that there are even 90M sites in the genome. There are few samples where this number goes more than 100M. Are you reporting the number of cytosines including all the reads here? then I expect this number to be way higher.

**Comment by FelixKrueger** [comment]
The number reported is the number of methylation calls performed in all reads across the different cytosine contexts. As such, this number has nothing to do with the number of cytosines in the Arabidopsis genome, or how well they were covered.

If you wanted to get the number of covered cytosine position you should proceed with the bedGraph coverage conversion (which can be started as part of the methylation extraction process). The number of lines in the coverage file (`.cov.gz`) is the number of total positions covered.

**Comment by rbpisupati** [comment]
Not sure if I understood it completely. I have 100bp reads, and considering GC content of 30-35, there would be approximately 30 cytosines on each read. For 5 million mapped reads (2.5 paired end alignments), the number of C's analysed should be 150Million?
