### ISSUE TITLE
Bismark_methylation_extractor line 487 

### ISSUE THREAD

**Issue by gourav924** [FelixKrueger/Bismark#485]
Hello Felix,

I am using Bismark_methylation_extractor function to generate comprehensive and CX reports. I am using the following command. I was using the same command and everything was running fine. However, now I get an error :

Died at /software/Bismark/bismark2bedGraph line 487.

./bismark_methylation_extractor -p  --no_overlap --gzip --CX --bedGraph --cytosine_report --comprehensive --multicore 30 --parallel 20  --genome_folder genome_arab  -output CL_paired_bismark_bt2_pe.deduplicated.bam

Can you help me to figure out the reason behind it

**Comment by FelixKrueger** [comment]
I suppose you have a found it by now? There were a few redundant options in your command, but I suppose `-output filename` was the one that tripped it up? I suppose this command should have worked:

```
./bismark_methylation_extractor --gzip --CX --bedGraph --cytosine_report --comprehensive --parallel 20 --genome_folder genome_arab -o output CL_paired_bismark_bt2_pe.deduplicated.bam
```

**Comment by gourav924** [comment]
That's true. Thanks, Felix!
