### ISSUE TITLE
bismark in v0.23.1 does not generate *bismark_SE_report.txt

### ISSUE THREAD

**Issue by ccmeth** [FelixKrueger/Bismark#486]
How can I get the *bismark_SE_report.txt when I use the bismark with v0.23.1?

**Comment by FelixKrueger** [comment]
Hmm, why would it not? Can you link the command you were using, potential on-screen text and say which files it produces?

**Comment by ccmeth** [comment]
> 

Hi, thanks for your reply. The version of bismark I used is v0.23.1, and the command in terminal is "bismark --bowtie2 --path_to_bowtie2 </..../> -un </genome reference/> my_fastq_file", and only bam file was generated. The content of *bismark_SE_report.txt (including final alignment report, final cytosine methylation report) was displayed on my screen.

**Comment by ccmeth** [comment]
> Hmm, why would it not? Can you link the command you were using, potential on-screen text and say which files it produces?

Hi, thanks for your quick reply. The command in the terminal is "bismark --bowtie2 --path_to_bowtie2 </bowtie2 location> -un </genome folder/> fastq1 & bismark --bowtie2 --path_to_bowtie2 </bowtie2 location/> -un -pbat </genome folder/> fastq2", and only bam files were generated. The content of *SE_report.txt (including final alignment report, and final cytosine methylation report) was only displayed on the screen.

**Comment by FelixKrueger** [comment]
This sounds bizarre, I have never heard that before. If the final overview is getting produced it looks like you the program is technically running OK. Can you run just a single command and send me the the log file? (just wrap it with `nohup ...&`)

```
bismark --bowtie2 --path_to_bowtie2 </bowtie2 location> --genome </genome folder/> fastq1
```

This should definitely produce the mapping report file as well.

**Comment by ccmeth** [comment]
> This sounds bizarre, I have never heard that before. If the final overview is getting produced it looks like you the program is technically running OK. Can you run just a single command and send me the the log file? (just wrap it with `nohup ... &`)
> 
> ```
> bismark --bowtie2 --path_to_bowtie2 </bowtie2 location> --genome </genome folder/> fastq1
> ```
> 
> This should definitely produce the mapping report file as well.

Thanks for your suggestion! I close this issue and will try it.
