### ISSUE TITLE
Using bed file

### ISSUE THREAD

**Issue by muntajihad** [FelixKrueger/Bismark#488]
Hi Felix,
Is there any way to use a BED file to make the alignment (or methylation extraction) to concentrate on a specific range of regions. 
Many thanks

**Comment by FelixKrueger** [comment]
I'm afraid there is isn't supported specifically. As work-arounds you could either make a very small custom genome just containing the region(s) you are interested in, alignments to such small sequences are staggeringly quick. Or, you could filter the BAM file for certain regions with a bedfile in e.g. Samtools. This might however be a bit tricky with paired-end BAM files as to my knowledge such filtering simply works on an overlap basis, which means there is a chance you could lose the Read1-Read2 order of the Bismark BAM file (which is required for correct paired-end methylation extraction).
