### ISSUE TITLE
Issue with --local module

### ISSUE THREAD

**Issue by AST87** [FelixKrueger/Bismark#490]
Hi Felix,

I am using Bismark Version: v0.22.3 and I am trying to perform a soft-clipping of my NMT-seq BSC data. When I am using the following command:

`bismark --multicore 8  --genome /data/Genomes/ -q -1 /data/MiSeq.scNMT/GC121284_ATCACGTT.220330.R1.fastq.gz -2 /data/MiSeq.scNMT/GC121284_ATCACGTT.220330.R2.fastq.gz --non_directional --local -o /data/NMT_ana/bismark_out/Non-directional/bam/ --nucleotide_coverage`

I am getting an error:

`Unknown option: local`
`Please respecify command line options`

Could you please suggest where could be the issue?

**Comment by FelixKrueger** [comment]
Hmm, to be honest the most straight forward answer would be that you were using a version prior to supporting local alignment... Could you run `bismark --version`? And next I would probably try to lose all options that are not required to see if there is a weird spelling error or so in the name. I would probably move into the folder containing the files, and then run:

```
bismark --genome /data/Genomes/ -1 GC121284_ATCACGTT.220330.R1.fastq.gz -2 GC121284_ATCACGTT.220330.R2.fastq.gz --non_directional --local
```

**Comment by AST87** [comment]
As mentioned, I am using the latest version of Bismark i.e. v0.22.3
`Bismark Version: v0.22.3`
Though I am copying my command options from
`bismark --help`
I will still look into spelling errors, as suggested by you. Thanks

**Comment by AST87** [comment]
I understood the issue. It has to do with the order of commands. If that order is disturbed, Bismark stops recognizing the command. Thanks again for your help.
