### ISSUE TITLE
Tips for low mapping efficiency runs

### ISSUE THREAD

**Issue by LedaKatopodi** [FelixKrueger/Bismark#491]
Hello~

I have been working on a WGBS dataset with ~400M reads per sample (post-trimming), PE150bp. For 6 out of 10 samples I achieve a pretty good mapping efficiency (67-78%), but for the rest I have a mapping efficiency of ~13%.

I have followed [your suggestions](https://github.com/FelixKrueger/Bismark/issues/317) for salvaging the low mapping efficiency libraries, but I do not observe any differences. Do you have any additional tips?

 More than happy to provide any information regarding the commands I run, etc.
 
 Cheers,
 Leda

**Comment by FelixKrueger** [comment]
HI Leda,

Yes I think it might help to take a look at some sample reads for the 4 samples that don't appear to be behaving well. Could you prepare subsamples (untrimmed, maybe 500K-1M reads, gzip compressed) and share them with me? I would also need to know which genome you were using. Cheers, Felix

**Comment by LedaKatopodi** [comment]
Hi Felix,

Thank you very much for proposing to give this a look!

I have prepared the subsamples, 1M reads paired per sample; they can be accessed through this [transfer link](https://we.tl/t-B2Bkb4jzLQ). The samples are human, I am using hg38 (Ensembl v98).

More than happy to provide any additional information.

Thanks a lot,
Leda

**Comment by FelixKrueger** [comment]
Thanks for that, I'll try to take a look tomorrow.

**Comment by FelixKrueger** [comment]
I did now have a look at your data, here are some conclusions (you didn't specify how the data was prepared, so I took an unbiased approach):

- the data appears to be non-directional
- the data carries some compositional bias at the first at least 9bp, so I carried out tests trimming off 10bp from the 5' ends more might be needed)
- the compositional bias also results in a drop in methylation levels (see M-bias plots for the unclipped MultiQC report attached)
- I couldn't see any 'typical' contaminants in the file, such as spike-ins or bacterial contamination
- even after trimming, a fair amount of sequences had a GC content of >50% and higher. This is almost certainly some kind of contamination, possibly adapter dimers, polyG sequences. It might also have to do with the library preparation protocol used, maybe it would be worth following their advice for data handling?
- the mapping efficiencies in single-end mode was consistently ~40%
- the mapping efficiency in paired-end mode was > 30% (and default mapping parameters)
- the fragment insert size was mostly in the region of 100-250bp, so the fragment length restriction of 500 is plenty high and doesn't lead to reduced mapping efficiency
- alignment with relaxed mapping parameters increased the mapping rate only moderately
- alignment with `--local` increased the mapping rate to >80% (in single-end mode), and 70-80% in paired-end mode. It might be worth exploring where these alignments come from, and what causes to sequence to not to align properly in end-to-end mode

I hope this helps a little?

[Archive.zip](https://github.com/FelixKrueger/Bismark/files/8727648/Archive.zip)

**Comment by LedaKatopodi** [comment]
Hi Felix,

Thank you so much for going into such detail with this dataset, all your comments are extremely insightful!

Some follow-up questions:
- The Zymo kit was used for the bisulfite treatment. The Nextflow core suggests the following [trimming parameters](https://nf-co.re/methylseq/1.6.1/parameters#adapter-trimming) - I am using Trim Galore for trimming:

```
--clip_r1 10
--clip_r2 15
--three_prime_clip_r1 10
--three_prime_clip_r2 10
```

I also noticed some adapter contamination (~10% of reads in some of the samples, for R2 specifically) and I remove those in a second pass. Does this sound like a good approach for the trimming?

- Would you suggest an alignment with `--local`? PE or SE? I will follow up on your observation and give the sequences that fail to align end-to-end a second look, but I am skeptical about using local alignment for my final results. Your thoughts?

Any additional insight greatly appreciated!

Cheers,
Leda

**Comment by FelixKrueger** [comment]
The trimming recommendations from nf-core are fine, this is also what we tend to suggest. I would probably not bother for a second round of trimming, as sequences with residual adapter won't align anyway (this kind of is equivalent to trimming...). 

This might however be different with local alignments. I suppose what you could do would be to run end-to-end alignments first, while specifying `--unmapped`, and then run a second round of alignments (`--non_dir`) with `--local`. This should then be informative to figure out whether there is a certain type of genomic element that is affected especially....

**Comment by LedaKatopodi** [comment]
Thank you for the suggestions Felix, I will give this a go. I am closing the issue -at least for now.

Thanks a lot!
