### ISSUE TITLE
Coverage after deduplication step

### ISSUE THREAD

**Issue by mo716** [FelixKrueger/Bismark#493]
Hi! I hope this message finds you well. I am interested on estimating the coverage right after the deduplication step from 150 PE reads alignments. The deduplicate_bismark command with the -o option generates a log file (*deduplication_report.txt) with a line showing the total count of leftover sequences after deduplication. An example of such line is found below:

`"Total count of deduplicated leftover sequences: 56878632 (78.71% of total)"`

Based on this, I would like to ask: is the number of leftover sequences above including both forward and reverse libraries? Or does it mean that 56878632 reads from each library remained after deduplication?

Thank you very much for any answer in advance :)

**Comment by FelixKrueger** [comment]
Yes, this means that your final, deduplicated BAM file should have 56,878,632 read pairs. 

The coverage calculation of is a function of the fragment length* and the genome size 

*ideally better: the non-overlapping portions of Read 1 + Read 2. For simplicity, if we assume an average fragment length of 150bp, and the human genome with a size of roughly 3,000,000,000 bp, the calculation would be:

  56,878,632 * 150 / 3,000,000,000 = 2.8X 

As a rough ballpark figure.

**Comment by mo716** [comment]
Hi! Thank you very much for you kind and quick reply! 

Just a couple of things that I am not too clear about and would appreciate your help with:

1 - If there are 56,878,632 read pairs, should not the coverage calculation be:

`56,878,632 * 150 * 2 / 3,000,000,000 = 5.6X` ?

2 - It seems that a 30x coverage is recommended for methylation studies but somehow I have not found clear evidence if this is
suggested for coverage before aligning **OR** after trimming, aligning and deduplicating. I am working with _Brassica napus_ (1.1 Gbp). The genome was prepared with bismark_genome_preparation. Each 150 bp pair ended library for the example above had 101 M reads, and consequently a total coverage of 27.55x (Coverage= (101,000,000 * 150 * 2)/1,100,000,000) .

Then the libraries were trimmed and aligned following the suggestions for TruSeq (EpiGnome) technique. I am aware that the alignment rates for the genome of interest are about 60-70% so the coverage after alignment and deduplicating should decrease. I estimated the coverage after deduplicating as either:

`56,878,632 * 150/ 1,100,000,000 = 7.75X or
56,878,632 * 150 * 2 / 1,100,000,000 = 15.51X`

depending on whichever of the calculations above is correct.

I observe, though, that the difference between the original estimated coverage (27.55x) and the coverage after deduplication (here as 7.75x) is a bit big.  In the end, I calculated methylation level and mC counts and found DMRs already; which altogether worked very well. My questions, however, are:

What are your thoughts regarding the pronounced coverage decrease? Do you consider that post-methylation alignment analyses (e.g. methylation level estimation, DMR calling) can still be valid with the deduplicated coverage?

I have found this paper in human research (Ziller et al 2015; https://doi.org/10.1038/nmeth.3152), where low coverage (5-15x) still allows DMR detection; but there does not seem to be mentions on deduplication on the paper nor in the supplementary files, so I am still unclear on how relevant the deduplicated coverage might be.

Thank you very much once again for your patience and help indeed

**Comment by FelixKrueger** [comment]
To 1): 

If you have performed paired-end 2x150bp sequencing, and the reads were neither trimmed not overlapping, your calculation would be correct. However, experience shows that BS-seq data is often much shorter than other standard sequencing applications, with fragments often being in the range of 80-150bp. If you had a fragment of 150bp, and sequence it from with R1 with a length of 150 bp from the top strand, as well as R2 (also 150bp) in reverse orientation, the fragment is still only 150 bp long in total. Thus, 2x150 bp sequence does not mean that you can (or should) include the both R1 and R2 into the calculation. Does that make sense?

To 2):

I think the 30X coverage is a nice figure that is probably guided by variant calling procedures. In reality, hardly any samples ever achieve such a coverage, often it is something much more practical, such as 'one line of HiSeq' for a sample, or similar. In my experience, people just work with whatever they have, which often isn't more than 1-5X for mammalian genomes (if that). One can, at least to some extent, achieve better statistical power to detect DMRs by aggregating data over larger regions. So I would just go ahead trying to identify DMRs, and should you find that you would benefit from additional sequencing coverage you could simply perform some more sequencing?

**Comment by mo716** [comment]
Super! Thank you very much for the detailed answers. Now it's much clearer to me! I had not considered the trimming and overlapping characteristics from BS-seq that you mentioned. Thank you very much also for sharing your experience and  comments on the second question. That was very helpful! 

Have a nice day! :)
