### ISSUE TITLE
sam merger issue and vim warning

### ISSUE THREAD

**Issue by Lu-103** [FelixKrueger/Bismark#496]
Dear Felix,

Hi, I am using bismark and some of my samples encountered the following problem at the end of the run:

Right, cleaning up now...

Deleting temporary sequence files...
Now merging BAM files SRR_1.fastq.temp.1_bismark_bt2_pe.bam SRR_1.fastq.temp.2_bismark_bt2_pe.bam SRR_1.fastq.temp.3_bismark_bt2_pe.bam into >>> SRR_1_bismark_bt2_pe.bam <<<
Use of uninitialized value $samtools_path in concatenation (.) or string at /storage/gbcl/qiaolu/Bismark-0.23.0/bismark line 1369, <IN2> line 273336556.
Merging from file >> SRR_1.fastq.temp.1_bismark_bt2_pe.bam <<
Use of uninitialized value $samtools_path in concatenation (.) or string at /storage/gbcl/qiaolu/Bismark-0.23.0/bismark line 1383, <IN2> line 273336556.
Merging from file >> SRR_1.fastq.temp.2_bismark_bt2_pe.bam <<
Use of uninitialized value $samtools_path in concatenation (.) or string at /storage/gbcl/qiaolu/Bismark-0.23.0/bismark line 1380.
Vim: Warning: Output is not to a terminal
Vim: Warning: Input is not from a terminal

I am not sure why this happened, but it seems the previous steps are completely fine. (I have compared with the runs that were finished normally.)
The output bam file is an empty file, so I am wondering if I could manually merge these temp files so that I don't have to rerun the whole process, or should I just start again?

Thank you so much!

**Comment by FelixKrueger** [comment]
Hmm, it seems that it didn't find a path to samtools for some reason, but I really don't know why you should have gotten working BAM files (for which you would require samtools as well), and then it would only fail for the merging step...

You could probably merge the files by hand, but I would probably still try to re-start the run again to see if the same issue arises again? Do you have samtools in your PATH, and if not, can you specify its location using `--path_to_samtools ....` (check --help for the exact spelling).

**Comment by Lu-103** [comment]
Thanks for the advice, I load samtools in the environment and rerun the process, and I still got the same result with some additional errors. The output is still empty, and the mapping time is a lot faster than the normal run. I have attached the err file for direct reference.

**Below is the job I submitted to the system, just in case I make some mistakes here:**

module load bowtie/2.4.2 
module load samtools/1.14 
/storage/Bismark-0.23.0/bismark --parallel 3 -p 3 --genome /storage/METH -1 SRR_1.fastq -2 SRR_2.fastq -o /storage/mapping/SRR

It is quite strange since I got it to work the first time with other samples, and I have not changed the command. I would be really thankful if you could provide any possible solutions...

[SRR5479507.txt](https://github.com/FelixKrueger/Bismark/files/8891077/SRR5479507.txt)

Thank you!

**Comment by FelixKrueger** [comment]
This is really weird, as Samtools is clearly found :

```
Alignments will be written out in BAM format. Samtools found here: '/soft/bio/samtools-1.14/bin/samtools'
```
And is working to write out the 3 initial temporary BAM files. I really am at a loss to say why it would not remember it later.... 

To find the issue I would probably just take the first 100 lines of your FastQ files in question to speed things up (by the way, were they trimmed with Trim Galore? They should!) and then try out a few things to see if it helps:

- lose `--parallel` and see it finishes fine
- lose `-p 3` to see if this has any effect
- drop the path information from the files to see if this works,
- drop `-o` to see if that's involved
But yea, ultimately this seems to be something very unique to your system....

**Comment by Lu-103** [comment]
Thanks for the advice, I tried without -- parallel and -p 3, and the run finished successfully.
Just took longer, but I am okay with it.
Thanks again!
