### ISSUE TITLE
feature request: explicit --single-ended input file

### ISSUE THREAD

**Issue by avilella** [FelixKrueger/Bismark#5]
Samey as with explicit `--genome_folder`, in case the input is not paired-ended, which has explicit `-1` and `-2` parameters, it would be useful to have an `-se` explicit option for single-ended input files.

perl's GetOptlong also allows synonyms via the pipe separator, so maybe add a short 'se' and a longer 'single_end' option would be convenient:
```
'se|single_end|single_fragment' => \$name_of_variable,
```
I think that covers all the implicit options that rely on the order of parameters being passed.

**Comment by FelixKrueger** [comment]
Would you have in mind an option to effectively skip processing the arguments provided in `@ARGV`, such as providing a (comma-separated) list of files like so:
`--single_end file1.fq.gz,file2.fq.gz,file3.fq.gz` ?

**Comment by avilella** [comment]
Yes, that would be great!

I would favour using ":" over "," (comma) as a separator, since it's
cleaner for certain bash evals, but that would mean banning the ':'
character in the input fastq files.

A.

**Comment by FelixKrueger** [comment]
Added new option:
`--se/--single_end <list>Sets single-end mapping mode explicitly giving a list of file names as <list>.
                         The filenames may be provided as a comma [,] or colon [:] separated list.`
