### ISSUE TITLE
Check for truncated BAM files

### ISSUE THREAD

**Issue by ewels** [FelixKrueger/Bismark#50]
Truncated BAM files are super scary - not only is data lost, but because the read pairing gets messed up, incorrect methylation calls can be generated.

BAM files should have EOF tags, making it possible to detect when they have been truncated. Could Bismark deduplication / methextraction steps check for this and either bail or throw a big scary warning if they're not found?

**Comment by avilella** [comment]
+1 on this feature.

We found a case like this recently: it wasn't bismark's fault, it was
Dnanexus doing an incomplete upload after alignment, but it went silently
without complaining...

**Comment by s-andrews** [comment]
Just a warning about this - just checking for the end tag doesn't catch all cases.  In SeqMonk we use the picard libraries which does a check for the end tag - but we still get BAM files which pass this test which are incomplete.  I've not dug into it to find out if you can do a standard truncation and get the tag by chance or if there's other cases which can cause this but we've found a bunch of different failure modes for corrupted (mostly truncated) BAM files.

**Comment by FelixKrueger** [comment]
Added EOF detection for `deduplicate_bismark` (ace0f359d37f62e6b4ac5d05c68d3fa310ee2695) and `bismark_methylation_extractor` (39013859980ffc5df1ae8b826d54928c9da218b3). Hope it will stop at least some of the most serious truncations.

**Comment by ewels** [comment]
Phew! Thanks @FelixKrueger 😀
