### ISSUE TITLE
hts-spec tags for modified bases

### ISSUE THREAD

**Issue by rrazaghi** [FelixKrueger/Bismark#500]
Hi Felix,

I was wondering if there are plans to add support for modified base bam output using MM and ML tags (https://github.com/samtools/hts-specs/blob/master/SAMtags.pdf). This would be really beneficial in the future as a lot of tools are adapting to this standard format.

Thanks!

**Comment by FelixKrueger** [comment]
Hi @rrazaghi

Thanks for your question, you are now the second party interested in this. I have now read section 1.7 of the SAM format specification, here are my initial thoughts:

- at first glance, it is a great move to bring the concept of base modifications to SAM files (I vaguely recall having been in an email thread at the very beginnings of this movement several years ago, this seems to the be final outcome of it)

- at second glance, while this great initiative, I assume this is probably more relevant for long or circular reads, or reads that can detect several different modifications natively, such as ONT or PacBio. Correct me if I'm wrong here, but in this regard bisulfite modification of short-ish reads is really rather 'boring', as at the read level it really only detects 'methylation', and that as a binary decision (which would mean that the `ML:B:` field would simply have probabilities of 1 throughout). 

- The `MM:Z:` and `ML:B:` fields do in theory not add anything new to the output, they are just a different representation of the information that is already present via the mapping coordinates, the `CIGAR`, `MD:Z:` and methylation call strings. I reckon they could be a useful alternative in the future, but I couldn't possibly just replace the current output with the new optional tags as I assume this would break a lot of things (if anything then maybe as an option so the the new tags could be output in addition to the default output?)

- Another consideration is also that adding two additional strings (with identical information content) would simple result in longer processing times, and increased file sizes, something that is probably difficult to justify. 

- Last but not least, one would think: all the information that is needed should be around anyway, so it should be fairly trivial, right? My worry would be that this wouldn't be exactly straight forward, as we still need to deal with all kinds of scenarios where we have:    
    - four different potential strands (OT, OB, CTOT, CTOB), and SAM format only rally deals with 2 strands
    - as I understood it, the `MM:Z:` and `ML:B:` are not the same as the `SEQ` field, which has to be reference forward strand based with the leftmost sequences first (something that may come off a sequences very differently). In contrast, the `MM:Z:` and `ML:B:`  are supposed to be sequence specific and 5' - 3' oriented. This would essentially mean one would have to completely recompute the `CIGAR`, methylation call, position, genome conversion and read conversion fields and then treat is sequence and not reference based
    - soft-clipping would need to be factored in as well, as an additional issue for the point above.

I am not saying it can't be done, but to be very honest it seems like a lot of trouble for essentially no added benefit. I would therefore say that it currently isn't very high on my priority list... 

If there was a very pressing use case that would demand such changes, it could of course change the situation.... (I suppose one could also envisage decoupling it from the Bismark alignment step entirely and having a post-processing script....). 

So, the question is: do you have a very pressing use case? :)

**Comment by rrazaghi** [comment]
Hi Felix,

Thanks a lot for the detailed response. I've been thinking about this for a bit now. I think I agree with everything you mentioned. 
I do think it would still be beneficial to have this option especially for the long read mode in bismark. This would enable users to compare and use all long-read methylation data in the same downstream processing tool regardless of using native long-read methylation callers or long-read EM-seq for example.

I do agree though that its not a very pressing case, rather providing more convenience for the end-user :)

**Comment by FelixKrueger** [comment]
Thanks for your comments. I have made a mental note that this might be a welcome convenience feature for a future release. Cheers, Felix
