### ISSUE TITLE
M-bias plot

### ISSUE THREAD

**Issue by itossolini** [FelixKrueger/Bismark#502]
Hi Felix,
I'm analyzing plant BS-seq data and I've had trouble figuring out why R2 reads have bias on methylation calls and how to fix it. I ran bismark_methylation_extractor with the --ignore_r2 2 option and these are the results:
![Captura de pantalla de 2022-07-08 14-35-01](https://user-images.githubusercontent.com/70298315/178042240-58e5a087-a959-4f0e-82ad-b868ec6257d0.png)
![Captura de pantalla de 2022-07-08 14-34-51](https://user-images.githubusercontent.com/70298315/178042245-795cb541-81e6-409c-8c18-5b54ebc58d94.png)
I appreciate your help with this issue.

**Comment by FelixKrueger** [comment]
Hi @itossolini 

If just look at the lines in bold, both R1 and R2 have pretty much the same level of methylation in each context, from start to end (with a tiny 'blip' for R2 at position 2, probably nothing to worry about).

The other, lighter curves are the total number of methylation calls performed for a given position, and I suppose your question is: "why do these lines drop so much for R2 but not R1?" The answer to that is mostly that this is a result of the overlap detection and removal, which occurs every time R2 starts overlapping R1. So in other words, the fragment length in your samples seemed to have been mostly in the range of 100-200bp, but your sequencing was done with 2x150bp reads - resulting in a lot of R2 information getting discarded as redundant data. This is very typical for bisulfite libraries, and nothing to worry about (there isn't much you could do about it either at this stage). Does this make sense?

**Comment by itossolini** [comment]
Hi @FelixKrueger 
Yes! Thank you for the clarification.
