### ISSUE TITLE
bismark failing

### ISSUE THREAD

**Issue by alyzas** [FelixKrueger/Bismark#503]
I have human WGBS data and would like to use bismark to align the data, however, I keep getting this error message: scaffolds/contigs/chromosomes frequently encountered errors with pre-sorting reads to 
 individual chromosome files. These errors were caused by the operating system's limit. 
I re-run bismark using the the following command: bismark_methylation_extractor  --gzip --paired-end --multicore $NSLOTS --scaffolds --buffer_size 10G --bedGraph --cytosine_report --genome_folder /data/ngsc4data/JE03JHU502/reference/hg38 ${samplename}_bismark.deduplicated.sam and get the same error. I am using 40G of memory and 24 cores. 
Thank you.
Alyza

**Comment by FelixKrueger** [comment]
The formatting of your command looks very funky to me, could you try to copy/paste the text you see on the screen and use ``` on either side? I am wondering if you pasted the command from a MS Word or PDF document, which might lead to formatting issues? The single most important option you will need is `--scaffolds`.

**Comment by FelixKrueger** [comment]
If the methylation has already worked, and completed, you should be able to move on to the bismark2bedGraph stage straight away:

```
bismark2bedGraph --gzip --scaffold -o output_CpG.cov CpG*samplename*txt
```
