### ISSUE TITLE
CpG sites that are not in the reference genome

### ISSUE THREAD

**Issue by lkerr34** [FelixKrueger/Bismark#505]
Hi and thanks for such a useful tool!

I have been using the methylation extractor and have noticed that I end up with some CpG sites being called that were not in my reference genome (they correspond to cytosines within other contexts but are called in CpG context). Can bismark detect "de novo" CpG sites within samples (i.e. CpG sites that are not in the reference)?

Thanks!

Lyndsay

**Comment by FelixKrueger** [comment]
Hi Lyndsay,

I believe I've got the answer for you [right here](https://github.com/FelixKrueger/Bismark/blob/master/Docs/FAQ.md#issue-3). A very short version of this is that sometimes deletions right downstream of C positions may introduce a context change.

Let me know if this didn't answer your question.

**Comment by lkerr34** [comment]
Thank you so much for your response - this has indeed answered my question!
