### ISSUE TITLE
/usr/bin/env perl ...?

### ISSUE THREAD

**Issue by ewels** [FelixKrueger/Bismark#51]
On our clusters, we have a system wide perl but mostly run a different version of perl loaded through the environment module system. However, the bismark scripts have `/usr/bin/perl` hashbangs at the top so always run on the system version. Currently the sysadmins go through each script editing this every time they load a new version. Any chance you could change it to `/usr/bin/env perl` in a future release so that it uses whatever the default perl path is?

I have a feeling that you guys had quite strong feelings about this, but I can't remember what they were or why, so I'm preparing myself for a fierce rebuttal 😬

**Comment by FelixKrueger** [comment]
Shortly after starting to write a fierce rebuttal I changed my mind and changed all shebangs to now use `/usr/bin/env perl` in a bid to follow the path of least resistance. I hoping that this will still work for most users and not break on too many systems...

Addressed here: 611bdb9a80783faa4ca3401068d13ce30a5f3114.
