### ISSUE TITLE
CTOT/CTOB tagged files in methylation extraction results

### ISSUE THREAD

**Issue by ilkertu** [FelixKrueger/Bismark#510]
Hi Felix,

I have a question regarding the methX output files, 
I did paired-end alignment with default directional option, 
but after methylation extraction, I see files named as CpG_CTOT_ ... or  CpG_CTOB_  even though it is a directional library?
I was wondering whether these are valid alignments?
 
Thank you

**Comment by FelixKrueger** [comment]
Hmm, I would agree that you would only like to see OT and OB files there. Is there a chance that you have accidentally run the methylation extractor in single-end mode, or used a not quite up-to-date version of the Bismark (where the auto-detection would sometimes not detect paired-end mode properly)?

**Comment by ilkertu** [comment]
Thank you for your quick response,

It is the latest version, v0.23.1
I also can confirm  from the log file that it runs in paired-end mode, 
for some reason the CTOT files are not empty and  not deleted at the end, 
it seems that in the methylation script,
OT/CTOT/OB/CTOB  is assigned based on the read1 (first in pair) , 
and as far as I see the read1 is based on the order not the flag, 
maybe the order in some reads changed?

**Comment by FelixKrueger** [comment]
I just confirmed that standard directional, paired-end alignments only produce OT/OB alignments and C* context files, as expected. 

Reasons for why this might happen in could include:
- the mapping was carried out in `--non_directional` mode (could you do `samtools view -H` and link the `@PG` line(s) here?
- maybe the order has been changed from the original BAM file, e.g. by positional sorting and then re-sorting by name? In theory, as soon as readIDs of consecutive lines do not match anymore, the methylation extractor should terminate with an error message. Have you (or anyone else) involved any third party programs between the Bismark mapping and methylation extraction steps?

**Comment by FelixKrueger** [comment]
Thanks for the details, I hope you'll find a way to get this to work eventually. Just for the record, I believe the methylation calls will be at the correct positions, but I would think that the strand assignment would be wrong - also the overlap detection and removal might not work correctly for such reads....
