### ISSUE TITLE
Difference betn CpG_123.deduplicated.txt.gz and 123.deduplicated.CpG_report.txt.gz

### ISSUE THREAD

**Issue by chasingdex** [FelixKrueger/Bismark#512]
What is the difference between CpG_123.deduplicated.txt.gz and 123.deduplicated.CpG_report.txt.gz? 
How do we generate 123.deduplicated.CpG_report.txt.gz?
Seems like MethylKit package accepts 123.deduplicated.CpG_report.txt.gz and not the former file as input as the so called "bismarkCytosineReport". 
But when I use the bismarktocytosine module, I rather get the CpG_123.deduplicated.txt.gz output and not the latter. Pretty confusing!! 
 CpG_123.deduplicated.txt.gz
<img width="722" alt="image" src="https://user-images.githubusercontent.com/92947920/180320292-13b0c1e9-e14a-4f13-8cbc-93b63af44fb6.png">

123.deduplicated.CpG_report.txt.gz
<img width="369" alt="image" src="https://user-images.githubusercontent.com/92947920/180320358-c260e74f-bf55-48f3-b80e-a6d9bf2c32ba.png">
Thanks admin. @FelixKrueger

**Comment by chasingdex** [comment]
CpG_123.deduplicated.txt.gz
<img width="722" alt="image" src="https://user-images.githubusercontent.com/92947920/180320292-13b0c1e9-e14a-4f13-8cbc-93b63af44fb6.png">

123.deduplicated.CpG_report.txt.gz
<img width="369" alt="image" src="https://user-images.githubusercontent.com/92947920/180320358-c260e74f-bf55-48f3-b80e-a6d9bf2c32ba.png">

**Comment by FelixKrueger** [comment]
The file `CpG_123.deduplicated.txt.gz` is the primary output of the methylation extractor (`bismark_methylation_extractor`: https://github.com/FelixKrueger/Bismark/tree/master/Docs#iv-bismark-methylation-extractor).

The file `123.deduplicated.CpG_report.txt.gz` is the output of `coverage2cytosine`: https://github.com/FelixKrueger/Bismark/tree/master/Docs#optional-genome-wide-cytosine-report-output.

You can get this by running sequentially `bismark_methylation_extractor` -> `bismark2bedGraph` -> `coverage2cytosine`, or in a single convenient step like so:

```
bismark_methylation_extractor --gzip --bedGraph --buffer_size 10G --cytosine_report --genome_folder /path_to_genome_folder/ sample_bismark_bt2.bam
```
