### ISSUE TITLE
Is it Okay to sort bismark bam by position, process the bam, then sort the bam by read name again before calling methylation?

### ISSUE THREAD

**Issue by yangdingyangding** [FelixKrueger/Bismark#513]
Hi,

We currently need to remove/modify some unwanted alignments on the `bismark`-aligned and `bismark`-deduplicated bam (which is sorted by read name) before sending it to `bismark_methylation_extractor` . Because the bam is very big, we'd like to process this bam in parallel, which calls for a bam index and thus a position-sorted bam.

Now comes the question: if I do the following, will the methylation calling result be correct?
1. sort the deduplicated bam by position
2. process the position-sorted bam
3. sort the processed bam by read name
4. feed the read name-sorted bam to `bismark_methylation_extractor`

Regards,
Yang

**Comment by FelixKrueger** [comment]
HI Yang,

In theory, I believe this procedure should work except if the alignments were performed in **non-directional mode**.  There have been issues in the past (e.g. this one here: https://github.com/FelixKrueger/Bismark/issues/170).

If you have directional alignments, and perform the sorting/re-sorting procedure, the `bismark_methylation_extractor` should a) run to completion without complaining about non-matching read IDs, and b) only produce methylation calls for the OT and OB strands. There has also been a very recent issue where this was not the case after using different tools: https://github.com/FelixKrueger/Bismark/issues/510. I hope it'll work!

**Comment by yangdingyangding** [comment]
Hi Felix,

Thanks for your reply! I looked into #170 and found the following:

> As you stated, re-sorting a positionally sorted BAM file by name with samtools brings R1 and R2 into the correct order again. 

and: 

>And as a final note: the corner-case issue of positionally sorting and then re-sorting by name that aforementioned positionally sorted file with sambamba discussed here may result in incorrectly assigning the strand from OB to CTOB. This should however not make any difference for the actual methylation call itself, because both OB and CTOB report on the very same C positions on the bottom strand. So it really is rather a cosmetic issue affecting read orientations anyway.

So it seems that, for `bismark_methylation_extractor`, the only thing matters in the "read order" of the input bam is: each two read ends of the same read pair must be put in consecutive lines, with the first read (flag 64) put first the second (flag 128) put second. The ordering of different read pairs does not matter. Furthermore, modifying/removing some read pairs in the bam without disrupting the bismark-related tags will not affect the methylation calls from other read pairs.

Therefore, I assume it doesn't affect the methylation results called if I do the following before running `bismark_methylation_extractor`, even if I used `non_directional`:
1. `samtools sort` the bismark-deduplicated bam;
2. manually trim the alignment of each read pair from both ends (which does not change the read order in the bam; the read sequence, read quality, tag XM, and tag MD are all trimmed to make the length consistent);
3. `samtools sort -n` the processed bam.

Is this correct?

**Comment by FelixKrueger** [comment]
This does sound correct, but if I were you I would want to check for a few examples if it does the right thing. Just to mention, we recently added a new flag `--strandID` [see here](https://github.com/FelixKrueger/Bismark/blob/dev/CHANGELOG.md#bismark) that might be of interest for sorting you are doing. Good luck!

**Comment by yangdingyangding** [comment]
Great, thank you for your clarification! We'll check the new `--strandID` option as well.
