### ISSUE TITLE
Can you add the TAPS parameter?

### ISSUE THREAD

**Issue by bio-Tao** [FelixKrueger/Bismark#515]
Can you add the TAPS parameter? When the data is compared to the reference genome, only convert cytosines in CpG context to thymines.

**Comment by FelixKrueger** [comment]
Hmm, I am not exactly sure I understand your question/request. If you are only interested in CpG context, can't just take the CpG context files?

**Comment by bio-Tao** [comment]
When running bismark_genome_preparation，I noticed that bismark will create two individual folders within this directory, one for a C->T converted genome and the other one for the G->A converted genome. When use TET-assisted pyridine borane sequencing (TAPS) for bisulfite-free direct sequencing of 5mC and 5hmC, Methylated cytosines in CpG context to
thymines and unmethylated cytosines remain unchanged. So I think when converted genome, only convert cytosines in CpG context to thymines, It can improve the accuracy of mapping for TAPS.

**Comment by bio-Tao** [comment]
Therefore, my requirement is whether a more suitable reference genome conversion for TAPS technology can be established, that is, only convert cytosines in CpG context to thymines.

**Comment by FelixKrueger** [comment]
So your reasoning would be that methylation in mammals occurs predominantly in the CG-context, and is typically quite low in non-CG context? Or is TAPS specific to CpG (I don't really see why it would be)?

In any case, with the read lengths that are available to use nowadays I would argue that the mapping efficiency of C-to-T converted reads/genomes is more or less equally as good if you kept some Cs in. the genomic sequence. On top of that, you are making assumptions on the context specificity, and the errors or unmapped reads introduced by ignoring non-CG methylation would probably outstrip any potential benefit.

**Comment by bio-Tao** [comment]
Traditional bisulfite sequencing converts most of the unmethylated C to T, leaving the methylated C unchanged and therefore converting the C in the reference genome to T when comparing to the reference genome. Taps sequencing is a new technique that only convert methylated C  to T, while leaving the unmethylated C unchanged. When use TAPS sequncing, most of the C in my sequence remains unchanged, and only the methylated C is converted to T ( predominantly in the CG-context ). When mapping, only convert C in CpG context to T of the reference genome, it will improve the accuracy of the mapping.

**Comment by FelixKrueger** [comment]
>> Taps sequencing is a new technique that only convert methylated C to T, while leaving the unmethylated C unchanged.

This is the exact issue. I do understand the logic that _most_ Cs in non-CG context are unmethylated, however this depends very much on cell type, or even organism (plants may have 5-50%? methylation in non-CG context....). As an example, if we assume 1 billion cytosines in non-CG context for the human genome, and a methylation rate of 5% (not uncommon for e.g. ooctyes, nerve/brain), you would find 50 million Cs methylated. Not converting non-CGs might 'improve' the mapping for a few select sequences (to a most likely negligible extent), however it would at the same time introduce a mapping bias against methylation in non-CG context, and therefore produce spurious results.

Given that a 'CpG-only' approach would only work a perfect world for a very select subset of cells at the best of times, but would most likely introduce incorrect biased alignments + methylation calls, I am afraid this isn't something I am prepared to pursue further.
