### ISSUE TITLE
mapping resources for help

### ISSUE THREAD

**Issue by Zeyu-An** [FelixKrueger/Bismark#516]
Hello!

I am tring to mapping my clean data (800 Gb) to a huge genome (>25 Gb).

So I wondering if I set `--parallel 4` and `-p 4`, how many cores and memery will be used?

Thank you very much!

**Comment by Zeyu-An** [comment]
Or do you have any good suggestions for dealing with such large genomes mapping to save times?

Really appreciate！

**Comment by FelixKrueger** [comment]
That is a lot of data, and a huge genome! I don't really have experience with mapping to genomes of that size, I suppose it would be easiest if you would maybe take the first 1 Mio reads or so, and then run a few tests regarding memory usage...

**Comment by Zeyu-An** [comment]
Thank for your help! I used 10G data and tested several times. Bismark used about 37Gb memery for one parallel. Then I set `--parallel 5` and `-p 16` , maybe is the best parameters for my sever. Btw, I found `-p 16` is much faster than `-p 4` in my test.

Thanks again for your suggestion!

**Comment by FelixKrueger** [comment]
thanks for leaving the feedback - especially about the `-p 16`..`
