### ISSUE TITLE
Regarding merging paired scBS-seq bam files

### ISSUE THREAD

**Issue by AST87** [FelixKrueger/Bismark#517]
Hello Dr. Krueger,
I am analyzing scBS-seq data using Bismark and following guidelines mentioned in [https://www.nature.com/articles/nprot.2016.187](url). After single-end mapping of reads through Bismark, I merged the files using samtools and followed to methylation extraction. However, it seems that due to my poor knowledge regarding merging of file, I am getting an error.

`bismark --multicore 8  --genome ./Genomes/ ./MiSeq.scNMT/*ATCACGTT*.fastq.gz --non_directional --local --gzip --nucleotide_coverage -o ./NMT_ana/bismark_out`
`Input files to be analysed (in current folder '/media/data/'):`
`./MiSeq.scNMT/GC121284_ATCACGTT.220330_Rosa.R1.fastq.gz`
`./MiSeq.scNMT/GC121284_ATCACGTT.220330_Rosa.R2.fastq.gz`

`deduplicate_bismark --paired --barcode --output_dir ./NMT_ana/Dedup/ ./NMT_ana/bismark_out/*ATCACGTT*.bam`

`samtools merge -n ./NMT_ana/Dedup/ATCACGTT.220330.R1_trimmed_bismark_bt2_dedup.bam ./NMT_ana/Dedup/ATCACGTT.220330.R2_trimmed_bismark_bt2_dedup.bam -o ./NMT_ana/merged/ATCACGTT.220330_merged.bam`

`bismark_methylation_extractor --multicore 8 -p ./NMT_ana/merged/ATCACGTT.220330_merged.bam --no_overlap --no_header\
 --remove_spaces --bedGraph --merge_non_CpG --gzip --cytosine_report --genome_folder ./Genomes/ -o ./NMT_ana/bis2bed_out/`

Error

`Now testing Bismark result file >./NMT_ana/merged/ATCACGTT.220330_merged.bam< for positional sorting (which would be bad...)`	
`The IDs of Read 1 (M04117:547:000000000-K6VK8:1:2115:15631:2390_2:N:0:ATCACGTT) and Read 2 (M04117:547:000000000-K6VK8:1:2115:21137:2447_2:N:0:ATCACGTT) are not the same. This might be the result of sorting the paired-end SAM/BAM files by chromosomal position which is not compatible with correct methylation extraction. Please use an unsorted file instead or sort the file using 'samtools sort -n' (by read name). This may also occur using samtools merge as it does not guarantee the read order. To properly merge files please use 'samtools merge -n' or 'samtools cat'.`

Could you please suggest a pipeline for proper merging of paired bam files?

[dedup_out.txt](https://github.com/FelixKrueger/Bismark/files/9310530/dedup_out.txt)

**Comment by FelixKrueger** [comment]
Hi @AST87 

The reason for the error you are getting is simply that merging two single-end mapped files doesn't make it a paired-end mapped file (but rather 2 merged single-end files).

As actual 'fix' for this you have several options:

1. you can run the deduplication in single-end mode (just let it use auto-detection), like so:
```
deduplicate_bismark --barcode *bam
```

followed by the methylation extraction:

```
bismark_methylation_extractor --bedGraph --gzip *deduplicated.bam
```

This would give you 2 coverage files, one for R1, one for R2, which you would then have to merge together, either in a downstream program, or  using script.

2. I believe merging the 2 single BAM files, followed by a single deduplication and methylation extraction process should also work (_not_in paired-end mode!)

3. The deduplication mode also has an option `--multiple` which effectively merges all files together for deduplication (should be similar to 2)

4. You could also run the steps as single-end files until the methylation extraction (without the `--bedGraph` option), and then run bismark2bedGraph on CpG (or all context) files you are interested in, e.g.:
```
bismark2bedGraph -o CpG_context_only_merged.cov.gz CpG*
```
This step would also merge the calls in CpG (in this example) context into a single coverage file.

If you are doing NMT-seq you might want to look at running `coverage2cytosine` afterwards using the `--nome` option.

So as you can see, one problem, but many solutions!

**Comment by AST87** [comment]
Hello Dr. Krueger,
The scBS-seq data that I have is a paired-end sequenced data and I have mapped it as per the recommendation in the mentioned paper (i.e. in single-end mode). So, I have two BAM files for the same data and now I need to merge these BAM files from both reads for imputation (for which coverage files are not fit). The method that you have suggested is not working for me. I also tried option 3 but I am not getting any output.

> deduplicate_bismark --barcode --multiple --output_dir ./Test/bismark/ ./Test/*trimmed_bismark_bt2.bam

`Output will be written into the directory: /media/data/Test/bismark/
The option --multiple is currently only working in default (= random alignment) mode
`

**Comment by FelixKrueger** [comment]
OK in that case suggested method 2. from should work:

>> I believe merging the 2 single BAM files, followed by a single deduplication and methylation extraction process should also work (_not_in paired-end mode!)

Your file `ATCACGTT.220330_merged.bam` is a merged BAM file, but you need to consider it as a single-end mapped file (because it is....)
