### ISSUE TITLE
dovetail read-pairs methylation calls

### ISSUE THREAD

**Issue by ilkertu** [FelixKrueger/Bismark#518]
Hi Felix,  

I would like to ask a question about dovetail read-pairs,

In PE mode with no_overlap option selected,
if we have a read-pair as below

                 X---------->   read1
          <------X----   read2

the methylation calling seems to start at position X on read1 and nothing will be called for positions < X on the second read?

In this case, the order would be important. 

Thank you for your time,

**Comment by FelixKrueger** [comment]
That is very well possible, I believe the extraction of read 2 just ends when an overlap is detected, and no sophisticated action is taken to keep track of what had actually been covered by read 1 in the first place. You should get the desired information if you allow overlaps, but I am not sure you want to be doing that ..

**Comment by ilkertu** [comment]
Thank you Felix, just wanted to double check

Best,
