### ISSUE TITLE
bismark2summary base filename question/snag

### ISSUE THREAD

**Issue by AstrobioMike** [FelixKrueger/Bismark#520]
Hi there!

First, thanks for developing and maintaining bismark :) 

Sorry if i'm missing something, i've looked a bit through the previous issues but can't sort this out.

When running `bismark2summary` without any deduplication step I have no snags with it, but when running it when there was a deduplication step, it's failing due to not being able to auto-detect the bismark report file from the `bismark` step for me. It's looking for something like this: 

"F-SRR12865062-test_trimmed_bismark_bt2.deduplicated_SE_report.txt" 

When the file is actually called this, without any 'deduplicated' string added yet:

"F-SRR12865062-test_trimmed_bismark_bt2_SE_report.txt"

Unless i'm confused, i think this is because to make the base filenames it is getting the bam files first and cutting off .bam, here: 

https://github.com/FelixKrueger/Bismark/blob/c487cf6d6e6f2942d7807c4cb39f15a0ce9c23a1/bismark2summary#L253 

But the bam files have been deduplicated (adding that to the suffix of all downstream files), while the initial output report from the `bismark` aligning step, which happens before the deduplication of the bams, doesn't have any 'deduplicated' added to it. 

Does it make sense there's a little snag here, or am i just confused/missing something?

Thanks for any help!
-Mike

**Comment by FelixKrueger** [comment]
Hi Mike,

the way `bismark2summary` works is to first detect the original BAM file created by Bismark, and then looking for the additional reports (alignment, deduplication, methylation extraction reports). This should work with or without deduplication, but I could imagine that it will break of the file names are changed manually at some stage. (I am also assuming you are using the latest version?)

The `.bam` is removed from the original Bismark mapped files, and then expected portions are added to this 'basename', i.e. `_PE_report.txt` or `_SE_report.txt` for the alignment reports, and something similar for the other types of report.

Only the following file names should be detected as original Bismark BAM files:
```
*bismark_bt2.bam
*bismark_bt2_pe.bam
*bismark_hisat2.bam
*bismark_hisat2_pe.bam
```

What are your file names called? In case the errors still shows up, could you list the filenames and maybe link the text you see on screen here?

**Comment by AstrobioMike** [comment]
Heya, thanks for getting back to me

Ohhh I see now. I was building this into a nextflow workflow (and therefore have to more specifically point/softlink to things rather than let the program find them because the process runs in a self-contained sub-directory), and I was linking all files *except* the original bams in the directory the bismark2summary process was happening in 🤦‍♂️ 

As you'd expect, works like a charm now that i'm also passing the non-deduped ones (which totally makes sense in hindsight with a fresh set of eyes)

I found it unlikely something like this could have possibly been missed until now, haha

Thanks for your help!

**Comment by FelixKrueger** [comment]
That sounds quite familiar from the early days when I was toying around with Nextflow :) I'm glad it's now all working!
