### ISSUE TITLE
Clarification of treatment to multimapping reads

### ISSUE THREAD

**Issue by yangdingyangding** [FelixKrueger/Bismark#523]
Dear Felix,

We need to remove all multimapping reads from Bismark (v0.23.0) bam. Running samtools flagstat did not give any 256 flags, and it seems that such multimapping reads will not be written to the final bam (from issue #336). 

However we are not sure about this, as this was not documented in Bismark's official manual (please correct me if I was wrong). Could you please confirm whether all multimapping reads would be removed from the final bam in the sense that any input read pair will occur at most one time in the final bam? And it would be best to ake this clear in the manual. Thanks!

Yang

**Comment by FelixKrueger** [comment]
Hi Yang, 

I can confirm that Bismark does not output multi-mapping reads at all (please also see the option `--ambiguous`, and `--ambi_bam`).

The Bismark manual (https://github.com/FelixKrueger/Bismark/tree/master/Docs#how-does-bismark-work) states:

>> ...Sequence reads that produce a unique best alignment from the four alignment processes against the bisulfite genomes (which are running in parallel) are then compared to the normal genomic sequence and the methylation state of all cytosine positions in the read is inferred. A read is considered to align uniquely if an alignment has a unique best alignment score (as reported by the AS:i field). If a read produces several alignments with the same number of mismatches or with the same alignment score (AS:i field), a read (or a read-pair) is discarded altogether.

So I would argue it has been there all along :)

**Comment by yangdingyangding** [comment]
Hi Felix,

Thanks very much for the clarification! It did save a lot of time on our project.
