### ISSUE TITLE
the best downstream program used for analyzing Bismark ouputs

### ISSUE THREAD

**Issue by biozzq** [FelixKrueger/Bismark#524]
Hi @all,

Do you have any recommended software used for downstream analyzing Bismark outputs, such as detecting regions of differential methylation, calculating methylation rate for targeted region, creating average methylation figure at specificed genomic regions (e.g., promoter), and so on. I would like use the command-line mode programs. I know you will recommend us to use SeqMonk, however I do not know how to run SeqMonk through the command line, as the same as running Bismark.

Looking forward to your reply, thanks.
Yours sincerely.

Zheng zhuqing

**Comment by biozzq** [comment]
Dear @FelixKrueger

I would like to follow up to making sure you have seen this minor issue.  Thank you in advance.

Best,
Zheng zhuqing

**Comment by FelixKrueger** [comment]
A package that seems to be fairly widely adopted is [methyKit]( (https://genomebiology.biomedcentral.com/articles/10.1186/gb-2012-13-10-r87)
