### ISSUE TITLE
Make *.deduplication_report.txt respect the user defined prefix set by -o

### ISSUE THREAD

**Issue by jinmingda** [FelixKrueger/Bismark#525]
When I run `deduplicate_bismark my.nsort.bam -o my`, it ends up giving me `my.deduplicated.bam` and `my.nsort.deduplication_report.txt`. I was wondering if `deduplicate_bismark` can change its behavior so that the deduplication report would also follow the prefix provided by `-o`. Thank you!

**Comment by jinmingda** [comment]
Maybe change the code from

https://github.com/FelixKrueger/Bismark/blob/c487cf6d6e6f2942d7807c4cb39f15a0ce9c23a1/deduplicate_bismark#L118

to

```perl
my $report = $file;
if ($user_defined_outfile){
	$report = $outfile;
}
```

**Comment by FelixKrueger** [comment]
Excellent point, I have now changed this behaviour in the latest commit (ed64377f6168adc17ce3186ad07b7e26c5aab594), can you clone the latest dev version and see if it works for you?

**Comment by jinmingda** [comment]
@FelixKrueger I tested it with the dev branch. It just worked like what I expected. Thank you! Please feel free to close the issue. Looking forward to the new release!

**Comment by FelixKrueger** [comment]
Excellent, thanks for the feedback.
