### ISSUE TITLE
Update samtools dependency

### ISSUE THREAD

**Issue by bounlu** [FelixKrueger/Bismark#527]
Hi,

Installing `bismark` from `bioconda` still depends on `samtools=1.6` which is very old and current version is `samtools=1.16`.
Please consider updating conda recipe for the dependency as otherwise it may broken things or forces users to use a very old version of samtools which is buggy and lack of many features.

Thanks.

**Comment by FelixKrueger** [comment]
I'm sorry but can you raise this with the Bioconda people? This really has nothing to do with Bismark as such.
