### ISSUE TITLE
bismark_methylation_extractor parallelise bedGraph sorting and cytosine report step by chr

### ISSUE THREAD

**Issue by avilella** [FelixKrueger/Bismark#53]
A feature request to parallelise bedGraph sorting and cytosine report step by chr.

Quoting Felix:

This step iterates through the genomic sequence, identifies every C and looks up whether or not the C was found in the coverage file. I theory this could be made more parallel, e.g. by doing it for each chromosome separately, but we did't find it very pressing to work on the efficiency of this step.

**Comment by FelixKrueger** [comment]
I realise that this option would be sort of convenient but since it is not a real bottleneck (adding another hour to a few days of processing...) I can't see it happening anytime soon to be honest. You are very welcome to contribute the code though... :)
