### ISSUE TITLE
low mapping efficiency for RRBS data

### ISSUE THREAD

**Issue by chiasinL** [FelixKrueger/Bismark#531]
Hello Felix,

I am working on a mouse data set of single-end, non-directional RRBS data - but have gotten a really low mapping efficiency of 25-28% for all samples. I trimmed the data with `trim_galore -q 30 --rrbs --non_directional` and another round of trimming with `cutadapt` because a bunch of Tru Seq adapters showed up as overrepresented sequences in `fastqc` reports. Then, I aligned the sequences with `bismark -N 1 --non_directional`.

While looking for ways to troubleshoot, I tried the strategies that you suggested in #265: screening for contamination with Fastq Screen, and trying `--score_min L,0,-0.4`. The latter increased mapping efficiency for ~5%. 

The fastq screen in `--bisulfite` mode for one sample looks like this:
<img width="1062" alt="image" src="https://user-images.githubusercontent.com/11150562/199544515-439b4ff6-e8da-4940-9d04-ad4bb86ee595.png">

Other than the no-hits reads, the rest of the reads mapped to multiple genomes. Do you have any idea what could have caused this? Can you please suggest the next things I should try for troubleshooting?

Many thanks,
Chia Sin

**Comment by chiasinL** [comment]
Hello Diego,

Let's see what Felix has to say. We might be having very different problems with our data. For mine, I am mostly concerned about 1) the excessively low mapping efficiency for a mouse data set (~25-28%) and 2) the ~40% reads that mapped to multiple genomes.

I have a hypothesis that these ~40% reads are probably low complexity and/or short reads - these might have something to do with the adapter contamination that I mentioned 🤷‍♀️ . I thought of setting a higher `--minimum-length` for `cutadapt` and that might get rid of some of them. But I thought I would pick Felix's brain before proceeding with more trimming/filtering that might or might not work.

Best,
CS

**Comment by FelixKrueger** [comment]
Hi Chia,

I think there are a couple of things here, even though without more seeing the actual data it is mostly me guessing. I will just say a few things that come to my mind:
- non-directional RRBS data is typically very rare, are you sure it is? If you see `TGG/CGG` as the first three bases, followed by a low C-content the data is most likely directional. If you don't see this base composition, the data might not be RRBS... If you could attach a FastQC HTML report it might be more obvious
- Just generally, you seem to see ~80% of sequences aligning, and ~20% in the 'no hits' fraction. That isn't bad for the mouse genome (how long are your reads?)
-  you shouldn't need another round of trimming after the first one, because if you full length adapter dimers present in the library, they will simply not align
- `bismark -N 1 --non_directional`. I don't really want to suggest that your library definitely isn't non-directional, but we've seen in the past that sequencing facilities said libraries were non-directional, when it was simply untrue. If this were the case, a non-directional alignment mode might add spurious alignments, and/or lead to multiple alignments that might get discarded. A quick look at the base composition should sort this question (see above). Also, using `-N 1` might cause more sequences to align to different places. Maybe check in the default mode (`-N 0`) as well?
- Having sequences that align to multiple genomes isn't necessarily a bad thing. As soon as you enrich for sequences that are conserved across species (e.g. ribosomal, repeat, conserved genes etc) you would get you this phenomenon
- Having sequences that align to multiple sequences in multiple organisms sounds like you are enriching for some type of repetitive (somehwat conserved) repetitive element. There is a chance that this is inherent to the technique (MspI digestion?), so it could be something you just have to live with
- shorter reads will indeed result in a lot more ambiguous (multiple) alignments, and these are removed from the unique alignment output (coming back to how long were your reads?). Also, single-end alignments are more prone to suffer from short read issues. Using a minimum read length (by the way Trim Galore also has this option) would not really help you here, because removing short reads from the outset is en effect the same as short reads not aligning (uniquely), even though the % mappability might look a little better

Hope this gives you something to test?

**Comment by FelixKrueger** [comment]
Hi @DiegoZavallo,

regarding your issue. Hmmm. In my experience, spike-in controls are not always well behaved, and more often than not result in conversion estimates that are clearly worse than you see in your actual sample (I have mentined this here as well https://github.com/FelixKrueger/Bismark/blob/master/Docs/FAQ.md#bisulfite-conversion-rate---considerations).

In your case, with the chloroplast genome you've got something like a built in control in your experiment - which also shows a conversion efficiency of only 60-70%. This would indeed worry me more, as such a poor overall conversion efficiency would confound your results substantially. 

When you look at your previous data, do you see the chloroplast genome well below 2% or so methylated in all contexts?

**Comment by chiasinL** [comment]
Hi Felix,

Thank you for your insights and suggestions. 

> non-directional RRBS data is typically very rare, are you sure it is? If you see TGG/CGG as the first three bases, followed by a low C-content the data is most likely directional. If you don't see this base composition, the data might not be RRBS... If you could attach a FastQC HTML report it might be more obvious

I had this initial suspicion about the directionality of the data as well. But `bismark align` with directionality (the default mode) gave mapping efficiency of ~5%, while using `--non-directional` increased that to ~20%. Bismark report also shows that most reads align to `CTOT` and `CTOB`. I also checked for strandedness with `infer_experiment.py` from `rseqc` and got 50/50 of both directions. I am not sure about `TGG/CGG` as the first three bases - I remember checking when reading your documentation about QC on RRBS data but couldn't figure out where exactly to look.

The data set was indeed MspI digested and the length is 150bp. I am going to try aligning to `-N 0` and see if that improves the mapping rate.

If you don't mind, can you please take a look at this [data subset of two samples](https://drive.google.com/drive/folders/1cJM7TelEwiqZwd6djQjj98thH5L6-Ucw?usp=share_link) (untrimmed, 500K, gzipped)? 

Many thanks,
CS

**Comment by DiegoZavallo** [comment]
Hi Felix! 
Thanks for your insights.
First, let me tell you that i checked if my data was indeed non directional and (sadly) it is. Most of my reads starts with CGA, and Trim Galore trims the first 2 with non directional option. 

I followed your suggestion and ran my previous data against the chloroplast and I you were right! less than 1% in all contexts.

I also noticed that the mapping efficiency was higher than my current data. 18% old data; 5.5% new data. Could this mean anything you might think of?

Should i talk to my sequencing facility? Do you know anyone who has used Zymo-seq RRBS libraries? 
Is it time to migrate to Nanopore? (hehe)

```
Final Alignment report
======================
Sequences analysed in total:    3684378
Number of alignments with a unique best hit from the different alignments:      658320
Mapping efficiency:     17.9%

Sequences with no alignments under any condition:       2705382
Sequences did not map uniquely: 320676
Sequences which were discarded because genomic sequence could not be extracted: 0

Number of sequences with unique best (first) alignment came from the bowtie output:
CT/CT:  274120  ((converted) top strand)
CT/GA:  384200  ((converted) bottom strand)
GA/CT:  0       (complementary to (converted) top strand)
GA/GA:  0       (complementary to (converted) bottom strand)

Number of alignments to (merely theoretical) complementary strands being rejected in total:     0

Final Cytosine Methylation Report
=================================
Total number of C's analysed:   8484598

Total methylated C's in CpG context:    17752
Total methylated C's in CHG context:    4153
Total methylated C's in CHH context:    26957
Total methylated C's in Unknown context:        52

Total unmethylated C's in CpG context:  1699726
Total unmethylated C's in CHG context:  912760
Total unmethylated C's in CHH context:  5823250
Total unmethylated C's in Unknown context:      9687

C methylated in CpG context:    1.0%
C methylated in CHG context:    0.5%
C methylated in CHH context:    0.5%
C methylated in Unknown context (CN or CHN):    0.5%


Bismark completed in 0d 0h 2m 43s

====================
Bismark run complete
====================
```

**Comment by FelixKrueger** [comment]
@DiegoZavallo Your data is indeed non-directional, as you've pretty much got a 1:1:1:1 strand alignment ratio....

That new report seems to confirm that chloroplasts are not very methylated generally, and for some reason your old data contained more chloroplast DNA. Not exactly sure how that happened (maybe the samples were prepared in the summer when there were 5 more hours of sunlight per day? :P). I don't want to be the person putting the blame on a sequencing facility, but if the bisulfite conversion was sub-optimal, there probably is a reason for it....

Nanopore. Maybe? How about EM-seq with long reads and Nanopore? I heard the new PacBio is going to be fantastic, too...

**Comment by chiasinL** [comment]
> Thanks for sending the subsets - it's now official that this is a very weird data set (not sure I have ever seen something like it to be honest...).

I was laughing out loud at this comment. 😆  I have limited experience with bisulfite methyl-seq data because we don't get these very often but I never thought this data set is so "unique". 

Thank you for looking at the data. I will go back to the company and report back.

**Comment by chiasinL** [comment]
Hello Felix,

So we have heard back from the company and they told us that:

-  the libraries were constructed via PBAT and standard RRBS enzyme digestion cleavage.
-  the library prep kit used was EpiNext High-Sensitivity Bisulfite-Seq Kit (Illumina), with method and adapters similar to Illumina TruSeq.
- bioinformatically, the data is non-directional and can be ran with `--pbat` setting if the software supports it.

I am trying to figure out what PBAT-constructed RRBS data means. I have only seen PBAT used in Single Cell and often produces PE data. I am not sure what PBAT means in MspI-selected RRBS context. Do you know if mapping efficiency is usually low for data produced in this way?

> - by looking at the reads I see no enrichment at what could be CpG islands

Can you please explain how this was done? I want to produce data to show the company.

Many thanks,
Chia Sin

**Comment by FelixKrueger** [comment]
- I would personally probably say that the terms 'non-directional' and 'PBAT-style' are mutually exclusive, but using `--pbat` might be the way to go nevertheless.
- if the method is similar to Illumina TruSeq (which by the way produced directional libraries (i.e. non PBAT)), you might want to trim a fair amount off the 5' and 3' ends to see if this increases the mapping efficiency (maybe 10bp?)

I don't think I have come across a pull-down based RRBS experiment, but yes we have seen low mapping efficiencies in PBAT data before (see here: https://sequencing.qcfail.com/?s=pbat).

I have simply imported the mapped BAM files into SeqMonk to look at the genomic location of the alignments. For RRBS there typically is a very distinctive enrichment of reads at CpG islands, and/or promoter regions, which was simply not there for your data. SeqMonk is a dead useful piece of software, it is simply to use and comes with several training videos to get you started.

**Comment by chiasinL** [comment]
Thank you so much for your insights and suggestions. I think I managed to get things worked by trimming 10bp from 5' and 3' ends and running Bismark with `--pbat`. The resulting mapping rate for all samples is ~35-50%.

> I have simply imported the mapped BAM files into SeqMonk to look at the genomic location of the alignments. For RRBS there typically is a very distinctive enrichment of reads at CpG islands, and/or promoter regions, which was simply not there for your data. SeqMonk is a dead useful piece of software, it is simply to use and comes with several training videos to get you started.

![Screen Shot 2022-11-17 at 4 54 10 PM](https://user-images.githubusercontent.com/11150562/202834735-7b6e5645-67e9-4f88-a911-4dcab0f9e5fb.png)

Thank you for this. I did what you suggested and indeed, it seems like there's no enrichment at CpG islands.

The M-Bias plot looks like what is expected - I think, except the total methylation calls for CpG, CHG, CHH declined drastically (especially for CHH) from the start towards the end of the reads. Should I be worried about this?

![image](https://user-images.githubusercontent.com/11150562/202834885-cc9d4797-16e3-4c89-91a1-6ed7385e1456.png)

**Comment by FelixKrueger** [comment]
Apologies for the late reply. My guess would be that you see quite a number of reads that read into the adapter sequence (read through contamination, very common for BS-seq reads as the the bisulfite conversion produces short fragments), and these portions of the reads get trimmed off.

There should be several ways to confirm whether this is the case:
- the adapter contamination plot in FastQC should show this
- the trimmed sequences histogram in the Trim Galore report should show the trimming
- the read length histogram within SeqMonk should also show the fragments sizes - presumably drastically shorter than your read length of 130bp (keep in mind that you trimmed off 10bp from the 5' end already).

**Comment by chiasinL** [comment]
Hello Felix,

Sorry for the late reply. You're correct. There's quite a bit of read through adapter contamination, especially second half of the reads. Thank you so much for your help and insights. I am going to close this issue as solved.

Thank you for developing amazing tools and being super supportive.

To summarize the issue for others who might have similar issues: 
- the low mapping rates were due to the data not being standard RRBS data and therefore required a different trimming strategy than `--rrbs` in trim galore. 
- because a PBAT styled pull down was used in the library construction, `--pbat` in Bismark worked better than default setting and the final mapping rates were similar to what Felix described here:

> I don't think I have come across a pull-down based RRBS experiment, but yes we have seen low mapping efficiencies in PBAT data before (see here: https://sequencing.qcfail.com/?s=pbat).
