### ISSUE TITLE
merge *cov files

### ISSUE THREAD

**Issue by Adnanhashim** [FelixKrueger/Bismark#532]
Hello and thank you for a wonderful tool and being active on github to address issues:)

I intend to combine *cov files. I wish to combine 12 replicate *cov files into a single *cov file.
I searched previous posts and realised that you may have a script to accomplish this. could you please provide it? Thank you in advance.

**Comment by FelixKrueger** [comment]
Hi Adnan, 
Can you try out the attached script?
[merge_arbitrary_coverage_files.zip](https://github.com/FelixKrueger/Bismark/files/9939146/merge_arbitrary_coverage_files.zip)

**Comment by Adnanhashim** [comment]
Hi Felix,

Thanks a lot for prompt response :) it worked.

**Comment by FelixKrueger** [comment]
That's what we like to hear! Enjoy!
