### ISSUE TITLE
[Feature request]: Alternative nucleotide conversion

### ISSUE THREAD

**Issue by AngelCampos** [FelixKrueger/Bismark#543]
Hello Felix. 

I wonder if you plan to implement other alternatives to nucleotide conversion in `bismark_genome_preparation` other than the existing ones (default and --slam).
[Liu et al., 2022](https://www.nature.com/articles/s41587-022-01487-9) recently published a work which relies on the A->G (+) T->C (-) conversions to detect m6A in RNA.

It is possible that similar approaches appear to detect other nucleotides, it would be great if Bismark had the flexibility to manage any nucleotide_A to nucleotide_B in silicon conversion, alignment, and quantification.

Best

**Comment by FelixKrueger** [comment]
Hi Miguel,

The `--slam` implementation was kind of a easy case to experiment with as it more or less behaves like inverse bisulfite experiments. Allowing to use arbitrary nucleotides A and B sounds attractive,  but to be honest this would require a thorough rewrite of the entire code base, which frankly isn't on the agenda in the near future.
Have you looked at HISAT-3N? This might already offer the functionality you are after.

Thanks for reaching out!
