### ISSUE TITLE
Error running bismark_genome_preparation

### ISSUE THREAD

**Issue by chrismahony** [FelixKrueger/Bismark#546]
I am running:

`bismark_genome_preparation --path_to_aligner /my_path/bowtie2-2.5.0-mingw-x86_64/bowtie2-2.5.0-mingw-x86_64/ --verbose /my_path/RRBS/
`

And I get the following output just after step III launches:

bowtie2-build-s does not exist, try running `[g]make bowtie2-build-s'
Parent process: Failed to build index

Could you help?

Thanks
Chris

**Comment by FelixKrueger** [comment]
Hmm, not exactly sure what this is. Does Bowtie2 itself run fine? You could test this by moving into the `Bisulfite_Genome/CT_conversion/` folder, and then run something like:

`bowtie2-build --verbose genome_mfa.CT_conversion.fa BS_CT`

**Comment by chrismahony** [comment]
This works fine, I also run this for the GA and it runs fine.

I run:

module load Bowtie2/2.4.4-GCC-10.3.0
bowtie2-build --verbose genome_mfa.CT_conversion.fa BS_CT


Can I manually run the next steps of creating the genome in a similar way?

Thanks
Chris

**Comment by FelixKrueger** [comment]
Hi Chris,

Yes, you should be able to just execute this step once for the CT_conversion and once for the GA_conversion folders. I still don't quite understand where the error comes from. Maybe it is because of different versions of Bowtie2 you used for the Bismark and manual way?

**Comment by chrismahony** [comment]
OK great, how do I get bismark to start after this step?

Thanks
Chris
