### ISSUE TITLE
Directional or non-directional libraries

### ISSUE THREAD

**Issue by pasviber** [FelixKrueger/Bismark#547]
Hello,

I am working with plant WGBS libraries (PE150) that according to the company that performed the sequencing are non-directional. Previously, I tried to align with bismark in directional mode (default) and non-directional mode (--non_directional). The mapping results are as follows:

**Directional mode:**

Sequence pairs analysed in total:	42009779

Number of paired-end alignments with a unique best hit:	24329910
Mapping efficiency:	57.9% 
Sequence pairs with no alignments under any condition:	13000825
Sequence pairs did not map uniquely:	4679044
Sequence pairs which were discarded because genomic sequence could not be extracted:	0

Number of sequence pairs with unique best (first) alignment came from the bowtie output:
CT/GA/CT:	12196042	((converted) top strand)
GA/CT/CT:	0	(complementary to (converted) top strand)
GA/CT/GA:	0	(complementary to (converted) bottom strand)
CT/GA/GA:	12133868	((converted) bottom strand)

Number of alignments to (merely theoretical) complementary strands being rejected in total:	0

**Non-directional mode:**

Sequence pairs analysed in total:	42009779
Number of paired-end alignments with a unique best hit:	24331145
Mapping efficiency:	57.9% 
Sequence pairs with no alignments under any condition:	12996787
Sequence pairs did not map uniquely:	4681847
Sequence pairs which were discarded because genomic sequence could not be extracted:	0

Number of sequence pairs with unique best (first) alignment came from the bowtie output:
CT/GA/CT:	12190217	((converted) top strand)
GA/CT/CT:	6213	(complementary to (converted) top strand)
GA/CT/GA:	6704	(complementary to (converted) bottom strand)
CT/GA/GA:	12128011	((converted) bottom strand)

In both modes, most reads map onto the OT and OB strands. Normally if they are non-directional we would get a 1:1:1:1:1 ratio (OT:OB:CTOT:CTOB), right? So, should I use the directional mode (default) since it is less computationally exhaustive or as I know they are non-directional should I use the non-directional mode?

On the other hand, the mapping efficiency is the same in both modes although I find it low, is the mapping efficiency usually about 60%? I tried with another library and the results were very similar. 31% of sequence pairs not aligning is a high percentage.

Thanks in advance

**Comment by FelixKrueger** [comment]
Hi @pasviber 

The libraries are certainly directional, and I would therefore recommend running it in default mode; furthermore you should tell the company that they should stop saying they are non-directional.

If the data was non-directional, you would certainly expect a mapping efficiency of < 50% in directional mode (as you would only see half of the alignments....).

Regarding the mapping efficiency, I suggest you read the following FAQ article on paired-end mapping efficiencies: http://felixkrueger.github.io/Bismark/faq/low_mapping/

Also, regarding trimming modes it is worth checking out the recommendations for different library types/kits: http://felixkrueger.github.io/Bismark/bismark/library_types/

Happy to assist if you have any further questions.

**Comment by pasviber** [comment]
Hello again,

Thank you very much for the reply. I already told the sequencing company about the problem. I have done several tests to improve the mapping efficiency and I would like your opinion if you don't mind. To do the tests I selected one of the libraries and reduced it to approximately 4M reads.

1- First, I tried to compare the mapping efficiency by removing 10 bases from the 5' ends (case 1) and removing 10 bases from the 5' and 3' ends (case 2). Then it went from 60% (case 1) to 60.3% (case 2) of mapping efficiency so the improvement was minimal and also the number of C's processed decreased. I understand that trimming the 3' end affects more the reliability of methylation extraction by eliminating low quality bases than the mapping efficiency.

2- Second, I tested aligning in single end mode to determine if the mapping efficiency varied much between both R1 and R2 libraries. The mapping efficiency results were 66.7% for R1 and 64.5% for R2. Therefore, I ruled out any bias in the results caused by misalignment of R1 or R2.

3- Third, returning to paired end mode, I simply changed from `--score_min L,0,-0.2` (default) to `--score_min L,0,-0.6` obtaining a mapping efficiency of 60% and 72%, respectively.

4- Fourth, I tried changing the default end-to-end alignment to local alignment with the `--local` parameter obtaining a mapping efficiency of 60% and 78.9%, respectively.

In tests 2, 3, 4 I always worked with the default parameters except for the parameters I indicated that I modified and always starting from clean adapter sequences and trimmed only the 5' end with Trimgalore.

Considering these results, to what extent can I improve the mapping efficiency and therefore the coverage as well without reducing the reliability of the methylation extraction? I have to say that the genome I work with is cucumis melo which is not poorly annotated but also not as well annotated as arabidopsis thaliana or as human or mouse.

Best regards 

Pascual

**Comment by FelixKrueger** [comment]
regarding 1): in a standard Trim Galore run, bases with a base call quality < 20 are removed by default, which means only bases with a predicted error rate of <1% make it through. Removing 10 additional bases from the end therefore has only a marginal effect. Removing bases from the start is not normally performed, but if your library preparation protocol introduces some biases at the start, this may have a drastic effect on the mapping efficiency. In you case it seems to have a moderate effect, it might be interesting to know which library prep kit you used, and what the M-bias plots look like - in other words: as trimming 10bp off from the 5' end really warranted?

regarding 2): Having lower mapping efficiencies with R2 are not uncommon, but it doesn't look particularly pronounced in your case. Which is good!

regarding 3): tolerating more errors and/or deletions seems to increase the mapping. Keep in mind that allowing too many errors may end up generating spurious alignments - but this is a judgement call

regarding 4): that is the 'beauty' of local alignments - it will just result in pretty high alignment rates in general (keep in mind that you have >10% of unplacable ambiguous alignments as well, so this gets you close to the 100% mark (which is frankly somewhat unrealistic).

Finding the *right* parameters to go ahead is tricky, and there isn't really a right or wrong call. If the C. melo genome isn't super polished just yet I would agree that relaxing the stringency may be the way to go (score min to -0.4 or -0.6?). You could even go down the `local` route, but you should be aware that this may in some cases trim large stretches of your reads and then place the remainder somewhere - sometimes these regions can be a little dubious... You should be especially aware of the fact that the Accel Swift kit (http://felixkrueger.github.io/Bismark/bismark/library_types/#swift) in conjunction with local alignment might really introduce a lot of errors (as R2 in these libraries often starts with 10-15bp of GGGGGG (which would appear methylated). It's your call really - good luck!
