### ISSUE TITLE
Bismark mapping issue

### ISSUE THREAD

**Issue by ccmeth** [FelixKrueger/Bismark#549]
Hi Developers,

Thanks a lot for providing such a useful tool. When I used the bismark code, I met with a very strange issue that did not appear before. I have three WGBS samples with paired-end sequencing. The size of each R1.fastq.gz is about 30G. I ssh the server three times to process the three samples simultaneously. However, the processes all ended abnormally after about ~60 million sequences were processed. Then I tried to check the generated bam files, however, when I entered the directory harboring the fastq and bam files, "ls" does not give any response and "ctrl+c" does not kill it. Could you please tell me how to fix such an issue?

##
Bismark version: 0.23.1
bismark --genome /data/REF/hg19 -1 xxx_R1.fastq.gz -2 xxx_R2.fastq.gz
##

**Comment by FelixKrueger** [comment]
Hi @ccmeth 

I am afraid I would need some more details regarding your procedure, especially the error message you are seeing. What exactly are you doing, which type of libraries do you have, what are the system resources on the machine you `ssh` into, did you perform trimming of the files beforehand etc. It might also be worth starting with a smaller sample to see if that completes well. To select say the first 1 million reads, you can do:

```bash
gunzip -c xxx_R1.fastq.gz | head -4000000 | gzip -c - >xxx_1M_R1.fastq.gz
gunzip -c xxx_R2.fastq.gz | head -4000000 | gzip -c - >xxx_1M_R2.fastq.gz
```

(again, ideally you should trim the reads first, e.g. with [Trim Galore](https://github.com/FelixKrueger/TrimGalore)).
