### ISSUE TITLE
bismark_methylation_extractor

### ISSUE THREAD

**Issue by yy549159265** [FelixKrueger/Bismark#550]
I'm a newbie ，doing bismark_methylation_extractor, why does the cov file have zero lines

bismark_methylation_extractor -p \
                              --parallel 16 \
                              --bedGraph --counts \
                              --cytosine_report --report\
                              --CX \
                              --comprehensive \
                              --buffer_size 10G \
                              $i \
                              --genome_folder /home/yuanshuai20/DP/Transcribe/process/gene_index/ina \
                              -o /home/yuanshuai20/DP/Transcribe/process/result/

reference genome file Ensembl
Oryza_indica.ASM465v1.dna.toplevel.fa

**Comment by yy549159265** [comment]
(dp) [yuanshuai20@ZH404 bismark]$ samtools view SRR10498878_1_bismark_bt2_pe.bam | head -4
[W::bam_hdr_read] EOF marker is absent. The input is probably truncated
SRR10498878.8_8_length=150      99      4       26375785        42      30M     =       26375942        207     TTTATTAATTTATTAAAATTTTGAAATATT  FKKKKKKKKKKKKKK<KKKKKKKKKFFKKK  NM:i:8  MD:Z:0C1C1C0C4C8C0C7C1  XM:Z:h.h.hh....h........hx.......h.     XR:Z:CT XG:Z:CT
SRR10498878.8_8_length=150      147     4       26375942        42      50M     =       26375785        -207    TATGATTTTAATTTATTTGATAAGAATTTAAAAGATTAGATATTTTGTAT      FKAKKFKKFKKKKKAFFKFKKKKFAAAAFKKKKKKFKA7FKKAFFF7KAK      NM:i:11 MD:Z:0C5C4C0C0C3C2C14C7C0C4C0   XM:Z:h.....h....hhh...z..h..............h.......hx....h  XR:Z:GA XG:Z:CT
SRR10498878.10_10_length=150    83      9       16116016        42      69M     =       16115872        -213    TTCTATCTTTAACCATTTCTTTTATACAAATATAATTATTCAACAATTACTCAAATTTTTCAACATTTC   FFAKKFKAAAKKKKFKFKKKFFKAKFKKKF<,KKKKKFFKKKFKFKAKAKKKKFKKKKKKKKKKKKKKK   NM:i:11 MD:Z:4G6G13G2G2G5G7G2G4G0G7G6    XM:Z:....x......h.............h..x..h.....h.......x..h....xh.......x......      XR:Z:CT XG:Z:GA
SRR10498878.10_10_length=150    163     9       16115872        42      56M     =       16116016        213     TTAAACCATTTAAATTCAAACTTAATTCAATAACCATATCTTTCTATAAATTAAAA        KFKKKK7FKKFKKKKKKFKKKKKKKKKFFFKKKKA<KKKKKKKKFKKKKFFKKKKK        NM:i:3  MD:Z:12G16G24G1 XM:Z:............h................x........................h.    XR:Z:GA XG:Z:GA

This is the bam file I generated

**Comment by FelixKrueger** [comment]
A couple of things:

- I suppose you did run the Bismark genome preparation first, then ran a trimming step, e.g. with Trim Galore (https://github.com/FelixKrueger/TrimGalore), followed by Bismark alignments - and all completed fine?

- When you say the coverage file has `zero lines`, can you go back through the logs to see if something failed, and why it failed? Did the methylation extraction run to completion? Did you get any error messages that the rice genome has thousands of small-ish scaffolds and contigs? I would probably suggest you re-run the bedGraph step using the option `--scaffolds`).

In your previous post I also saw: `[W::bam_hdr_read] EOF marker is absent. The input is probably truncated`: such an error certainly also has the potential to crash the whole process....

**Comment by yy549159265** [comment]
Dear author, I found the relevant answers in the history question. I decided to try your answer before

**Comment by yy549159265** [comment]
> A couple of things:
> 
> * I suppose you did run the Bismark genome preparation first, then ran a trimming step, e.g. with Trim Galore (https://github.com/FelixKrueger/TrimGalore), followed by Bismark alignments - and all completed fine?
> * When you say the coverage file has `zero lines`, can you go back through the logs to see if something failed, and why it failed? Did the methylation extraction run to completion? Did you get any error messages that the rice genome has thousands of small-ish scaffolds and contigs? I would probably suggest you re-run the bedGraph step using the option `--scaffolds`).
> 
> In your previous post I also saw: `[W::bam_hdr_read] EOF marker is absent. The input is probably truncated`: such an error certainly also has the potential to crash the whole process....

Thank you very much for your reply. Dear author, I found the relevant answers in the history question. I decided to try your answer before。
Use fastqc for quality control, fastp for filtering, bismark for genome comparison, and deduplicate_ Bismark de duplication

**Comment by yy549159265** [comment]
> A couple of things:
> 
> * I suppose you did run the Bismark genome preparation first, then ran a trimming step, e.g. with Trim Galore (https://github.com/FelixKrueger/TrimGalore), followed by Bismark alignments - and all completed fine?
> * When you say the coverage file has `zero lines`, can you go back through the logs to see if something failed, and why it failed? Did the methylation extraction run to completion? Did you get any error messages that the rice genome has thousands of small-ish scaffolds and contigs? I would probably suggest you re-run the bedGraph step using the option `--scaffolds`).
> 
> In your previous post I also saw: `[W::bam_hdr_read] EOF marker is absent. The input is probably truncated`: such an error certainly also has the potential to crash the whole process....

Attempt to use the command to successfully output the cov file，Thank you very much
bismark2bedGraph --CX -o test.cov -scaffolds CpG_context_SRR10498878_1_bismark_bt2_pe.deduplicated.txt

**Comment by yy549159265** [comment]
> A couple of things:
> 
> * I suppose you did run the Bismark genome preparation first, then ran a trimming step, e.g. with Trim Galore (https://github.com/FelixKrueger/TrimGalore), followed by Bismark alignments - and all completed fine?
> * When you say the coverage file has `zero lines`, can you go back through the logs to see if something failed, and why it failed? Did the methylation extraction run to completion? Did you get any error messages that the rice genome has thousands of small-ish scaffolds and contigs? I would probably suggest you re-run the bedGraph step using the option `--scaffolds`).
> 
> In your previous post I also saw: `[W::bam_hdr_read] EOF marker is absent. The input is probably truncated`: such an error certainly also has the potential to crash the whole process....

Hello, dear author, the names of chromosomes in the first column of the cov file are all 1.Is this correct?
`(dp) [yuanshuai20@ZH404 result]$ cat SRR10498882.cov.gz.bismark.cov | head -100
1       698     698     100     1       0
1       702     702     100     1       0
1       705     705     100     1       0
1       725     725     100     2       0
1       735     735     100     2       0
1       745     745     100     3       0
1       748     748     100     3       0
1       770     770     66.6666666666667        2       1
1       783     783     100     1       0
1       784     784     100     3       0
1       789     789     50      1       1
1       790     790     100     3       0
1       800     800     50      1       1
1       801     801     100     3       0
1       811     811     100     2       0
1       812     812     100     3       0
1       815     815     100     2       0
1       816     816     66.6666666666667        2       1
1       829     829     100     2       0
1       830     830     100     3       0
1       960     960     100     1       0
1       978     978     100     1       0
1       986     986     100     1       0
1       991     991     100     1       0
1       1001    1001    100     1       0
1       1062    1062    100     2       0
1       1079    1079    100     2       0
1       1097    1097    100     3       0
1       1106    1106    100     3       0
1       1112    1112    100     2       0
1       1127    1127    100     3       0
1       1132    1132    100     3       0
1       1157    1157    100     3       0
1       1162    1162    100     3       0
1       1164    1164    100     3       0
1       1191    1191    100     3       0
1       1226    1226    100     3       0
1       1245    1245    100     3       0
1       2491    2491    100     1       0
1       2494    2494    100     1       0
1       2501    2501    0       0       1
1       2518    2518    0       0       1
1       2521    2521    100     1       0
1       2533    2533    100     1       0
1       2559    2559    100     1       0
1       2563    2563    100     1       0
1       2566    2566    100     1       0
1       2576    2576    100     1       0
1       2581    2581    100     1       0
1       2583    2583    100     1       0
1       2591    2591    100     1       0
1       2594    2594    100     1       0
1       2597    2597    100     1       0
1       2604    2604    100     1       0
1       2608    2608    100     2       0
1       2645    2645    100     2       0
1       2655    2655    100     2       0
1       2666    2666    100     2       0
1       2669    2669    100     2       0
1       2696    2696    100     2       0
1       2711    2711    50      1       1
1       2718    2718    100     2       0
1       2731    2731    0       0       1
1       2736    2736    0       0       1
1       2748    2748    100     1       0
1       2750    2750    100     1       0
1       2752    2752    100     1       0
1       2757    2757    100     1       0
1       2762    2762    100     1       0
1       2765    2765    0       0       1
1       2772    2772    0       0       1
1       2777    2777    100     1       0
1       2783    2783    100     1       0
1       2796    2796    100     1       0
1       2816    2816    100     1       0
1       2819    2819    100     1       0
1       2823    2823    100     1       0
1       2841    2841    100     1       0
1       2846    2846    100     1       0
1       3162    3162    100     1       0
1       3168    3168    100     1       0
1       3178    3178    100     1       0
1       3185    3185    100     1       0
1       3193    3193    100     1       0
1       3208    3208    100     1       0
1       3222    3222    100     1       0
1       3231    3231    100     1       0
1       3233    3233    100     1       0
1       3236    3236    100     1       0
1       3244    3244    100     1       0
1       3296    3296    100     1       0
1       3298    3298    0       0       1
1       3321    3321    100     1       0
1       3328    3328    100     1       0
1       3335    3335    100     1       0
1       3343    3343    100     1       0
1       3360    3360    100     1       0
1       3391    3391    100     1       0
1       5261    5261    100     2       0
1       5267    5267    100     2       0
`

**Comment by yy549159265** [comment]
> A couple of things:
> 
> * I suppose you did run the Bismark genome preparation first, then ran a trimming step, e.g. with Trim Galore (https://github.com/FelixKrueger/TrimGalore), followed by Bismark alignments - and all completed fine?
> * When you say the coverage file has `zero lines`, can you go back through the logs to see if something failed, and why it failed? Did the methylation extraction run to completion? Did you get any error messages that the rice genome has thousands of small-ish scaffolds and contigs? I would probably suggest you re-run the bedGraph step using the option `--scaffolds`).
> 
> In your previous post I also saw: `[W::bam_hdr_read] EOF marker is absent. The input is probably truncated`: such an error certainly also has the potential to crash the whole process....

``(dp) [yuanshuai20@ZH404 result]$ cat SRR10498882.cov.gz.bismark.cov | head -100
1       698     698     100     1       0
1       702     702     100     1       0
1       705     705     100     1       0
1       725     725     100     2       0
1       735     735     100     2       0
1       745     745     100     3       0
1       748     748     100     3       0
1       770     770     66.6666666666667        2       1
1       783     783     100     1       0
1       784     784     100     3       0
1       789     789     50      1       1
1       790     790     100     3       0
1       800     800     50      1       1
1       801     801     100     3       0
1       811     811     100     2       0
1       812     812     100     3       0
1       815     815     100     2       0
1       816     816     66.6666666666667        2       1
1       829     829     100     2       0
1       830     830     100     3       0
1       960     960     100     1       0
1       978     978     100     1       0
1       986     986     100     1       0
1       991     991     100     1       0
1       1001    1001    100     1       0
1       1062    1062    100     2       0
1       1079    1079    100     2       0
1       1097    1097    100     3       0
1       1106    1106    100     3       0
1       1112    1112    100     2       0
1       1127    1127    100     3       0
1       1132    1132    100     3       0
1       1157    1157    100     3       0
1       1162    1162    100     3       0
1       1164    1164    100     3       0
1       1191    1191    100     3       0
1       1226    1226    100     3       0
1       1245    1245    100     3       0
1       2491    2491    100     1       0
1       2494    2494    100     1       0
1       2501    2501    0       0       1
1       2518    2518    0       0       1
1       2521    2521    100     1       0
1       2533    2533    100     1       0
1       2559    2559    100     1       0
1       2563    2563    100     1       0
1       2566    2566    100     1       0
1       2576    2576    100     1       0
1       2581    2581    100     1       0
1       2583    2583    100     1       0
1       2591    2591    100     1       0
1       2594    2594    100     1       0
1       2597    2597    100     1       0
1       2604    2604    100     1       0
1       2608    2608    100     2       0
1       2645    2645    100     2       0
1       2655    2655    100     2       0
1       2666    2666    100     2       0
1       2669    2669    100     2       0
1       2696    2696    100     2       0
1       2711    2711    50      1       1
1       2718    2718    100     2       0
1       2731    2731    0       0       1
1       2736    2736    0       0       1
1       2748    2748    100     1       0
1       2750    2750    100     1       0
1       2752    2752    100     1       0
1       2757    2757    100     1       0
1       2762    2762    100     1       0
1       2765    2765    0       0       1
1       2772    2772    0       0       1
1       2777    2777    100     1       0
1       2783    2783    100     1       0
1       2796    2796    100     1       0
1       2816    2816    100     1       0
1       2819    2819    100     1       0
1       2823    2823    100     1       0
1       2841    2841    100     1       0
1       2846    2846    100     1       0
1       3162    3162    100     1       0
1       3168    3168    100     1       0
1       3178    3178    100     1       0
1       3185    3185    100     1       0
1       3193    3193    100     1       0
1       3208    3208    100     1       0
1       3222    3222    100     1       0
1       3231    3231    100     1       0
1       3233    3233    100     1       0
1       3236    3236    100     1       0
1       3244    3244    100     1       0
1       3296    3296    100     1       0
1       3298    3298    0       0       1
1       3321    3321    100     1       0
1       3328    3328    100     1       0
1       3335    3335    100     1       0
1       3343    3343    100     1       0
1       3360    3360    100     1       0
1       3391    3391    100     1       0
1       5261    5261    100     2       0
1       5267    5267    100     2       0
``

**Comment by yy549159265** [comment]
> A couple of things:
> 
> * I suppose you did run the Bismark genome preparation first, then ran a trimming step, e.g. with Trim Galore (https://github.com/FelixKrueger/TrimGalore), followed by Bismark alignments - and all completed fine?
> * When you say the coverage file has `zero lines`, can you go back through the logs to see if something failed, and why it failed? Did the methylation extraction run to completion? Did you get any error messages that the rice genome has thousands of small-ish scaffolds and contigs? I would probably suggest you re-run the bedGraph step using the option `--scaffolds`).
> 
> In your previous post I also saw: `[W::bam_hdr_read] EOF marker is absent. The input is probably truncated`: such an error certainly also has the potential to crash the whole process....


Hello, the name of the first chromosome in the cov file is 1. Does this affect the subsequent differential expression analysis
![image](https://user-images.githubusercontent.com/40821310/203990843-0de4ad2d-cd61-4da0-9fb5-cabe6f5e7146.png)

**Comment by FelixKrueger** [comment]
erm, no? The all of the chromosomes are in the file.

**Comment by yy549159265** [comment]
> erm, no? The all of the chromosomes are in the file.

Thank you very much for your help！This tool will be better and better
