### ISSUE TITLE
bismark_genome_preparation runs on a single thread regardless of --parallel flag

### ISSUE THREAD

**Issue by onurcanbektas** [FelixKrueger/Bismark#551]
I run it as
`bismark_genome_preparation --path_to_aligner <path to bowtie2> --bowtie2 --verbose <genome folder> --large-index --parallel 4`

on a Macbook Pro with 10 cores. However, it runs over a single thread. I also run with different numbers of cores, but it always runs over a single thread.
![Screenshot 2022-12-06 at 20 02 15](https://user-images.githubusercontent.com/18240112/205999101-582f3932-1c3e-42f6-873c-eb5d9b33b603.png)

How can I parallelise `bismark_genome_preparation`?

**Comment by FelixKrueger** [comment]
The only process that runs in single-core mode is the initial C>T transposition (which typically finished within a minute or so). The `--parallel 4` will be passed on to the index build processes, so if you wait a little bit longer you should see the CPU usage increase to 800%.
