### ISSUE TITLE
Minor size differences in output bam file

### ISSUE THREAD

**Issue by chasingdex** [FelixKrueger/Bismark#552]
Hi @FelixKrueger I have three bam outputs generated with identical parameters and identical versions of Bismark and bowtie2 using a set of paired end trimmed inputs.
Three parallel parameters were used- 8, 12 and 16.
The total no. of reads aligned to the genome according to their respective alignment reports  are the same.

However, the bam files have a size difference. See below.
**What could cause these size differences?**

- Parallel thread;   Bam size
- 16;   86370183058
- 12;   86250282377
- 8;    86111223110

**Comment by FelixKrueger** [comment]
This. is probably a question better directed towards some compression afficionados -  data simply compresses slightly different depending on how you do it, or in your case - which reads come first. I have seen size differences of nearly 2-fold with (read name) sorted BAM files for the same information content...
