### ISSUE TITLE
Documentation error for EM-seq mapping flags on github.io page

### ISSUE THREAD

**Issue by alexcpan** [FelixKrueger/Bismark#554]
Hi @FelixKrueger, I found a discrepancy in the documentation [here](http://felixkrueger.github.io/Bismark/bismark/library_types/) stating that the EM-seq libs should be mapped as non-directional.

This is at odds with the [main docs page](https://github.com/FelixKrueger/Bismark/tree/master/Docs#ix-notes-about-different-library-types-and-commercial-kits), which suggests they should be mapped w/ default settings (i.e. that EM-seq libs are directional)
Documentation from NEB also states that the kit is directional (https://www.neb.com/faqs/2019/03/12/are-em-seq-libraries-directional-or-non-directional).

Thanks and happy new year!

**Comment by FelixKrueger** [comment]
Well spotted, that was indeed an oversight. I have now removed the non directional flag from the table. Happy New Year!
