### ISSUE TITLE
Mapping coverage/bedmark results to cpg ids

### ISSUE THREAD

**Issue by gherrgo** [FelixKrueger/Bismark#557]
Hi all,

First, thanks so much for this amazing package. It has done a fantastic job on my newly generated WGBS data and helped immensely.
I have a quick question regarding downstream analyses from Bismark results...
Following the methylation calling, are you aware of any packages or guidances provided on how to map these genomic coordinates to actual CpG IDs such as those used in an EPIC array? My ultimate goal is to correlate WGBS methylation %'s to EPIC array beta values obtained across the same sample, however I am having issues overlapping the genomic coordinates between Bismark results and an hg38 CpG manifest, for example.

Any guidance you may provide would be extremely helpful and appreciated. @FelixKrueger 
Thanks!

Grayson

**Comment by FelixKrueger** [comment]
If your 10 samples are different biological samples, this needs to be run separately.

If your 10 samples are technical replicates of the same sample, they should be merged. This can either happen before the coverage file creation (e.g. you could feed all CpG* files from the different replicate samples to `bismark2bedGraph` (e.g. `bismark2bedGraph -o all_merged.cov.gz --gzip CpG*` (aassuming that all the CpG* files from the methylation extractor are in that folder), or you could also merge coverage files separately, and then feed them to `coverage2cytosine`. The outcome should be identical.

**Comment by gherrgo** [comment]
Great, thanks so much Felix!
________________________________
