### ISSUE TITLE
Can I use Bismark to identify the BS-seq method(WGBS or RRBS)?

### ISSUE THREAD

**Issue by PanZiwei** [FelixKrueger/Bismark#558]
Hi,
Thanks for the amazing tool. I am trying to use the Bismark to reanalyze a public BS-seq dataset, but it didn't mention the method is WGBS or RRBS. I had the original fastq file and also the final So is there a way to identify the BS-seq method with the help of Bismark (e.g. conversion rate? Deduplication percentage?) If so, how? 

If the original analysis includes deduplicating steps, can I assume that the data should be WGBS since deduplication is not recommended for RRBS?

The analysis pipeline is attached below:
```
# Trimming of the adaptors specific to SWIFT ACCELL-NGS METHYL-SEQ
#  - trim 15 bases from the end of R1 (3’ end)
#  - 15 bases from the beginning of R2 (5’ end)
#  - run fastqc again
trim_galore --three_prime_clip_R1 15 --clip_R2 15 --fastqc --paired --retain_unpaired ${reads1} ${reads2} -o trim_galore

# Alignment with Bismark:
bismark --multicore 20 -q ${reference} -1 trim_galore/*_R1_val_1.fq.gz -2 trim_galore/*_R2_val_2.fq.gz -o bismark

# Deduplication:
deduplicate_bismark -p --bam --output_dir bismark/ -o ${id} bismark/*_R1_val_1_bismark_bt2_pe.bam

# Methylation extraction:
bismark_methylation_extractor --multicore 20 -p --gzip bismark/${id}.deduplicated.bam -o bismark

# Bismark to bedgraph per CpG context:
bismark2bedGraph --CX --buffer_size 20G --zero_based --dir cpg -o CpG bismark/CpG_OT_${id}.deduplicated.txt.gz bismark/CpG_OB_${id}.deduplicated.txt.gz
#bismark2bedGraph --CX --buffer_size 20G -o CHH <CHH_OT_.deduplicated.txt.gz> <CHH_OB_"$ID".deduplicated.txt.gz>
#bismark2bedGraph --CX --buffer_size 20G -o CHG <CHG_OT_.deduplicated.txt.gz> <CHG_OB_"$ID".deduplicated.txt.gz>
```

**Comment by FelixKrueger** [comment]
If the data is Swift Accell Methyl-seq, the data should be whole-genome data. The quickest way to check this would be to import the BAM file into a genome browser (e.g. SeqMonk), and look at the position of the files. Genome-wide data should have a fairly even coverage across the whole genome, RRBS will most likely start (and end) at predefined enzyme cut sites, so you should see bi piles of reads at the very same position, and then have fairly large gaps to the next mapping location.

**Comment by PanZiwei** [comment]
Thank you so much for your response! Really beneficial! I will load the BAM file into the genome browser to get an idea about the pattern.
