### ISSUE TITLE
Suggest to make "Chromosomal sequence could not be extracted" a warning, not an error. 

### ISSUE THREAD

**Issue by mobilegenome** [FelixKrueger/Bismark#559]
Hi,

sorry re-raise an issue for the this error message that was already answered multiple times, for example in #94 or #303.

I also ran into it and have already concluded that it's due to short unplaced contigs in our genome. Also, I have read your suggestions to wrap these contigs into `NN`s to alleviate the error.  However, I am hesitant to do this manual modification to a reference genome just for this. Also, it would alter genomic coordinates for the modified contigs making comparisons with other sequencing types difficult. All in all, this solution appears a bit "hacky". 

For me, the actual issue is that this errors triggers a non-zero exit code, which breaks the whole analysis pipeline. (In my case nf-core's methylseq). 

Would it be possible to treat this errors as warnings and quit Bismark after processing with a successful exit-code? As it seems, this is a frequent error that can be accepted if the overall alignment and sequence context extractions are okay. 
What do you think about this? 

Possibly, I could also do modification to the code myself (or at least make suggestions), but couldn't locate the lines that trigger the error. 

Best wishes

Fritjof

**Comment by FelixKrueger** [comment]
Hi Fritjof, 

Sorry I seem to have missed this suggestion entirely!

And I completely agree, these warnings are intended as warnings only anyway, and should not cause the pipeline to exit with a non zero exit code. I have just tried to add an explicit statement to exit with code 0 if it reaches the end (ef10a57930e345986681364baea0c832c412ded8), do you think this would do the trick?

**Comment by FelixKrueger** [comment]
I will just close this for now, and hope the proposed changes address this issue. I've also got an interest in getting this right, as we are also heavily using the methylseq pipeline these days...

**Comment by mobilegenome** [comment]
Looks good as far as I can tell. I will try it when I run the pipeline again.
