### ISSUE TITLE
Ambiguous alignments wrongly considered unique

### ISSUE THREAD

**Issue by jsh58** [FelixKrueger/Bismark#56]
Compared with v0.15.0, the latest version of Bismark (v0.16.1) is giving far fewer reads (~10%) that "did not map uniquely".  That is, reads that were previously discarded for having ambiguous alignments are now labeled unique and given in the output BAM file.  This may be related to the fix "Bismark: Changed the behaviour of corner cases..." from v0.16.0.  

All of the new alignments are to the top strand (CT/CT) and have equivalent alignments to the other strand (CT/GA), but not the same position (or even the same chromosome).

Thanks,

John Gaspar
john.gaspar@rutgers.edu

One example:
// C_to_T converted read
@NS500532:74:HMLCNBGXX:1:11101:16159:1424_1:N:0:AAACATCG
GTTTTATATTGAATTTTGAGGAAGATTGTAGATAGTTTTGATTTTGTTAGAATTTTTTGTGATGTTAATAGTTAAA
+
AAAAAEEEEEEEEEEAEEAEEEEE6EEEEEEEAEEEEEEEEEEEEEEEEEEEEEEEEEEEEA/EEAEE<EEEEEEE

// aligned with Bismark to mm9:

v0.15.0 alignment: ambiguous, not given

v0.16.1 alignment: NS500532:74:HMLCNBGXX:1:11101:16159:1424_1:N:0:AAACATCG	0	chr5	2414222442	76M	*	0	0	GTTTTATATTGAATTTTGAGGAAGATTGTAGATAGTTTTGATTTTGTTAGAATTTTTTGTGACGTTAATAGTTAAA	AAAAAEEEEEEEEEEAEEAEEEEE6EEEEEEEAEEEEEEEEEEEEEEEEEEEEEEEEEEEEA/EEAEE<EEEEEEE	NM:i:19	MD:Z:1C0C0C0C1C1C6C9C2C3C2C0C0C3C0C3C7C1C14C4	XM:Z:.hhhh.h.x......x.........x..x...x..hhx...hh...h.......h.x.....Z........h....	XR:Z:CT	XG:Z:CT

// individual alignments with Bowtie2 confirm two equivalent alignments (AS=0):

// individual alignment with Bowtie2, CT converted:
NS500532:74:HMLCNBGXX:1:11101:16159:1424_1:N:0:AAACATCG	0	chr5_CT_converted	2414222442	76M	*	0	0	GTTTTATATTGAATTTTGAGGAAGATTGTAGATAGTTTTGATTTTGTTAGAATTTTTTGTGATGTTAATAGTTAAA	AAAAAEEEEEEEEEEAEEAEEEEE6EEEEEEEAEEEEEEEEEEEEEEEEEEEEEEEEEEEEA/EEAEE<EEEEEEE	AS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:76	YT:Z:UU

// individual alignment with Bowtie2, GA converted:
NS500532:74:HMLCNBGXX:1:11101:16159:1424_1:N:0:AAACATCG	16	chr19_GA_converted	3239183042	76M	*	0	0	TTTAACTATTAACATCACAAAAAATTCTAACAAAATCAAAACTATCTACAATCTTCCTCAAAATTCAATATAAAAC	EEEEEEE<EEAEE/AEEEEEEEEEEEEEEEEEEEEEEEEEEEEAEEEEEEE6EEEEEAEEAEEEEEEEEEEAAAAA	AS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:76	YT:Z:UU

**Comment by FelixKrueger** [comment]
Hi John,
thanks for your message, I will look into this as soon as I find the time. Best, Felix

**Comment by FelixKrueger** [comment]
I have now looked into this and you were absolutely right, something had crept in during the latest 'adjustment' of corner cases! I have now replaced greater than (>) with greater or equals (>=) which appears to do the job fine again, just like it was with version 0.15.0. (addressed in a831ce73c22ef5b60fdc8f3f58b462417ddb59a2)

I have also made a new release v0.16.2 (https://github.com/FelixKrueger/Bismark/releases) that fixes this bug and also adds a few more convenience features. Please let me know if you still encounter any odd situations with the new version.

Thanks again for spotting this, Best wishes, Felix
