### ISSUE TITLE
Context-specific bedGraphs

### ISSUE THREAD

**Issue by pna059** [FelixKrueger/Bismark#562]
Hi, 
I am trying to figure out how to generate three context-specific bedGraphs (which will allow easy plotting an visualization).
Is this possible to output directly from Bismark? Currently, I only have the one bedGraph and I think about subsetting somehow using chromosome and positions from the context-specific .txt files with awk.
Thank you~
Pavla

**Comment by FelixKrueger** [comment]
Hi Pavla,

You could achieve this by running the methylation extractor, and then running `bismark2bedGraph` separately for each context. Something like this should work:

```
bismark2bedGraph --gzip --buffer 10G -o CpG_context.cov.gz CpG*
bismark2bedGraph --CX --gzip --buffer 10G -o CHG_context.cov.gz CHG*
bismark2bedGraph --CX --gzip --buffer 10G -o CHH_context.cov.gz CHH*
```

**Comment by pna059** [comment]
Thank you, that`s exactly what I needed.
