### ISSUE TITLE
extracting all unmapped reads with a mate that mapped

### ISSUE THREAD

**Issue by olmath** [FelixKrueger/Bismark#563]
Hi Felix

I would be interested in extracting all unmapped reads with a mate that mapped from the output bam file of Bismark.

I have tried  'samtools view -b -f 4 -F 8’ but this gives an empty output.  

Would you have any advice on how to go about getting these reads?

Many thanks

**Comment by FelixKrueger** [comment]
I suppose you could run the alignments while specifying `--unmapped`, and then re-run the unmapped files in single-end mode (default directional for R1, `--pbat` for R2), and then work with those outputs?

**Comment by olmath** [comment]
I'll give it a try. 
Thanks for your suggestions
