### ISSUE TITLE
Bismark CX report files

### ISSUE THREAD

**Issue by hidvegin** [FelixKrueger/Bismark#567]
I made already the methylation extraction from `BAM` files with `methylation_extractor`. I get `CpG_context.deduplicated.txt.gz`, `CHG_context.deduplicated.txt.gz` and `CHH_context.deduplicated.txt.gz` files. I would like to make some downstream analysis with `DMRcaller` R package [https://bioconductor.org/packages/release/bioc/html/DMRcaller.html](url). This program wold like to get CX report files from `Bismark`. Are there the CX report files which I get from `Bismark` below or something else? How can I generate CX report files from `Bismark`?

**Comment by FelixKrueger** [comment]
You can either get this from the methylation extractor directly, using the options `-- bedGraph` and `--cytosine_report`, see here: http://felixkrueger.github.io/Bismark/options/methylation_extraction/#bedgraph-specific-options

Or, if you have already run the methylation on its own you can run `bismark2bedGraph` using the C* output files of the methylation extractor as the input to generate a  coverage file, and then run `coverage2cytosine` on the coverage file to generate the cytosine report. If you really want this for non-CG context, make sure to specify `--CX` (but this will all take quite a bit longer)

**Comment by hidvegin** [comment]
Thank @FelixKrueger for you quick answer. I will try the second solution because I have got already the output files of the methylation extractor.

**Comment by hidvegin** [comment]
I have an other problem with `bismark_methylation_extractor`. I tried use this command: `bismark_methylation_extractor -p '/NVMe1/novogene/UD_IM_WGBS/align/P2/P2_FKDN220493968-1A_H3JFGDSX5_L1_1_val_1_bismark_bt2_pe.multiple.deduplicated.bam' --comprehensive -o '/NVMe1/novogene/UD_IM_WGBS/methylation_extractor/P2' --multicore 10 --gzip --bedGraph --CX --buffer_size 40G --cytosine_report --CX --genome_folder '/NVMe1/novogene/reference_bismark/paradicsom'`. But I have got too many chromosomes and scaffold in the reference fasta file (3148) and I got this error messages: ```
Now writing methylation information for file >>CpG_context_P1_FKDN220493967-1A_H3JFGDSX5_L1_1_val_1_bismark_bt2_pe.multiple.deduplicated.txt.gz<< to individual files for each chromosome
Failed to open filehandle: Too many open files at /home/gulyas/Programok/Bismark-0.24.0/bismark2bedGraph line 279, <IN> line 676486.
Finished BedGraph conversion ...
```

Somehow can I increase the maxumim open files number on ubuntu?

**Comment by FelixKrueger** [comment]
The solution should be to simply specify `--scaffolds/--gazillion`. The description for this can be found by specifying `bismark_methylation_extractor --help`:

```
--scaffolds/--gazillion  Users working with unfinished genomes sporting tens or even hundreds of thousands of
                         scaffolds/contigs/chromosomes frequently encountered errors with pre-sorting reads to
                         individual chromosome files. These errors were caused by the operating system's limit
                         of the number of filehandle that can be written to at any one time (typically 1024; to
                         find out this limit on Linux, type: ulimit -a).
                         To bypass the limitation of open filehandles, the option --scaffolds does not pre-sort
                         methylation calls into individual chromosome files. Instead, all input files are
                         temporarily merged into a single file (unless there is only a single file), and this
                         file will then be sorted by both chromosome AND position using the Unix sort command.
                         Please be aware that this option might take a looooong time to complete, depending on
                         the size of the input files, and the memory you allocate to this process (see --buffer_size).
                         Nevertheless, it seems to be working.
```

**Comment by hidvegin** [comment]
Thank you @FelixKrueger for your answer. It helped a lot.
