### ISSUE TITLE
Mis-alignment in OB file?

### ISSUE THREAD

**Issue by rickyleungyk** [FelixKrueger/Bismark#568]
Thanks for developing this useful tool. I like it very much. 
I just used Bismark to align my targeted bisulfite-sequencing data (paired-end), 8 regions within 5 genes. I used the following parameters to do the alignment. 
bismark -q --non_directional --bowtie2 --un --ambiguous -o bismark_output --multicore 32 --genome ~/genome/mouse fastafiles.  
It worked fine for the alignment and creating .cov files. Then, I used BiSeq R package to determine differential methylation among samples. It was fine as well. 
The problems arose when I want to visualize the methylation data using the lollipop diagram. FYI, I used trackViewer R package for plotting the data. I found one or two genes/regions showed more CpG sites than what I expect. For example, I only expect to sequence 7x CpG sites in one region but the lollipop figure showed 11x CpG sites. I examined the data from one sample and then went back to all four  *_bismark_bt2_pe.txt files (OT, CTOB, CTOT and OB) generated by bismark. I found out all the genomic locations in the OB file were shifted by 1 base. For example, while all the other three files correctly determine the CpG site was in 21905745, the one from OB file showed the site was in 21905746. So, when I combine all samples to plot the lollipop diagram, it showed extra CpG sites within the same region. 
Did I do anything wrong with the alignment parameters? Do you have any suggestions on how to fix it? Thanks in advance

**Comment by FelixKrueger** [comment]
Hi there,

a) I am a little surprised that your alignments seem to have worked fine, as you used --multicore 32! A quick back of the envelope calculation would suggest that this requires roughly 500GB of RAM, and 150 cores of compute for the whole mouse genome! Or are you just using a small subset of genes as reference sequence? If you think you may have exceeded your compute resources, I would probably start by simply dropping the --multicore parameter, or using something like 2-4...

b) Bismark reports alignments to both the top and bottom strands. So if you sequence a CpG from both strands, you may cover the C on the top strand, as well as the C on the bottom strand - which is naturally shifted by exactly 1 bp. The `coverage2cytosine` module that comes with Bismark has the option to merge CpG dinucleotides (or dyads), if you are interested?

Let me know if you got any further questions.

**Comment by rickyleungyk** [comment]
Thanks for your quick reply. 
I used a whole mouse genome for alignment. I only have 192Gb RAM and 104 cores in my workstation but it seems to work fine. Anyway, I will re-run the analysis with your suggested parameters. Also, I will try the coverage2cytosine option too. Thanks.

**Comment by rickyleungyk** [comment]
I did what you suggested. It works. All the coordinates are fine now. Thank you very much

**Comment by FelixKrueger** [comment]
Excellent!
