### ISSUE TITLE
bismark_methylation_extraction: gzip: stdout: Broken pipe 

### ISSUE THREAD

**Issue by asulit08** [FelixKrueger/Bismark#570]
Hi,

I've only just noticed that running the bismark_methylation_extraction displays a gzip:stdout:Broken pipe error in some parts but I do get the CpG, CHH, and CHG context files in OB,OT, CTOT, and CTOB directions as well as an M-bias txt file and a splitting report. I indicated `--bedgraph` as well so I was also able to get a bedGraph.gz and a bismark.cov.gz file. I also get a 

samtools view: writing to standard output failed: Broken pipe
samtools view: error closing standard output: -1

at the end of some log files. 

The code I used is the following:

`bismark_methylation_extractor --gzip --bedGraph -p --no_overlap -o ./ sample1.bam > sample1.log 2>&1`

I wouldn't have even noticed these errors (as I've gotten the results files) if I hadn't been exploring the log files. I'm not sure what these mean and if I can trust the output of the results. I could point out that I am automating this in a python script that calls for the bismark comman using os.system(). 

Thanks. Any advice would be appreciated

**Comment by FelixKrueger** [comment]
Hmm, that is a good question. Pipes are always difficult to debug, and it isn't the first time that such warnings/errors show up (I recall there was a similar issue with Trim Galore recently caused by a snakemake pipeline, but the underlying command seemed to have completed successfully).

I would probably suggest to run the same command outside of the Python script to see if the contents look the same in the first instane...

**Comment by asulit08** [comment]
Thanks, I will do so and get back to you

**Comment by asulit08** [comment]
Update: 

I have ran the same command outside of the script on two different samples. I do not get the broken pipe/gzip error with these. I compared md5sums of the results files generated from within the Python script (with broken pipe/gzip error) and from outside (without broken pipe/gzip error) and I am getting the same md5sums for all results files  (12 context files,  bedGraph.gz, bismark.cov.gz, M-bias.txt, splitting_report.txt). 

Would you say it will be fine to continue with the results from within the Python script as it seems they don't differ? I'm running bismark on multiple samples and would rather automate it. I can make a snakemake run, if it's really necessary but I found the python script simpler if it's just bismark that I am running.

Thanks

**Comment by FelixKrueger** [comment]
Sorry I missed this.
If the output looks and feels the same (as assessed by the md5sum) I would probably just go ahead and use them. Doing some sanity checks (e.g. mapping efficiency etc) certainly won't help.

**Comment by asulit08** [comment]
thank you
