### ISSUE TITLE
DRAGEN bam outputs to bismark_methylation_extractor

### ISSUE THREAD

**Issue by imdanique** [FelixKrueger/Bismark#571]
Hello, 

Thank you for developing Bismark, it is very useful!

We have output files from Illumina DRAGEN: R1 and R2 fastqs, and bam files.

I've been running`bismark` with fastqs and then `bismark_methylation_extractor`, but because `bismark` is a rate-limiting step, I thought it would be better to use DRAGEN bam and run `bismark_methylation_extractor` straight away.

There is a [page](https://support.illumina.com/content/dam/illumina-support/help/Illumina_DRAGEN_Bio_IT_Platform_v3_7_1000000141465/Content/SW/Informatics/Dragen/MPipelineBisMeth_fDG.htm) on Illumina website that says that bam can be used to extract methylation with Bismark. However, when I tried to use DRAGEN bam as input for `bismark_methylation_extractor`:

```bash
bismark_methylation_extractor --parallel 2 --comprehensive --output sample_name --merge_non_CpG --bedGraph --gzip  dragen.bam
```

It throws this error: `Single-end or paired-end reads not specified properly`. 

I've checked BAM tags, but couldn't identify what's missing. Do you have any idea how to fix it?

**Comment by FelixKrueger** [comment]
I don't exactly know how the Dragen implementation of Bismark works exactly, but if your data is paired-end (R1 + R2), you simply need to add the option `-p` (or `--paired`) to your command. Just in case Dragen also carries out sorting by coordinates, you might have to sort the file by name again, but let's cross this bridge only if we have to. Best, Felix

**Comment by imdanique** [comment]
@FelixKrueger 

Thank you! Enabling `-p` indeed helped. It's strange that I used `bismark_methylation_extractor` with `bismark` output without this option and it was fine.

Now I have been running this command as you suggested, and it still fails, but with another error:

`bismark_methylation_extractor -p --output "out_dir" "sample.sorted.bam"` 

```bash
 Use of uninitialized value $first_read_conversion in string eq at /csc/epitkane/home/dkarabay/.conda/envs/cfdna2/bin/bismark_methylation_extractor line 1917, <IN> line 3375.
Use of uninitialized value $first_read_conversion in string eq at /csc/epitkane/home/dkarabay/.conda/envs/cfdna2/bin/bismark_methylation_extractor line 1920, <IN> line 3375.
Use of uninitialized value $first_read_conversion in string eq at /csc/epitkane/home/dkarabay/.conda/envs/cfdna2/bin/bismark_methylation_extractor line 1923, <IN> line 3375.
Use of uninitialized value $first_read_conversion in string eq at /csc/epitkane/home/dkarabay/.conda/envs/cfdna2/bin/bismark_methylation_extractor line 1926, <IN> line 3375.
Use of uninitialized value $first_read_conversion in concatenation (.) or string at /csc/epitkane/home/dkarabay/.conda/envs/cfdna2/bin/bismark_methylation_extractor line 1930, <IN> line 3375.
Use of uninitialized value $genome_conversion in concatenation (.) or string at /csc/epitkane/home/dkarabay/.conda/envs/cfdna2/bin/bismark_methylation_extractor line 1930, <IN> line 3375.
Unexpected combination of read and genome conversion:  /
Now testing Bismark result file >/csc/epitkane/projects/cfdna/dragen/GR02017/GR02017.sorted.bam< for positional sorting (which would be bad...) srun: error: a5: task 0: Exited with exit code 29```

**Comment by imdanique** [comment]
@FelixKrueger 

Below are the first three entries from BAM

```
A00464:566:HWH7YDSX3:3:1352:3504:2832   97      chr1    9985    6       38M5D113M       chr7_KI270899v1_alt     6887    0       TTTTAATTTTAATTTTTAATTTTAATTTTAATTTTAATTTTTAATTTTAATTTTAATTTTAACGTTAATGTTAACGTTAATTTTAATTTTAATTTTAATTTTAATTTTAATTTTAATTTAATTTTAATTTTAATTTTAATTTTAATTTTAA FFFF:FFFFFF,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF,:FFFF:FFFFFFF,FFFFFFFFFFFFFFFFF::FFFFFFFFFFFFFF,:FFF:FF:FFFFFFFF::FFFFFFFFFFF,FF:FFF RG:Z:BHWH7YDSX3-3-121   AS:i:-23        XS:i:-26        NM:i:86 sd:f:0.125      MD:Z:0N0N0N0N0N0N0N0N0N0N0N0N0N0N0N0N3C0C0C3C0C0C3C0C0C3C0^CCTAA0C0C0C3C0C0C3C0C0C3C0C0C4C0C3C0C0C4C0C3C0C0C3C0C0C3C0C0C3C0C0C3C0C0C3C0C0C3C0C0C2C0C0C3C0C0C3C0C0C3C0C0C3C0C0C3
A00464:566:HWH7YDSX3:3:1120:21504:10113 83      chr1    9985    0       104M    =       9985    -104    CCCAAAACCATAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAAC        FFF:FF,,:FFFFF,FFFFFFFFFFFFFFFFF:FF:F:FFFFF:F:FFFFFFFFF:FFFFFFF:FFFFFFFFF:F:FFF:FFFFFF::FFFFFFFF,FFFFFF:        RG:Z:BHWH7YDSX3-3-121   AS:i:0  XS:i:-8 NM:i:16 sd:f:0.153      MD:Z:0N0N0N0N0N0N0N0N0N0N0N0N0N0N0N0N88
A00464:566:HWH7YDSX3:3:1323:15239:30608 89      chr1    9985    0       1M1I123M1I25M   =       9985    0       CCCCACACCCTCATCCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTA F,,:,FFF,FF:,FFFFF,F,FF:F::F,F:F,:FFFF:FFF:F:F::FF:F:FF:FF:F::FF,FFFFFF:FF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFF,F RG:Z:BHWH7YDSX3-3-121   AS:i:-14        XS:i:-20        NM:i:18 sd:f:0.106      MD:Z:0N0N0N0N0N0N0N0N0N0N0N0N0N0N0N0N133
A00464:566:HWH7YDSX3:3:1609:32958:16235 89      chr1    9985    0       1M5I123M1I21M   =       9985    0       AATTAAAATTAAAATTAAAATTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCNAAC FF:FFFFFFFFFFF:FFFFFFFFFF,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF#FFF RG:Z:BHWH7YDSX3-3-121   AS:i:-18        XS:i:-27        NM:i:23 sd:f:0.117      MD:Z:0N0N0N0N0N0N0N0N0N0N0N0N0N0N0N0N125T3
```

**Comment by FelixKrueger** [comment]
That's interesting. Whoever made, sorted or otherwise interfered with this BAM file - it is not in the format that Bismark outputs, and is no longer usable by downstream Bismark tools such as the methylation extractor. More specifically, as the error message from above already pointed out, the BAM file no longer contains the optional fields for the read and genome conversions which are required for the methylation extraction.

As a fix you need to get hold of the original BAM file produced by Bismark, everything should work well then.

PS: Since your reads are mostly concatenated telomeric hexamer repeats `(CCCTAA)n`, I am wondering whether these reads were maybe not generated by Bismark in the first place? In my experience, telomeric repeats are very unlikely to align uniquely in the genome, so they are very often not included in the output of uniquely mappable reads... Is this a possibility?

**Comment by FelixKrueger** [comment]
Closing this as I haven't heard back in a while
