### ISSUE TITLE
 hisat2-align died with signal 13 (PIPE) 

### ISSUE THREAD

**Issue by robertama95** [FelixKrueger/Bismark#572]
Hello, 

first of all, thank you for the great tool you have created. 
I have been having few issues with the final step of the alignment. 

**This is the code I have used:** 

 % bismark --genome /Volumes/MEMORY/Methylation/ --hisat2 -1 /Volumes/MEMORY/Methylation/R1.fastq -2 /Volumes/MEMORY/Methylation/R2.fastq -o /Volumes/MEMORY/Methylation

**This is the error I get:** 

Input files are R1.fastq_C_to_T.fastq and R2.fastq_G_to_A.fastq (FastQ)
Now running 2 instances of HISAT2 against the bisulfite genome of /Volumes/MEMORY/Methylation/ with the specified options: -q --score-min L,0,-0.2 --ignore-quals --no-mixed --no-discordant --maxins 500 --no-softclip --omit-sec-seq

Now starting a HISAT2 paired-end alignment for CTread1GAread2CTgenome (reading in sequences from R1.fastq_C_to_T.fastq and R2.fastq_G_to_A.fastq, with the options: -q --score-min L,0,-0.2 --ignore-quals --no-mixed --no-discordant --maxins 500 --no-softclip --omit-sec-seq --norc))
Found first alignment:
A00119:865:H255LDSX7:4:1101:2166:1047_1:N:0:CGTATCTC+GTACCTTG/1	77	*	0	0	*	*	0	0	TGTGAATTATATTTTAGGTATGTAAAGAATGTTTTTGTTGTTGTTAGTGGTAATATGTGGATTAATTATTAGTTATAATAATATTTTTTATTTTTTAGGTATTGATTTAATAATTTGATAGTTTTTTTTTTATTTTGGTAATGATTTTAT	FFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFF,FFFFFFF	YT:Z:UP
A00119:865:H255LDSX7:4:1101:2166:1047_2:N:0:CGTATCTC+GTACCTTG/2	141	*	0	0	*	*	0	0	ACCTAACTAACATCAATATTTAAAAAAAAAACCAAATATTAAACCATTATTTTATATTATTTCATATCATTAATATTTTACTATTTAACAATAAAACATTTTTAACAAAAAATCTAAATACTCTAAAATTTCATCTATATCAATTTATAT	FFFFFFFFF,FFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFF:FFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF,FFFFFFF:F:FF:FF:FFFF::F::FFFF,FFFFFFFFFF:F:FFFFFFFFFFF	YT:Z:UP
Now starting a HISAT2 paired-end alignment for CTread1GAread2GAgenome (reading in sequences from R1.fastq_C_to_T.fastq and R2.fastq_G_to_A.fastq, with the options: -q --score-min L,0,-0.2 --ignore-quals --no-mixed --no-discordant --maxins 500 --no-softclip --omit-sec-seq --nofw))
Found first alignment:
A00119:865:H255LDSX7:4:1101:2166:1047_1:N:0:CGTATCTC+GTACCTTG/1	83	NC_066835.1_GA_converted	4908628	60	150M	=	4908317	-461	ATAAAATCATTACCAAAATAAAAAAAAAACTATCAAATTATTAAATCAATACCTAAAAAATAAAAAATATTATTATAACTAATAATTAATCCACATATTACCACTAACAACAACAAAAACATTCTTTACATACCTAAAATATAATTCACA	FFFFFFF,FFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFF	AS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:150	YS:i:0	YT:Z:CP	NH:i:1
A00119:865:H255LDSX7:4:1101:2166:1047_2:N:0:CGTATCTC+GTACCTTG/2	163	NC_066835.1_GA_converted	4908317	60	150M	=	4908628	461	ACCTAACTAACATCAATATTTAAAAAAAAAACCAAATATTAAACCATTATTTTATATTATTTCATATCATTAATATTTTACTATTTAACAATAAAACATTTTTAACAAAAAATCTAAATACTCTAAAATTTCATCTATATCAATTTATAT	FFFFFFFFF,FFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFF:FFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF,FFFFFFF:F:FF:FF:FFFF::F::FFFF,FFFFFFFFFF:F:FFFFFFFFFFF	AS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:150	YS:i:0	YT:Z:CP	NH:i:1

>>> Writing bisulfite mapping results to R1_bismark_hisat2_pe.bam <<<

sh: line 1: 59577 Abort trap: 6           /Users/robymarcoli/opt/anaconda3/envs/Bismark/bin/samtools view -bSh - 2> /dev/null > /Volumes/MEMORY/Methylation/R1_bismark_hisat2_pe.bam
(Bismark) robymarcoli@Robertas-MacBook-Pro Methylation % (ERR): hisat2-align died with signal 13 (PIPE) 
(ERR): hisat2-align died with signal 13 (PIPE) 

**These are the steps I tried:** 

- [ ]  I have tried to change the max_memory, but I get error (memory comand not found)

 --genome /Volumes/MEMORY/Methylation/ --bowtie2 --max_memory 1800G -1 /Volumes/MEMORY/Methylation/R1.fastq -2 /Volumes/MEMORY/Methylation/R2.fastq
Unknown option: max_memory

- [ ] I have tried to use bowtie2 - I get the same error as per hisat 2
- [ ] I have tried to add --multicore 4 and --multicore 2 (in two different codes and runs) and I get the same PIPE 13 error. 

Any chance you could give me a hand with this? 
Thanks in advance! :)

**Comment by FelixKrueger** [comment]
Two things that I would check: 
1) which version of Samtools are you running, can you update it?
2) How much memory does your machine have? It looks like you are running this on a MacBook, which genome is it? A typical human or mouse run will take at least 12GB of RAM....

**Comment by robertama95** [comment]
Hello Felix,

Thank you for your response. I have updated the samtools and I now
have the samtools
1.13.

I am working with the barramundi genome, on a 16GB Mac. I am getting access
to the HPC, but I wanted to have a first trial.

I have tried to re-run the code, after updating the samtools, and I am
getting this error: sh: line 1: 68533 Abort trap: 6
/Users/robymarcoli/opt/anaconda3/envs/Bismark/bin/samtools
view -bSh - 2> /dev/null > R1_bismark_bt2_pe.bam

(Bismark) ***@***.*** Methylation % (ERR):
bowtie2-align died with signal 13 (PIPE)

(ERR): bowtie2-align died with signal 13 (PIPE)



Any other suggestions? thank you again

Cheers

Roby

**Comment by FelixKrueger** [comment]
Hmm, the error message `sh: line 1: 68533 Abort trap: 6` really has nothing to do with Bismark itself I am afraid. When googling I found several issues around C++, Shift, Homebrew and Xopen, e.g. here: https://github.com/dmurdoch/rgl/issues/45

I'm really not sure what to suggest, but I guess you will have to test individual programs involved and systematically update them one by one, e.g. conda, samtools, bowtie2, homebrew? etc...
