### ISSUE TITLE
Bismark alignment output is empty?

### ISSUE THREAD

**Issue by edceeyuchen** [FelixKrueger/Bismark#573]
I used trimgalore to clean the WGBS data , and the pipeline was compeleted, the script as follows:
${trim_galore} -output_dir ${cleandata} --fastqc --gzip -j 4 --paired --length 20 --stringency 3 --quality 20 ${fqdir}/${id}_1.fq.gz ${fqdir}/${id}_2.fq.gz
And than I do bismark alignment, here is my script:
/share/apps/softwares/Bismark-0.23.1/bismark --bam \
  --bowtie2 --path_to_bowtie2 /share/apps/softwares/bowtie2-2.4.5-linux-x86_64 \
  --genome_folder ~/genome/bismark_database/references/Homo_sapiens/UCSC/hg38/Sequence/BismarkIndex/ \
  --temp_dir $tmpdir \
  -o ${outdir} \
  -B ${id} \
  -1 ${cleandata}/${id}_1_val_1.fq.gz \
  -2 ${cleandata}/${id}_2_val_2.fq.gz
However, the log shows: there is no header from *_pe.bam, and the *_pe.bam and *_PE_report.txt are empty!
What's wrong about my script? 
Hope for help! Thank you

**Comment by FelixKrueger** [comment]
what does the log show? Does the process start alright? Does it find first alignments? Does it run out memory or the like?

**Comment by edceeyuchen** [comment]
@FelixKrueger  Thank you for your reply! 
And I increased running memory, now it works normally!

**Comment by FelixKrueger** [comment]
Yay! thanks for the update
