### ISSUE TITLE
Bismark_methylation_extractor interupts too early by sudden BASH termination

### ISSUE THREAD

**Issue by bveyb** [FelixKrueger/Bismark#574]
Dear Felix,

I try to extract all methylation calls from barley using

bismark_methylation_extractor /results/bismark-deduplicate/118_S17_R1.bam  -
-bedGraph 
--CX 
--cytosine_report --parallel 3 
--buffer_size 150G 
--genome_folder /home/shared/reference_genome/ 
--split_by_chromosome

the first steps of the algorithms seem to work well,
but after writing the CX_report file of the first chromosome
my BASH does disappear.

Does a solution exist to obtain all CX_reports?

The BAM file is 17,2GB and the barley genome V2 FA file is 4,4GB.

Thank you for help,
Olaf.
(plant physiologist with rookie skills in bioinformatics)

**Comment by FelixKrueger** [comment]
OK, I have never heard of that before.... your command is essentially 3 commands running sequentially:

1. the methylation extraction itself (which end in CpG, CHH and CHG files)
2. the bedGraph/coverage file generation (which generates a `.cov.gz` file)
3. the cytosine report generation, starting from the .cov.gz file)

Did you get the desired output from steps 1 and  2?

You can re-run step 2 on its own using `bismark2bedGraph`, or re-run step 3 using `coverage2cytosine`. This might narrow down what is happening....

**Comment by bveyb** [comment]
Thank you very much for the fast reply.
1. the methylation extraction itself (which end in CpG, CHH and CHG files)
-> is running well. I obtain all context_OT/OB_118_S17_R1.txt files, the 118_S17R1.M-bias_R1/R2.png files
    and if running --comprehensive the three     CpG/CHH/CHG_context_118_S17_R1.txt files, too.

2. the bedGraph/coverage file generation (which generates a .cov.gz file)
-> is also running well. I obtain 118_S17_R1.bismark.cov.gz and 118_S17_R1.bedGraph.gz

3. the cytosine report generation, starting from the .cov.gz file)
-> stop's after writing the 118_S17_R1.CX_report.txt.chrchr1H.CX_report.txt file (6,7GB),
    the 118_S17_R1.CX_report.txt.chrchr1H.cytosine_context_summary.txt is empty 
    and my BASH does disappear.

Now I will try to run step 3 using `coverage2cytosine`.

Thank you much, for your help.
Olaf

**Comment by FelixKrueger** [comment]
Looking at your command, and log file I see the following:

`-o /118_S17_R1.CX_report.txt`

This would attempt to write log  straight into your top level root folder `/`. Is this intended, and would you have permission to write there at all? I would probaby just drop the `/` and use `-o 118_S17_R1.CX_report.txt`

**Input file:**
` /118_S17_R1.bismark.cov.gz`
Same here: is this file really located in your system's root folder? `./` would be the current folder, or if you are in the folder with the input file, ` 118_S17_R1.bismark.cov.gz` will suffice.

Ah, and here is the error message:

```
gzip: /118_S17_R1.bismark.cov.gz: No such file or directory
No last chromosome was defined, something must have gone wrong while reading the data in (e.g. specified wrong file path for a gzipped coverage file?). Please check your command!
```

If I had to guess, I would think that writing to the root folder causes this, so let's see what happens if you change the input command.

**Comment by bveyb** [comment]
I followed you suggestions and used

overage2cytosine 
--CX 
--genome_folder /home/shared/reference_genome/ 
--split_by_chromosome 
-o 118_S17_R1.CX_report.txt 
118_S17_R1.bismark.cov.gz

a few minutes after writing 6,7GB
into the 118_S17_R1.CX_report.txt.chrchr1H.CX_report.txt file
the 118_S17_R1.CX_report.txt.chrchr1H.cytosine_context_summary.txt remains empty
and my BASH did disappear again.
???

(the error message, you mention, was due to a wrong PATH to the file)

**Comment by FelixKrueger** [comment]
This is very weird indeed.... Could you try to drop the `--split_by_chromosome` and see if that's to blame?

**Comment by bveyb** [comment]
I tried
coverage2cytosine 
--CX 
--genome_folder /home/shared/reference_genome/ 
-o 118_S17_R1.CX_report.txt 
118_S17_R1.bismark.cov.gz

([118_S17_R1.log](https://github.com/FelixKrueger/Bismark/files/11158322/118_S17_R1.log))

a few minutes after writing 6,7GB
into the 118_S17_R1.CX_report.txt
which only contains chr1H
the 118_S17_R1.cytosine_context_summary.txt remains empty
and my BASH did disappear again.

**Comment by bveyb** [comment]
My system runs with 62.6G available RAM and it provides a SWAP of 514G.
During the 'coverage2cytosine' task the whole RAM is used and, if I run without the --CX option
around 36G of the SWAP (not much less, than with the --CX option with around 50G).
I followed your suggestion and tried

coverage2cytosine 
--genome_folder /home/shared/reference_genome/ 
-o 118_S17_R1.CX_report.txt 
118_S17_R1.bismark.cov.gz

a few minutes after writing 1,1GB
into the 118_S17_R1.CX_report.txt.CpG_report.txt
which contains all CpG marks only of chr1H
the 118_S17_R1.CX_report.txt.cytosine_context_summary.txt remains empty
and my BASH did disappear again.

**Comment by FelixKrueger** [comment]
This is super weird indeed. I am pretty sure that it somehow has to do with the system you are running it on, and it not only seems to kill the application, but the entire shell together with it... Do you have a chance to run this task on a different, beefy enough machine?

**Comment by bveyb** [comment]
Finished writing out cytosine report for covered chromosomes (processed 8 chromosomes/scaffolds in total)

Now processing chromosomes that were not covered by any methylation calls in the coverage file...
All chromosomes in the genome were covered by at least some reads. coverage2cytosine processing complete.

Look's well, doesn't it.
Thank you very much for your help.
I did run 'coverage2cytosine' on the cluster of our IT Service Center,
using one node with one task and 250GB RAM.
It seems, the problem does occur, when the SWAP is used.
Maybe this produces errors, which the algorithm is not able to tolerate.
My system runs on a 2TB SSD, I'm not sure, but maybe there are too
much errors if a SSD is used as pseudo RAM?
Is it possible to implement a procedure, by which a RAM overflow of
'coverage2cytosine' is prevented?

Thank you and all the best,
Olaf.

**Comment by bveyb** [comment]
Dear Felix,

again, thank you much for your help.

I followed your suggestion and set
the '/proc/sys/vm/overcommit_memory' variable to 1 and
the '/proc/sys/vm/swappiness' varaible to 1, too,
to prevent the OOM Killer, but the problem still remains and
my BASH terminal does disappear after writing the CX-report
for the first chromosome.

All the best to you,
yours sincerely 
Olaf.
