### ISSUE TITLE
bismark_methylation_extractor error

### ISSUE THREAD

**Issue by JaZwy** [FelixKrueger/Bismark#577]
Dear Felix,
bismark_methylation_extractor, a step after deduplication, is still going into this error (below). I have tried different version of samtools, unsorted/sorted deduplicated bam files, then I make new deduplication and run the extractor and still the same error. I have the same script for 9 samples and for the rest 8 samples was going ok. This sample is the biggest one (78 Gb when deduplicated). Do you have any idea what could help? Thank you!

samtools view: error closing standard output: -1
Processed lines: 196000000
[FATAL ERROR:] The IDs of Read 1 (A00703:139:HNK5CDSX2:1:1101:21052:1000_1:N:0:GACCTGAA+CTCACCAA) and Read 2 (A00703:139:HNK5CDSX2:1:1101:26838:1000_1:N:0:GACCTGAA+CTCACCAA) are not the same. This might be the result of sorting the BAM files by chromosomal position or merging several files with Samtools sort, and this is not compatible with correct methylation extraction. Please use an unsorted file instead or sort the file by name using the command 'samtools sort -n'. Paired-end files may be merged properly (without risking this error) using either 'samtools merge -n' or 'samtools cat'.

samtools view: writing to standard output failed: Broken pipe
samtools view: error closing standard output: -1
samtools view: writing to standard output failed: Broken pipe
samtools view: error closing standard output: -1

**Comment by FelixKrueger** [comment]
Hi there, 

Given that the process failed 196 million sequences is would argue that there is an issue with the file merging. May I ask how this was done? It is known that certain methods of merging (e.g. with `samtools merge` alone) do not guarantee that Read 1 and Read 2 follow each other in the BAM file. See also the comment above:

> Paired-end files may be merged properly (without risking this error) using either 'samtools merge -n' or 'samtools cat'.

It might also be worth mentioning that the files produced by Bismark should *always* work with both `deduplicate_bismark` and the methylation extractor without any further step required (sorting, resorting, merging, etc). Wouldn't that be a option?

**Comment by JaZwy** [comment]
Hello Felix,
I am using Bismark from the beginning, so all steps are done with Bismark only. That is why I am surprised, because Bismark is running well for other samples. I didn't merge the files by myself, so I didn't use any samtools command separately. I started to play around with the samtools sorting when I got this error.

**Comment by FelixKrueger** [comment]
Hmm, if that is the case is there a chance that the Bismark run did not finish properly for this one sample? Could you go back to the log of that run, and see if it ran to completion or if there were any errors? Could you try to identify the lines around where the process goes wrong with e.g. something like:

```
samtools view mapped_file_pe.bam | grep -B 10 -A 10 A00703:139:HNK5CDSX2:1:1101:21052:1000_1:N:0:GACCTGAA
```
 
This might show whether or not there are weird things going on (this command will probably take a few minutes to run)

**Comment by JaZwy** [comment]
Dear Felix,
it is solved. It was a repeated mistake on a server. Anyway, it runs well on a different machine. So you were right, that was not a case of Bismark :) Thank you!

**Comment by FelixKrueger** [comment]
Excellent, great it is working for you now!
