### ISSUE TITLE
report file and CX_report file give different results

### ISSUE THREAD

**Issue by H1889** [FelixKrueger/Bismark#578]
Hi. I have a question that is probably a silly one.

In a bismarck *bismark_bt2_PE_report.txt file I have obtained:
Final Alignment report
======================
Sequence pairs analysed in total:	20834280
Number of paired-end alignments with a unique best hit:	12271418
Mapping efficiency:	58.9% 
Sequence pairs with no alignments under any condition:	4965388
Sequence pairs did not map uniquely:	3597474
Sequence pairs which were discarded because genomic sequence could not be extracted:	142

Number of sequence pairs with unique best (first) alignment came from the bowtie output:
CT/GA/CT:	6340517	((converted) top strand)
GA/CT/CT:	0	(complementary to (converted) top strand)
GA/CT/GA:	0	(complementary to (converted) bottom strand)
CT/GA/GA:	5930759	((converted) bottom strand)

Number of alignments to (merely theoretical) complementary strands being rejected in total:	0

Final Cytosine Methylation Report
=================================
Total number of C's analysed:	549613956

Total methylated C's in CpG context:	2078402
Total methylated C's in CHG context:	578780
Total methylated C's in CHH context:	4113332
Total methylated C's in Unknown context:	7

Total unmethylated C's in CpG context:	64398808
Total unmethylated C's in CHG context:	89020082
Total unmethylated C's in CHH context:	389424552
Total unmethylated C's in Unknown context:	267

C methylated in CpG context:	3.1%
C methylated in CHG context:	0.6%
C methylated in CHH context:	1.0%
C methylated in unknown context (CN or CHN):	2.6%

However when I count the number of Cs or the number CpGs in the *bismark_bt2_pe.deduplicated.CX_report.txt of the same sample the number of Cs is 98066396 or the number of methylated CpGs is 407357 and the global methylation level is slightly different (for CpG from 3.44% to 3.1%)

Is this caused by the deduplication step? I suspect that the report file is generated before the deduplication step and the CX_report file is generated after the deduplication step, so if I want to show my global level of methylation what estimate should I use, before or after?

Thank you very much.

**Comment by FelixKrueger** [comment]
Hi there,

In my experience, the number total number of calls that end up in the extracted methylation calls (which are the C* files output by the methylation extractor, the coverage file output by the `--bedGraph` option or the bismark2bedGraph module, or the C*_report file output by coverage2cytosine process) can be different for a number of reasons:

- deduplication will remove a fraction of reads
- overlap detection and removal between R1 and R2 may remove some calls
- applying a coverage filter might change the values (this is *not* done by default though)

I would argue that you should go with the values that are most relevant for what you are working downstream, so I would use the calls from the extraction report after the deduplication and methylation have taken place.

**Comment by H1889** [comment]
thank you for your reply, it is clear now. I close the issue.
