### ISSUE TITLE
Methylation conversion efficiency and m-bias plot

### ISSUE THREAD

**Issue by Anamika-kumari** [FelixKrueger/Bismark#581]
Hello Sir,

I am checking the conversion efficiency of the spike-in control used (puC19). Kit used is NEBNext Enzymatic methyl seq kit.
Below are the commands I have used for analysis.
Before these command I have run the same pipeline using Bowtie 1 and it gave 21% conversion but when aligned using bowtie2 it gave 48% conversion.
Firstly, does this variation comes usually with the bowtie tool.
Could you please help in resolving this, is there any mistake in commands as the conversion efficiency should be 96-98%. 

 
trim_galore -paired --fastqc --clip_R2 5 --dont_gzip /home/singhrajender/Documents/Bismark-0.22.3/Am_WGM_R1.fastq.gz /home/singhrajender/Documents/Bismark-0.22.3/Am_WGM_R2.fastq.gz

./bismark_genome_preparation /home/singhrajender/Documents/Ana/second/genome

./bismark --bam --bowtie2 /home/singhrajender/Documents/Ana/second/genome -1 /home/singhrajender/Documents/Bismark-0.22.3/Am_WGM_R1_val_1.fq -2 /home/singhrajender/Documents/Bismark-0.22.3/Am_WGM_R2_val_2.fq

./deduplicate_bismark -p -bam /home/singhrajender/Documents/Bismark-0.22.3/Am_WGM_R1_val_1_bismark_bt2_pe.bam

./bismark_methylation_extractor -p  --no_overlap --merge_non_CpG --gzip --bedGraph --counts --cytosine_report --genome_folder /home/singhrajender/Documents/Ana/second/genome /home/singhrajender/Documents/Bismark-0.22.3/Am_WGM_R1_val_1_bismark_bt2_pe.deduplicated.bam

**Comment by FelixKrueger** [comment]
The commands you are using look fairly sensible to me. As this is meant to be a conversion control only, I would probably do this analysis in single-end mode using Read 1 only (it is faster and less more hassle-free).

I am not sure if there can be such a difference between Bowtie and Bowtie2, but Bowtie (1) doesn't do InDel mapping so it has been kind of phased out some 10 years ago.... I don't see a reason why one wouldn't trust the default alignments to pUC19 using Bowtie2.

I just wanted to mention that even if you see fairly hight levels of methylation, which you interpret as non-conversion, there have been studies showing that the secondary structure, or super-coiling of DNA (here, the mitochondrium) can lead to a failure in bisulfite conversion: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5671948/ Maybe this is something to consider?

**Comment by Anamika-kumari** [comment]
Thank you for your response.

I have checked this paper talking about secondary structure, but before going for library preparation we fragment sample. So secondary structure should not be the probable cause.

One more thing that I noticed is human sample on which I am working is showing 75% methylated CpG but only spike-in control is showing low methylation.

**Comment by FelixKrueger** [comment]
This is not the first time spike-in 'controls' are acting up... http://felixkrueger.github.io/Bismark/faq/conversion_efficiency/#bisulfite-conversion-rate-considerations
