### ISSUE TITLE
Broken link - "Quality Control, trimming and alignment of Bisulfite-Seq data"

### ISSUE THREAD

**Issue by tamuanand** [FelixKrueger/Bismark#582]
Hi @FelixKrueger 

On this page - https://github.com/FelixKrueger/Bismark/#links - the 3rd link seems to be broken

Our protocol "Quality Control, trimming and alignment of Bisulfite-Seq data"
http://www.epigenesys.eu/en/protocols/bio-informatics/483-quality-control-trimming-and-alignment-of-bisulfite-seq-data-prot-57

In case it is possible at your end, it would be good to have this fixed.

Thanks in advance

**Comment by FelixKrueger** [comment]
I removed the link entirely (on the dev branch), I am afraid this is broken on the Epignesys side of thing. Thanks for letting me know.
