### ISSUE TITLE
[Question]: Bismark Alignment step with bowtie2 - Guidelines on using --parallel with -p NTHREADS

### ISSUE THREAD

**Issue by tamuanand** [FelixKrueger/Bismark#583]
Hi @FelixKrueger 

I have a question on using the combination of `--parallel with -p NTHREADS` with Bismark alignment using bowtie2 

http://felixkrueger.github.io/Bismark/options/alignment/#alignment (for `--parallel` says this)
```
(May also be --multicore ). Sets the number of parallel instances of 
Bismark to be run concurrently. This forks the Bismark alignment 
step very early on so that each individual Spawn of Bismark processes
 only every n-th sequence (n being set by --multicore). Once all processes
 have completed, the individual BAM files, mapping reports, unmapped
 or ambiguous FastQ files are merged into single files in very much
 the same way as they would have been generated running Bismark 
conventionally with only a single instance.

If system resources are plentiful this is a viable option to speed up 
the alignment process (we observed a near linear speed increase 
for up to --multicore 8 tested).
```
http://felixkrueger.github.io/Bismark/options/alignment/#bowtie-2-effort-options says 
```
PARALLELIZATION OPTIONS:
-p NTHREADS

Launch NTHREADS parallel search threads (default: 1). 
Threads will run on separate processors/cores and synchronize 
when parsing reads and outputting alignments. Searching for 
alignments is highly parallel, and speed-up is close to linear. 
NOTE: It is currently unclear whether this speed increase also 
translates into a speed increase of Bismark since it is running 
several instances of Bowtie 2 concurrently! 

Increasing -p increases Bowtie 2's memory footprint. E.g. when 
aligning to a human genome index, increasing -p from 1 to 8 increases 
the memory footprint by a few hundred megabytes (for each instance of Bowtie 2!)
```

Question: Given the above, let's say I have a r5.12 EC2 (48 cpu and 384GB) and I have my bismark genome (human) already prepared, what would be the right combo of --parallel and -p that you would recommend for PE fastq.gz files
- should it be --parallel 8 and -p 8 OR am I overanalyzing/over-optimizing things here.

Thanks in advance.

**Comment by FelixKrueger** [comment]
That would probably overcommit on the CPU part quite a bit, if each of the 8 x 2 Bowtie 2 threads would use the full amount of CPUs you would be looking at 8 (Bismark) + (2 * 8 ) * 8 CPUs....

I would probably start a little more moderate, how about `--parallel 4 -p 4`?

**Comment by tamuanand** [comment]
Hi @FelixKrueger 

I am trying this with `--parallel 4 -p 4` as you suggested. The bismark align step has been running for about 5 days now - is this expected? I have used TrimGalore on a paired end SRR id - SRR10532144 and Bismark align is running on the trimmed fastq files

```
bismark --genome <path_to_hg38_Bismark_Index> \
   -1 SRR10532144_2_1_val_1.fq -2 SRR10532144_2_2_val_2.fq \
  --maxins 1000 --parallel 4 -p 4 --no_dovetail
```

Thanks

**Comment by FelixKrueger** [comment]
Quite a while, how many reads are in this file? Just from experience, `-X 1000` will make alignments a fair bit slower, while normally not adding (m)any additional alignments....

**Comment by tamuanand** [comment]
Hi @FelixKrueger  These are the read metrics

```
SRR10532144_2_1.fastq [and 2_2.fastq] - 323,906,726 reads 

After trimming,  323,393,551 reads each and this is what is being used for bismark
```

**Comment by tamuanand** [comment]
I followed this from the nf-core methylseq docs - should I remove them? 

> Just from experience, -X 1000 will make alignments a fair bit slower, while normally not adding (m)any additional alignments

https://nf-co.re/methylseq/2.3.0/parameters#em_seq 
```
Equivalent to --clip_r1 8 --clip_r2 8 --three_prime_clip_r1 8 --three_prime_clip_r2 8.

Also sets the --maxins flag to 1000 for Bismark.
```

**Comment by tamuanand** [comment]
Hi @FelixKrueger 

When I remove `--no_dovetail`, the job finishes in about 12 hrs.

http://felixkrueger.github.io/Bismark/options/alignment/ does not provide info on `--no_dovetail`
- it might be a good idea to add info about `--no_dovetail` to the above docs

bismark command line has this

```
--no_dovetail            It is possible, though unusual, for the mates to "dovetail", with the mates seemingly extending
                         "past" each other as in this example:

                         Mate 1:                 GTCAGCTACGATATTGTTTGGGGTGACACATTACGC
                         Mate 2:            TATGAGTCAGCTACGATATTGTTTGGGGTGACACAT
                         Reference: GCAGATTATATGAGTCAGCTACGATATTGTTTGGGGTGACACATTACGCGTCTTTGAC

                         By default, dovetailing is considered inconsistent with concordant alignment, but by default
                         Bismark calls Bowtie 2 with --dovetail, causing it to consider dovetailing alignments as
                         concordant. This becomes relevant whenever reads are clipped from their 5' end prior to mapping,
                         e.g. because of quality or bias issues.

                         Specify --no_dovetail to turn off this behaviour for paired-end libraries. Default: OFF.
```

To make sure I am applying (or not applying) the `--no_dovetail` argument
- I am assuming that if I have PE reads from EM-Seq,  I should not use it if I use the EM-Seq recommended trimming options [listed here](http://felixkrueger.github.io/Bismark/bismark/library_types/)

```
--clip_r1 10 --clip_r2 10 --three_prime_clip_r1 10 --three_prime_clip_r2 10
```

Thanks

**Comment by FelixKrueger** [comment]
You should be fine if you don't specify anything. Dovetailing really only becomes relevant if reads are trimmed from their 5' ends, and allowing dovetailing is the default mode.

I'll try to add this to the documentation. Cheers, Felix

**Comment by FelixKrueger** [comment]
This has now been updated, and can be found here: 
http://felixkrueger.github.io/Bismark/options/alignment/#bowtie-2-specific-options

**Comment by tamuanand** [comment]
Thanks @FelixKrueger 

One question on inputs to bismark
- will it be faster if I were to use pigz to decompress the gzipped fastq files and then provide them as input to bismark

I know bismark can take gzipped files, but I feel a lot of time is used up by perl to gunzip them before passing it on to bowtie2.
- As mentioned above, each of the fastq files has about 323,393,551 reads

I wanted to seek your inputs based on your expertise.
