### ISSUE TITLE
How to combine forward and reverse .bam files of same sample ?

### ISSUE THREAD

**Issue by SowmyaPulapet** [FelixKrueger/Bismark#586]
Hi, 

I was using Bismark for mapping my Bisulfite seq samples (paired-end) and unfortunately I got very low mapping efficiancy of 30-40%. So, based on the instructions given [here](https://github.com/FelixKrueger/Bismark/blob/master/Docs/FAQ.md#issue-2) I aligned my reads in single-end mode (R1 in default (=directional) mode and R2 in --pbat mode) and also added the --local  option. I was using Bowtie and as expected the mapping efficiency increased to 80% after this. 

But now what I don't understand is how can I proceed to downstream processing using  this seperate bam files for each samples ? I did methylation calling using `bismark_methylation_extractor` seperately for each read bam file and then used this command for `bismark2bedGraph`: 

`bismark2bedGraph -o sample CpG* --zero_based`

where CpG* includes the files for both R1 and R2. 

I also need the summary but when I tried it with the following command: 

`bismark2summary sample_R1_bismark_bt2.bam sample_R2_bismark_bt2.bam -o sample --title sample_summary_report`

the report showed details for both bam files seperately and it was not shown as a single sample. 

Also while calculating the mapping statistics for a single sample how can I get the values by combining statistics of forward and reverse bam files ?

Also can I combine the bam files of forward and reverse  reads at the deduplication step using the option `--multiple` and `--paired` ?

Hope you would help me with this. 

Thank you.

**Comment by FelixKrueger** [comment]
The tips given in the FAQ document are mostly meant to assist you with trouble shooting of why the mapping efficiency is poor in a paired-end setting. By far the easiest and best outcome of the single-end alignment exercise would be to understand why the mapping is poor in paired-end mode, rectify the situation (most likely a trimming and/or other parameter setting), and then repeat the paired-end alignment - this time with a better outcome. Is it just the `--local` option that brings the mapping rate up, can do you know where it went wrong? e.g.
- do you see poor sequencing quality in one of the reads?
- do you see a very biased sequence composition at at the start (or elsewhere in the reads?)
- did you use the Accel Swift kit (which has a very high number of 10-20 Gs at the start of R2)?
- did you have to use a larger value for the insert size (`-X)`?

I'd be happy tom take a look at your FastQC reports if that would help.

If you can't find out the issue itself and rectify it, does paired-end alignment with `--local` also result in a good mapping efficiency, or is it really only single-end alignments that work well?

Only if the above steps fail I would move on to the single-end approach, personally. As you have already seen, it is a little tricky getting the results presented in a nice way (the summary report won't take care of merging the for example), and you will double-count data from regions where R1 and R2 overlap, thereby causing a coverage bias. This is why paired-end processing with overlap detection and removal would be superior in my eyes.

The methylation extraction, and coverage file generation from all CpG* files makes sense to me, and the resulting coverage file should be valid (with the caveat of overlapping calls, see above). I am afraid if you wanted to merge both reports together you have to manually do the calculation and edit one set of reports to use those numbers. But again I would avoid this if it was possible at all.

**Comment by SowmyaPulapet** [comment]
Hi, 

Thank you for your quick reply. To answer your questions: 

1. My sequence reads have good sequence quality
2. I believe not 
3. No, I didn't use Accel Swift kit 
4. Not really. 

I will attach the Fastqc reports and a sample of my sequences here. I am currently running the paired-end alignment with `--local` option, I will let you know how that goes once finished. 

Thank you. 
[sample data.zip](https://github.com/FelixKrueger/Bismark/files/11573670/sample.data.zip)

**Comment by FelixKrueger** [comment]
I agree the data is of good quality, but then I saw these base compositions in Read 2:

<img width="539" alt="Screenshot 2023-05-26 at 11 10 17" src="https://github.com/FelixKrueger/Bismark/assets/5870509/70c38a6b-05a3-4da1-bdf9-a58128533a0d">

I am > 99% sure that this **is** an Accel Swift data set, and trimming of the data accordingly should work like a charm.

http://felixkrueger.github.io/Bismark/bismark/library_types/#swift

```
trim_galore --clip_R1 15 --clip_R2 15 --three_prime_clip_R1 15--three_prime_clip_R2 15 --paired file1 file2
```

**Note:** 

Running this data in `--local` mode will almost certainly include a lot of these G bases from Read 2 into your data, which consequently looks as though you've got methylated calls. These calls are artifactual, however, and I would advise you to perform trimming as outlined above. I hope this helps!
