### ISSUE TITLE
[Question]: Is bismark faster if provided with decompressed fastq files

### ISSUE THREAD

**Issue by tamuanand** [FelixKrueger/Bismark#588]
Hi @FelixKrueger 

One question on inputs to bismark
- will it be faster if I were to use pigz to decompress the gzipped fastq files and then provide them as input to bismark

I know bismark can take gzipped files, but I feel a lot of time is used up by perl to gunzip them before passing it on to bowtie2.
- In my case I am using PE fastq files where each has about 323,393,551 reads

I wanted to seek your inputs based on your expertise.

Thanks in advance.

**Comment by FelixKrueger** [comment]
Here are my thoughts in this issue: 

Conceptually, Bismark runs in the following steps: 

1. The compressed input files are read in and converted _in-silico_ into a C->T style
2. The C -> T converted files (uncompressed, unless you as for them to be compressed) are a used as input for Bowtie 2
3. The unconverted input files are once more read in used for the methylation calling

It is well known that gunzip decompression isn't the fastest, and that there are faster alternatives out there. (As an example, Trim Galore now preferentially uses `igzip` for decompression if available, and `pigz` for faster compression https://github.com/FelixKrueger/TrimGalore/pull/149). While step 1 would undoubtedly benefit somewhat from faster decompression, the generation of converted input files really is only the first step in the process, and should only be small-ish role in the overall alignment process, compared to finding alignments and methylation calling.

Having said that, I have never run any specific tests for this myself. Do you fancy implementing `igzip` and `pigz` as optional  de-/compression methods, and submitting a PR? 😃
