### ISSUE TITLE
output of CX report file not consistently sorted by Chromosomes?

### ISSUE THREAD

**Issue by juicybrain** [FelixKrueger/Bismark#591]
Hi Felix,

I recently processed a set of samples using the Bismark Methylation Extractor with the following command:
for spl in ...; do bismark_methylation_extractor -p --bedGraph --gzip --parallel 4 --CX --cytosine_report --genome_folder ~/ref/genome/mm10 ${spl}\_filtered.bam; done.

This resulted in the generation of the CX report files.  I noticed that the chromosome names in 5 out of the 12 samples start with "chr1", which seems to indicate that they were sorted accordingly. However, the remaining samples did not follow this pattern, with chromosome names starting with "chr4_JH584294_random" or "chrY_JH584300_random".

Is this an expected outcome? If not, what could potentially explain this discrepancy in chromosome sorting?

Looking forward to your guidance on this matter.

Best,
Yuxiang

**Comment by FelixKrueger** [comment]
Hi Yuxiang,

I just quickly tried to find the term 'sort' in coverage2cytosine, and it appears that it reports the reads in the same order as they come in from the input coverage files. Chromosomes that were not covered in the experiment as reported in a sorted manner, and after the chromosomes that were covered.

I suppose the order of the files may be different, but the contents (i.e. the number of lines), should be equivalent.

**Comment by juicybrain** [comment]
Hi Felix,

Thank you very much for your reply and help regarding this issue!

Indeed, the Chrs' order of CX files is the same as the corresponding ".cov.gz" files, and the numbers of lines are the same among different replicates with different Chrs' orders.  

Yuxiang
