### ISSUE TITLE
chromatin accessibility bam file

### ISSUE THREAD

**Issue by Rongge11** [FelixKrueger/Bismark#592]
Hi Felix,

Thank you for this wonderful Bismark!

I am analyzing scNMT-seq data and having some questions.

In order to obtain footprints, I aim to use TOBIAS, which only accept bam file,  by inputting open chromatin's .bam files generated from scNMT-seq.  I already got manOwar file following the instructions provided at #268. 

Now my questions is how to setup threshold to filter manOwar and extract the GC .bam, like meth.GC > 1?

Thank you for your help.

**Comment by FelixKrueger** [comment]
I think this was mentioned in the other thread.

> Now finally, I think you should be able to make use of this file by:

- reading in the manOwar file, filtering on GC methylation (e.g. if meth.GC >0), and store the read ID (or at least the first part of the file, `HWI-D00436:298:C9KY4ANXX:1:1101:2035:2000` in the example above)
- read in again the Bismark BAM file, and write out only reads that contain the (previously filtered) read IDs

If you are very skilled with command line tools you might be able to do this as a one-liner (which I am not...), or you would have to write a script in Python, Perl etc. to do this for you.
