### ISSUE TITLE
bismark2bedGraph empty cov file

### ISSUE THREAD

**Issue by NaomiZakimi** [FelixKrueger/Bismark#595]
I tried runnning 'bismark2bedgraph CpG_context_1ct.trimmed.fastq_bismark.txt --cutoff 3 -o CpG_context_1ct_trimmed.fastq_bismark.bedgraph' but the coverage file is empty. The CpG_context file is not empty so not sure what could be causing this issue. (see screen output)
Thanks in advance.

<img width="1262" alt="Screen Shot 2023-06-12 at 10 26 58 PM" src="https://github.com/FelixKrueger/Bismark/assets/136419360/bbe7a6ea-8cd5-468b-86cf-f666aa1741c1">

**Comment by FelixKrueger** [comment]
The issue seems to be that you've got a genome that has too many chromosomes, scaffolds or contigs to write to concomitantly. The solution to this is to use the flag `--scaffolds`. This is the help text:

```
--scaffolds/--gazillion    Users working with unfinished genomes sporting tens or even hundreds of thousands of
                           scaffolds/contigs/chromosomes frequently encountered errors with pre-sorting reads to
                           individual chromosome files. These errors were caused by the operating system's limit
                           of the number of filehandle that can be written to at any one time (typically 1024; to
                           find out this limit on Linux, type: ulimit -a).
                           To bypass the limitation of open filehandles, the option --scaffolds does not pre-sort
                           methylation calls into individual chromosome files. Instead, all input files are
                           temporarily merged into a single file (unless there is only a single file), and this
                           file will then be sorted by both chromosome AND position using the Unix sort command.
                           Please be aware that this option might take a looooong time to complete, depending on
                           the size of the input files, and the memory you allocate to this process (see --buffer_size).
                           Nevertheless, it seems to be working.
```

If I were you I would probably not start using a cut-off of 3 calls per position to start with as this has the potential to remove a lot of data (you could run it without threshold and filter later, or simply run it twice, with and without filtering, to see how many positions you would essentially lose (the number of lines in each coverage output file is equivalent to the number of different positions covered). Good luck!

**Comment by NaomiZakimi** [comment]
> The issue seems to be that you've got a genome that has too many chromosomes, scaffolds or contigs to write to concomitantly. The solution to this is to use the flag `--scaffolds`. This is the help text:
> 
> ```
> --scaffolds/--gazillion    Users working with unfinished genomes sporting tens or even hundreds of thousands of
>                            scaffolds/contigs/chromosomes frequently encountered errors with pre-sorting reads to
>                            individual chromosome files. These errors were caused by the operating system's limit
>                            of the number of filehandle that can be written to at any one time (typically 1024; to
>                            find out this limit on Linux, type: ulimit -a).
>                            To bypass the limitation of open filehandles, the option --scaffolds does not pre-sort
>                            methylation calls into individual chromosome files. Instead, all input files are
>                            temporarily merged into a single file (unless there is only a single file), and this
>                            file will then be sorted by both chromosome AND position using the Unix sort command.
>                            Please be aware that this option might take a looooong time to complete, depending on
>                            the size of the input files, and the memory you allocate to this process (see --buffer_size).
>                            Nevertheless, it seems to be working.
> ```
> 
> If I were you I would probably not start using a cut-off of 3 calls per position to start with as this has the potential to remove a lot of data (you could run it without threshold and filter later, or simply run it twice, with and without filtering, to see how many positions you would essentially lose (the number of lines in each coverage output file is equivalent to the number of different positions covered). Good luck!

Thank you! You are correct. The genome I'm working with has many chrs.
