### ISSUE TITLE
Chh or chg context cov files to be generated

### ISSUE THREAD

**Issue by manjumoorthy95** [FelixKrueger/Bismark#596]
Is it possible to generate chh or chg context .cov files from bismark? I know we can use the bismark2bedgraph command, along with -cx option and chg or chh context file as input. But is that the right way to get it? As its taking very long time to get the output.

Also I wanted to clarify if there is any way we can make the cpg chh or chg context text files compatible with methylkit R package?

**Comment by FelixKrueger** [comment]
Yes, that is the way I would do it. And yes, it will take longer to make these output files, be reason simply being that there are so many ore Cs in non-CG context. I am not quite sure what is needed to get the data into methylKit, but this should be a fairly trivial transformation with a command line tool such as sed/awk. You can probably also ask ChatGPT do this for you :)
