### ISSUE TITLE
Running Bismark on reads from circular DNA

### ISSUE THREAD

**Issue by SaraValsoni** [FelixKrueger/Bismark#597]
Dear Felix,

I have methylation data from HBV cccDNA samples.
The experiment is like a target bisulfite sequencing but using different couples of primers to amplify several regions.
I'm studying how to manage the genome reference since it is a circular DNA and I was wondering if you have any suggestion about the genome preparation step or the parameters to use for the subsequent analysis with Bismark.

Thank you!
Best regards,
Sara

**Comment by FelixKrueger** [comment]
Hi Sara, 

apologies for the late response. I am afraid Bismark doesn't understand the concept of a circular reference, but I could see solutions one could get to work fairly easily. Both of them would require you to run the first round of data to the linearised reference sequence, while specifying `--unmapped`. You could then treat the unaligned reads

1. to a newly built reference sequence, which would be end of the reference sequence (at least the read length of your library long) plus the start of the original reference (also at least the read length of your samples). the problem with this approach would be that you would have to correct the methylation call positions manually (or writing a script to it) afterwards.
2. It might be easier to run the unaligned reads in `--local` mode to the original reference. This way you might get one of side of the reference to align (but not the other). The benefit of this would be that you don't have to translate coordinates, but you would arguably lose some calls.

Does this make sense?
