### ISSUE TITLE
Bismark Methylation % too high 

### ISSUE THREAD

**Issue by chipmunk824** [FelixKrueger/Bismark#598]
Hello, 

This wasn't a technical issue but I needed some advice so I'm writing on this github page. I've used the bismark tool to align and extract the methylation level of my sample but the level of methylation % was too high. Majority of my samples showed 99% methylation and I think there was an issue during the aligning process or the methylation extraction process. If you have any suggestions I would really appreciate it. 

Thank you in advanced!

**Comment by FelixKrueger** [comment]
Hi @chipmunk824 

Do you see 99-100% methylation rate in all contexts, i.e. CpG, CHG as well as CHH, or are there major differences? The only plausible answer to the former case I can think of would be that the sample in question has not been converted with sodium-bisulfite at all. In fact, if you align any bog standard sequencing method (e.g. ChIP-seq, ATAC or RNA-seq, you would also get methylation information in the 99% area.
