### ISSUE TITLE
Unknown option: directional Unknown option: ignore-quals Unknown option: no-mixed Unknown option: no-discordant

### ISSUE THREAD

**Issue by aijigekoukou-shen** [FelixKrueger/Bismark#599]
Hi

I encountered the following error with bismark.

**Unknown option: directional
Unknown option: ignore-quals
Unknown option: no-mixed
Unknown option: no-discordant
Please respecify command line options**

My command is **bismark --genome ./index/ -p 5 -q --score_min L,0,-0.2 --maxins 500 --bowtie2 --directional --ignore-quals --no-mixed --no-discordant --dovetail -o ./ -1 L1.R1.Clean.fq.gz -2 L1.R2.Clean.fq.gz**.

Both bismark and bowtie2 are the latest versions, what should I do? Thank you for your attention.

**Comment by FelixKrueger** [comment]
As the  error messages suggest, you were trying to set several parameters that are not exposed to the user, and can thus not be set. The correct command would simply be:

```
bismark --genome ./index/ -p 5 --score_min L,0,-0.2 --maxins 500  -o ./ -1 L1.R1.Clean.fq.gz -2 L1.R2.Clean.fq.gz
```
