### ISSUE TITLE
bam2nuc CG value?

### ISSUE THREAD

**Issue by avilella** [FelixKrueger/Bismark#60]
Hi,

Just a clarification on the values returned from bismark bam2nuc for bisulfite converted data:

Is the CG percent sample value for a bisulfite converted dataset the observed value of a bisulfite converted reference with all the CG positions preserved?

Is so, for a sample with only 50% methylated-CpGs, is it correct to assume that the CG percent sample value should drop by half, with respect to another sample with a 100% methylated-CpGs?

Thx

**Comment by FelixKrueger** [comment]
Hi Albert,

The coverage value should be independent of the methylation state as it uses the genomic sequence rather than the sequence in the reads themselves. This is taken from `bam2nuc --help`:

```
SYNOPSIS:

  This script bam2nuc reads BAM files and calculates the mono- and di-nucleotide coverage of the
  reads (using the genomic sequence rather than the observed sequence in the reads themselves)
  and compares it to the average genomic sequence composition. Reads harbouring InDels are not
  taken into consideration.
```

Does that clarify things?

**Comment by avilella** [comment]
I think it's clear now:

If one had two bam files produced with identical reads, one with
conversion_rate 99 and another with conversion rate 1 pct, since the
counting is from the genomic sequence where the reads fall, rather than the
observed sequence in the reads themselves, then those two files would
produce the same bam2nuc result.

Correct?

Thanks for clarifying Felix,

A.

**Comment by FelixKrueger** [comment]
Correct!

**Comment by jrmerritt6** [comment]
So just to be clear, if the samples have a similar percent.sample to percent.genomic, the DNA was not bs converted? Or if they are similar, you had 100% bisulfite conversion?

**Comment by FelixKrueger** [comment]
No, if `percent.sample` is very similar to `percent.genomic` it means that there is no obvious enrichment or depletion for certain dinucleotides in the observed sample compared to the genomic average. This script uses the observed positions of the mapped bisulfites samples, but analyses the sequence based on the reference genome. It is, if you will, more a measure of whether the bisulfites treatment has an effect on the read mapping as such (read conversion or methylation states are completely disregarded for this). Hope this helps, Felix

**Comment by jrmerritt6** [comment]
Thank you. I had a mini-heart attack. My values are almost exactly the same. Thank you!

**Comment by FelixKrueger** [comment]
On the contrary, I think this is a good thing! Please don't have a heart attack over some bisulfite-seq samples :)
