### ISSUE TITLE
Obtain the methylation percentage of a region of my amplicon.

### ISSUE THREAD

**Issue by ifalconi20** [FelixKrueger/Bismark#600]
For context, I have data from a 230 base pair (bp) amplicon. These data include sequences ranging in length from 44 to 230 bp, after applying a filtering and quality control process. I have performed the mapping and obtained the percentage of methylation for the entire amplicon. However, I would like to know how to obtain the methylation percentage for a specific section of my amplicon, in particular the first 100 bp.

The main problem is that I have the size of the sequences between 44-230, so trimming down to 100 bp sequences would remove important regions for mapping. I would like to know how to get the percentage of methylation of the first 100 bp after mapping in Bismark. Since I have reconstructed my amplicon there.

**Comment by FelixKrueger** [comment]
To be very honest, I am not exactly sure if I understand the nature of your problem. Are you saying you've got a single amplicon, so virtually all of your reads start at the very same position? Are you aligning the reads to the amplicon sequence on its own, or to the genome where the amplicon is part of it?  Can't you simply only use CpG with positions 1-100, and ignore the rest (or in the genome use the genomic offset +1 to +100?

If the data is of paired-end nature, you could do something similar for the other end?
