### ISSUE TITLE
[Question]: Command line options for generating CX report

### ISSUE THREAD

**Issue by tamuanand** [FelixKrueger/Bismark#602]
Hi @FelixKrueger 

I had a question on what's the correct command line options to be used to generate CX reports. 

Based on what you suggest [here](https://github.com/FelixKrueger/Bismark/issues/567#issuecomment-1445470771), I tried this 

```
bismark_methylation_extractor \
    SRR13076821_trimmed_1_bismark_bt2_pe.deduplicated.bam \
    --bedGraph \
    --cytosine_report \
    --counts \
    --gzip \
    --report \
    --paired-end \
    --parallel 10 \
    --ample_memory \
    --genome_folder hg38_Bismark_Index 
```

However, these output files got generated **_but nothing with `*_CX_report.txt.gz`_**. 

```
CHG_OB_SRR13076821_trimmed_1_bismark_bt2_pe.deduplicated.txt.gz
CHG_OT_SRR13076821_trimmed_1_bismark_bt2_pe.deduplicated.txt.gz
CHH_OB_SRR13076821_trimmed_1_bismark_bt2_pe.deduplicated.txt.gz
CHH_OT_SRR13076821_trimmed_1_bismark_bt2_pe.deduplicated.txt.gz
CpG_OB_SRR13076821_trimmed_1_bismark_bt2_pe.deduplicated.txt.gz
CpG_OT_SRR13076821_trimmed_1_bismark_bt2_pe.deduplicated.txt.gz
SRR13076821_trimmed_1_bismark_bt2_pe.deduplicated.bedGraph.gz
SRR13076821_trimmed_1_bismark_bt2_pe.deduplicated.bismark.cov.gz
SRR13076821_trimmed_1_bismark_bt2_pe.deduplicated.CpG_report.txt.gz
SRR13076821_trimmed_1_bismark_bt2_pe.deduplicated.cytosine_context_summary.txt
SRR13076821_trimmed_1_bismark_bt2_pe.deduplicated.M-bias.txt
SRR13076821_trimmed_1_bismark_bt2_pe.deduplicated_splitting_report.txt
```

Am I using the correct arguments? 

Thanks in advance.

**Comment by FelixKrueger** [comment]
If you want the full non-CG report you need to include `--CX`. That's all :)

**Comment by tamuanand** [comment]
Hi @FelixKrueger 

I do not need the full non-CG report. Is `SRR13076821_trimmed_1_bismark_bt2_pe.deduplicated.cytosine_context_summary.txt` then the CX report being referred to in other threads?

Also happened to see this - which seems to indicate a report with file name ending in *.CX_report.txt.gz
https://support.illumina.com/help/BaseSpace_App_MethylSeq_help/Content/Vault/Informatics/Sequencing_Analysis/Apps/swSEQ_mAPP_MethylSeq_CytosineReport.htm 

```
Cytosine Report (*.CX_report.txt.gz)The MethylSeq v1.0 app provides a 
Cytosine Report in a GZIP archive file format (*.CX_report.txt.gz). 
The unzipped report is generated in a tab-delimited text (TXT) format.
The cytosine report contains methylation status for every cytosine in the genome, 
including both strands. This report is only generated when you select 
Enable genome-wide cytosine methylation report for all cytosines in the genome on the input form
--

**Comment by FelixKrueger** [comment]
By default, the process `coverage2cytosine` is run for the CpG context only, resulting in a a file ending in `CpG_report.txt.gz` (which you linked above). If you want to extend this report to all 3 contexts (Cpg, CHH and CHG) you need to include the option `--CX` , which would result in a file ending in `CX_report.txt.gz`. More details on this are shown [here](http://felixkrueger.github.io/Bismark/bismark/methylation_extraction/#optional-genome-wide-cytosine-report-output)

The Cytosine Context Summary is something [quite different](http://felixkrueger.github.io/Bismark/bismark/methylation_extraction/#gpc-methylation-assessment-context-specific-methylation-summary-report) and mostly relevant for assessing GpC methylation.

I hope this helps?
