### ISSUE TITLE
empty bam files - single end RRBS data

### ISSUE THREAD

**Issue by riyabelani** [FelixKrueger/Bismark#604]
hello! I am working to process single end RRBS data. I used trimgalore to remove the Illumina adapter and the poly g tail and reran FastQC to verify there were no adapters. I am now trying to take the trimmed files and align them with the reference genome I downloaded from genbank as a fasta file. I have processed the genome and it created the CT and GA conversion folders. when I try to align the data, however, the outputs are zero bytes. I updated my samtools and all programs seem to be downloaded but I am unsure what is going wrong. I am using conda. 

here is what it looks like:

Single-end alignments will be performed
=======================================

Input file is in FastQ format
Writing a C -> T converted version of the input file 2B_trimmed_trimmed.fq.gz to 2B_trimmed_trimmed.fq.gz_C_to_T.fastq

Created C -> T converted version of the FastQ file 2B_trimmed_trimmed.fq.gz (424930 sequences in total)

Input file is 2B_trimmed_trimmed.fq.gz_C_to_T.fastq (FastQ)

Now running 2 instances of Bowtie 2 against the bisulfite genome of /Volumes/SEACR_Mac_Seagate/referencegenome/ with the specified options: -q --score-min L,0,-0.2 --ignore-quals

Now starting the Bowtie 2 aligner for CTreadCTgenome (reading in sequences from 2B_trimmed_trimmed.fq.gz_C_to_T.fastq with options -q --score-min L,0,-0.2 --ignore-quals --norc)
Using Bowtie 2 index: /Volumes/SEACR_Mac_Seagate/referencegenome/Bisulfite_Genome/CT_conversion/BS_CT

Found first alignment:	NB551671:66:HFG2NAFX2:1:11101:21258:1048_1:N:0:CTTAGGAC+CAGTGAAG	0	JAKFGF010003257.1_CT_converted	12386	1	62M	TGGGGAGGATATTATTTTTTATTTGGTTTTGAATTTTTATTTTTTTAATTGTTAATTTGATT	AAAAAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE	AS:i:0	XS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:62	YT:Z:UU
Now starting the Bowtie 2 aligner for CTreadGAgenome (reading in sequences from 2B_trimmed_trimmed.fq.gz_C_to_T.fastq with options -q --score-min L,0,-0.2 --ignore-quals --nofw)
Using Bowtie 2 index: /Volumes/SEACR_Mac_Seagate/referencegenome/Bisulfite_Genome/GA_conversion/BS_GA

Found first alignment:	NB551671:66:HFG2NAFX2:1:11101:21258:1048_1:N:0:CTTAGGAC+CAGTGAAG	16	JAKFGF010006760.1_GA_converted	8935	1	62M	AATCAAATTAACAATTAAAAAAATAAAAATTCAAAACCAAATAAAAAATAATATCCTCCCCA	EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAAAAA	AS:i:0	XS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:62	YT:Z:UU

>>> Writing bisulfite mapping results to /Volumes/SEACR_Mac_Seagate/bismark/2B_trimmed_trimmed_bismark_bt2.bam <<<

sh: line 1: 23528 Abort trap: 6           /Users/rtanner/anaconda3/envs/bismark/bin/samtools view -bSh - 2> /dev/null > /Volumes/SEACR_Mac_Seagate/bismark/2B_trimmed_trimmed_bismark_bt2.bam

any assistance would be greatly appreciated!

**Comment by riyabelani** [comment]
my end goal is to get the dna methylation levels and look at CpG methylation levels specifically, through bismark and also seqmonk!

**Comment by riyabelani** [comment]
hello! Thank you, I downloaded the 1.3.1 version of conda and that seemed to work! I was able to produce all of my bam files!

**Comment by FelixKrueger** [comment]
glad to hear!
