### ISSUE TITLE
large genome

### ISSUE THREAD

**Issue by AlisaGU** [FelixKrueger/Bismark#606]
Hi, I want to apply bismark on the large genome. To improve the efficiency, I plan to split the fastq into several files and cat bam files into one.
These steps were tested on the test file provided by the bismark.
Out of expected, the bam file from `split-map-cat` was different from `map` slightly in the MAPQ column of two reads (2261_Ecoli_K12:561749-562016_R1 and 340_Ecoli_K12:561883-562258_R1).

Is it normal during this process?

Best regards,

**Comment by FelixKrueger** [comment]
I think this is potentially rather a question for Ben Langmead and/or the Bowtie 2 team. As far as I know, some heuristics may be applied that do not necessarily always results in the same sequence resulting in the very same result (I remember a few years back we came a across a case where a sequence aligned well in one case, but with a different readID the sequence did not produce an alignment at all). I suppose these cases are extremely rare overall though.

Just as an aside, the split-map-merge technique is applied internally within Bismark if you use the option `--parallel` already, maybe it could save you some time re-inventing it?
