### ISSUE TITLE
suggestion for -p 

### ISSUE THREAD

**Issue by AlisaGU** [FelixKrueger/Bismark#608]
Hi,
I noticed that the suggested value for -p parameter is 4. Maybe it depends on the reference genome size.
My reference genome is 47G. After test with `-p 4` `-p 10` `-p 20`, running time for 1000,000 read pairs is 144min, 75min and 36 min. It's clear that -p 4 is no more the best parallel value.

**Comment by FelixKrueger** [comment]
Thanks for your suggestion, I might just change the recommendation to 'needs to be determined empirically' in the future. Cheers, Felix
