### ISSUE TITLE
bismark2report graphs not generated

### ISSUE THREAD

**Issue by igordot** [FelixKrueger/Bismark#61]
I generated data with Bismark 0.16.3. I ran `bismark2report`. It found all 5 reports and completed without errors. However, when I checked the resulting html file, the charts did not show up. I reran it and it was the same. I then ran `bismark2report` from 0.16.0 in the same directory and the charts showed up.

I checked JavaScript console in Chrome and I see that there is an error in the 0.16.3 report, but not 0.16.0 report.

Screenshot from 0.16.3 report:
![image](https://cloud.githubusercontent.com/assets/6363505/17644696/92dfc582-615b-11e6-89e5-44a21c5b78bd.png)

Screenshot from 0.16.0 report:
![image](https://cloud.githubusercontent.com/assets/6363505/17644697/9cde1ac0-615b-11e6-98f6-e921fd16ebab.png)

**Comment by FelixKrueger** [comment]
Hi Igor, can you just get the latest development version of `bismark_sitrep.tpl` which I have changed just before I left. (see here: 1fec1615253c83078205b97980fec98f4233687e).
