### ISSUE TITLE
G->A conversion

### ISSUE THREAD

**Issue by AlisaGU** [FelixKrueger/Bismark#610]
Hi, Felix
After reading the paper and manual of Bismark, I am still confused about the `G->A conversion` for reads and genome. `C->T` is clear. Could you share the reason why convert G to A and a small example about it?

Best regards,

**Comment by AlisaGU** [comment]
>  the conversion of C to T needs to take place for both strands separately

That's because the methylation can occur at two strands (right?). 

Methylation in the top strand can be addressed by the `C` to `T` of reads and genome. So the conversion of `G` to `A`  is for the Methylation in the bottom strand.

I am still confused about the mapping process when the methylation occurred on the bottom strand.  Can you share the process based on my example?
![微信图片_20230809193633](https://github.com/FelixKrueger/Bismark/assets/38097726/34deece6-0c83-4542-b69c-eaa385f1dc68)

Best regards,

**Comment by FelixKrueger** [comment]
If your sequence from the machine is `GTCAAGT`, it would be converted in a `C->T` manner, to be 

`GTTAAGT`. This top-strand converted sequence is:

`ATTTGAT` - CT/CT alignment would fail (OT)

The bottom strand converted sequence is (GA converted top strand):

`ACTTAAC`
`GTTAAGT`  the CT/GA aligment (OB) would work, giving a match in reverse (-) direction.

**Comment by AlisaGU** [comment]
Thanks! I get it!

I was stuck in the comparison between `ACTTAAC` and `GTTAAGT` and thought they would fail. After your explanation, they will match in reverse direction.

Thanks again!

**Comment by FelixKrueger** [comment]
Excellent, glad it helped!
