### ISSUE TITLE
Stage to merge biological replicates

### ISSUE THREAD

**Issue by hAmbreen** [FelixKrueger/Bismark#614]
Hi Felix,

First of all, I must congratulate you on this wonderful tool and moreover, your constant efforts to actively resolve issues.

I am working with whole genome bisulfite sequencing for the first time and I was wondering when should be a good time to merge information from biological replicates. I have two biological replicates for each condition and wish to combine them to divulge details in high resolution. Shall I merge my bam files to get a consolidated cytosine coverage or since I am planning on identifying DMRs so I can combine my coverage report. Not really sure if my approach is fine to go with.

Any help or guidance would be greatly appreciated.

Many Thanks,
Heena

**Comment by FelixKrueger** [comment]
Thanks for the kind words!

I would say that biological replicates should generally not be merged, however if you would like to increase coverage and want to use a single sample (as you are suggesting), then you've got different options:

1. merge the BAM files (using `samtools cat`) and then then continue with deduplication
2. run `deduplicate_bismark` with the option `--multiple`, which will do the merging and deduplication for your.
3. you could also run the alignment and deduplication and then the methylation extraction separately (to get separate coverage files), and then merge the coverage files afterwards (either using a script, or e.g. in a tool like SeqMonk)
4. You could also run the methylation extraction separately, and then run `bismark2bedGraph` using the CpG* files from both replicates as input (something like `bismark2bedGraph --gzip -o replicates_merged.cov.gz CpG*`

As you can see there are no problems, but several solutions!

**Comment by hAmbreen** [comment]
Thank you, Felix. This makes total sense.

**Comment by AlisaGU** [comment]
Hi, @FelixKrueger 
I encountered a similar problem with merging results.

To avoid high duplication rates, I divided one sample into 10 libraries to sequence separately and performed the `bismark`, `deduplicate` and `methylationExtractor` separately.

After these steps, many files were generated in each of the 10 directories
![image](https://github.com/FelixKrueger/Bismark/assets/38097726/19f96e04-b3f6-49d4-b66a-1c636219fe4f)

>you could also run the alignment and deduplication and then the methylation extraction separately (to get separate coverage files), and then merge the coverage files afterwards (either using a script, or e.g. in a tool like SeqMonk)

It seems that the 3rd suggestion was suitable for me. I am not sure whether merging *.deduplicated.bismark.cov.gz in these 10 directories was enough.

**Comment by FelixKrueger** [comment]
If I am not mistaken, taking 1 sample and splitting it into 10 before preparing the libraries would make the 10 samples technical replicates. These could be used to give you an idea how consistent your library prep method and the sequencing is. 

Taking a single sample, splitting it into 10 sub-files, and running them separately will likely decrease the sequencing depth, and also the duplication rate. 

In both scenarios, the samples would need to be **deduplicated as a single file**. I will depend on the rate of duplication in your sample how big of an effect your treatment will make, but I would argue that merging at the coverage file level is not the right thing to do here.

**Comment by AlisaGU** [comment]
These are the duplication rates of 10 files
![image](https://github.com/FelixKrueger/Bismark/assets/38097726/01e3baef-0852-46f4-a84f-d8eec4b3974f)

**Comment by FelixKrueger** [comment]
That's fine, but they should not be deduplicated separately if they come from the same sample. You can deduplicate all 10 samples in one go by using:

```
deduplicate_bismark --multiple *bismark_pe.bam
```

**Comment by AlisaGU** [comment]
Thanks, I got it!
