### ISSUE TITLE
What to do in a case of low mapping efficiency ?

### ISSUE THREAD

**Issue by Emm2342** [FelixKrueger/Bismark#618]
Hi ! 

I have WGBS samples that I trimmed with `trim_galore` and mapped on its reference genome (a mitochondrial genome) using `bismark` (Bowtie 2). I also mapped the samples on two _spike-ins_ : lambda (unmethylated) and pUC19 (fully methylated).

Based on the lambda _spike-in_, 3 samples have good bisulfite conversion efficiency (> 98%) and 5 samples have very poor conversion efficiency (as low as 70%)... The methylation calls are present on both CpGs and CpH, but the rate is higher on CpH for all 5 samples. The results for the pUC19 _spike-in_ were good (methylation rate >97%), but again, the CpH methylation rate was kind of high, considering that methylation should only be on CpGs.

Re-doing the experiment is impossible for us. Is there any way to recover and analyse these samples while filtering the false-positives ? 

I don't want to calculate DMRs, and I have for premises that 1) CpH methylation could be present in the mitochondrial genome, and 2) methylation rates/patterns could vary among samples.

Thanks !!

**Comment by FelixKrueger** [comment]
Hi @Emm2342 

I am afraid it is difficult for me to give you a clear cut answer to your questions. Like with so many other experiments (e.g. spike-ins for ChIP-seq, ERCC for RNA-seq etc), using spike-ins as conversion controls in bisulfite experiments is notoriously very unpredictable. Not sure if spike-ins have ever worked consistently for anyone? I remember having had Lambda spike-in "controls" that suggested the conversion rate had been only 70%, when clearly it must have been 99% or higher (as evidenced by non-CG methylation in the genome of between 0.3 and 1%...). I think fairly often, in such cases people chose to ignore that they had included spike-ins in the first place, and continue with their analyses.

I wanted to link some thoughts about [bisulfite conversion and spike-ins](http://felixkrueger.github.io/Bismark/faq/conversion_efficiency/#bisulfite-conversion-rate-considerations), and secondly a  nice paper where the authors clearly showed that structural properties of mitochondria were responsible for the seemingly elevated levels of methylated mitochondrial DNA: [Evidence Suggesting Absence of Mitochondrial DNA Methylation](https://pubmed.ncbi.nlm.nih.gov/29163634/)

I hope that you might find some inspiration in there?

**Comment by FelixKrueger** [comment]
I am not sure whether `methylation_consistency` is the right script as it assesses how consistent the calls are within a read. You might want to look at `filter_non_conversion` (or similar), as this aims to remove reads that seemingly resisted the bisulfite conversion. I do agree though, you should approach the data analysis very carefully.
