### ISSUE TITLE
concordant/discordant PE reads for CpG status?

### ISSUE THREAD

**Issue by avilella** [FelixKrueger/Bismark#62]
Hi,

Is there any code in bismark to know how many CpGs are the same state within an aligned paired-end read? For example:

- Given a pair of reads, which contain 2 or more CpGs, we would call the pair of reads concordant if all CpGs are converted, or if all CpGs are unconverted.
- Given another pair of reads, which contain 2 or more CpGs, we would call the pair of reads discordant if there is a mix of converted and unconverted assayed CpGs within the read.

Is there code in bismark to do this? If not, where would this fit best?

**Comment by FelixKrueger** [comment]
There is currently no code in Bismark itself doing this, but we've written separate scripts to go through BAM files and sort the reads that are fully methylated, fully unmethylated (or as a percentage) or display mixed methylation. I can send you the scripts if you are interested.

**Comment by avilella** [comment]
Sounds like a plan. If it's a single script maybe simply copy+paste on
https://gist.github.com/ ?

I can refer to it once you send me the link.

A.

**Comment by FelixKrueger** [comment]
Here is a link:
https://gist.github.com/FelixKrueger/aef704b6edfb20bf8854accfc3fd4e8a

**Comment by FelixKrueger** [comment]
It might need to be modified for paired-end data but it should be a start.

**Comment by avilella** [comment]
Got it. It basically looks for `Z` or `z` in the bam entries and puts the
read into different buckets depending on the counts.

Would the PE mode basically look also at `Z` or `z` in Read 2 or would it
need some other tweaking?

**Comment by FelixKrueger** [comment]
as it stands it would work read by read I guess, so for paired-end you would need to read another line, and then decide if you wanted to add both together (you could just join the two) or treat them individually, and then sort both lines at the same time.
