### ISSUE TITLE
CX report

### ISSUE THREAD

**Issue by ceromova** [FelixKrueger/Bismark#620]
Hello,

I am trying to run DMRcaller and it can run a [Bismark CX report ](https://support.illumina.com/help/BaseSpace_App_MethylSeq_help/Content/Vault/Informatics/Sequencing_Analysis/Apps/swSEQ_mAPP_MethylSeq_CytosineReport.htm). The required fields are: chromosome, position, strand, number of reads from methylated DNA, total number of reads, Cytosine context (CG, CHG or CHH) and trinucleotide context (were, instead of H, the exact nucleotide is included). I used this command: 

`Bismark/bismark_methylation_extractor --CX_context --bedGraph --cytosine_report --comprehensive --no_overlap --paired-end --gzip --parallel 8 --genome_folder Bismark/index/ -o outdir bam_file`

But this creates three files with different cytosine context. How can I get the CX report as the DMRcaller input?

Thank you!

**Comment by FelixKrueger** [comment]
This command should create CpG, CHH and CHG files (the output of the methylation extractor), then use all of these files for the bedGraph generation (resulting in a `.cov.gz` file), and finally also yield a file ending `.CX_report.txt.gz`, which should be the file you are looking for.

**Comment by ceromova** [comment]
The output of the command is the following one:

10311_1_val_1_bismark_bt2_pe.bedGraph.gz
10311_1_val_1_bismark_bt2_pe.bismark.cov.gz
10311_1_val_1_bismark_bt2_pe.M-bias.txt
10311_1_val_1_bismark_bt2_pe_splitting_report.txt
CHG_context_10311_1_val_1_bismark_bt2_pe.txt.gz
CHH_context_10311_1_val_1_bismark_bt2_pe.txt.gz
CpG_context_10311_1_val_1_bismark_bt2_pe.txt.gz

But none of them contains the information in the format mentioned [here](https://support.illumina.com/help/BaseSpace_App_MethylSeq_help/Content/Vault/Informatics/Sequencing_Analysis/Apps/swSEQ_mAPP_MethylSeq_CytosineReport.htm)
