### ISSUE TITLE
Seeking assistance with the "bismark_methylation_extractor" command.

### ISSUE THREAD

**Issue by dianzhiyong** [FelixKrueger/Bismark#622]
Dear Bismark author,

I am currently using Bismark for the analysis of bsseq data. The code I am using is as follows: "bismark_methylation_extractor --gzip --genome_folder $genomepath --no_overlap -o ./methylation --parallel 20 --scaffolds $bam". However, the program stops after giving the following output:

” Processed lines: 59500000
Processed lines: 60000000
Finished processing child process. Exiting..
Processed lines: 60000000
Finished processing child process. Exiting..
Processed lines: 60000000
Finished processing child process. Exiting..  “

It seems that the analysis did not complete.
Any assistance would be greatly appreciated.
Best regards
zhiyongdian

**Comment by FelixKrueger** [comment]
I believe you asked the script to spawn 20 processes, of which 19 are 'child' processes, and one is the parent. Typically, once all 19 child processes exited successfully (the parent process will wait for the children to finish) the parent process will tidy up and finish the process. It might very well have finished by now?

**Comment by dianzhiyong** [comment]
thanks doctor
The analysis is not complete and no error messages are being displayed.
now i demonstrate the code and the results show below ：
$ ls methylation 

CHG_context_H1.deduplicated.txt.gz
CHH_context_H1.deduplicated.txt.gz
CpG_context_H1.deduplicated.txt.gz
H1.deduplicated_splitting_report.txt
H1.deduplicated_splitting_report.txt.10
H1.deduplicated_splitting_report.txt.10.mbias
H1.deduplicated_splitting_report.txt.12
H1.deduplicated_splitting_report.txt.12.mbias
H1.deduplicated_splitting_report.txt.14
H1.deduplicated_splitting_report.txt.14.mbias
H1.deduplicated_splitting_report.txt.4
H1.deduplicated_splitting_report.txt.4.mbias

#############
$ tail nohup.out 
Processed lines: 60000000
Finished processing child process. Exiting..
Processed lines: 59500000
Processed lines: 59500000
Processed lines: 60000000
Finished processing child process. Exiting..
Processed lines: 60000000
Finished processing child process. Exiting..
Processed lines: 60000000
Finished processing child process. Exiting..

######
There is no issue with the test data provided in the Bismark software package.
What do you think is the issue?

**Comment by dianzhiyong** [comment]
the operating system is  almallinux

**Comment by FelixKrueger** [comment]
Hmm, when you type `top` is the process still running? Maybe it got killed somehow? Can you scan the nohup file for other anomalies? I would probably just rerun in and try to reduce the number of parallel processes, to maybe 2 or 4 in the first instance?

**Comment by dianzhiyong** [comment]
ok, thank you. I will follow your advice and rerun it
