### ISSUE TITLE
output file has only R1 pair end

### ISSUE THREAD

**Issue by JHBI115** [FelixKrueger/Bismark#623]
Hi , 
I'm new to this , so this may be a silly question. 
My bismark BAM output file do not contain any R2 reads when I do samtools view. 
The *bismark_bt2_PE_report.txt clearly states:
 "Bismark report for: S1_R1.fq.gz and S1_R2.fq.gz 
  ...
  Sequence pairs analysed in total: .."
So it know the input is pairend. 

What am I missing ? 

Thank you so much! 
C

**Comment by FelixKrueger** [comment]
When using `samtools view` on Bismark BAM files you should see two lines with the **very same** read ID on consecutive lines, the first one being R1, the second one being R2. Do you see something else?

**Comment by JHBI115** [comment]
Hi Felix, thank you so much  for your fast reply!

Oh, yes you are right! I just got confused because they both have the R notation (_1:N:0,  instead on _2:N:0 for R2), but the flags will tell one is R2:

One more question:

I run on paired:
 - trimgalore with defaults and then bismark : mapping efficiency = 17.1%
 - trimgalore --non_directional --rrbs and then bismark --non_directional :  mapping efficiency = 42.13%

Then run on separate on R1 and R2:

R1 - directional : 23.6 %
R2 - directional : 33.0%
R2 - nondirectional: 53.8%

Would this tell me that the data is nondirectional and I should use only R2 in the analysis ?

Thank you so much !
Corina


________________________________

**Comment by FelixKrueger** [comment]
Hmm, this is tricky to answer from just these numbers. What would help more would be to know which type of library preparation was performed, and if possible could you attach (or send via email) the the FastQC HTML reports of the raw data (i.e. untrimmed)?

**Comment by JHBI115** [comment]
Thank you so much Felix! We finally got the answer from the sequencing lab and they are non-directional.

Best,
Cori
________________________________

**Comment by FelixKrueger** [comment]
quite often non-directional library preps require additional trimming from the 5' end, still happy to take a look at your FastQC profiles if that helps. Good luck otherwise!
