### ISSUE TITLE
XM:z tag , which one is Unknown context ?

### ISSUE THREAD

**Issue by chufuyun** [FelixKrueger/Bismark#627]
SO this is my knowledge about XM:Z tag
<img width="858" alt="image" src="https://github.com/FelixKrueger/Bismark/assets/88359419/964a9c1d-41fa-46c8-a338-26fd0dd6cf3e">
but I didn't see any U/u in my bam files ? (using grep to check and not find these characters)Is there any parameter could add this information? THX 
<img width="1429" alt="image" src="https://github.com/FelixKrueger/Bismark/assets/88359419/ee2c8a4f-6fcd-4c40-832d-93e5bff8658d">

**Comment by chufuyun** [comment]
Because I want to extract a C>T bam files(just for my project),so the u is kind of important ; and i have a basic question about the mapping step, if one of my reads has no C>T mutation or G>A mutation, when it mapping to C>T or G>A genome, it should not be mapped , so why there are so many reads contain H/X/Z (they are mismatches when mapping to converted genome)

**Comment by FelixKrueger** [comment]
Regarding the question about reads in Unknown context: This may happen if:
- the genome reference contains the letter `N` (immediately downstream, either one or two bp downstream of the C)
-  you've got insertions in the read, right adjacent to a Cytosine (in terms of context calling these inserted bases are getting filled in with 'X', which are subsequently called as Unknown.

Regarding your second question, I am afraid I'm not sure what you are actually asking. Could you give an example?

**Comment by chufuyun** [comment]
Thank you so much Felix! 
Regarding the second question ,  I have already figured it out .
But still have a question about the strandness, so if i'm using the following strand specific library method : 
<img width="306" alt="image" src="https://github.com/FelixKrueger/Bismark/assets/88359419/95f46174-32c8-4324-a615-0678332b2c9d">
And I checked that R1 stands for my strand orientation;
so if i want to split the bam file to OT and OB ;
can i using the flags to split ?
<img width="704" alt="image" src="https://github.com/FelixKrueger/Bismark/assets/88359419/166ef8c7-574f-40fe-be16-87d082cecd7b">
and by default OT and OB 's strand orientation is R1 in bismark ?

**Comment by FelixKrueger** [comment]
Yes, that's correct. Sorry for the late reply
