### ISSUE TITLE
High levels of non CpG methylation

### ISSUE THREAD

**Issue by mikulenaitev** [FelixKrueger/Bismark#628]
Hi,
I have used bismark to extract methylation information of K562 cells. Obtained results show unexpectedly high methylation levels in the context of CHG and CHH. I would like to ask you for your opinion - what could be the cause of such data, no conversion at all?

<img width="581" alt="Screenshot 2023-09-26 at 11 50 50 AM" src="https://github.com/FelixKrueger/Bismark/assets/142809432/9aa82125-34b0-4038-b303-dd7450f8d876">

Thank you in advance

**Comment by FelixKrueger** [comment]
I would agree, this looks pretty much like what you would expect if you take normal genomic, i.e. non bisuflite-converted data....
