### ISSUE TITLE
CRISPRoff methylation specificity analysis

### ISSUE THREAD

**Issue by abearab** [FelixKrueger/Bismark#633]
Hi @FelixKrueger I deeply appreciate all your helps so far!! (i.e. https://github.com/FelixKrueger/TrimGalore/issues/174, etc.)

Now I have another question for DMR analysis and manhattan plots to show CRISPRoff methylation specificity. I started with reanalysis of published data from [here](https://www.cell.com/cell/pdf/S0092-8674(21)00353-6.pdf) and I used below tiling parameters to find DMRs. How do you think I can recapitulate something like **Fig 2. E** (see below)? I think I need to switch to base level comparison but I would love to hear expert advice! Thanks in advance.
```R
tileMethylCounts(CpG_meth,win.size=500,step.size=100,cov.bases=0)
```
This is my current result:

<img width="600" alt="image" src="https://github.com/FelixKrueger/Bismark/assets/53412130/e60a47ed-3591-4916-9538-83ba701be52d">

___
and here is the **Fig 2. E** from [here](https://www.cell.com/cell/pdf/S0092-8674(21)00353-6.pdf)

<img width="600" alt="image" src="https://github.com/FelixKrueger/Bismark/assets/53412130/8eb198f8-2152-4434-b97c-bc0364b43c35">

> **(E)** A Manhattan plot displaying differentially methylated CpGs between cells treated with CRISPRoff and CLTA-targeting or NT sgRNAs (30 days post-transfection) analyzed by WGBS. Red dots represent CpGs that gained DNA methylation in targeting sgRNA cells and blue dots represent CpGs that gained DNA methylation in NT sgRNA cells. The arrow denotes the genomic position of CLTA.

**Comment by abearab** [comment]
Actually, it's more a [methylKit](https://github.com/al2na/methylKit) question – @al2na

**Comment by abearab** [comment]
I keep failing to load huge `bam` files to R using `methylKit::processBismarkAln` so I'm aiming to follow [this](https://compgenomr.github.io/book/extracting-interesting-regions-differential-methylation-and-segmentation.html#working-with-large-files) and use `methylKit::methRead` with these options: `pipeline = 'bismark', context = "CpG", resolution = "base", dbtype = "tabix"`.

Now I would like to know what I need to use from `bismark_methylation_extractor` 

I'm mainly not sure which of these output files I need to use in `methylKit::methRead`:
```
OT    –  original top strand
CTOT  –  complementary to original top strand
OB    –  original bottom strand
CTOB  –  complementary to original bottom strand
```
@FelixKrueger any advice would be appreciated 👀

**Comment by FelixKrueger** [comment]
again, I am afraid you should post this over at the methylKit page....

**Comment by abearab** [comment]
Agreed 👍
(however, I think a tiling window plus a smaller step size will give me what I want here)
