### ISSUE TITLE
(ERR): bowtie2-align exited with value 141

### ISSUE THREAD

**Issue by avilella** [FelixKrueger/Bismark#64]
I ran bismark with some human data on a machine like this:

```
CPU: 1% (36 cores) * Memory: 2688/60387MB * Storage: 2874GB free * Net: 0↓/0↑MBps
dxpy/0.200.3 (Linux-3.13.0-95-generic-x86_64-with-Ubuntu-12.04-precise)
```

The options for bismark 0.14.5 were:

```
++ bowtie_path=/home/dnanexus/bowtie2-2.2.5
++ opts=' --phred33-quals --multicore 5 -p 4 input_indexes/ --path_to_bowtie /home/dnanexus/bowtie2-2.2.5 --bowtie2 -q  -1 CEGX-47-4_S4_L001_R1_001.1.cutA.fq.gz -2 CEGX-47-4_S4_L001_R1_001.1.cutA2.fq.gz'
++ ./bismark_v0.14.5/bismark --phred33-quals --multicore 5 -p 4 input_indexes/ --path_to_bowtie /home/dnanexus/bowtie2-2.2.5 --bowtie2 -q -1 CEGX-47-4_S4_L001_R1_001.1.cutA.fq.gz -2 CEGX-47-4_S4_L001_R1_001.1.cutA2.fq.gz
```

Started at 2.44PM...

Then about 4 minutes later, it threw this error (printed twice on the screen):

```
(ERR): bowtie2-align exited with value 141
(ERR): bowtie2-align exited with value 141
```

And then at 2.53PM produced this alignment report, and exited with an error:

```
Final Alignment report
======================
Number of paired-end alignments with a unique best hit: 586479
Sequence pairs analysed in total:   792544
Mapping efficiency: 74.0%
Final Cytosine Methylation Report
=================================
Sequence pairs with no alignments under any condition:  171559
Total number of C's analysed:   14515835
Sequence pairs did not map uniquely:    34506
Total methylated C's in CpG context:    299642
Sequence pairs which were discarded because genomic sequence could not be extracted:    2
Total methylated C's in CHG context:    23560
Total methylated C's in CHH context:    76601
Number of sequence pairs with unique best (first) alignment came from the bowtie output:
Total methylated C's in Unknown context:    0
CT/GA/CT:   292918  ((converted) top strand)
GA/CT/CT:   0   (complementary to (converted) top strand)
Total unmethylated C's in CpG context:  379434
GA/CT/GA:   0   (complementary to (converted) bottom strand)
CT/GA/GA:   293559  ((converted) bottom strand)
Total unmethylated C's in CHG context:  3350293
Number of alignments to (merely theoretical) complementary strands being rejected in total: 0
Total unmethylated C's in CHH context:  10386305
Total unmethylated C's in Unknown context:  0
C methylated in CpG context:    44.1%
C methylated in CHG context:    0.7%
C methylated in CHH context:    0.7%
Can't determine percentage of methylated Cs in unknown context (CN or CHN) if value was 0
792544 reads; of these:
  792544 (100.00%) were paired; of these:
    461165 (58.19%) aligned concordantly 0 times
    292329 (36.88%) aligned concordantly exactly 1 time
    39050 (4.93%) aligned concordantly >1 times
41.81% overall alignment rate
792544 reads; of these:
```

Any ideas?

**Comment by FelixKrueger** [comment]
I'm afraid this is some kind of Bowtie2 error but I don't know exactly what's going on. Googling the error message I found a few things about permission problems (e.g. https://github.com/bowhan/piPipes/issues/11) or gtf file problems in Tophat runs. 
Do you get a higher number of mapping reads when you align the same files on a different machine? 
What happens when you update both Bowtie2 and Bismark to the latest versions (you are more than 5 releases behind)?

**Comment by FelixKrueger** [comment]
Haven't heard anything back in 2 months, closing.

**Comment by ray1919** [comment]
I have encountered the same error, after looking into the data, I found there is some too short reads which caused such errors. I hope this might help.

**Comment by dktanwar** [comment]
I have encountered exactly same error while using `bowtie2 version 2.3.4.1`

**Comment by githubjiangweiling** [comment]
(ERR): bowtie2-align exited with value 1
I have also encountered exactly same problem.Is there someone can help me?

**Comment by tAndreani** [comment]
same error with hisat2

**Comment by FelixKrueger** [comment]
Hmm, is there anything else in the on screen text that might give a hint? Do you have a enough system resources for the command and genome you are using? Which version of all software are you using? Googling the error message I found that this could be specific to certain versions of Bowtie2, e.g. here: https://www.biostars.org/p/229653/.

**Comment by dgescher** [comment]
Hi! I just installed the latest version of bismark and bowtie2 at ubuntu (I'm using a windows pc). When starting bismark with 2 files, after some seconds this error appears. The genetic files are okay, I already analyzed them with bismark on my macbook without any error message. Unfortunately, the macbook needs too long time, that's why I had to change to a windows-based PC, which has really much power.  Bowtie2 was running well with the recommended test files. 
bowtie2-align-s version 2.2.5 64-bit 
bismark version: v0.23.1

Protokoll: all steps runned well before:
(...) "now starting a Bowtie 2 paired-end alignment for CTread1GAread2CTgenome", found first alignment (shown), 
"Now starting a  Bowtie 2 paired-end alignment for CTread1GAread2GAgenome" found first alignement (shown), 
">>>Writing  bisulfite mapping results to ...."
(ERR): bowtie2-align exited with value 141
(ERR): bowtie2-align exited with value 141

Is there any idea what I can do? Thanks very much!!!!

**Comment by FelixKrueger** [comment]
Hmm, can you get Bowtie2 to run on its own? A command for the first 100K reads should be something like:

```
bowtie2 --no-unal -u 100000 -x Bisulfite_Genome/CT_conversion/BS_CT input_file_trimmed.fq.gz | samtools view -bS - > output.bam
```

**Comment by dgescher** [comment]
> HI Felix, thank you so much, since I use bismark for the first time. I commanded the first part: 
bowtie2 --no-unal -u 100000 -x Bisulfite_Genome/CT_conversion/BS_CT -1 input_file1a 2 input_file1b 
it was running through without problems:
100000 (100.00%) were paired; of these:                                                                         60741 (60.74%) aligned concordantly 0 times                                                                   21153 (21.15%) aligned concordantly exactly 1 time                                                            18106 (18.11%) aligned concordantly >1 times                                                                  ----                                                                                                         
60741 pairs aligned concordantly 0 times; of these:                                                             3934 (6.48%) aligned discordantly 1 time                                                                    ----                                                                                                          
56807 pairs aligned 0 times concordantly or discordantly; of these:                                             113614 mates make up the pairs; of these:                                                                       97001 (85.38%) aligned 0 times                                                                                4526 (3.98%) aligned exactly 1 time                                                                           12087 (10.64%) aligned >1 times                                                                      
51.50% overall alignment rate      
  
Concerning the 2. part of the command ("samtools view -bS - > output.bam"), I still try to understand how to adopt with my data. 
Is there a similar command that I can use for bismark?  Is there a risk to lose information, if I use this modified command? 
Many thanks!!!

**Comment by FelixKrueger** [comment]
The sample command was to get an idea whether Bowtie 2 is working (which it is), and whether the BAM file generation using `samtools` is working. Is Samtools installed on your system? Bismark will itself run a command internally very similar to this. The next question is, how much RAM do you have available on your system?

**Comment by dgescher** [comment]
Samtools is installed, but I'm not familiar with sh and command lines. 
It has 64 RAM (should be enough)

**Comment by FelixKrueger** [comment]
You shouldn't really need to know more about sh and command lines, Bismark will simply call the samtools to generate a BAM file.  If you can type on the command line: `samtools --version`, do you see the version information? If not, you should install it.

And yes I would agree, 64GB is plenty.

**Comment by dgescher** [comment]
samtools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory

-> perhaps this is an owner conflict, like it was with other directories. I will check that - or what do you think?

**Comment by FelixKrueger** [comment]
I bet that's it, sounds like something with dynamic libraries and samtools. Can you try and google this issue?

**Comment by dgescher** [comment]
yes, I need to leave our conversation for now, so sorry, but I will answer tomorrow.

**Comment by dgescher** [comment]
Hi Felix, meanwhile bismark runs well, but I have the impression that I don't earn the full information results. In the report only the first 150bp are pictured and especially I cannot find any localization mapping of my sample within the genome. How can I proof what was going wrong? Thanks a lot!

**Comment by AbRawoof** [comment]
> I bet that's it, sounds like something with dynamic libraries and samtools. Can you try and google this issue?

I also had the same problem.. After updating the version of both samtools and bowtie2... bingo ... the error goes off.. and program working fine.

**Comment by 2909ft** [comment]
Hello! I am also getting this same error. I am using the most recent versions of bowtie2 (2.5.4) and samtools (1.21) and I have 64 Gb of RAM. Bismark is 0.24.2. I have the same output as mentioned in this thread:
"now starting a Bowtie 2 paired-end alignment for CTread1GAread2CTgenome", found first alignment (shown),
"Now starting a Bowtie 2 paired-end alignment for CTread1GAread2GAgenome" found first alignement (shown),
">>>Writing bisulfite mapping results to ...."
(ERR): bowtie2-align exited with value 141
(ERR): bowtie2-align exited with value 141

It runs for a couple of minutes and then it exits with this error. Any ideas on what might be happening? Thank you very much!
