### ISSUE TITLE
bsseq::read.bismark() input - reference error

### ISSUE THREAD

**Issue by desmodus1984** [FelixKrueger/Bismark#640]
Hi,

I am trying to use methylSig, and I am reading the input bedgraph files created with methylDackel. I used the same reference file for all of them, processed with the same commands. I was told that I can use bsseq::read.bismark() function to read my files, but when I read them 
```
pData<-read.csv("~/Downloads/methylKit/meth.ctrl.max.csv")
cc.max <- c("V00001_methyldackel_CpG.bedGraph", "V00750_methyldackel_CpG.bedGraph",
              "V00796_methyldackel_CpG.bedGraph", "V00861_methyldackel_CpG.bedGraph", "V01425_methyldackel_CpG.bedGraph",
              "V01712_methyldackel_CpG.bedGraph", "V01926_methyldackel_CpG.bedGraph", "V01947_methyldackel_CpG.bedGraph",
              "V02055_methyldackel_CpG.bedGraph",
              "V00021_methyldackel_CpG.bedGraph", "V00314_methyldackel_CpG.bedGraph",
              "V00315_methyldackel_CpG.bedGraph", "V00759_methyldackel_CpG.bedGraph",
              "V00760_methyldackel_CpG.bedGraph",...
ctrl.max = bsseq::read.bismark(
  files = cc.max,
  colData = pData,
  rmZeroCov = TRUE,
  strandCollapse = FALSE)
```
I get the error
Warning message:
In .merge_two_Seqinfo_objects(x, y) :
  Each of the 2 combined objects has sequence levels not in the other:
  - in 'x': NW_022883010.1
  - in 'y': NW_022883351.1, NW_022883409.1
  Make sure to always combine/compare objects based on the same reference
  genome (use suppressWarnings() to suppress this warning).

I repeat, I used the same reference file for all my files.

Thank you very much;

**Comment by FelixKrueger** [comment]
I am afraid this should really be asked elsewhere (maybe on the methylSig page?)

**Comment by desmodus1984** [comment]
I did ask the author of methylSig and I was told to post this question for Bismark:
"This is a bsseq::read.bismark() issue, not an issue with methylSig."
