### ISSUE TITLE
Mapping Efficiency is low

### ISSUE THREAD

**Issue by AmrSaadeldin** [FelixKrueger/Bismark#641]
I am working with whole-genome bisulfite sequencing (WGBS) data, which comprises paired-end sequences with approximately 2 billion reads per sample (1 billion for the forward read and 1 billion for the reverse read). To preprocess the data, I utilized trim-galore! to remove adapters successfully. Subsequently, I performed mapping using Bismark with the following command: This is human samples. 

bismark --genome /storage/projects/amr/WGBS/referencegenome/ --parallel 8 --bowtie2 -1 Lcmerged_R1_val_1.fq.gz -2 Lcmerged_R2_val_2.fq.gz -o 95

In this process, I used a reference genome directory (referencegenome/) which contains both the unmodified reference genome in .fa format and a subdirectory named Bisulfite_Genome/. Inside Bisulfite_Genome/, there are two subdirectories: CT_conversion and GA_conversion. However, I'm uncertain if this directory structure is correct for referencing the genome in the analysis.

While the mapping process was completed without errors, I encountered a challenge related to mapping efficiency. Across multiple parallel files and samples, I consistently observed a mapping efficiency of approximately 56%. Given that the sequencing data is expected to be of high quality and depth, I am seeking guidance on how to address and improve this issue.

Any insights or recommendations to enhance the mapping efficiency in this WGBS analysis would be greatly appreciated.

![Screenshot 2023-12-03 at 19 23 42](https://github.com/FelixKrueger/Bismark/assets/86196891/89c48a0d-0d54-4e38-8c5e-c883c8d5dddd)

**Comment by AmrSaadeldin** [comment]
Thank you so much for your fast response! appreciated! I will send you part of the data and get back to you later today! thank you so much.

**Comment by AmrSaadeldin** [comment]
Hi @FelixKrueger, I just sent you the details via email. Thank yo so much for your efforts!

**Comment by FelixKrueger** [comment]
I believe this is all sorted. For the record, this was Accel swift data, and with appropriate trimming (`--clip_r1 10 --clip_r2 15 --threeprime_clip_r1 10 --three_prime_clip_r2 10`; https://felixkrueger.github.io/Bismark/bismark/library_types/) the mapping efficiency went up to 85%.
