### ISSUE TITLE
 Bismark Version: v0.24.2 Issue

### ISSUE THREAD

**Issue by NeGomics** [FelixKrueger/Bismark#651]
I am executing the bismark on paired end data using the command: bismark --multicore 12 path/genome_dir --output_dir path/alignment -1 <(gunzip -c "filename_R1.fq.gz") -2 <(gunzip -c "filename_R2.fq.gz")

Error: Child process terminated with exit signal: '65280'

Child process terminated with exit signal: '65280'

Child process terminated with exit signal: '65280'

Child process terminated with exit signal: '3072'

Child process terminated with exit signal: '3072'

Child process terminated with exit signal: '3072'

Child process terminated with exit signal: '3072'

Terminating. Not all child processes successfully finished. at /home/cloud-user/anaconda3/bin/bismark line 602, <IN2> line 106663392.

I request for the help to resolve the issue. I have 32 core processor. I am heartily thankful to you. 

When I am running in shell script then it is not reading R2 the script is:

#!/bin/bash

# Define the number of CPU cores to use
num_cores=12  # Adjust accordingly based on your system's specifications

# Define the path to the genome directory
genome_dir="/mount/raw_data/goel/wgbs_methylation/methylation_new/genome_T2T_Y_2023"

# Define the path to the output directory for alignment results
alignment_results_dir="/mount/raw_data/goel/wgbs_methylation/methylation_new/alignment_result_T2T"

# Define the path to the temporary directory
temp_dir="/mount/raw_data/goel/wgbs_methylation/methylation_new/temp_t2t"

# Loop through each pair of forward and reverse reads files in the folder
for f in /mount/raw_data/goel/wgbs_methylation/methylation_new/trimmed_data/*_R1_001_val_1.fq.gz; do
    # Extract the file name (without extension)
    filename=$(basename -- "$f")
    filename_no_ext="${filename%.*}"

    # Extract the sample ID from the filename
    sample_id="${filename_no_ext%%_*}"

    # Perform Bismark alignment
    bismark --multicore "$num_cores" --non_directional --phred33-quals --no_overlap --temp_dir "$temp_dir" "$genome_dir" --output_dir "$alignment_results_dir/$sample_id" -1 <(gunzip -c "$f") -2 <(gunzip -c "/mount/raw_data/goel/wgbs_methylation/methylation_new/trimmed_data/${filename_no_ext}_R2_001_val_2.fq.gz")
done

**Comment by FelixKrueger** [comment]
This is very much related to #652.

The command used for Bismark contains a lot of stuff, just mentioning a few things here:

- `--multicore "$num_cores"`: be a little careful... 
- `--non_directional`: Is the library really non directional? (most libraries aren't...)
- `--phred33-quals`: is the default
-  `--no_overlap`: Is not a Bismark option (only for methylation extractor, and there it is the default)
- I have never seen the `<(gunzip -c "$f")` before, it is also not necessary as Bismark reads gzipped files

Good to see that the files appear to be trimmed with Trim Galore!
