### ISSUE TITLE
Incomplete Documentation regarding expected outputs

### ISSUE THREAD

**Issue by VasLem** [FelixKrueger/Bismark#653]
There is nowhere in the website, or the docs, information about the output of each step. I am currently developing a pipeline and I want to know the exact output that I expect from each step. Please update the documentation.

**Comment by FelixKrueger** [comment]
Hmm, I am not quite sure I agree... The documentation is here: https://felixkrueger.github.io/Bismark/

And here is an example. Is there anything specific you are referring to?
<img width="1067" alt="Screenshot 2024-02-15 at 23 07 32" src="https://github.com/FelixKrueger/Bismark/assets/5870509/44530c03-d6da-4f21-8c95-ae04e05a32cf">

**Comment by VasLem** [comment]
Hi, thanks for the quick reply. Indeed there exists quite extensive documentation for the files produced by bismark_methylation_extractor, as well as the format of the bam files. However documentation is missing for the outputs of:

- bismark_genome_preparation
- bismark
- deduplicate_bismark

Given that the output filenames are pretty much constant, they should be documented somewhere. For example, bismark_genome_preparation is creates a folder Bisulfite_Genome, which then is populated by two subfolders with known names. This information resides only in the code.

**Comment by VasLem** [comment]
Nice, yes, now it is clear! Thanks for the quick updates! :)

**Comment by VasLem** [comment]
I noticed that the output files names are also missing from [here[(https://felixkrueger.github.io/Bismark/options/methylation_extraction/), can you update that part as well?

**Comment by FelixKrueger** [comment]
I have added some examples as well now. Good luck!
