### ISSUE TITLE
Is it necessary to execute command (samtools sort -n) before run Deduplication?

### ISSUE THREAD

**Issue by changchuanjun** [FelixKrueger/Bismark#658]
@FelixKrueger, hello! Thanks for your excellent work on the Bismark, this software facilitates community to study DNA methylation.
 I have finished Alignment step with the command:

for i in $(cat sample.txt)
do
    ~/software/Bismark/bismark \
        --bowtie2 \
        -X 1000 \
        --score_min L,0,-0.6 \
        --genome_folder /lns \
        -1 ./${i}_1_val_1.fq.gz \
        -2 ./${i}_2_val_2.fq.gz \
        --output_dir ./${i}_bismark_bowtie2_p1_X1000score_min_L_0_0.6_20240204 \
        1>./${i}_bowtie2_X1000score_min_L_0_0.6.log 2>&1
done
 
**and got a BAM output like this**
![1709288788518](https://github.com/FelixKrueger/Bismark/assets/155738984/10066610-8a9a-4ef7-93d8-82866d9d4eb7)

Next step is Deduplication.
Now I have a question is it necessary to execute command (samtools sort -n) before run Deduplication?
or  can I execute the Deduplication command(deduplicate_bismark mybamfile.bam) directly?
I am looking forward to your reply sincerely.

**Comment by FelixKrueger** [comment]
You can run the deduplication directly, files are output with R1 and R2 directly following each other. Good luck!

**Comment by changchuanjun** [comment]
The sentence ：
files are output with R1 and R2 directly following each other.

is hard to understand for me. Can you describe it thoroughly.Thanks！

---Original---
From: "Felix ***@***.***&gt;
Date: Fri, Mar 1, 2024 19:27 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [FelixKrueger/Bismark] Is it necessary to execute command(samtools sort -n) before run Deduplication? (Issue #658)




 
You can run the deduplication directly, files are output with R1 and R2 directly following each other. Good luck!

**Comment by changchuanjun** [comment]
> files are output with R1 and R2 directly following each other.

@FelixKrueger ， this file refers to the bam file, the result of Alignment step ?

**Comment by changchuanjun** [comment]
Thanks! I get it.
