### ISSUE TITLE
Can deduplicate_bismark (the component of bismark) script distinguish single-end/paired-end BAM/SAM Bismark files directly ?

### ISSUE THREAD

**Issue by changchuanjun** [FelixKrueger/Bismark#659]
@FelixKrueger,
In deduplicate_bismark script instruction part, It persents can detect single-end/paired-end BAM/SAM Bismark files automatically.
![image](https://github.com/FelixKrueger/Bismark/assets/155738984/986477a1-89af-4b2c-bf2a-56c0a491addb)

But when I ran this script using paired-end BAM/SAM Bismark files,It detect it a single-end BAM/SAM Bismark file. It is very weird.
![image](https://github.com/FelixKrueger/Bismark/assets/155738984/a4bbb92d-5bbd-4315-8ddc-8cbfde065225)

So I am confused that whether deduplicate_bismark (the component of bismark) script distinguish single-end/paired-end BAM/SAM Bismark files directly.Or when I ran deduplicate_bismark script with the -p parameter?

**Comment by FelixKrueger** [comment]
Which version of `deduplicate_bismark` are you using?

**Comment by changchuanjun** [comment]
@FelixKrueger 
Deduplicator Version: v0.24.2
![image](https://github.com/FelixKrueger/Bismark/assets/155738984/786f2566-65cb-4e3d-90fe-253629bdfecf)

**Comment by changchuanjun** [comment]
@FelixKrueger 
Deduplicator Version: v0.24.2
![image](https://github.com/FelixKrueger/Bismark/assets/155738984/786f2566-65cb-4e3d-90fe-253629bdfecf)

**Comment by FelixKrueger** [comment]
Ok thanks. It appears that the top message should probably just say Bismark output files, and lose the '--single-end'. I'll have that changed.

The last line of the screen-shot above says: "Treating file as paired-end file". So that is good, this is the important bit.

**Comment by changchuanjun** [comment]
OK. 
So Can deduplicate_bismark script distinguish single-end/paired-end BAM/SAM Bismark files directly? 
Or when I ran deduplicate_bismark script with the parameter --paired ?

**Comment by FelixKrueger** [comment]
either is fine. The distinction is that the auto-detection work on a per file basis, whereas `-p` works for all files supplied.
