### ISSUE TITLE
Minimum conversion efficiency for filter_non_conversion

### ISSUE THREAD

**Issue by gevro** [FelixKrueger/Bismark#663]
Hi,
Is there a minimum conversion efficiency below which filter_non_conversion will not be advisable or useful to use? For example is 95% conversion efficiency useful to use filter_non_conversion? Or 92.5%, or 90%? At some point, I assume it will not be advisable.

Thanks

**Comment by FelixKrueger** [comment]
I don't think there is a generally accepted 'minimum conversion efficiency', it really is more in the eye of the beholder.
