### ISSUE TITLE
reads with a single basepair indel not mapping

### ISSUE THREAD

**Issue by DJ-Raving** [FelixKrueger/Bismark#67]
Hi, I've been using Bismark for awhile to map some bisulfite PCR resequencing data, and overall performance has been good.  Lately I've been attempting to improve the performance of my resequencing assay by looking at the unmapped reads from the analysis, and that's how I came across this issue.

It generally seems to be a problem whereby Bismark is rejecting reads with a single 1 bp gap in them, despite the fact they otherwise perfectly map.

My understanding is that using Bismark with bowtie2 should enable gapped alignment, but if I'm incorrect please let me know.

The analysis steps I performed were as follows:

I have been performing mapping with bismark 0.14.2  with the following settings, using  bowtie2 v2.1.0
bismark --bowtie2 -N 1 -L 15 --bam  --un -p 4 --score L,-0.6,-0.6 --non_directional $genomeIndex reads.fq  -o results.bismark/

 I've also tested v0.16 and gotten similar results.

To better get a sense of the sequence composition of the unmapped reads (as well as to simplify the analysis) I have collapsed them using fastx_collapser

Next, I have analyzed the collapsed, unmapped reads by using bowtie2 v2.1.0 and mapping the unmapped reads from the above analysis against an index made from the CT/GA converted fasta files that bismark_genome_preparation makes.

bowtie2 -x ~/indexes/ -f --sam-no-hd  -S bp_nextseq12.sam -p 4 -U bp_nextseq12.fa --un bp_nextseq12.bt2_unmapped.fa --no-unal

I then examined the first few mapped reads.  It seems that in many/most cases, there is a single gap in the alignment, but otherwise the read maps perfectly, as shown by the CIGAR strings from the snippet of the SAM file below:

28-626  0   EGL638_hg19_chr19_21769009_CT_converted 163 42  76M1D31M
19-986  0   EGL003_hg19_chr19_30017284_CT_converted 4026    42  45M1D80M
48-373  0   EGL638_hg19_chr19_21769009_CT_converted 163 42  102M1I7M
45-388  0   EGL003_hg19_chr19_30017284_CT_converted 4026    42  33M1I91M
62-289  0   EGL860_hg19_chr11_268641_GA_converted   66  0   94M2I4M
56-324  16  EGL860_hg19_chr11_268641_GA_converted   66  0   94M2I4M
98-177  0   EGL005_hg19_chr10_135050105_CT_converted    482 42  81M1D27M
88-189  16  EGL460_hg19_chr7_35292855_GA_converted  1095    42  55M1D68M

I have also visualzed the mapped reads in IGV and can confirm they map perfectly, other than the 1bp indel

In this case, the concern is that the unmapped reads could cause the methlyation values to be misreported.  For example, read 19-986 in the above example represents 986 reads which map perfectly to the unmethylated strand.  As this is resequencing data, my thought is that including an extra 1000 unmethylated reads in the final analysis could potentially lower the overall methlyation values reported for this region by a significant amount.  

As a side note, I have also tried analyzing the unmapped reads from the bismark 0.14.2 analysis with an older version of bismark, and it seems to handle some (although not all) of these residual unmapped reads better.

bismark_v0.8.0/bismark --bowtie2 -p 4 --score L,-0.6,-0.6 --non_directional  $genomeIndex reads.fq
# Final Alignment report

Sequences analysed in total:    431891
Number of alignments with a unique best hit from the different alignments:      49439
Mapping efficiency:     11.4%

Remapping with bismark 0.14.2 yields no mapped reads using similar settings

I have also tried adjusting the score function to be lower (i.e., --score L,-2.0, -2.0), but Bismark did not successfully map the remaining unmapped reads

Am I correct in thinking that Bismark should be mapping a read that is otherwise perfect except for a single 1bp gap?  Or is gapped alignment problematic, despite using bowtie2?

I can provide a link to the index and original read data if you would like to try and replicate the analysis.

Many thanks
DJ

**Comment by FelixKrueger** [comment]
Hi DJ,
Thanks for reporting this issue and sorry for not getting back to you earlier. Yes I would agree that simple InDels should not be the cause of reads getting rejected, but this often has to do with read orientation, both reads starting and ending at the same position (see option `--dovetail`) or the like.

 I would indeed like to take a look at the issue myself if that would be OK? I could send you an email (felix.krueger@babraham.ac.uk) with the details of an FTP site unless you've got other means to share the data.

Best, Felix

**Comment by DJ-Raving** [comment]
Hi Felix, thanks for the reply.  My turn to apologize for the delay in getting back to you.

I've been playing around and this seems to be partially related to the use of -N 1 -L 15 in Bismarks options.  Removing these from the command line has improved mapping somewhat.  Regardless, I'll follow up with an email to you shortly to arrange sending you the data so you can replicate my observation yourself.

Thanks

**Comment by FelixKrueger** [comment]
That's interesting, I've once heard about drastic changes in mapping efficiency when the `-N 1` was specified instead of using the defaults but I never found time to follow this up... I'll wait for further details via email.

**Comment by FelixKrueger** [comment]
Haven't heard back from this for a while, closing. Can always re-open if I hear back.
