### ISSUE TITLE
Analyzing spike in control performance

### ISSUE THREAD

**Issue by gevro** [FelixKrueger/Bismark#677]
Hi, What is the best practice for conversion efficiency analysis of spike in control DNAs?

Would the aligned BAM file be split to include only or exclude reads aligned to spike in contigs, and run methylation extraction separately on each pf the BAM files?

**Comment by gevro** [comment]
My other thought is to run bismark 3 separate times: once with the species genome, once with positive control spike-in fasta, and once with a negative control spike-in fasta. That way I can make separate methylation coverage reports for each and the species genome report won't be confounded by the spike-ins.

**Comment by FelixKrueger** [comment]
You can either include the two (positive and negative control) spike-ins as additional 'chromosomes' for the main alignment, or, as you suggested, run them individually. In the latter case, the alignments should be *very* fast as the genomes are only tiny.
