### ISSUE TITLE
Correcting low % methylated regions

### ISSUE THREAD

**Issue by gevro** [FelixKrueger/Bismark#679]
Hi,
My % methylation histogram (plotted by methylKit, attached) is not fully bimodal. I'm curious if there is a common practice or would it make sense to manually transform sites with < 10% or < 20% or some other cutoff methylation to 0%? Since one could assume that low % methylated regions are actually unmethylated regions that were not fully bisulfite converted.

Thanks
[M10.methylStats.pdf](https://github.com/user-attachments/files/15955640/M10.methylStats.pdf)

**Comment by FelixKrueger** [comment]
I don't think this is common practice at all, at least not for bulk data. You need to think about these values over different regions of measurement as the average over several (hundred/thousand/million?) cells. You can say that regions between 20 and 80% of methylation appear more variable (and therefore maybe more interesting?) than regions that are just always methylated or unmethylated.

**Comment by gevro** [comment]
I see, thanks, makes sense.

**Comment by gevro** [comment]
Perhaps this explains also why we do not see a more drastically bimodal distribution. Because these are from bull tissues with many different cell types.

**Comment by FelixKrueger** [comment]
That is indeed most likely the case
