### ISSUE TITLE
Expected unique alignment %

### ISSUE THREAD

**Issue by gevro** [FelixKrueger/Bismark#681]
Hi,
What is the expected unique alignment %? For example, for NEB EM-seq libraries, I'm seeing only 60 - 75%, which seems low to me. This is with max insert size set to 1000.

**Comment by FelixKrueger** [comment]
This depends on several factors, naming just a few: the genome of interest and its repeat content, SE or PE, read length, contamination (adapter dimers, other organisms, out of control spike-ins, PhiX etc), and appropriate trimming. For human libraries with ~100bp reads PE I would probably expect around 80%, for mouse probably a little less

**Comment by gevro** [comment]
Thanks!
