### ISSUE TITLE
Parent process: Failed to build index

### ISSUE THREAD

**Issue by yangjw1996** [FelixKrueger/Bismark#682]
Hi，I am using bismark v0.24.2，and bowtie2 v2.2.5. My reference genome is less than 1 Mb, when I use bismark_genome_preparation to tansform and index the reference, I alway get this problem: Failed to build index.

Here is the bug report: 
Error: Encountered internal Bowtie 2 exception (#1)
Command: bowtie2-build --wrapper basic-0 --threads 4 -f genome_mfa.CT_conversion.fa BS_CT
Parent process: Failed to build index

The CT_conversion and GA_conversion of reference is created correctly, but the indexprocess is somehow wrong.

If I use 'bowtie2-build --wrapper basic-0 --threads 4 -f genome_mfa.CT_conversion.fa BS_CT' to directly index the transformed reference, It can't be indexed, either.  It will report 'bowtie2-build: unrecognized option --threads'.

How can I solve this problem?

**Comment by FelixKrueger** [comment]
When you type `bowtie2-build --version`, what do you get? It could be that your version of Bowtie2 is too old to accept the `--threads` parameter? 

`bowtie2-build -f genome_mfa.CT_conversion.fa BS_CT`

inside the conversion folders should work though.

**Comment by yangjw1996** [comment]
Hi，I have solved the problem by changing to .Bowtie2 v2.5.4, which works well with bismark v0.24.2. Thanks to your advice!

At the beginning, I installed bismark through conda，and the bowtie2 v2.2.5 was installed automatically along with  bismark. Now I am sure bowtie2 v2.2.5 does support '--thread' argument in bowtie2-build.  I guess anyone installing bismark through conda should pay attention to the version of bowtie2.

**Comment by FelixKrueger** [comment]
Excellent, I am glad it works now. 

Just for your interest, I believe the conda recipe for Bismark only has the requirement that Bowtie 2 runs, so it doesn't necessarily install an (outdated) version of Bowtie 2 itself. Maybe you had a previous installation of a fairly old version of Bowtie 2 that satisfied the requirement? In any case, let's close this issue as it all works now.
