### ISSUE TITLE
Issue with Perl in filter_non_conversion

### ISSUE THREAD

**Issue by edogiuili** [FelixKrueger/Bismark#688]
Hi, 

While running the bismark docker container **biocontainers/bismark:0.24.0--hdfd78af_0** (but the same issue arises also with the latest container versions), I face the following issue when using _filter_non_conversion_ : 

``` 
/usr/local/bin/filter_non_conversion: /usr/bin/perl: bad interpreter: No such file or directory
```

I think the problem might be due to the script shabang, which is still #!/usr/bin/perl as it was years ago before [this commit](https://github.com/FelixKrueger/Bismark/commit/611bdb9a80783faa4ca3401068d13ce30a5f3114) . Do you think it might be possible to change it for this script as well?

Thanks!

**Comment by FelixKrueger** [comment]
Can you change the sheebang line to `#!/usr/bin/env perl`?

**Comment by FelixKrueger** [comment]
Oh I see, the shebang got changed back. When did that happen? ...

**Comment by FelixKrueger** [comment]
It should now be fixed in the `dev` version

**Comment by edogiuili** [comment]
Thanks!
