### ISSUE TITLE
ambiguous results in .bam file

### ISSUE THREAD

**Issue by iranianuser** [FelixKrueger/Bismark#690]
Hello dear Felix,
My bismark alignment has finished after 2 days at least ... and I got my report file:

**Bismark report for**: /home/ubuntu/SRR4298802_1_val_1.fq and /home/ubuntu/SRR4298802_2_val_2.fq (version: v0.24.2)
Bismark was run with Bowtie 2 against the bisulfite genome of /home/ubuntu/ with the specified options: -q --score-min L,0,-0.2 --ignore-quals --no-mixed --no-discordant --dovetail --maxins 500
Option '--directional' specified (default mode): alignments to complementary strands (CTOT, CTOB) were ignored (i.e. not performed)

Final Alignment report
======================
Sequence pairs analysed in total:	171035784
Number of paired-end alignments with a unique best hit:	134138933
Mapping efficiency:	78.4% 
Sequence pairs with no alignments under any condition:	24141588
Sequence pairs did not map uniquely:	12755263
Sequence pairs which were discarded because genomic sequence could not be extracted:	65

Number of sequence pairs with unique best (first) alignment came from the bowtie output:
CT/GA/CT:	67092253	((converted) top strand)
GA/CT/CT:	0	(complementary to (converted) top strand)
GA/CT/GA:	0	(complementary to (converted) bottom strand)
CT/GA/GA:	67046615	((converted) bottom strand)

Number of alignments to (merely theoretical) complementary strands being rejected in total:	0

Final Cytosine Methylation Report
=================================
Total number of C's analysed:	4942715100

Total methylated C's in CpG context:	158205936
Total methylated C's in CHG context:	4297893
Total methylated C's in CHH context:	15038457
Total methylated C's in Unknown context:	8857

Total unmethylated C's in CpG context:	54614523
Total unmethylated C's in CHG context:	1027108410
Total unmethylated C's in CHH context:	3683449881
Total unmethylated C's in Unknown context:	1240748

C methylated in CpG context:	74.3%
C methylated in CHG context:	0.4%
C methylated in CHH context:	0.4%
C methylated in Unknown context (CN or CHN):	0.7%

Bismark completed in 1d 21h 5m 45s

________________
but when I want to open the .bam file I see this:
[Doc1.docx](https://github.com/user-attachments/files/16467545/Doc1.docx)

why I cant see my bam file??

thanks

**Comment by FelixKrueger** [comment]
I suppose you are now using Samtools to look at the BAM file?

**Comment by iranianuser** [comment]
Oops!
I thought bam files are not human-readable 
and this is why I can't see the bam file 

sorry for my simple question cause I'm so stressed for my work

**Comment by FelixKrueger** [comment]
they are indeed not human readable, but `samtools view -h file.bam | head` will convert them for you
