### ISSUE TITLE
deduplicate_bismark problem

### ISSUE THREAD

**Issue by iranianuser** [FelixKrueger/Bismark#691]
hello again

I used deduplicate_bismark and I got these results:

```
Total number of alignments analysed in SRR4298802_1_val_1_bismark_bt2_pe.bam:	134138868
Total number duplicated alignments removed:	2279406 (1.70%)
Duplicated alignments were found at:	2212334 different position(s)

Total count of deduplicated leftover sequences: 131859462 (98.30% of total)
```
what was wrong with my process?
my reads are PE (WGBS) and RG hg38

Thank you for answering my questions patiently

**Comment by FelixKrueger** [comment]
Why would you assume that anything is wrong with your process? This looks like a well diverse library.

**Comment by iranianuser** [comment]
well I thought there must be at least some duplicated alignments removed

**Comment by FelixKrueger** [comment]
Well:

> Total number duplicated alignments removed:	2279406 (1.70%)

That's not nothing?
