### ISSUE TITLE
index of genome faulty or non-existant

### ISSUE THREAD

**Issue by iranianuser** [FelixKrueger/Bismark#692]
Hi
I finished my bismark analysis to the end and got my bedGraph. but when I start the workflow for the second paired-end reads just like the previous sample,  I see this message in bismark run:

`The Bowtie 2 index of the C->T converted genome seems to be faulty or non-existant ('BS_CT.2.bt2'). Please run the bismark_genome_preparation before running Bismark`

this was repeated for all of my Index files. why? Is it necessary to run   `bismark_genome_preparation` again even if we did it before?
this is the code:
`perl bismark --genome_folder /path/ -1 first.gz -2 second.gz`
 the path for reference genome includes bisulfite converted genome and the original one. 

thank you for your advice

**Comment by FelixKrueger** [comment]
The indexing process is a one-off, and you do not need to perform it for every single sample. Can you link check the path to the index very carefully, and link the exact command and the error message you see on screen here if it fails again?

**Comment by iranianuser** [comment]
This is the exact command I used and the error message :

`ubuntu@dr:~/Bismark-0.24.2$ perl bismark --genome_folder **/home/ubuntu/** -1 **/home/ubuntu/SRR4298804_1_val_1.fq.gz** -2 **/home/ubuntu/SRR4298804_2_val_2.fq.gz**
Bowtie 2 seems to be working fine (tested command 'bowtie2 --version' [2.4.4])
Output format is BAM (default)
Alignments will be written out in BAM format. Samtools found here: '/usr/bin/samtools'
Reference genome folder provided is /home/ubuntu/       (absolute path is '/home/ubuntu/)'
The Bowtie 2 index of the C->T converted genome seems to be faulty or non-existant ('BS_CT.1.bt2'). Please run the bismark_genome_preparation before running Bismark
The Bowtie 2 index of the C->T converted genome seems to be faulty or non-existant ('BS_CT.2.bt2'). Please run the bismark_genome_preparation before running Bismark
The Bowtie 2 index of the C->T converted genome seems to be faulty or non-existant ('BS_CT.3.bt2'). Please run the bismark_genome_preparation before running Bismark
The Bowtie 2 index of the C->T converted genome seems to be faulty or non-existant ('BS_CT.4.bt2'). Please run the bismark_genome_preparation before running Bismark
The Bowtie 2 index of the C->T converted genome seems to be faulty or non-existant ('BS_CT.rev.1.bt2'). Please run the bismark_genome_preparation before running Bismark
The Bowtie 2 index of the C->T converted genome seems to be faulty or non-existant ('BS_CT.rev.2.bt2'). Please run the bismark_genome_preparation before running Bismark
The Bowtie 2 index of the G->A converted genome seems to be faulty or non-existant ('BS_GA.1.bt2'). Please run bismark_genome_preparation before running Bismark
The Bowtie 2 index of the G->A converted genome seems to be faulty or non-existant ('BS_GA.2.bt2'). Please run bismark_genome_preparation before running Bismark
The Bowtie 2 index of the G->A converted genome seems to be faulty or non-existant ('BS_GA.3.bt2'). Please run bismark_genome_preparation before running Bismark
The Bowtie 2 index of the G->A converted genome seems to be faulty or non-existant ('BS_GA.4.bt2'). Please run bismark_genome_preparation before running Bismark
The Bowtie 2 index of the G->A converted genome seems to be faulty or non-existant ('BS_GA.rev.1.bt2'). Please run bismark_genome_preparation before running Bismark
The Bowtie 2 index of the G->A converted genome seems to be faulty or non-existant ('BS_GA.rev.2.bt2'). Please run bismark_genome_preparation before running Bismark

Couldn't find a traditional small Bowtie 2 index for the genome specified (ending in .bt2). Now searching for a large index instead (64-bit index ending in .bt2l)...
64-bit large genome Bowtie 2 index found...
FastQ format assumed (by default)

Input files to be analysed (in current folder '/home/ubuntu/Bismark-0.24.2'):
/home/ubuntu/SRR4298804_1_val_1.fq.gz
/home/ubuntu/SRR4298804_2_val_2.fq.gz
Library is assumed to be strand-specific (directional), alignments to strands complementary to the original top or bottom strands will be ignored (i.e. not performed!)
Setting parallelization to single-threaded (default)

Summary of all aligner options: -q --score-min L,0,-0.2 --ignore-quals --no-mixed --no-discordant --dovetail --maxins 500
Current working directory is: /home/ubuntu/Bismark-0.24.2

Now reading in and storing sequence information of the genome specified in: /home/ubuntu/

chr 1 (248956422 bp)
chr 2 (242193529 bp)
chr 3 (198295559 bp)
^C
ubuntu@dr:~/Bismark-0.24.2$
`
I stopped the process by myself cause I saw this failure. 
I don't know I understand what you want correctly

**Comment by iranianuser** [comment]
I exactly use the same command I used before. I'm really confused.

**Comment by FelixKrueger** [comment]
The last message was:

```
64-bit large genome Bowtie 2 index found...
```

So it is all fine, no need to stop it - it was working all along.

**Comment by iranianuser** [comment]
thank you so much 

 I wish you the best
