### ISSUE TITLE
Bismark2summary not working for output with hisat2 

### ISSUE THREAD

**Issue by JingranZhuo** [FelixKrueger/Bismark#693]
Hello Felix,

I ran bismark with hisat2 to align the reads. It seems the output files can be recognize by bismark2summary. The error message is as follows.

`Command error:
  INFO:    Environment variable SINGULARITYENV_TMPDIR is set, but APPTAINERENV_TMPDIR is preferred
  INFO:    Environment variable SINGULARITYENV_NXF_TASK_WORKDIR is set, but APPTAINERENV_NXF_TASK_WORKDIR is preferred
  INFO:    Environment variable SINGULARITYENV_NXF_DEBUG is set, but APPTAINERENV_NXF_DEBUG is preferred
  No Bismark/Bowtie2 single-end BAM files detected
  No Bismark/Bowtie2 paired-end BAM files detected
  No Bismark/HISAT2 single-end BAM files detected
  No Bismark/HISAT2 paired-end BAM files detected`

Thanks!

**Comment by FelixKrueger** [comment]
Hi Jingran,

I just simulated a few files for both single-end and paired-end scenarios, and it all worked just fine:

```
├── PE
│   ├── bismark_summary_report.html
│   ├── bismark_summary_report.txt
│   ├── sample1_R1_bismark_hisat2_pe.bam
│   ├── sample1_R1_bismark_hisat2_PE_report.txt
│   ├── sample1_R1.fastq.gz
│   ├── sample1_R2.fastq.gz
│   ├── test2_R1_bismark_hisat2_pe.bam
│   ├── test2_R1_bismark_hisat2_PE_report.txt
│   ├── test2_R1.fastq.gz
│   └── test2_R2.fastq.gz
└── SE
    ├── bismark_summary_report.html
    ├── bismark_summary_report.txt
    ├── SE_test1_bismark_hisat2.bam
    ├── SE_test1_bismark_hisat2_SE_report.txt
    ├── SE_test1.fastq.gz
    ├── SE_test2_bismark_hisat2.bam
    ├── SE_test2_bismark_hisat2_SE_report.txt
    ├── SE_test2.fastq.gz
    ├── SE_test3_bismark_hisat2.bam
    ├── SE_test3_bismark_hisat2_SE_report.txt
    ├── SE_test3.fastq.gz
    ├── simulated_bismark_hisat2.bam
    ├── simulated_bismark_hisat2_SE_report.txt
    └── simulated.fastq.gz
```

Which version are you running?

**Comment by JingranZhuo** [comment]
Hello Felix,


I am using  bismark/0.24.2.


The error occurs both when I run it locally or via our nextflow pipelines. https://github.com/vonMeyennLab/nf_methylseq.


Best regards,

Jingran



________________________________

**Comment by FelixKrueger** [comment]
We are in a bit of a pickle now, since v0.24.2 correctly identifies both SE and PE files generated by Bismark/HISAT2. Did you rename your files by any chance? Are they in a different format than the ones above?

**Comment by JingranZhuo** [comment]
Hello Felix,

Here I have the filenames like this: 

(sample_name)_GRCm39_bismark_ht2_pe.bam

Best,
Jingran

**Comment by FelixKrueger** [comment]
Alright, it's the filenames resulting from your nextflow workflow then.

```
 @detected_files = <*bismark_hisat2.bam>;  # SE HISAT2
...
 @detected_files = <*bismark_hisat2_pe.bam>; # PE HISAT2
```

a simple `rename s/_ht2_/_hisat2_/` in your results file might do the trick. 

By the way, MultiQC should also be a good option for capturing the output.

**Comment by JingranZhuo** [comment]
Thank you Felix
