### ISSUE TITLE
SNAKEMAKE wrapper: How to add multicore?

### ISSUE THREAD

**Issue by kenji-yt** [FelixKrueger/Bismark#706]
Asking here as I don't know where else:

I would like to use parallel processing with the snakemake wrapper for Bismark. 
From the wrapper documentation it did not become clear what I should do. I suspect we need to fill something in params, probably related to "--multicore: bismark parallel execution" but I am unsure how to pass this to the wrapper. 

Any help would be appreciated. 
-Kenji

**Comment by FelixKrueger** [comment]
I'll leave this here for someone else to comment as I am not a snake make person myself. Good luck!

**Comment by kenji-yt** [comment]
It seems the issues I had was due to the incompatibility between --basename and --multicore. Without basename it should be possible to use multiple cores with: extra=f'--multicore {workflow.cores}', whith some modifications needed at the output specification. 

This issue can therefore be closed. However I would like to ask if it is possible to predict how many cores a Bismark alignment will use? This would be very useful when allocating resources. I read in the manual that giving it 4 cores with --multicore results in 20 cores used for the GRCm38 mouse genome. This seems therefore to be dependant on the genome? Can this be restricted? 

Thank you in advance.

**Comment by FelixKrueger** [comment]
Bismark itself will use 1 core at pretty much 100%, then each thread of aligner will also use 1 core (at least, if you use `-p` this will change) at 100%, so 2 cores for default (directional) or PBAT alignments, or 4 cores for non-directional alignments. and then various small processes such as reading from and writing to gzip filehandles, but they tend to have a ver low usage. So I would say 3-5 cores at high usage, and ~10-15GB of RAM for single-core. For each level of `--parallel` you need to multiply these numbers. Does that make sense?

**Comment by kenji-yt** [comment]
Yes it makes perfect sense. Thank you very much!
