### ISSUE TITLE
Speed up merge_individual_BAM_files

### ISSUE THREAD

**Issue by MilosCRF** [FelixKrueger/Bismark#707]
Hi Felix,

I’m currently running Bismark on AWS using 192 CPUs. Everything is running at lightning speed except for merging the temporary BAM files. It seems that the merging process is not utilizing multiple cores with the current `bismark` settings.

Do you know of any way to speed up this step? Perhaps adding `-@ $num_threads` to the `samtools `command that is likely handling the merging?

**Comment by FelixKrueger** [comment]
`samtools cat` does have a `-@` flag, but I am not sure if this would at any point break the order of Read1/Read2 following each other directly (which would break downstream processed). Do you have possibility to find the command that merges the BAM files and try out adding increasing values of `-@`?

**Comment by MilosCRF** [comment]
Thank you, Felix.
Yes, I can definitely test it. However, I couldn't find `samtools cat` in Bismark's main script. Isn't the merge accomplished by samtools view at line 1427?

`open (OUT,"| $samtools_path view -bSh 2>/dev/null - > ${output_dir}${merged_name}") or die "Failed to write to $merged_name: $!\n";`

**Comment by FelixKrueger** [comment]
I think you are right, I must have confused this with something else (e.g. deduplication of multiple files).

Can you try to try a different number of threads? E.g. 2, 4, 8? We only have to be mindful how this would affect resource allocation for e.g. nf-core workflows, but this would be a downstream problem.

**Comment by MilosCRF** [comment]
I apologize for the delay.

I conducted a test by altering the number of CPUs for `samtools view`, and the results are as follows:

**Time Efficiency:** The time required to merge temporary files decreased significantly (1 CPU = ~10 minutes vs. 4 CPUs = ~2.5 minutes). This improvement is substantial as the entire Bismark run originally took about 30 minutes for each of my samples (approximately 50M paired reads).
**CPU Utilization:** Utilizing more than 4 CPUs did not yield any further improvements. I am unsure why this is the case.  I had 12 temporary BAMs to merge as set by --parallel 12. Despite setting more than 4 CPUs, `samtools view` utilized only up to 4 CPUs for merging.
**Data Integrity:** The methylation profiles remained unaffected by the increase in the number of CPUs used for merging temporary BAMs.

A brief report from the test is attached.
[Bismark_mergeBAMs_multithreading.zip](https://github.com/user-attachments/files/17629523/Bismark_mergeBAMs_multithreading.zip)

**Comment by FelixKrueger** [comment]
Thanks for the testing and the report! That does indeed look good, I have now added `--threads 4` as the default option (this should always fall within the amount of CPUs requested for any multicore run. This will feature in the next release.
