### ISSUE TITLE
question about mapping efficiency

### ISSUE THREAD

**Issue by Marh32** [FelixKrueger/Bismark#709]
Hi,
I'm sorry to bother you. I have a WGBS dataset, and while performing Bismark mapping, I noticed that my mapping efficiency is very low, only 40%. I reviewed your previous suggestions regarding low mapping efficiency and used `--score_min L,0,-0.6`, which improved the mapping efficiency to about 55%, but it's still not satisfactory. Below are the FastQC quality control results for Read1 and Read2. Do you think I need to trim Read2? Thanks in advance for your help
[CP15_01R_1.pdf](https://github.com/user-attachments/files/17495077/CP15_01R_1.pdf)
[CP15_01R_2.pdf](https://github.com/user-attachments/files/17495079/CP15_01R_2.pdf)

**Comment by FelixKrueger** [comment]
This looks like Accel Swift data, and I would recommend trimming the start (and possibly end of both reads, see here for recommendations: https://felixkrueger.github.io/Bismark/bismark/library_types/

This command should sort you out:

```
trim_galore --paired --clip_r1 1 --clip_r2 15 --three_prime_clip_r1 10 --three_prime_clip_r2 10 *fastq.gz
```

All the best! Felix

**Comment by Marh32** [comment]
Thank you for your quick response. I wanted to ask how you determined it was Accel Swift data (I'm not quite sure how to make that determination). Thank you again.

**Comment by Marh32** [comment]
I see. Thank you for your answer. I really appreciate it.

**Comment by FelixKrueger** [comment]
sorry that was a typo, 10, 15, 10, 10 is what is typically used

**Comment by Marh32** [comment]
Got it. Thank you very much for your help.
