### ISSUE TITLE
bismark(err): bowtie2-align died with signal 13 (pipe)

### ISSUE THREAD

**Issue by wydsqgg524** [FelixKrueger/Bismark#712]
[WW-WT-r2.txt](https://github.com/user-attachments/files/17657524/WW-WT-r2.txt)
bismark --bowtie2 -N 1 --un -L 25 -p 4 --quiet --ambiguous -o WW-WT-r2 /data1/jfhe/bismark/reference -1 ../clean_data/2_R1.fq.gz -2 ../clean_data/2_R2.fq.gz 2>WW-WT-r2.txt

**Comment by FelixKrueger** [comment]
This looks like an out-of-memory error, what kind of machine are you running this on?

**Comment by FelixKrueger** [comment]
not heard back, closing.
