### ISSUE TITLE
CX.report Inquiry

### ISSUE THREAD

**Issue by RosalynLiu885** [FelixKrueger/Bismark#714]
Hi Felix,
  I'm new to studying WGBS, so I hope you'll forgive me for my possibly stupid questions. 
  I used bismark_methylation_extractor, I set the parameter as -- cutoff 5, and I was wondering if it was an indicator for data screening. Anyway,  when I scanned the output file `.CX_report.txt.gz`, part of it was shown below, I found that there are still many cases where both the <count methylated> and <count unmethylated> columns are zero, or at least one column is zero.
<img width="373" alt="1731642226819" src="https://github.com/user-attachments/assets/426436aa-0fff-4f1c-947a-b82f66a303c6">
  This really confused me because I took for granted that at least one of the two columns would be greater than five. Please let me know if I am mistaken. 
  Sorry for taking up your time. I look forward to your reply!

**Comment by FelixKrueger** [comment]
Hi @RosalynLiu885 

This is not a stupid question at all, in fact I was somewhat surprised myself :P I have now familiarised myself with the situation, and the explanation is this:

If you use the methylation extractor to define a coverage threshold, this gets passed on to the bedGraph/coverage file generation step (carried out by `bismark2bedGraph`); I would indeed expect every line in the coverage output to have a count of 5 or more.

The coverage file then serves as the input file for `coverage2cytosine`, which generates the CX report. In contrast to coverage files, which are different for each samples, the genome wide CX report has unified structure and reports every single cytosine position in the genome, so if you want to compare different samples with each other you can create a matrix with the same positions for all samples. 

`coverage2cytosine` does have a threshold cutoff option as well (`---coverage_threshold INT`, see `coverage2cytosine --help`), but this is not run by default via the bismark_methylation_extractor route. You now have a few options:

1. Using the coverage file as input (`.cov.gz`) you could run `coverage2cytosine` once more applying a coverage theresshold
2. Using an `awk` command to calculate if columns 4 + 5 in the report are < 5, and filter the output that way
3. you proceed as is and get rid of positions with 0 calls in your next downstream step

As an aside, I personally never use a coverage filter right at the initial processing, as this can typically always be applied later (whereas if you never report positions with a coverage < 5 they will simply never show up in the first place). This depends on your data and personal taste though.
