### ISSUE TITLE
Very low mapping efficiency in Bismark

### ISSUE THREAD

**Issue by cuteelephant** [FelixKrueger/Bismark#715]
Hi, Felix.
I am currently utilizing Bismark to analyze DNA methylation data from the Cyprinus carpio species and am encountering issues with very low mapping efficiencies (1.7%). Could you please provide some guidance on how I might improve these mapping rates? To provide more context, I have not performed any trimming on the raw data. My paired-end 150 bp (PE150) libraries were prepared using the Accel-NGS Methyl-Seq DNA Library Kit. I have sent part of the sequencing data and logs files to your email. In addition, could allotetraploids and repeat sequences up to about 70% be responsible for the low mapping efficiency in this species?
Thank you in advance for your time and assistance.

**Comment by FelixKrueger** [comment]
I just ran a few tests with your data. The quality looked as expected for Accel Swift data, so I trimmed it using our [typical recommendations](https://felixkrueger.github.io/Bismark/bismark/library_types/):

```
trim_galore --clip_r1 10 --clip_r2 15 --three_prime_clip_r1 10 --three_prime_clip_r2 10 --paired *fq.gz
```
Interestingly, this only resulted in ~5% unique alignments using the stringent settings. Relaxing the `--score_min` to `L,0,-0.4` or `L,0,-0.6` increased mapping to ~ 30 or 45%, respectively, indicating that there seem to be quite a few mismatches to the reference sequence. Using local alignments (i.e. not end-to-end), like so:
 
```
bismark --genome genome --local -1 sub1_100k_val_1.fq.gz -2 sub2_100k_val_2.fq.gz
```

Resulted in a mapping efficiency of ~75%. I couldn't detect higher levels of E. coli, PhiX or Lambda. Repetitive alignments accounted for ~10%, so they were not the major cause of low mapping efficiency.

As the reference genome you are using doesn't seem a bit divergent to your samples, I would recomend the above trimming followed by `--local`  alignments

**Comment by cuteelephant** [comment]
Thank you very much for your prompt reply. After reading your reply, I immediately trimmed and mapped the original data according to your parameters. When using the --local parameter, the mapping efficiency was 74.1%, although it was much slower, which was still quite good.
