### ISSUE TITLE
bismark_genome_preparation fails with --genomic_composition

### ISSUE THREAD

**Issue by mike8115** [FelixKrueger/Bismark#74]
Error:
"Failed to read from sequence file Homo_sapiens.hg19.fa No such file or directory"
Input:
`bismark_genome_preparation --verbose --genomic_composition bismark_prepare_genome/`

I suspect that the current working is incorrectly set at line 130 because `get_atomic_frequencies` and `create_bisulfite_genome_folders` do not return with the same working directory, making my .fa file appear missing.

In subroutine `create_bisulfite_genome_folders:484`, `chdir $genome_folder` changes the working directory before returning.
In subroutine `get_atomic_frequencies:354`, the last change directory command occurred in a call at `read_genome_memory:561` as `chdir $parent_dir or die "Failed to move to directory $parent_dir\n"`.

I suspect that the current working directory should be $genome_folder before running `process_sequence_files`. An easy fix is to set the working directory before calling the subroutine.

**Comment by FelixKrueger** [comment]
Thanks for reporting this Mike, I'll make sure to fix it soon.
