### ISSUE TITLE
Obtain methylation level for full length chrM

### ISSUE THREAD

**Issue by Shicheng-Guo** [FelixKrueger/Bismark#75]
Hi All, 

'Chromosomal sequence could not be extracted for NB500986:37:HCKC7BGXY:4:21602:6049:9601_1:N:0:AGGGCATA+CTTCGCCT chrM    1' will be happened if the sequencing is from chrM:1-200. 

Then how to get the methylation level for start/beginning of the chrosome? 

Thanks.

**Comment by FelixKrueger** [comment]
Hi Shicheng,
The easiest solution would be to add to both ends of the mitochondrial sequence like so:
**NN**mitochondrialSequence**NN**
and then re-index the genome. Cheers, Felix
