### ISSUE TITLE
Paired-end HTML report doesn't show plots when data is not deduplicated

### ISSUE THREAD

**Issue by FelixKrueger** [FelixKrueger/Bismark#81]
But why?

**Comment by ewels** [comment]
Some missing data breaking the javascript, disrupting the whole page? Could probably make the page more resilient to these JS glitches by adding a bunch of `try` / `catch` blocks.. (with more useful warnings saying that something has gone wrong).

**Comment by FelixKrueger** [comment]
Yes sounds good. I will just sit here, ready to merge a PR!

**Comment by ewels** [comment]
PR in #82 ;)

**Comment by FelixKrueger** [comment]
Seems to be working again, many thanks.
