### ISSUE TITLE
Add documentation about different library types/kits

### ISSUE THREAD

**Issue by FelixKrueger** [FelixKrueger/Bismark#84]
Something along these lines:

![20161205_110259](https://cloud.githubusercontent.com/assets/5870509/20883144/7a04b8f8-badc-11e6-8fbe-637a05f2b12f.jpg)

**Comment by ewels** [comment]
![whiteboards](https://pics.onsizzle.com/whiteboards-o-o-o-there-re-kabued-7848694.png)

**Comment by FelixKrueger** [comment]
Added in b2c02455c31b2d5daa0a851f67c6ddd0b38566f4.
