### ISSUE TITLE
use --prefix option and deleting multiple temporary BAM files 

### ISSUE THREAD

**Issue by yfwang27** [FelixKrueger/Bismark#87]
Hi, 
I am using Bismark_0_16_3 and the script I used as follow and I have problems deleting multiple temporary sequence files.
`bismark --bowtie2 --ambiguous -p 8 --multicore 2 --ambig_bam --output_dir /analysis/BSseq/Bismark_0_16_3_result/output/ --temp_dir /analysis/BSseq/Bismark_0_16_3_result/output/ --prefix time04_rep1 /rawdata/BSGenome/BSmm9_bt2/ /analysis/BSseq/Bismark_result/mysample_1_trimmed.fq.gz`

The error message shows:
`Deleting temporary sequence files...
Now merging BAM files mysample_1_trimmed.fq.gz.temp.1_bismark_bt2.bam mysample_1_trimmed.fq.gz.temp.2_bismark_bt2.bam into >>> time04_rep1.mysample_1_trimmed_bismark_bt2.bam <<<
Merging from file >> mysample_1_trimmed.fq.gz.temp.1_bismark_bt2.bam <<
[E::hts_open] fail to open file '/analysis/BSseq/Bismark_0_16_3_result/output/mysample_1_trimmed.fq.gz.temp.1_bismark_bt2.bam'
samtools: failed to open "/analysis/BSseq/Bismark_0_16_3_result/output/mysample_1_trimmed.fq.gz.temp.1_bismark_bt2.bam" for reading: No such file or directory
Failed to close filehandle`

Similar error message happens again here too.
`Deleting temporary ambiguous BAM files...
Failed to delete temporary ambiguous BAM file /analysis/BSseq/Bismark_0_16_3_result/output/mysample_1_trimmed.fq.gz.temp.1_bismark_bt2.ambig.bam: No such file or directory
`
I have checked the temp files that created by Bismark and my temp files have the --prefix name, i.e. **time04_rep1**.mysample_1_trimmed.fq.gz.temp.1_bismark_bt2.ambig.bam. Hopefully I didn't make any mistakes that might cause this issue. However, it looks like Bismark adds the prefix name to the temp files but deleting temp files without the prefix. I would like to report this problem to the Bismark team. Thank you very much.

**Comment by FelixKrueger** [comment]
Thanks for reporting this. The issue here was actually that you specified the filenames with full path information in addition to `--prefix`. I have now tried to fix this issue in this commit d1d7ef7b0740ef0add9f47e6ff48e1712a239dab. Can you please clone the latest development version and let me know if it works well in your hands?

Cheers, Felix

**Comment by yfwang27** [comment]
Hi Felix,

Many thanks for your prompt reply and resolving the absolute path issue! Yes, the latest development version worked smoothly. It created the correct merged files and deleted the temp files with the --prefix option. 
Thank you very much and have a nice day.
Regards,
Yi-Fang

**Comment by FelixKrueger** [comment]
Excellent, thanks for the feedback!
