### ISSUE TITLE
bismark_sitrep directory missing in tarball

### ISSUE THREAD

**Issue by shanesturrock** [FelixKrueger/Bismark#90]
bismark2report in the 0.17.0 release tarball doesn't work unless the bismark_sitrep directory is created and bismark_sitrep.tpl etc are moved into it:

bismark_sitrep/bismark_sitrep.tpl
bismark_sitrep/bismark_sitrep.js
bismark_sitrep/highcharts.js
bismark_sitrep/jquery-3.1.1.min.js

Once this change is made, bismark2report runs fine.

**Comment by FelixKrueger** [comment]
Thanks for reporting this, I have now changed the tarball generation and replaced the file on the Babraham Bioinformatics website. Addressed here 83b233bb5ca0e85ea8c21b33794c12e1333eaf0b.
