### ISSUE TITLE
bam2nuc ignors output dir

### ISSUE THREAD

**Issue by lorbaer** [FelixKrueger/Bismark#92]
Hi,
I'm using the bam2nuc script separately after alignment and deduplication.
First report of the script looks good.
Input: >>/home/hpc/wgbs/data/deduplicated/ND5.dedup.bam<<
```
Summary of parameters for nucleotide coverage report:
=====================================================
Output directory:			>/home/hpc/wgbs/data/b2n/<
Parent directory:			>/home/hpc/wgbs/<
Genome directory:			>/home/hpc/wgbs/reference_genome/reference_genome_grcm38_snpv4_NZO_HlLtJ/<
Samtools installation:			>/usr/bin/samtools<
```

However, at the end, the nucleotide stats are saved in the input directory, instead of the output dir.

cheers

**Comment by FelixKrueger** [comment]
Thanks for spotting this, it should work now. Addressed here: eb0624c142e5f38b6e8551b645b881c260fadcf0. Please let me know if you still encounter any problems. Best, Felix

**Comment by lorbaer** [comment]
Hi Felix,
there is still an error.
Using your update leads to some "double pathing", cause your $outfile is holding the complete input path.
I made a work around for my purpose in 
```
my $outfile = $infile;
die "file needs to be in BAM or CRAM format (ending in .bam or .cram). Terminating process...\n" unless ($outfile =~s /(bam|cram)$/nucleotide_stats.txt/);
warn "Printing nucleotide stats to >>$outfile<<\n";
------------------------------------------------------
die "problem in path substitution. Terminating process...\n" unless ($outfile=~s/.*\///);
------------------------------------------------------
open (OUT,'>',"${output_dir}$outfile") or die "Failed to write to file $outfile: $!\n\n";

```
My inputfiles are always given with full path, but this substitution could bring some problems to others.


cheers

**Comment by FelixKrueger** [comment]
Hehe, that's right, I have changed it again so the input file path information is dropped before writing to the outfile (bae850eaca5ca82ab1245e05e5aa2487d4825a40). Hope it's all fine now.
