### ISSUE TITLE
bismark2summary deprecated use in regex

### ISSUE THREAD

**Issue by lorbaer** [FelixKrueger/Bismark#93]
Hi,
the regular expression starting in line 856 state the warning
`unescaped left brace in regex is deprecated`

using perl 5.22
this will cause an error in newer versions of perl
quick change to
`s/\{\{num_samples}}/$num_samples/g;`
for all of the regex will counter this. :)

cheers

**Comment by FelixKrueger** [comment]
I have changed the occurrences of {{ in the regex, thanks for the notice. a481c6eb7bd454dd45de0849af79d6918e6257fc.
